### ISSUE TITLE
Request/Response matching does not comply with spec when using DTLS

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#1]
I would like to follow up on the discussion we started on the [mailing list](https://dev.eclipse.org/mhonarc/lists/cf-dev/msg00574.html) around this issue.

I am creating the issue in the top level repo because we are merging the *californium.core*, *californium.element-connector* and *californium.scandium* repos into this repo soon.

**Comment by jvermillard** [comment]
For reference the ietf-core thread about CoAP RFC limitation on cross epoch
notifications
https://mailarchive.ietf.org/arch/search/?email_list=core&gbt=1&index=oJD7psrLwJj662gjbRku1hGp44c

--
Julien Vermillard

**Comment by sophokles73** [comment]
Thanks for the link, @jvermillard :-)
My understanding is that you have proposed the same thing that we have also discussed on the Californium list, i.e. alternatively matching on session ID and cipher strength, right?
Did you get any further replies on the core list since you originally posted the issue there?

**Comment by sophokles73** [comment]
fixed in 9a0235a0d78b41a1426361e007f8b30e0be819fd
