### ISSUE TITLE
When the device is a certificate handshake，how does the peerIdentity field remain unique?

### ISSUE THREAD

**Issue by cnneillee** [eclipse/californium#1001]
hello，
I have a question。

When the device is a certificate handshake，how does the peerIdentity field remain unique?

Thank You

**Comment by cnneillee** [comment]
Because I need to save DTLSSession based on the uniqueness of the device.

**Comment by boaks** [comment]
> When the device is a certificate handshake

There are two variants, one with a client certificate and one without.
I assume you want to use the client certificate. (And I assume, you use 2.0.x)
In that case the `peerIdentity` is a `X509CertPath` instance, containing the x.509 certificate and certificate path of the other peer. It will be as unique, as that x.509 certificate used is unique (means, if you change the certificate or reuse it in some devices, it's not longer unique).

> Because I need to save DTLSSession based on the uniqueness of the device.

I'm not sure, that smells for mixing up things. The "peerIdentity" is usually intended to be "long term" stable (couple of months, depending on the x.509 expiring date). The DTLSSession is much more short living (a couple of hours or days) . Therefor the DTLSSession has a session ID.

I'm not sure, if you want to save the java class `DTLSSession` or also the `DTLSConnectionState`. If it's only the `DTLSSession` without the `DTLSConnectionState` there is already a solution, the `SessionTicket` and the `SessionCache` or `ClientSessionCache`.

**Comment by cnneillee** [comment]
Yes, I am talking about 2.0.
Thank you for your answer.

I have another question.
If peerIdentity is a X509CertPath instance，When I get the parameter through peerIdentity.getName(), this parameter represents the subject of a certificate. The subject of different device certificates may be the same?

Thank You

**Comment by boaks** [comment]
That depends on your x.509 deployment. I would strongly recommend, not to reuse such a client certificate. But some scenarios use the "client certificate" as a "tenant certificate", means, all devices are using the same "tenant certificate" as "client certificate" and the pass in a device ID somehow else (not standardized).

**Comment by cnneillee** [comment]
Thank you very much for your answer.

**Comment by boaks** [comment]
Your welcome. 
(So do you plan to save the `DTLSConnectionState` as well? Is your use case to restart that endpoint?)
