### ISSUE TITLE
COAP retry after receiving 5.03 error code from device with Max-age Option

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#1009]
Version of Californium- 2.0.0-M12

Hi,

I sent COAP Observe request to device , device responded back with 5.03 error with option set Max_age 70 second . 

Does COAP retry is implemented in Californium after max-age expire ?
 
Thank you .

**Comment by boaks** [comment]
The "retry" is not just a retransmission, it requires a new request and is therefore delegated to the application layer. So, **no**, californium doesn't retry that request.

**Comment by madhushreegc** [comment]
ok . Thank you .
