### ISSUE TITLE
double-checked locking issue.

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/californium#101]
Hi,

We have scanned the Calofornium core code with HP fortify tool and found few issues. Please let us know your views on these two issues.

1. Double Checked Locking(13):-

> The method setRetransmissionHandle() in Exchange.java relies on double-checked locking, an incorrect idiom that does not achieve the intended effect.
> 
> 
> Explanation:
> 
> Many talented individuals have spent a great deal of time pondering ways to make double-checked locking work in order to improve performance. None have succeeded.
> 
> Example 1: At first blush it may seem that the following bit of code achieves thread safety while avoiding unnecessary synchronization.
> 
> 
> if (fitz == null) {
>   synchronized (this) {
>     if (fitz == null) {
>       fitz = new Fitzer();
>     }
>   }
> }
> return fitz;
> 
> 
> The programmer wants to guarantee that only one Fitzer() object is ever allocated, but does not want to pay the cost of synchronization every time this code is called. This idiom is known as double-checked locking.
> 
> Unfortunately, it does not work, and multiple Fitzer() objects can be allocated. See The "Double-Checked Locking is Broken" Declaration for more details [1].
> [16:49:47] sneha shruti: Recommendations:
> 
> Synchronization is probably less expensive than you believe. In many cases, the best thing to do is to use the most straightforward solution.
> 
> Example 2: The code in Example 1 could be rewritten in the following way:
> 
> 
> synchronized (this) {
>   if (fitz == null) {
>     fitz = new Fitzer();
>   }
>   return fitz;
> }
> 
> 
> 
> References:
> 
> [1] D. Bacon et al., The "Double-Checked Locking is Broken" Declaration, http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
> 
> [2] LCK10-J. Use a correct form of the double-checked locking idiom, CERT, https://www.securecoding.cert.org/confluence/display/java/LCK10-J.+Use+a+correct+form+of+the+double-checked+locking+idiom
> 
> [3] Standards Mapping - Common Weakness Enumeration, CWE ID 609
> 
> [4] Standards Mapping - Payment Card Industry Data Security Standard Version 3.0, Requirement 6.5.6
> 
> [5] Standards Mapping - Payment Card Industry Data Security Standard Version 3.1, Requirement 6.5.6
> 
> [6] Standards Mapping - Payment Card Industry Data Security Standard Version 3.2, Requirement 6.5.6
> 
> 

2. Insecure Randomness(4):-

Details:-

> The random number generator implemented by nextInt() cannot withstand a cryptographic attack.
> 
> 
> Explanation:
> 
> Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in security-sensitive context.
> 
> In this case the function that generates weak random numbers is nextInt() in Matcher.java at line 90.
> 
> Computers are deterministic machines, and as such are unable to produce true randomness. Pseudorandom Number Generators (PRNGs) approximate randomness algorithmically, starting with a seed from which subsequent values are calculated.
> 
> There are two types of PRNGs: statistical and cryptographic. Statistical PRNGs provide useful statistical properties, but their output is highly predictable and forms an easy to reproduce numeric stream that is unsuitable for use in cases where security depends on generated values being unpredictable. Cryptographic PRNGs address this problem by generating output that is more difficult to predict. For a value to be cryptographically secure, it must be impossible or highly improbable for an attacker to distinguish between it and a truly random value. In general, if a PRNG algorithm is not advertised as being cryptographically secure, then it is probably a statistical PRNG and should not be used in security-sensitive contexts, where its use can lead to serious vulnerabilities such as easy-to-guess temporary passwords, predictable cryptographic keys, session hijacking, and DNS spoofing.
> 
> Example: The following code uses a statistical PRNG to create a URL for a receipt that remains active for some period of time after a purchase.
> 
> 
> String GenerateReceiptURL(String baseUrl) {
>     Random ranGen = new Random();
>     ranGen.setSeed((new Date()).getTime());
>     return (baseUrl + ranGen.nextInt(400000000) + ".html");
> }
> 
> 
> This code uses the Random.nextInt() function to generate "unique" identifiers for the receipt pages it generates. Because Random.nextInt() is a statistical PRNG, it is easy for an attacker to guess the strings it generates. Although the underlying design of the receipt system is also faulty, it would be more secure if it used a random number generator that did not produce predictable receipt identifiers, such as a cryptographic PRNG.
> [16:52:43] sneha shruti: Recommendations:
> 
> When unpredictability is critical, as is the case with most security-sensitive uses of randomness, use a cryptographic PRNG. Regardless of the PRNG you choose, always use a value with sufficient entropy to seed the algorithm. (Values such as the current time offer only negligible entropy and should not be used.)
> 
> The Java language provides a cryptographic PRNG in java.security.SecureRandom. As is the case with other algorithm-based classes in java.security, SecureRandom provides an implementation-independent wrapper around a particular set of algorithms. When you request an instance of a SecureRandom object using SecureRandom.getInstance(), you can request a specific implementation of the algorithm. If the algorithm is available, then it is given as a SecureRandom object. If it is unavailable or if you do not specify a particular implementation, then you are given a SecureRandom implementation selected by the system.
> 
> Sun provides a single SecureRandom implementation with the Java distribution named SHA1PRNG, which Sun describes as computing:
> 
> "The SHA-1 hash over a true-random seed value concatenated with a 64-bit counter which is incremented by 1 for each operation. From the 160-bit SHA-1 output, only 64 bits are used [1]."
> 
> However, the specifics of the Sun implementation of the SHA1PRNG algorithm are poorly documented, and it is unclear what sources of entropy the implementation uses and therefore what amount of true randomness exists in its output. Although there is speculation on the Web about the Sun implementation, there is no evidence to contradict the claim that the algorithm is cryptographically strong and can be used safely in security-sensitive contexts.
> 
> 
> References:
> 
> [1] Java Cryptography Architecture, Sun Microsystems, http://java.sun.com/j2se/1.4.2/docs/guide/security/CryptoSpec.html#AppA
> 
> [2] J. Viega, G. McGraw, Building Secure Software, Addison-Wesley, 2002
> 
> [3] MSC02-J. Generate strong random numbers, CERT, https://www.securecoding.cert.org/confluence/display/java/MSC02-J.+Generate+strong+random+numbers
> 
> [4] Standards Mapping - Common Weakness Enumeration, CWE ID 338
> 
> [5] Standards Mapping - FIPS200, MP
> 
> [6] Standards Mapping - NIST Special Publication 800-53 Revision 4, SC-13 Cryptographic Protection (P1)
> 
> [7] Standards Mapping - OWASP Mobile Top 10 Risks 2014, M6 Broken Cryptography
> 
> [8] Standards Mapping - OWASP Top 10 2004, A8 Insecure Storage
> 
> [9] Standards Mapping - OWASP Top 10 2007, A8 Insecure Cryptographic Storage
> 
> [10] Standards Mapping - OWASP Top 10 2010, A7 Insecure Cryptographic Storage
> 
> [11] Standards Mapping - Payment Card Industry Data Security Standard Version 1.1, Requirement 6.5.8
> 
> [12] Standards Mapping - Payment Card Industry Data Security Standard Version 1.2, Requirement 6.3.1.3, Requirement 6.5.8
> 
> [13] Standards Mapping - Payment Card Industry Data Security Standard Version 2.0, Requirement 6.5.3
> 
> [14] Standards Mapping - Payment Card Industry Data Security Standard Version 3.0, Requirement 6.5.3
> 
> [15] Standards Mapping - Payment Card Industry Data Security Standard Version 3.1, Requirement 6.5.3
> 
> [16] Standards Mapping - Payment Card Industry Data Security Standard Version 3.2, Requirement 6.5.3
> 
> [17] Standards Mapping - SANS Top 25 2009, Porous Defenses - CWE ID 330
> 
> [18] Standards Mapping - Security Technical Implementation Guide Version 3.1, APP3150.2 CAT II
> 
> [19] Standards Mapping - Security Technical Implementation Guide Version 3.10, APP3150.2 CAT II
> 
> [20] Standards Mapping - Security Technical Implementation Guide Version 3.4, APP3150.2 CAT II
> 
> [21] Standards Mapping - Security Technical Implementation Guide Version 3.5, APP3150.2 CAT II
> 
> [22] Standards Mapping - Security Technical Implementation Guide Version 3.6, APP3150.2 CAT II
> 
> [23] Standards Mapping - Security Technical Implementation Guide Version 3.7, APP3150.2 CAT II
> 
> [24] Standards Mapping - Security Technical Implementation Guide Version 3.9, APP3150.2 CAT II

**Comment by sophokles73** [comment]
Hi,

first of all: a big thank you for your interest in Californium and doing such a thorough analysis :-)
I am not surprised that your tool dug up some *code smells* or *bad practices*, in fact, I would be interested in getting to know whether you found more like this. I guess after all we are just humans who sometimes make mistakes or simply do not know better (yet).

A first thing of interest would be on which branch/version you have been running the analysis: master? 1.0.4? 2.0.x? I am asking because the 1.0.x branch is merely receiving bug fixes while development is done on master (1.1.x) and 2.0.x.

Coming to the issues you identified:

1. IMHO we should replace the code where the *double-check locking* idiom is currently in use with plain simple synchronization. This seems to be an *idiom of the past* ...
Would you be interested in providing a PR for fixing this?

2. There are multiple places throughout Californium where (pseudo-)random numbers are used. Not all of them require a cryptographically strong PRNG. I have searched the whole code base (not only californium-core) on master for references to `java.util.Random` and I found 28 references altogether of which 5 were not in test cases. Of the five references in non-test code there is only one I would consider problematic and that is the one identified by your analysis, i.e. the code for creating tokens. We currently rely on a standard `Random` instead of a `SecureRandom` to produce the bytes for the tokens. I agree that this makes it possible for an attacker to *predict* tokens and use this information to try to inject fake responses to requests issued by a Californium peer. We are currently in the middle of re-factoring the whole code around MID and token generation so I will take this a valuable input to the process of doing so. Thanks again for pointing this out :-)

**Comment by evgeniynickolaev** [comment]
BTW I saw strange double-check locking at ```Exchange```  while examining #103 

https://github.com/eclipse/californium/blob/45897ef294a7874d0fcc5b9cff7f957c6ca18141/californium-core/src/main/java/org/eclipse/californium/core/network/Exchange.java#L400

https://github.com/eclipse/californium/blob/45897ef294a7874d0fcc5b9cff7f957c6ca18141/californium-core/src/main/java/org/eclipse/californium/core/network/Exchange.java#L416

I hope I could rid of it if along with PR for #103.

**Comment by sophokles73** [comment]
@evgeniynickolaev,

yes, I guess that's what @Rajsmit has been referring to as well...

**Comment by Rajsmit** [comment]
@sophokles73 
We have analyzed in 2.0.0.

Please let us know there are two issues.

1. Double locking(13 instances)
2. Insecure Randomness(4 instances):-

@evgeniynickolaev , are you resolving all 13 instances of double-check-locking.

should we submit PR.

**Comment by evgeniynickolaev** [comment]
@Rajsmit no, I've meant the only mentioned cases.
But currently I haven't ever touch them at all so never mind)

**Comment by sophokles73** [comment]
@Rajsmit,

by all means, please go ahead and create a PR for getting rid of the double locking occurrences. You do not need to work on the *insecure randomness* issue, we will address that as part of #83.

**Comment by Rajsmit** [comment]
Hi @sophokles73 

I have created the PR for this issue https://github.com/eclipse/californium/pull/111

Please review it.

Thanks,
Rajesh kumar.

**Comment by sophokles73** [comment]
fixed on master in bd0253a4488c2c6380ad7ab79ad8d9b1eab2d92b
fixed on 2.0.x in ae7177730b05567e7b9586d0df38ceb7a75de317
