### ISSUE TITLE
Add a description to californium github project

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1016]
I just saw that https://github.com/eclipse/californium does not have any description ...

I think we should add one, but unfortunately I didn't have right to do that.
Maybe @boaks or @sophokles73, you have right for that ?

The description could be something like : 
>Eclipse Californium is a CoAP implementation in Java.
>This repository also contains Scandium module which is a DTLS implementation in java.

We could also add some tags like : `dtls`, `java` ?

**Comment by boaks** [comment]
I recognized this a few days ago, but I haven't the rights also.
Maybe @sophokles73 can do it. Otherwise I would try to contact @mkovatsc, if he is allowed to add a description.

**Comment by sophokles73** [comment]
no, none of us has the permissions required to edit the description. We need to open an issue in IPZilla for the Eclipse Foundation Webmasters to do it for us.

@boaks can you create a corresponding issue?

**Comment by boaks** [comment]
[Ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549423)

Description:
CoAP/DTLS Java Implementation

Link to project
https://www.eclipse.org/californium/

**Comment by sbernard31** [comment]
Do you agree to add tags too ? (`dtls`, `java`)

**Comment by boaks** [comment]
sure

**Comment by boaks** [comment]
done.
