### ISSUE TITLE
different request and response port will reject 

### ISSUE THREAD

**Issue by jiangyoudi** [eclipse/californium#1019]
Dear, I come a  tricky problems,and hope to get your help.
I have a coap server behind Nginx and will communicate with many smart devices.
send message route:  server->Nginx(Intranet portA)-->Nginx(Extranet port 5683)--->device(5683)
return message route：device -->Nginx(Extranet port 5683)-->Nginx(Intranet portB)-->server(5683).

Nginx port Occasionally form portA  become portB ,and server will discard the return message.

     Nginx udp session maintenance is to ensure a port mapping between the client and nginx, but nginx may use different port forwarding when forwarding requests. In the case of small concurrency, try to ensure that one port is used. The maximum number of ports used is determined by the number of workers configured by nginx.

     How could I do to solve this question？if i delete the peerAddress1.getPort() != peerAddress2.getPort() will it resolve the question or will get what serious impact?

public boolean isResponseRelatedToRequest(EndpointContext requestContext, EndpointContext responseContext) {
		if (checkAddress) {
			InetSocketAddress peerAddress1 = requestContext.getPeerAddress();
			InetSocketAddress peerAddress2 = responseContext.getPeerAddress();
			if (**peerAddress1.getPort() != peerAddress2.getPort()**
					|| !peerAddress1.getAddress().equals(peerAddress2.getAddress())) {
				LOGGER.info("request {}:{} doesn't match {}:{}!", peerAddress1.getAddress().getHostAddress(),
						peerAddress1.getPort(), peerAddress2.getAddress().getHostAddress(), peerAddress2.getPort());
				return false;
			}

		}
		return super.isResponseRelatedToRequest(requestContext, responseContext);
	}

**Comment by boaks** [comment]
RFC7252 defines the usage of the endpoint in several places:
[Messages and endpoints](https://tools.ietf.org/html/rfc7252#section-4.1)
[Request/Response matching](https://tools.ietf.org/html/rfc7252#section-5.3)

So, if you disable the "port" check, californium will not be able to match the messages according RFC7252.

That seems to be a common issue, that NATs could not be used too easily with coap (or dtls),
Assuming, that a NAT maps a route for a certain amount of time in a static way. the usual traffic should make no trouble, because CON/ACK or request-response are considered to only take a few seconds.
For observe/notify via a NAT, it becomes difficult, when the notifies are sent with "too much time in between" and the NAT maps for the route expires.

In your case, I miss more details, 
What is the timespan of the related messages? Is it larger then the timeouts of your NAT.

(The "relaxed mode" for plain coap is in my opinion more or less for "observe/notify in laboratories".)

**Comment by jiangyoudi** [comment]
> RFC7252 defines the usage of the endpoint in several places:
> [Messages and endpoints](https://tools.ietf.org/html/rfc7252#section-4.1)
> [Request/Response matching](https://tools.ietf.org/html/rfc7252#section-5.3)
> 
> So, if you disable the "port" check, californium will not be able to match the messages according RFC7252.
> 
> That seems to be a common issue, that NATs could not be used too easily with coap (or dtls),
> Assuming, that a NAT maps a route for a certain amount of time in a static way. the usual traffic should make no trouble, because CON/ACK or request-response are considered to only take a few seconds.
> For observe/notify via a NAT, it becomes difficult, when the notifies are sent with "too much time in between" and the NAT maps for the route expires.
> 
> In your case, I miss more details,
> What is the timespan of the related messages? Is it larger then the timeouts of your NAT.
> 
> (The "relaxed mode" for plain coap is in my opinion more or less for "observe/notify in laboratories".)




Thanks,the port is not always changing,it is Occasionally。The NAT will keep about 1 minute,and  the timespan of the related messages use CON/ACK default timeout ,it is not larger then the timeouts of  NAT.。I use Open source project leshan ，it resolves the NAT problem。
 
 if I disable the "port" check, californium will not be able to match the messages according RFC7252。so,is it will affect normal communication? i just want the server do not discard the ack response.

**Comment by boaks** [comment]
> so,is it will affect normal communication?

You must define "normal". 
ACK (without piggybacked responses) and RST will not work reliable, if the endpoint changes. 
Also [deduplication](https://tools.ietf.org/html/rfc7252#section-4.5) will not work reliable.

Generally the other matching modes are introduced for DTLS (e.g. `PRINCIPAL`). 
FMPOV, they are not intended to be used for plain coap outside a "laboratory".

**Comment by boaks** [comment]
@sbernard31 

Though it's related to leshan, maybe you can comment on it.
Otherwise, I would like to ask to close this issue.

**Comment by sbernard31** [comment]
To be honest I'm not sure to understand the use case and the issue.

What is the purpose of Nginx here ? Loadbalancing on several cluster instances ?
Is DTLS used ?

> send message route: server->Nginx(Intranet portA)-->Nginx(Extranet port 5683)--->device(5683)
return message route：device -->Nginx(Extranet port 5683)-->Nginx(Intranet portB)-->server(5683).
>
>Nginx port Occasionally form portA become portB ,and server will discard the return message

I do not understand what is portA and port B.
