### ISSUE TITLE
Is it possible to disable autogeneration of Californium.properties file?

### ISSUE THREAD

**Issue by watta90** [eclipse/californium#1023]
Hi

I'm using the CoapClient (not the server) version 2.0.0-M15
Every time I execute the client a Californium properties file is generated. Can I disable this because I don't need the file? If not, is it possible to choose the location where this is generated?

Thanks in advance

**Comment by boaks** [comment]
Try

`NetworkConfig.createStandardWithoutFile()` 

at the very beginning.

**Comment by watta90** [comment]
Thanks!
That's solved it for me. I don't know how common this question is but I couldn't find it easily when googling. Don't know if it should be added in the Readme or if this issue will be indexed by google so people can find it now.

**Comment by boaks** [comment]
[Javadoc](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L49)

So, maybe, if you help us by providing the words/terms you used for your web-search, I can add them to the javadoc and hopefully the next will find it :-).

**Comment by watta90** [comment]
Great!
This is what I googled :) 

> californium coap properties file stop generating
why is californium coap properties file generated
californium don't generate properties file
californium coap runtime properties
