### ISSUE TITLE
observer  client in CoapService

### ISSUE THREAD

**Issue by chejdj** [eclipse/californium#1026]
What should I do to observer the client when observe the resource and when disconnect?

**Comment by boaks** [comment]
I can't understand that question:
a coap-client send a observe-request to the coap-server
a coap-server then will response and will notify, if the value of the resource is changing.

What do you mean by "disconnect"?
For which side, coap-client or coap-server, do you want a recommendation?

**Comment by chejdj** [comment]
Sorry, I just want to observer  the connection between coap-client and coap-server in coap-serverside. I use the ResourceObserver,but it can't

**Comment by boaks** [comment]
"disconnect" - "connection" - what exactly do you mean?
Do you use coap? coaps? Or coap over tcp (coap+tcp)?

**Comment by chejdj** [comment]
OK,I just want to ask 
when a coap-client send a observe-request to the coap-server,  I want to know the which one coap client send a observe-request in coap-server 。
And if the coap-client shutdown, whether I can get the information in coap server。

**Comment by boaks** [comment]
On the server-side currently you get only a counter of observers. `public int getObserverCount()`

When the client shuts down, It will take usually some time, until the server tries to validate the client's observe by a CON notify. A shutdown client will not ACK that CON message and so the server will remove that client from the observers list.

A client may also try to cancel the observer before it shuts down, but that depends on the client.

Does the `getObserverCount()` help you? Or do we need to make the `observeRelations`accessible with a public getter?

**Comment by chejdj** [comment]
In fact,For the  `CoapResource.getObserverCount()`, information is not detail. I think `observeRelations` accessible is great. Thank you.
