### ISSUE TITLE
DTLS retransmission question

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1034]
This a scenario inspired from a real world capture:

```
Time      Source      Destination      Info 
2.127170  client      server      Client Hello
2.287418  server      client      Hello Verify Request
2.315333  client      server      Client Hello
2.478780  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
No answer from client after 1s, we retransmit.
------------------------------------------
3.479602  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
Still no answer from client after 2s, we retransmit again.
-----------------------------------------
5.479355  server      client      Server Hello, Server Key Exchange, Server Hello Done
-----------------------------------------
The client recieved all messages but it sounds it was busy or not able to answer in time.
Now it unqueue message and answer one by one to each retransmission in a very short delay.
-----------------------------------------
5.673280  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
5.683168  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
5.705030  client      server      Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
-----------------------------------------
At server side we also recieve all messages and answer to each retransmission.
-----------------------------------------
5.841709  server      client      Change Cipher Spec, Encrypted Handshake Message
5.841823  server      client      Change Cipher Spec, Encrypted Handshake Message
5.863473  server      client      Change Cipher Spec, Encrypted Handshake Message
```

My first impression was "this is a pretty strange capture why all messages are sent 3 times ?".
After analyzing it, it seems to me there is nothing which could help to prevent this in the DTLS RFC. So I would say this is the "expected" behavior.

And I can not see any good way to avoid this...

WDYT ?

**Comment by boaks** [comment]
Usually a peer should ignore the "retransmissions", if the handshake sequence number is the same as already received. So, do you have a wireshark capture?

**Comment by boaks** [comment]
[RFC6347, 4.2.2](https://tools.ietf.org/html/rfc6347#page-18)

> If the sequence number is less than next_receive_seq, the message MUST be discarded. 

[RFC6347, 4.2.4](https://tools.ietf.org/html/rfc6347#page-20)

> 2. The implementation reads a retransmitted flight from the peer: the
>       implementation transitions to the SENDING state, where it
>       retransmits the flight, resets the retransmit timer, and returns
>       to the WAITING state.  The rationale here is that the receipt of a
>       duplicate message is the likely result of timer expiry on the peer
>       and therefore suggests that part of one's previous flight was
>       lost.

The issue with that is, that the retransmitted messages are queued before they processed. So they not re-received at the time of processing.

**Comment by boaks** [comment]
AFAIK, scandium therefore doesn't trigger a resend, when a message is re-received. Scandium just waits for the normal retransmit timeout. So the wireshark would really be interesting.

**Comment by sbernard31** [comment]
[Here](https://github.com/eclipse/californium/files/3501422/retransmission_capture.zip) the capture. (The handshake sequence number is the same, the capture is done at client side and cf-2.0.0M16 is used)

Just to be clear, here we talk about `message_seq` from Handshake message (not about record sequence number), right ? 

About both RFC parts you mentioned, it seems to be contradictory. I mean : 
 - first one says : discard.
 - second one says : do like timer expiry (so retransmit)
I probably missed something ...
My feeling is that "discard only" is better (at least at bandwidth point of view, probably not for latency).  Counting only on expiration time seems enough.

> AFAIK, scandium therefore doesn't trigger a resend, when a message is re-received. Scandium just waits for the normal retransmit timeout.

Reading quickly the scandium code, I would bet the same, but the capture sounds invalidate my bet :thinking:. So I looked at this deeper and the behavior for the last flight is different : 
```java
if (lastFlight != null) {
	// we already sent the last flight (including our FINISHED message),
	// but the client does not seem to have received it because we received
	// its finished message again, so we simply retransmit our last flight
	LOGGER.debug("Received client's ({}) FINISHED message again, retransmitting last flight...",
			getPeerAddress());
	lastFlight.incrementTries();
	lastFlight.setNewSequenceNumbers();
	sendFlight(lastFlight);
	return;
}
```
This is recommended by the RFC and I'm not sure another solution exists. (maybe retransmission timer + waiting for application data ...)

So the client which is not scandium could probably avoid to send its message 3 times but the server (scandium side) is right to do that.

**Comment by boaks** [comment]
> (The handshake sequence number is the same, the capture is done at client side and cf-2.0.0M16 is used)

But cf-2.0.0-M16 is not used on the client side, or?

**Comment by sbernard31** [comment]
My mistake this is californium 2.0.0-M14. cf is not used at client side only at server side.

**Comment by boaks** [comment]
We can try to filter those records, received before we resent the last flight. In the capture, it may help, 8 and 9 have timestamps before 10. 
But with small changes in the timing, that may also fail.
(We currently have a "current receive timestamp", if we compare that with the actual send timestamp of the last flight, that may filter a little.)

**Comment by boaks** [comment]
> cf is not used at client side

Using  79 cipher suites would have been a great extension for scandium :-).

**Comment by boaks** [comment]
Should we go for the "time filter" and see, if it improves also the reality?

**Comment by sbernard31** [comment]
> Using 79 cipher suites

and finally CBC is used :grin: !
This remember me that we should remove support of CBC in production. :sweat_smile: 
This also remember me that cipher suite negociation priority is driven by client preferences in Scandium. (I always forgot this as intuitively I expect the opposite)

> We currently have a "current receive timestamp", if we compare that with the actual send timestamp of the last flight, that may filter a little

> Should we go for the "time filter" and see, if it improves also the reality?

This could be an interesting optimization. :+1: 
I wanted mainly understand if all of this was normal. I feel there is no urgency so if you have more higher priority, do not hesitate to let this aside. :-)

**Comment by boaks** [comment]
Do you feel, that there is something left for this issue? Or can we close it?

**Comment by sbernard31** [comment]
Now that https://github.com/eclipse/californium/pull/1035/commits/f38351598d0856f54e713f29d14a285b079074a7#diff-50ff2ed780e7b7a1d25a95c4f1a337b7L445 is integrated, I think we can close it.

About the new filter :
```java
if (record.getReceiveNanos() < flightSendNanos) {
	LOGGER.debug("Discarding {} message received from peer [{}] before last flight was sent:{}{}",
			record.getType(), record.getPeerAddress(), StringUtil.lineSeparator(), record);
	return;
}
```
I would like to be able to see if this happened when we will deploy the M17 but as this is a log.debug(), this will probably flood the log. (even if I activate this only for `Handshaker`)

Maybe in a first time we could set it as info (then go back in debug if M18)  ? (I know it's a bit strange as this is clearly not an info but a debug)

Or, maybe we should define a way that make debug usable in production : : 
Debug : something which could happened but should not (as bad device behavior) : Must not log so much in "normal" behavior.
Trace : all behavior for development only : can flood the log. 

WDYT ?

**Comment by boaks** [comment]
> WDYT

Though I'm currently still change too much in scandium, I would prefer "info" for M17, and the log level adjustment for M18 (or 2.0.0 release, we will see).

**Comment by sbernard31** [comment]
Before to release the 2.0.0 I advice to release a RC1 or something like this.
(RC means that only bug fix will be done after that)

**Comment by sbernard31** [comment]
> I would prefer "info" for M17

I pushed a commit (b6841081365841281b3fb0f9421a20e34b8ab1dc) to change this. 

So I closed this PR.

**Comment by sbernard31** [comment]
@boaks, maybe you could be interested by https://github.com/ARMmbed/mbedtls/issues/2825#issuecomment-529872121.

**Comment by boaks** [comment]
What exactly? The remark about DTLS 1.3?

**Comment by boaks** [comment]
Until now, no one requested it. 
From my experience, the "resends" are more caused by bugs then by message drops. 
So the lazy variant of scandium fits very well.
