### ISSUE TITLE
 Identifying a received multicast message

### ISSUE THREAD

**Issue by JustMellow** [eclipse/californium#1040]
I'm currently trying to analyse on the server-/resource-side if a received request is a multicast request. For this, I'm using `exchange.advanced().getRequest().isMulticast()` at a corresponding `CoapResource` (inside the `handleGET` method as an example). However, this query is always false. 

If I do a similar query on the client before sending the multicast request, it returns true. I can see with Wireshark that the Request is being send to the correct Multicast-Address (224.0.1.187). 

Is this a bug or is my approach incorrect? If it’s wrong: is there a possibility to identify if a received request is a multicast request?

Version used: 2.0.0-M16 // Java 12

**Comment by boaks** [comment]
Yes, that `Request.isMulticast()` only works on the client side. 

In pure-java I didn't find a way, to distinguish `Datagrams` received by multicast or not. If you know such an approach, let me know. 
I also considered to ask the ietf-core group to add a "multicast" option to solve this java issue, but until now, I didn't get the time to do so. Alternatively you may set the multicast address as host-address option and use that also on the server-side. But that would also be a none standardized way.

**Comment by JustMellow** [comment]
Thank you very much for the quick answer. I was already thinking about bypassing the problem with an additional option, but this was the last solution I wanted to consider. 

Unfortunately, I'm not very familiar with `Datagrams` in Java, so I'll consider an additional option parameter for now. Nevertheless, I'll ask a colleague if he has an idea regarding the identification of multicast datagrams.

**Comment by boaks** [comment]
Just to mention:
Using the multicast address as Uri-Host option is a convention. It will not work with "ready-to-use-peers/devices" from others, because they don't use that convention. But if you implement both sides, it's simply up to you. That should be possible with all libraries.

**Comment by JustMellow** [comment]
This is actually a nice approach. Thanks for mentioning it!

**Comment by boaks** [comment]
@JustMellow 

Just, if you're still interested in the multicast feature:

There is an ongoing discussion in the ietf core-mailing-list, see [RFC 7252 - 8.2 - Multicast - Request / Response Layer, page 67, top](https://mailarchive.ietf.org/arch/msg/core/d2CJN0g-ksq9uf0hDqBCRqcHz5g/).
I addressed the discussed topic in PR #1272.
I would appreciate, if you can test, if that approach works for you.

**Comment by JustMellow** [comment]
@boaks 
Thanks for the news about the new features - the Multicast Receiver looks very promising . Currently, I'm working on something else, but I'll take a look soon and provide you some feedback.
