### ISSUE TITLE
Release cf-nat ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1041]
I'm currently using `NatUtil` for writing some tests.
AFAIK, `NatUtil` is not released so I copy/paste it.

Maybe it could make sense to release it ?
I don't see any issue to do that. Maybe the only one could be the `logback.xml` in `/cf-nat/src/main/resources` which could make trouble if it is integrated in a real application. (because if there are several `logback.xml` we don't know which one will be used...)

**Comment by boaks** [comment]
> Maybe it could make sense to release it ?

If wanted, we can add it to the release job.

**Comment by sbernard31** [comment]
Ok.

For logback.xml issue a solution could be to rename `logback.xml` in something like `logback-config.xml` and add this static block : 

```java
    static {
        // Define a default logback.configurationFile
        String property = System.getProperty("logback.configurationFile");
        if (property == null) {
            System.setProperty("logback.configurationFile", "logback-config.xml");
        }
    }
```
in `Nat` class.

But If you prefer we can start by just releasing cf-nat like this and see if we really face logback.xml classpath issue.

**Comment by boaks** [comment]
Sorry, I forget to answer.
Please add that stuff to the Nat.

**Comment by sbernard31** [comment]
I integrated the #1041 in master and modify jobs :
- [californium-deploy-maven-central](https://ci.eclipse.org/californium/view/Release/job/californium-deploy-maven-central/)
- [californium-deploy-eclipse](https://ci.eclipse.org/californium/view/Release/job/californium-deploy-eclipse/)

by adding this to the maven step : 
> --projects
californium-osgi,californium-proxy,cf-oscore,demo-apps/cf-plugtest-server,**demo-apps/cf-nat**
-am
deploy

I hope I didn't miss something.

@boaks, if it's OK for you we can close this issue.

**Comment by boaks** [comment]
The jobs looks good for me.
We will see next week, if it works :-),

**Comment by sbernard31** [comment]
After so many time I finally try to integrate the release version instead of copy/paste one and I get this error : 
```
Failed to collect dependencies at org.eclipse.californium:cf-nat:jar:2.2.3:
Failed to read artifact descriptor for org.eclipse.californium:cf-nat:jar:2.2.3: 
Could not find artifact org.eclipse.californium:demo-apps:pom:2.2.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

I didn't investigate so much but my guess is `demo-apps` need to be release too ?

**Comment by boaks** [comment]
Currently I plan a "utility" for the cf-nat, interop-test, and intergration tests.
Maybe we the publish that?

**Comment by sbernard31** [comment]
I'm not sure to get your point ?
You mean a new cf-utility project used by cf-nat, interop-test and integration tests ?

**Comment by boaks** [comment]
A utility additionally to demo-apps and moving the other mentioned modules as submodules into that.
