### ISSUE TITLE
cf-rd cannot register an endpoint to RD with a context in URI query

### ISSUE THREAD

**Issue by navoda** [eclipse/californium#105]
This is regarding the _Resource Directory (cf-rd) in eclipse Californium Tools_

I tried to Register an endpoint to the RD (Resource Directory) using Third-party registration where a remote client sends a POST request with the endpoint details. 

> Interaction: CLIENT --> RD
> Method: POST
> URI Template: /{+rd}{?ep,d,et,lt,**con**}
>       con := in the form of _scheme://host:port_

This template is according to [CoRE Resource Directory](https://tools.ietf.org/html/draft-ietf-core-resource-directory-08) **6.3 Registration**

As an example 
> Req: POST coap://rd.example.com/rd?ep=node1&d=core&con=coap://localhost:5683

But when **_RDNodeResource_** is using this URI query to add a resource to the RD, regarding the given endpoint, the **con** attribute fails to pass correctly.

I found the class **_LinkAttribute_** (org.eclipse.californium.tools.resources.LinkAttribute) receives the query **con=coap://localhost:5683**  and omits the host and port returning only the schema (in this case **coap**). 

This cause the system to fail to understand the **con** attribute as an actual URI, hence rejects the whole Resource creation.

#### Can you please confirm if this is a bug. If it is, I can send a patch to fix this.

**Comment by navoda** [comment]
I have addressed the same issue in [californium.tools](https://github.com/eclipse/californium.tools/issues/24)
I would appreciate if you can give me a response soon.

**Comment by sophokles73** [comment]
see https://github.com/eclipse/californium.tools/issues/24
