### ISSUE TITLE
Requests are send over cellular data instead of WiFi

### ISSUE THREAD

**Issue by logo17** [eclipse/californium#1053]
I'm having the issue that all CoAP requests are being send over cellular data network even if I'm conected to the CoAP server via WiFi. According to Android documentation I can use **bindProcessToNetwork** (https://developer.android.com/reference/android/net/ConnectivityManager.html#bindProcessToNetwork(android.net.Network)) however it only works one time, if for some reason the CoAP server gets disconnected the remaining request will be send over **cellular data** . 

Also Android documentation says: 

> Using individually bound Sockets created by Network.getSocketFactory().createSocket() and performing network-specific host name resolutions via Network#getAllByName is preferred to calling bindProcessToNetwork.

Is there a way to implement the request with californium with that specific implementation using sockets?

Thanks in advance.

Version: org.eclipse.californium:californium-core:2.0.0-M13

**Comment by boaks** [comment]
> I'm having the issue that all CoAP requests are being send over cellular data network even if I'm conected to the CoAP server via WiFi.

Strange, that's not my experience. Anyway,
See [UDPConnector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/UDPConnector.java) and [UdpMulticastConnector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/UdpMulticastConnector.java) how to setup your own `Socket`.

**Comment by logo17** [comment]
I forgot to mention that the CoAP server does not have internet connection, that’s why Android gives priority to cellular data.

**Comment by boaks** [comment]
> I forgot to mention that the CoAP server does not have internet connection

FMPOV,  a CoAP server offers a `CoapEndpoint` with an `Connector`, which has a `DatagramSocket` bound to one of the host's network interfaces (or all interfaces). So what does "internet connection" mean?

**Comment by logo17** [comment]
According to Android documentation for enableNetwork:

> Note: Network communication may not use Wi-Fi even if Wi-Fi is connected; traffic may instead be sent through another network, such as cellular data, Bluetooth tethering, or Ethernet. For example, traffic will never use a Wi-Fi network that does not provide Internet access.

So the CoAP server that I'm connecting in the Android application does not provide internet connection, so all the requests for the android application are sent via **TYPE_MOBILLE** network.

What I want to do is use the **WiFi network** in the Android application to send all the CoAP requests even if it has cellular data enabled.

**Comment by boaks** [comment]
As I already wrote, your described behaviour doesn't match my experience.
In Android Settings - WLAN - Extended, there is a switch to enable/disable the use of cellular when wlan is bad. My be you enabled it? 
You issue seems to be more Android specific. I'm no Android expert, and though I didn't have the behaviour on my Android Device, it's hard to find out, what's wrong on your side. May be you try in parallel to clarify the common Android setup for your details in a Android Forum?

**Comment by logo17** [comment]
Is there a way that I can specify the network interface **en0** for the CoapClient?

**Comment by logo17** [comment]
Already fixed it. Thanks

**Comment by boaks** [comment]
@logo17 

May be it's for others also interesting, how you solved it.

**Comment by logo17** [comment]
What I did was specify the **wlan0** interface in the CoAP Client Uri.. now all the request are being send by that interface.

**Comment by Selvam-bestea** [comment]
@logo17 can you share your code
