### ISSUE TITLE
Extend TokenGenerator - reintroduce address scoped tokens

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1064]
In late 2017 we introduced the `TokenGenerator` with two kind of tokens:

- long term tokens, used for clustered observe/notifies
- short term tokens, used for normal requests

With that, we changed the scope of the tokens to be no only unique per peer, we changed it to be unique per cluster or single cluster node.

FMPOV, that limits to RFC7252 confirm usage of tokens too much. 
Therefore, i would like to change this again and introduce 3 token scopes:

- long term tokens, used for clustered observe/notifies unique within the cluster
- short term tokens - node unique, used for multicast requests
- short term tokens - peer unique, used for normal requests

For the "short term tokens - peer unique",  the equals and hashCode will be extended by the ip-address:port (endpoint) of the peer. That rules are only apply for outgoing request and incoming responses. The server-side handle the tokens still opaque.
 
 To distinguish the scope, my plan is to add a Scope enum to the `TokenGenerator`, replace the `boolean longTermScope` argument by that enum, and add a `Scope getScope(Token)`. That enables the usage of custom rules creating tokens as well as support "application supplied tokens" with that scoping.

If no objection, I would like to prepare a PR for that.

**Comment by sbernard31** [comment]
> FMPOV, that limits to RFC7252 confirm usage of tokens too much.

Could you explain a bit more the limitation you are talking about ?

**Comment by boaks** [comment]
[RFC7 7252 - Token](https://tools.ietf.org/html/rfc7252#section-5.3.1)  

> A token is intended for use as a client-local identifier for differentiating between concurrent requests (see Section 5.3); it could have been called a "request ID".

So, if the token is provided by the application, may be even a EMPTY token (as LwM2M specified ago), the consideration may be based on that "client-local identifier" intention.

**Comment by sbernard31** [comment]
I remember that token must be unique by foreign peer.
By the past I tried to introduced a [endpoint Identifier](https://github.com/eclipse/californium/pull/322). This way we could have identified a request by [token+endpoint identifier].
I still feel that this kind of abstraction  would really help. (E.g. with connectionID, I bet that we could find that address:port is not a really good identifier :thinking:)

I thought that maybe you discovered a new limitation but I understand correctly this is not the case. You finally just think this is too restrictive, am I right ?

This brings me into those questions :
 1. Do you face a use case (situation) where the current behavior is too restrictive ?
 2. Do we need this for 2.0.0 ?
 3. Do you think this endpoint identifier could be a good feature for 3.0.0 ?

**Comment by boaks** [comment]
If I remember well, my main issue with that "endpoint identifier" was, that it will be available late. At least without a prior "connect".

> 1. 

[openHUB2 - requires empty token](https://stackoverflow.com/questions/57558648/how-to-handle-custom-coap-options-non-standard)

> 2.

Though it changes the API, I would go for it for 2.0. I already started to check, what must be changed (if the address is used).

> 3.

Depends on the solution of the "late availability".

**Comment by boaks** [comment]
Let me add:

For outgoing none-observe requests, I still think the address is not too bad.
For outgoing observe requests, that change should be very small.

For incoming stuff, the "endpoint identifier" is available, and then be applied for the KeyMID in the deduplication store for the case, where a peer tries to handshake before all retransmissions expires. But that helps only in rare cases.

I can also replace the InetSocketAddress in `KeyToken getKeyToken(Token token, InetSocketAddress peer);` by the `EndpointContext`. That would hopefully limit future changes to the `KeyToken` only.

**Comment by sbernard31** [comment]
1. I didn't get the OPENHAB use case, why does it need an empty token ?
2. and 3. I asked this because if there is no emergency to do that and if "endpoint identifier" is the chosen way, there is no need to implement this.

As it seems you think we need it and you already implement it, I guess my question are a bit obsolete :sweat_smile: I will review #1066.

> Depends on the solution of the "late availability".

It could be done by adding the relation during `MessageObserver.onContextEstablished(EndpointContext)`
By the way, I don't really see `EndpointContext` as an endpoint identifier, even if I agree it contains all the information (even more) needed to create an endpoint identifier.

**Comment by boaks** [comment]
Basically I implemented it to see, what need to be changed.

> It could be done by adding the relation during 

The verification, if the key token is already used, will be also late. If that fails, it would require to serialize the request again with a new token.

**Comment by sbernard31** [comment]
> The verification, if the key token is already used, will be also late. If that fails, it would require to serialize the request again with a new token.

Just some thoughts about that : 

As with this modification the scope will be by peer, depending on token size the random generation collision would [become very improbable](https://github.com/eclipse/californium/issues/173#issuecomment-293245718), and so maybe not a real issue :thinking:  (except if using random generation with short token is needed)

The remaining issue is if the users use `setToken` twice with the same token.
But in that case this seems to be users (progammation) issue, and we could just raise log (WARN or ERROR) and keep only the last relation. (This is already what we did)

Adding on onContextEstablished will limit the number of persist store too as instead of "1 call with putIfAbsent + 1 call setContext" we will only have "1 call putIfAbsent" (as context will be known)

**Comment by boaks** [comment]
If I remember it right, leshan uses the available `EndpointContext` directly without the callback `onContextEstablished`. So try to distinguish:

1. both peers have fixed addresses, which don't change
1. on peer has a changing address, the other a fixed

For 1, the ip-address could be used.
For 2, it depends on the peer. The peer with the changing address is communication with a peer with a fixed address, therefore that side can use that fixed address of the other peer. The peer with the fixed address must wait until the other peer with the changing address sends a message. Therefore that peer will have a `EndpointContext` to identify the peer with the changing address.

With that, I would go for changing the KeyToken to use Object instead of InetSocketAddress. That would allow a "cloud server", to implement the peer identifier as considered for it. That don't require change in the call sequences.

**Comment by sbernard31** [comment]
> If I remember it right, leshan uses the available EndpointContext directly without the callback onContextEstablished

In the particular case of Leshan, you remember well as we always know the endpointcontext/endpoint identifier when we send the request. (at client or server or bsserver side)

> With that, I would go for changing the KeyToken to use Object instead of InetSocketAddress. That would allow a "cloud server", to implement the peer identifier as considered for it. That don't require change in the call sequences.

Probably better. (I ask my self if we should create a marker interface for this and insist on the fact that equals and hashcode should be implemented in a "compared by value" way ?)

**Comment by boaks** [comment]
> (I ask my self if we should create a marker interface for this and insist on the fact that equals and hashcode should be implemented in a "compared by value" way ?)

OK. I will change it and prepares some integration tests.

With that, I would also (other PR) try out, if the `KeyMID` could be processed similar. We will see how many changes that will cause :-).

**Comment by boaks** [comment]
> marker interface

I got aware, that this will not work easily with the `InetSocketAddress`. So I would go for a better javadoc only.

**Comment by boaks** [comment]
One of the side outcome of this experiment is, that using KeyMID and KeyToken and keep them in the Exchange and use them for house-keeping, simplifies that even. But to reach that simplification, both keys must be used. Therefore I put them all together with the new `EndpointContextResolver` into one PR with one commit. Otherwise the change will be frequently overwritten in followup commits.

**Comment by boaks** [comment]
Fixed with PR  #1074
