### ISSUE TITLE
Is it possible to implement UDPConnector via netty?

### ISSUE THREAD

**Issue by oliverzst** [eclipse/californium#1068]
# Please providing basic issue information

Issues may be answered much faster, if you provide more details ahead!

* branch your faced the issue. Currently 
   * 1.0 is the current release,
   * 1.1 is the previous master (no plans to continue this)
   * and master (previous 2.0) is the development branch and our upcoming release!
* If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
  commit your using
* If your issue is related to your own snippet, please provide that
* If you have logs, please provide them
* If you have tcpdump captures (wireshark), please provide them.

**Comment by boaks** [comment]
Sure, but all, who tried it, found, that there are close to no benefits!

**Comment by boaks** [comment]
The idea, to use async IO is somehow worth to be considered. But mainly for load-test clients. Though, we are not too many active committer, this approach was postponed.

**Comment by boaks** [comment]
@oliverzst 

You may have a look at #434  

Californium uses the [Connector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/Connector.java) interface for transmission. You may implement that using netty. Feedback would be very welcome.

**Comment by boaks** [comment]
Did you have a look on the implementation? 
Still interested?
Do you consider a contribution?
