### ISSUE TITLE
cannot connect a second time to californium coap server

### ISSUE THREAD

**Issue by paxter** [eclipse/californium#1072]
I'm using 2.0.0-M17.

I'm connecting with the c library libcoap to my californium coap server and everything is working fine. I'm receiving the ACK and the 205 response. But if I'm trying to connect a second time, nothing happens. I have to restart the californium coap server to get it working again.
I'm not sure, if I'm  doing something wrong. After getting the ACK from coap server, I close the DTLS session on the client side and try to opening a new session for the next connect.

My simple coap server implementation is looking like this:

```java
public class CoapFileServer {
    CoapFileServer(InMemoryPskStore inMemoryPskStore) {
        CoapServer server = new CoapServer();
        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setPskStore(inMemoryPskStore);

        DTLSConnector dtlsConnector = new DTLSConnector(builder.build());

        server.add(new CoapResource("test") {
            @Override
            public void handlePUT(CoapExchange exchange) {
                Request request = exchange.advanced().getRequest();
                byte[] payload = exchange.getRequestPayload();

               [... handling payload here ...]

               exchange.respond(CoAP.ResponseCode.CONTENT);
            }
        });

        CoapEndpoint.Builder coapBuilder = new CoapEndpoint.Builder();
        coapBuilder.setConnector(dtlsConnector);
        coapBuilder.setNetworkConfig(NetworkConfig.getStandard());
        server.addEndpoint(coapBuilder.build());
        server.start();

        // add special interceptor for message traces
        for (Endpoint ep : server.getEndpoints()) {
            ep.addInterceptor(new MessageTracer());
        }
    }
}
```

Is there something I have to handle after the `exchange.respond`? Maybe there is any session not closed properly? I've tested with a different port on client side for the second connect too, but it's the same.

I don't know how to enable the debug level and I just see the INFO messages on the terminal. Maybe somebody could give me a hint. This could help I think.

I'm testing this on an own network interface and connecting through link-local addresses with the `ff80:::%adapterhere` option.

**Comment by paxter** [comment]
> The CLIENT_HELLO contains a random, and I checked that already in the first capture, that it differs from handshake to handshake. The cookie is based on that random, so it should not depend on the "server-only secret" to create the specific cookie for your CLIENT_HELLO.

Ah ok.

> The second CLIENT_HELLO of the handshake with cookie as response to the HELLO_VERIFY_REQUEST?

I hope so. I can not see that in the debug output, but it's a message of 67 bytes length, which was before the second CLIENT_HELLO.

> Then it may be just by random, that the server must be restarted.

You may be right.

> Do you capture on the server host?

Yes.

> Do you filter on the address or port?

I'm filtering on the bound interface and port.

> Maybe you try to filter on the port and see, if that second CLIENT_HELLO is received on an other interface. Or if some other ICMP message indicates an issue.

I will check that. Thanks for your help.

**Comment by paxter** [comment]
Looks more like a client issue, so I'm closing this issue. Thank you for your support @boaks. :)

**Comment by paxter** [comment]
Sorry, but I have to reopen this issue. The second secure dtls communication is still not working between tinyDTLS <--> Californium.

Maybe both parts are doing something wrong on handshaking or there is something wrong with my tuntap interfaces. Anyway, here is my current test.
Client (tinyDTLS) and server (Californium) use for both connections different ports and link-local ipv6 addresses (to enforce new sessions, because I firstly thought there was a problem with reusing of existing sessions between known peers).

As usual, the first connection where californium acts as client is working fine. Well. Now I shutdown the client and do a fresh restart. I'm trying to start a new dtls session from client (tinyDTLS) with new parameters (using psk with TLS_PSK_WITH_AES_128_CCM_8) to the server.

The client send the CLIENT HELLO, Californium received that and now, nothing happens. This time I can provide debug outputs from both sides and a fresh wireshark capture (I captured everything on the interface).

tinyDTLS debug output
```
Jan 01 00:00:00 DEBG ***[fe80::cafe:cafe:1337:caff]:49152 <-> [fe80::cafe:cafe:1337:cafe]:5999 DTLS: new outgoing session
Jan 01 00:00:00 DEBG ***new session 0x80cc0c0
Sep 24 16:48:59 DEBG DTLSv12: initialize HASH_SHA256
Sep 24 16:48:59 DEBG send handshake packet of type: client_hello (1)
Sep 24 16:48:59 DEBG send header: (13 bytes):
00000000 16 FE FF 00 00 00 00 00 00 00 00 00 36  
Sep 24 16:48:59 DEBG send unencrypted: (12 bytes):
00000000 01 00 00 2A 00 00 00 00 00 00 00 2A  
Sep 24 16:48:59 DEBG send unencrypted: (42 bytes):
00000000 FE FD 00 00 00 00 41 D7 22 0B 6C BC E5 27 D8 A4  
00000010 00 42 E8 9B B7 09 68 D2 D4 8A 98 65 6F 7B C3 F4  
00000020 62 B5 00 00 00 02 C0 A8 01 00  
Jan 01 00:00:00 DEBG ** DTLS global timeout set to 1999ms
Jan 01 00:00:00 DEBG *  [fe80::cafe:cafe:1337:caff]:49152 <-> [fe80::cafe:cafe:1337:cafe]:5999 DTLS: sent 67 bytes
Jan 01 00:00:00 DEBG ** [fe80::cafe:cafe:1337:caff]:49152 <-> [fe80::cafe:cafe:1337:cafe]:5999 DTLS: tid=22564: delayed
waiting for response...
Jan 01 00:00:00 DEBG ** DTLS global timeout set to 1998ms
```

Californium debug output

```
16:48:59.866 [DTLS-Receiver-0-/fe80:0:0:0:cafe:cafe:1337:cafe%4:5999] DEBUG org.eclipse.californium.scandium.DTLSConnector - Received 1 DTLS records from /fe80:0:0:0:cafe:cafe:1337:caff%4:49152 using a 16490 byte datagram buffer
16:48:59.870 [DTLS-Connection-Handler-3] DEBUG org.eclipse.californium.scandium.DTLSConnector - Processing new CLIENT_HELLO from peer [/fe80:0:0:0:cafe:cafe:1337:caff%4:49152]
16:48:59.870 [DTLS-Connection-Handler-3] DEBUG org.eclipse.californium.scandium.dtls.Record - Parsing HANDSHAKE message without a session
16:48:59.871 [DTLS-Connection-Handler-3] DEBUG org.eclipse.californium.scandium.DTLSConnector - Verifying client IP address [/fe80:0:0:0:cafe:cafe:1337:caff%4:49152] using HELLO_VERIFY_REQUEST
```
[capture.pcap.zip](https://github.com/eclipse/californium/files/3648417/capture.pcap.zip)

It's very difficult to find out, which component is doing something wrong or it's a coding issue by myself. :/

**Comment by boaks** [comment]
What are your filter setting for wireshark?
I would prefer, if the server starts on 5684, as wrieshark filter only dtls is used, and then capture ...
I'm not aware of sending problems after that log-message.
If the connector is started on the wildcard address (only the port is provided), then sometime the routing of the host takes strange ways ... 
Therefore, use 5684 and capture all dtls traffic.

**Comment by paxter** [comment]
I'm using tcpdump and the port shouldn't be any problem, or?

`tcpdump -i tap0 -n udp -w capture.pcap`

**Comment by boaks** [comment]
Between that logging message and send there is not too much code ...

But without being able to reproduce the effect, I'm just guessing ...

**Comment by paxter** [comment]
I can provide a full log/capture of both sides without restarting the client. I'm testing for a week now and I don't understand why only one dtls session works fine and the second one don't. I tested many different cases, switched ports, ipv6 addresses, tested with interface binding and without. Nothing works and I've no clue what's wrong. 
I only know that the handshake isn't completing on the second dtls connection.

There are so many possibilities. Also it could be a problem on RIOT OS (where the client is running), libcoap, tinyDTLS or anything on the host system.

**Comment by boaks** [comment]
```
DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
builder.setPskStore(inMemoryPskStore);
builder.setAddress(new InetSocketAddress("[fe80::cafe:cafe:1337:cafe]", 5684);
DTLSConnector dtlsConnector = new DTLSConnector(builder.build());
```

try that.

**Comment by boaks** [comment]
And/or add logging in `DTLSConnector-sendNextDatagramOverNetwork` direct around the `socket.send`.

**Comment by boaks** [comment]
And did you check, if "plain" coap, without dtls, works after a pause?

**Comment by boaks** [comment]
Does your client run in an emulator? Or on a device?
I'm wondering. At the start it was the client, which didn't respond, now it's the server ...
I'm really hove no glue ...

**Comment by boaks** [comment]
If it's a emulator and doesn't require specific client hardware, and your client code doesn't contain your "property", I may spend next Saturday or Monday on it.

**Comment by paxter** [comment]
> ```
> DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
> builder.setPskStore(inMemoryPskStore);
> builder.setAddress(new InetSocketAddress("[fe80::cafe:cafe:1337:cafe]", 5684);
> DTLSConnector dtlsConnector = new DTLSConnector(builder.build());
> ```
> 
> try that.

It's the same as before.

> And/or add logging in `DTLSConnector-sendNextDatagramOverNetwork` direct around the `socket.send`.

I will check that tomorrow.

> And did you check, if "plain" coap, without dtls, works after a pause?

Yep, works fine.

> Does your client run in an emulator? Or on a device?

All components run in an ubuntu vagrant vm. But I think that shouldn't be the problem.

> I'm wondering. At the start it was the client, which didn't respond, now it's the server ...
> I'm really hove no glue ...

Yes, it's a little bit confusing, because I changed the test case a bit. My implementation is like that:

Client (tinyDTLS) <--> Server (Californium, can also act as client)

1.) Californium (as client) connects to client (tinyDTLS) with a secure dtls connection
2.) Client (tinyDTLS) takes the connection and handles the sent data
3.) Client (tinyDTLS) later (in my tests some seconds) connects to the server ( californium coap-server part) with dtls
4.) Server (Californium) handles the received data

In any case, there is only one dtls connection working properly. If I skip step 1.), step 3.) works and vice versa. It looks like there is something strange on the constrained client side, but I really don't know exactly what it is.

> If it's a emulator and doesn't require specific client hardware, and your client code doesn't contain your "property", I may spend next Saturday or Monday on it.

This is really nice from you, but I think it's not necessary. I started my work 3 month ago and every library I'm using (and the OS also) is outdated (except of californium). So the first step would be to upgrade all components to their latest versions and try everything again. But I've no time for that and I need the results to the end of the week. Also it's ok if it's not working, but it would be better if it was of course.
The RIOT version I'm using also has problems with posix sockets, maybe it's something with that.

Thanks for all your help, fast replys and helping comments. My problem is not solved, but you helped me a lot though.  

If I'm find something new out, I will update this issue. Unless, I will close it to the end of the week.

Thanks again. :)

**Comment by boaks** [comment]
Does the tinyDTLS act first as dtls-server, and then as dtls-client?

If yes, maybe @sbernard31 knows, if there is something to obey, setting up tinyDTLs for both roles.

**Comment by paxter** [comment]
> Does the tinyDTLS act first as dtls-server, and then as dtls-client?

Exactly. But it makes no difference, if it's acting as server or client. The problems are the same. It's not possible to establish a second dtls connection.

**Comment by sbernard31** [comment]
I'm a bit lost.

Could you explain again what is the smaller/simple use case which does not work without DTLS roles exchanges  (I mean client always acts as a client and server as a server) ?

**Comment by paxter** [comment]
My usecase is about updates on constrained devices. So the constrained device offers an coap endpoint for receiving meta information about the upcoming update (acts as server). If the constrained device received meta information about an update, it can deside itself, wheter or when it download the update. In the case of downloading the update, the constrained device acts as client.

**Comment by sbernard31** [comment]
Ok I realize that "use case" was not exactly the right term, I have more in mind something like a minimal scenario which reveal the issue.

If I well understand you says that you are not able to do 2  successive handshakes, but I'm lost about what is exactly the scenario. I mean I remember I already succeed to make 2 successful handshakes using tinyDTLS as client and scandium as server.

**Comment by paxter** [comment]
> Ok I realize that "use case" was not exactly the right term, I have more in mind something like a minimal scenario which reveal the issue.

Oh, sorry. But that won't be possible, because there are a bunch of different code which is needed for testing. My hope was that somebody would find a clue in the debug logs.

> If I well understand you says that you are not able to do 2 successive handshakes, but I'm lost about what is exactly the scenario. I mean I remember I already succeed to make 2 successful handshakes using tinyDTLS as client and scandium as server.

So it's most likely something with the underlaying OS or anything else strange.

**Comment by boaks** [comment]
[docker/openssl/second DTLS client](https://stackoverflow.com/questions/58104244/dtlsv1-listen-unable-to-accept-second-client-in-a-docker-container)

With some luck, this is related and solved before the end of week ;-).

**Comment by paxter** [comment]
Indeed, that sounds similar to my issue. Thanks for sharing the link @boaks. I will monitor this thread. :)

**Comment by boaks** [comment]
Which value does the Californium.properties contain for `MAX_ACTIVE_PEERS`?

**Comment by paxter** [comment]
I'm using the default settings. So it's `MAX_ACTIVE_PEERS=150000`.

**Comment by boaks** [comment]
OK, I just want to ensure, that this doesn't cause your issue.
