### ISSUE TITLE
How to send multicast message to Thread Nodes?

### ISSUE THREAD

**Issue by tarunsmalviya** [eclipse/californium#1076]
I am using Californium CoAP server for receiving CoAP packets coming from [thread network](https://openthread.io/guides/border-router/raspberry-pi-3b) in Raspberry Pi 3b. 

I am able to send a packet from RPi to Thread device successfully after appending interface to URI like `coap://[fddf:dd::1c2:2233:6b2:4189%wpan0]:5683/d`.

Now, the issue is that I am unable to send multicast message, i.e. using URI `coap://[ff03::1%wpan0]:5683/d`. I checked the tcpdump logs, there are no packet traces.

**Comment by boaks** [comment]
Which version of californium you are using?

What is your setup? Does Californium run on your RasPi? Is that in the "local open thread" network?

Do you have packet traces on the californium host (Raspi)?

Did you try a normal request? do they work?

**Comment by boaks** [comment]
@tarunsmalviya 

I would like to help you, but without more information I don't know how.

**Comment by tarunsmalviya** [comment]
@boaks Apologies for delay in response.

I am using `californium-core-2.0.0-M12.jar` library.

I have configured RPi as border router as explained on openthread.io website. I have created a dummy interface having IP 10.0.0.1. A SED is sending data to this address and a CoAP server(californium) is listening to this on 5683 port.

I was able to send a packet from RPi to Thread device successfully after appending interface to URI like coap://[fddf:dd::1c2:2233:6b2:4189%wpan0]:5683/d (I am using Californium CoAP server).

Now, the issue is that I am unable to send multicast message, i.e. using URI coap://[ff03::1%wpan0]:5683/d. I checked the tcpdump logs, there are no packet traces.

Kindly let me know what extra information you want to know.

PFA for wpan0 and nat64 interface traces.

[packet_traces.zip](https://github.com/eclipse/californium/files/3676373/packet_traces.zip)

**Comment by boaks** [comment]
According PR #839 , I assume , multicast was brought back in 2.0.0-M13.
Though we frequently fixed issues, I strongly recommend to use 2.0.0-M17.
Any reasons to stick to the old milestone?

**Comment by boaks** [comment]
If it's possible for you to switch to a newer milestone, you may use
 
[MulticastTestClient](https://github.com/eclipse/californium/blob/master/demo-apps/cf-helloworld-client/src/main/java/org/eclipse/californium/examples/MulticastTestClient.java)

to check the multicast feature.
Don't hesitate to report issues, if they could be (re-)produced with our current 2.0.0-M17.

**Comment by boaks** [comment]
Do you still have this issue? Even with 2.0.0-M17? Or could this issue be closed?

**Comment by tarunsmalviya** [comment]
@boaks Please give me some time to test. I will update here in few days.

**Comment by boaks** [comment]
> Please give me some time to test.

Sure. 

> I will update here in few days.

Your update will be very welcome.

**Comment by boaks** [comment]
2.0.0-M18 is released! 

#1091 

I would appreciate it, if that could be tested and your feedback would address that version.

**Comment by boaks** [comment]
Hi @tarunsmalviya ,

have you been able to spend time into it?
Do you have an update for us?

**Comment by tarunsmalviya** [comment]
@boaks I tried sending multicast message to thread node using above example but failed. The example you mentioned in previous comment is for sending IPv4 multicast message.

**Comment by boaks** [comment]
> The example you mentioned in previous comment is for sending IPv4 multicast message.

Did you consider to adjust the example for ipv4 multicast-address to your ipv6 multicast-address?

The capture in my comment above [Multicast Request with M17](https://github.com/eclipse/californium/files/3678418/M17.zip) contains a ipv6-multicast-request. It was sent by that example, when I modified it slightly using a ipv6 multicast address.

**Comment by boaks** [comment]
Don't hesitate to open a new issue, if you still have troubles with ipv6 multicasts,

**Comment by boaks** [comment]
With PR #1171 ipv6 multicast now works even "out of the box".

**Comment by kentsimp** [comment]
Hi @boaks and @tarunsmalviya,

Sorry to re open this thread, but I am trying to do exactly the same as your scenario but having an issue with the multicast adapter/address selection.

> I am using Californium CoAP server for receiving CoAP packets coming from thread network in Raspberry Pi 3b.

I am using the multicast example [here](https://github.com/eclipse/californium/blob/master/demo-apps/cf-helloworld-server/src/main/java/org/eclipse/californium/examples/MulticastTestServer.java)

But when the startup sequence logs the selected adapter & address, I only see it binding to eth0, and not the wpan0 network (which I think is what I need to make this work).

This is from the logs:

`Multicast Network Interface: eth0
Multicast: IPv6 Network Address: fe80:0:0:0:bf91:1d30:51ad:8d20%eth0`

Would you mind posting the implementation of the multicast server you used to successfully receive multicast requests from the wpan0/thread network?

Thanks in advance!!

**Comment by boaks** [comment]
I'm not sure, if it works, but the idea was to use [COAP_NETWORK_INTERFACES](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/NetworkInterfacesUtil.java#L123) to select the network interfaces. Provide a regex for your network interface. So, if possible, please try

```sh
java -DCOAP_NETWORK_INTERFACES='.*wpan0' -jar target/cf-helloworld-server-2.5.0-SNAPSHOT.jar MulticastTestServer
```

**Comment by boaks** [comment]
@kentsimp 

Could you check, if that regex works for you?

**Comment by kentsimp** [comment]
Hi @boaks ,

Yes it does address my issue, very nicely - thank you.

FYI, I tried to add this to the readme but getting a 403 on my push so assume I have missed on of the contribution steps.

----------------------------------

# Adapter Selection

For some systems (particularly when multicasting), it may be necessary to specify/restrict californium to a particular network interface, or interfaces. This can be achieved by setting the `COAP_NETWORK_INTERFACES` JVM parameter to a suitable regex, for example:
 
`java -DCOAP_NETWORK_INTERFACES='.*wpan0' -jar target/cf-helloworld-server-2.5.0-SNAPSHOT.jar MulticastTestServer`

**Comment by boaks** [comment]
> 403 on my push 

Thanks! Very welcome. I will add that, now someone has "validated" it :-).

Just, if you plan to help to improve Californium in the future, the Eclipse Foundation uses a [contribution](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md) process. That mainly requires a [ECA](http://www.eclipse.org/legal/ECA.php).

**Comment by boaks** [comment]
If you want to contribute your documentation, just let me know, I will wait for the PR.
Let me also know, if you don't want to, so that I can add it on my own.

**Comment by kentsimp** [comment]
Here is the PR: https://github.com/eclipse/californium/pull/1430

Thanks again for your help.

**Comment by boaks** [comment]
You're welcome. Can we close the issue again?

**Comment by kentsimp** [comment]
Yes we should close it now.
