### ISSUE TITLE
Unregistered CoAP-Content Types are defined

### ISSUE THREAD

**Issue by jimsch** [eclipse/californium#1078]
In going through a different code based that was originally based on Californium, I noted that the following CoAP Content Types were define there but are not in fact registered by IANA.  These values where were dropped during the development of the original CoAP document should be either removed or moved to a new private value space.  (I intend to just remove them.)

There is an effort going on to get a sweep of all of the known media-types registered, however when that is done different values will be assigned to these content formats.

Text/xml = 1
Text/csv = 2
Text/html = 3
Image/Gif = 21
Image/Jpeg = 22
Image/png = 23
Image/tiff = 24
Audio/Raw = 25
Video/Raw = 26
Application/rdf+xml = 43
Application/soap+xml = 44
Application/atom+xml = 45
Application/fastinfoset = 48
Application/soap+fastinfoset = 49
Application/x-obix-binary = 51

**Comment by boaks** [comment]
Thanks!

[IANA - CoAP Content Formats(https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats)

> There is an effort going on to get a sweep of all of the known media-types registered,

Does this ongoing effort affect that list?

**Comment by jimsch** [comment]
As I said, they will all get new values at that point, probably greater than 255.  You can track the new registrations with the draft https://datatracker.ietf.org/doc/draft-bormann-core-proactive-ct/, but as you can see it has not yet become a working group document.

**Comment by boaks** [comment]
OK, I think 1 milestone deprecate and then remove it would be the best FMOPV.

**Comment by boaks** [comment]
Deprecated.

**Comment by boaks** [comment]
Remove in master.
