### ISSUE TITLE
Do we have any metric support plan

### ISSUE THREAD

**Issue by joechen2010** [eclipse/californium#1079]
currently, there is no metric in californium, actually, we want to know the counter of notification, observation, dtls session, authentication success/fail counter...

**Comment by boaks** [comment]
DTLS:
See `ConnectionListener` it's passed in with `DtlsConnectorConfig`.

Coap - general messages:
See `MessageInterceptor` it's passed in at the `CoapEndpoint`.

Coap - observes - coap-server side:
See `ResourceObserver` it's passed in at the `Resource`.

**Comment by sbernard31** [comment]
DTLS hanshake : 
See `SessionListener` it's passed by surcharging `DTLSConnector.onInitializeHandshaker()`

**Comment by boaks** [comment]
Did the answers help you?
Do you have additional questions?
If not, could this issue be closed?

**Comment by sophokles73** [comment]
It would be nice to have some implementations of these listeners which e.g. report metrics using Prometheus. WDYT?

**Comment by sbernard31** [comment]
> It would be nice to have some implementations of these listeners. 

It would, but if this means enlarge a bit more the scope of the project and so more tests and maintenance (in this case this is maybe not so big).

If we decide to add this, I would not include this in the 2.0.0.

About the choice of the implementation : 
 - I never played with Prometheus. (so I don't know if this is a good choice, maybe it is)
 - at sierra we used https://metrics.dropwizard.io/4.1.0/index.html

**Comment by sophokles73** [comment]
> If we decide to add this, I would not include this in the 2.0.0.

I agree, this would be post 2.0.0.

> I never played with Prometheus. (so I don't know if this is a good choice, maybe it is)

Prometheus is actually the metrics back end, i.e. the time series DB where you collect the metrics data.
Within Californium, we would use something like Dropwizard (which we originally also used in Eclipse Hono) or maybe [Micrometer](https://micrometer.io) which we migrated to because it seemed to be more flexible with regards to tags and back end connectivity.
