### ISSUE TITLE
warning :  "new request could not be registered!"

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1082]
(using californium-2.0.0-M16)

We are facing several raised by UdpMatcher: `new request could not be registered!`

Reading the code,  I understand that happens at "deduplicating" time when an MID+address is reused by a different peer. In that case the new request is not "registered" and deduplication will not be available for this one. Is that right ?

**Comment by boaks** [comment]
```
// the new context doesn't match the previous.
exchangeStore.remove(idByMID, previous);
if (exchangeStore.findPrevious(idByMID, exchange) != null) {
	LOGGER.warn("new request could not be registered!");
}
```

with a closer look:
That `remove` affects the `exchangesByMID` but the `findPrevious` the `deduplicator`.
So the workaround of issue #837 is buggy ...
The intention was to remove the deprecated exchange and try the new one ...
I will fix it ...

**Comment by boaks** [comment]
But your analysis of the current behaviour is right, as far as I understand. But not my intended one.

**Comment by sbernard31** [comment]
The intended would be : remove/drop any information about the previous request ? and register the new one ?

**Comment by boaks** [comment]
yes

**Comment by sbernard31** [comment]
I suppose you will keep the warning, in that case please could you log related requests. (I would like to see which request is replaced by which)

**Comment by boaks** [comment]
OK.

**Comment by sbernard31** [comment]
I get it around 7 by hour. It's hard to me to know if this is a "normal" situation.

**Comment by boaks** [comment]
OK. The probability **AFTER THE NEW FIX** for that message should be very small,

**Comment by sbernard31** [comment]
I was talking about the request replacement itself not about the failure of the replacement. :)

**Comment by boaks** [comment]
Then I didn't get, what you want to say/ask.
Should the exchange be not replaced? Do you have an other preference?
With the new KeyMID using the Principal as peer I would guess, that you will have less such warnings. And with the new "replace" in #1083 also. 
So I'm not sure, if there is something left, you want to know?

**Comment by sbernard31** [comment]
No I think it's ok. :+1: 
I agree with the behavior expected.
And #1083 should implement it + add a log to see which request is replaced by which.
