### ISSUE TITLE
Timestamp on request ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1085]
There is a get/setTimestamp  on `Message`.

I was expected that was the date where the request was sent. I wanted to use it to know if I was handling an "old" request.

But it seems this is never set.
Should we set this value ? or remove those setter/getter ? or keep it to let user to what ever they want with it (this one sounds a bit strange) ?

**Comment by boaks** [comment]
After  reconsider the current implementation, I think to adapt the code again.
It's not only the token or mid, which are modified by different threads.
It's more "close to all", sent error, timeout, sent, sometimes cancel, ACK, RST.
So from that point of view, my intention to process the timestamp different is some how ridiculous. I would go to rename it back to timestamp, set it, and I think we need also some additional waits ( waitSent, waitCompleted).
WDYT?

**Comment by sbernard31** [comment]
Go back to timestamp naming ? Just set it without taking account which thread modify it ?
==> no objection.

Not clear to me what is about waitSent waitCompleted and how this is related this this.

Bonus question, what will contain timestamp attibutes? the time we send or receive the message ?

**Comment by boaks** [comment]
> Not clear to me what is about waitSent waitCompleted and how this is related this this.

Though someone may like to wait for the timestamp to contain a valid value, a Message may provide such additional waits.

> Bonus question, what will contain timestamp attibutes? the time we send or receive the message ?

Outgoing: just before send
Incoming: just after receive

**Comment by sbernard31** [comment]
Wait would be mainly used for tests ?

OK sounds good.

**Comment by boaks** [comment]
See PR #1092
