### ISSUE TITLE
Peer address update in 2.0.0-M15/M16

### ISSUE THREAD

**Issue by Philago** [eclipse/californium#1094]
Hello @boaks ,

with the latest discussions regarding peer address update (https://github.com/tlswg/dtls-conn-id/pull/70), I'm a little bit lost on what 2.0.0-M15/M16 does regarding peer address update.

In 2.0.0-M15/M16 the peer address is updated with each received record (are the records in the enclosing datagram cryptographically validated before or not ?) ?
And with 2.0.0-M17 and later versions peer addresses are only updated for newest tls12_cid records ? Am I correct ?

Thank you for thhe clarifications

Philippe

**Comment by boaks** [comment]
The commit 48aa680f6b1c74ba28e90a7a23b0d29e3da9cda9 introduces to update the address only for newer records. That commit was merged according git on 2019-07-30.
So, only 2.0.0-M17 contains it.
Earlier versions should have updated the address, when it successfully passes the anti-replay filter.

**Comment by boaks** [comment]
> In 2.0.0-M15/M16 the peer address is updated with each received record (are the records in the enclosing datagram cryptographically validated before or not ?) ?

As far as I remember, I always have checked the  cryptographically validated (including the anti replay protection, if enabled) before the address got updated.

> And with 2.0.0-M17 and later versions peer addresses are only updated for newest tls12_cid records ? Am I correct ?

That is the default behaviour and maybe changed using the dtls configuration
`setCidUpdateAddressOnNewerRecordFilter` 

I'm also a bit lost. When things are discussed, IANA registration are pending, early implementations are mainly for exploring the new function and providing feedback to the specification. I just don't know the exact behaviour of older version. I'm focus on the new ones. The new IANA value of the hello extension was anyway a breaking change.

**Comment by boaks** [comment]
2.0.0-M15

`DTLSConnector.processApplicationDataRecord`

```
**1 if (!useFilter || session.isRecordProcessable(record.getEpoch(), record.getSequenceNumber(), useWindowFilter)) {
	try {
		// APPLICATION_DATA can only be processed within the context of
		// an established, i.e. fully negotiated, session
		record.setSession(session);
**2		ApplicationMessage message = (ApplicationMessage) record.getFragment();
		// the fragment could be de-crypted, mark it
		session.markRecordAsRead(record.getEpoch(), record.getSequenceNumber());
		if (ongoingHandshake != null) {
			// the handshake has been completed successfully
			ongoingHandshake.handshakeCompleted();
		}
		connection.refreshAutoResumptionTime();
**3		connectionStore.update(connection, record.getPeerAddress());
```

**1: check record sequence number for replay attack (if enabled)
**2: decrypt/check MAC
**3: update address after **1 and **2

**Comment by boaks** [comment]
2.0.0-M16

Same as in 2.0.0-M15, the relevant checks haven't changed.

The newer milestones offers more security updates. Consider to check the upcoming 2.0.0-M19 to support the quality for the scheduled release of 2.0.0 in December.

I hope, that is the information your looking for. Could this issue be closed then?

**Comment by Philago** [comment]
Hello,

thank you for your answers, it's clear now.

yes this issue can be closed

**Comment by boaks** [comment]
Just for your information:

The #1424 gets more and more available.

[built-in CID-load-balancer](https://github.com/eclipse/californium/tree/wip_dtls_cid_cluster/demo-apps/cf-extplugtest-server#built-in-dtls-connection-id-load-balancer-cluster)

Feedback is very welcome.
