### ISSUE TITLE
Memory leak in InMemoryConnectionStore ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1099]
Since we are deploying cf-2.0.0-M16 we notice that memory consumption increase significantly.
After few days (less than a week), heap is full and garbage collector use all the CPU trying to make some space ^^. (In our case, the instance is killed and redeployed automatically without real issue)

Doing some heap dump, I see some suspect values in `InMemoryConnectionStore`.

The `LeastRecentlyUsedCache` capacity is set to 100 000.
The size is around 99998. (That's ok.)

But looking at `connectionsByAddress` the size is 181883 and for `connectionsByEstablishedSession` the size is 460429.

I didn't try to reproduce this locally for now.

**Comment by sbernard31** [comment]
Reading the code quickly my first bet would be :
When "a put in LRUCache" replaces a value,  `connectionByAddress` and `connectionByEstablishedSession` sounds not be cleaned.

But this should only happen on connectionId collision. :thinking:

**Comment by sbernard31** [comment]
Ok my first bet was not so good.
It seems the issue is more simple than that this [`if (sessionCache != null)`](https://github.com/eclipse/californium/blob/2.0.0-M18/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/InMemoryConnectionStore.java#L157) prevent to cleaning this map if we don't use `SessionCache`.

About my comment just above, I will investigate a bit more about.

**Comment by sbernard31** [comment]
:warning: This is not directly linked to the memory leak and this is not really an issue :warning: 

Following the https://github.com/eclipse/californium/issues/1099#issuecomment-542669928 idea, I finally understand there is no way to do a `LRUCache.put()` which will do a replace.
But by curiosity, I do some math about connectionID generation and connectionStore size to see if we could have collision issue. :mag: 

With my use case connectionStore size = 100.000, the [default algorithm](https://github.com/eclipse/californium/blob/2.0.0-M18/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/InMemoryConnectionStore.java#L238) generates a 5 bytes conID.
This means that when the store is full, we get [~0,45%](https://www.wolframalpha.com/input/?i=1-e%5E%28-100000%5E2%2F%282*2%5E40%29%29) to get a conflict, which is pretty high but 
[which is also not a big deal as we retry 10 times until we get a free ID](https://github.com/eclipse/californium/blob/2.0.0-M18/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/InMemoryConnectionStore.java#L218). Finally the probability to not be able to create conID is very very low [~3.69×10^-24]((1-e^(-100000^2/(2*2^40)))^10)

Regarding the code,
```java
int bits = Integer.SIZE - Integer.numberOfLeadingZeros(connections.getCapacity());
int cidLength = ((bits + 7) / 8) + DEFAULT_EXTRA_CID_LENGTH
```
The formula to calculate CID size from connectionStore capacity is something like this :
```
(1+floor(log2(x))+7)/8+2  (in bytes)
```
(because : floor(log2(x)) = 31 - numberOfLeadingZeros(x) and DEFAULT_EXTRA_CID_LENGTH=2)

So using the [birthday paradox approximation](https://en.wikipedia.org/wiki/Birthday_problem#Approximations), we can define a function which give the probability of CID collision(when the store is full) given the connectionStore capacity, this should be something like this.
```
f(x) = 1-e^(-x^2/(2*2^cid_size_in_bits))
f(x) = 1-e^(-x^2/(2*2^(8*((floor(log2(x))+8)/8+2))))
```

Here is the result : 
![conid_collision](https://user-images.githubusercontent.com/840294/66936240-a5645c80-f03d-11e9-9928-4f9fe39a5332.png)
(image done with [mathe-fa](https://www.mathe-fa.de/), formula : 1-E^(-x^2/(2*2^(8*((floor(ld(x))+8)/8+2))) )

Now what is the probability to not being able to create a connectionID :  
![unable_to_create_conid](https://user-images.githubusercontent.com/840294/66937309-86ff6080-f03f-11e9-9c02-3153402e462f.png)

(formula : (1-E^(-x^2/(2*2^(8*((floor(ld(x))+8)/8+2))))^10 )

So I think there is no collision issue here unless you are using very large connectionStore.
I give a quick look and I see that for 10.000 connections I use ~ 35/40MB so 1.000.000 means something like 3,5/4GB which sounds realistic, 10.000.000 probably less...

**Comment by sbernard31** [comment]
I succeed to reproduce a leak of those maps locally, this PR #1100  should fix the issue.

Regarding the code it seems the [issue is present since cf-2.0.0-M14](https://github.com/eclipse/californium/blob/2.0.0-M14/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/InMemoryConnectionStore.java#L163).

So for now I can not explained why this is only clearly visible in production since we deployed cf-2.0.0-M16. :thinking:  (maybe another issue involved ?)

(We will deploy a workaround by using a fixed InMemoryConnectionStore in production and we will see if this fixes the issue)

**Comment by boaks** [comment]
> But this should only happen on connectionId collision. 

The LRU.put may be affected by collisions, but the two places where it is called are either using new cid from `newConnectionId` where the collision is checked ahead by `LRU.get() == null`, or, if the cid is already provided by the connection, checked also with `LRU.get() != null`. So, collisions should not happen ...

**Comment by sbernard31** [comment]
> So, collisions should not happen ...

That's what I finally found in https://github.com/eclipse/californium/issues/1099#issuecomment-542785530 : _"I finally understand there is no way to do a LRUCache.put() which will do a replace."_

But I was curious to see how `newConnectionId` should behave (what is the probability it does not find the cid at first try and what is the probability it does not succeed with 10 tries)

**Comment by boaks** [comment]
My intention was to use 2 bytes more, than the number of connections would require. that should result in 1/64K probability for the 1. try. and I used 10 retries but without thinking too much on it.

Do you see any issue with that?

**Comment by sbernard31** [comment]
> Do you see any issue with that?

If my math are correct, there is no issue as long as you are not using very large store.
If I'm wrong and there is an issue we will see : `"Connection ids exhausted!"` or `drop session {} {}, could not allocated cid!`
(maybe we could add a log when we don't find free conID at first time in `newConnectionId`? :thinking: )

**Comment by boaks** [comment]
Maybe it's better to add more bytes, if the number is larger?

**Comment by sbernard31** [comment]
> Maybe it's better to add more bytes, if the number is larger? 

Yep, just adding 1 byte will decrease significantly the risk to get collision.
- :large_blue_circle: DEFAULT_EXTRA_CID_LENGTH = 2
- :red_circle: DEFAULT_EXTRA_CID_LENGTH = 3

![conid_collision_3bytes](https://user-images.githubusercontent.com/840294/67383017-bd346700-f58e-11e9-9f40-fb667a0281b6.png)

**Comment by boaks** [comment]
So fixed 3 would be "short-cut"?

**Comment by sbernard31** [comment]
> So fixed 3 would be "short-cut"?

I don't see what you mean ?

**Comment by boaks** [comment]
I mean "3 extra bytes cid". In the meantime I adapted it with 2 bytes up to 64K, 3 bytes for larger capacities.
