### ISSUE TITLE
getKey(identity) from PSKStore is never used ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1101]
I integrated cf-2.0.0-M18 in Leshan master and see some test failing.

This is because I have some pskStore which does not implement `PskStore.getKey(ServerNames, PskPublicInformation)`.
I don't think to much how to integrate SNI in Leshan, so for now this is deactivated and so this sounds not a problem to not implement this method.

But since cf-2.0.0-M18, the other `PskStore.getKey(PskPublicInformation)` method is never called. Only the `serverNames` version is called.

So my question 
1. should we fix this ?
 2. or remove the `PskStore.getKey(PskPublicInformation)` and explain in the javadoc how this should behave when SNI is deactivated ?

(the "issue" is probably in [`PskUtil`](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/PskUtil.java#L77))

**Comment by boaks** [comment]
#1102 is merged, so the issue should be fixed.

**Comment by boaks** [comment]
@sbernard31 

Can we close this?

**Comment by sbernard31** [comment]
Yep
