### ISSUE TITLE
DTLS server only by message ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1104]
Currently there is a way to configure DTLSConnector in a way it acts as a `client only` or a `server only` or `both`.

With LWM2M, I think a server might want to act as `both` for device using U binding and `server only` for device using UQ binding.

Should it make sense to add a way to configure this maybe by adding a parameter in endpoint context like for `KEY_RESUMPTION_TIMEOUT` ?

**Comment by boaks** [comment]
Maybe I'm not sure, what the exact situation is.
Does scandium have a Connection with EndpointContext for such "UQ" clients? 
if yes, what triggers then the handshake? 
If there is no EndpointContext, but the Messages uses a EndpointContext with a principal set, isn't that already denied instead of triggering a handshake?
So, maybe, if you just set or not set the principal in the EndpointContext, you may already have the behavior. Or do I miss something?

**Comment by sbernard31** [comment]
> Does scandium have a Connection with EndpointContext for such "UQ" clients?

It does not have a DTLS connection but it have a registration.

> if yes, what triggers then the handshake?

A request we need to send to it. 

> If there is no EndpointContext, but the Messages uses a EndpointContext with a principal set, isn't that already denied instead of triggering a handshake?

No with "both" mode, this will not deny. If there is no connection and a Endpointcontext set. We try to handshake and at the end of the handshake we check the endpointContext.

> So, maybe, if you just set or not set the principal in the EndpointContext, you may already have the behavior.

We always send the endpointcontext.

----------------------------------------------------
To be clearer, the case is : 
- device does an handshake.
- device does an update
- server starts to send it requests.
- device answers and before we finished to sent it all requests.
- it close the dtls connection (close notify) => this does not really respect the specification.
- server tries to send the next request
- no dtls connection, so server starts an handshake which will timeout. (device is sleeping)

This is 1 example where DTLS connection is lost. I suppose we can imagine other.
And so it seems to me that especially for QueueMode, this does not makes sense to try to initiate a handshake, I would prefer to fail fast.

Does it makes sense ?

**Comment by boaks** [comment]
That behaviour seems to be the difference between:

[PrincipalEndpointContextMatcher](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/PrincipalEndpointContextMatcher.java#L63)

[KeySetEndpointContextMatcher](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/KeySetEndpointContextMatcher.java#L95)

For the standard, the message with critical entries will be dropped, for the other it will trigger a handshake. I have to think more about it ...

**Comment by sbernard31** [comment]
From my side, when you acts as a client, It makes senses that :
- if you set an endpoint context and no connection is present you start an handshake and check endpoint context after this.

**Comment by boaks** [comment]
If the connection-context is missing, the match is executed twice. First with `null`, then, after the handshake, with the resulting context. For the Principal, the new context may contain the provided principal. But for the session based, it's extremely unlikely, that the new session has the same id. Therefore the first match already drops the message and doesn't start a handshake.

**Comment by boaks** [comment]
If the PR #1107 solves this, I would go to add unit tests to the PR.

**Comment by sbernard31** [comment]
Yep you can add unit tests, #1107 is on the right track :)

**Comment by boaks** [comment]
@sbernard31 

Is this issue solved? If yes, could it be closed?
