### ISSUE TITLE
Do DTLSConnector support message retransmit?

### ISSUE THREAD

**Issue by pear-li1015** [eclipse/californium#1112]
I'm trying to use Californium DTLSConnector to send messages to a localhost server. When I send these messages at a high speed, some messages just lose by the server. And I didn't find the retransmit act by DTLSConnector.
Then, I tried to use MessageCallback in package org.eclipse.californium.elements and the method onDtlsRetransmission(int flight) or onError(Throwable error) didn't call by any thread. And I also tried to send the second message after the method onSent() is called. 
I reviewed the MessageCallback carefully. And I find the method onDtlsRetransmission(int flight) only called when the DTLSConnector retransmits a handshake flight. 
So, how to use Californium retransmit DTLS encrypted messages, when time out?

My code.
``` Java Client
public class PureDtlsCoapClient {
void startSendMessage() {
        isRunning.set(true); // to sign out if the client is running
        Message message = null; // the message will be send
        while (true) {
            if (isUseAble.get()) { // will be true after the method onSent() in Callback is called
                if ((message = CoapMessageList.getMessage()) != null) {
                    RawData data = RawData.outbound(message.getData(), new AddressEndpointContext(message.getSocketAddress()),
                            new CoAPMessageCallback(dtlsConnector, this), false);
                    System.out.println(Thread.currentThread().getName() + " client send a message -- " + new String(message.getData()) + " -- current message amount " + CoapMessageList.getMessageAmount());
                    dtlsConnector.send(data);
                } else {
                    System.out.println(Thread.currentThread().getName() + " .get message is null. ");
                    isRunning.set(false); // return this thread to the pool.
                    break;
                }
            }
        }

    }
}
```
```CoAPMessageCallback 
public class CoAPMessageCallback implements MessageCallback {
    DTLSConnector dtlsConnector;
    Message message;
    PureDtlsCoapClient client;

    public CoAPMessageCallback(DTLSConnector dtlsConnector, PureDtlsCoapClient client) {
        this.dtlsConnector = dtlsConnector;
        this.client = client;
    }
@Override
    public void onSent() {
        client.isUseAble.set(true);  // client could send message only if isUseAble.get() is true 
    }
}
```

**Comment by boaks** [comment]
[DTLS 1.2, RFC6347](https://tools.ietf.org/html/rfc6347) doesn't define such a retransmission, but supports message loss and retransmission by the next layer.
If CoAP is used, and the message is sent as CON, then retries are used. For DTLS 1.2 the record for the one message is just lost, and the retry is packed into a next record.

**Comment by boaks** [comment]
The `onDtlsRetransmission(int flight)` is only called for handshake-record-flights, because their retransmission is defined in DTLS 1.2.

**Comment by pear-li1015** [comment]
thanks for your help.
