### ISSUE TITLE
How to fix the Token ?

### ISSUE THREAD

**Issue by chejdj** [eclipse/californium#1113]
version: 2.0.0-M12
problem: The token is generated by `RandomTokenGenerator` , it is random.  Are there a way to provide the request Token by me??

**Comment by boaks** [comment]
2.0.0-M12 is one year old and currently we have release the 2.0.0-M18.

With 2.0.0-M18 you just set the token in the request, complying to the "scope convention" of the `TokenGenerator`. 
Using the default `RandomTokenGenerator` the first two bits of the first byte are used to encode the scope: [scoped token](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/RandomTokenGenerator.java#L75)

For application provided tokens, the [`getScope`](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/RandomTokenGenerator.java#L82)  defines the resolution. So just use a shorter token and usually that should do it.

**Comment by chejdj** [comment]
Thank you so much. But I think you should make a detail document.
