### ISSUE TITLE
M18 breaks DTLS-PSK lookup with sniEnabled=false

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#1117]
The client-side lookup of PSK in a DTLS psk handshake breaks when SNI is not used, when using the InMemoryPskStore.

The reason is that when the PSK is added to the InMemoryPskStore using the store.addKnownPeer(InetSocketAddress, String, byte[]) method, this in turn calls the 
addKnownPeer(InetSocketAddress, ServerName, String, byte[]) method with ServerName == GLOBAL_SCOPE == (NameType.UNDEFINED, Bytes.EMPTY)

However when the client tries to do a lookup for the corresponding key, the constructor of 
PskUtil tries to lookup the PSK with this line:

pskSecret = pskStore.getKey(session.getServerNames(), pskIdentity);

and the server name in session.getServerNames() is not emtpy like in GLOBAL_SCOPE.

I haven't yet been able to track down where the exact mismatch is created, but somewhere where session.ServerNames is populated something goes wrong.

**Comment by LudwigSeitz** [comment]
This is probably related to #1101

**Comment by LudwigSeitz** [comment]
I've got the culprit now:
DTLSSession.setVirtualHost(String hostname) is setting a ServerName in the serverNames member using the hostname, while InMemoryPskStore.addKnownPeer(InetSocketAddress, String, byte[]) creates a server name based on GLOBAL_SCOPE. 

Strange I would have thought this would have been covered by a Junit test.

**Comment by boaks** [comment]
> Strange I would have thought this would have been covered by a Junit test.

If #1102 is not solving your issue, and if it's possible, please check [DTLSConnectorHandshakeTest](https://github.com/eclipse/californium/blob/master/scandium-core/src/test/java/org/eclipse/californium/scandium/DTLSConnectorHandshakeTest.java). Maybe you can put your scenario in a unit test. Or at least help me, to understand, what exactly is missing.

**Comment by LudwigSeitz** [comment]
Have a look at this: https://github.com/LudwigSeitz/CF-Test

This is an extract of my library that used to work with code prior to M18. The only really interesting part of the code is the DtlsClient, since the whole mismatch is exclusively there.

The problem is the when I add a key to the client's pskStore with .addKnownPeer() the lookup to find that peer later when I try to do the handshake doesn't work anymore.  The reason seems to be that when the key is added with addKnownPeer() it uses GLOBAL_SCOPE, when it does the lookup, it gets some other ServerName from the DTLSSesssion.

**Comment by boaks** [comment]
```
  <properties>
	<snapshotDependencyAllowed>true</snapshotDependencyAllowed>
	<californium.version>2.0.0-SNAPSHOT</californium.version>
	<logback.version>1.2.3</logback.version>
  </properties>
  <dependencies>
   	<dependency>
		<groupId>org.eclipse.californium</groupId>
		<artifactId>californium-core</artifactId>
		<version>${californium.version}</version>
	</dependency>
	<dependency>
		<groupId>org.eclipse.californium</groupId>
		<artifactId>scandium</artifactId>
		<version>${californium.version}</version>
	</dependency>
	<dependency>
		<groupId>ch.qos.logback</groupId>
		<artifactId>logback-classic</artifactId>
		<version>${logback.version}</version>
		<scope>runtime</scope>
	</dependency>
  </dependencies>
```

Using 2.0.0-M18 fails, using the current "master" SNAPSHOT works.
