### ISSUE TITLE
2.0.0-RC1 Released

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1118]
I would like to release Californium 2.0.0-M19 (RC1) next Thursday 7.11.2019.

The 2.0.0-M18 had 3 bugs and 1 extension was added.

So, next try for a RC1.

**Comment by boaks** [comment]
Current status:

Recently detected issues:
- stopping the DTLSConnector using an external executor shows race conditions, though the job already passed to the executor and the jobs, which are pending in the serial execution may be executed simultaneously.
- rare leaks in MessageExchangeStore, CON responses

```
DEBUG [health]: coaps MessageExchangeStore contents: 4 exchanges by MID, 0 exchanges by token, 0 MIDs.
DEBUG [health]:   KeyMID[/127.0.0.1:56755, 47562], Exchange[R62267312], retransmission 0, CON-POST   MID=39123, Token=A8CB3479E653185F, OptionSet={"Uri-Host":"localhost", "Uri-Path":"reverse-observe", "Uri-Query":["obs=25000","res=feed-NON","rlen=400"]}, no payload, CON-5.00   MID=47562, Token=A8CB3479E653185F, OptionSet={}, no payload
DEBUG [health]:   KeyMID[/127.0.0.1:34609, 43396], Exchange[R62267461], retransmission 0, CON-POST   MID=29530, Token=D094F029E2F97B47, OptionSet={"Uri-Host":"localhost", "Uri-Path":"reverse-observe", "Uri-Query":["obs=25000","res=feed-NON","rlen=400"]}, no payload, CON-5.00   MID=43396, Token=D094F029E2F97B47, OptionSet={}, no payload
DEBUG [health]:   KeyMID[/127.0.0.1:36978, 17499], Exchange[R62267441], retransmission 0, CON-POST   MID= 4047, Token=54B601015CEF28EF, OptionSet={"Uri-Host":"localhost", "Uri-Path":"reverse-observe", "Uri-Query":["obs=25000","res=feed-NON","rlen=400"]}, no payload, CON-5.00   MID=17499, Token=54B601015CEF28EF, OptionSet={}, no payload
DEBUG [health]:   KeyMID[/127.0.0.1:45693, 63679], Exchange[R62267460], retransmission 0, CON-POST   MID=18076, Token=FCC9DB210E1774AD, OptionSet={"Uri-Host":"localhost", "Uri-Path":"reverse-observe", "Uri-Query":["obs=25000","res=feed-NON","rlen=400"]}, no payload, CON-5.00   MID=63679, Token=FCC9DB210E1774AD, OptionSet={}, no payload
```

FMPOV, the 1. may be postponed, the 2. may be fixed after 2.0.0-M19

**Comment by boaks** [comment]
@sbernard31 

Just to mention.
I create some PRs. Many are very simple and only affects the logging.
I would appreciate, if could have a look first at the simple ones, so that they could be merged.
Some PRs are currently based on each other. But each PR should have it's "single own commit". So If you feel, that that commit could not be fast "reviewed", just remove the "merged soon". I will then try to isolate the changes of that PR, hopefully based on some PRs already merged.

**Comment by sbernard31** [comment]
I will look at this !

**Comment by boaks** [comment]
2.0.0-RC is available in the eclipse repo.

**Comment by boaks** [comment]
And now 2.0.0-RC1 is also available in the maven central repo.

**Comment by boaks** [comment]
> rare leaks in MessageExchangeStore, CON responses

It seems to be caused by [exchange-cleanup for responses](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/stack/ExchangeCleanupLayer.java#L76). If the type is not already set, then the cleanup doesn't work. That seems to be common, the reliability layer set the type frequently. I adjusted that check. After the epl 2.0 update, I will prepare a PR for that.

**Comment by boaks** [comment]
> rare leaks in MessageExchangeStore, CON responses

See PR #1138

**Comment by boaks** [comment]
Replaced by 2.0.0-RC2, see #1143
