### ISSUE TITLE
Release 2.0.0 - planned schedule December 05. 2019

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1131]
Californium is preparing for release 2.0.0!

After two years of extending and testing, we believe it's good enough to replace the 1.0 release.
For details about the supported features see [Release 2.0.0](https://projects.eclipse.org/projects/iot.californium/releases/2.0.0).

The first step toward the release will be the [2.0.0-M19 RC1](https://github.com/eclipse/californium/issues/1118) release on Thursday November 7. 2019. I would like to invite everyone to have a look at this 2.0.0-M19 in order to fill issues your setup may have with it. 

In order to release Californium 2.0.0 according the current Eclipse Foundation regulations, the license must be updated from [EPL 1.0](https://www.eclipse.org/org/documents/epl-v10.php) to [EPL 2.0](https://www.eclipse.org/legal/epl-2.0/) to benefit from improved details. The EPL 2.0 is very close to our current dual license, see [FAQ: Is EPL-2.0 with the Secondary License clause considered dual?](https://www.eclipse.org/legal/epl-2.0/faq.php#h.lgjcpvoq08a9). To achieve this, all files will be changed! Therefore, if you plan to make larger contributions, please stay by. Smaller contribution (couple of files) should still be possible by the risk of updating the license then before merging it.

**Comment by boaks** [comment]
Recent update:

The licenses will change EPL 1.0 to EPL 2.0 and the EDL 1.0 will be kept as dual licence.

**Comment by rogierc** [comment]
Is it possible to use EDL as secondary license? The EPL 2.0 faq states:

> 2.12. Can I use other licenses as a Secondary License other than the GPL-2.0 or later?
>No. The provisions of the EPL-2.0 stipulates Secondary License "means either the GNU General >Public License, Version 2.0, or any later versions of that license, including any exceptions or >additional permissions as identified by the initial Contributor"

**Comment by boaks** [comment]
> Is it possible to use EDL as secondary license? 

I forwarded the question.

**Comment by sophokles73** [comment]
@rogierc Californium will continue to be dual licensed, i.e. you can choose whether you would like it to use under the terms of the EPL 2.0 (formerly EPL 1.0) OR EDL 1.0 instead.
This has nothing to do with the "secondary license" which has been introduced by the Eclipse Foundation in order to allow people to use and distribute Eclipse project code in a GPL context.

**Comment by rogierc** [comment]
OK, thanks for explaining!

**Comment by boaks** [comment]
For the license update, see PR #1137

**Comment by boaks** [comment]
Californium is updated to EPL 2.0.

If no issues are reported until Fr.  November 15., I update actinium and californium.tools using the same approach.

**Comment by boaks** [comment]
Californium Tools and Actinium are also updated using EPL 2.0.
