### ISSUE TITLE
Release 2.0.0 - renaming "...-tcp" into "...-netty-tcp"

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1134]
I would like to rename `element-connector-tcp` into `element-connector-netty-tcp` in order to use the `element-connector-tcp` for a future "simple client implementation using plain java sockets".

Any objections or opinions?

Just to be clear:
I personally don't plan such a implementation in the next time, nor do I plan to complete the TCP function according the RFC.

**Comment by sbernard31** [comment]
`element-connector-tcp-netty` ?

**Comment by boaks** [comment]
Would work as well.

**Comment by sophokles73** [comment]
And the plain socket implementation could then be `element-connector-tcp-plain` ...
