### ISSUE TITLE
About Android Demo

### ISSUE THREAD

**Issue by MonsoonSa** [eclipse/californium#1139]
Base on the **cf-android** demo，I tried to build a client to post some Json data to server ,but it seems not work well，**json data can't be posted completely to the server**，there were allways 'Block 1'，but no 'Block 2'，like this:

`coapServer.py - parseCoapData - 369 - INFO - ====================================================================================================
coapServer.py - parseCoapData - 376 - INFO - version=1 message_type=1 token_len=8 code=2==POST mid=37512
coapServer.py - parseCoapData - 386 - DEBUG - ====>To Parse Options
coapServer.py - parseCoapData - 424 - DEBUG - ====>option_num:11  option_value:b'u'b'p'b'l'b'o'b'a'b'd'
coapServer.py - parseCoapData - 440 - INFO - options:Uri-Path==upload
coapServer.py - parseCoapData - 386 - DEBUG - ====>To Parse Options
coapServer.py - parseCoapData - 424 - DEBUG - ====>option_num:12  option_value:50
coapServer.py - parseCoapData - 440 - INFO - options:Content-Type==(b'2',)
coapServer.py - parseCoapData - 386 - DEBUG - ====>To Parse Options
coapServer.py - parseCoapData - 424 - DEBUG - ====>option_num:27  option_value:13
coapServer.py - parseCoapData - 427 - INFO - options:Block1 num:0-more:1-size:512
coapServer.py - parseCoapData - 386 - DEBUG - ====>To Parse Options
coapServer.py - parseCoapData - 424 - DEBUG - ====>option_num:60  option_value:6285
coapServer.py - parseCoapData - 440 - INFO - options:Size1==(b'\x18', b'\x8d')
coapServer.py - parseCoapData - 446 - DEBUG - ====>To Parse Payload
coapServer.py - parseCoapData - 483 - INFO - {"timeStamp":"2019-11-14 10:40:30","UID":"322229a9-d41d-4642-80a2-1bc53d6ba19c","data":[{"systemStartTime":"2019-11-14 08:51:59","androidVersion":"4.4.2","model":"9R08 E6000","host":"rjyby07","hardware":"rtd298x","width":1280,"defaultLanguage":"zh","display":"KOT49H dev-keys","board":"rtd298x","SDK":19,"routerMac":"dc:d2:fc:01:8a:17","id":"KOT49H","product":"rtd298x_tv010_768","localWifiMac":"90:c3:5f:2a:ff:7c","fingerprint":"Skyworth\/rtd298x_tv010_768\/rtd298x_tv010_768:4.4.2\/KOT49H\/20181211:user\/dev-k`

I have set the client useNONs，so the server dosen't need to reply my request

My codes:
` public boolean initCoAP(String jsonStr) {
        mJsonStr = jsonStr;
        URI uri;
        try {
            uri = new URI(COAP_URL);
            new CoapGetTask().execute(uri.toString());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

class CoapGetTask extends AsyncTask<String, String, CoapResponse> {
        protected void onPreExecute() {
            // reset text fields
        }

        protected CoapResponse doInBackground(String... args) {
            CoapResponse response = null;
            CoapClient client = new CoapClient(args[0]);
            try {
                response = client.useNONs().post(mJsonStr, MediaTypeRegistry.APPLICATION_JSON
                );
            } catch (ConnectorException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return response;
        }

        protected void onPostExecute(CoapResponse response) {
            if (response != null) {
                Log.i(TAG, response.getCode() + "\n"
                        + response.getOptions() + "\n"
                        + response.getResponseText() + "\n"
                        + Utils.prettyPrint(response));
            }
        }
    }
`
Besides, I saw the demo has the function 'initCoapEndpoint'，is that work for my question？
Even if it works , but i can't running successfully，because the bug like this:

`java.lang.NullPointerException: Trust store must not be null
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.setTrustStore(DtlsConnectorConfig.java:1562)
        at com.avc.ottsdk.coap.ConfigureDtls.loadCredentials(ConfigureDtls.java:64)
        at com.avc.ottsdk.net.DataPost.initCoapEndpoint(DataPost.java:208)
        at com.avc.ottsdk.net.DataPost.<init>(DataPost.java:64)
        at com.avc.ottsdk.net.DataPost.getInstance(DataPost.java:71)
        at com.avc.ottsdk.service.AvcHbService.checkHeartBeatDB(AvcHbService.java:134)
        at com.avc.ottsdk.service.AvcHbService.access$500(AvcHbService.java:26)
        at com.avc.ottsdk.service.AvcHbService$MyThread.run(AvcHbService.java:116)
`
I am not good at English,so please forgive me if there are something wrong in my words
Hope you can help me
My Sincerely thanks

**Comment by boaks** [comment]
Maybe you can check, if it works with an Californium server.

> there were allways 'Block 1'，but no 'Block 2'，like this:
 
Sorry, don't understand that logs.
Generally, if you want to sent more data than fits into one request, a blockwise transfer using option BLOCK1 is used. Option BLOCK2 is only used, if more data is read, than fits into one response.

> I have set the client useNONs，so the server dosen't need to reply my request

A none Request must also be answered by a Response according RFC7252.

The android example hasn't been maintained for some time. I'm, not sure, if I can spend some time within the next week in it. We will see ...

**Comment by boaks** [comment]
Please check, if PR #1140 works better for you, especially, if you use californium as server.

**Comment by boaks** [comment]
It's merged in the meantime, just fetch and update the master (or pull).

I'm not sure, what you really want to do with CoAP. It's very efficient to exchange data, which fit's into one IP message. Depending on your network setup, that may be 1280 (IPv6) or 512 (IPv4). If there alre some links in between, which provides smaller packages, as NB IoT, you may benefit, if your packages are even small (e.g. 300 bytes). If the payload is larger, the IETF have defined an extension [RFC7959 - Blockwise](https://tools.ietf.org/html/rfc7959), but both peers have to implement/support it. Sometimes it's therefore easier to use a "more binary" payload as JSON. CBOR is one common alternative. It's not unusual, that you can send twice the application information as with JSON, but that depends on obviously on that information.

**Comment by MonsoonSa** [comment]
> It's merged in the meantime, just fetch and update the master (or pull).
> 
> I'm not sure, what you really want to do with CoAP. It's very efficient to exchange data, which fit's into one IP message. Depending on your network setup, that may be 1280 (IPv6) or 512 (IPv4). If there alre some links in between, which provides smaller packages, as NB IoT, you may benefit, if your packages are even small (e.g. 300 bytes). If the payload is larger, the IETF have defined an extension [RFC7959 - Blockwise](https://tools.ietf.org/html/rfc7959), but both peers have to implement/support it. Sometimes it's therefore easier to use a "more binary" payload as JSON. CBOR is one common alternative. It's not unusual, that you can send twice the application information as with JSON, but that depends on obviously on that information.

I'm a chinese developer and my english is not very well ,so maybe my words is not easy to understand. really sorry about that 

I just want to use CoAP to post some Json data to my server , Now my data is about 2.5kb，But everytime I start the client , Just about 500 bytes has been posted . I don't know why

I know CoAP always seperate several packages when the data is too big ,So I guess my data is seperated by several packages，Therefore my server just receive the first package right？But where are the others？ Where can I set this ?

As you reply '**A none Request must also be answered by a Response according RFC7252.**'，So that means my server must answer my request, So the other packages can be posted？
Now I'm trying...

**Comment by boaks** [comment]
> I'm a chinese developer and my english is not very well ,so maybe my words is not easy to understand. really sorry about that

I'm no native English speaker as well :-).

> I just want to use CoAP to post some Json data to my server , Now my data is about 2.5kb，But everytime I start the client , Just about 500 bytes has been posted . I don't know why
> 
> I know CoAP always seperate several packages when the data is too big ,So I guess my data is seperated by several packages，Therefore my server just receive the first package right？But where are the others？ Where can I set this ?
> 

The answer is somehow related to your other question.
There are two layer in CoAP, the message transmission [RFC7252 - Section 4](https://tools.ietf.org/html/rfc7252#section-4) and the request/response [RFC7252 - Section 5](https://tools.ietf.org/html/rfc7252#section-5). That allows to decouple transmission and processing times. But in the end, each request expects a response

[Figure 22: Non-confirmable Request; Non-confirmable Response](https://tools.ietf.org/html/rfc7252#page-109)

That is also true, for "single block request" in a blockwise transfer. [BLOCK 1 exchange](https://tools.ietf.org/html/rfc7959#section-3.2). The first single block request get's a "continue" as response, and with that sends the next block request (and so on).

But, both sides must implement that extension. On frustrating situation in CoAP seem to be, that many implementations are more or less only implementing the core RFC7252 and not too many offers also the extensions as RFC7959. Therefore I recommended to try californium as server as well. Alternatively use not JSON, use some more comprehensive encoding as CBOR (that very similar to JSON, at least if you use APIs instead of prepare your JSON as string on your own).

Did you also try to send the larger payload with that python implementation as client as well? 
Do you use a public available python coap implementation?

**Comment by MonsoonSa** [comment]
> Did you also try to send the larger payload with that python implementation as client as well?
> Do you use a public available python coap implementation?
No I didn't, Now I only use californium because it's the best 

I had revised my server to give a response to my request ,but still not working 
I caught the package
My request :
```
01.. .... = Version: 
..00 .... = Type: Confirmable (0)
.... 1000 = Token Length :8
Code :POST(2)
Message ID: 6982
Token: 204afc7575069289
```

My response:
```
01.. .... = Version :1
..10 .... = Type: Acknowledgement （2）
.... 0000 = Token Length : 0
Code : Empty Message (0)
Message ID : 6982
```
So the Message ID is matched, But My response has not  Code and Token ,Is that the reason ?
Do I have to set a Code or a Token in my response?

**Comment by boaks** [comment]
MID is for transmission.
Token is for request/response. 

Your ACK just indicates: the message is received, don't repeat.
That's because your ACK is "EMPTY" Code 0.

Add the token and a response code, that converts it into a "piggybacked" response.

```
CLIENT                                                             SERVER
     |                                                                |
     | CON [MID=1234, T=ABCD], PUT, /options, 1:0/1/128    ------>    |
     |                                                                |
     | <------   ACK [MID=1234, T=ABCD], 2.31 Continue, 1:0/1/128     |
```

**Comment by boaks** [comment]
[Request/Piggybacked Response](https://tools.ietf.org/html/rfc7252#page-105)

> Figure 17 shows a similar example, but with the inclusion of an non-
>    empty Token (Value 0x20) in the request and the response, increasing
>    the sizes to 17 and 12 bytes, respectively.

  ```
 Client  Server
      |      |
      |      |
      +----->|     Header: GET (T=CON, Code=0.01, MID=0x7d35)
      | GET  |      Token: 0x20
      |      |   Uri-Path: "temperature"
      |      |
      |      |
      |<-----+     Header: 2.05 Content (T=ACK, Code=2.05, MID=0x7d35)
      | 2.05 |      Token: 0x20
      |      |    Payload: "22.3 C"
      |      |
```

(Note: a empty token in the request and response, may also be valid, but the server must include just the token of the request in the response.)

**Comment by MonsoonSa** [comment]
> [Request/Piggybacked Response](https://tools.ietf.org/html/rfc7252#page-105)
> 
> > Figure 17 shows a similar example, but with the inclusion of an non-
> > empty Token (Value 0x20) in the request and the response, increasing
> > the sizes to 17 and 12 bytes, respectively.
> 
> ```
> Client  Server
>     |      |
>     |      |
>     +----->|     Header: GET (T=CON, Code=0.01, MID=0x7d35)
>     | GET  |      Token: 0x20
>     |      |   Uri-Path: "temperature"
>     |      |
>     |      |
>     |<-----+     Header: 2.05 Content (T=ACK, Code=2.05, MID=0x7d35)
>     | 2.05 |      Token: 0x20
>     |      |    Payload: "22.3 C"
>     |      |
> ```
> 
> (Note: a empty token in the request and response, may also be valid, but the server must include just the token of the request in the response.)

Thanks for your reply
Fortunately, I got the response log and token is be added 

My request :
```
01.. .... = Version: 
..00 .... = Type: Confirmable (0)
.... 1000 = Token Length :8
Code :POST(2)
Message ID: 318
Token: 90cc2ee8bb72ca93
```

My response:
```
01.. .... = Version :1
..10 .... = Type: Acknowledgement （2）
.... 0000 = Token Length : 8
Code : 2.31 Continue (95)
Message ID : 318
Token: 90cc2ee8bb72ca93
[Request In : 744]
[Response time : 0.000299000 seconds]
```
So that means , Server has received data's part1 , Then the part2 should be posted , And then part3 ...etc, Right?
But my server just received part1 again , **And not receive any more** , My data still not be posted completely.

My client code : 

```
public void initCoAP(String jsonStr) {
        mJsonStr = jsonStr
        URI uri;
        try {
            uri = new URI(COAP_URL);
            new CoapGetTask().execute(uri.toString());

        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

    class CoapGetTask extends AsyncTask<String, String, CoapResponse> {

        protected void onPreExecute() {
            // reset text fields
        }

        protected CoapResponse doInBackground(String... args) {
            CoapResponse response = null;
            CoapClient client = new CoapClient(args[0]);
            response = client.post(mJsonStr, MediaTypeRegistry.APPLICATION_JSON);
            return response;
        }

        protected void onPostExecute(CoapResponse response) {
            if (response != null) {
                Log.i(TAG, response.getCode() + "\n"
                        + response.getOptions() + "\n"
                        + response.getResponseText() + "\n"
                        + Utils.prettyPrint(response));
            }
        }
    }
```
Maybe there is something wrong with my client code ? Should I do something when I get the response ? Please help me.
Thank you.

**Comment by boaks** [comment]
Are you able to use wireshark or create captures with tcpdump?
Your logs are missing the block1 option infos and such captures are usually contain all information.

**Comment by boaks** [comment]
> So that means , Server has received data's part1 , Then the part2 should be posted , And then part3 ...etc, Right?

Yes, the server has received a part (block). If the client continues the send the next block, depends  
on the block1 opion of the response.

> But my server just received part1 again , And not receive any more , My data still not be posted completely.

That may be related to the block1 option in your response.

> Maybe there is something wrong with my client code ? Should I do something when I get the response ? Please help me.

Your client looks good, I still think, if you use californium as server, and use wireshark to see, what exactly is exchanged, you will find the difference between you python and the californium server implementation.

**Comment by boaks** [comment]
```
CLIENT                                                             SERVER
     |                                                                |
     | CON [MID=1234, T=ABCD], PUT, /options, 1:0/1/128    ------>    |
     |                                                                |
     | <------   ACK [MID=1234, T=ABCD], 2.31 Continue, 1:0/1/128     |
```

Just to mention: **1:0/1/128** is for:

"1:" for option block1.
"0/": for block1 number 0 (1th block).
"1/": for more block1 pending (the last will be 0).
"128": size of the block1, 128 bytes.

**Comment by MonsoonSa** [comment]
> ```
> CLIENT                                                             SERVER
>      |                                                                |
>      | CON [MID=1234, T=ABCD], PUT, /options, 1:0/1/128    ------>    |
>      |                                                                |
>      | <------   ACK [MID=1234, T=ABCD], 2.31 Continue, 1:0/1/128     |
> ```
> 
> Just to mention: **1:0/1/128** is for:
> 
> "1:" for option block1.
> "0/": for block1 number 0 (1th block).
> "1/": for more block1 pending (the last will be 0).
> "128": size of the block1, 128 bytes.

I made it ! Finally the server has received all the blocks :-)
Thank you very much , Your reply is really helpful.

But sadly, Our company's server has some custom rules , There are  some different fields in option, 
For example , Our server need a field to decide whether all these blocks can be integrated into a complete json data , That means we have to rewrite some code.
The server's developer in our company (not me) didn't want to rewrite his code... So I guess maybe I have to try to rewrite the source code of Californium... Even though I had absolutely no idea how to do...

Whatever , Appreciated for your help . 
非常感谢你的帮助

**Comment by boaks** [comment]
> I made it ! Finally the server has received all the blocks :-)

Your welcome!

> The server's developer in our company (not me) didn't want to rewrite his code... 

That's sad. 

> Even though I had absolutely no idea how to do...

That depends on these "custom rules". If these rules are just depend on CoAP options, californium offers to use custom options. Simply create the `Option` (using the `Option(int number, byte[] opaque)` should offer a generic way to do that), and add them to the `Request` by 

``` 
request.getOptions().addOption(new Option(yourOptionNo, yourOptionValue));
``` 

If that options must be adjusted during the blockwise transfer, then it will get more complicated, but it's not impossible :-).
