### ISSUE TITLE
 Elliptic Curve J-PAKE Cipher Suites for TLS support

### ISSUE THREAD

**Issue by sksemenov** [eclipse/californium#114]
Hi,

We are considering a library to implement Thread commissioning protocol. Californium seems as an excellent option for CoAp but it seems that it does not yet support  Elliptic Curve J-PAKE Cipher Suites for TLS (https://tools.ietf.org/html/draft-cragie-tls-ecjpake-01).

Question: does Californium support the cipher suites? If not, is there a plan to implement it ?

Thnaks

**Comment by sophokles73** [comment]
no, we do not support that cipher (yet) nor do we have any plans for adding support for it. You are more than welcome to add it, though, of course :-)

**Comment by sksemenov** [comment]
Thanks for such a quick reply. If we implement it will definitely share the source.
