### ISSUE TITLE
2.0.0-RC2 Released

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1143]
I would like to release 2.0.0-RC2 on Thursday, November 21. 2019

Fixed leak, PR #1138 
Renamed tcp module
Update CBOR dependency
Updated to EPL 2.0
Remove none IANA content types, issue #1078

Any objection?
Any additional issues to fix?

**Comment by sbernard31** [comment]
:+1:
(Just to let you know, we still use leshan 1.0.0-M12 and so californium 2.0.0-M16 in production for now, so but 2.0.0-RC1 is integrated in master of Leshan)
