### ISSUE TITLE
Passing reliabililityLayer parameter in request.

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#1154]
Hi,

Californium version : 2.0.0 RC1.

I tried to set reliabilityLayerParameters on each downlink request.

For example like below. No re transmission attempt was made.

coapRequest = new Request(Code.FETCH);
    	coapRequest.setReliabilityLayerParameters(reliabilityLayerParameters);
    	coapRequest.getOptions().setContentFormat(format.getCode());
    	coapRequest.getOptions().setAccept(format.getCode());
    	coapRequest.setPayload(payload);

Please help in rectifying the issue . Any additional parameters needed to be passed?

**Comment by boaks** [comment]
retransmission would be defined in the values of that `reliabilityLayerParameters`, but I can't see them. I'm even not sure, if "no retransmission" is the issue and you want to have retransmissions.
Therefore, please report the used values of the reliabilityLayerParameters. And maybe you could express more clearly, what you expect and what you get instead.

**Comment by madhushreegc** [comment]
Hi 

Reliability layer is working perfectly when it is passed at the message level . There was problem in my tcpConnector(Custom) one .

I am very sorry  for posting this.

**Comment by boaks** [comment]
> tcpConnector(Custom)

AFAIK, the `reliabilityLayerParameters` are not used at all for copa+tcp, though that transmission function is implemented within the tcp stack.
