### ISSUE TITLE
Session vs connection

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1163]
### My understanding of the RFCs is :
Connection and session have different life cycle.
With session resumption, a session could be used by several connections.

### My understanding of californium code :
**_The default behavior_** :
By default the `ConnectionStore` contains connections. Session is not store in a specific store and are just strongly linked to connection.

That means that if the connection is deleted, session is lost too.
This could bring to suboptimal behavior. e.g. 
 - I have a client A which create a connection cA  using IP_A and port_A linked to a session sA.
 - then a client B create a new connection cB / session sB reusing IP_A:port_A : This will remove cA from the store and so we lost sA
 - now if client A try to resume sA using a new IP/port this will not be possible

**_Session cache_** :
But Californium provides a `SessionCache` which allow to uncouple Session and connection.
I begin to play a little with it but I see most of the time session is removed from sessionCache when associated connection is removed from cache.
E.g. if connection is evicted or connection is close because of close_notify the linked session is removed too.

My feeling is this is not really the good behavior, AFAIK the only good reason to remove the session (and so forbid resumption) is when we receive an [error_alert](https://tools.ietf.org/html/rfc5246#section-7.2.2) or cache limitation (size + lifetime).

Did I miss something ?

(a workaround to avoid this "unwanted remove" with the current API is to not implement `SessionCache.remove()` but this means that session is not remove on error alert too)

**Comment by boaks** [comment]
Californium's `Connection` is more a container for all information and the thread-serialization. The RFC6347 term  "Connection" (or "Association") is then more the `DTLSConnectionState` and the `DTLSSession`'s `sequenceNumbers` and `receiveWindow`.

If a new association/connection (client_hello) is created, the old one should not be deleted. It get's mainly removed from the address-table, but the session table is kept and so resumption should have a chance. Did you test your scenario?

The most  of your other conclusions/observations are shared by me. My issue with the `SessionCache` is, that if this is shared/distribute, I'm not sure, how that is intended to work.

**Comment by boaks** [comment]
Please checkout PR #1164 and verify, that the behavior is not as described with

1. I have a client A which create a connection cA using IP_A and port_A linked to a session sA.
1. then a client B create a new connection cB / session sB reusing IP_A:port_A : This will remove cA from the store and so we lost sA
1. now if client A try to resume sA using a new IP/port this will not be possible
 
It's 

1. I have a client A which create a connection cA using IP_A and port_A linked to a session sA.
1. then a client B create a new connection cB / session sB reusing IP_A:port_A : This will remove cA from the address-table of the store but keep it in the session table so sA is still resumable.
1. now if client A try to resume sA using a new IP/port this is still possible
 
The new implementation with the connection id use that id as "primary key" and the other as "optional secondary keys". If just the address is used for an other connection, the old one is removed from the address-table, but kept in the id- and session-table.

**Comment by boaks** [comment]
I prepared a second PR #1167 with adapted close notify processing.
I'm not sure, if this "pays off". 
Anyway, please check, if this may solve a part of your issue.

**Comment by sbernard31** [comment]
> that the behavior is not as described

Uups I check this with on Californium 2.0.0-M12 which we are still using for some services :sob:

About **close notify**, this is a real use case we have some device which initiate a connection then send close notify before to go to sleep and try to resume the session.

About **eviction**, I look at the master code quickly and I still think that eviction should not remove session from cache.

I will look at all #1164 and #1167 now.

**Comment by sbernard31** [comment]
Some questions about `SessionCache` ?

@sophokles73, @boaks :
1. Are you using or do you know someone who is using it ?
2. Same question but with a persistent/shared usage ?
3. Do you think it make sense to remove session from cache on ConnectionStore eviction, in particular when you persist/shared session in a cluster ?

**Comment by boaks** [comment]
1. only rare for some test-setups (server). And in my android demo app (client).
2. only persistent for my android demo app (client)
3. the only sense for me is to prevent the current test `InMemorySessionCache` from leaking.

Just, if you collect issues for the session cache: 
The cleanup of stale or aborted sessions seems for me to be the main open issue, especially for a distributed use-cases.

**Comment by sbernard31** [comment]
>3. the only sense for me is to prevent the current test InMemorySessionCache from leaking.

We currently think about using it maybe at mid term. If we do that we will probably store this in something like a redis store. This store will be much more larger than the `connectionStore` and so this eviction removing sounds to be a problem.

> The cleanup of stale or aborted sessions seems for me to be the main open issue, especially for a distributed use-cases.

Could you explain a bit more  what you have in mind exactly ?

**Comment by boaks** [comment]
Nothing exactly. It's just, that if session are only added, but not removed, I guess the cache will overflow. So, I see two cases, where session should be removed, one is stale session (or expired ones), the other is aborted sessions (fatal alerts).

**Comment by sbernard31** [comment]
Ok I get it.

FMPOV, **aborted sessions** (fatal alerts) should be remove by Scandium.
I'm not sure to see exactly what you call **stale session** but my current feeling is that session lifetime and store size limitation should be handle by the store itself. :thinking:

**Comment by boaks** [comment]
Sure, but also that has to be specified.

And there maybe advanced cases, where a session is to be removed, because the credentials are withdrawn. You raised that in other issues and therefore the connection-iterator is introduced. But that will not work for a shared session-cache. So, it may require more.

**Comment by sbernard31** [comment]
Quickly tested with Leshan and it sounds to behave as expected.
