### ISSUE TITLE
Voting for Versioning

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1166]
Hi Californians,

currently there is a discussion about versioning here #1159 .
Please participate in that discussion and add your comments.
And there are first changes, which are suspicious to break the API, e.g. [add final to - protected final PublicKey publicKey](https://github.com/eclipse/californium/pull/1146#discussion_r356595673) .

I wonder now, which approach would create the most benefit for the users.

Consider any public API breaking change as "major" version. Perhaps using a tool to verify that.

Consider "reachable" public API breaking change as "major" version. Though reachable maybe sometimes not clear, that may result in requests, to reestablish the old API.

My personal impression is, that a lot of the public API is just not used external. And considering major releases for changing them seems to be for me a wrong sign. 
2.0.0 toke now years, also because the API was changed a lot. But maintaining  the tools and actinium showed, that there are required changes, but not that much.  
I would therefore prefer to do it in a "soft" way, but if the majority wants something else, then this will be the way to go. 

(My impression is, that in that past, keeping that internal APIs as they where external, prevent them from being cleaned up.)

**Comment by boaks** [comment]
Consider any public API breaking change as "major" version. Perhaps using a tool to verify that. 

If you think, that's the way you benefit most, then vote on this comment.

**Comment by boaks** [comment]
Consider "reachable" public API breaking change as "major" version. Though reachable maybe sometimes not clear, that may result in requests, to reestablish the old API.

If you think, that's the way you benefit most, then vote on this comment.

**Comment by boaks** [comment]
And, sure, additional proposals are welcome!

(You can't vote for this :-)  )

**Comment by boaks** [comment]
From the current discussions in #1168 

[Asn1DerDecoder.OID](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/Asn1DerDecoder.java#L123)

is reported as inconsistent API.

> [INFO] java.class.nonPublicPartOfAPI: class org.eclipse.californium.elements.util.Asn1DerDecoder.OidEntityDefinition: Class 'org.eclipse.californium.elements.util.Asn1DerDecoder.OidEntityDefinition' is indirectly included in the API (by the means of method return type for example) but the class is not accessible (neither public nor protected). (breaks semantic versioning)

There now two ways, to work on that:
1. [strict](https://github.com/eclipse/californium/pull/1168#issuecomment-565460106)

> I'm not sure to understand but "the non breaking way to fix this API inconsistency" is to make the class OidEntityDefinition to public.
> If you thing this attribute must not be used and should be private in the next major, you just deprecate it in the minor and go to private in the next major. (again I can see the issue)
> But Non-Public Part of API is another problem this is more about API consistency than semantic versioning. We can decide to fix this consistency issue only for the 3.0.

2. [relaxed](https://github.com/eclipse/californium/pull/1168#issuecomment-565450609) 

> Same would apply to change Asn1DerDecoder.OID to private. From the programming language it may be considered to be a breaking API change, from the "domain", it maybe a bugfix (though the OID is not that useful outside).

In my opinion, the first will required to start a 3.0 and to cleanup  the technical stuff of the "public API" ahead of most other work. Currently it's not completely clear, who is going to do that work. There will be easy parts, and I guess also more complicated parts.

The second one will improve the "public API" step by step would easier allow to intermix that with other extensions/improvements. The API breaks according that tool will get documented in the "ignore configuration". If that hit's someones use-case, simply report it, and we will see, how to fix that.

**Comment by sbernard31** [comment]
> In my opinion, the first will required to start a 3.0

My opinion,
a) Nothing forces us to fix that quickly, I mean we can leave with a 2.1 without that fix. (I believed that fixing bug and testing was the priority, so fixing this could be done later)
b) This is a very special use case where the API is inconsistent and currently using that field is not even possible (as this is impossible to declare a field of this private type). My opinion this should even be a compilation issue, and maybe fixing this should not be consider as break by revapi. So this is a rare case where I consider fixing it is not really breaking the API. (unlike adding final keyword)
c) If we want to fix it, make it (public+deprecated+comment in code) for the 2.1 is another valid simple way. (even simpler to me that maintaining an exception file.)

**Comment by boaks** [comment]
@sbernard31 

I have really strong concerns and doubts about the amount of time your able to spend into your approach! Your me this look pretty much, that this actually blocks any other progress for a unknown time period. So please, clarify your planed schedules!

**Comment by rogierc** [comment]
Semantic versioning only works when there is a clear understanding of what is considered part of the API and what is not (obviously). This can be achieved by package structure (internal package), but it can also be achieved by a statement in **javadoc** of concerning class or interface, or other documentation. This can be added without changing major/minor version. As long as it is clear to the user what he/she is supposed to use and what _should_ not change in minor version/patch release, the goal of semantic versioning will be reached.
An aproach that places priority on aiding proper use of Cf could be:

1. Document what is part of the API and what is not. The user then "knows" what to depend on and what can be expected on version change. Explain ambiguous situations here. 
2. During lifecycle place internal stuf in internal packages  and test on API changes (revapi) when appropriate and feasable.

In this approach versioning would be relaxed and gradually moves towards strict. In the meanwhile users can anticipate on changes.

From a user perspective maintaining a strict versioning on the API alone is not enough. On minor version/patch release I expect not only that the API is backward compatible and my code will compile, but also that all my tests will run and succeed - that there is no significant change in behaviour. To achieve semantic versioning  all regression testing is important, not only testing API-breaking.  (Possibly, a change in behaviour has much larger impact on user-side than a syntactical API change). 
IMHO impact on user _must_ be leading for versioning, compile compatibily _should_.

Bluntly:
What is the message to users when development continues on 3.0.0 instead of 2.x? Stop developments based on 2.0.0 because everything is going to change??

**Comment by sbernard31** [comment]
> Bluntly:
> What is the message to users when development continues on 3.0.0 instead of 2.x? Stop 
> developments based on 2.0.0 because everything is going to change??

The message of increment major version is just that the development team know that they break some part of the API. This doesn't mean that all the API will change and this will be a nightmare to go from 2.0.0 to 3.0.0. You can find a lot of migration guide where there is almost nothing to do.
Why this would mean that developments based on 2.0.0 should be stopped ? I clearly don't understand the concerns here.
By the way the message could be clearly claim as : "3.0.0 would be an improved version of the 2.0.0 with hoping minimal break on commons usage and with clear definition of public API". 

> but it can also be achieved by a statement in javadoc of concerning class or interface, or other documentation.

This sounds pretty fastidious to do, not so clear for user and also harder to check consistency, so I prefer the package way.

I agree with @rogierc about  : 
 - "Semantic versioning only works when there is a clear understanding of what is considered part of the API and what is not (obviously)."
 - "From an user perspective maintaining a strict versioning on the API alone is not enough, .... that there is no significant change in behaviour"

**Comment by boaks** [comment]
Just to mention:

When I agreed to use "revapi", I requested [my comment](https://github.com/eclipse/californium/issues/1159#issuecomment-565006828)

> Please, just start with introducing one of your proposed tools, if they allow to exclude some stuff from the check. 

For me it seems, that use a tool out of the box, in a strict manner, without prior preparing the source according that use of the tool, results in spending much more time. 
At least I had to spend 2 days in find out, how to exclude some stuff from being checked by revapi. That was exactly, what I didn't want; spending my time into using a tool.

> "Semantic versioning only works when there is a clear understanding of what is considered part of the API and what is not (obviously)."

Unfortunately, the source and APIs are implemented by many different people. I don't think, that someone has an overview over all. At least I have mainly an overview of some parts. Spending some days into the proxy showed me again, that not all is really clear. (Just to mention: working on the proxy I already started to think, that a 3.0 may come sooner, as I would would have thought some weeks ago.)

> "From an user perspective maintaining a strict versioning on the API alone is not enough, .... that there is no significant change in behaviour"

Unfortunately, the behaviour is sometimes in some details "undefined" or may have changed in the specifications. So, sometimes the behaviour has to be changed. See `Request` in my current PR #1176 .

"define the public API":
Moving stuff into internal package may cause additional work in split functions and classes. Therefore I claimed my doubts about the timeline for that approach.
"revapi" supports also annotations, I proposed to introduce two "NoPublicAPI" and "ExperimentalAPI". I also proposed to exclude `externalClassExposedInAPI` from the checks in the parent pom (see justification there).

**Comment by rogierc** [comment]
> >     What is the message to users when development continues on 3.0.0 instead of 2.x? Stop
> >     developments based on 2.0.0 because everything is going to change??
> > 
> 
> ... This doesn't mean that all the API will change and this will be a nightmare to go from 2.0.0 to 3.0.0. 

Agree. My point was merely that when the API (and/or behaviour) is not so clearly defined, the major version change would rougly mean something like "big impact" and a minor version change "small impact". 
Yes, release notes and migration guides explain, but are often not yet available in early development stages. When restructuring of packages takes considerable time, it may be good to inform users of changes they can expect. Documentation (or annotations) may be helpfull there. That can be done early and doesn't conflict with a possible 2.0.1 or 2.1.0 release. 
Could working on that also help to define the 3.0.0 scope?
