### ISSUE TITLE
How to implement store and restore observation relations

### ISSUE THREAD

**Issue by dgooris** [eclipse/californium#1177]
Hello, 

I have CoAP-clients running in observation mode and this works fine with the Californium CoAP-Server.  After a restart of the server, obviously the relationship between the server and the clients are gone.  I am looking for a way to store and restore the dynamic data within the server in a database or file.

The data to be saved should include items like the IP addresses of the clients, ports, tokens, message id's etc, all what is essential to restore the sessions later on.

Looking for some hits and tips, I found this discussion: issue 535 'Restoring observe relations after Californium restart' where I read this phrase:

_In this case with the Californium 2.0.x, you can implement your own ObservationStore and so persist observation in a persistent store/file_

The software level is already on release 2.0.

I do not know how to take advantage of this ObservationStore interface.

What are the objects to save so I have the address:port and all the other parameters ?
Where is the best place to store the data (I thought of ServerMessageDeliverer ?)
And what would be the best place/moment to restore the data to re-build all the objects ?

Kind regards.

**Comment by boaks** [comment]
Maybe it's a good point to clarify the terms:
The coap-client is the peer, which sends the request with the observe option.
The coap-server send the current response back and also responses for future changes.
The "observe-cluster" was developed for the LwM2M use-case, where the LwM2M server acts as coap-client. 
But for now (2.0.0), we don't have a persistent implementation of the coap-server in californium.

**Comment by dgooris** [comment]
Achim,

Thanks for your response. Indeed the terms are according my configuration.
So then I have to figure out how to implement the store and restore mechanism.

Maybe I can save the essential parameters of the session between the coap-client and coap-server such as client address, port, MID of client, MID of server, token, etc and re-apply these parameters in some way after recovery so that the objects like Exchange, ObserveRelation are built again..

Anyway, now that I know that it is not supported in 2.0.0 I can try to find alternative ways.

Thanks, and kind regards, - Dirk

**Comment by boaks** [comment]
I personally consider [RFC7641 Observer-Notify](https://tools.ietf.org/html/rfc7641) more  as solution for a "short term progress indicator". I'm not sure, if that use-case would not work easier, when the observed peer just reports changes by requests (even if that breaks the REST idea). That put the requires stuff into the application-layer (e.g. request provided URL for event-reporting). But it doesn't require to change the libraries in a way, that observes can be persisted and restored. Especially, if you want to use that designa also for other coap-libraries (e.g. in C), then it may be easier to move it into the application-layer.
