### ISSUE TITLE
Some strange behavior about Handshake mode NONE (#1104)

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1186]
We finally integrate leshan-1.0.0-M13(based on Cf-2.0.0) in production . \o/

In Leshan, we add the feature where each requests sent to a UQ device use the handshake mode NONE. (#1104)
For now, almost all our devices use Q mode (as server initiated in still experimental), but we : 
 - still see in our metrics a lot of server initiated handshake.
 - still see a lot of "Hanshake flight 1 timeout".

Where we expected a decrease of this.

So I add an `MessageInterceptor` to log if EndpointContext is well set before to enter in the coap stack.
And all sounds OK excepts maybe for transparent blockwise where destination endpoint context parameter of parent request sounds maybe not transmit to "children" block requests. (I'm not sure)

Anyway I'm pretty sure this "blockwise bug" is not the main reason, as requests which failed on "Handshake flight 1 timeout" rarely used block wise transfer.

I looked at the californium code and for now, I can not explained this behavior :thinking:

**Comment by boaks** [comment]
[BLOCK1 - Request](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/stack/Block1BlockwiseStatus.java#L120)
[BLOCK2 - Request](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java#L980)

Seems the endpoint-context is tranferred.

**Comment by sbernard31** [comment]
For block2 : `block.setDestinationContext(response.getSourceContext())`, the  parent request destination context sounds not to be used. So parameters like HANDSHAKE_MODE seems lost :thinking:. Did I miss something ?

**Comment by boaks** [comment]
Maybe a `MessageObserver`, which checks `onSendError(Throwable error)` for the error-message ("Hanshake flight .* timeout"), and reports more details about the affected `Message`?

(Just to mention, from time to time, I used to cleaned up the error-messages, so just ensure, you grep for the right one.)

**Comment by boaks** [comment]
> For block2 : block.setDestinationContext(response.getSourceContext()), the parent request destination context sounds not to be used. So parameters like HANDSHAKE_MODE seems lost thinking. Did I miss something ?

Hm,  the context of the response is used, to ensure, that the crypto stuff get's added.
Maybe change that to a variant, which checks, if the original Request's context already contains the information and use that instead, would help here.

**Comment by boaks** [comment]
> Hm, using the other modes e.g. "HANDSHAKE_MODE_FORCE_FULL" will then not work.
> So, maybe just a solution for the "NONE"?

Same issue for BLOCK1, using it with that modes, will result in irritating handshakes.

**Comment by sbernard31** [comment]
> Maybe a MessageObserver, which checks onSendError(Throwable error) for the error-message ("Hanshake flight .* timeout"), and reports more details about the affected Message?

In our logs I see affected LWM2M requests. And I can see nothing special 
```
ection-Handler-3] c.s.a.app.lwm2m.RequestSender    [endpoint=354382103989418, system=592a4f27937c4374ac16e213e0b4fb3d] Could not send the request Request [ticketId=ed83f48d44044de78c8c9905f37634a6, request=ReadRequest [path=/5/0/5 format=null]]
org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://10.193.16.158:32484/5/0/5
 at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:153) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.coap.Message.setSendError(Message.java:896) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.coap.Request.setSendError(Request.java:815) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1109) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.elements.RawData.onError(RawData.java:303) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.DTLSConnector$1.handshakeFailed(DTLSConnector.java:432) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:1223) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2406) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.DTLSConnector.access$1900(DTLSConnector.java:214) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.DTLSConnector$TimeoutPeerTask$1.run(DTLSConnector.java:2562) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) ~[lwm2mfe.jar:na]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
 at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: java.lang.Exception: handshake flight 1 failed!
 at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2403) ~[lwm2mfe.jar:na]
 ... 6 common frames omitted
Caused by: java.lang.Exception: handshake flight 1 timeout after 4 retransmissions!
 at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2399) ~[lwm2mfe.jar:na]
 ... 6 common frames omitted
```

> (Just to mention, from time to time, I used to cleaned up the error-messages, so just ensure, you grep for the right one.)

I'm not sure to get the point.

> Maybe change that to a variant, which checks, if the original Request's context already contains the information and use that instead, would help here.

Something like that, yep

> Hm, using the other modes e.g. "HANDSHAKE_MODE_FORCE_FULL" will then not work.

Good catch ... Maybe we should have 2 type of parameters 1 which is transmitted to children requests and 1 which is only use for the "first" one (or something like this) ?

**Comment by sbernard31** [comment]
Tomorrow I will activate some debug log on DTLSConnector for few minutes hoping I will see something.

**Comment by sbernard31** [comment]
We find something about transparent block mode but I'm more concern about the general issue. 
This looks like race condition but looking at the code I can not see where. My first idea was a race condition where we receive a close_notify (and so remove connection) when we send a message ? but again looking at the code that sounds not possible :thinking:

**Comment by boaks** [comment]
The logging message "c.s.a.app.lwm2m.RequestSender"  doesn't show the endpoint context's - handshake mode, or? Maybe adding that would help.

**Comment by boaks** [comment]
The bockwise stuff may work better with PR #1188

**Comment by sbernard31** [comment]
> The logging message "c.s.a.app.lwm2m.RequestSender" doesn't show the endpoint context's - handshake mode, or? Maybe adding that would help.

The idea would be to check if the mode is correctly set ?
If yes, we already check this by adding log on a `MessageInterceptor` to check if context is correctly set for each requests which pass though the interceptor.
Or maybe I missunderstand ?

**Comment by sbernard31** [comment]
Activating logs I think I find the issue.

We face some devices which : 
 - do an handshake
 - send an app_data (I suppose this is a reg or reg update request)
 - just after send a close_notify ... (why ? we don't know .. probably a bug)
 - at server side we try to send something, I suppose the response (I see DTLS endpointContext is used which confirm this is probably not a request, request should use a MAP endpointContext). This trigger a server initiated handshake.
 - just after that we try to send the request with the handshake mode NONE, but as handshake is already initiated the raw message will be added to deferred handshake message.
 - when handshake failed (flight 1 timeout) both messages failed (confirmed by `failed, report error to deferred 2 messages` log)

Here a complete logs : 
```
[0.0/0.0.0.0:5686] o.e.c.scandium.DTLSConnector [] Received 1 DTLS records from /10.193.16.158:5835 using a 16490 byte datagram buffer
2020-01-17 11:07:23.000
[ection-Handler-6] o.e.c.scandium.DTLSConnector [] Processing new CLIENT_HELLO from peer [/10.193.16.158:5835]
2020-01-17 11:07:23.000
[ection-Handler-6] o.e.c.scandium.DTLSConnector [] Verifying client IP address [/10.193.16.158:5835] using HELLO_VERIFY_REQUEST
2020-01-17 11:07:24.000
[0.0/0.0.0.0:5686] o.e.c.scandium.DTLSConnector [] Received 1 DTLS records from /10.193.16.158:5835 using a 16490 byte datagram buffer
2020-01-17 11:07:24.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] Processing new CLIENT_HELLO from peer [/10.193.16.158:5835]
2020-01-17 11:07:24.000
[ction-Handler-10] o.e.c.scandium.DTLSConnector [] Processing CLIENT_HELLO from peer [/10.193.16.158:5835]
2020-01-17 11:07:24.000
[ction-Handler-10] o.e.c.scandium.DTLSConnector [] Client [/10.193.16.158:5835] wants to resume session with ID [0000000000000000000000000000000000000000000000000000000000000000]
2020-01-17 11:07:24.000
[ction-Handler-10] o.e.c.scandium.DTLSConnector [] Client [/10.193.16.158:5835] tries to resume non-existing session [ID=0000000000000000000000000000000000000000000000000000000000000000], performing full handshake instead ...
2020-01-17 11:07:24.000
[ction-Handler-10] o.e.c.scandium.DTLSConnector [] Sending flight of 2 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:24.000
[0.0/0.0.0.0:5686] o.e.c.scandium.DTLSConnector [] Received 3 DTLS records from /10.193.16.158:5835 using a 16490 byte datagram buffer
2020-01-17 11:07:24.000
[ection-Handler-5] o.e.c.scandium.DTLSConnector [] Received Handshake (22) record from peer [/10.193.16.158:5835]
2020-01-17 11:07:24.000
[ection-Handler-5] o.e.c.scandium.DTLSConnector [] Received Handshake (22) record from peer [/10.193.16.158:5835]
2020-01-17 11:07:24.000
[ection-Handler-5] o.e.c.scandium.DTLSConnector [] Sending flight of 2 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:24.000
[0.0/0.0.0.0:5686] o.e.c.scandium.DTLSConnector [] Received 1 DTLS records from /10.193.16.158:5835 using a 16490 byte datagram buffer
2020-01-17 11:07:24.000
[0.0/0.0.0.0:5686] o.e.c.scandium.DTLSConnector [] Received 1 DTLS records from /10.193.16.158:5835 using a 16490 byte datagram buffer
2020-01-17 11:07:24.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] Received APPLICATION_DATA for DTLS(10.193.16.158:5835,ID:62711FF13D)
2020-01-17 11:07:24.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] Terminating connection with peer [/10.193.16.158:5835], reason [CLOSE_NOTIFY]
2020-01-17 11:07:24.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] send ALERT Alert Protocol Level: WARNING Description: CLOSE_NOTIFY for peer /10.193.16.158:5835.
2020-01-17 11:07:24.000
[apServer(main)#2] o.e.c.scandium.DTLSConnector [] create new connection for /10.193.16.158:5835
2020-01-17 11:07:24.000
[ction-Handler-11] o.e.c.scandium.DTLSConnector [] Sending application layer message to [DTLS(10.193.16.158:5835,ID:62711FF13D)]
2020-01-17 11:07:24.000
[ction-Handler-11] o.e.c.scandium.DTLSConnector [] Sending flight of 1 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:24.000
[ection-Handler-4] o.e.c.scandium.DTLSConnector [] Sending application layer message to [MAP(10.193.16.158:5835)]
2020-01-17 11:07:25.000
[ection-Handler-8] o.e.c.scandium.DTLSConnector [] Re-transmitting flight for [/10.193.16.158:5835], [3] retransmissions left
2020-01-17 11:07:25.000
[ection-Handler-8] o.e.c.scandium.DTLSConnector [] Sending flight of 1 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:27.000
[ection-Handler-3] o.e.c.scandium.DTLSConnector [] Re-transmitting flight for [/10.193.16.158:5835], [2] retransmissions left
2020-01-17 11:07:27.000
[ection-Handler-3] o.e.c.scandium.DTLSConnector [] Sending flight of 1 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:31.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] Re-transmitting flight for [/10.193.16.158:5835], [1] retransmissions left
2020-01-17 11:07:31.000
[ection-Handler-1] o.e.c.scandium.DTLSConnector [] Sending flight of 1 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:39.000
[ection-Handler-9] o.e.c.scandium.DTLSConnector [] Re-transmitting flight for [/10.193.16.158:5835], [0] retransmissions left
2020-01-17 11:07:39.000
[ection-Handler-9] o.e.c.scandium.DTLSConnector [] Sending flight of 1 message(s) to peer [/10.193.16.158:5835] using 1 datagram(s) of max. 1500 bytes
2020-01-17 11:07:55.000
[ection-Handler-8] o.e.c.scandium.DTLSConnector [] Flight for [/10.193.16.158:5835] has reached maximum no. [4] of retransmissions, discarding ...
2020-01-17 11:07:55.000
[ection-Handler-8] o.e.c.scandium.DTLSConnector [] Handshake with [/10.193.16.158:5835] failed, report error to deferred 2 messages
2020-01-17 11:07:55.000
[ection-Handler-8] c.s.a.app.lwm2m.RequestSender [endpoint=358464065418770, system=3d6d9c4b3d4e426a981321fb1a975480] Could not send the request Request [ticketId=188c7ce76f86453e884d0ed3ec5d9e39, request=ReadRequest [path=/5/0/5 format=null]] org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://10.193.16.158:5835/5/0/5 at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:153) ~[lwm2mfe.jar:na] at org.eclipse.californium.core.coap.Message.setSendError(Message.java:896) ~[lwm2mfe.jar:na] at org.eclipse.californium.core.coap.Request.setSendError(Request.java:815) ~[lwm2mfe.jar:na] at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1109) ~[lwm2mfe.jar:na] at org.eclipse.californium.elements.RawData.onError(RawData.java:303) ~[lwm2mfe.jar:na] at org.eclipse.californium.scandium.DTLSConnector$1.handshakeFailed(DTLSConnector.java:432) ~[lwm2mfe.jar:na] at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:1223) ~[lwm2mfe.jar:na] at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2406) ~[lwm2mfe.jar:na] at org.eclipse.californium.scandium.DTLSConnector.access$1900(DTLSConnector.java:214) ~[lwm2mfe.jar:na] at org.eclipse.californium.scandium.DTLSConnector$TimeoutPeerTask$1.run(DTLSConnector.java:2562) ~[lwm2mfe.jar:na] at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) ~[lwm2mfe.jar:na] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212] at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212] Caused by: java.lang.Exception: handshake flight 1 failed! at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2403) ~[lwm2mfe.jar:na] ... 6 common frames omitted Caused by: java.lang.Exception: handshake flight 1 timeout after 4 retransmissions! at org.eclipse.californium.scandium.DTLSConnector.handleTimeout(DTLSConnector.java:2399) ~[lwm2mfe.jar:na] ... 6 common frames omitted
```

I suppose at Leshan side we should also add the NONE mode when needed(UQ device) to response too. 
And probably there is no issue at Californium side (except the transparent block2 stuff we discuss before).
Or do you think we should do something at cf side ?

**Comment by boaks** [comment]
When PR #1188 is polished, I would like to merge it into 2.1.0.
Depends on the future outcomes of this story, we can either include it in a 2.0.1 or not.

**Comment by boaks** [comment]
should we add a counter for such received "close_notifies" in the dtls-health?

**Comment by sbernard31** [comment]
> When PR #1188 is polished, I would like to merge it into 2.1.0.

:+1: 

> Depends on the future outcomes of this story, we can either include it in a 2.0.1 or not.

Do you plan to release the 2.1 soon (something like in 1 month) ? if yes, I will rather integrate the 2.1 in Leshan than a 2.0.1.

> should we add a counter for such received "close_notifies" in the dtls-health?

I don't know. For now we monitor DTLS with `SessionListener` and so we don't use `DtlsHealth`. I didn't look at this deeper but I have pretty much the same feeling than for `MessageInterceptorListener`. I think we should try to merge those ways to monitor the DTLS connector. (but this is another question)

> I suppose at Leshan side we should also add the NONE mode when needed(UQ device) to response too.
And probably there is no issue at Californium side (except the transparent block2 stuff we discuss before).
Or do you think we should do something at cf side ?

Any idea about that ? I look at a way to set the handshake mode NONE on response and there is no good way to do. (mainly because of [that](https://github.com/eclipse/californium/blob/2.0.0/californium-core/src/main/java/org/eclipse/californium/core/network/Exchange.java#L372))

Waiting for a better way, I implemented a crappy way like this : 
```java
 @Override
public void handleRequest(Exchange exchange) {
    Request currentRequest = exchange.getCurrentRequest();
    if (currentRequest != null) {
        final EndpointContext sourceContext = currentRequest.getSourceContext();
        if (sourceContext != null) {
            MapBasedEndpointContext newContext = MapBasedEndpointContext.addEntries(sourceContext, DtlsEndpointContext.KEY_HANDSHAKE_MODE,DtlsEndpointContext.HANDSHAKE_MODE_NONE);
            currentRequest.setSourceContext(newContext);
        }
    }
    super.handleRequest(exchange);
}
```

**Comment by boaks** [comment]
I would do that in a `MessageInterceptor`. Please check, if a `DtlsEndpointContext.KEY_HANDSHAKE_MODE` is not already set.

Some time ago, my intention was to keep the endpoint-context unmodifiable in order to reuse the instances. I still think, that "clone&modify" is the right approach.

**Comment by boaks** [comment]
```
public void sendResponse(Response response) {
	Request current = currentRequest;
	response.setDestinationContext(current.getSourceContext());
	endpoint.sendResponse(this, response);
}
```

Or adapt this to check, if the destination-context is already set.

**Comment by boaks** [comment]
> Do you plan to release the 2.1 soon (something like in 1 month) ? if yes, I will rather integrate the 2.1 in Leshan than a 2.0.1.

I have no strong opinion on that. 
I would appreciate, if some proxy stuff could be finished, but that's not too important.
I have a very rare race condition left in "cancel observe", but I didn't analysed that so far.  
Let me put the PR #1188 stuff on my "continues testing systems" for a couple of days, and see, if it's OK. After that, we can decide about the scheduling for 2.1.

**Comment by boaks** [comment]
```
public void sendAccept() {
	assert (origin == Origin.REMOTE);
	Request current = currentRequest;
	if (current.getType() == Type.CON && current.hasMID() && !current.isAcknowledged()) {
		current.setAcknowledged(true);
		EmptyMessage ack = EmptyMessage.newACK(current);
		endpoint.sendEmptyMessage(this, ack);
	}
}

public void sendReject() {
	assert (origin == Origin.REMOTE);
	Request current = currentRequest;
	if (current.hasMID() && !current.isRejected()) {
		current.setRejected(true);
		EmptyMessage rst = EmptyMessage.newRST(current);
		endpoint.sendEmptyMessage(this, rst);
	}
}

public void sendResponse(Response response) {
	Request current = currentRequest;
	response.setDestinationContext(current.getSourceContext());
	endpoint.sendResponse(this, response);
}
```

The issue seems to be more complex :-).
Maybe we add an "send context" to be used, if provided.

**Comment by sbernard31** [comment]
> Or adapt this to check, if the destination-context is already set.

Maybe this solution is more straightforward for user. I mean it can create the `Response` set the `Context` then call `coapExchange.respond(myResponse)` in an `handleRequest` method of a `CoapResource` ?

**Comment by sbernard31** [comment]
> The issue seems to be more complex :-).

Because this not only about response ?

**Comment by boaks** [comment]
Yep ...

**Comment by sbernard31** [comment]
for empty message I ask myself if this make sense to allow to initate an handshake :thinking:

To be honest I also asked myself for response but this make sense at least for notify and maybe also for some separated response.

**Comment by boaks** [comment]
For me, the question would be, where leshan decides to use "none" or not.
Generally a "send/destination context" in the Exchange maybe a solution, but that depends on leshan, if that's a proper way.

**Comment by sbernard31** [comment]
About Leshan, the idea was to not initiate handshake at server side for queue device as if we don't have connection for this devices that probably means is not reachable anymore (NAT, sleep mode ...)
On this part I pretty sure this is the right way to do.

For empty message and response this is not so clear...
I would say that it does not make sense to initiate an handshake on empty message. (queue or not queue)
For response, as LWM2M server does not send `notify` and should not really need to use `separate response` my naive answer for now would be we don't need to initiate handshake on response too.

So both solution works for Leshan.

But my feeling is that "empty message should not initiate handshake" can maybe be generalized to all coap use case.  If we do that set context on response is more homogeneous as this looks like how we handle context on request.

But maybe we should also think about transparent block wise response too ? in this case both method should work but maybe the `send/destincation context` on Exchange will works out of the box.

**Comment by boaks** [comment]
Or maybe a new dtls connector configuration "onlyOnTrigger", which only starts handshakes, if the message contains the handshake-mode "may-start".

**Comment by sbernard31** [comment]
and this mode will be the default one in the 3.0.0 ?

**Comment by boaks** [comment]
If "clientOnly" is `true`, I'm not sure.

I still in list the options.

Maybe also a flag in RawData would do a good job, especially, if ack/rst should be excluded.

**Comment by sbernard31** [comment]
> If "clientOnly" is true, I'm not sure.

It makes sense. 
`onlyOnTrigger` make sense only sense for connector which act as client and server.

> Maybe also a flag in RawData would do a good job, especially, if ack/rst should be excluded.

I'm not sure to see how user could set this rawData flag :thinking:

**Comment by boaks** [comment]
I tried to address this issue with PR #1193 

That would introduce a "default handshake mode" for the dtls connector.
Additionally an new handshake mode "auto".
For the most servers, default "none" and in some cases request with auto will do it.
For the most clients, default "auto" will be used for backwards-compatibility.

**Comment by sbernard31** [comment]
My first test with leshan sounds to be OK, we will see if it behaves better in production.
