### ISSUE TITLE
Be able to refuse to add an observation in ObservationStore API

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1187]
In Leshan before to add an observation to the `ObservationStore` we ensure that the registration linked to the observation is "still alive".
If this is not the case we refuse to add it to the store.
The way we do that is [by raising an `IllegalStateException`](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M13/leshan-server-redis/src/main/java/org/eclipse/leshan/server/redis/RedisRegistrationStore.java#L556), this sounds to works but this generate this kind of warning logs : 
```
[apServer(main)#1] o.e.c.c.n.stack.BaseCoapStack    [] error send request CON-GET    MID=19358, Token=9129D067B33608DA, OptionSet={"Observe":0, "Uri-Path":"10251"}, no payload
java.lang.IllegalStateException: no registration for this Id
 at com.sierrawireless.airvantage.app.lwm2m.registration.RedisRegistrationStore.add(RedisRegistrationStore.java:598) ~[lwm2mfe.jar:na]
 at com.sierrawireless.airvantage.app.lwm2m.registration.RedisRegistrationStore.putIfAbsent(RedisRegistrationStore.java:576) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.BaseMatcher.registerObserve(BaseMatcher.java:187) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.UdpMatcher.sendRequest(UdpMatcher.java:121) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:799) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:227) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:105) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:322) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendRequest(ExchangeCleanupLayer.java:63) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:184) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:86) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.CoapEndpoint$8.run(CoapEndpoint.java:669) [lwm2mfe.jar:na]
 at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) [lwm2mfe.jar:na]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212
```

I ask myself if we can not introduce a better way to handle this ?

**Comment by boaks** [comment]
Sure. 
Just a special Exception, which doesn't log?

**Comment by sbernard31** [comment]
Something like this :)

**Comment by boaks** [comment]
```
if (token == null) {
	do {
		token = tokenGenerator.createToken(Scope.LONG_TERM);
		request.setToken(token);
	} while (observationStore.putIfAbsent(token, new Observation(request, null)) != null);
} else {
	observationStore.put(token, new Observation(request, null));
}
```

Or we check for "send errors", that maybe also an approach.
(And for cancel(), but that is more in the case, that the request gets canceled somewhere else.)

**Comment by sbernard31** [comment]
> we check for "send errors", that maybe also an approach.

Not sure to see the idea ? if the idea is that `ObservationStore` implementation should call `observation.geRequest().setSendError(new MyException())` ? I really don't see the benefits of this compared to just throw an specific checked exception . :thinking:

**Comment by boaks** [comment]
> I really don't see the benefits of this compared to just throw an specific checked exception.

FMPOV, currently either the cancel or send error approach is used to stop Messages by intention. The exceptions seems to occur for the "unintended cases". But, sure, the difference is not that large.

**Comment by sbernard31** [comment]
From the `ObservationStore` implementation perspective, I think this is more straightforward to add a new exception instead of  explain to implementers that they need to do something like : `observation.geRequest().setSendError(new MyException())`.

In the end, I suppose the stack will catch this error and do a `request.setSendError(storeException);`

**Comment by boaks** [comment]
That raises the question, if a callback is safe to throw Exceptions, even, if that behavior is not defined in the javadoc. For both, exception or "send error/cancel" a specification of the behavior must be added to the javadoc of the callback interface.

And just again:
Currently is see the "cancel/send error" as more common in callbacks then the exceptions. So I'm not sure, if using that exception doesn't introduce more followup changes by using exception then for other cases.

**Comment by sbernard31** [comment]
> That raises the question, if a callback is safe to throw Exceptions, even, if that behavior is not defined in the javadoc. For both, exception or "send error/cancel" a specification of the behavior must be added to the javadoc of the callback interface.

I don't know exactly what "safe" means but anyway the idea here would be to make this part of the API by adding something like a `throws StoreException` (or any better name :sweat_smile:)
In this case a javadoc is better, but I guess for most users this is straightforward to understand it is allowed to raise it.

> So I'm not sure, if using that exception doesn't introduce more followup changes by using exception then for other cases.

I'm not sure to see what issue you are in mind but it seems to me that this would behave approximately in a same way, the only difference is the API exposed.
I mean the store will raise the exception and somewhere it will be catch and "send error" will used : 

```java 
catch (storeException e)  {
    LOGGER.debug("unable to add observation ... blah.. blah ", e);
    request.setSendError(e);
    return;
}
```

**Comment by boaks** [comment]
My point is:
AFAIK, it was never intended, that callbacks are allowed to throw unchecked exceptions. At least from my side, this is not explicitly implemented nor tested.

**Comment by sbernard31** [comment]
> AFAIK, it was never intended, that callbacks are allowed to throw unchecked exceptions. At least from my side, this is not explicitly implemented nor tested.

Ok. We know that currently this usage is not really expected.
We did that because we think that keeping the redis database consistent is more important than "unexpected behavior" in the coapstack.

So our feedbacks : we do that in production since a long time. Currently the way the stack handles this sounds not so bad.  Like any unexpected exception which could be raised in the stack. 

``` java
try {
	top.sendRequest(exchange, request);
} catch (RuntimeException ex) {
	LOGGER.warn("error send request {}", request, ex);
	request.setSendError(ex);
}
```
The only issue we face is the irritating log as we consider this as a normal behavior.

**Comment by boaks** [comment]
You did that with the awareness, that you must check the resulting behavior, which was possible for you though you know a lot of californium implementations details. I would also guess, that in the most cases everything should work, but "guess" is different from "grant".

With that:
If someone cancel a request or set the send error, that seems for me to be more common and "safe" (OK, without change, in this case it will be "endless" :-) ), than start throwing exceptions in one place, where it works.

**Comment by sbernard31** [comment]
> If someone cancel a request or set the send error, that seems for me to be more common and "safe" (OK, without change, in this case it will be "endless" :-) ), than start throwing exceptions in one place, where it works.

This is really don't clear to me : 
1. Do you think there is a concrete implementation issue to throwing exception in store ?
2. Do you think this is a better API ?
3. (maybe both ?)

**Comment by boaks** [comment]
> I would also guess, that in the most cases everything should work, but "guess" is different from "grant".

1. I "guess" there is no issue. Therefore I don't see a concrete issue. But there maybe some.

2. For me it's more passive. In that case of this issue, to escape the loop with set send error, someone has to request for. And with that request the API gets documented and, FMPOV, improved.

**Comment by sbernard31** [comment]
> For me it's more passive. In that case of this issue, to escape the loop with set send error, someone has to request for. And with that request the API gets documented and, FMPOV, improved.

I still don't get your point :sweat_smile:

**Comment by sbernard31** [comment]
You meant you want to handle the case where request goes in error during [this loop](https://github.com/eclipse/californium/issues/1187#issuecomment-575906764) anyway ?

If yes, I don't know if this is a good idea. I'm not even sure that `setSendError` is intended to be called by users.
At least, it seems to me this is not needed to handle my use case.

**Comment by boaks** [comment]
> I really don't see the benefits of this compared to just throw an specific checked exception 

I tried that out, but revapi reports:

> [ERROR] java.method.exception.checkedAdded: method org.eclipse.californium.core.observe.Observation org.eclipse.californium.core.observe.ObservationStore::put(org.eclipse.californium.core.coap.Token, org.eclipse.californium.core.observe.Observation) throws org.eclipse.californium.core.network.StoreException: Method newly throws checked exceptions: org.eclipse.californium.core.network.StoreException. (breaks semantic versioning)
> [ERROR] java.method.exception.checkedAdded: method org.eclipse.californium.core.observe.Observation org.eclipse.californium.core.observe.ObservationStore::putIfAbsent(org.eclipse.californium.core.coap.Token, org.eclipse.californium.core.observe.Observation) throws org.eclipse.californium.core.network.StoreException: Method newly throws checked exceptions: org.eclipse.californium.core.network.StoreException. (breaks semantic versioning)

So, either:
1. "unchecked" or 
1. revapi ignore, or 
1. cancel/setSendError.

**Comment by sbernard31** [comment]
Currently for reason expose above, I don't really like the 3. (cancel/setsenderror)
My preference is 1. unchecked (+ eventually a TODO to make it checked for 3.0)
But if you prefer 2. (revapi ignore) it's ok for me too.

**Comment by boaks** [comment]
[RevAPI, runtime exception](https://revapi.org/modules/revapi-java/index.html#method_now_throws_a_runtime_exception)

[RevAPI, checked exception](https://revapi.org/modules/revapi-java/index.html#method_now_throws_a_checked_exception)

Seems that both are considered to potentially break semver.
The left issue seems to be, that if this interface is used also somewhere else (outside californium), then it breaks the API.

**Comment by sbernard31** [comment]
RevAPI, runtime exception :
>This is both source and binary compatible but represents a danger for the semantics of the user code that might want to catch the newly thrown exception.

This look more like a warning than a real issue.

FMPOV, in our case  it's OK to add the unchecked exception, we keep source and binary compatibility.
This interface is intended to be implemented by users, so their versions will not raise the new exception so  even if the interface is used  outside of californium it should not be a problem.


Else the fully compatible way is to create a new interface v2 with the checked exception. (it seems a bit overkill to me)

**Comment by boaks** [comment]
See PR #1207 

I still don't think, that such an exception has advantages, but if you prefer it, we can got for it.

**Comment by sbernard31** [comment]
> I still don't think, that such an exception has advantages

compare to what  ?

**Comment by boaks** [comment]
>  compare to what ?

My alternative proposal is the comments above.

**Comment by sbernard31** [comment]
...
