### ISSUE TITLE
Tls/TcpClientConnector using netty / really required?

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#119]
Using netty for the server may be OK, but for the client I think it would work also without.
So are there any reasons to use netty on the **clients**?

**Comment by joemag1** [comment]
Is there downside to using Netty? What's the alternative?

**Comment by boaks** [comment]
The downside is, that the "client-plattform" has to support/provide it :-).
Depends on that plattform, it may be not available.

**Comment by joemag1** [comment]
Saying something shouldn't be used, without providing an alternative is not
very helpful. What would you use to provide async IO functionality?

**Comment by boaks** [comment]
Why must a client use async IO? So even with a "some" LWM2M Servers, you may use a thread for each.
So I would just see for an alternative implementation using "plain" java. 

But it's not pior 1.

**Comment by joemag1** [comment]
You may have many outgoing connections, and you don't want to block others
because of a single slow one. You also need to deal with hand off of
received packets - and separation of IO and protocol threads removes some
sharp edges there.

Because of these, any plain Java implementation will likely end up with
significantly more complexity than Netty.

But if there are domains where that complexity is preferred to using netty,
then we can provide an alternative implementation and put it behind a
config property.

**Comment by sophokles73** [comment]
IMHO we will probably deal with two classes of clients:
* constrained devices that do not run Java anyways: for these it doesn't matter whether we use Netty or not
* gateway-type class devices that have enough power to run Java decently: for those it is usually no problem to also use Netty. This is also true for smart phones I assume ...

I therefore think that we can/should stick with the Netty based client for now. If later someone needs a more *constrained* client implementation we can still add one ...

**Comment by sophokles73** [comment]
@boaks 

I will now close this issue, feel free to open a PR with an alternative (client side) implementation e.g. based on plain Java NIO.

**Comment by kaikreuzer** [comment]
I'd like to revive this discussion (sorry, I only stumbled over it by chance now).

> gateway-type class devices that have enough power to run Java decently: for those it is usually no problem to also use Netty

@sophokles73 Sorry, I do not agree at all. Running an Eclipse project that currently uses Californium for CoAP support and which targets exactly such devices, I can tell you that an additional dependency of 1.5 MB (or what is actually needed?) is a huge pain - especially, if it isn't needed at all.
The whole Eclipse SmartHome stack is about 20MB, which includes the whole OSGi framework. We put huge efforts into keeping the stack small and adding such dependencies just for a protocol that claims to be "lightweight and made for embedded" is a no-go. We are currently using Californium 1.0.6, which has a decent size and is self-contained in its own. This new Netty dependency blocks any future version upgrade for us.

I am not asking for an alternative implementation of the same functionality as Netty.
What I rather expect from an Eclipse project is good support of OSGi and an appropriate level of modularity. If I understand it right, Netty is currently only required for TCP support, which isn't even part of the official CoAP spec (yet).
Couldn't this dependency hence declared optional in the manifest? Or even better: Could the TCP support be packaged as a separate, optional jar/bundle?

**Comment by boaks** [comment]
> What I rather expect from an Eclipse project is good support of OSGi and an appropriate level of modularity. If I understand it right, Netty is currently only required for TCP support, which isn't even part of the official CoAP spec (yet).

FMPOV "modularity" on a moving specification as draft-ietf-core-coap-tcp-tls-09 is unfortunately not that easy, because while the draft is moving, the dependencies may change in a unpredictable way. 

But as I understand you well, your main point is to have the possibility not to include netty, if you don't need TCP. Some "minor additional" classes in the core are not that relevant?

**Comment by kaikreuzer** [comment]
> while the draft is moving, the dependencies may change in a unpredictable way.

Well, this is another argument FOR keeping it separate from the rest of the code :-)

> But as I understand you well, your main point is to have the possibility not to include netty, if you don't need TCP.

Yes, correct.

> Some "minor additional" classes in the core are not that relevant?

If you are referring to the classes such as `TcpClientConnector`, which require Netty: Yes, if all of them are in separate Java packages and it is made clear that whoever uses these packages will require Netty to be present, that would be ok.
But as mentioned above: The cleaner approach from an OSGi perspective would be to have those classes in a separate jar/bundle. But I do not care much, which solution is chosen as long as there is one :-)

**Comment by boaks** [comment]
With "some "minor additional" classes" I ment `TcpAdaptionLayer` of the core package. 
I would check, if the TCP connector stuff in the "element-connector" could be moved into a separated project and therefore get rid of the mandatory TCP netty dependencies.

So, what timeline plans do you have? Are you consider using 1.1 or 2.0?

**Comment by sbernard31** [comment]
Personnally, I'm not against having a clear separation with something like a new `element-connector-tcp` and `californium-tcp` projects.

**Comment by boaks** [comment]
The issue is much more: who will do it :-).

Therefore I try to find, what is required at least ...

**Comment by kaikreuzer** [comment]
> what timeline plans do you have? Are you consider using 1.1 or 2.0?

No time pressure on my side, we don't have any immediate plans for upgrading.
But let me return the question: What is the timeline for 1.1/2.0 releases? From what I see [here](https://github.com/eclipse/californium/releases), only 1.0.6 is an official release (and not even mentioned explicitly) so far.

**Comment by boaks** [comment]
> But let me return the question: What is the timeline for 1.1/2.0 releases? 

We currently fixing a couple of issues and we try to solve the 
"observing a resource over DTLS with changing IP endpoints" issue 
(see https://www.ietf.org/mail-archive/web/core/current/msg07813.html). 

And your "reopen" of an half a year old issue shows, that maybe even the users haven't already told us, how they use californium and what are the requirements of such a usage.

So FMPOV we can not announce a realistic timeline for 2.0. 
But that's just my personal opinion.

**Comment by kaikreuzer** [comment]
>the users haven't already told us, how they use californium

Just to give you a small "customer success story": [This](https://twitter.com/kaikreuzer/status/887329151920750593) has been made possible by Californium 👍

**Comment by boaks** [comment]
Thanks! 

https://github.com/eclipse/californium/issues/372#issuecomment-319611673

So even that "customer success story" you reported strikes back and consumes unplanned time to sort out windows 10 specific issues :-).

**Comment by kaikreuzer** [comment]
At least it doesn't seem to be an openHAB user, so I do not feel guilty ;-)
But I guess that IKEA has helped attracting quite some new users for Californium in general.
We are also still struggling with [irregular connection losses](https://github.com/eclipse/smarthome/issues/3869) - once I find more time to dive deeper into it, I have the need upgrade to a newer/patched version. But ok, I am moving completely off-topic, sorry, I keep quiet now.

**Comment by sbernard31** [comment]
@kaikreuzer, since #469  element-connector-tcp has its own project. Is it acceptable now ?

**Comment by kaikreuzer** [comment]
Excellent, looks good! Thanks a lot 👍
