### ISSUE TITLE
Too extensive log in CoapEndpoint in case of CoAP Ping

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/californium#12]
CoapEndpoint logs every response to a CoAP ping on log level INFO. In my opinion that is to extensive. It is not helpful for an administrator to see that the server got pinged.

For example, to check if our server is still reachable we send a ping to it every second. If we do not lower the log level to WARNING for CoapEndpoint our logs are full with these ping log statements. 

What do you think about that, what would be a more appropriate log level? FINEST?

**Comment by sophokles73** [comment]
I agree, on master the log level for ping messages has already been reduced to FINER.

**Comment by DanielMaier-BSI** [comment]
Sorry my fault, I did not have a look on the master. I think i can close this issue.
