### ISSUE TITLE
TcpMatcher and Notifications

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#121]
Currently notifications are "only" processed in the UdpMatcher.
Does TcpMatcher require the same functionallity?
Are there any plans to change something there in the near future?

**Comment by sophokles73** [comment]
I guess you are referring to the `TcpMatcher.receiveResponse()` method where we currently do not have the same logic for looking up observation information etc. as in the corresponding method of `UdpMatcher`, right?

**Comment by boaks** [comment]
Yes, its missing the "notificationListener.onNotification(request, response);" call.
I think, the "UdpMatcher" has clustering/persistent logic, and therefore is rather complex.
Is this intended to be also in the TcpMatcher? Or could we start with an "simple" approach?

**Comment by sophokles73** [comment]
I think it would be strange if they would behave differently. So my preference would be to also have the clustering support for TCP ...

**Comment by boaks** [comment]
So what does clustering "TCP/TLS" mean?
Is the client intended to establish a new connection?
Or is the connection transferred to a other node?

**Comment by sophokles73** [comment]
That's a good question ;-) We might not be able to provide the same functionality as in the DTLS case since we will probably not be able to resume the TLS connection with another backend node. Thus, we will not be able to fail-over the existing observations ...

**Comment by sophokles73** [comment]
That's a good question ;-) We might not be able to provide the same functionality as in the DTLS case since we will probably not be able to resume the TLS connection with another backend node. Thus, we will not be able to fail-over the existing observations ...

**Comment by boaks** [comment]
Maybe, this depends on the outcome of the "long term observation" issues in core.
I will make a simple non cluster/failover solution just for testing coap+tcp in leshan.
We will see, if this simple solution makes then sense  or is just for early leshan testing.

**Comment by sophokles73** [comment]
Sounds good to me :+1:

**Comment by boaks** [comment]
"simple" simply doesn't work with leshan ;-(.

The coupling between californium and leshan is not only 
"NotificationListener.onNotification(Request coapRequest, Response coapResponse)",
the "observationStore" must be handled also in the intended way.

Will take some more time ...

**Comment by boaks** [comment]
See #134
