### ISSUE TITLE
Add a specific exception for HandshakeTimeout ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1223]
In Leshan, when a [request timeout for any reason](https://github.com/eclipse/leshan/wiki/Request-Timeout) we raise a TimeoutException.
We decide recently to consider a Handshake flight timeout as Leshan request timeout.

But currently there no easy way to know handshake timeout because we raise an `Exception`.
So the code looks like something like this : 
```java
    if (error instanceof Exception && error.getMessage().startsWith("Handshake flight")) {
```
Should we raise a specific exception ? 

(Ideally I would like to be able to distinguish a CoAP timeout from a Blockwise timeout but I guess this would be a really more complex task , this is maybe relative to https://github.com/eclipse/californium/issues/818 ?)

**Comment by boaks** [comment]
> Ideally I would like to be able to distinguish a CoAP timeout from a Blockwise timeout but I guess this would be a really more complex task

is the "CoAP timeout" the timeout of a single request? And the blockwise timeout then the timeout of the complete blockwise transfer?

**Comment by sbernard31** [comment]
Nope I try to explain "my terminology" in this [wiki page](https://github.com/eclipse/leshan/wiki/Request-Timeout).

Let me know if this is not clear.

My idea is to let user aware of the cause/type of the timeout and so he will be able to change it if needed.

**Comment by boaks** [comment]
1. a specific exception for handshake timeouts should be possible.

2. the CoAP timeout should already work (`Message.isTimedOut()`). Do you see any issue with it?

3. the blockwise timeout seems to be more your domain (at least it's based on your contributions). My impression is, that this timeout mainly occurs on the server-side to free the resource payload.

**Comment by sbernard31** [comment]
> 1. A specific exception for handshake timeouts should be possible.

:+1: ! 

> 2. The CoAP timeout should already work (Message.isTimedOut()). Do you see any issue with it? 

AFAIK, there is no issue here. (In leshan we use MessageObserver.onTimeout(). (see https://github.com/eclipse/leshan/pull/812/commits/3e1002628416688ca5e94fd4f84d198ae17b3070)

> 3. the blockwise timeout seems to be more your domain (at least it's based on your contributions). My impression is, that this timeout mainly occurs on the server-side to free the resource payload.

I think you're right in normal use case this should mainly be a timeout at server side.
The only exception I see is if CON is not used or piggybacked is not used (which is maybe out of spec) in the case request could be timed-out (so at client side). Anyway as I said I can not see easy way to do that without modifying the API. (This is more a midterm/longterm thinking)

**Comment by sbernard31** [comment]
:thinking:  in that case I feel it normal as we cancel the request before, or I missed something ?

**Comment by boaks** [comment]
>  in that case I feel it normal as we cancel the request before

What is considered to be **normal**? The blockwise timeout?

**Comment by sbernard31** [comment]
I was talking about : 

> so even that may not end up in a blockwise timeout.
