### ISSUE TITLE
`recommendedCipherSuiteOnly` is not hold by `DtlsConnectorConfig`.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1225]
About `DtlsConnectorConfig`, `clientOnly` and `recommendedCipherSuitesOnly` attributes belong to the builder instead of the `DtlsConnectorConfig`.

The way it is used in Leshan, this information is lost. (see [CaliforniumEndpointsManager](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M13/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/CaliforniumEndpointsManager.java#L86))

Could we move those in `DtlsConnectorConfig` ?

**Comment by boaks** [comment]
[feel free](https://github.com/eclipse/californium/pull/1029#discussion_r312373503)

**Comment by sbernard31** [comment]
Not used by Leshan servers but Leshan client. :)

**Comment by boaks** [comment]
Still, "feel free" to contribute that. Regardless, if it's required by the server or client.

**Comment by boaks** [comment]
Do you want to contribute it for the 2.1.0 release? Or afterwards?

**Comment by sbernard31** [comment]
ideally for the 2.1.0 as I would like to integrate it for Leshan 1.0.0

**Comment by boaks** [comment]
OK, so I wait with the release for your contribution.
