### ISSUE TITLE
Clarification on network configuration keys

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#1231]
Californium version : m12
Leshan version : M10

NETWORK_STAGE_RECEIVER_THREAD_COUNT 
NETWORK_STAGE_SENDER_THREAD_COUNT 

What are these network keys used for?

**Comment by sbernard31** [comment]
AFAIK, this is the number of thread used by `UDPConnector` to receive or send data. (see https://github.com/eclipse/leshan/issues/789#issuecomment-577127595)

(With californium plugtest "demo", this could also affect `DTLSConnector`)

**Comment by madhushreegc** [comment]
Thank you for answer.
