### ISSUE TITLE
Should we activate offloading by default ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1254]
When I read the PR #1238, I saw that it was activated by default and I haven't any concern about this because I just thought this was an optimization without any behavior drawback.

But since v2.2.0-RC1, I have several tests which do not pass anymore (not in Leshan, another project) mainly because of  `IllegalState message FULL offloaded!`

Generally, the pattern which cause the illegalstate is something like  : 
```java
Request commandRequest = lwm2mClient.waitRequest();
assertNotNull(commandRequest);
assertEquals(Code.POST, commandRequest.getCode());
assertEquals("/asset/engine/start", new URI(commandRequest.getURI()).getPath());
 ==> BOOM
```

`lwm2mClient.waitRequest()` is custom code which collect request received with an interceptor.

My point here is that maybe offloading feature is more impacting than expected  (it could break behavior compatibility) and maybe we should deactivate it by default (at least for a 2.x version)

What do you think ?

**Comment by boaks** [comment]
coap-server side? Is it a `PostProcessInterceptor`?

**Comment by sbernard31** [comment]
```java
  coapEndpoint.addInterceptor(new MessageInterceptor() {

            @Override
            public void receiveRequest(Request request) {
                LOG.debug("received request: {}", request);
                receivedRequests.add(request);
                requestLatch.countDown();
            }
```
and 
```java
    public Request waitRequest() throws InterruptedException {
        requestLatch.await(5, TimeUnit.SECONDS);
        return receivedRequests.poll();
    }
```

**Comment by boaks** [comment]
Yep, so just "protect" the request in the callback, if you want to use it later :-).

If we set the default to `false`, I'm not sure, if we get such important error reports.
But for the 2.2.0 we can set it to false and enable it for the SNAPSHOT again.

**Comment by sbernard31** [comment]
> Yep, so just "protect" the request in the callback, if you want to use it later :-).

I get the point but this seems to be a behavior break :thinking:

> But for the 2.2.0 we can set it to false and enable it for the SNAPSHOT again.

For cf, I think it's probably better.  
To be honest for Leshan I don't know If I should activate or deactivate it by default :sweat_smile:.

**Comment by sbernard31** [comment]
Silly question, instead of offloading the request for deduplicator, should we store only data we need to deduplicate (in another bean). This way this optimization would be more transparent for users ?

**Comment by boaks** [comment]
> I get the point but this seems to be a behavior break

Sure, but for that, either switch it off or use `setProtectFromOffload`.

> instead of offloading the request for deduplicator, should we store only data we need to deduplicate (in another bean). 

Or "duplicate" the request for the exchange and offload that double. 
But I guess, this will hit something else. 
In my opinion, if someone want to use that feature, it's just important to know, how it works.

**Comment by sbernard31** [comment]
I talk about that with @msangoi, we decide to deactivate it for now (in Leshan and in our product)

I try to looked at the code and `Deduplicator` is not as simple ...
My feeling is, if there is a more transparent way we should maybe give it a try. (you know better than me if this is doable or not)
In all case we should deactivate it by default in 2.x (it could be activate by default for 3.x), knowing that this feature is really needed only if you have memory issue with deduplicator. (in that case you will probably search a solution and find/try offloading)

Should we close this issue ?

**Comment by boaks** [comment]
yes.

**Comment by boaks** [comment]
Default is no `false`.
Don't forget to cleanup all "Californium???.properties".

**Comment by sbernard31** [comment]
If you think this is valuable, I can activate it on leshan sandbox ? (maybe a safe way to "test" this feature)

**Comment by boaks** [comment]
That would be great!
In the meantime, I get also doubts about the general usage of this solution.
I consider, keeping the default to `false` and just document, that this maybe one option to overcome a "deduplicator heap overload" (the other one is a smaller max_exchange_times).

**Comment by sbernard31** [comment]
I activated offloading on leshan sandboxes (https://leshan.eclipseprojects.io and https://leshan.eclipseprojects.io/bs)
