### ISSUE TITLE
DTLS seq_no incremented in Handshake protocol

### ISSUE THREAD

**Issue by kiemlicz** [eclipse/californium#1257]
Branch: all of them

I spotted that Scandium implementation increments DTLS `seq_no` during handshake retransmissions

I think this is not compliant with RFC: https://tools.ietf.org/html/rfc6347#section-4.2.2
(see the example linked) and some other implementations fails to process such retransmission.

**Comment by boaks** [comment]
Just to ensure, that we have no misunderstanding:

There are two different "number sequences", one for the records

[sequence_number](https://tools.ietf.org/html/rfc6347#section-4.1)

and one for the handshake messages

[message_seq](https://tools.ietf.org/html/rfc6347#section-4.2.2)

According the [sequence diagram](https://tools.ietf.org/html/rfc6347#19) and the note below that diagram

>  Note, however, that from the perspective of the DTLS record layer,
>  the retransmission is a new record.  This record will have a new
>  DTLSPlaintext.sequence_number value.

The record's number is incremented, while the handshake's number is kept.

Do you have different experience?

**Comment by kiemlicz** [comment]
Thank you!

This is my misunderstanding, you're right. These are different sequence numbers and both are handled properly
