### ISSUE TITLE
new ciphersuite selection

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1259]
With PR #1256 and #1258 new possibilities are enabled, but also the risk, that a handshake is aborted or encryption function are chosen, which may be considered weaker (e.g. RPK instead of x509, or PSK instead of RPK).

Information to select the cipher suite:
- the supported ciphersuites of both sides (pre-selected by the available credential types)
- the supported signing and hash algorithms of both sides (scandium actively uses only EC-based, but may passively use also other to verify the certificate chain, if the JRE supports that)
- the supported curves of both sides 
- the certificate-type (x509 or RPK) of both sides 

That affects mostly the server-side selection.
Though both PRs are changing al lot of common code, I would therefore prefer to postpone the implementation (and discussion) of this selection details after merging the two PRs.

Any opinions?

**Comment by sbernard31** [comment]
> I would therefore prefer to postpone the implementation (and discussion) of this selection details after merging the two PRs.

I'm lost the only new selection stuff is about sign and hash algorithms ? why not discuss this for the PR which introduce it ? :thinking:

**Comment by boaks** [comment]
Because, if you also look on the other PR, the changes for the "select ciphersuite" are affecting mostly the same source-lines as the other PR and so requires always a manual merges after adapting it (again and again :-) ).

**Comment by sbernard31** [comment]
This would be clearer to do 

So I don't know so much how to handle this, so I will list my comments/concerns here.
For  #1256 : 
1. the cipher selection
2. some part of the code could be clearer. (especially the create certificate call)
3. the default value for sign_hash. 

I will look at #1258 next week. (+2,692 −1,004 :cold_sweat:)

**Comment by boaks** [comment]
> I will look at #1258 next week. (+2,692 −1,004 cold_sweat)

Greta! [Start with XECDHECryptography](https://github.com/eclipse/californium/pull/1258#issuecomment-604372009) and a lot of the other changes will be much easier too understand.

**Comment by boaks** [comment]
> 1. the cipher selection

Therefore I opened this issue to signal, that this must be discussed.

> 2. some part of the code could be clearer. (especially the createCertificateRequest)

As always :-). And, also as always, that depends much on personal preferences. We will see ...

> 3. the default value for sign_hash.

With the openssl issue of today, I would go to pick additional sign_hash from the provided certificate chain as default. Scandium seems to comply with the definitions of [RFC 7252, 9.1.3.2](https://tools.ietf.org/html/rfc7252#section-9.1.3.2)

> The key used MUST be ECDSA capable.  The curve secp256r1 MUST be supported [RFC4492]; this curve is equivalent  to the NIST P-256 curve.  The hash algorithm is SHA-256. Implementations MUST use the Supported Elliptic Curves and Supported
> Point Formats Extensions [RFC4492]; the uncompressed point format MUST be supported;

So the default from RFC 5246 [sha1_ecdsa] seems to be not too `authoritative`.


The definition in RFC 5246 would have never been a too good choice for scandium,

**Comment by sbernard31** [comment]
My point about  "default", is not to say that scandium should use `sha1_ecdsa` my point is if it don't use it it should use the sign_hash extension and when a foreign peer don't use this extension is should consider the default as `sha1_ecdsa`.

**Comment by boaks** [comment]
Ah OK. Maybe, that was the intention of PR #1253.

**Comment by boaks** [comment]
> (+2,692 −1,004 cold_sweat)

Now "+2,131 −857" :-).

And 750 are the new `XECDHECryptography` with a lot of javadoc.

**Comment by sbernard31** [comment]
I add some items to the list : 

- the cipher selection
- some part of the code could be clearer. (especially the createCertificateRequest)
- the default value for sign_hash.
- is certtypes should be a list ? (https://github.com/eclipse/californium/pull/1258#discussion_r400233676)

**Comment by boaks** [comment]
I prepared a first proposal PR for the cipher selection part (server side only).
See PR #1270 .

**Comment by boaks** [comment]
Proposal for cipher suite selection:

1. Generate lists of "common" supported parameters, ordered by the client preference.
1. For each cipher suite, check, if the parameters could be supported
   1. PSK : doesn't depend on parameters, always selectable
   1. PSK-ECDHE: requires at least on common supported group (curve) for ECDHE. (Signing is not used, nor certificates, not certificate types.)
   1. ECDSA-ECDHE: requires at least on common supported group (curve) for ECDHE. There must be at least one common server certificate type. If client authentication is required or wanted, there must be also at least one common server certificate type.
The public key must use a common supported group, and at least one common signature and hash algorithm usable with the public key must exist.
If the server certificate type is X509, check all certificates to use a common supported group and a common signature and hash algorithm. If that check fails for one certificate, and RPK is also contained in the common list of supported server certificate types, select the cipher suite and use RPK. Otherwise, try the next cipher suite.

If client authentication is just wanted, it may be considered to select the cipher suite even if no common client certificate type exists.

**Comment by sbernard31** [comment]
If client authentication is required or wanted, there must be also at least one common ~server~ ?**client**? certificate type

It sounds good to me :)

> If client authentication is just wanted, it may be considered to select the cipher suite even if no common client certificate type exists.

For this part, I'm not sure. What is the use case for certificate wanted ? I imagine this is when certificate is "checked" at upper layer ?

**Comment by boaks** [comment]
If the certificate request is sent, the client sends it's certificate, even if this is a empty one.
With wanted, the server continues the handshake, with required the server aborts the handshake. 
if no "common parameters" are available for the client certificate, the certificate request will result in an empty certificate. 
So I see three possibilities:
1. don't select this cipher suite
1. select this cipher suite and request the client certificate anyway, and then let the empty certificate pass.
1. select this cipher suite and don't request the client certificate.

**Comment by sbernard31** [comment]
My first intuition is that : we should not select the cipher suite.
But as I'm not sure to well understand real use case for want certificate, maybe I'm wrong.

In all case, I think if there is another cipher suite which match parameters, ideally it should be preferred. I mean even if we decide that a cipher suite without common parameters could be selected. (I said ideally meaning that if we don't do that it's not a big deal)

**Comment by sbernard31** [comment]
I think #1270 addresses : 
- ~the cipher selection~
- ~some part of the code could be clearer. (especially the createCertificateRequest)~
- ~is certtypes should be a list ?~

if I'm not wrong, the missing one is : 
- the default value for sign_hash.

Maybe in another PR ? or we need to talk about this before ?

**Comment by boaks** [comment]
> Maybe in another PR ?

Yes, an other, new PR.
Therefore I titled the PR #1270 only with "Add new cipher suite and parameter selection".

**Comment by boaks** [comment]
And, not to forget, the client-side will also need a update, which parameter are provided for resumption. The RFC seems to forget, that sometimes the resumption fails and so at least the common parameter maybe be send instead of non parameter. But that requires also some investigation. :-)

**Comment by boaks** [comment]
In the meantime I managed to add test with openssl and libcoap/openssl for mixed certificate chains (ecdsa/rsa). These tests has shown, that the sig/hash algs in the "certificate request" are considered to be the server sides, not the reduced set of common sig/hash algs . I adapted that.

**Comment by boaks** [comment]
After some experience, I would go for ECDSAwithSHA256 and RSAwithSHA256 as default, and add the sig/hash algs contained in the provided certificate, if one is provided.

**Comment by sbernard31** [comment]
> After some experience, I would go for ECDSAwithSHA256 and RSAwithSHA256 as default

Could you explain why your experience led you to choose this ?

**Comment by sbernard31** [comment]
(Not directly linked to this and you probably already know that but just in case :
If there is some kind of behavior break/change like changing default value, it should good to identify it and make a list to document the next release)

**Comment by boaks** [comment]
> Could you explain why your experience led you to choose this ?

The interoperability tests with openssl. And issue #1260 .

**Comment by boaks** [comment]
> (Not directly linked to this and you probably already know that but just in case :
If there is some kind of behavior break/change like changing default value, it should good to identify it and make a list to document the next release)

FMPOV, introducing configurable sig/hash is a new feature. And so I guess, it will be on the list of changes. We may also add a remark about the changed behavior. Just to mention: this solution doesn't allow to provide no sig/hash for the hello extension. As far as I understand, other 1.2  implementations may ignore or process it, but should not fail. Therefore I didn't implement that "backwards compatibility".

**Comment by boaks** [comment]
OK to close?

**Comment by sbernard31** [comment]
The default value is ECDSAwithSHA256 / RSAwithSHA256 and so by default the extension is present, right ? 

Meaning : 

>My point about "default", is not to say that scandium should use sha1_ecdsa my point is if it don't use it it should use the sign_hash extension and when a foreign peer don't use this extension is should consider the default as sha1_ecdsa.

is done ?  

> when a foreign peer don't use this extension is should consider the default as sha1_ecdsa.

I'm not sure this part is implemented ?

**Comment by boaks** [comment]
> is done ?

The default is `SignatureAndHashAlgorithm.getDefaultSignatureAlgorithms()`. Californium uses It now for both sides, client and server.

> I'm not sure this part is implemented ?

That is implemented in `List<SignatureAndHashAlgorithm> ServerHandshaker.getCommonSignatureAndHashAlgorithms(ClientHello clientHello)`. 

> use this extension is should consider the default as sha1_ecdsa.

No, SHA1 is not longer recommended, RFC 5246 is deprecated in that.
For CoAP that would then result in deny ECDSA instead of accept the handshake as SHA256withECDSA, which is mandatory for CoAP. So I decided to send the certificate and the servers sig/hash list. The list is anyway not negotiated, as tests has shown and the RFC 5246 defines.

**Comment by sbernard31** [comment]
OK
