### ISSUE TITLE
Drops packet log analysis

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1276]
We face some logs in production about dropping packet at DTLS level.
I would like to see if you think this should be considered as normal or if there is an issue behind.
If this is "normal" I think we should probably consider to lower the log level.

(Let me know if you prefer 1 issue by log)

>DTLSConnector (DTLS-0.0.0.0:5686) drops X bytes, [PreSharedKey Identity [identity: BA274C9012492A8EADE271A07E50AF73]] != [PreSharedKey Identity [identity: 0AEC93A5BD00D7E597194D73AC808A18],TLS_PSK_WITH_AES_128_CCM_8]

This happens ~60/80 time by hours.
Reading the code I understand this happens when we try to send a message to a peer but this is no more the expected identity.
As the expected context does contain the Cipher, I guess the message is a request and not a response.
`EndpointMismatchException` will be raised on the message.
So this means that we try to send a request to a peer which is not behind this address anymore.

That sounds a normal use case, so maybe you should pass the log to debug ? or maybe even if this is "normal" this should not happens often else this means that you have some network issue anyway and so me must keep the log ? In the mean time the exception `EndpointMismatchException` is maybe enough to be aware of the network issue.

> Drop record with X bytes, connection lost address /121.31.250.168:13328! (shift 0ms)

This happens ~10/20 time by hours.
I'm not sure to be able to interpret the shift 0ms. This is almost always 0ms, the rare case (less than 10 times a day) when it is not, this is between 1 and 50 ms.
Reading the code I understand that happens when we try to send message and the connection is lost/closed (peer is not connected)
`EndpointUnconnectedException` will be raised on the message.
So it seems to be a normal use case, so should be lower the log ?

> Drop record [Alert|Application Data] (?), connection changed address /206.152.128.41:39489 => null! (shift 0ms)

This happens ~70/100 time by hours. Mainly Application Data.
New address is always null.
I'm not sure to be able to interpret the shift 0ms. This is almost always 0ms, the rare case (less than 10 times a day) when it is not, this is between 1 and 30 ms.
`No exception raised.`
Reading the code I understand that happens when we try to process and incoming record and the connection is lost/closed (peer is not connected)

So it seems to be a normal use case, so should be lower the log ?

>c.s.a.app.lwm2m.RequestSender    [endpoint=354723090124636, system=406aebe6355d4b23bc19756f7ddd40a7]
Could not send the request Request , address changed!
org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://10.16.3.196:56830/cloudInterface/dh/cmd at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:167)
at org.eclipse.californium.core.coap.Message.setSendError(Message.java:986)
at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1123) 
at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1259)
at org.eclipse.californium.elements.RawData.onError(RawData.java:303)
at org.eclipse.californium.scandium.DTLSConnector$1.handshakeFailed(DTLSConnector.java:439) 
at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:1275) 
at org.eclipse.californium.scandium.dtls.Connection.updatePeerAddress(Connection.java:296) 
Caused by: java.io.IOException: address changed!

This is less frequent ~30 time by day.
This is less clear to me. It seems to happens if a connection losts its peer address (address reused or connection closed) during and handshake which contains deferred message ?.
Knowing that we don't initiate DTLS connection from server side, how could we have a request in a deferred message queue of a handshaker ? we try to send a message during a handshake initiate by a client ? and this handshake failed because its address was "stolen" or the connection is closed during the handshake ?
` java.io.IOException: address changed!` is raised.

If this is correct this sounds a normal use case too : 
 - should we lower the log level ? 
 - the Exception class and message sounds not so good. Maybe we should create a dedicated exception or reuse EndpointUnconnectedException or DtlsException. The message should "address lost or connection closed during handshake" ?

**Comment by boaks** [comment]
> I would like to see if you think this should be considered as normal or if there is an issue behind.

That depends on 

- the clients implementation
- the communication patters
- and the network environment.

> That sounds a normal use case, so maybe you should pass the log to debug ? or maybe even if this is "normal" this should not happens often else this means that you have some network issue anyway and so me must keep the log ? In the mean time the exception EndpointMismatchException is maybe enough to be aware of the network issue.

I would prefer to introduce a "DROP_LOGGER" to be able to enable/disable the message drops easily. That may help to analyze the drop behavior from time to time. The messages should be also include a classifier for outgoing or incoming 

> Drop record with X bytes, connection lost address /121.31.250.168:13328! (shift 0ms)

My current concerns are race conditions around "close_notify". I already have a first experimental implementation of my idea [cheap cheat](https://github.com/eclipse/californium/issues/1273#issuecomment-612353485). With that, the logging messages may also indicate, if a "CLOSE" was the cause for the drop.


> org.eclipse.californium.scandium.dtls.Connection.updatePeerAddress(Connection.java:296)
> Caused by: java.io.IOException: address changed!

The stacktrace ends, where it would be interesting ...

I guess again, "CLOSE_NOTIFY" ...

**Comment by sbernard31** [comment]
> I would prefer to introduce a "DROP_LOGGER" to be able to enable/disable the message drops easily. That may help to analyze the drop behavior from time to time. The messages should be also include a classifier for outgoing or incoming

We can do that this could be great to review the log level with this kind of "rules" : 
- `Error` : (extremely rare) This MUST NOT happens => there is probably a bug somewhere.
- `Warning` : (pretty rare) This SHOULD NOT happens => there is maybe a problem.
- `Info` : (very rare) Mainly for information at startup or stop.
- `Debug`: (should not flood) This should show unexpected behavior, should help to detect bad foreign peer behavior or network configuration issue, stuff like this.
- `Trace` : (can flood) Mainly for development usage.

> The stacktrace ends, where it would be interesting ...

The full stacktrace
```
endpoint=354723090124636, system=406aebe6355d4b23bc19756f7ddd40a7] Could not send the request Request [ticketId=557a74de65bc430fae424c4e136c1053, request=CON-PUT    MID= 2050, Token=E48D32C2D8109D63, OptionSet={"Uri-Path":["cloudInterface","dh","cmd"], "Content-Format":"application/cbor"}, address changed! "x8{"t":2,"i":60926,"r":{".. 58 bytes]
org.eclipse.leshan.core.request.exception.SendFailedException: Unable to send request coap://10.16.3.196:56830/cloudInterface/dh/cmd
 at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onSendError(CoapAsyncRequestObserver.java:167) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.coap.Message.setSendError(Message.java:986) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1123) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1259) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.elements.RawData.onError(RawData.java:303) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.DTLSConnector$1.handshakeFailed(DTLSConnector.java:439) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:1275) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.dtls.Connection.updatePeerAddress(Connection.java:296) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore$3.run(InMemoryConnectionStore.java:584) ~[lwm2mfe.jar:na]
 at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) ~[lwm2mfe.jar:na]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
 at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: java.io.IOException: address changed!
 ... 6 common frames omitted
```

**Comment by boaks** [comment]
> We can do that this could be great to review the log level with this kind of "rules" :

"great" means mainly also "great" work, so I'm not sure. In some cases it's even not easy to decide, which will be the proper level.

**Comment by boaks** [comment]
See PR #1277

**Comment by sbernard31** [comment]
I try to look at the #1277 but before to review it, I would prefer to agree on the log level "role".

Does the description proposed above (https://github.com/eclipse/californium/issues/1276#issuecomment-613313675) sound good to you ?

**Comment by boaks** [comment]
I always find it hard to "agree on such general rules" , because in my experience, there maybe also some "exceptions" :-). For a communication library it may also depend on the origin of the data (that may cause the log message). Incoming may be considered never as warning. 

>     Error : (extremely rare) This MUST NOT happens => there is probably a bug somewhere.

OK, if doesn't end up in discussion, if this error could really occur,

>    Warning : (pretty rare) This SHOULD NOT happens => there is maybe a problem.

OK

>    Info : (very rare) Mainly for information at startup or stop.

Or, if something exceptional on incoming data is reported. 

>    Debug: (should not flood) This should show unexpected behavior, should help to detect bad foreign peer behavior or network configuration issue, stuff like this.

As I wrote above, debug is for me to understand the call-sequence-flow. Bad behaviout of other peers would be info on my opinion. 

>   Trace : (can flood) Mainly for development usage.

OK.

One question left maybe, if it requires different loggers to setup logging based on received data.

**Comment by sbernard31** [comment]
As you said this general rules and of course it could have some exception if there is good reason to do it.

Let's try to agree on general rules ^^.

My needs is to have a level of log that : 
- I can activate/deactivate without any lost of critical/configuration logs (ERROR, WARNING,INFO)
- could show me some unexpected behavior without flooding me.

So I was targeting the DEBUG level and so keep the TRACE level for flooding logs.

It seems to me that you didn't agree with that or did I miss understand ? Reading you I understand that you want do use DEBUG pretty much like TRACE ?

**Comment by boaks** [comment]
For me, DEBUG should show the coarse grained messages in order to understand the call-sequence-flow. That doesn't need to be complete, but should give enough information to reduce the scope of an analysis. Usually it's only enabled during development, so a logging flood would be not something, I would consider in the first.

**Comment by sbernard31** [comment]
But if you do that in development and flooding is not something to consider why not using TRACE level ?
And keep debug to help to debug in production environment ?

**Comment by boaks** [comment]
In my experience, DEBUG in production requires frequently a idea, what to search for, and mostly adaption in the logging for that idea. Just to mention, I don't plan to change some trace to debug, and if you fell, that some debugs should be trace, I have no objection. But I would not review all the logging according the idea, that DEBUG should not flood.

**Comment by sbernard31** [comment]
> But I would not review all the logging according the idea, that DEBUG should not flood.

You mean you don't want to do that ? or you don't want that anybody do that ?

**Comment by boaks** [comment]
**I** don't want to do that.

**Comment by sbernard31** [comment]
Ok I will try to review #1277 with this in mind. :sweat_smile:

**Comment by sbernard31** [comment]
Should we close this now ?

**Comment by sbernard31** [comment]
The WARN level does not flood at all now. (except #1284)

I activated DEBUG log in on several production servers. And now the log flow is lower. This is usable in our case during few minutes.

:thinking: I notice some DEBUG logs which could maybe be lowered, as there don't seem so interesting and still flood a little : 
- All drops about duplicate message.
- Discarding {} record received from peer [{}] without an active session for epoch 

Anyway, I think we can close this one now.
