### ISSUE TITLE
2.2.2 Released

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1281]
The current 2.2.x branch contains new bugfixes for processing "CLOSE_NOTIFY", 
see issue #1273 and PR #1274. The PR #1280 will be also contained. 

Are issues left, which should be contained in a 2.2.2?
If not, should 2.2.2-RC1 be released tomorrow, 16. April 2020?

**Comment by sbernard31** [comment]
AFAIK, No issue left.

Do we really need RC1 for a minor version ?

**Comment by boaks** [comment]
I guess so. But we can also release a 2.2.2, if you prefer.

**Comment by sbernard31** [comment]
The Leshan release was planned for today but I'm still waiting the PMC approval.
I plan to integrate the 2.2.2 release of californium in it, so I would prefer a 2.2.2 directly but it's not a big deal if this is not possible. I'm not so hurry the 15th April is just an approximate date to me. 

In a general way, I'm not sure this is really needed to release RC1 for revision/patch release which  generally just contains fixes on extremely minor changes.

**Comment by boaks** [comment]
OK, so should I start the 2.2.2 release?

**Comment by sbernard31** [comment]
yep :)

**Comment by boaks** [comment]
Bugfix release:

- 56344cb1 Change output level of some logs in DTLSConnector.
- d2525ff7 Add logger for message drops.
- 2703dcbf Fix closing on uncompleted handshakes.
- f7433d62 Add a logging-messages to analyze issue #1273.

**Comment by boaks** [comment]
The 2.2.2 is released!
 
It's available at the [Eclipse Repo](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/) and soon on [Maven Central](https://search.maven.org/search?q=g:org.eclipse.californium%20a:parent%20v:2.2.2).

**Comment by sbernard31** [comment]
Thx :pray:
