### ISSUE TITLE
Android sample project not updated

### ISSUE THREAD

**Issue by pedromassango** [eclipse/californium#1282]
The android project in this repository is too old and it does not run anymore. I though it was created using Eclipse and it is not running on Android Studio. Maybe it need a fresh update to use the latest Android technologies.

**Comment by boaks** [comment]
The last time, I updated it, I used the android studio.
Which version of the android studio do you use?
What error did you get?

**Comment by pedromassango** [comment]
I'm using 3.6.2

**Comment by pedromassango** [comment]
Looks like some dependencies are outdated

**Comment by boaks** [comment]
I will update it until tomorrow.

**Comment by boaks** [comment]
If possible, please checkout PR #1283 and check, if it work for you.

**Comment by pedromassango** [comment]
It works

**Comment by pedromassango** [comment]
One question. Is it possible to add a new example about how to consume a [coaps] server in Android? I'm stuck on that since yesterday.

Or can you at least tell me the step-by-step on how to configure this package with DTLS to consume a server?

Thanks for this amazing package by the anyway.

**Comment by boaks** [comment]
Thanks!

**Comment by boaks** [comment]
> One question. Is it possible to add a new example about how to consume a [coaps] server in Android? I'm stuck on that since yesterday.

Is it about coaps ?
What does "consume a [coaps] server" mean?
Android is the coap-client?
Android is the coap-server?

**Comment by pedromassango** [comment]
Android is the client. I mean I want need to conect to a CoAP server using secure connection (DTLS) using this package but I'm not understanding how to configure this package to send the requests

**Comment by boaks** [comment]
Bascialy, use

coaps://californium.eclipse.org:5684/

as URI.

Details:
For clients it's possible to use the `EndpointManager` to setup a `DTLSConnector`.

[setup DTLS](https://github.com/eclipse/californium/blob/master/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/MainActivity.java#L139)

[DTLS credentials](https://github.com/eclipse/californium/blob/master/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/ConfigureDtls.java#L55)  

With that, just use "coaps" as scheme.

**Comment by pedromassango** [comment]
It is neccessary to point to a `.p12` and keystore file? I do't have my keystore right now as I just want to make tests with my server

**Comment by boaks** [comment]
No, you don't need x509, if you don't use it.
I guess, you use PSK instead. So copy the line [setup PSK store](https://github.com/eclipse/californium/blob/master/demo-apps/cf-android/app/src/main/java/org/eclipse/californium/examples/ConfigureDtls.java#L71) from `ConfigureDtls` to your `initCoapEndpoint` and remove the  `ConfigureDtls.loadCredentials` there.

Just to say: 
such compiled in credentials are good for demos.
For something close to production it's much better to add a activity to manage these credentials and the store them encrypted using something similar as [AndroidKeyStore](https://developer.android.com/training/articles/keystore).

**Comment by pedromassango** [comment]
Thank you for the support

**Comment by boaks** [comment]
You're welcome.

**Comment by boaks** [comment]
The PR is merged on master.
If this issue is solved for you, please close it.
