### ISSUE TITLE
Malformed options are handled according to RFC-7252

### ISSUE THREAD

**Issue by nherasiutsin** [eclipse/californium#1288]
We've encountered an issue that californium throws `IllegalArgumentException` for malformed options without answering to a client, e.g. Uri-Path option exceeds 255 bytes. The same happens with other options in method org.eclipse.californium.core.coap.OptionSet#addOption. The main issue that we can't handle that exception in our code (correct me if I'm wrong).

Stacktrace:
`java.lang.IllegalArgumentException: {} option's length {} must be between {} and {} inclusive!
    at org.eclipse.californium.core.coap.OptionSet.checkOptionValue(OptionSet.java:1598)
    at org.eclipse.californium.core.coap.OptionSet.addUriPath(OptionSet.java:652)
    at org.eclipse.californium.core.coap.OptionSet.addOption(OptionSet.java:1493)
    at org.eclipse.californium.core.network.serialization.DataParser.parseOptionsAndPayload(DataParser.java:165)
    at org.eclipse.californium.core.network.serialization.DataParser.parseMessage(DataParser.java:100)
    at org.eclipse.californium.core.network.serialization.DataParser.parseMessage(DataParser.java:76)
    at org.eclipse.californium.core.network.serialization.DataParser.parseMessage(DataParser.java:55)
    at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:1097)
    at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$2200(CoapEndpoint.java:1063)
    at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:1080)
    at org.eclipse.californium.core.network.CoapEndpoint$11.run(CoapEndpoint.java:1319)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)`

RFC-7252 tells the following:

> 5.4.1. Critical/Elective
Unrecognized options of class "critical" that occur in a Confirmable request MUST cause the return of a 4.02 (Bad Option) response. This response SHOULD include a diagnostic payload describing the unrecognized option(s) (see Section 5.5.2).
Unrecognized options of class "critical" that occur in a Confirmable response, or piggybacked in an Acknowledgement, MUST cause the response to be rejected (Section 4.2).

> 5.4.3. Length
Option values are defined to have a specific length, often in the form of an upper and lower bound. If the length of an option value in a request is outside the defined range, that option MUST be treated like an unrecognized option (see Section 5.4.1).

> 5.9.2.3. 4.02 Bad Option
The request could not be understood by the server due to one or more unrecognized or malformed options. The client SHOULD NOT repeat the request without modification.

According to the RFC, the server should've answered with 4.02 Bad Option.
Our goal is to be fully RFC-7252 compliant, so we want to fix that in any way. Do we miss something or the only way to fix that is to change the californium code?

**Comment by boaks** [comment]
Thanks! Seems to be related to issue #453 (2017).
 I'm not sure, if it's possible to fix that in "custom code", but, I'm sure, that contribution will be welcome. If you're interested, check [CONTRIBUTION](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md). You mainly need a ECA.

**Comment by boaks** [comment]
Just a implementation hint:
If `CoAPMessageFormatException` is extended with then token
`CoapEndpoint.Inbox.receiveMessage()` may be adapted to send an error response instead of a reject.
And in order to reject or response, the `IllegalArgumentException` must be converted in such a  `CoAPMessageFormatException` in the `DataParser.parseOptionsAndPayload`.

**Comment by boaks** [comment]
To be compliant to [5.4.1](https://tools.ietf.org/html/rfc7252#section-5.4.1) may require some more details (from the core-mailing-list):

> Unrecognized options of class "critical" that occur in a
> Confirmable response, or piggybacked in an Acknowledgement, MUST
> cause the response to be rejected (Section 4.2). 

AFAIK, it's not possible the reject an ACK, and a piggybacked response is an ACK.

> Unrecognized options of class "critical" that occur in a
> Confirmable request MUST cause the return of a 4.02 (Bad Option)
> response.  This response SHOULD include a diagnostic payload
> describing the unrecognized option(s) (see Section 5.5.2).

> Unrecognized options of class "critical" that occur in a Non-
> confirmable message MUST cause the message to be rejected
> (Section 4.3).

I'm not sure, why the type of the request (CON/NON) should affect, if a response is sent or the message is rejected.

**Comment by boaks** [comment]
Just in the case you're interested in the answer from the core-mailing-list:

[RFC7252 - 5.4.1 Critical/Elective](https://mailarchive.ietf.org/arch/msg/core/RZNPAVHn1WZNRbp-CyiAILkgdx4/)

**Comment by boaks** [comment]
If you're interested, I prepared two PRs to reduce the difference.

- PR #1296 
- PR #1297

I would appreciate, if you try out the PRs, if the fix your issue.

**Comment by boaks** [comment]
The PRs are merged, If this fixes your issue, please close it.
