### ISSUE TITLE
[question] what "Parsing HANDSHAKE message plaintext with parameter [null]" means?

### ISSUE THREAD

**Issue by pedromassango** [eclipse/californium#1289]
While trying to connect to my server I'm receiving this message in Logs: 

`[DTLS-Connection-Handler-3] Parsing HANDSHAKE message plaintext with parameter [null]`

Want to know what this means to me?

Edit: Then I receive a HandshakeException message:

```
I/o.e.c.s.DTLSConnector: [DTLS-Connection-Handler-4] error occurred while processing record from peer
[/178.79.163.185:5684]org.eclipse.californium.scandium.dtls.HandshakeException: Message SERVER_HELLO (2) fragment length 78 doesn't match data 813
    	at org.eclipse.californium.scandium.dtls.HandshakeMessage.fromByteArray(HandshakeMessage.java:214) ~[na:0.0]
    	at org.eclipse.californium.scandium.dtls.Record.handshakeMessageFromByteArray(Record.java:740) ~[na:0.0]
    	at org.eclipse.californium.scandium.dtls.Record.decodeFragment(Record.java:718) ~[na:0.0]
    	at org.eclipse.californium.scandium.dtls.Record.applySession(Record.java:598) ~[na:0.0]
    	at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1266) ~[na:0.0]
    	at org.eclipse.californium.scandium.DTLSConnector$11.run(DTLSConnector.java:1158) ~[na:0.0]
    	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

**Comment by boaks** [comment]
Do you still use Californium on Android?
And the other peer is also Californium?
Is the error reproducible?
Are you able to capture that handshake with wireshark (please select only the dtls traffic on export the capture)?

**Comment by pedromassango** [comment]
Yes I'm still using Californium on Android. The server is not using Californium. I'm just calling a coaps URL with a self-signed certificate.

I never used wireshark before but I can try it

**Comment by boaks** [comment]
Which server are you using (if you're allowed to tell it :-)?

libcoap ?
ocf go coap?

**Comment by pedromassango** [comment]
> Which server are you using (if you're allowed to tell it :-)?
> 
> libcoap ?
> ocf go coap?

I cant' tell you right now. But I share more updates when possible. Is this a Log message a big problem? What is going wrong?

**Comment by boaks** [comment]
> Is this a Log message a big problem? 

Not for Californium :-).

> What is going wrong?

I assume the other peer send malformed fragmented handshake messages.

**Comment by boaks** [comment]
[Handshake Message Fragmentation and Reassembly](https://tools.ietf.org/html/rfc6347#page-20)

> Note that as with TLS, multiple handshake messages may be placed in
> the same DTLS record, provided that there is room and that they are
> part of the same flight.  Thus, there are two acceptable ways to pack
> two DTLS messages into the same datagram: in the same record or in
> separate records.
 
Is the server using multiple handshake messages within one dtls record?
If so, Californium unfortunately doesn't support that for now. Could you try to configure the server to use multiple dtls records instead?

**Comment by boaks** [comment]
Hi @pedromassango ,

have you been able the adapt the server to send multiple dtls records instead of multiple handshake messages in on dtls record?

Last year, I redesigned the handshake. Adding support for the "1 dtls records, n handshake records" seemed to be a larger change. And I don't know too many servers, which do it in that way. So, if you could adapt the server's mode, I would like to postpone support for that "once more".

**Comment by pedromassango** [comment]
No. I'm currently looking for using normal https for now since this is just a prototype. I will be back into COAPS later

**Comment by boaks** [comment]
Thanks for your feedback!

**Comment by boaks** [comment]
Just in the case, that you're still interested and able to spend time in:

PR #1363 includes now support for dtls records with multiple handshake messages.

**Comment by pedromassango** [comment]
Thank you. This will be useful once we use CoAP in the project.

**Comment by boaks** [comment]
> I think I can close this.

That will be welcome. If you once test it, maybe you can report your results.

**Comment by pedromassango** [comment]
> If you once test it, maybe you can report your results

Of course.
