### ISSUE TITLE
Allow integration with HSM

### ISSUE THREAD

**Issue by JaimieW** [eclipse/californium#1291]
I'm using Californium to write a CoAP and DTLS server implementation.
My problem is that the DTLS PSK Key is stored in a Hardware Security Module.
This means that the key material cannot be extracted and used to create the pre master secret.
It also means that the master secret derivation has to be performed on the HSM itself.

I have a PR containing the changes I needed to make, which are fairly minimal.

**Comment by boaks** [comment]
The extension in general is great.

I would prefer a implementation, which uses a new interface passed in via `DtlsConnectorConfig`. Let me know, if you could consider to change your PR accordingly, or if we should go for now with your implementation.

**Comment by JaimieW** [comment]
I'm looking into changing the code to use an interface passed in via the config.
I should have a commit ready later today.


________________________________

**Comment by boaks** [comment]
Sounds great!

**Comment by boaks** [comment]
It's merged, so can we close this issue?
