### ISSUE TITLE
Prevent to use 2 certificate with same subject truststore ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1307]
It seems there is nothing to prevent to put 2 different certificate with the same ~issuer~ subject in the scandium trust store.

Should we add a check about that ?

**Comment by boaks** [comment]
I'm not sure, if you mean "same subject"?
For issuers I'm not sure, why that should be checked.

**Comment by sbernard31** [comment]
Yep I would mean same subject.

**Comment by boaks** [comment]
I'm not sure about the rules, which applies to x509.

[Multiple Certificates with same DN](https://security.stackexchange.com/questions/174640/multiple-certificates-with-same-dn)

seems to permit that.

**Comment by sbernard31** [comment]
Let's explain my story :)

I was doing some tests of Leshan (using demo). I created several root certificates that I used as truststore at server side.  
And at client side, I was doing some test with several certificate signed by those root certificates.

I faced a situation where handshake failed. After a while I finally discovered this was because I have several root certificates with exactly the same subject and  [search method](https://github.com/eclipse/californium/blob/2.2.2/element-connector/src/main/java/org/eclipse/californium/elements/util/CertPathUtil.java#L344) doesn't  pick the right one.

So my first idea was to avoid to have several certificate with same subject to avoid this behavior.

**Comment by boaks** [comment]
OK, maybe we add a short javadoc to `setTrustStore`, that explains that rule and mention `setCertificateVerifier`,  if that rule should be bypassed?
(by the way, I think, the check order needs to be fixed as well. And:
```
public Builder setTrustStore(Certificate[] trustedCerts) {
	if (trustedCerts == null) {
		throw new NullPointerException("Trust store must not be null");
	} else if (config.certificateVerifier != null) {
		throw new IllegalStateException("Trust store must not be used after certificate verifier is set!");
	} else if (trustedCerts.length == 0) {
		config.trustStore = new X509Certificate[0];
	} else {
		config.trustStore = SslContextUtil.asX509Certificates(trustedCerts);
		checkTrustStore();
	}
	return this;
}
```
)

**Comment by sbernard31** [comment]
> OK, maybe we add a short javadoc to setTrustStore, that explains that rule and mention setCertificateVerifier, if that rule should be bypassed?

We can do that (simple solution) or we check against all certificates (less simple one)

What do you mean by check order ? 

`checkTrustStore()` before `config.trustStore = SslContextUtil.asX509Certificates(trustedCerts);` ?

I did it intentionally because `asX509Certificates` checks null entry and I assumed that the `IllegalArgumentException` will stop the execution and so not a big deal if config.trustore is set.

But after thinking again about this, we should avoid to set config.truststore if validation failed.

**Comment by boaks** [comment]
> What do you mean by check order ?

```
else if (config.certificateVerifier != null) {
	throw new IllegalStateException("Trust store must not be used after certificate verifier is set!");
} else if (trustedCerts.length == 0) {
```

The order of these two checks.

**Comment by boaks** [comment]
> We can do that (simple solution) or we check against all certificates (less simple one)

I don't get it.
My idea, add a javadoc which explains, that the check is done and add that check.
If someone feels, that this check must be bypassed, the setCertificateVerifier should be used.

That helps in the most cases to sort our your kind of issues.
And enables others to do, what they think is worth.

**Comment by sbernard31** [comment]
> or we check against all certificates (less simple one)

I meant another solution could be (maybe) to check against all certificate with the expected Subject value.

e.g. If there is 2 certificates with the expect subject, we check against the first one and if it fails, we try with the other one.

**Comment by sbernard31** [comment]
(Should I cherry pick #1308 in master ?)

**Comment by boaks** [comment]
Yes, please.

**Comment by sbernard31** [comment]
(done commit 3e5bb4d)

**Comment by boaks** [comment]
Just to mention:

PR #1442 will change the behavior
