### ISSUE TITLE
Send COAPClient Request via UDPDatagramPacket

### ISSUE THREAD

**Issue by jigish-shah** [eclipse/californium#1310]
Hello Team

Could you please advise if we can send COAPClient using UDPDatagramPacket ? If yes please share reference

Thanks

**Comment by boaks** [comment]
A coap-client send coap-requests as UDP datagram and receives the responses.
There are simple examples for that e.g. "demo-apps/cf-helloworld-client" and "demo-apps/cf-helloworld-server".  Both demos open a DatagramSocket to send and receive UDP messages. See [UDPConnector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/UDPConnector.java).

**Comment by jigish-shah** [comment]
sure.. let me have a look at it.. Basically I was using below...

`Endpoint clientEndpoint;
		CoapEndpoint.Builder builder = new CoapEndpoint.Builder();
		builder.setInetSocketAddress(new InetSocketAddress("0.0.0.0", 9901));
		clientEndpoint = builder.build();
	    client1.setEndpoint(clientEndpoint);
	    CoapResponse response = client1.get();
	    System.out.println( "Client1 "+response.getResponseText() );
	    System.out.println( "Client1 "+response.advanced().getSourceContext().getPeerAddress().getHostName());
	    System.out.println( "Client1 "+response.advanced().getSourceContext().getPeerAddress().getPort());`

I can see request/response in PCAP but its directly showing protocol as CoAP.

Let me check with UDPConnector

**Comment by boaks** [comment]
If you use wireshark, the middle window will show the protocol stack:


> Frame 17: 84 bytes on wire (672 bits), 84 bytes captured (672 bits) on interface 0
> Ethernet II, Src: AsustekC_79:a3:50 (4c:ed:fb:79:a3:50), Dst: AvmAudio_2b:43:d1 (f0:b0:14:2b:43:d1)
> Internet Protocol Version 4, Src: 192.168.178.45, Dst: 104.196.15.150
> User Datagram Protocol, Src Port: 40765, Dst Port: 5683
>     Source Port: 40765
>     Destination Port: 5683
>     Length: 50
>     Checksum: 0xeb73 [unverified]
>     [Checksum Status: Unverified]
>     [Stream index: 1]
> Constrained Application Protocol, Confirmable, GET, MID:17690
>     01.. .... = Version: 1
>     ..00 .... = Type: Confirmable (0)
>     .... 1000 = Token Length: 8
>     Code: GET (1)
>     Message ID: 17690
>     Token: e8952d9c92c5f878
>     Opt Name: #1: Uri-Host: californium.eclipse.org
>     Opt Name: #2: Uri-Path: test
>     [Response In: 18]
>     [Uri-Path: coap://californium.eclipse.org/test]
> 

It shows also the detail for User Datagram Protocol, if you unfold them.

**Comment by jigish-shah** [comment]
@boaks : not sure if UDPConnector can do something like below. here i'm assuming if there is any possibility to replace packet with actual coap request.

`					rawBytes = packet.getBytes();
					DatagramPacket sendDatagramPacket = new DatagramPacket(rawBytes , rawBytes.length , InetAddress.getByName(clientIP) , clientPort);`


Thanks!

**Comment by boaks** [comment]
The `CoapEndpoint` uses the `DataSerializer` to convert a Request (or an other CoAP message) into the its bytes representation, which is then handover to the connector to send these bytes as UDP packet.

I'm not sure, If I get your questions. It seems, that you want to do something, which Californium already does. Though the demos should demonstrate that, I'm still not sure, what you miss.

**Comment by jigish-shah** [comment]
Yes. I think UDPConnector will work here!

Many thanks @boaks
