### ISSUE TITLE
Blockwise Transfer

### ISSUE THREAD

**Issue by devannair777** [eclipse/californium#1311]
Hello ,
I am new to Californium using Californium v 2.2.2 and can I get some advice on implementation of block transfer. I have a Coap Server which is trying to send a resource representation that is about 7 kB. When I use a libcoap based client (coap-client) The server sends the entire resource via blockwise transfer over 7 blocks as I have set my PREFERRED_BLOCK_SIZE=1024...I tried to write a Californium based implementation using CoapClient class and I get only one message block ...The client does not respond to M=true with end of block message for a multicast GET (as I assume it normally does for unicast requests) .What is transparent block transfer as I have seen mentioned in the community and how can I check if Block Transfer layer is working or not for a multicast request...If possible could you provide a sample code using CoapClient ? as I assume my mistake is in the client side implementation...

This is the sample Client application I wrote
CoapEndpoint.Builder builder = new CoapEndpoint.Builder();
        NetworkConfig config = NetworkConfig.getStandard();
        CoapEndpoint ep = builder
                .setInetSocketAddress(new InetSocketAddress(portNum))
                .setNetworkConfig(config)
                .build();
        CoapClient coapClient = new CoapClient();
        coapClient.setEndpoint(ep);
        coapClient.useNONs();
        String uri = scheme+mGroups+coapPort+"/test";
        LOGGER.info("URI that is set :"+uri);
        coapClient.setURI(uri);

       coapClient.get(new ServerResponseHandler())

public class ServerResponseHandler implements CoapHandler {
...///Interface method Implementations
}

Thank you

**Comment by devannair777** [comment]
I am sorry I forgot to mention above It is a multicast request...

**Comment by boaks** [comment]
Unicast - blockwise:

Your observation, that the client gets only one large response is intended. You may use wireshark or [MessageTracer](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/interceptors/MessageTracer.java) to see the single blocks.

Multicast - blockwise:

That is [currently disabled](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java#L625). If it get enables, you probable risk to get much more traffic than expected. My idea here is just to report the first bock, and leave it to the client to download the follow-up blocks (even if that "follow-up" is currently also not implemented, so just GET the complete response, repeating the first block).

Multicast - blockwise - observer:

Same as multicast-blockwise.

**Comment by devannair777** [comment]
Ok Thank You for the response , I tested with unicast and thought that my multicast implementation had some mistake . Closing the issue as Multicast blockwise is disabled by default
