### ISSUE TITLE
Better Error Handling on response handling failure

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1317]
On `MessageObserver` there is a `onSendError(Throwable error)` callback to be aware if error occurred on sent.

But there is nothing if an error occurred on response.
Example: in `BlockwiseLayer` when request is cancelled because of max body size exceeded : 
```java
if (responseExceedsMaxBodySize(response)) {
    LOGGER.debug("requested resource body exceeds max buffer size [{}], aborting request", maxResourceBodySize);
    exchange.getRequest().cancel();
}
```
Here the request will be cancelled and the application layer will just be aware that the request is cancelled without any information about why ?

Maybe a kind of   `onReceiveError(Throwable error)` callback should be added.

**Comment by boaks** [comment]
Introducing new methods in interfaces is according revapi not that easy.
Currently the `MessageObserver` is already extended by the `InternalMessageObserver`.
That new method would require an additional interface. If we could postpone it for 3.0, it would be easier.

**Comment by sbernard31** [comment]
Generally this could be achieved in a minor version by creating a new interface which extends the previous one and just do an `instanceof` where the new methods is called.

**Comment by sbernard31** [comment]
it sounds not so impacting.

**Comment by boaks** [comment]
I don't get it.

1. you proposal about a new interface seems to be the same as my additional interface (InternalMessageObserver is already one).

2. I asked to postpone it, because in my opinion the cleanup required for 3.0 will already cost some more time.

**Comment by sbernard31** [comment]
I just say I prefer to have it in a minor release.

**Comment by boaks** [comment]
OK. Do you like to add it on your own?
I would appreciate, if you use the 

```
@PublicAPIExtension(type = MessageObserver.class)
```

annotation. I hope it will be faster to list such extensions when merging them into the main interface for 3.0 .

**Comment by sbernard31** [comment]
Another solution is  just to make the new interface inherit the old one.

This way :
- this is easy to retrieve all interface for maintainer or user just with a type hierarchy on the root class in your IDE.
- not need to introduce a new annotation.

**Comment by sbernard31** [comment]
If I implement it I will use your annotation.

**Comment by boaks** [comment]
> not need to introduce a new annotation.

My intention of the annotation was only to search faster for stuff to cleanup for 3.0.
It has no other function.

**Comment by sbernard31** [comment]
I understand, I just let you know that making the new interface extends the old one do this job too.
maybe you don't know and maybe you will find this is better so I just let you know

**Comment by sbernard31** [comment]
(eventually this avoid to user to implements 2 extensions)

**Comment by boaks** [comment]
I assumed, that for a 3.0 a cleanup would merge all these extension interfaces into the main. I would not keep them separate.

**Comment by sbernard31** [comment]
I agree with this.
