### ISSUE TITLE
ObservationUtil.shallowClone() exception

### ISSUE THREAD

**Issue by gaomingok** [eclipse/californium#1321]
https://github.com/eclipse/californium/blob/97a4d50e7e3cbdc11837cea963830fc862ba6a46/californium-core/src/main/java/org/eclipse/californium/core/observe/ObservationUtil.java#L49
**clonedRequest.setPayload(request.getPayload());**
If request.isUnintendedPayload ()==true && request.getCode()==GET, this line will throw an exception, causing an observe exception.

**Comment by boaks** [comment]
Please check, if PR #1322 would fix this bug.

GET with payload is considered to be not compliant. Maybe you consider to use FETCH.
[FETCH, PATCH, IPATCH](https://tools.ietf.org/html/rfc8132)

**Comment by boaks** [comment]
PR #1322 is merged. 
If that fixes this issue, please close it.
