### ISSUE TITLE
MulticastServer not responding to requests

### ISSUE THREAD

**Issue by devannair777** [eclipse/californium#1328]
Hello,
I am using californium-core and californium-elements v2.2.3 and I tried to set up a simple Multicast Server on a host with two interfaces.I tried the procedure as mentioned in #895 . I am attaching the code and the startup logs of the server. 
It is an Ubuntu host.
The issue :
1)When I try to send a GET request to the multicast address , I do not get a reponse, However if I send a request to the unicast interface address, I get appropriate response.
2)If I do an ip maddr show on the host, it shows the respective interface successfully registered to the multicast group.
If I made any mistake could you suggest the correction or any possible workaround to have  multicast servers on 2 interfaces as the following code intends to

       public class MCastTest
     {
        public static void main(String[] args) {

        CoapServer coapServer1 = new CoapServer();
        CoapServer coapServer2 = new CoapServer();

        TestResource r1 = new TestResource("test");
        TestResource r2 = new TestResource("test");

        String ipAddress = "192.168.15.1";
        String ipAddress2 = "192.168.16.1";
        String mAddr1= "239.0.10.15";
        String mAddr2 ="239.0.10.16";

        NetworkConfig config = NetworkConfig.getStandard();
        int port = 5683;
        InetSocketAddress socket1 = new InetSocketAddress(ipAddress,port);
        InetSocketAddress socket2 = new InetSocketAddress(ipAddress2,port);

        InetAddress mCastAddr1 = (new InetSocketAddress(mAddr1, 0)).getAddress();
        InetAddress mCastAddr2 = (new InetSocketAddress(mAddr2, 0)).getAddress();
        UdpMulticastConnector connector1 = new UdpMulticastConnector(socket1.getAddress(),socket1,mCastAddr1);
        UdpMulticastConnector connector2 = new UdpMulticastConnector(socket2.getAddress(),socket2,mCastAddr2);

        CoapEndpoint ep1 = new CoapEndpoint.Builder().setNetworkConfig(config)
                                .setConnector(connector1).build();
        CoapEndpoint ep2 = new CoapEndpoint.Builder().setNetworkConfig(config)
                                .setConnector(connector2).build();

        coapServer1.addEndpoint(ep1);
        coapServer2.addEndpoint(ep2);

        coapServer1.add(r1);
        coapServer2.add(r2);

        coapServer1.start();
        coapServer2.start();

    }
    private static class TestResource extends CoapResource
    {

        public TestResource(String name) {
            super(name);
        }

        @Override
        public void handleGET(CoapExchange exchange) {
            //super.handleGET(exchange);
            System.out.println("Inside GET Handler");
            exchange.respond(CoAP.ResponseCode.CONTENT,"Hello !!");
        }
    }

}`

![mCast](https://user-images.githubusercontent.com/44372574/82470722-fc477e00-9ac5-11ea-95f3-c6fd4151d895.jpg)

![mCast2](https://user-images.githubusercontent.com/44372574/82472102-eaff7100-9ac7-11ea-94ea-14ff508cd088.jpg)

(I hit Ctrl+C after timeout)

**Comment by boaks** [comment]
The rules to setup multicast sockets with java seems to be OS dependent and not too clear :-).

First, please use "master", we are on the way to release that as 2.3.0 and I used it to verify the setup.

```
UdpMulticastConnector(InetAddress intfAddress, InetSocketAddress localAddress,
			InetAddress... multicastGroups) 
```

On linux it seems, that the "localAdress" is used to filter the traffic. if you want to receive all requests for unicast and multicast, use the "any" address.

```
InetSocketAddress socket1 = new InetSocketAddress(port);
InetSocketAddress socket2 = new InetSocketAddress(port);  
```

with that it works "on my machine".

Some additional hints:
A californium CoapServer can have multiple endpoints.
So using one CoapServer, one TestResource, and two Endpoints works as well.

**Comment by boaks** [comment]
Please, first check the simple setup above, before try out this sophisticated one:

If you want to distinguish between unicast and multicast traffic, use the multicast address also for the multicast socket.

```
InetSocketAddress socket1 = new InetSocketAddress(mcast1, port);
InetSocketAddress socket2 = new InetSocketAddress(mcast2, port);  
```
 
Also create standard `Endpoint`s using the `UDPConnector` and the unicast socket addresses. 

```
InetSocketAddress uniSocket1 = new InetSocketAddress(ipAddress, port);
InetSocketAddress uniSocket2 = new InetSocketAddress(ipAddress2, port);  
```

Add the multicast receiver using

`((MulticastReceivers) coapEndpoint).addMulticastReceiver(connector);`

and then, add the unicast `Endpoint`s with `CoapServer.add(Endpoint)`.  
 
Good luck, multicast seems to be sometimes a beast :-).

**Comment by boaks** [comment]
> 20:08:14.010 INFO [NetworkConfig]: loading properties from file /home/achim/repos/californium/demo-apps/cf-helloworld-server/Californium.properties
> 20:08:14.025 INFO [RandomTokenGenerator]: using tokens of 8 bytes in length
> 20:08:14.034 INFO [CoapEndpoint]: coap CoapEndpoint uses udp plain
> 20:08:14.039 INFO [BlockwiseLayer]: BlockwiseLayer uses MAX_MESSAGE_SIZE=1024, PREFERRED_BLOCK_SIZE=512, BLOCKWISE_STATUS_LIFETIME=300000, MAX_RESOURCE_BODY_SIZE=8192, BLOCKWISE_STRICT_BLOCK2_OPTION=false
> 20:08:14.041 INFO [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=2000, ACK_RANDOM_FACTOR=1.5, and ACK_TIMEOUT_SCALE=2.0 as default
> 20:08:14.042 INFO [RandomTokenGenerator]: using tokens of 8 bytes in length
> 20:08:14.042 INFO [CoapEndpoint]: coap CoapEndpoint uses udp plain
> 20:08:14.043 INFO [BlockwiseLayer]: BlockwiseLayer uses MAX_MESSAGE_SIZE=1024, PREFERRED_BLOCK_SIZE=512, BLOCKWISE_STATUS_LIFETIME=300000, MAX_RESOURCE_BODY_SIZE=8192, BLOCKWISE_STRICT_BLOCK2_OPTION=false
> 20:08:14.043 INFO [ReliabilityLayer]: ReliabilityLayer uses ACK_TIMEOUT=2000, ACK_RANDOM_FACTOR=1.5, and ACK_TIMEOUT_SCALE=2.0 as default
> 20:08:14.043 INFO [CoapServer]: Starting server
> 20:08:14.049 INFO [UdpMulticastConnector]: socket 0.0.0.0:5683, loopback mode false
> 20:08:14.049 INFO [UdpMulticastConnector]: joined group 239.0.10.15
> 20:08:14.049 INFO [UDPConnector]: UDPConnector starts up 1 sender threads and 1 receiver threads
> 20:08:14.051 INFO [UDPConnector]: UDPConnector listening on 0.0.0.0/0.0.0.0:5683, recv buf = 106496, send buf = 106496, recv packet size = 2048
> 20:08:14.051 DEBUG [UDPConnector]: Starting network stage thread [UDP-Receiver-0.0.0.0/0.0.0.0:5683[0]]
> 20:08:14.051 DEBUG [UDPConnector]: Starting network stage thread [UDP-Sender-0.0.0.0/0.0.0.0:5683[0]]
> 20:08:14.051 INFO [CoapEndpoint]: coap Started endpoint at coap://239.0.10.15:5683
> 20:08:14.051 INFO [CoapServer]: Starting server
> 20:08:14.052 INFO [UdpMulticastConnector]: socket 0.0.0.0:5683, loopback mode false
> 20:08:14.052 INFO [UdpMulticastConnector]: joined group 239.0.10.16
> 20:08:14.052 INFO [UDPConnector]: UDPConnector starts up 1 sender threads and 1 receiver threads
> 20:08:14.052 INFO [UDPConnector]: UDPConnector listening on 0.0.0.0/0.0.0.0:5683, recv buf = 106496, send buf = 106496, recv packet size = 2048
> 20:08:14.052 INFO [CoapEndpoint]: coap Started endpoint at coap://239.0.10.16:5683
> 20:08:14.052 DEBUG [UDPConnector]: Starting network stage thread [UDP-Sender-0.0.0.0/0.0.0.0:5683[0]]
> 20:08:14.052 DEBUG [UDPConnector]: Starting network stage thread [UDP-Receiver-0.0.0.0/0.0.0.0:5683[0]]
> 20:08:19.673 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.16:5683) received 9 bytes from /192.168.178.45:42346
> Inside GET Handler
> 20:08:19.701 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:42346
> 20:08:22.545 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.15:5683) received 9 bytes from /192.168.178.45:40115
> Inside GET Handler
> 20:08:22.547 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:40115
> 

My logs. local interfaces on the used machine are `192.168.178.45` and `192.168.122.1`.

**Comment by devannair777** [comment]
I have two doubts regarding your implementation 
1)From the logs is it true that both multicast groups are registering to the same default interface , in your case it seems at 192.168.178.45 ? (I could be misinterpreting the logs as well !)

If so then thats not the scenario I desire ... I want for example
192.168.178.45 -> Multicast group 239.0.10.15
192.168.122.1 -> Multicast group 239.0.10.16

20:08:14.043 INFO [CoapServer]: Starting server
20:08:14.049 INFO [UdpMulticastConnector]: socket 0.0.0.0:5683, loopback mode false
20:08:14.049 INFO [UdpMulticastConnector]: joined group 239.0.10.15

20:08:14.052 INFO [UDPConnector]: UDPConnector listening on 0.0.0.0/0.0.0.0:5683, recv buf = 106496, send buf = 106496, recv packet size = 2048
20:08:14.052 INFO [CoapEndpoint]: coap Started endpoint at coap://239.0.10.16:5683

And 
2)Is MulticastReceivers currently available only on master branch (2.3.0 Release)? If so then it will take some time for me to test it out as I was working with v2.2.3 for most of other stuff and I had other projects to deal with over next few days . I will let you know as soon as I can about the results ..

And also the problem I felt was :
UdpMulticastConnector(InetAddress intfAddress, InetSocketAddress localAddress,
			InetAddress... multicastGroups)  
this particular solution does not seem to be working for me as I cannot get server responding to multicast requests with this constructor ,
but it works with
UdpMulticastConnector(InetSocketAddress localAddress,
			InetAddress... multicastGroups)  
However then I lose control over which  interface joins a particular multicast group.

I will try master branch solution first and I will let you know  

Thank you for such a detailed response so soon !! Much appreciated  :-)

**Comment by boaks** [comment]
If I use different responses "Hello 1!" and "Hello 2!", at last on my machine it seems to work.

> $ coap-client -N -m get coap://239.0.10.15/test
> Hallo 1!
> $ coap-client -N -m get coap://239.0.10.15/test
> Hallo 1!
> $ coap-client -N -m get coap://239.0.10.16/test
> Hallo 2!
> $ coap-client -N -m get coap://239.0.10.16/test
> Hallo 2!

> 22:32:31.167 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.15:5683) received 9 bytes from /192.168.178.45:35713
> Inside GET Handler Hallo 1!
> 22:32:31.169 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:35713
> 22:33:37.852 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.15:5683) received 9 bytes from /192.168.178.45:48487
> Inside GET Handler Hallo 1!
> 22:33:37.854 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:48487
> 22:33:40.591 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.16:5683) received 9 bytes from /192.168.178.45:54593
> Inside GET Handler Hallo 2!
> 22:33:40.593 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:54593
> 22:33:44.936 DEBUG [UDPConnector]: UDPConnector (mc/239.0.10.16:5683) received 9 bytes from /192.168.178.45:60866
> Inside GET Handler Hallo 2!
> 22:33:44.938 DEBUG [UDPConnector]: UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 14 bytes to /192.168.178.45:60866

**Comment by boaks** [comment]
```
public class MulticastTestServer2 {

	public static void main(String[] args) {

		CoapServer coapServer1 = new CoapServer();
		CoapServer coapServer2 = new CoapServer();

		TestResource r1 = new TestResource("test", "Hallo 1!");
		TestResource r2 = new TestResource("test", "Hallo 2!");

		String ipAddress = "192.168.178.45";
		String ipAddress2 = "192.168.122.1";
		String mAddr1 = "239.0.10.15";
		String mAddr2 = "239.0.10.16";

		NetworkConfig config = NetworkConfig.getStandard();
		int port = 5683;
		InetSocketAddress socket1 = new InetSocketAddress(port);
		InetSocketAddress socket2 = new InetSocketAddress(port);

		InetAddress intf1 = new InetSocketAddress(ipAddress, 0).getAddress();
		InetAddress intf2 = new InetSocketAddress(ipAddress2, 0).getAddress();

		InetAddress mCastAddr1 = (new InetSocketAddress(mAddr1, 0)).getAddress();
		InetAddress mCastAddr2 = (new InetSocketAddress(mAddr2, 0)).getAddress();
		UdpMulticastConnector connector1 = new UdpMulticastConnector(socket1.getAddress(), socket1, mCastAddr1);
		UdpMulticastConnector connector2 = new UdpMulticastConnector(socket2.getAddress(), socket2, mCastAddr2);

		CoapEndpoint ep1 = new CoapEndpoint.Builder().setNetworkConfig(config).setConnector(connector1).build();
		CoapEndpoint ep2 = new CoapEndpoint.Builder().setNetworkConfig(config).setConnector(connector2).build();

		coapServer1.addEndpoint(ep1);
		coapServer2.addEndpoint(ep2);

		coapServer1.add(r1);
		coapServer2.add(r2);

		coapServer1.start();
		coapServer2.start();
	}

	private static class TestResource extends CoapResource {
		private String message;

		public TestResource(String name, String message) {
			super(name);
			this.message = message;
		}

		@Override
		public void handleGET(CoapExchange exchange) {
			// super.handleGET(exchange);
			System.out.println("Inside GET Handler " + message);
			exchange.respond(CoAP.ResponseCode.CONTENT, message);
		}
	}
}

```

**Comment by boaks** [comment]
Anyway, Californium uses only the multicast functionality java offers on your OS.
You may try to setup your unicast and multicast sockets in plan java without californium. If that works according your intention, then it should be possible to adapt californium accordingly.

**Comment by devannair777** [comment]
Firstly I really appreciate the effort you took  to test it out quickly ,generally people refrain from engaging multicast problems as much of problems are caused because of the kernel limitations!!

2)I also was considering this , since it will give me some room to experiment wrt the scenario I have for my system.
Anyway, Californium uses only the multicast functionality java offers on your OS.
You may try to setup your unicast and multicast sockets in plan java without californium. If that works according your intention, then it should be possible to adapt californium accordingly.

The existing californium solution possibly seems inadequate for my purpose , so I will probably take the above suggestion to deal with the problem.
I will close this for now , I may reopen it if I am unable to find a workaround .Hope thats Ok with you !!

**Comment by boaks** [comment]
Any update on this?
Did you succeed to process the traffic on your OS/java in the way you want?
Or doesn't java offer that on your OS and so the limits the possible use-cases?
Is there something to change in Californium's multicast setup and/or connector?

**Comment by devannair777** [comment]
Hi,
I extended Cf's MulticastConnector to include one modification

socket.join(NetworkInterface ni,InetSocketAddress Multicast_Address)

It worked after that, I was using Cf 2.2.3 at that time, so I did not check with the later release, if this change is incorporated

**Comment by boaks** [comment]
Thanks!
I prepared PR #1358 to added support to provide a network interface for joining.

**Comment by devannair777** [comment]
Thank You,
Multicast servers should work properly after that fix for all OS 'es now I guess.
