### ISSUE TITLE
broadcast in 1.0.7 version can not get response

### ISSUE THREAD

**Issue by jiangyoudi** [eclipse/californium#1329]
HI ,i have a question in 1.0.7 version.when i use the url of  "coap://192.168.1.1:5683/searchgw",I can get correct result,but when use   coap://192.168.1.255:5683/searchgw,I can not get correct response. 

CoapClient client = new CoapClient("coap://192.168.1.1:5683/searchgw");
String data = "{"key":"value"}";
CoapResponse response = client.post(data, MediaTypeRegistry.APPLICATION_JSON);
System.out.println("result:" + response.getResponseText());

How could I do to deal this?

**Comment by boaks** [comment]
First at all:

The current release is 2.2.3 and 2.3.0-RC will be released this week.
Is there a good reason to stick to use 1.0.7?

Currently Californium 2.x.y handles only multicast addresses proper, broadcast addresses are not recognized and so are processed using [RFC7252, 5.3.  Request/Response Matching](https://tools.ietf.org/html/rfc7252#section-5.3) instead of
[RFC7252, 8.  Multicast CoAP](https://tools.ietf.org/html/rfc7252#section-8).

I did a short check, how a "broadcast-address" could be detected in java, but for me it seems to be not something easy as `InetAddress.isMulticastAddress()`. Such a test would be required to fix it.

**Comment by jiangyoudi** [comment]
thanks，I just use coap discover function to find a sever existing and simple communicating，I can use  2.2.3 or 2.3.0-RC as your advises。broadcast-address can be count by user，such as android OS，when it network is ok ,it will get broadcast-address。I find libcoap （C library）use 192.168.1.255 can get response。

**Comment by jiangyoudi** [comment]
client.setURI("coap://" + CoAP.MULTICAST_IPV4.getHostAddress() + "/searchgw");
		Request multicastRequest = Request.newPost();
		multicastRequest.setPayload(data);
		multicastRequest.setType(Type.NON);
		client.advanced(handler, multicastRequest);
		while (handler.waitOn(2000)) ;
		client.shutdown();
I use this with 2.0.0-M18 client demo also can not get response .my server run in a router with 2.0.0-M3,server version can not change now.

**Comment by boaks** [comment]
As far as I tested it, it is the coap-client, which applies the standard request-response matching (token + endpoint addresses) and not the multi request-response matching (token only).
To switch the client to match according the multi request-response, the InetAddress must be checked, if the targets to many peers or one peer. Currently this is implemented just by `InetAddress.isMulticastAddress()`, which doesn't detect broadcast addresses.
 
> I use this with 2.0.0-M18 client demo also can not get response .my server run in a router with 2.0.0-M3,server version can not change now.

Are you able to change the client version? If so, why do you use 2.0.0-M18 instead of 2.2.3? (For time reasons, I will only be able to prepare a bugfix for the upcoming 2.3.0 or a later version.)

**Comment by boaks** [comment]
Just to mention:
In difference to "broadcast", "multicast" requires to setup the server to join the multicast group. That is not implemented in 2.0.0-M3 and maybe the reason, why multicast doesn't work with a 2.0.0-M3 router. The broadcast may work without special server setup, but I will be only able to test it with the current 2.3.0-SNAPSHOT.

**Comment by jiangyoudi** [comment]
Yes, I can change the client version. I test 2.3.2 version with follow code:

 CoapClient client = new CoapClient("coap://192.168.1.255:5683/searchgw");
 String data = "{"key":"value"}";
 CoapResponse response = client.post(data, MediaTypeRegistry.APPLICATION_JSON);
 System.out.println("result:" + response.getResponseText());

Still ,I can not get response.   I use MulticastAddress coap://224.0.1.187:5683/searchgw , also can not get response.

**Comment by jiangyoudi** [comment]
I use MulticastAddress coap://224.0.1.187:5683/searchgw , also can not get response. this maybe my server problem,server not set suitable(I use client demo and server demo with 2.3.2 is ok).but server version can not change,so I want get a right result  just use the up simple code.

**Comment by boaks** [comment]
As I tried to explain:
To use multicast, your server must have joined that multicast-address.
2.0.0-M3 is 3 years old!
The `UdpMulticastConnector` was introduced 1 and a half year ago.
So, I guess 2.0.0-M3 is not able to receive multicast requests.

Hope, the 2.0.0-M3 server will be able to receive a broadcast request. Though you wrote, it worked with libcoap, I guess, it will work with Californium, if the broadcast address is detected as multi peers address. Please checkout PR #1330, if that fixes your issue.

**Comment by boaks** [comment]
To test requests to multiple peers, please use `CoapClient.useNONs()`. if your interested in more than the first response, see the `MulticastTestClient` and just use your broadcast address (e.g. x.y.z.255) as destination. With the fix in PR #1330 the broadcast destination is detected and the request and response should be processed according [RFC7252, 8.  Multicast CoAP](https://tools.ietf.org/html/rfc7252#section-8).

**Comment by jiangyoudi** [comment]
> As I tried to explain:
> To use multicast, your server must have joined that multicast-address.
> 2.0.0-M3 is 3 years old!
> The `UdpMulticastConnector` was introduced 1 and a half year ago.
> So, I guess 2.0.0-M3 is not able to receive multicast requests.
> 
> Hope, the 2.0.0-M3 server will be able to receive a broadcast request. Though you wrote, it worked with libcoap, I guess, it will work with Californium, if the broadcast address is detected as multi peers address. Please checkout PR #1330, if that fixes your issue.


HI, I clone the code from "bosch-io:support_broadcast" and use CoapClient.useNONs() ,broadcast address (e.g. x.y.z.255) as destination ,but i not works well.

**Comment by boaks** [comment]
And you used the server, which libcoap could successfully post the request to?
Could you please set the logging level to DEBUG on the client and post the log?
If possible, please also post your minimal client code to reproduce the issue.

**Comment by jiangyoudi** [comment]
> And you used the server, which libcoap could successfully post the request to?
> Could you please set the logging level to DEBUG on the client and post the log?
> If possible, please also post your minimal client code to reproduce the issue.

Sorry, I try again, It's amazing it works.thank you for your patient explain. Have a good day!

**Comment by boaks** [comment]
Great!

**Comment by boaks** [comment]
Just to mention:
Communication to multi-peers should be done in NON mode (CON would not work). With that, messages are not retransmitted by the coap-stack. If the request times out without response, you may send a second and third request.

**Comment by jiangyoudi** [comment]
> Just to mention:
> Communication to multi-peers should be done in NON mode (CON would not work). With that, messages are not retransmitted by the coap-stack. If the request times out without response, you may send a second and third request.

thanks your mention,i have got it.

**Comment by jiangyoudi** [comment]
> Just to mention:
> Communication to multi-peers should be done in NON mode (CON would not work). With that, messages are not retransmitted by the coap-stack. If the request times out without response, you may send a second and third request.

ok,thanks your mention,i have got it.

**Comment by jiangyoudi** [comment]
HI,I find another question in 2.3.0-RC1.when I use a client only,it is ok .but when i start a server and a client in one project,the clent can not get response.

192.168.1.1 has a server,192.168.1.2 has a server and client,I use 192.168.1.2 to request 192.168.1.1 by broadcast.
The wireshark package：
![image](https://user-images.githubusercontent.com/27320848/83367377-d2a42600-a3e6-11ea-82ef-e42a65ea5340.png)

**Comment by boaks** [comment]
> when i start a server and a client in one project,the clent can not get response.

Is it the same server implementation?

If you select the 4 messages in wireshark, export the selected messages into a capture, and zip that, you can upload that by drag and drop into a comment. Please, check, that only the 4 selected messages are in the exported captuer by open that capture before you upload it.

Especially the server's connector get's easily setup in a way, which may be "wrong" for a intended scenario. But that's related to the OS and java, Californium is only able to process data, which is received by the java `DatagramSocket` (or `MulticastSocket`) on your OS. So, the first thing to analyze would be, if the the Californium Connector receives the data at all. Therefor, please enable the Californium logging on the server side (adapt the logback.xml), and check, if data is received. If not, please use "plain java" `DatagramSocket`and/or `MulticastSocket` and check, how you need to set them up to receive the data in your scenario. If such a "plain java" scenario works, wee will see, if Californium works as well or requires some adaption.

**Comment by jiangyoudi** [comment]
HI, I try again, 192.168.1.1 has a server with special resouce(/qlink/searchgw), 192.168.1.7 has a server with no special resource(/qlink/searchgw), I use a client in 192.168.1.2 to request by broadcast 192.168.1.255. sometime I can get response,but sometime I can not get response. I think ,the client can only handle the first response, if it reveive 4.04 first by 192.168.1.7, it will not analysis other response.In this case, If I start a server and client in same OS, probable probability I can not get right response。

      In test1.pcapng，the first broadcast ，I can get right result, the second broadcast ,I can not get.  (192.168.1.1 and 192.168.1.7.txt and 192.168.1.7.txt) are client logs.I do not know why client log sometime get 192.168.1.1 and 192.168.1.7 resoponse,but sometime only get 192.168.1.7 or 192.168.1.1.


[result.zip](https://github.com/eclipse/californium/files/4715719/result.zip)

**Comment by jiangyoudi** [comment]
HI, I try again, 192.168.1.1 has a server with special resouce(/qlink/searchgw), 192.168.1.7 has a server with no special resource(/qlink/searchgw), I use a client in 192.168.1.2 to request by broadcast 192.168.1.255. sometime I can get response,but sometime I can not get response. I think ,the client can only handle the first response, if it reveive 4.04 first by 192.168.1.7, it will not analysis other response.In this case, If I start a server and client in same OS, probable probability I can not get right response。

  In test1.pcapng，the first broadcast ，I can get right result, the second broadcast ,I can not get.  (192.168.1.1 and 192.168.1.7.txt and 192.168.1.7.txt) are client logs.I do not know why client log sometime get 192.168.1.1 and 192.168.1.7 resoponse,but sometime only get 192.168.1.7 or 192.168.1.1.


[result.zip](https://github.com/eclipse/californium/files/4715888/result.zip)

**Comment by jiangyoudi** [comment]
I guess, whether it can filter 4.04 respone by other server and clinet itselt response.
Other than that，I have a requirement, I want to get all correct respone by all response servers, is it can do?

**Comment by boaks** [comment]
OK, so at least data is received. (Even if I'm mixed up, what you really do and what your logs are showing :-) ).

Starting with "the clent can not get response." and ending with "4.04" response seems to be a different scenario, which requires other logs and information.
Which client are you using? How do you send the request and how do you get/read the related responses?
Please enable the logging on the client general to "TRACE". Especially the logs of the case, where the 4.04 harms, will be important.

**Comment by jiangyoudi** [comment]
Client use 2.3.0-RC1 with follow code:

public class SearchGw {
    public static void main(String[] arg) throws ConnectorException, IOException {
        CoapClient client = new CoapClient("coap://192.168.1.255:5683/qlink/searchgw");
        String data = "{\n" +
                "\t\"searchKey\": \"ANDLINK-DEVICE\",\n" +
                "\t\"andlinkVersion\": \"V2\"\n" +
                "}";
        client.useNONs();
        CoapResponse response = client.post(data, MediaTypeRegistry.APPLICATION_JSON);
        System.out.println("result:" + response.getResponseText());
    }
}

![image](https://user-images.githubusercontent.com/27320848/83502521-4bdd6f00-a4f4-11ea-9230-050120b18c06.png)

client logs and wireshark package:
[result2.zip](https://github.com/eclipse/californium/files/4716069/result2.zip)

**Comment by boaks** [comment]
> CoapResponse response = client.post(data, MediaTypeRegistry.APPLICATION_JSON);

That would report one response for one request, or?

I already mentioned [some days ago above](https://github.com/eclipse/californium/issues/1329#issuecomment-633445244)

> If your interested in more than the first response, see the MulticastTestClient and just use your broadcast address (e.g. x.y.z.255) as destination

So, did you check the [MulticastTestClient](https://github.com/eclipse/californium/blob/master/demo-apps/cf-helloworld-client/src/main/java/org/eclipse/californium/examples/MulticastTestClient.java#L130)? Using a `CoapHandler` provides you a callback, which is called once per response. If more than one response is expected, that's the way to go. You may also just use something as:

```
client.post(new CoapHandler() {
 ... do something in onLoad and onError ...
 }, data, MediaTypeRegistry.APPLICATION_JSON);
```

**Comment by boaks** [comment]
Have you been able to check, if such a `CoapHandler` receives the multiple responses of your scenario? If so, can we close this issue again?

**Comment by jiangyoudi** [comment]
Yes,I try again as your suggestion,it works.thanks.Have a good day!
