### ISSUE TITLE
UDPConnector wrong datagram port on receiver

### ISSUE THREAD

**Issue by oz117** [eclipse/californium#1353]
Hi all,
We are using leshan demo server at work for testing. And we seem to have it an issue with `UDPConnector`. So whenever we send a request to one of our device the `UDPConnector$Receiver` seems to think that the response was received on port **1024**.
This is impossible given that our client receives and sends data on port **5683**.

When we have a look at what happens with wireshark it indiquates that the `src_port` and `dest_port` are **5683**.
So I do not understand how `UDPConnector$Receiver` can think that the client sent the packet from port **1024**.
Do you have any idea of what is happening ?

For more information, we are using leshan server demo **1.0.1** which uses californium **2.2.3**; the server is running inside kubernetes. 
Some wireshark captures:
```
Capturing on 'eth0'
Frame 1: 63 bytes on wire (504 bits), 63 bytes captured (504 bits) on interface 0
    Interface id: 0 (eth0)
        Interface name: eth0
    Encapsulation type: Ethernet (1)
    Arrival Time: Jun 25, 2020 15:17:37.289652802 UTC
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1593098257.289652802 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 63 bytes (504 bits)
    Capture Length: 63 bytes (504 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:coap]
Ethernet II, Src: 42:01:0a:00:04:05 (42:01:0a:00:04:05), Dst: 42:01:0a:00:04:01 (42:01:0a:00:04:01)
    Destination: 42:01:0a:00:04:01 (42:01:0a:00:04:01)
        Address: 42:01:0a:00:04:01 (42:01:0a:00:04:01)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: 42:01:0a:00:04:05 (42:01:0a:00:04:05)
        Address: 42:01:0a:00:04:05 (42:01:0a:00:04:05)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.0.4.5, Dst: 172.16.0.56
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 49
    Identification: 0xd44e (54350)
    Flags: 0x4000, Don't fragment
        0... .... .... .... = Reserved bit: Not set
        .1.. .... .... .... = Don't fragment: Set
        ..0. .... .... .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 64
    Protocol: UDP (17)
    Header checksum: 0xac20 [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.0.4.5
    Destination: 172.16.0.56
User Datagram Protocol, Src Port: 5683, Dst Port: 5683
    Source Port: 5683
    Destination Port: 5683
    Length: 29
    Checksum: 0xba7b [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]

Frame 2: 61 bytes on wire (488 bits), 61 bytes captured (488 bits) on interface 0
    Interface id: 0 (eth0)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:coap:lwm2mtlv]
Ethernet II, Src: 42:01:0a:00:04:01 (42:01:0a:00:04:01), Dst: 42:01:0a:00:04:05 (42:01:0a:00:04:05)
    Destination: 42:01:0a:00:04:05 (42:01:0a:00:04:05)
        Address: 42:01:0a:00:04:05 (42:01:0a:00:04:05)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: 42:01:0a:00:04:01 (42:01:0a:00:04:01)
        Address: 42:01:0a:00:04:01 (42:01:0a:00:04:01)
        .... ..1. .... .... .... .... = LG bit: Locally administered address (this is NOT the factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 172.16.0.56, Dst: 10.0.4.68
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x28 (DSCP: AF11, ECN: Not-ECT)
        0010 10.. = Differentiated Services Codepoint: Assured Forwarding 11 (10)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 47
    Identification: 0x0023 (35)
    Flags: 0x0000
        0... .... .... .... = Reserved bit: Not set
        .0.. .... .... .... = Don't fragment: Not set
        ..0. .... .... .... = More fragments: Not set
        ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 252
    Protocol: UDP (17)
    Header checksum: 0x03e7 [validation disabled]
    [Header checksum status: Unverified]
    Source: 172.16.0.56
    Destination: 10.0.4.68
User Datagram Protocol, Src Port: 5683, Dst Port: 5683
    Source Port: 5683
    Destination Port: 5683
    Length: 27
    Checksum: 0x8137 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
```

**Comment by sbernard31** [comment]
Could you share what makes you think that _"UDPConnector$Receiver seems to think that the response was received on port 1024"_ ?

**Comment by oz117** [comment]
Yes sorry here is the log:
`2020-06-25 15:17:37,286 DEBUG UdpMatcher - tracking open request [KeyMID[172.16.0.56:5683-10785], KeyToken[172.16.0.56:5683-7CF97A42191959A5]]
2020-06-25 15:17:37,286 DEBUG EventServlet - Dispatching COAPLOG event from endpoint urn:dev:ops:0x0000-2-100506
2020-06-25 15:17:37,289 DEBUG UDPConnector$Sender - UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 21 bytes to /172.16.0.56:5683
2020-06-25 15:17:38,023 DEBUG UDPConnector$Receiver - UDPConnector (0.0.0.0/0.0.0.0:5683) received 19 bytes from /172.16.0.56:1024
2020-06-25 15:17:38,025 TRACE UdpMatcher - received response ACK-2.05   MID=10785, Token=7CF97A42191959A5, OptionSet={"Content-Format":"application/vnd.oma.lwm2m+tlv"}, c1 00 01  from UDP(172.16.0.56:1024)
2020-06-25 15:17:38,027 TRACE UdpMatcher - discarding by [KeyToken[172.16.0.56:1024-7CF97A42191959A5]] unmatchable piggy-backed response from [UDP(172.16.0.56:1024)]: ACK-2.05   MID=10785, Token=7CF97A42191959A5, OptionSet={"Content-Format":"application/vnd.oma.lwm2m+tlv"}, c1 00 01`

**Comment by boaks** [comment]
I guess, I have to check my logging statements, just a second ...

**Comment by sbernard31** [comment]
Code sounds good to me :thinking: 
https://github.com/eclipse/californium/blob/2.2.3/element-connector/src/main/java/org/eclipse/californium/elements/UDPConnector.java#L362

**Comment by boaks** [comment]
I checked it, I don't think, there is an issue.
Maybe you can provided us logs and capture from the same messages?

One issue from the past was, that if you use a "router" and that contains a NAT, that sometimes makes strange things, if the same port is used on the device and the server. Even if there is no reason for that,

**Comment by boaks** [comment]
What do you use as client?

**Comment by sbernard31** [comment]
Where is done the capture ? (server or client side)

**Comment by oz117** [comment]
> What do you use as client implementation?

-> Our client is a home made one.



> Where is done the capture ? (server or client side)

-> This capture is happening inside the docker container running leshan server demo



> I checked it, I don't think, there is an issue.
> Maybe you can provided us logs and capture from the same messages?
> 
> One issue from the past was, that if you use a "router" and that contains a NAT, that sometimes makes strange things, if the same port is used on the device and the server. Even if there is no reason for that,

-> here are the logs:
- `leshan`:

`2020-06-26 09:41:39,392 DEBUG ReliabilityLayer - Exchange[L31] send request, failed transmissions: 0
2020-06-26 09:41:39,393 DEBUG ReliabilityLayer - Exchange[L31] prepare retransmission for CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["1","0"], "Accept":"application/vnd.oma.lwm2m+tlv"}, no payload
2020-06-26 09:41:39,393 DEBUG InMemoryMessageExchangeStore - [LWM2M Server-coap://] Exchange[L31] added with generated mid KeyMID[172.16.0.157:5683-14882], CON-GET    MID=14882, Token=null, OptionSet={"Uri-Path":["1","0"], "Accept":"application/vnd.oma.lwm2m+tlv"}, no payload
2020-06-26 09:41:39,394 DEBUG InMemoryMessageExchangeStore - [LWM2M Server-coap://] Exchange[L31] added with generated token KeyToken[172.16.0.157:5683-A8EC7AC2E0A3880B], CON-GET    MID=14882, Token=A8EC7AC2E0A3880B, OptionSet={"Uri-Path":["1","0"], "Accept":"application/vnd.oma.lwm2m+tlv"}, no payload
2020-06-26 09:41:39,394 DEBUG UdpMatcher - tracking open request [KeyMID[172.16.0.157:5683-14882], KeyToken[172.16.0.157:5683-A8EC7AC2E0A3880B]]
2020-06-26 09:41:39,395 DEBUG EventServlet - Dispatching COAPLOG event from endpoint urn:dev:ops:0x0000-2-100422
2020-06-26 09:41:39,396 DEBUG UDPConnector$Sender - UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 19 bytes to /172.16.0.157:5683
2020-06-26 09:41:40,085 DEBUG UDPConnector$Receiver - UDPConnector (0.0.0.0/0.0.0.0:5683) received 31 bytes from /172.16.0.157:1024
2020-06-26 09:41:40,087 TRACE UdpMatcher - received response ACK-2.05   MID=14882, Token=A8EC7AC2E0A3880B, OptionSet={"Content-Format":"application/vnd.oma.lwm2m+tlv"}, c1 00 01 c4 01 00 03 f4 80 c1 06 00 c1 07 55  from UDP(172.16.0.157:1024)
2020-06-26 09:41:40,088 TRACE UdpMatcher - discarding by [KeyToken[172.16.0.157:1024-A8EC7AC2E0A3880B]] unmatchable piggy-backed response from [UDP(172.16.0.157:1024)]: ACK-2.05   MID=14882, Token=A8EC7AC2E0A3880B, OptionSet={"Content-Format":"application/vnd.oma.lwm2m+tlv"}, c1 00 01 c4 01 00 03 f4 80 c1 06 00 c1 07 55 
2020-06-26 09:41:44,395 DEBUG CoapSyncRequestObserver - Synchronous request cancelled CON-GET    MID=14882, Token=A8EC7AC2E0A3880B, OptionSet={"Uri-Path":["1","0"], "Accept":"application/vnd.oma.lwm2m+tlv"}, canceled no payload
2020-06-26 09:41:44,396 DEBUG CleanupMessageObserver - canceled, Exchange[L31] request [MID=14882, Token=A8EC7AC2E0A3880B]
2020-06-26 09:41:44,397 WARN ClientServlet - Request /api/clients/urn:dev:ops:0x0000-2-100422/1/0 timed out.
2020-06-26 09:41:44,396 TRACE Exchange - Exchange[L31, complete]!
java.lang.Throwable: Exchange[L31, complete]
        at org.eclipse.californium.core.network.Exchange.setComplete(Exchange.java:838)
        at org.eclipse.californium.core.network.Exchange$1.run(Exchange.java:911)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
2020-06-26 09:41:44,397 DEBUG InMemoryMessageExchangeStore - [LWM2M Server-coap://] removing Exchange[L31, complete] for token KeyToken[172.16.0.157:5683-A8EC7AC2E0A3880B]
2020-06-26 09:41:44,398 DEBUG InMemoryMessageExchangeStore - [LWM2M Server-coap://] removing Exchange[L31, complete] for MID KeyMID[172.16.0.157:5683-14882]
2020-06-26 09:41:44,398 DEBUG Exchange - local Exchange[L31, complete] completed CON-GET    MID=14882, Token=A8EC7AC2E0A3880B, OptionSet={"Uri-Path":["1","0"], "Accept":"application/vnd.oma.lwm2m+tlv"}, canceled no payload!`

- `tcpdump`:
`09:41:39.396817 IP (tos 0x0, ttl 64, id 51736, offset 0, flags [DF], proto UDP (17), length 47)
    10.0.4.5.5683 > 172.16.0.157.5683: [bad udp cksum 0xbade -> 0xdf8e!] UDP, length 19
09:41:40.084518 IP (tos 0x28, ttl 252, id 7, offset 0, flags [none], proto UDP (17), length 59)
    172.16.0.157.5683 > 10.0.4.68.5683: [udp sum ok] UDP, length 31`

**Comment by oz117** [comment]
Following this comment:
> One issue from the past was, that if you use a "router" and that contains a NAT, that sometimes makes strange things, if the same port is used on the device and the server. Even if there is no reason for that
I tried multiple things:
 - different ports between the client and the server -> not ok the port printed by the comment is still `1024`
 - server on 5683 and client on 1024 -> not ok the port printed by the comment is now `1025`

**Comment by sbernard31** [comment]
It's really a surprising behavior. :open_mouth: 

Looking at the code again, I would be really surprised that the issue was at californium level. As `Datagram.getPort()` (JDK API) returns the wrong port.

Did you test using DTLS ? or/and another client like `leshan-client-demo` ? or launch leshan-server-demo on the same machine but outside the container ? (This could maybe help to localize the issue :thinking: )

Considering that wireshark port are correct, I would guess this is not an network issue but maybe a kind of port-forward/mapping issue at container level ?

**Comment by oz117** [comment]
I will try to run it directly inside the vm. However, I have put the container in host mode. Meaning there should not be any kind of port-forwarding

**Comment by boaks** [comment]
I can't see in the code, that californium mixes up the ports.
I don't belief, that java has a bug in the ip stub, that would affect the "world" :-).

But from my experience of the last 2 years:

I guess it's k8s, that applies unaware modifications on the network traffic :-).

Using 

ubuntu 18.04, 
microk8s (v1.18.4), 
hono deployed using hono packages (k8s with two coap adapter nodes)

I get:

1. Sending a coap request from port 5684 to my hono running in k8s,
it shows a "mapped host" (CNI) and the original port.

1. Sending a second coap request from the same host and port 5684
it still shows the same "mapped host" and the original port.

1. Sending a third coap request from the different host and port 5684
it shows the same "mapped host" and a different port (1024 for the first different host).

Looks like source NATing, at least for my microk8s installation.

AFAIK, k8s comes with many implementations and many CNIs. They may behave different.

So, I would propose, that you try out your installation&configuration with the procedure above and report us your results.

**Comment by oz117** [comment]
Hey @boaks thanks, I am going to try.
I was worried that it might be linked to kubernetes...

**Comment by boaks** [comment]
Hi @oz117 ,

could make progress in your investigation? Did you find a solution?

Just to mention, I use Californium with k8s, but my communication is always incoming triggered, so the NAT doesn't make trouble. If you didn't find a solution, maybe you consider to send the outgoing request via a different route, maybe even using a proxy. That would leave the NAT mapping to be triggered by incoming messages and that should work, at least in my experience. For LwM2M compliance that may mean, you send a POST /1/x/8 (Tripper Update) to the device, that ack/response to that maybe lost. But that should trigger the device to execute a "registration update" and with that it should work on k8s. Maybe you use anyway something as a SMS or similar a call with an extended dial number (means: call a number and send additional number to authenticate, if your device is able to receive that).

**Comment by oz117** [comment]
Hello @boaks,
I haven't had time to spent on this issue. However a colleague of mine took the subject and simply decided to write a `lwm2m` in go.
All of our backend is written in go. That's why.
As for the rest I will close this issue. I still think this behavior is very strange I hope someone will find what is happening here. Because it could be great to have leshan running inside a kubernetes cluster with all it's features enabled :smilley:

Thanks for the help

**Comment by boaks** [comment]
I don't think, that it depends on java or go, what k8s applies to the udp-traffic.
And I don't belief, that a go implementation will be production ready too soon ;-).

**Comment by oz117** [comment]
All of our backend is written in go. And the guys here are not ready to switch to Java. So that's why we are writing it in go.
As for a production ready implementation I agree with you, it won't be coming anytime soon. We are trying to fix our communication issues with something we have better understanding, control and knowledge 😀

**Comment by boaks** [comment]
@oz117 

Any progress in your k8s topic? Did using `go` provide any help?

Working on [k8s cid-load-balancer support](https://github.com/eclipse/californium/tree/wip_dtls_cid_cluster/demo-apps/cf-extplugtest-server#k8s-nodes) I added a "context" resource to the plugtest server and improved the `cf-browser`. Using both together, you see, if your `address:port` tuples are changing.

![Cf-brower - context](https://user-images.githubusercontent.com/10937819/97690632-89dbc080-1a9d-11eb-9124-123c1bfa0890.png)

Using the `--local-port` and starting the client from different host should the show, if the `address:port` tuple is changed. Maybe you can add such a "context", or maybe just a "myip" resource as well to your approach to see, if that applies there as well.

**Comment by oz117** [comment]
Hi @boaks,
the go version seem to be working fine last time I checked. I am no longer working at the company.
I will however pass them this topic so they can add something if needed.
In the ended the issue was/is linked to k8s, no one was able to explain what exactly was going wrong 😬

**Comment by boaks** [comment]
Thanks!

> In the ended the issue was/is linked to k8s

That's also my impression ;-).

**Comment by schmurfy** [comment]
Hello,
We made the go version of the lwm2m server for multiple reasons but the port issue also happens with our new implementation so I can confirm it is linked to k8s and I stopped looking for it, I just made a quick and dirty tweak and ignore the incoming port.

(oz117 was my colleague :) )

**Comment by boaks** [comment]
@schmurfy 

Thanks for the information! 

In the last weeks I spend also some more time into the k8s networking.
As already mentioned above, one small extension, which helps to understand the current k8s implementations, is to add something as "myip" or "context" to the server to easier see, what is exactly seen on the server node.

For me, at least the "kube-proxy" used by microk8s seems to apply a sNAT strategy (it replaces the source). It keeps the port, if that's free, but with a seconds client using the same, the port changes. 

With that I have a list of alternatives to analyze:
- using envoy. Seems this fails fast, because it's also a sNAT, at least that's what I understand from the docu.
- using IPVS instead of the plain ip-tables "kube-proxy". I'm not sure, if the other k8s components work, if that is put into sNAT mode (or if that is possible at all).
- using a headless-service and try to find load-balancer/proxy, which implements the dNAT approach.

If you have success with any setup (other then ignore the port ;-), I would welcome that helping information.

**Comment by schmurfy** [comment]
@boaks I have narrowed down the k8s issue to, at least, know where it is occuring but I am not sure why.

Each node can do some NAT on both directions (managed by kube-proxy I suppose), for incoming packets you can use `externalTrafficPolicy: Local` on `Service` to decide wether you want to see the real source ip or use the default which is to replace it with the node address (to be honest I have no idea why I would want that but I stopped thinking too much about k8s design decisions)

The initial issue I had was that the first incoming packet had the correct port but every other following that (for each source so I suspect a state issue in the iptables rules) had its source port replaced by 1024 but the ip was correct.

I will post an update here if I manage to find a working (non dirty ;) ) solution but for now I stopped spending time on this since this hack works.

**Comment by boaks** [comment]
Thanks for that `externalTrafficPolicy` hint!

I guess, I must check the possibilities of a k8s services much more :-).

**Comment by oz117** [comment]
@boaks be careful with the `externalTrafficPolicy` I discovered later on that it also has an impact on how requests coming to your cluster are load balanced between nodes and pods running inside those nodes.

Lets say you have three pods (`pA`, `pB`, `pC`) running with two nodes (`nA`, `nB`).
 - `pA` and `pB are running on node `nA`
 - `pC` is running on node `nB`

In such configuration it would make sens for `nA` to receive more requests as it has more instances running.

When `externalTrafficPolicy` is switched to `local` k8s won't be able to properly load balance and so `pC` might be receiving more requests than the two other pods.

**Comment by boaks** [comment]
Thanks for reporting this finding.

I had this week time to test with that service configuration. FMPOV, if the downside is known, it may be possible to mitigate it. But for now, I didn't checked it with multi-node deployments. I currently focused on the built-in DTLS CID load-balancer and the new DTLS graceful restart. On interest, see PR #1547 for details.
(At least in my experience, much more are using "public network" with NAT, than a "private network" with fixed IPs.)

With the "less handshakes", the clients will be even more sticky and so I guess, this unbalancing will be anyway get a real issue, regardless of the frontside balancing. But the trade off for the clients is much better, especially, if frequently lwm2m-registration-updates are used. Only a couple of coap bytes, but always an handshake. With CID its only a couple of coap bytes + a very small couple of CID bytes (6-10). That doesn't only save traffic, the "uptime" of the client is also smaller. Considering CAT-NB, my times are:

PSM enabled, 1 request every h:
> INFO [statistic]: success: 304, failures: 2
> INFO [statistic]: RTT all: 304, avg.: 5295 ms, 95%: 8320 ms, 99%: 50900 ms, 99.9%: 55358 ms, max.: 55358 ms
> INFO [statistic]: CON all: 319, avg.: 2918 ms, 95%: 1310 ms, 99%: 44550 ms, 99.9%: 141820 ms, max.: 141820 ms
> INFO [statistic]: PWR all: 303, avg.: 13563 ms, 95%: 15920 ms, 99%: 58290 ms, 99.9%: 163846 ms, max.: 163846 ms

5s average with PSM enabled is not that bad.
