### ISSUE TITLE
Proxy server for OpenThread network.

### ISSUE THREAD

**Issue by tarunsmalviya** [eclipse/californium#1354]
Hi, 

I am writing a proxy server in which HTTP server is running at 7070 port and CoAP server is running at 5683 port.

**Setup:**
1. I am using raspberry pi as IoT gateway which is configured as OpenThread border router.
2. Some OpenThread node are connected to raspberry pi.
3. A HTTP server is running at port 8080 in raspberry pi which is responsible for handling packets coming from OpenThread nodes via proxy server.

**Problem statement:**
I have written a code in which a reverse proxy CoAP resource is registered which is responsible for transmitting incoming packet from OpenThread node(CoAP client) to the HTTP server running at 8080 port. This functionality is working fine. 

Now, I want to fetch some information from OpenThread node via proxy server using forward proxy feature. So, for that I am firing a HTTP GET request at proxy server (URI: `http://127.0.0.1:7070/proxy/coap://[feef:ee::d7b4:9d35:b3f8:95d6%wpan0]:5683/clk`). This is not working. Can someone please help me with this. I am attaching my proxy server code.

Thanks in advance!

```
package com.zenatix.coap.server;

import com.zenatix.coap.server.resource.*;
import com.zenatix.coap.server.util.LoggerSingleton;
import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.CoapServer;
import org.eclipse.californium.core.network.CoapEndpoint;
import org.eclipse.californium.core.network.config.NetworkConfig;
import org.eclipse.californium.core.network.config.NetworkConfigDefaultHandler;
import org.eclipse.californium.core.server.MessageDeliverer;
import org.eclipse.californium.elements.util.DaemonThreadFactory;
import org.eclipse.californium.elements.util.ExecutorsUtil;
import org.eclipse.californium.elements.util.NetworkInterfacesUtil;
import org.eclipse.californium.proxy2.EndpointPool;
import org.eclipse.californium.proxy2.Http2CoapTranslator;
import org.eclipse.californium.proxy2.HttpClientFactory;
import org.eclipse.californium.proxy2.ProxyHttpServer;
import org.eclipse.californium.proxy2.resources.ForwardProxyMessageDeliverer;
import org.eclipse.californium.proxy2.resources.ProxyCoapResource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.net.*;
import java.util.concurrent.ScheduledExecutorService;

public class ProxyServer {

    private static final Logger STATISTIC_LOGGER = LoggerFactory.getLogger("org.eclipse.californium.proxy.statistics");

    /**
     * File name for network configuration.
     */
    private static final File CONFIG_FILE = new File("Californium.properties");
    /**
     * Header for network configuration.
     */
    private static final String CONFIG_HEADER = "Californium CoAP Properties file for Example Proxy";
    /**
     * Default maximum resource size.
     */
    private static final int DEFAULT_MAX_RESOURCE_SIZE = 8192;
    /**
     * Default block size.
     */
    private static final int DEFAULT_BLOCK_SIZE = 1024;

    /**
     * Special network configuration defaults handler.
     */
    private static final NetworkConfigDefaultHandler DEFAULTS = new NetworkConfigDefaultHandler() {

        @Override
        public void applyDefaults(NetworkConfig config) {
            config.setInt(NetworkConfig.Keys.MAX_ACTIVE_PEERS, 20000);
            config.setInt(NetworkConfig.Keys.MAX_RESOURCE_BODY_SIZE, DEFAULT_MAX_RESOURCE_SIZE);
            config.setInt(NetworkConfig.Keys.MAX_MESSAGE_SIZE, DEFAULT_BLOCK_SIZE);
            config.setInt(NetworkConfig.Keys.PREFERRED_BLOCK_SIZE, DEFAULT_BLOCK_SIZE);
            // 24.7s instead of 247s
            config.setInt(NetworkConfig.Keys.EXCHANGE_LIFETIME, 24700);
            config.setInt(NetworkConfig.Keys.MAX_PEER_INACTIVITY_PERIOD, 60 * 60 * 24); // 24h
            config.setInt(NetworkConfig.Keys.TCP_CONNECTION_IDLE_TIMEOUT, 10); // 10s
            config.setInt(NetworkConfig.Keys.TCP_CONNECT_TIMEOUT, 15 * 1000); // 15s
            config.setInt(NetworkConfig.Keys.TLS_HANDSHAKE_TIMEOUT, 30 * 1000); // 30s
            config.setInt(NetworkConfig.Keys.UDP_CONNECTOR_RECEIVE_BUFFER, 8192);
            config.setInt(NetworkConfig.Keys.UDP_CONNECTOR_SEND_BUFFER, 8192);
            config.setInt(NetworkConfig.Keys.HEALTH_STATUS_INTERVAL, 60);
        }

    };

    private NetworkConfig networkConfig;

    private EndpointPool pool;
    private CoapServer coapServer;
    private ProxyHttpServer httpServer;

    private static final int COAP_PORT = 5683;
    private static final int HTTP_PORT = 7070;

    public ProxyServer() throws IOException {
        // Create network configuration by overriding some parameters by default value
        networkConfig = NetworkConfig.createWithFile(CONFIG_FILE, CONFIG_HEADER, DEFAULTS);
        HttpClientFactory.setNetworkConfig(networkConfig);

        int threads = networkConfig.getInt(NetworkConfig.Keys.PROTOCOL_STAGE_THREAD_COUNT);
        ScheduledExecutorService mainExecutor = ExecutorsUtil.newScheduledThreadPool(threads,
                new DaemonThreadFactory("Proxy#"));
        ScheduledExecutorService secondaryExecutor = ExecutorsUtil.newDefaultSecondaryScheduler("ProxyTimer#");

        NetworkConfig outgoingConfig = new NetworkConfig(networkConfig);
        outgoingConfig.setInt(NetworkConfig.Keys.NETWORK_STAGE_RECEIVER_THREAD_COUNT, 1);
        outgoingConfig.setInt(NetworkConfig.Keys.NETWORK_STAGE_SENDER_THREAD_COUNT, 1);
        pool = new EndpointPool(1000, 250, outgoingConfig, mainExecutor, secondaryExecutor);

        // Create a CoAP server
        coapServer = new CoapServer(networkConfig, ProxyServer.COAP_PORT);
        MessageDeliverer coapServerMessageDeliverer = coapServer.getMessageDeliverer();
        coapServer.setExecutors(mainExecutor, secondaryExecutor, false);
        coapServer.add(new PingResource());
        coapServer.add(new ClockResource());

        // Proxy resource which forwards request from CoAP to HTTP server
        coapServer.add(new ProxyResource());

        // A child of proxy resource which forwards request from CoAP to ZenEdge's HTTP server
        // Reverse proxy: add a proxy resource with a translator returning a fixed destination URI
        URI destination = URI.create("http://localhost:8080/packet");
        CoapResource reverseProxy = ProxyCoapResource.createReverseProxy("zenedge", true, true, true, destination, this.pool);
        coapServer.getRoot().getChild("proxy").add(reverseProxy);

        // Create a HTTP server
        // HTTP Proxy which forwards http request to CoAP server and forwards
        // translated CoAP response back to http client
        httpServer = new ProxyHttpServer(networkConfig, ProxyServer.HTTP_PORT);
        httpServer.setHttpTranslator(new Http2CoapTranslator());
         httpServer.setLocalCoapDeliverer(coapServerMessageDeliverer);
        httpServer.setProxyCoapDeliverer(coapServerMessageDeliverer);

        coapServer.add(httpServer.getStatistics());
    }

    public void start() throws IOException {
        this.coapServer.start();
        this.httpServer.start();
    }
}

```

**Comment by tarunsmalviya** [comment]
PFA for the debug logs when I hit `http://10.8.62.161:7070/proxy/coap://10.0.0.1:5684/clk`

<img width="1872" alt="Screenshot 2020-06-30 at 10 14 52 PM" src="https://user-images.githubusercontent.com/9993036/86153385-3d986800-bb1f-11ea-8c75-2de00145b149.png">

**Comment by boaks** [comment]
Using the proxy-server setup above and `http://localhost:7070/proxy/coap://104.196.15.150:5683/test` results "on my machine " in:

> DEBUG [HttpStack]: Incoming http request: on /127.0.0.1:7070 from /127.0.0.1:33170
>    GET /proxy/coap:/104.196.15.150:5683/test HTTP/1.1
> DEBUG [Http2CoapTranslator]: URI <= '/proxy/coap:/104.196.15.150:5683/test'
> DEBUG [Http2CoapTranslator]: URI path => '/proxy/coap:/104.196.15.150:5683/test'
> DEBUG [Http2CoapTranslator]: URI destination => 'coap://104.196.15.150:5683/test'
> INFO [HttpStack]: Received HTTP request and translate to CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}, no payload
> INFO [ProxyHttpServer]: ProxyEndpoint handles request CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}, no payload
> DEBUG [ProxyHttpServer]: Cache returned null
> INFO [ProxyHttpServer]: Cache response coap://104.196.15.150:5683/test
> DEBUG [ProxyCacheResource]: Cached response
> DEBUG [HttpStack]: Incoming response: null-2.05   MID=   -1, Token=null, OptionSet={"Content-Format":"text/plain"}, "************************".. 406 bytes
> DEBUG [HttpStack]: Outgoing http response: HTTP/1.1 200 OK
> DEBUG [HttpStack]: HTTP returned null-2.05   MID=   -1, Token=null, OptionSet={"Content-Format":"text/plain"}, "************************".. 406 bytes
> 

>
> ****************************************************************
> CoAP RFC 7252
> ****************************************************************
> This server is using the Eclipse Californium (Cf) CoAP framework
> published under EPL+EDL: http://www.eclipse.org/californium/
> 
> (c) 2014-2020 Institute for Pervasive Computing, ETH Zurich and others
> ****************************************************************
>

That means:
The http request is translated into the coap-request `CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}`. That request is "delivered" in your setup with the "standard server deliverer". That "standard server deliverer" looks up the resource by the provided path and deliver the request to that resource. In the case above, the path is "/", which is mapped to the root-resource. Though the standard root-resource doesn't handle the "proxy-uri" option, this simply results in get for the root-resource.

To emit a coap-request, the translated request must be delivered to a resource, which is implemented to handle that "proxy-uri" option. One possibility is to use a `ForwardProxyMessageDeliverer` to deliver the request to `ProxyCoapResource`.

```
// create proxy-resource
Coap2CoapTranslator translater = new Coap2CoapTranslator();
ProxyCoapResource coap2coap = new ProxyCoapClientResource("coap2coap", false, true, translater, this.pool);
coapServer.add(coap2coap);

// create proxy deliverer 
ForwardProxyMessageDeliverer proxyMessageDeliverer = new ForwardProxyMessageDeliverer(coapServer.getRoot(), translater);
// add proxy-resource to deliverer
proxyMessageDeliverer.addProxyCoapResources(coap2coap);

...
// add proxy-deliverer instead of standard deliverer
httpServer.setProxyCoapDeliverer(proxyMessageDeliverer);
```

with that setup, the result "on my machine" is:

> DEBUG [HttpStack]: Incoming http request: on /127.0.0.1:7070 from /127.0.0.1:33276
>    GET /proxy/coap:/104.196.15.150:5683/test HTTP/1.1
> DEBUG [Http2CoapTranslator]: URI <= '/proxy/coap:/104.196.15.150:5683/test'
> DEBUG [Http2CoapTranslator]: URI path => '/proxy/coap:/104.196.15.150:5683/test'
> DEBUG [Http2CoapTranslator]: URI destination => 'coap://104.196.15.150:5683/test'
> INFO [HttpStack]: Received HTTP request and translate to CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}, no payload
> INFO [ProxyHttpServer]: ProxyEndpoint handles request CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}, no payload
> DEBUG [ProxyHttpServer]: Cache returned null
> DEBUG [ProxyCoapClientResource]: ProxyCoapClientResource forwards CON-GET    MID=   -1, Token=null, OptionSet={"Proxy-Uri":"coap://104.196.15.150:5683/test"}, no payload
> DEBUG [Coap2CoapTranslator]: Incoming request translated correctly
> DEBUG [ProxyCoapClientResource]: Sending proxied CoAP request to IP(104.196.15.150:5683)
> DEBUG [ProxyCoapClientResource]: ProxyCoapClientResource received ACK-2.05   MID=39185, Token=18BFD0973CC8945D, OptionSet={"Content-Format":"text/plain", "Max-Age":30}, "Type: 0 (CON)
> Code: 1 (G".. 62 bytes
> DEBUG [Coap2CoapTranslator]: Incoming response translated correctly
> INFO [ProxyHttpServer]: Cache response coap://104.196.15.150:5683/test
> DEBUG [ProxyCacheResource]: Cached response
> DEBUG [HttpStack]: Incoming response: null-2.05   MID=   -1, Token=null, OptionSet={"Content-Format":"text/plain", "Max-Age":30}, "Type: 0 (CON)
> Code: 1 (G".. 62 bytes
> DEBUG [HttpStack]: Outgoing http response: HTTP/1.1 200 OK
> DEBUG [HttpStack]: HTTP returned null-2.05   MID=   -1, Token=null, OptionSet={"Content-Format":"text/plain", "Max-Age":30}, "Type: 0 (CON)
> Code: 1 (G".. 62 bytes

> Type: 0 (CON)
> Code: 1 (GET)
> MID: 39185
> Token: 18BFD0973CC8945D

Hope, that's what your looking for.

**Comment by tarunsmalviya** [comment]
@boaks It worked. Thank you so much!

Also, is there any documentation of Californium library besides example.

When I fetch data from OpenThread node using URI `coap://[feef:ee:0:0:5b26:4b0d:2331:b4a]:5683/test`, it works. But when I try to fetch data from OpenThread node using URI `coap://[feef:ee:0:0:5b26:4b0d:2331:b4a%wpan0]:5683/test`, proxy server throws exception. Any explanation why. PFA for details.

<img width="1920" alt="Screenshot 2020-07-01 at 1 48 25 PM" src="https://user-images.githubusercontent.com/9993036/86221400-7b8aa000-bba2-11ea-8a79-0826362dd661.png">

**Comment by boaks** [comment]
> Also, is there any documentation of Californium library besides example.

Unfortunately, no. There is some javadoc, but especially for the new proxy2, that is not "complete".

That exception is an old friend. I'll try to fix it.

**Comment by boaks** [comment]
Currently my test indicates, that the `%` in the host part should be encoded/escaped with `%25`.
could you try that?

**Comment by tarunsmalviya** [comment]
@boaks Yes, I did encoded thr URI into URL encoded format. 
For reference: `coap%3A%2F%2F%5Bfeef%3Aee%3A0%3A0%3A5b26%3A4b0d%3A2331%3Ab4a%25wpan0%5D%3A5683%2Ftest`

**Comment by boaks** [comment]
I adapted the URI processing. Could you please check, if it works (or throws an other exception  :-) ).

**Comment by tarunsmalviya** [comment]
@boaks How can I create jar file from above PR?

**Comment by boaks** [comment]
Is it possible for you to build it locally using maven and java?

**Comment by tarunsmalviya** [comment]
@boaks It is working. PFA for reference.

<img width="1920" alt="Screenshot 2020-07-01 at 4 59 57 PM" src="https://user-images.githubusercontent.com/9993036/86239189-776b7c00-bbbc-11ea-830f-83233db06024.png">

**Comment by boaks** [comment]
Thanks!

**Comment by tarunsmalviya** [comment]
@boaks I have got another question. 
By default proxy server listens on every network interface, isn't it? If yes, then how can I make it listen to particular network interface.

**Comment by boaks** [comment]
coap or http?

**Comment by tarunsmalviya** [comment]
@boaks Both

**Comment by boaks** [comment]
For http:

Check, if you can use a specific `InetSocketAddress` in `HttpServer.start()` when calling
`ioReactor.listen(new InetSocketAddress(httpPort));`. I haven't checked it, but if it works, I extend the included HttpServer.

For coap:

```
coapServer = new CoapServer(networkConfig);
coapServer.addEndpoint(new CoapEndpoint.Builder().setInetSocketAddress(new InetSocketAddress("addr", 5683)).build());
coapServer.addEndpoint(new CoapEndpoint.Builder().setInetSocketAddress(new InetSocketAddress("addr2", 5683)).build());
coapServer.addEndpoint(new CoapEndpoint.Builder().setInetSocketAddress(new InetSocketAddress("addr3", 5688)).build());
```

No port in the server constructor.
Add `CoapEndpoint`, as required.

**Comment by boaks** [comment]
You may check PR #1359. I added support to provide the network interface to bind the http server to.

**Comment by boaks** [comment]
If it works for you, please close this issue.

**Comment by tarunsmalviya** [comment]
Yes. It works. 
Thank You.
