### ISSUE TITLE
Fetching client certificate when handling requests

### ISSUE THREAD

**Issue by nxSwe** [eclipse/californium#136]
Hello!

I am currently writing a program that's forwarding some requests from coap to http, and using scandium for DTLS with client authentication.

The problem is that I would like to fetch the client certificate used in the DTLS handshake and forward it to the HTTP server. But I have found no way of retrieving the client certificate outside of the connector threads. I would for example like to have access to the client certificate during `forwardRequest` of a `ForwardingResource`, which only has a `Request` object as parameter.

I'm comparing this to the servlet-api `HttpServletRequest` which has the following property:
`X509Certificate[] clientCerts = (X509Certificate[])req.getAttribute("javax.servlet.request.X509Certificate");`

**Is it possible to retrieve the client certificate in some way I haven't figured out**, or is this something that needs to be implemented?

I can see that in the 2.0 branch there is a new class - `DtlsCorrelationContext`. Without having looked too much at the 2.0 code, perhaps something like that could be used to save the client certificate for later retrieval.

**Comment by sophokles73** [comment]
What version of Californium are you using?

**Comment by nxSwe** [comment]
1.0.4 currently

**Comment by sophokles73** [comment]
1.0.x does not (and will not) provide any means to determine the client's identity for a request.

However, this is available on master and the 2.0.x branch for some time now. You can use `Request.getSenderIdentity()` to get a standard `java.security.Principal` object representing the (authenticated) sender's identity.

We are currently in the process of figuring out when we want to do a 1.1 and 2.0.0 release. For the meantime you might be best off with using the 2.0.0-M2 milestone ...

**Comment by nxSwe** [comment]
Ah I see. I looked through the source code of 2.0 now and I had not realised that the senderIdentity could be a `org.eclipse.californium.scandium.auth.X509CertPath` containing more than just the subject. Perhaps this could be made clearer in the Javadoc of `Request.getSenderIdentity`.

I think I will upgrade to the 2.0 branch. Thanks!
