### ISSUE TITLE
Unused class ConnectorBase

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#138]
Does someone using the ConnectorBase?

Right now I can't see, that this class is used within californium.
Maybe we can remove it ...

**Comment by sophokles73** [comment]
I think we can remove it from the 2.0.x branch. But we should probably deprecate it on master for a while first ...

**Comment by boaks** [comment]
Agreed.

**Comment by sophokles73** [comment]
fixed on master in 071c6ac641549948c2d90ceaaa0267ec941bbd42
fixed on 2.0.x in 882ab5f61b35de0f2bea58a6e0113d8fac3646ec
