### ISSUE TITLE
Californium ReliabilityLayerParameters layer usage

### ISSUE THREAD

**Issue by madhushreegc** [eclipse/californium#1392]
Hi,

How to set ReliabilityLayerParameters  for downlink request from Leshan? I did not see interface supporting this. 

Regards,
Madhushree.

**Comment by boaks** [comment]
There is a general set for all messages without these parameters defined by the `NetworkConfig` - Californium.properties.
If a special set is wanted, use [Message.setReliabilityLayerParameters(ReliabilityLayerParameters parameter)](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L372)

**Comment by madhushreegc** [comment]
Message.setReliabilityLayerParameters(ReliabilityLayerParameters parameter) , this I have tried . Works fine . 

No idea of adding this as  parameter in method public <T extends LwM2mResponse> void send(Registration destination, DownlinkRequest<T> request,
            ResponseCallback<T> responseCallback, ErrorCallback errorCallback) {
        requestSender.send(destination, request, DEFAULT_TIMEOUT, responseCallback, errorCallback);
  

Thank you for response.

**Comment by boaks** [comment]
I guess, that is a question for the leshan project.

**Comment by boaks** [comment]
If your question is answered, please close it.

**Comment by madhushreegc** [comment]
Yes, Thanks . I have wrongly raised a question here . 

Thank you .

**Comment by boaks** [comment]
>. I have wrongly raised a question here .

You're welcome, question are never wrong. 
But I think, the leshan project can help more with the left part of this question.
