### ISSUE TITLE
Add eclipse code formatter rules file

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#14]
Several committers have complained about the lack of Eclipse code formatter definitions for some time now ;-)

**Comment by sophokles73** [comment]
So far I have been using Ecilpse's standard built-in formatting rules when working on Californium.

@mkovatsc, are you using any specific formatting rules or would mind me creating a set of reasonable ones based on standard Eclipse (which seem to be not much different from what we are currenly using implicitly)?

**Comment by mojadita** [comment]
Imho is that some formatting in relation to tabs/spaces must be agreed, and os newline chars must be agreed or some commits will result in all lines being changed by the same but with a differnet newline convention.  I think we are mixed windows/unix developers and some files are in trouble (like .gitignore in some places)

**Comment by sophokles73** [comment]
I have added a Eclipse code formatter and clean-up profiles to master in 6bdaf6d.

**Comment by mojadita** [comment]
Ok... thanks for the feedback :)

**Comment by mkovatsc** [comment]
At least it did not take me two complete months... :P

I have been using the default Eclipse profile with a longer line length
It looks like the maximum line length is 120. This is already more than 80, but checking my laptop setup, I can easily display 160. Locally, I actuall have the line length set to 1000 and always break long lines manually. This is becaue I prefer helpful logical clustering over strict line lengths.

Could we increase the maximum line length in the included formatter?

**Comment by sophokles73** [comment]
I have no problem with that. Go ahead and set to whatever you feel is right ...
