### ISSUE TITLE
InMemoryObservationStore assumes UDP transport

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#141]
The current implementation of `InMemoryObservationStore` uses the `UdpSerializer` to serialize messages to a byte array. When doing so, the `UdpSerilazer` implicitly stores the byte array within the `Message` object so that it doesn't need to be serialized again later on.

However, if the message is supposed to be sent over coap+tcp then the wrong message encoding is used because the stored byte array from the `Message` object will be used instead of performing the (correct) coap+tcp encoding.

**Comment by boaks** [comment]
The evil issue here is, that this pattern is already used "outside" of californium.

Leshan: `InMemoryLwM2mObservationStore`

Therefore PR #135 introduces a workaround, which would fix the missbehavior of the missuse :-).
I'm not sure, if users want to use the "serialization format" also for cluster and persistence usage.
If so, fixing only `InMemoryObservationStore `will not be enough.

**Comment by sophokles73** [comment]
But this is the Californium project, not the leshan project. If the leshan project needs to fix this as well, so be it.

**Comment by sophokles73** [comment]
fixed on master in 2f427e91887940665a2b5a9d40dd7109ac9d4207
fixed on 2.0.x in c48a2d308b09f67a0f88f141cc1130e6045eb04e

**Comment by boaks** [comment]
Are you sure, that serialize/parse on add instead of each get doesn't introduce a different functionality?

(Without checking the sources) I would assume, that in this solution the MessageObservers, added by each notify, would accumulate.

**Comment by boaks** [comment]
In my opinion, we need to know, why we need a "fresh" request.
I'm still wonder, if we just need to reset/clear the messageObservers.

**Comment by sophokles73** [comment]
@boaks,

I am not sure if I understand your point. I have moved the *cloning* to the `add` method because IMHO it better reflects the original intention of the ObservationStore, i.e. sharing of state between nodes.

> (Without checking the sources) I would assume, that in this solution the MessageObservers, added by each notify, would accumulate.

Do you suspect a memory leak here?

**Comment by sophokles73** [comment]
Hey,

I now see what you mean and you are totally right. We are accumulating more and more listeners on the (cloned) Request with every notification received. Will fix this tomorrow. Thanks for reviewing this 😀

**Comment by sophokles73** [comment]
fixed in 083ebc5982c1b0fced4b776dde2abccf64304539
