### ISSUE TITLE
2.0.0-M14，resumeexistingsession error

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#1414]
https://github.com/eclipse/californium/blob/76a5e5cb31eafe48a594e33677e97eab26c50905/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1585

In the resumeExistingSession scen, the connection is deleted, but no new connection put.  

in old version 2.0.0-M1 ,code like this :

 // immediately remove previous connection
terminateConnection(previousConnection);
// add the new one to the store
connectionStore.put(peerConnection);

when use resumeexistingsession, can not find connection.
Received 1 DTLS records from /11.42.170.225:5684 using a 16474 byte datagram buffer
no connection available for /11.42.170.225:5684,null
Discarding 1 records from [/11.42.170.225:5684] received without existing connection

**Comment by boaks** [comment]
> 2.0.0-M14

Maybe you can retest that with 2.4.1?

**Comment by boaks** [comment]
Have you been able to check that with 2.4.1?
AFAIK, resumption works, so I don't see the issue. If you have a test-case, where the resumption with 2.4.1 fails, let me know.

**Comment by boaks** [comment]
If the failure exists for 2.4.1, don't hesitate to report that.
