### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [eclipse/californium#1421]
https://github.com/eclipse/californium/blob/688853649bcee162bd7925a6561a238c85bec1d6/californium-proxy/src/main/java/org/eclipse/californium/proxy/HttpStack.java#L78

https://github.com/eclipse/californium/blob/688853649bcee162bd7925a6561a238c85bec1d6/californium-proxy/src/main/java/org/eclipse/californium/proxy/HttpStack.java#L84

This field is never used.

**Comment by boaks** [comment]
use proxy2 instead.
