### ISSUE TITLE
CoAP Client cant receive the response

### ISSUE THREAD

**Issue by PittLo** [eclipse/californium#1425]
Hi,I implement the interface **Connector** to try a new communication.
I can receive the response when I use a older version.
But the client cant receive the response when I update the version to the newest.
Here is the code:
old:  
            UDPSMSconnector = new UDPSMSConnector( activity,localPort, localPhoneNumber);
            client = new CoapClient();
            client.setEndpoint(new CoapEndpoint(UDPSMSconnector, NetworkConfig.getStandard()));
new:
           client = new CoapClient();
          UDPSMSconnector = new UDPSMSconnector(activity, localPort, localPhoneNumber);
          CoapEndpoint.Builder udpsmsEndpointBuilder = new CoapEndpoint.Builder();
          udpEndpointBuilder.setConnector(UDPSMSconnector);
          client.setEndpoint(udpEndpointBuilder.build());

Is there anything wrong？
I would appreciate it if you could answer.

**Comment by boaks** [comment]
Please configure logging (e.g. backlog) and enable DEBUG and provide the output.
Did you try to implement the "EndpointContext" Stuff for your Connector?

**Comment by boaks** [comment]
[Logs and IP Capturing](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) may help to prepare for logs and captures.

**Comment by PittLo** [comment]
thx,I will try implement the "EndpointContext" and observation the result.

**Comment by PittLo** [comment]
> Please configure logging (e.g. backlog) and enable DEBUG and provide the output.
> Did you try to implement the "EndpointContext" Stuff for your Connector?

Thank you very much.I did not add the "EndpointContext"  to implement the interface in my Connector into the old version.

/**
RawMsg.onContextEstablished(connectionContext);
**/

Now I solve the problem . 
Very appreciate it.

**Comment by boaks** [comment]
You're welcome.

**Comment by boaks** [comment]
Does it work in the meantime?
If so, could this issue be closed?
