### ISSUE TITLE
Less strict DtlsConnectorConfig.Builder ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1427]
In Leshan we have a builder to create our LWM2M client. 
With this builder you can set a `DtlsConnectorConfig.Builder` to tweak the dtls config. ([LeshanClientBuilder](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M1/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/LeshanClientBuilder.java#L151))

But this `DtlsConnectorConfig.Builder` will be used to create all endpoints/connectors (1 by server). PSK could be used for a given server and x509 for another one.

The given DtlsConnectorConfig.Builder is used as base to create all endpoint/connector. (See [CaliforniumEndpointsManager](https://github.com/eclipse/leshan/blob/leshan-2.0.0-M1/leshan-client-cf/src/main/java/org/eclipse/leshan/client/californium/CaliforniumEndpointsManager.java#L98)). The whole config is common except identity. 

So this config could contains more information than the only one needed for the created endpoint. 
E.g. you can set usable cipher suite (here we found a solution with https://github.com/eclipse/californium/pull/1416)
E.g. you can imagine for example, you set the truststore for X509 server. (https://github.com/eclipse/leshan/pull/905#discussion_r504956525)

The issue is that currently `DtlsConnectorConfig.Builder` is very strict.
**For "classic" use case, I think it's a good point.**

But for our "Leshan" use case, it's not so good.
A solution at Leshan side could be to create a new config and reapply parameters 1 by 1 (instead of doing `Builder newBuilder = new Builder(dtlsConfigbuilder.getIncompleteConfig());` but this could be fastidious and  we could missed new addition from scandium.

Maybe there is a smarter solution. Any idea ?
- maybe being able to unset some field (but this mean housekeeping is needed at leshan side)
- maybe having a less strict mode for dtlsbuilder which failed only for missing data and don't complain for extra data. To do that we need to define "less/extra data" regarding what ? I suppose identity parameters ? (PskStore, public/private keys, certainchain/private keys)

I pretty sure my last point is not so clear. So I give an example, if I set a public/private key and a x509 truststore, this will not raise an issue. (because this just extra data for RPK and not missing one)

**Comment by boaks** [comment]
> failed only for missing data and don't complain for extra data

The idea of complain on extra data  was to prevent accidentally ambiguous configuration.
I'm not sure, what really causes trouble.
Did you have already a look at the new `StaticNewAdvancedCertificateVerifier.Builder` of the upcoming 2.5.0?

I tried to understand the comments in the referred PR.
The issue with supporting the old (trust-store) and the new API (certificate verifier) is, that it easily gets ambiguous. Assume, starting with a trust store, then build() and then try to change the trust store again, is not too easy. The new `StaticNewAdvancedCertificateVerifier.Builder` helps to overcome that. With that, it's up to the caller to provide a ready `NewAdvancedCertificateVerifier` and that could then be replaced in the `DtlsConnectorConfig.Builder`.

**Comment by sbernard31** [comment]
> The idea of complain on extra data was to prevent accidentally ambiguous configuration.

I agree. That's why I said : "**For "classic" use case, I think it's a good point.**"
I think we need to keep this and if we need to relax it, I imagine some thing like new `DtlsConnectorConfig.Builder(relaxed)` ( keep the default one strict)

>  I'm not sure, what really causes trouble.

I try to explain the use case above :point_up:. I can understand this is not obvious, I'm not sure how I can explain this differently. :confused: 
Maybe you can see the dtlsconfig given to LeshanClientBuilder as a kind of "set of default values" used to create concrete dtlsconfig each time we need to create an endpoint.

>  Did you have already a look at the new StaticNewAdvancedCertificateVerifier.Builder of the upcoming 2.5.0?

I just look at this but I'm not sure to see how it could help.
I just see that you  deprecated setTrustStore in 2.5.0, so truststore is no more a good example. (As we want to keep a truststore as collection of certificate we will handle it on our own)

Anyway If I try to list what "was" or "I guess could be" an issue : 
- ciphersuite => resolved by #1416
- truststore => will be deprecated (so out of topic now)
- (maybe supported signature algo) => could be maybe resolve like #1416
- (maybe supported groups) =>  could be maybe resolve like #1416

My idea was to found a generic solution, rather than a specific one for each case, but maybe not a good idea. So let's close this issue and we will see if we need to re-open it later.

(If you have more thoughts about this please to not hesitate to share here)
