### ISSUE TITLE
ServerHello.extensions optional (null) or mandatory (empty set)?

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#143]
I get some NullPointerExceptions in ClientHandshaker:

		if (message.getExtensions().getExtension(ExtensionType.SERVER_NAME) != null) {

In many places, the extensions are checked to be not null. Should such a check be added her also?

**Comment by sophokles73** [comment]
Obviously.

**Comment by boaks** [comment]
In ClientHello the extensions are just initialized. so initialize or check for null

**Comment by boaks** [comment]
Just to be clear:
Should we/I cleanup the code either by adding always a check for `!= null` or should we just add a initialization as in  ClientHello (empty set), and remove the unnecessary checks?
Im for initialize and remove the checks :-)

**Comment by sophokles73** [comment]
I'd rather have a dedicated getter in `ServerHello` for retrieving the server_name extension, along the lines of `SeverHello.getMaxFragmentLength()` ...

It is actually very interesting that this doesn't occur in any of the integration test cases which means that we always have at least one additional extension present in the ServerHello in these tests ...

**Comment by sophokles73** [comment]
However, since I need to work on SNI in the context of #139 anyways, I can fix this as well. Thanks for reporting :+1:

**Comment by sophokles73** [comment]
fixed in 083ebc5
