### ISSUE TITLE
2.5.0 Released / x509 Sandbox Certificates Exchanged

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1431]
The 2.5.0 release comes with

Changes in DTLS:
- Asynchronous certificate verifier
- built-in CID load-balancer (beta)

Changes in CoAP:
- Introduce ClientObserveRelation

Changes in demo-apps:
- add "context" resouce to plugtest-server. Makes connection details of the server-side visible.

Changes in californium.tools:
- improved cf-browser, support for observe-notify

**Comment by boaks** [comment]
I postponed the 2.5.0 release for one week in order to add more test and some READMEs.

**Comment by sbernard31** [comment]
@boaks, I don't know if this should be in the scope of the 2.5.0 but : 
1. we have some CertificateVerifier in Leshan which maybe could be integrated in cf. (see https://github.com/eclipse/leshan/pull/923)
2. I suspect there is come code about certificate chain validation which should be in Leshan (see https://github.com/eclipse/leshan/pull/923#discussion_r518785898)

Let me know if you are interested by this. (If needed we can create dedicated issue to discuss about this)

**Comment by boaks** [comment]
If multiple CA-Certificates with common DN are "state of the art", the Californium requires some fixes/redesigns.

**Comment by boaks** [comment]
See PR #1442

**Comment by boaks** [comment]
The release is in the Eclipse Repos.

The artifacts are currently **NOT** on maven central, that has been postponed for short (infrastructure issue). 
The releases of actinium and tools are also postponed for that reason.

**Comment by boaks** [comment]
The 2.5.0 is available on the sandbox coap://californium.eclipse.org 
Please Note: the x509 demo certificates are renewed.

**Comment by boaks** [comment]
The releases of actinium 2.5.0 and tools 2.50 are available in the [Eclipse Repos](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/).

**Comment by boaks** [comment]
The 2.5.0 release is now also available on maven central.

**Comment by boaks** [comment]
Changelist:

a842c1d57 2020-11-12 Release 2.5.0
db7635c42 2020-11-09 Fix tcp/tls-tests with broken x509 chain and new keystore format.
0538d9f94 2020-11-09 Add external eddsa provider to java system security.
ab9716455 2020-11-10 Use root as common CA for libcoap tests.
2827a52d6 2020-11-09 Support multiple certificates for same DN.
b3e64a18f 2020-11-09 Update certificates.
866e54027 2020-11-12 Fix k8s install shell script of cf-extplugtest-server.
0ba00985b 2020-11-10 Add more documentation for the dtls-cid-cluster implementation.
574c7c432 2020-11-10 Update READMEs.
17d2b6731 2020-11-10 Add more javadoc to cluster connectors.
de9c93abb 2020-10-29 Add dtls cluster configuration to cf-extplugtest-server.
fe1b636aa 2020-10-29 Add cf-cluster module.
d0d928243 2020-11-05 Add integration tests for cluster function.
18ec67ae1 2020-10-07 Add cluster connector.
cb09c7d30 2020-10-27 Report outgoing alerts to handler as well.
d518d82a7 2020-11-04 Add ed25519-java by default, if build with java 11.
be282a302 2020-11-02 Benchmark client, increase stale timeout for dtls fail-over.
ea5f71fc2 2020-11-02 Adapt maven name of cf-bom to "Californium (Cf) BOM" compliant to other names.
5a5008078 2020-10-31 Add detection for handshakes with itself.
dfafbb768 2020-11-01 Fix javadoc typos in cf-nat.
179fb2e57 2020-11-01 Add ports to benchmark configuration.
f73a7ed34 2020-10-28 Add reverse address update.
e2cc63482 2020-10-29 #1420: Remove double-check locking in CoapClient
b507a473a 2020-10-28 Add previous address to handshake error message.
26e0d0014 2020-10-28 Update netty to 4.1.52.
a3c16ae26 2020-10-27 Add --non to cli client configuration.
a2722ebf7 2020-10-27 Fix load-balancer destination timeout.
6ae2c87a3 2020-10-25 Add write cid and server version to context.
ff718a3bf 2020-10-23 Add createFlight to Handshaker.
2b001e679 2020-10-23 update readme file to include detail around network interface selection
8a404a6c1 2020-10-20 Change xml element name to context.
632decc36 2020-10-18 Introduce ClientObserveRelation.
c5f145aa0 2020-10-17 Add link to Logs and IP Capturing wiki page for new issues.
3f44de5a9 2020-10-16 Add CID to endpoint context.
50ee690e1 2020-10-15 Add USE_TCP, USE_UDP, USE_PLAIN, and USE_SECURE to imported variables.
fa18f3c02 2020-10-13 Prevent last destination from expiring.
d8dd3c45c 2020-10-10 Fix defaults for receive client.
a848e3489 2020-10-07 Update picocli to 4.5.1.
c47406b88 2020-10-07 Add nat clear n.
6152165d1 2020-10-07 Exclude com.google.code.findbugs from indirect dependencies.
ab6148ade 2020-10-04 Fix javadoc typos.
b984031e7 2020-10-04 Fix shebang in shell scripts.
e7e4284b8 2020-09-30 Adjust thread group name for AsyncNewAdvancedCertificateVerifier.
24f84d545 2020-09-28 Fix NioNatUtil message-reorderer.
b0a4bd897 2020-08-27 Merge LoadBalancer function into NAT.
3b4f382e6 2020-08-27 Add counter for wrong message routes.
884e2fc33 2020-09-25 Slim cleanup for SslContextUtil.getInputStreamFromUri.
688853649 2020-09-24 Fix logger name.
0ff7603ff 2020-09-23 Fix javadoc typos.
bad8eadea 2020-09-23 Update javadoc for (client) session cache.
ca7d891ee 2020-09-22 Add unit test for trusting the node's certificate or intermediate certificates.
e64532706 2020-09-21 fix oscore dependency : californium-proxy2 should be test scope.
2ffa7e2ed 2020-09-17 Add preselected cipher suites to dtls configuration.
df349f76d 2020-09-18 Make signatureEncoded field final in EcdhEcdsaServerKeyExchange.
5042e7908 2020-09-18 Use CertPathValidator.getDefaultType() for CertPathValidator.
18a6de67b 2020-09-17 Adapt trust of node's certificate.
219cc3b0a 2020-09-18 Add alert description to handshake exception.
7a2696eba 2020-09-18 Move signature map to ThreadLocalSignature.
af2edf6bf 2020-09-18 Move KEY_FACTORIES map to ThreadLocalKeyFactory.
1ec3f63b8 2020-09-18 Re-encode EdDSA private keys on loading instead of using.
52ab36bca 2020-09-17 Change some fields in handshaker to final.
ca0a81e6b 2020-09-17 Fix race condition for benchmark startup with RPK.
a23b68413 2020-09-17 Update benchmark.sh to 2.5.0-SNAPSHOT.
1dfed9cbb 2020-09-02 Add new advanced certificate verifier.
37712426e 2020-09-10 Update to 2.4.1.
1fbefe7a7 2020-09-04 Fix typos in javadoc.
3178d2529 2020-09-02 Add NullPointerException to javadoc.
ec3449362 2020-09-02 Fix typos.
62e87719f 2020-09-01 Disable netstat logger for windows.
7c02f7693 2020-09-01 Fix cookie generator.
bcb7937a6 2020-08-31 Adapt benchmark.
113cb1611 2020-08-28 Add simplified support for hono request and PSK credentials.
b4c67aaaf 2020-08-26 Support protocol version 1.0 for dtls-firewall-rules.
5f30714f2 2020-08-24 Use version 1.0 for hello verify requests.
834f09f76 2020-08-30 Cleanup advanced handshake tests.
4e8ad21fe 2020-08-30 Add more logging in dtls for dropped messages.
b36a81828 2020-08-30 Add finish message to test name logger rule.
923def44e 2020-08-28 Fix assembly files.
b683e6769 2020-08-27 Add "work in progress" annotation to mark new APIs.

**Comment by boaks** [comment]
The 2.5.0 unfortunately comes with an unintended API break (see issue #1451):

Using [DtlsConnectorConfig.Builder](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java) it is not longer possible to use
`setRpkTrustStore` and `setCertificateVerifier` at the same time.
The intention is to use `StaticNewAdvancedCertificateVerifier` or a custom implementation of the `NewAdvancedCertificateVerifier`. Temporary also the `BridgeCertificateVerifier` will help.
