### ISSUE TITLE
Looking for a server side AlertHandler extension point within scandium

### ISSUE THREAD

**Issue by TerenceYi** [eclipse/californium#1432]
Looking for a server-side ALERT handler which can register a call back when an ALERT message is generated from scandium.
Scandium provided org.eclipse.californium.scandium.AlertHandler which can register a call back in order to be able to react to  when an <em>ALERT</em> message is received from a peer, which was not designed for server-side ALERT

I'm using californium 2.2.3.

What I have tried is registered a SessionListener which will not be involved when handshake failed. During testing, the UNKNOWN_PSK_IDENTITY has not triggered the handshake fails, the ongoing HS was terminated with a timeout.
I found a discussion related to this behavior, https://bugs.eclipse.org/bugs/show_bug.cgi?id=533258. what I'm looking for was to collect server-side counters for handshake fail.

**Comment by boaks** [comment]
> counters for handshake fail.

Maybe `DtlsHealth` works for you. You may pass it in via `DtlsConnectorConfig`. 
If you want to count specific reasons, then I guess, we will need to extend scandium.
Let me know, what you're looking for.

**Comment by TerenceYi** [comment]
Thanks for your quick reply!

I checked the DtlsHealth which is good enough to provided the overview of health status.
I'm looking for the count for specific reasons, all Alert defined in [RFC5246](https://tools.ietf.org/html/rfc5246#page-28).

**Comment by boaks** [comment]
> BTW, what do you mean "need to extend scandium"?

Add that missing feature.

**Comment by boaks** [comment]
I currently checked the `AlertHandler`. With your explanation from above, I consider you want to be called for the suppressed UNKNOWN_PSK_IDENTITY but then not for the followup TIMEOUT, or?

**Comment by boaks** [comment]
If possible, please check, if PR #1433 works for you.
