### ISSUE TITLE
Should CertPathUtil.validateCertificatePath() return the selected TrustAnchor ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1443]
`CertPathUtil.validateCertificatePath()` is responsible to do PKIX validation. 
To do that, it needs to select the right trustAnchor.

It could make sense to have an API which allow to know this selected Anchor.
Java API seems to provides this information via `PKIXCertPathValidatorResult.getTrustAnchor()` when using `validator.validate(verifyCertPath, params);`

CA Constraint usage (0) from [rfc6698](https://tools.ietf.org/html/rfc6698#section-2.1.1) is an example where this would be usefull : 
```
* 0 -- Certificate usage 0 is used to specify a CA certificate, or
 *       the public key of such a certificate, that MUST be found in any of
 *       the PKIX certification paths for the end entity certificate given
 *       by the server in TLS.  This certificate usage is sometimes
 *       referred to as "CA constraint" because it limits which CA can be
 *       used to issue certificates for a given service on a host.  The
 *       presented certificate MUST pass PKIX certification path
 *       validation, and a CA certificate that matches the TLSA record MUST
 *       be included as part of a valid certification path.  Because this
 *       certificate usage allows both trust anchors and CA certificates,
 *       the certificate might or might not have the basicConstraints
 *       extension present.
```

**Comment by boaks** [comment]
Variant 1:
Add that as last certificate to the chain. In many cases, just truncate the chain after that, and not before.

Variant 2:
Modify the trustedCertificates (set others to `null`).

Variant 3:
Use a different return value.

For all variants, I would add a new function in order to prevent breaking using code by the different behaviour.

I would prefer variant 1, but I'm also open for the other variants or additional proposals.

**Comment by sbernard31** [comment]
I would prefer to understand correctly the "truncated" stuff before to give an opinion on this. (https://github.com/eclipse/californium/pull/1442#issuecomment-724162848)

**Comment by boaks** [comment]
The selected anchor is returned as last certificate in the resulting chain.
