### ISSUE TITLE
Request.userContext

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#145]
I'm pretty unsure, for what this is used. Currently leshan puts some data in.
Is intended to be related to the CorrelationContext? Or was it intended to be used unrelated to that context?

**Comment by sophokles73** [comment]
I think this is used in the context of failing over observations between nodes.
`ObservationStore.add()` also persists the data from `Request.userContext`.

**Comment by sbernard31** [comment]
UserContext is used to attach application data to a request. (a feature provided by californium for enduser) (see #86)
E.g we use it in Leshan to attach the registration id linked to an observe requests.

CorrelationContext contains data used to make correlation between CoAP messages. (needed for internal californium behavior)

HTH

**Comment by boaks** [comment]
Thanks!
