### ISSUE TITLE
Feedback about  release 2.5.0

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1451]
I put on my user cap by integrating Cf-2.5.0 in Leshan, some feedback above : 

### Deprecation PskStore/AdvancedPskStore :
1. frustrating to remove deprecated stuff and get other deprecated warning stuff instead : setResultHandler(~PskSecretResultHandler~ resultHandler)

2. API is probably more flexible but for user who only cares about providing key for a given identity it's really less straightforward. (too many  useless parameters in this case, you need to implement method you don't care about async, you need to ask yourself if you support ecdhe)
   For single psk/key pair, `AdvancedSinglePskStore` helps a lot.

### Deprecation RpkTrustStore/NewAdvancedCertificateVerifier
API is probably more flexible but for user who only cares about just saying if they trust or not a given RPK in a sync way this is  really less straightforward. (you need to handle X509 and RPK at same type, you need to care about CertificateType,  you need to implement method you don't care about async)

For static configuration, the `StaticNewAdvancedCertificateVerifier.Builder` helps a lot but it should maybe be more visible in javadoc where old stuff is deprecated. Currently only `NewAdvancedCertificateVerifier` interface is referenced.

### Deprecation CertificateVerifier&trust/NewAdvancedCertificateVerifier
More or less same remarks as above.

### DtlsConnectorConfig
1. I think there is maybe a backward compatibility bug. Before you was able to set a RpkTruststore + a CertificateVerifier. I suspect that now you can not do that.

2. I think that getTrustStore, getCertificateVerifier & getRpkTrustStore should not be deprecated. Pretty much the same issue than https://github.com/eclipse/californium/issues/1323#issuecomment-641184338 but it seems it can not be fixed in a same way.

### Global Feeling
My current feeling is that API bring probably more possibility at cost of complex API.
For some static usecase there is some API which hide this complexity. :+1: 
For some other classic sync usecase, the API is now clearly less user-friendly than before.

**Comment by boaks** [comment]
> frustrating to remove deprecated stuff and get other deprecated warning stuff instead : setResultHandler(PskSecretResultHandler resultHandler)

Sure, therefore I plan to switch to 3.0. It's simply hard to change an API "again". The `PskSecretResultHandler` will be removed and fully replaced by the generic `HandshakeResultHandler`.
 
The issue of supporting both "in memory trusts stores" and "dynamic verifier callback" got somehow wired up.
For the new ones, there are builders, `StaticNewAdvancedCertificateVerifier.Builder`, I hope these builder makes it easier to configure, what is wanted. OK, it's a little more typing.

> I think there is maybe a backward compatibility bug. Before you was able to set a RpkTruststore + a CertificateVerifier. I suspect that now you can not do that.

That mix requires now a custom implementation of a `NewAdvancedCertificateVerifier`. For the time to migrate, you may use the `BridgeCertificateVerifier`, also with builder (see javadoc of `CertificateVerifier`).  

> getTrustStore, getCertificateVerifier & getRpkTrustStore should not be deprecated

If the DtlsConfiguration is about to keep the stuff for Scandium, then these getter are not longer used by Scandium and therefore removed . FMPOV, it simply got to wired, to have all the mixtures.

> For some other classic sync usecase, the API is now clearly less user-friendly than before.

FMPOV, it's now a couple of lines more for the users, but much less headache for me :-)-

**Comment by sbernard31** [comment]
> FMPOV, it's now a couple of lines more for the users, but much less headache for me :-)-

It's not about writing a couple of lines but  more about understanding all the complex stuff which MUST BE ignored to do what they want. You need to understand before to be sure you don't need it.

This sounds to me this is better design to only expose user to level of complexity he needs.
I will not insist on this point as I already failed as committer (with a very unpleasant experience to me :worried:), I just report this as user without too many hope :disappointed: ...

I had more hope for this points  : 

1. For static configuration, the StaticNewAdvancedCertificateVerifier.Builder helps a lot but it should maybe be more visible in javadoc where old stuff is deprecated. Currently only NewAdvancedCertificateVerifier interface is referenced.

2. I think there is maybe a backward compatibility bug. Before you was able to set a RpkTruststore + a CertificateVerifier. I suspect that now you can not do that.

3. I think that getTrustStore, getCertificateVerifier & getRpkTrustStore should not be deprecated. Pretty much the same issue than #1323 (comment) but it seems it can not be fixed in a same way.

4. frustrating to remove deprecated stuff and get other deprecated warning stuff instead : setResultHandler(PskSecretResultHandler resultHandler)

I think 1) is important.
You should read 2) again because I think you introduce a behavior break. (look at both setter in DtlsConnectorConfig to better understand)
For 3) please re-read https://github.com/eclipse/californium/issues/1323#issuecomment-641184338 to better understand the problem.
For 3) 4), Maybe I'm wrong but I think that user you be able to write its code without deprecated stuff. I mean if this is deprecated, I should be able to rewrite my code in another way without this.

**Comment by boaks** [comment]
When I worked on Californium the last months, I already considered to stop 2.x and switch to 3.x because the changes seems to require a more consequent cleanup.

1) Just a question of time ...

2) seems so ... that's what my feeling was about try to support too many variants and get mixed up.
    Temporary work-around use `BridgeCertificateVerifier`. Solution: use new interfaces. 

3) The methods are deprecated, because they are intended to be removed on the next major version.
    As the related setter and even the deprecated interfaces will also be removed.
(For leshan my intention is, that the "credentials" are exchange by a callback, which reads out the stuff from the data-model in leshan. With the async feature,  that could be now done even within a different threading model.)
 
4) I just didn't find a solution, which put the stuff forward to the "final" solution. Without introducing too many new interfaces ...

**Comment by sbernard31** [comment]
For 3. My point is this would be better to just say to user that using setter is not good because this is deprecated and just let getter not deprecated. I can not see the issue with that solution.

For 4. I also think this is probably better to not deprecate the PskSecretResultHandler as it must be used when you implement a not deprecated Interface. 

You can remove stuff in 3.0 which are not deprecated in 2.0. I can even bet that this will happened.

Deprecated means please use something else instead, if I can't don't deprecate even if you consider to remove it later.

**Comment by boaks** [comment]
AFAIK, methods/interfaces which are be to removed, should be deprecated first. Right?

**Comment by sbernard31** [comment]
Yep we differ on this. My understanding : 
I think this is pretty much impossible to deprecate everything you will remove.
When you release a new Major, you can break anything (doesn't mean you must break without thinking of impact, but if needed you can). 
Sometime the code change so much that deprecation doesn't even make sense. 

So I think this is a good approach when it's possible to say to user :warning:  "this is not the recommended way now, so please use this instead".

But saying "this will be removed", but not being able to change the code to prepare this removing sounds not useful to me. (just frustrating because I need to add ugly suppress warning)

**Comment by boaks** [comment]
My intention was to provide a comment with the deprecation in order to assist in migration. 
But, yes, if it is not required to deprecate something before removing, the `PskSecretResultHandler` may not be considered to be deprecated.

**Comment by rogierc** [comment]
You could maybe create a v3 migration guide file, where you can put that kind of comment?

**Comment by boaks** [comment]
My hope is, that migrating to v3 is first to migrate to 2.5, then you either do, what the deprecation comment recommend using the 2.5, or you know what to do, when migrating to v3.
I guess, for the most, there is not too much to do at all.

**Comment by sbernard31** [comment]
From https://github.com/eclipse/californium/issues/1451#issuecomment-730231995, 1) 2) 3) and 4) should be "fixed" in cf-2.6.0.
