### ISSUE TITLE
Question: how to set Options on CoAP response

### ISSUE THREAD

**Issue by kentsimp** [eclipse/californium#1462]
Hi,

I am trying to modify/set the request options (block 2) in my CoAP endpoint. I want to set the szx, num etc in response to an incoming request.

I am using the following lib version
```
<dependency>
	<groupId>org.eclipse.californium</groupId>
	<artifactId>californium-core</artifactId>
	<version>2.4.1</version>
</dependency>
```

Below is my (simplified) code snippet, where I try to set the block2 option on the passed in coap exchange opbject:

```
@Override
public void handleGET(final CoapExchange exchange) {
	// read the options from block 2
	final BlockOption block2Options = exchange.getRequestOptions().getBlock2();
	final int szx = block2Options.getSzx();
	final int blockNumber = block2Options.getNum();

	final BlockDataDto blockData = this.someFunctionThatGetsMeABlock(blockNumber, szx);

	// build the response
	final int newSzx = size2Szx(blockData.getBlockData().length);

	exchange.getRequestOptions().setBlock2(newSzx, blockData.isMoreBlocks(), blockNumber);
	LOGGER.debug("Request options (block 2): {}", exchange.getRequestOptions().getBlock2());

	exchange.respond(ResponseCode.CONTENT, blockData.getBlockData());
}
```

Below is a tcpdump of the request/response, also attaching an image below with some colour coding/decoding of the message.

```
15:17:14.504598 IP6 fe80::f003:5d26:2618:6b7b.5683 > Khadas.5683: UDP, length 38
        0x0000:  6000 0000 002e 1140 fe80 0000 0000 0000  `......@........        REED IPAdr
        0x0010:  f003 5d26 2618 6b7b fe80 0000 0000 0000  ..]&&.k{........        Followed by Host IPAdr
        0x0020:  6425 0391 625f 23cd 1633 1633 002e 076a  d%..b_#..3.3...j
        0x0030:  4201 6068 7a9d b466 696c 65c1 04ff 6669  B.`hz..file...fi
        0x0040:  6c65 6e61 6d65 3d66 696c 652f 7770 6373  lename=file/wpcs
        0x0050:  2d65 6672 3332                           -efr32
15:17:14.507268 IP6 Khadas.5683 > fe80::f003:5d26:2618:6b7b.5683: UDP, length 263
        0x0000:  600a 6f98 010f 1140 fe80 0000 0000 0000  `.o....@........        Host and REED IPAdr
        0x0010:  6425 0391 625f 23cd fe80 0000 0000 0000  d%..b_#.........
        0x0020:  f003 5d26 2618 6b7b 1633 1633 010f 9c40  ..]&&.k{.3.3...@
        0x0030:  6245 6068 7a9d ffeb 17a6 0308 0000 0000  bE`hz...........        Payload separator + File contents
        0x0040:  0000 0300 0000 00f4 0a0a f41c 0000 0002  ................        starts EB 17 A6..
        0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0060:  0000 0000 0000 0000 0000 00fd 0303 fdb0  ................       
        0x0070:  0000 0000 0000 0040 9a00 2029 1006 0031  .......@...)...1       
        0x0080:  5e00 0035 5e00 00a7 0a02 0200 0100 0004  ^..5^...........
        0x0090:  180f ac50 2acc 0000 0000 0000 0000 0000  ...P*...........
        0x00a0:  0000 0000 0000 0000 0000 0098 6408 0000  ............d...
        0x00b0:  0000 0000 0000 0000 0000 0000 0000 00ff  ................
        0x00c0:  ffff ffff ffff ffff ffff ffff ffff ffff  ................
        0x00d0:  ffff ffff ffff ff00 700f 0000 0000 0000  ........p.......
        0x00e0:  0000 00ff ffff ffff ffff ff1c 0000 0000  ................
        0x00f0:  0000 0000 0000 0000 0000 0000 0000 00f4  ................
        0x0100:  4202 20f4 4202 2040 9a00 20a0 5c09 0048  B...B..@....\..H
        0x0110:  4f08 0040 9800 2010 9800 2000 0010 0000  O..@............
        0x0120:  0000 00fd 0303 fd56 4e09 0000 0100 0040  .......VN......@
        0x0130:  9a00 2029 1006 00                        .                       and ends 29 10 06 00
```

![image](https://user-images.githubusercontent.com/10782630/100696531-a5b5e780-33f8-11eb-96db-8043960e48f2.png)

To me it looks like the token (0x7a9d) is followed directly by the payload separator (0xff), and no request options are set on the outgoing response.

Is this the correct way to set the options in response to an outgoing response?

I could find examples online for setting options for an outgoing coap client request, but nothing for processing a response exchange.

Appreciate any help you could provide.

**Comment by kentsimp** [comment]
Sorry, I think I can now answer my own question, it needs to be set like this:

```
@Override
public void handleGET(final CoapExchange exchange) {
	// read the options from block 2
	final BlockOption block2Options = exchange.getRequestOptions().getBlock2();
	final int szx = block2Options.getSzx();
	final int blockNumber = block2Options.getNum();

	final BlockDataDto blockData = this.someFunctionThatGetsMeABlock(blockNumber, szx);

	// build the response
	final int newSzx = size2Szx(blockData.getBlockData().length);

	exchange.getRequestOptions().setBlock2(newSzx, blockData.isMoreBlocks(), blockNumber);
	LOGGER.debug("Request options (block 2): {}", exchange.getRequestOptions().getBlock2());

	final Response response = new Response(ResponseCode.CONTENT);
	response.setPayload(blockData.getBlockData());
	response.getOptions().setBlock2(newSzx, blockData.isMoreBlocks(), blockNumber);
	exchange.respond(response);
}
```

**Comment by boaks** [comment]
There is a pitfall, if you run this in a public network environment:

Don't just use the blocksize requested, it must be the minimum of the requested and configured.
See [Californium Wiki - Security Links](https://github.com/eclipse/californium/wiki/Links-to-CoAP-or-DTLS-1.2-research-information#security), the links 2-4 in that section.

If you just use the requested blocksize, then your node my be misused for amplification attacks.

**Comment by boaks** [comment]
I'm not sure, what you really want to do.

Let me first start:

Wireshark knows CoAP! If you [capture your traffic](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) as described here, you may select the messages of interest, export them, zip them and upload them (all described in our wiki). It's much easier to see the CoAP information in WireShark then to decoded it on your own.

Californium offers two ways for blockwise transfer (RFC 7959):
- transparent (californium does it for you)-
- pass-through (you may do all the exotic stuff you want)

The first is mainly for resources, which are just "little too large", in order the handle them easily. e.g. if your PMTU limits you to e.g. 1k but some of your resources have up to 4k, this modes helps you to transfer also these larger resources without to much pain. To do so, you setup Californium's `NetworkConfig` using "Californium.properties".

`MAX_RESOURCE_BODY_SIZE`:  0: pass-through is enabled, >0, transparent, limited to this maximum resource size.
`MAX_MESSAGE_SIZE`: the maximum message size, if the message gets larger, then blockwise is used. 
`PREFERRED_BLOCK_SIZE`: the preferred blocksize of the peer. The actual blocksize is negotiated and may be smaller.

The `pass-through` is intended, if some "special" requirements must be fulfilled.
E.g. "very large" payload, as usual for firmware downloads. With that, pause and resume on the client side may be required. For the server-side, that's normally not that issue. And though Californium is more used for the server-side, that `pass-through`is also not that mature as the transparent mode.

If you provide more infos about your plans, you may get more details and hints. 
There is also a [simple file server](https://github.com/eclipse/californium/tree/master/demo-apps/cf-simplefile-server) to start with.
