### ISSUE TITLE
update junit 4.13.1

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1471]
In junit 4.13.1, [ExpectedException.none()](https://github.com/junit-team/junit4/issues/1684) has been deprecated.

There are several options to go:

- switch from java 7 to java 8 in order to use lambdas.
- use a "wrapper factory"
- use different java version only for tests (I didn't find a way to do that for maven. maybe someone else knows how to do that.)

See also PR #1470 

Any opinions?

**Comment by sbernard31** [comment]
:warning:  I didn't look at this deeper. :warning: 

> use different java version only for tests (I didn't find a way to do that for maven. maybe someone else knows how to do that.)

I don't like so much this idea. 

> use a "wrapper factory"

I'm not sure what you have in mind, exactly

So possible way : 
1. keeping the warning waiting we decide about java7 or java 8 (and then we will see)
2. This is also possible to use `assertThrows` without lambda.

**Comment by boaks** [comment]
> I'm not sure what you have in mind, exactly

That's the proposal from the junit community.
Basically it wraps the deprecated `ExpectedException.none()` and with that, requires only to suppress the warning there.

**Comment by boaks** [comment]
> This is also possible to use assertThrows without lambda.

FMPOV, that will be a lot of typing.

**Comment by sbernard31** [comment]
> Basically it wraps the deprecated ExpectedException.none() and with that, requires only to suppress the warning there.

I'm not against this idea.

**Comment by rogierc** [comment]
> switch from java 7 to java 8 in order to use lambdas 

[Mule CoAP Connector](https://github.com/teslanet-nl/mule-coap-connector) developments focus on Mule 4 which abandoned java 7. No objections to java 8 from there.

**Comment by boaks** [comment]
I adapted the unit tests using `ExpectedExceptionWrapper`.
That may be replaced by test-redesign with java 8 (but not now).
