### ISSUE TITLE
should we send onResponse callback out of syncronized block in blockwise layer ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1479]
https://github.com/eclipse/californium/blob/864c58f817e2d2a403c6a7bf54e75fbc5c408dbe/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java#L871

Should this line be move out of the `synchronized` block ? or maybe there is a good reason to keep it in this sync block ?

---------------------------------

Some context which is not really needed to be able to answer to the question :sweat_smile:  :
We face a situation where we lock all threads in the coap stack.

Here is hypothesis of what maybe happened :  
When receiving a coap response we do an http call.
In some very rare circumstance we suspect this http call can never end (we guess about some socket timeout issues on our side)
This is an issue as this will stuck one thread forever. 
But in our case that was a bit worst as this happened for a response of block1 request (see above :point_up:) and so this take the `block1Transfers` lock forever. Then each time a new block1 request was create a new thread was block until no more thread was able to handle coap request.

**Comment by boaks** [comment]
Seems, that I had focused only on the block2 case.

My first impression; 
just remove the synchronized on 810 and also on 731.

A "critical section" seems to be line 768 (get==null) and 784 (create).
Maybe, adding a second "get" and put that together with the the "create" in a short synchronized block will do it.

The block2 case then do a "late check" in `requestNextBlock` on line 1128 `status.isComplete()`. I guess, that will also do a good job on `sendNextBlock` line 891.

And then test, test ...

**Comment by boaks** [comment]
Though you title "onResponse" callback:
I'm not sure, why that is then causing trouble.
FMPOV, in such callback usually nothing blocking should be executed.
If it gets complex, I hand that stuff over to other threads/executors.

(But, sure, the scope of that synchronized should be limited.)

**Comment by sbernard31** [comment]
> FMPOV, in such callback usually nothing blocking should be executed.
If it gets complex, I hand that stuff over to other threads/executors.

In a general way, I agree with this (in practice **maybe some rare case** where this could be not so true). Anyway, I think there is probably a bug in our code which are using leshan/californium. 
But searching it, I also asked myself if this synchronize block was not too large. (so this issue)

> (But, sure, the scope of that synchronized should be limited.)

:+1: 

> My first impression;
> just remove the synchronized on 810 and also on 731.
> 
> A "critical section" seems to be line 768 (get==null) and 784 (create).
> Maybe, adding a second "get" and put that together with the the "create" in a short synchronized block will do it.
> 
> The block2 case then do a "late check" in requestNextBlock on line 1128 status.isComplete(). I guess, that will also do a good job on sendNextBlock line 891.

It sounds impacting so probably deserve time to check if it works and so I understand that it will require many tests.

My first idea was just to move the critical part `upper().receiveResponse(exchange, response);` out of the block, this should be less impacting and do not deserve too much tests.

1. should I flag this issue as enhancement ? 
2. should I provide this first PR with just the "move out of the block" ?

**Comment by boaks** [comment]
See PR #1480

**Comment by boaks** [comment]
PR merged into master and 2.6.x branch.
