### ISSUE TITLE
message IDs exhausted, could not register outbound request for tracking

### ISSUE THREAD

**Issue by zhangdaopin** [eclipse/californium#1487]
2020-12-29 12:30:16.843 [CoapServer(main)#1] WARN  o.e.c.c.n.InMemoryMessageExchangeStore 226 - [LWM2M Server-coap://] cannot send message to /XX.XX.XX.XX:YYYY, all MIDs are in use
2020-12-29 12:30:16.843 [CoapServer(main)#1] WARN  o.e.c.core.network.UdpMatcher 136 - message IDs exhausted, could not register outbound request for tracking
org.eclipse.leshan.core.request.exception.SendFailedException: Request CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["1","0"]}, automatic message IDs exhausted no payload cannot be sent
        at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:106)
        at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1063)
        at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1133)
        at org.eclipse.californium.core.network.UdpMatcher.sendRequest(UdpMatcher.java:137)
        at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:981)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:231)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:107)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:333)
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
        at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendRequest(ExchangeCleanupLayer.java:63)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:188)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:87)
        at org.eclipse.californium.core.network.CoapEndpoint$8.run(CoapEndpoint.java:829)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: automatic message IDs exhausted
        ... 15 common frames omitted

**Comment by zhangdaopin** [comment]
There is no problem if only one device is connected; however, when a large number of devices are registered at the same time, the MID seems to be exhausted, what should I do? ? ?

**Comment by zhangdaopin** [comment]
We use californium-2.4.1
EXCHAGE_LIFETIME = 10000

**Comment by boaks** [comment]
> There is no problem if only one device is connected; however, when a large number of devices are registered at the same time, the MID seems to be exhausted, what should I do? ? ?

I'm not sure, how you setup the endpoints.

The intention of the `MessageIdProvider`is to keep track of the used MID per destination. But in your case, it seems to be different. Can you provide more information about the used `MessageIdTracker` in `InMemoryMessageIdProvider` and the destinations you're using?

**Comment by boaks** [comment]
I guess, there are many `CoapClient`s used, all sharing the same default `CoapEndpoint`. In spite of the class name, a `CoapClient` is only a facade for the `CoapEndpoint`. If you want to use "many clients", you need to prepare many `CoapEndpoint` and apply them to each client by calling `CoapClient.setEndpoint(Endpoint endpoint)`.

How many client do you plan to use?
If it's about 1000-2000, it's recommended to share the ExecutorServices (see `CoapEndpoint.setExecutors`).

**Comment by zhangdaopin** [comment]
> > There is no problem if only one device is connected; however, when a large number of devices are registered at the same time, the MID seems to be exhausted, what should I do? ? ?
> 
> I'm not sure, how you setup the endpoints.
> 
> The intention of the is to keep track of the used MID per destination. But in your case, it seems to be different. Can you provide more information about the used in and the destinations you're using?`MessageIdProvider``MessageIdTracker``InMemoryMessageIdProvider`

yes,I used Leshan's client to do the test, and started 10 clients to initiate registration at the same time;
but,Californium.properties  ---> 'MID_TACKER=NULL' (Is it useful to modify this parameter?)

**Comment by boaks** [comment]
That is even more mystic to me;

> `MID_TACKER=NULL` 

should not track the used MIDs at all ...

> started 10 clients 

10 clients is a rather small number, so it's OK to use 10 threads. Just if you want much more clients, hten it's recommended to set it up differently.

Do you start 10 java vm, each with one Leshan client?
Or 1 java vm, wiht 10 leshan clients? (I'm not sure, if that is supported by leshan).

**Comment by boaks** [comment]
The `InMemoryMessageIdProvider` returns `Message.NONE`, if the `MAX_ACTIVE_PEERS` are reached.

I'm still confused about your setup:
Do you also use a Leshan server? Does the error occur on the leshan client? Or server?

If it's the server side, I would check the value of `MAX_ACTIVE_PEERS` in the server "Californium.properties".

Maybe you start the server and client in the same directory an maybe Leshan simply uses the "Californium.properties" there. That's somehow sub-optimal, in my opinion it may be better to setup clients and server with their specific "Californium.properties". So, if you start the server and clients from the same directory or if you "reuse" the "Californium.properties", I would propose, that you start the clients and the server from different directories with different "Californium.properties".

**Comment by zhangdaopin** [comment]
@boaks I check the value of MAX_ACTIVE_PEERS in the server "Californium.properties". MAX_ACTIVE_PEERS is equal to 10, I changed it to 100, and connected to 10 clients (10 VMs) at the same time, and the "message IDs exhausted, could not register outbound request for tracking" exception no longer appeared;
Maybe I need more observation and testing. . .

But I changed these five parameters, and I am not sure which parameter actually worked. It will take some time to test...
![image](https://user-images.githubusercontent.com/24818052/103396735-c09e8780-4b6f-11eb-83f0-97b025160814.png)

**Comment by boaks** [comment]
> exception no longer appeared;

Great news! I will got to change that error message for Californium 3. to report that directly.

> Maybe I need more observation and testing. . .

That's always a very good idea. Each setup is different ...

1. `MAX_ACTIVE_PEERS` is used to limit the consumed resources in order to protect the java-vm. Though there are not too much resources used per peer, values below 10000 have negative effects in my experience :-).
2. PROTOCOL_STAGE_THREAD_COUNT in my experience this number is about the number of available cores. Smaller number are mainly used for clients (there it is 1), using larger number should be tested, if that results in the wanted behavior/performance. More doesn't mean faster, at last, not always.
3. EXCHANGE_LIFETIME that is important for the deduplication. Only within that time, retransmissions are detected. FMPOV 2470 is too short, that will result in reprocessing retransmissions. I would recommend to use values not smaller than 24700.
4. RESPONSE_MATCHING using PRINCIPAL is intended for DTLS servers, for LwM2M that is mainly the LwM2M server.
5. MID_TRACKER GROUPED is the one, Californium uses most, NULL the one Leshan used most. 

The values for EXCHANGE_LIFETTIME, MID_TRACKER, and DEDUPLICATOR are used to "fine tune" the deduplication and congestion control. As long as your use-case is communication of "many rather slow peers", it should work without too much changes. Only if you want to use only a few, but very high-speed peers, then you need to know what you do. And to test your setup.

So, adjust the EXCHANGE_LIFETIME to a larger value, and test, if that setup works for you.
(If you want, just give a hint, what your target scenario (number of peers, speed of peers) looks like, then I will provide more hints.)

**Comment by zhangdaopin** [comment]
@boaks Sorry, I may bother you again, this is another problem, or it is caused by the modification of the parameters described above;
2021-01-01 00:49:37 (East Eighth District), my service suddenly no longer accepts data from port 5683, causing the device to retransmit continuously until it fails.
![image](https://user-images.githubusercontent.com/24818052/103502010-e509a500-4e8a-11eb-8cd2-f0af99511b03.png)
（The screenshot is that I used Wireshark parsing to grab the traffic packets on port 5683）

Until 2020-01-01 00:51:51 (East Eighth District), my service was receiving these retransmission messages, which caused abnormalities and service paralysis. . .
I'm starting to investigate this problem in the californium source code. Can you give me some inspiration? Thank you very much. . .

**Comment by boaks** [comment]
> Sorry, I may bother you again

You're welcome.

I see 5 requests with pauses between 5s to 45s
And, with a delay of 45s, 3 ACKs.

So: 
if your server is "overstressed/overloaded", that is not too unusual. In that case, some messages may get drop and some are answered with delay.

If you use a unix-like OS, you may try to use [unix-health](https://github.com/eclipse/californium/blob/master/cf-utils/cf-unix-health/src/main/java/org/eclipse/californium/unixhealth/NetStatLogger.java). That logs additional information about your network.

```sh
DEBUG [NetStatLogger]: udp network statistic:
    udp OutDatagrams :        2 (889102781 overall).
    udp InDatagrams  :       14 (887245991 overall).
    udp SndbufErrors :        0 (       0 overall).
    udp RcvbufErrors :        0 (11017084 overall).
    udp InErrors     :        0 (11017084 overall).
    udp InCsumErrors :        0 (       0 overall).
    udp NoPorts      :        0 (       0 overall).
```

Just create a `NetStatLogger` and call  `NetStatLogger.dump()`.
Enable the logger in your logging config, e.g. if logback is used, add

```xml
<logger name="org.eclipse.californium.unixhealth.NetStatLogger" level="DEBUG" additivity="false">
    <appender-ref ref="STDOUT" />
</logger>
```

to the used `logback.xml`

That will not fix your issue, but you may see the amount of messages dropped in the local network stack of your server. In my experience that's caused by overloaded servers.

**Comment by zhangdaopin** [comment]
> > Sorry, I may bother you again
> 
> You're welcome.
> 
> I see 5 requests with pauses between 5s to 45s
> And, with a delay of 45s, 3 ACKs.
> 
> So:
> if your server is "overstressed/overloaded", that is not too unusual. In that case, some messages may get drop and some are answered with delay.
> 
> If you use a unix-like OS, you may try to use [unix-health](https://github.com/eclipse/californium/blob/master/cf-utils/cf-unix-health/src/main/java/org/eclipse/californium/unixhealth/NetStatLogger.java). That logs additional information about your network.
> 
> ```shell
> DEBUG [NetStatLogger]: udp network statistic:
>     udp OutDatagrams :        2 (889102781 overall).
>     udp InDatagrams  :       14 (887245991 overall).
>     udp SndbufErrors :        0 (       0 overall).
>     udp RcvbufErrors :        0 (11017084 overall).
>     udp InErrors     :        0 (11017084 overall).
>     udp InCsumErrors :        0 (       0 overall).
>     udp NoPorts      :        0 (       0 overall).
> ```
> 
> Just create a and call .
> Enable the logger in your logging config, e.g. if logback is used, add`NetStatLogger``NetStatLogger.dump()`
> 
> ```
> <logger name="org.eclipse.californium.unixhealth.NetStatLogger" level="DEBUG" additivity="false">
>     <appender-ref ref="STDOUT" />
> </logger>
> ```
> 
> to the used `logback.xml`
> 
> That will not fix your issue, but you may see the amount of messages dropped in the local network stack of your server. In my experience that's caused by overloaded servers.

It’s a good idea. 
Based on your reply, I thought about it carefully. It should have nothing to do with the network. It seems that the message on my server is blocked. After checking the code, I found that when I was processing the message, there was a The method is modified by **synchronized**. 
However, the execution of this method may time out due to waiting for the response, resulting in waiting for about 30s, then the data coming in from port 5683 will be queued for processing. . . Caused an abnormal situation in the capture file, I have made changes and look forward to good results ^_^;; 
Thanks again for your reply！

**Comment by boaks** [comment]
> After checking the code, I found that when I was processing the message, there was a The method is modified by synchronized.

Just to mention: 

Californium  was developed over the time by many different people. AFAIK, all callbacks must be handled in a "non-blocking" way. Usually, if more processing is required, it's a good idea to execute that in a job of an other executor.

> waiting for the response

If that happens in a callback, that may cause [deadlocks](https://github.com/eclipse/leshan/issues/827)!

**Comment by boaks** [comment]
FMPOV, the questions are answered. If you have new ones, just open a new issue.
