### ISSUE TITLE
CoapClient.ping() should use EmptyMessage instead of empty Request

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#149]
`CoapClient.ping()` currently sends the ping via `Endpoint.sendRequest()` using a CON `Request` with a `null` code. This requires special handling of the `null` value. It would be better to enforce a non-null code in `Request` and sending an `EmptyMessage` for doing the ping.

**Comment by sophokles73** [comment]
@mettke,

isn't this something for you? IIRC you offered to work on this, didn't you?

**Comment by mettke** [comment]
Yes - waiting for #134 to be Merged.

**Comment by mettke** [comment]
@sophokles73 I've added a Commit with the first steps

**Comment by boaks** [comment]
After understand californium better, I think in the meantime, that the "empty message" ping should stay being an request. The other flavour would require too much changes.
