### ISSUE TITLE
pom.xml of element-connector sub module still contains scm and repository infos 

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/californium#15]
The pom of element-connector still contains (old?) scm configuration and duplicates repositories of parent pom. Is this leftover from moving to multi module project or was this done intentionally?

    <scm>
		<developerConnection>scm:git:https://github.com/eclipse/californium.element-connector.git</developerConnection>
		<url>https://github.com/eclipse/californium.element-connector</url>
		<tag>HEAD</tag>
	</scm>

    <repositories>
		<repository>
			<id>eclipse_snapshots</id>
			<name>Eclipse Snapshots</name>
			<url>https://repo.eclipse.org/content/repositories/snapshots/</url>
		</repository>
		<repository>
			<id>eclipse_releases</id>
			<name>Eclipse Releases</name>
			<url>https://repo.eclipse.org/content/repositories/releases/</url>
		</repository>
	</repositories>

**Comment by sophokles73** [comment]
This is a left-over. I will remove it ...

Did this cause any trouble for you, though?

Thanks for pointing it out :-)

**Comment by DanielMaier-BSI** [comment]
No, did not cause any problem. I just stumbled over it. 

But I have another point that causes problems for me:

There is still the element-connector in dependency-management section in parent pom. In contrast the other sub modules are referenced with ${project.version} in dependency section of child modules. I think this dependency management entry is also a left over? Or does it make sense to use another version than ${project.version}?

This dependency management entry of own sub module causes problems with maven release plugin.

**Comment by sophokles73** [comment]
Oh yes, that's another left-over and surely doesn't make much sense anymore.

However, you shouldn't make your life harder than necessary by using the Maven release plugin ... ;-)

**Comment by DanielMaier-BSI** [comment]
How do you release this project? Something like this: https://axelfontaine.com/blog/final-nail.html?

**Comment by sophokles73** [comment]
yep

**Comment by DanielMaier-BSI** [comment]
Ok, thanks. 

Back to the dependency management stuff: I am not sure about his, but i would have removed the element-connector completely from dependency management. All the other sub modules are also not managed dependencies.

**Comment by sophokles73** [comment]
Since element-connector is required by all others we *pulled it up*. But you are right, we are not doing this consistently for all dependencies (which should probably improved in the future).

Can we close this issue then?

**Comment by DanielMaier-BSI** [comment]
Yes, I will close it.
