### ISSUE TITLE
Introduce hamcrest-library dependency

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#151]
For some test with Strings, I would like to add

		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-library</artifactId>
			<version>1.3</version>
		</dependency>

to the dependency of the element-connector.

Any objections?

**Comment by sophokles73** [comment]
Are you sure that you need `hamcrest-library` and `hamcrest-core` is not sufficient?

**Comment by boaks** [comment]
If you know how to do

		assertThat(tlsContext.getSessionId(), is(not(isEmptyOrNullString())));
		assertThat(tlsContext.getCipher(), is(not(isEmptyOrNullString())));

without, thean its not needed.
But please not "length()=0" or something like that. I don't like this hamcrest stuff at all, but if used, we should use it at then really at wording level.

**Comment by sophokles73** [comment]
Why don't you simply try it out?

**Comment by boaks** [comment]
Does this mean:
1. rewrite the test NOT using hamcrest-library?
Or
2. leave the test and just NOT use hamcrest-library?

1. is possible with some "calculations" instead of `is(not(isEmptyOrNullString()))`
2. reports errors (in eclipse).

I want to add the principal test and then make a PR. I think, it would be easier to discuss it there.

**Comment by sophokles73** [comment]
Just replace the string `hamcrest-library` with `hamcrest-core` in your pom.xml :-)

**Comment by sophokles73** [comment]
I can open a CQ for adding `hamcrest-library` as a test dependency. Luckily, we already thought about using it in Hono as well, so we can piggy back that CQ. I'll let you know when you can add and use the dependency ...

**Comment by sophokles73** [comment]
see [CQ 12347](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12347)

**Comment by sophokles73** [comment]
fixed on master in 47c4f586fb24e4953c38856ec40e45598f61871e
fixed on 2.0.x in a6bd2f2db10866760250d0ab8580da21405739ba
