### ISSUE TITLE
Is there a good performance test tool recommended?

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#1532]
Is there a good performance test tool recommended ?

**Comment by boaks** [comment]
I just use the `demo-apps/cf-extplugtest-client`, normally in combination with `demo-apps/cf-extplugtest-server`.
Generally it depends much on what you want to benchmark (single RTTs, throughput).

The get a first impression, try out [cf-extplugtest-server/cf-extplugtest-client](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server)

**Comment by xuzhiweiand** [comment]
thank you

**Comment by boaks** [comment]
You're welcome.
Once I find the time to work on the nio client (issue #1203), I will ping you. But I still have no time-schedule for that.
