### ISSUE TITLE
Documentation issue getRequestPayload on CoapExchange

### ISSUE THREAD

**Issue by mateusz1364** [eclipse/californium#1537]
version - 2.6.1
environment - java 11 (oracle)

Class: CoapExchange
Method: getRequestPayload()

--
After upgrade from version 1.X.X to version 2.6.1 my application throw null pointer exception after action on result (byte[]) of method getRequestPayload().

I suggest add to documentation info about nullable method or change return type to Optional<byte[]>. This situation not happend on versions 1.X.X - method return empty array.

**Comment by boaks** [comment]
Thanks for reporting this. I will adapt the javadoc accordingly.

I'm not sure, in which situation you have been faced that `null`? My first impression is, that there is no such difference in the "payload". Do you use "USE_MESSAGE_OFFLOADING"?

**Comment by boaks** [comment]
Hm on a second view, "USE_MESSAGE_OFFLOADING" is not related to a `null`.

Are you aware of the ["intended payload"](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L352) feature?

(Anyway, the javadoc should contain the `null`).

**Comment by boaks** [comment]
@mateusz1364 

If possible, a feedback for PR is welcome.
As I wrote, I'm not sure, if the payload handling is really changed from 1x.y to 2.6.1, except of the "intended payload" feature. I would appreciate, if you can give more details about the set where this error occurred to ensure, that this is not an additional unaware change.

1. which request do you use?
2. does the null occur on the server or client side?
3. before or after the response is received/send?

**Comment by mateusz1364** [comment]
@boaks Yes, of course. Thank you for quickly response and docs change.

The error appeared in server side on specify endpoint (handlePOST, ConcurrentCoapResource). Data generating by client side is the same but i see the difference by server side (comparing versions exactly 1.0.4 to 2.6.1). The first thing after calling handlePOST is check payload by method getRequestPayload(). If this information is helpful - am extending ConcurrentCoapResource now, earlier CoapResource.

**Comment by mateusz1364** [comment]
I am using default settings from Californium.properties

**Comment by boaks** [comment]
Thanks, that helps!

I guess, the request is not sent with payload, so

[DataParser - no payload](https://github.com/eclipse/californium/blob/1.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/serialization/DataParser.java#L166)

that has changed to `null`. 

My feeling:
- For 2.6.x, I don't think, the behavior should be changed. 
- For 3.0.x, I will check to initialize/use `Bytes.EMPTY`, though it seems there is no difference in RFC 7252 for `null` or empty payload. (RFC 7252 "If present and of non-zero length, it is prefixed by a
fixed, one-byte Payload Marker (0xFF)").
