### ISSUE TITLE
Missing license on element connector tcp

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#154]
Some classes in the element-connector tcp implementations have no license.
Could this be added by the initial contributor?

**Comment by sophokles73** [comment]
fixed on master in 4d9c28ae7523ec325652f91e6a6fa521bbf7ae63
fixed on 2.0.x in cbfd74a9d7b41c48a06391c3a8be37cd2c47dcf8

**Comment by boaks** [comment]
Do we have license in the test also?
If, yes, its missing in the tcp/tls test also.

**Comment by sophokles73** [comment]
Hope this is it, now ...
Fixed on master in 921e2d7595a8969118dc940c30ff7019ba185ca4
Fixed on 2.0.x in 5f3a50736a379ca80e9d6872addf29b60e73ac95
