### ISSUE TITLE
bad problems

### ISSUE THREAD

**Issue by superJack2222** [eclipse/californium#1551]
This error occurred when I upgraded the SDK. How to resolve this error
![image](https://user-images.githubusercontent.com/19429672/109253001-c344f280-7829-11eb-9b96-48417be4afe2.png)

**Comment by boaks** [comment]
Generally, that reports, that you send a response, but the exchange is already completed (mean, the response have already been sent). From the stacktrace it seems, that the "separate response". 

So, do you know the "application context", where this response is sent?
Is it "required" from the "application context" to resend the response?
Or what is the intention of sending more than one response?
Is it related with  a "Observer/Notify" [RFC7641](https://tools.ietf.org/html/rfc7641)?

(Just for the case, it makes a difference: Do you use now 2.6.0 or 2.6.1? Or a older version?)

**Comment by boaks** [comment]
Did you found the time to investigate, why it seems, that two responses should be send?
Without more details, it's not possible to help solving that error.

Just as additional hint:
Some implementations are using a "different messaging" toward the northbound (towards application or next layer). And sometimes that "northbound messaging" also repeats messages and so may cause your error, if such a "repeated northbound messaging" triggers to send a coap-response. But this is just a very nibulous guess.

**Comment by boaks** [comment]
PR #1563 fixes some rare corner cases on the coap-server side using notifies. Without that fix, exceptions as reported above may have occurred, which are now fixed. But there may be many other causes for such exceptions, without more specific details of your case, it stays unclear, if the fixes will help or not.

(See also issue #1565 )

**Comment by boaks** [comment]
Any news?

**Comment by boaks** [comment]
@superJack2222 

Don't hesitate to comment on this issue, if you have any update.

**Comment by boaks** [comment]
@superJack2222 

Are you still facing this issue?
I plan to release Californium 3.0.0 in a few couple of weeks. If there is something to change, now would be a good point in time. Not that it's later not impossible, but now the API could be adapted more easily.
