### ISSUE TITLE
Californium does not support standard coap codes for ping 7.02 and pong 7.03

### ISSUE THREAD

**Issue by joe-pulse** [eclipse/californium#1564]
* Tag: 2.6.1 (i.e. latest)
* Protocol: TCP

## Problem description

There seems no support in Californium for the ping/pong messages defined by CoAP RFC 8323:
* Ping = request code 7.02
* Pong = response code 7.03
See https://tools.ietf.org/html/rfc8323#section-5.4

Currently, if Calfornium receives a PING sent by another CoAP stack, `DataParser.parseMessage` throws an "illegal message code" exception.

Because code 7.02 lies outside `REQUEST_CODE_LOWER_BOUND, REQUEST_CODE_UPPER_BOUND` and `RESPONSE_CODE_LOWER_BOUND, RESPONSE_CODE_UPPER_BOUND` defined in `californium.core.coap.CoAP`.

This causes significant problems communicating with other CoAP stacks.

**Comment by boaks** [comment]
Yes, the TCP implementation RFC 8323 is still very experimental and more or less based on a early version of that RFC.

Do you have interest in evolving it?

My interest in CoAP over TCP is limited. See [Next major version 3.0 - About CoAP over TCP / RFC 8323](https://github.com/eclipse/californium/issues/1469#issuecomment-745183730) and issue #1488.

**Comment by joe-pulse** [comment]
Thanks for the reply. Sure, we have a fairly conservative fix that simply forwards the 7.02 pings to the application layer as Requests, and allows the application to handle them. Will submit a PR!

**Comment by boaks** [comment]
Please obey [CONTRIBUTING](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md).

You will mainly need a [ECA](http://www.eclipse.org/legal/ECA.php), using the same e-mail address as used for "signing" the commit.

**Comment by boaks** [comment]
Just to ask:

Do you want to apply this for 2.6.x? If so, is it possible that you give us/me your planed time-schedule?

In order to sync with an upcoming leshan milestone release, I scheduled a 2.6.2 bugfix release for next Tuesday. If required, that could also be postponed for 1-2 days.

**Comment by boaks** [comment]
Uups, sorry, I was mislead. 
Though that change will be an API extension, it requires a minor version. That would trigger a new review (our last is more than a year ago). So, please, only plan for 3.0 .

**Comment by boaks** [comment]
@joe-pulse 

Any news on this?

**Comment by boaks** [comment]
@joe-pulse 

Don't hesitate to create a PR, if you're still on this issue.
