### ISSUE TITLE
Insecure cipher algorithm and hash functions

### ISSUE THREAD

**Issue by xingweitian** [eclipse/californium#1590]
# Please provide basic issue information

Issues may be answered much faster, if you provide more details ahead!

* branch your faced the issue. Currently 
   * (1.0 is the previous release, usually no bugfixes are applied)
   * (1.1 is the previous master, no plans to continue this)
   * 2.6.x is the current release,
   * and master (previous 2.0) is the development branch and our upcoming release!
* If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
  commit your using
* If your issue is related to your own snippet, please provide that
* If you have logs, please provide them
* If you have tcpdump captures (wireshark), please provide them.

(See https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information .)

Hi there, we found that the following places using the insecure cipher and hash functions:

```
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:773: error: [algorithm.not.allowed] Algorithm: MD5 is not allowed by the current rules
		HMAC_MD5("HmacMD5", "MD5",16, 0, 0),
		                    ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:774: error: [algorithm.not.allowed] Algorithm: SHA-1 is not allowed by the current rules
		HMAC_SHA1("HmacSHA1", "SHA-1", 20, 8, 64),
		                      ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:923: error: [algorithm.not.allowed] Algorithm: AES/CCM is not allowed by the current rules
		AES_128_CCM_8(AeadBlockCipher.AES_CCM, CipherType.AEAD, 16, 4, 8, 8), // explicit nonce (record IV) length = 8
		                             ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:924: error: [algorithm.not.allowed] Algorithm: AES/CCM is not allowed by the current rules
		AES_256_CCM_8(AeadBlockCipher.AES_CCM, CipherType.AEAD, 32, 4, 8, 8), // explicit nonce (record IV) length = 8
		                             ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:925: error: [algorithm.not.allowed] Algorithm: AES/CCM is not allowed by the current rules
		AES_128_CCM(AeadBlockCipher.AES_CCM, CipherType.AEAD, 16, 4, 8, 16), // explicit nonce (record IV) length = 8
		                           ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CipherSuite.java:926: error: [algorithm.not.allowed] Algorithm: AES/CCM is not allowed by the current rules
		AES_256_CCM(AeadBlockCipher.AES_CCM, CipherType.AEAD, 32, 4, 8, 16), // explicit nonce (record IV) length = 8
		                           ^
/home/xwt/IdeaProjects/californium/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CCMBlockCipher.java:49: error: [algorithm.not.allowed] Algorithm: AES/ECB/NOPADDING is not allowed by the current rules
	public static final ThreadLocalCipher CIPHER = new ThreadLocalCipher(CIPHER_NAME);
	                                                                     ^
```

**Comment by boaks** [comment]
Yes, security code scanner may report that.

What is really used for encryption (and not only for logging, that a other peer want's to negotiate something not supported nor recommended) is defined by the available cipher suites and the signature and hash-algorithms.
For the cipher suite Californium offers therefore the "recommended", see [DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1473). The [default signature and hash-algorithms](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/SignatureAndHashAlgorithm.java#L240) contains SHA256_WITH_ECDSA (mandatory for coap) and SHA256_WITH_RSA (seems to be required for "lets encrypt", but only for chain certificates, not for node-certificates!). Additionally Californium offers a "recommended" feature also for ECC groups/curves, DtlsConnectorConfig](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1491).

With that, I don't see, the "not recommended" algorithms are selected, except someone configure scandium to sue them.

About: SHA1
That's unsecure for mid/long term signatures. For MAC the issues is muss smaller. Though using SHA256 is easy, we don't recommend to use`TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`. But, if some requires that, I don't see a reason for removing that.  

About: "AES/ECB/NOPADDING" 
Nice, and demonstrates the limits of  security code scanner :-). The class name CCM should give enough information for a short investigation with the outcome, that AESCCM AESGCM and AESCBC are all based on ECB. Though Californium implemented AESCCM for jvms, which don't support that direct, we use the ECB to build CCM.

Hope that answers you question.

**Comment by xingweitian** [comment]
Hi @boaks, thanks for the quick response!

Overall, I think the static analysis tool does the right thing --- reporting the potential insecure usage. For the intentional use of insecure algorithms, like building CCM from ECB, it is easy to suppress the warnings from the static analysis tool. For the "not recommended" algorithms, I did not see documents in the source code indicate them as insecure. The static analysis tool reminds us of the existence of insecure algorithms so that the maintainer can choose how to deal with them. At least we can document them as "insecure and not recommended algorithms". We cannot expect all our developers and users are crypto experts, right?

**Comment by boaks** [comment]
> We cannot expect all our developers and users are crypto experts, right?

I expect the none-experts not even to read the javadoc! At least, that's my impression of the last years.

> Overall, I think the static analysis tool does the right thing --- reporting the potential insecure usage. 

As hints, maybe.
But they easily mix-up the none-experts, because the messages of the scanner usually don't include the trade-offs. Using SHA-1 as MAC is not that bad, it's just in almost all cases easy to use SHA256, which is then better. But that doesn't make SHA-1 as MAC generally insecure. It's more "not  recommended".    
I would not "force" someone to roll-out a firmware update just to switch the MAC from SHA1 to SHA256. If the firmware update is anyway considered, then it may be a good idea to switch. But again "not recommended" is not "insecure".

> For the intentional use of insecure algorithms, like building CCM from ECB, it is easy to suppress the warnings from the static analysis tool.

I don't get that. There are many tools, even online tools. I'm not aware, that there is a common way to amend a hint to wrong reports. I can add some javadoc, e.g. "AES CCM is AES CCM, not the reported AES ECB", but the tools will still report the wrong hits. And some may get also uncertain about such comments.
If you know the way how to tell the tool you used about wrong security issues, let me know. 
(If you like, a contribution/PR with that is welcome.)

**Comment by xingweitian** [comment]
I don't think there is a common way to avoid warnings from all the security tools... Usually, there should be only one or two static analysis tools running in your CI. So, it will really depend on which tool you are using to scan your code.

For example, our insecure algorithm checking is built on [the Checker Framework](https://github.com/typetools/checker-framework), which offers pluggable type checking for java. If you use this tool, we provide a `@SuppressWarnings` annotation to avoid false positives. Just insert it into the code location where reports a false positive. Here is a more detailed description: https://checkerframework.org/manual/#suppressing-warnings

Other tools, like error prone and findbugs, also have `@SuppressWarnings` annotations. For security tools leveraging java annotations, annotation aliasing of `@SuppressWarnings` can be seen as a common way to avoid wrong report. The Checker Framework supports the alias of this annotation in other tools. So if you use `@SuppressWarnings` from error prone, it can be detected correctly by the Checker Framework.

I would be happy to open a Pull request inserting `@SuppressWarnings` to avoid such warnings in the future.

**Comment by boaks** [comment]
> I would be happy to open a Pull request inserting @SuppressWarnings to avoid such warnings in the future.

Sounds great! 
Please check [CONTRIBUTING](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md).

**Comment by boaks** [comment]
@xingweitian 

Are you still consider to contribute it? If not, I would prefer to close this issue.

**Comment by xingweitian** [comment]
Hi @boaks, sorry for the late response... I will try to open a PR within this week.

**Comment by boaks** [comment]
Great!

Just to say: it's never too late :-), as "after a release is before the next release".

**Comment by boaks** [comment]
Is it OK to close this issue? As I wrote, your contribution will always be welcome.

**Comment by boaks** [comment]
Just to mention:
I plan to release 3.0.0-RC1 in August. 
If you still plan to contribute something, please do so.
