### ISSUE TITLE
Coapclient status error code by  using CrossProxyExample2

### ISSUE THREAD

**Issue by Asemn** [eclipse/californium#1602]
Hello dear community ,

I am sending   a Json-file  from a coap client to  a http Backend  interface. I  have tested  it  with a httpclient and I can receive a 200 Status code which are sending back when the request is successfully processed. But I am  doing the test  now  with a Coap client and the **CrossProssyExample2** . The Cross Proxy example is up. And I am trying  to get the status code on the Coap client side with the following implementation :

URI  uri = new URI("coap://127.0.0.1:5683/coap2http/http://127.0.0.1:9090/post");
                        CoapClient client = new CoapClient (uri);
                        client.useCONs();
                        CoapResponse response =  client.post(json, MediaTypeRegistry.TEXT_PLAIN);
                        if(response == null ){
                            System.out.println("out");
                        }else{
                            System.out.println("code:"+response.getCode());
                        }
Please should I have to set any other parameters  on  the CoapClient  ? 
Thanks

**Comment by boaks** [comment]
I'm not sure, what you did exactly.
Did you enable the logging in the proxy2? If yes, what is printed in that logs?
Did you enable the logging in the coap-client? If yes, what is printed in that logs?
At least you have your own `System.out.println`, what is printed with that.

Some more details:
How large is you "json"? 
Does your http server ignore the content-type? You send TEXT_PLAIN, do you use that also for the direct http-client?
Does the proxy send a http-request to the http server at all?

**Comment by boaks** [comment]
> "coap://127.0.0.1:5683/coap2http/http://127.0.0.1:9090/post"

I guess, this is a URL from other proxies/examples? Maybe the previous proxy before proxy2?
If so, consider to read [proxy2](https://github.com/eclipse/californium/tree/master/californium-proxy2).

**Comment by boaks** [comment]
See also [ExampleProxy2CoapClient](https://github.com/eclipse/californium/blob/master/demo-apps/cf-proxy2/src/main/java/org/eclipse/californium/examples/ExampleProxy2CoapClient.java#L103). And please, **don't** use the deprecated way using CoAP and Proxy URI together. Just setup the proxy as destination and the use the option as shown in the example.

**Comment by boaks** [comment]
```java
AddressEndpointContext proxy = new AddressEndpointContext(new InetSocketAddress("127.0.0.1", 5683));
Request request = Request.newPost();
request.setDestinationContext(proxy);
request.setProxyScheme("http");
request.setURI("coap://127.0.0.1:9090/post"); // coap: will be overwritten by proxy-scheme, http:
request.setPayload(json);
CoapClient client = new CoapClient();
CoapResponse response = client.advanced(request);
```

try out that example :-). 
Using the standardized forwarding-proxy is much easier as implementing and using a "specialized reverse proxy".

**Comment by Asemn** [comment]
By trying  the followings examples with the  BasicforwardingProxy2  and also with CrossexampleProxy2  I get the  Response_code  Error 4.02. 

**Client :**  
AddressEndpointContext proxy = new AddressEndpointContext(new InetSocketAddress("127.0.0.1", 5683));
Request request = Request.newPost();
request.setDestinationContext(proxy);
request.setProxyScheme("http");
request.setURI("coap://127.0.0.1:9090/post"); 
request.setPayload(json);
CoapClient client = new CoapClient();
CoapResponse response = client.advanced(request);
System.out.println("code:"+response.getCode());

**REST service  with  server started on localhost:9090**
 @PostMapping(value = "/post", consumes = {MediaType.APPLICATION_JSON_VALUE}  
    public HttpStatus post(@RequestParam("json") String gson_file ) throws JsonProcessingException{
        Data data  = new Data() 
         data   = new ObjectMapper.readValue(gson_file , Data.class);
        System.out.printf(data +"\n");
        return HttpStatus.OK;    
    }
   
**After starting the CrossExampleProxy2, the output   shows that the Proxy is UP:**   
 ** HTTP Local at: http://localhost:8080/local/
** HTTP Proxy at: http://localhost:8080/proxy/
** CoAP Proxy at: coap://localhost:5683/coap2http
** CoAP Proxy at: coap://localhost:5683/coap2coap
CrossExampleProxy2 started (974MB heap) ...

Each 2 Sec the output  is the code Error 4.02 as response. Should I have to change or set any other Parameter  for the consuming of the REST service ?

**Comment by boaks** [comment]
> Does your http server ignore the content-type? 

I guess, not :-). Try to add content-format

```java
request.setPayload(json);
request.getOptions().setContentFormat(MediaTypeRegistry.APPLICATION_JSON);
CoapClient client = new CoapClient();
```

If that doesn't help, then you may check, if there is more logging for the proxy2 available.
Using the (src/main/resources) "logback.xml" of the "proxy2" from branch "2.6.x", I get message like:

```sh
09:48:27.069 DEBUG [ProxyCacheResource]: Cache read GET http://localhost:8000/http-target#ct=undefined#hc=2107127237
09:48:27.076 DEBUG [Coap2HttpTranslator]: Incoming request translated correctly
09:48:27.078 DEBUG [ProxyHttpClientResource]: Outgoing http request: GET /http-target HTTP/1.1
09:48:27.142 DEBUG [HttpServer]: 127.0.0.1:8000<->127.0.0.1:49320, 1 request handled!
09:48:27.150 DEBUG [ProxyHttpClientResource]: Incoming http response: HTTP/1.1 200 OK
09:48:27.152 DEBUG [Coap2HttpTranslator]: Incoming response translated correctly
09:48:27.152 DEBUG [ProxyCacheResource]: Add new response to resource http://localhost:8000/http-target, 1 responses
09:48:27.161 DEBUG [ProxyCacheResource]: Cached response GET http://localhost:8000/http-target#ct=undefined#hc=2107127237
09:48:27.161 DEBUG [ProxyCacheResource]: Add new response to resource http://localhost:8000/http-target, 2 responses
09:48:27.161 DEBUG [ProxyCacheResource]: Cached response GET http://localhost:8000/http-target#ct=text/plain#hc=2107157028
09:48:27.162 DEBUG [ProxyHttpClientResource]: Incoming http response: HTTP/1.1 200 OK processed!
09:48:27.179 DEBUG [ProxyCoapClientResource]: ProxyCoapClientResource forwards CON-GET    MID=62937, Token=B8DA24392A2B77F8, OptionSet={"Uri-Host":"localhost", "Uri-Path":"coap2coap", "Proxy-Uri":"coap://localhost:5685/coap-target"}, no payload
09:48:27.182 DEBUG [Coap2CoapTranslator]: Incoming request translated correctly
09:48:27.182 DEBUG [ProxyCacheResource]: Cache read GET coap://localhost:5685/coap-target#ct=undefined#hc=934494796
09:48:27.184 DEBUG [ProxyCoapClientResource]: Sending proxied CoAP request to IP(localhost/127.0.0.1:5685)
09:48:27.197 DEBUG [ProxyCacheResource]: Add new response to resource coap://localhost:5685/coap-target, 1 responses
09:48:27.198 DEBUG [ProxyCacheResource]: Cached response GET coap://localhost:5685/coap-target#ct=undefined#hc=934494796
09:48:27.198 DEBUG [ProxyCacheResource]: Add new response to resource coap://localhost:5685/coap-target, 2 responses
09:48:27.198 DEBUG [ProxyCacheResource]: Cached response GET coap://localhost:5685/coap-target#ct=text/plain#hc=934524587
09:48:27.198 DEBUG [ProxyCoapClientResource]: ProxyCoapClientResource received ACK-2.05   MID=58865, Token=644A2587A1656785, OptionSet={"Content-Format":"text/plain", "Max-Age":15}, "Hi! I am the coap server".. 49 bytes
09:48:27.199 DEBUG [Coap2CoapTranslator]: Incoming response translated correctly
09:48:27.202 DEBUG [ProxyCacheResource]: Cache read GET http://localhost:8000/http-target#ct=undefined#hc=2107127237
```

which tells me more about the internal processing. 
Do you get that as well? 
If not, do you start the proxy2 from a IDE? Or from the console? 
Using "java -jar ...." or "java -cp ... CrossExampleProxy2"? 

For the console and "java -cp", please add "-Dlogback.configurationFile=./path-to/logback.xml" e.g.

```sh
java -Dlogback.configurationFile=./src/main/resources/logback.xml -cp target/cf-proxy2-3.0.0-SNAPSHOT.jar org.eclipse.californium.examples.CrossExampleProxy2
```

**Comment by Asemn** [comment]
- I am starting from the console don't get the same output and receive an URI Error  
`23:36:48.369 INFO [ForwardProxyMessageDeliverer]: address 0.0.0.0/0.0.0.0:5683
23:36:48.373 INFO [ForwardProxyMessageDeliverer]: Exposed port 5683
23:36:48.373 INFO [ForwardProxyMessageDeliverer]: Exposed host /0:0:0:0:0:0:0:1%lo
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /127.0.0.1
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /fe80:0:0:0:ae16:2dff:fe46:395c%eno1
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /192.168.1.2
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /fe80:0:0:0:ae16:2dff:fe46:395c%eno1:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /0:0:0:0:0:0:0:1%lo:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /127.0.0.1:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /192.168.1.2:5683
23:36:48.404 INFO [HttpServer]: HttpServer listening on port 8080 started.
** HTTP Local at: http://localhost:8080/local/
** HTTP Proxy at: http://localhost:8080/proxy/
** CoAP Proxy at: coap://localhost:5683/coap2http
** CoAP Proxy at: coap://localhost:5683/coap2coap
CrossExampleProxy2 started (974MB heap) ...
23:36:54.612 DEBUG [ProxyHttpClientResource]: URI error.
org.eclipse.californium.proxy2.TranslationException: Destination host missing!
        at org.eclipse.californium.proxy2.CoapUriTranslator.getDestinationURI(CoapUriTranslator.java:124)
        at org.eclipse.californium.proxy2.resources.ProxyHttpClientResource.handleRequest(ProxyHttpClientResource.java:97)
        at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:107)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:484)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:278)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:137)
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:289)
        at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:270)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by Asemn** [comment]
I start from the console and I don't get the same output and receive an URI Error :
23:36:48.369 INFO [ForwardProxyMessageDeliverer]: address 0.0.0.0/0.0.0.0:5683
23:36:48.373 INFO [ForwardProxyMessageDeliverer]: Exposed port 5683
23:36:48.373 INFO [ForwardProxyMessageDeliverer]: Exposed host /0:0:0:0:0:0:0:1%lo
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /127.0.0.1
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /fe80:0:0:0:ae16:2dff:fe46:395c%eno1
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed host /192.168.1.2
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /fe80:0:0:0:ae16:2dff:fe46:395c%eno1:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /0:0:0:0:0:0:0:1%lo:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /127.0.0.1:5683
23:36:48.374 INFO [ForwardProxyMessageDeliverer]: Exposed service /192.168.1.2:5683
23:36:48.404 INFO [HttpServer]: HttpServer listening on port 8080 started.
** HTTP Local at: http://localhost:8080/local/
** HTTP Proxy at: http://localhost:8080/proxy/
** CoAP Proxy at: coap://localhost:5683/coap2http
** CoAP Proxy at: coap://localhost:5683/coap2coap
CrossExampleProxy2 started (974MB heap) ...
23:36:54.612 DEBUG [ProxyHttpClientResource]: URI error.
org.eclipse.californium.proxy2.TranslationException: Destination host missing!
        at org.eclipse.californium.proxy2.CoapUriTranslator.getDestinationURI(CoapUriTranslator.java:124)
        at org.eclipse.californium.proxy2.resources.ProxyHttpClientResource.handleRequest(ProxyHttpClientResource.java:97)
        at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:107)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:484)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:278)
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:137)
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:289)
        at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:270)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by boaks** [comment]
OK, `CoapUriTranslator.getDestinationURI()` assumes, that the proxy request contains a host. Using the same literal IP (e.g. `127.0.0.1`) for the proxy and destination isn't unfortunately considered there.

Please, as temporary workaround, use 

```java
request.setURI("coap://localhost:9090/post");
```

instead of

```java
request.setURI("coap://127.0.0.1:9090/post");
```

I will see, if that could be done different for the upcoming 3.0.0. I currently work on the update of proxy2 to Apache Http Components 5, so with the next milestone 3.0.0-M2, I guess there will be a solution.

**Comment by boaks** [comment]
The point using the same literal IP for the destination and proxy is, that there is no uri-host option included.
Using the any address to listen to, makes not possible to determine, which address was used for the request, e.g. "127.0.0.1" (for local clients) or "a.b.c.d" (for external ones). Therefore, it's unclear, what the destination of the outgoing request should be (127.0.0.1:9090  of a.b.c.d:9090). To solve that requires not to use the any address to listen to. I will consider to adapt that, but FMPOV, it's not that important. Beside of examples and demos, I don't consider to many proxies forwarding requests just locally.

**Comment by Asemn** [comment]
Ok thanks, that's clear. My Request can now be forwarded after using the same literal IP. 
I have one another question:  Is there a possibility   to build the CoAP request_Body  with a Sting as a Request Parameter and the content of my  File as Json?

**Comment by Asemn** [comment]
Ok thanks! The issue is resolved from my side an can be closed now !

**Comment by Asemn** [comment]
Ok thanks! The issue is resolved from my side and can be closed now !
