### ISSUE TITLE
DTLS Handshake started/restarted with invalid message sequence numbers

### ISSUE THREAD

**Issue by pfg666** [eclipse/californium#1620]
Description
- Type: Bug
- Priority: Minor 

# Non-conformance Bug
**OS**  
Linux, Ubuntu 20

**build:**  
Version: 2.6.2

**Affected Versions**
DTLS 1.2

**Expected behavior**
According to the [DTLS 1.2. RFC](https://www.rfc-editor.org/rfc/rfc6347.html#page-16):

> The first message each side transmits in each handshake always has message_seq = 0. Whenever each new message is  generated, the message_seq value is incremented by one.

This means the server should only carry out the handshake if the first and second ClientHello messages have message_seq 0 and 1, respectively, assuming that cookie exchange is performed.

**Actual Behavior**
Our testing shows that the Scandium server does not properly validate the message_seq field. 
It allows for the handshake to be started and restarted by a ClientHello which has invalid message_seq (greater than 1).

**Steps to Reproduce**
I attached files necessary for reproduction (see reproduction.tar.gz) using [DTLS-Fuzzer](https://github.com/assist-project/dtls-fuzzer/), a Java-based tool for testing DTLS libraries based on TLS-Attacker. Also included in the archive is a capture of the interaction,  generated on my machine. DTLS-Fuzzer requires  the JDK for Java 8. On Ubuntu, this can be installed  by running:
`sudo apt-get install openjdk-8-jdk`

Unpack the archive, `cd` to resulting folder and run `bash reproduce.sh invalid_restart_sequence`, while running an instance of Wireshark on the side. The reproduction script will: 
* setup Californium/Scandium 2.6.2 and DTLS-Fuzzer;
* launch a Scandium server
* launch DTLS-Fuzzer, execute input sequence found in `invalid_restart_sequence`.
 
If everything works as planned, Wireshark should show an interaction similar to that in the image below:

![scandium_invalid_handshake_restart](https://user-images.githubusercontent.com/2325013/117979867-a94c8380-b333-11eb-8c21-4f1f0d16766b.png)

Notice that the forth ClientHello prompts the server to generate a new ServerHello flight. Looking at the contents of this ClientHello, we see that its message_seq field is 3 instead of 1. Further testing reveals that message_seq can take an even higher number (e.g. 10) and the handshake will still proceed.

![scandium_invalid_handshake_restart_client_hello](https://user-images.githubusercontent.com/2325013/117979888-ad78a100-b333-11eb-8ab0-8137d31b4a9c.png)

This is the case for when a handshake is restarted. We noticed similar behavior at the start of the handshake. Run `bash reproduce.sh  invalid_start_sequence`. You get:

![scandium_invalid_handshake_start](https://user-images.githubusercontent.com/2325013/117982718-95eee780-b336-11eb-9a40-2146796c2fc0.png)

With the ClientHello having message_seq 2:

![scandium_invalid_handshake_start_clienthello](https://user-images.githubusercontent.com/2325013/117982789-a901b780-b336-11eb-84fe-f2d005903e5a.png)

Note, the Scandium server is essentially the server program sc-dtls-example-server made to be more configurable. You can find its source code at `dtls-fuzzer/suts/scandium-2.6.2`. The archive contains captures for both invalid behaviors.

Thanks!

[reproduction.tar.gz](https://github.com/eclipse/californium/files/6466498/reproduction.tar.gz)

**Comment by boaks** [comment]
Let me first ask:

Beside that interpretation of RFC6347, did you observer or expect any harm?

[RFC6347, 4.2.1.  Denial-of-Service Countermeasures](https://tools.ietf.org/html/rfc6347#section-4.2.1)

>    In order to counter both of these attacks, DTLS borrows the stateless
>    cookie technique used by Photuris [PHOTURIS] and IKE [IKEv2]. 

[RFC6347, 4.2.1.  Denial-of-Service Countermeasures ff](https://tools.ietf.org/html/rfc6347#page-18)

>    If a server receives a ClientHello with an invalid cookie, it SHOULD
>    treat it the same as a ClientHello with no cookie.  This avoids
>    race/deadlock conditions if the client somehow gets a bad cookie
>    (e.g., because the server changes its cookie signing key).
> 
>    Note to implementors: This may result in clients receiving multiple
>    HelloVerifyRequest messages with different cookies.  Clients SHOULD
>    handle this by sending a new ClientHello with a cookie in response to
>    the new HelloVerifyRequest.

Assume, that "cookie expires" requires to increase that (handshake) message sequence number, and assume, a "stateless" implementation of such an cookie exchange, a CLIENT_HELLO will use a 2 and the server seems to have to accept that.

**Comment by boaks** [comment]
> Note, the Scandium server is essentially the server program sc-dtls-example-server made to be more configurable. 

That `sc-dtls-example-server` is a simple example as point to start to use Scandium. It's not intended as "out-of-the-box standalone solution".

Just to mention: in the meantime I use the `SslContextUtil` to load credentials.

**Comment by pfg666** [comment]
Hi! Thanks for the clarification, and in particular, for the RFC quotes. No harm was observed or expected. This is just an interesting behavior that came up from testing the system.

Using DTLS-Fuzzer on some client implementations, I see they indeed increase the message sequence number in ClientHello generated in response to each HelloVerifyRequest received.  Hence, a server would have to be open to the possibility of receiving ClientHello with increased message sequence. This likely explains why most implementations we tested exhibit behavior similar to Scandium in this respect.

Under this argument, I think the issue can be closed, particularly since it appears to be intended behavior.
