### ISSUE TITLE
Issue regarding the use of InternalError Alert

### ISSUE THREAD

**Issue by pfg666** [eclipse/californium#1621]
Hi,

According to our testing, Scandium generates Alerts of type internal_error in response to unexpected messages. Attached is a tar-ed capture showcasing this, with a screenshot of the capture shown below.

![scandium_internal_error](https://user-images.githubusercontent.com/2325013/117989870-ef5a1500-b33c-11eb-80b3-956b0233de12.png)

[capture.pcapng.tar.gz](https://github.com/eclipse/californium/files/6538857/capture.pcapng.tar.gz)

While not problematic, it seems a weird, arguably non-conforming choice. Other implementations we tested either used unexpected_message as their default Alert choice (which seems the natural choice according to the TLS 1.2 RFC)  or no alert at all (recommended by the DTLS 1.2 RFC). 

I was wondering if there was a reasoning behind using internal_error instead of what the RFCs suggest. Bellow are relevant snippets from the RFCs:

[DTLS 1.2](https://www.rfc-editor.org/rfc/rfc6347.html#page-12) on alerts:

> In general, DTLS implementations SHOULD silently discard records with
> bad MACs or that are otherwise invalid. 

[TLS 1.2](https://datatracker.ietf.org/doc/html/rfc5246#section-7.2.2) on unexpected_message and internal_error

>   unexpected_message
>      An inappropriate message was received.

>  internal_error
>  An internal error unrelated to the peer or the correctness of the  protocol (such as a memory allocation failure) makes it impossible to continue.

Thanks!

**Comment by boaks** [comment]
Yep, if possible, please retest with 3.0.0-M1

Scandium was redesigned and by that, I tried to report alerts more close to the RFCs.
If some irritating errors are found in 3.0.0-M1, it may be possible to fix them.

**Comment by pfg666** [comment]
Thanks for the confirmation. We have not yet tested 3.0.0-M1 (the harness needs to be updated), though once we do, I will update this post with our results.

**Comment by boaks** [comment]
For 2.6 only bug-fixes are planed, which don't require changes in the APIs.

Therefore I would appreciate, if you focus your tests on the upcoming version 3.
Help there is more sustainable :-).

**Comment by boaks** [comment]
For exactly that error, it's possible to adjust the 2.6.x (I will prepare a PR for that). I'm pretty sure, there are much more weird error types like that, which will not be fixed that easily. Therefore I would enjoy, if the analysis is focused on the 3.0, where such fixes are possible and more sustainable.

For me [4.1.2.7 Handling Invalid Records](https://www.rfc-editor.org/rfc/rfc6347.html#section-4.1.2.7), is more precise at the invalid records than [4.1.2.1 MAC](https://www.rfc-editor.org/rfc/rfc6347.html#section-4.1.2.1). 

>  In general, invalid records SHOULD be silently discarded, thus preserving the association;

That addresses the reason, preserving (established) associations, and so I think, reporting handshake errors during the handshake is the intended behavior.

One comment on the capture:
Please consider to select the relevant records according [Californium's Wiki, How To Provide The Right Information](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#wireshark).

**Comment by pfg666** [comment]
I reduced the capture file so that it only contains the relevant records. 

My original interpretation of the RFC is that it allowed an implementation to decide how to react to an invalid message during an message, i.e. whether to generate an alert or keep silent (and let the other side time out), with a strong recommendation for the latter once a session has been established. However, reviewing it, I agree that it appears to strongly favor silent discard only once an association has been established, so generating proper alerts does seem the intended approach during the handshake phase.  My only concern are the vulnerabilities that have resulted from alert generation, e.g. [Bleichenbacher](taking into account potential vulnerabilities). Given the ambiguity of the RFC on this matter and the potential risks, I would not fault implementations for staying silent during the handshake.

I should have some results for 3.0 by next week.

**Comment by boaks** [comment]
> I reduced the capture file so that it only contains the relevant records.

Only for future issues. This one is ok.

**Comment by boaks** [comment]
> I should have some results for 3.0 by next week.

Great, I'm looking forward to it.

**Comment by boaks** [comment]
I merged the PR.
If possible, please check, if that specific error cause is fixed.

**Comment by pfg666** [comment]
Hi! After running a rather extensive suite of tests on version 2.6.4-SNAPSHOT post-PR, I can confirm that the bug appears to be fixed.

**Comment by boaks** [comment]
Great!
