### ISSUE TITLE
Disable HelloVerifiy for DTLS

### ISSUE THREAD

**Issue by anyx9** [eclipse/californium#1622]
Currently, it is not possible to disable the HelloVerify message for the server and instead answer with the ServerHello.
I am aware of the security implications, but in my use case they are irrelevant. I am communicating over a very slow channel and have to reduce the number of bytes sent. 

Would it be possible to add support for disabling the HelloVerfiy message to the config builder?

**Comment by boaks** [comment]
I'll try it. 
But only for the upcoming 3.0. :-). Would that be OK for you?

**Comment by anyx9** [comment]
That would be great, thank you.

**Comment by boaks** [comment]
I prepared a PR. If possible, please test, if that works for you.

**Comment by boaks** [comment]
In order to limit the risk of amplification, the PR is adapted to use the HELLO_VERIFY_REQUEST, if the peers don't share a PSK cipher suite.

@anyx9 does it work for, if it is limited to PSK?

**Comment by anyx9** [comment]
I don't use a PSK suite, so that would not work for me.

**Comment by boaks** [comment]
> I am communicating over a very slow channel and have to reduce the number of bytes sent.

Hm, I thought, that using certificates "over a very slow channel" doesn't make sense, especially if "reduce the number of bytes sent" is important. 
Anyway, I will convert it into an callback ... then everyone may do what is the best in it's case.

**Comment by boaks** [comment]
Updated. 
Supports now to skip the hello verify request for PSK only or general.

@anyx9 

Please test, if ti works for you.

**Comment by anyx9** [comment]
I have diasbled hello verify in general by calling `builder.setUseHelloVerifyRequest(false)` and get the following error message:
`java.lang.IllegalArgumentException: HELLO_VERIFY_REQUEST disabled for PSK, requires at least one PSK cipher suite!`

The error is caused by setPreselectedCipherSuites. A check, to see if hello verify is generally disabled, is missing. It should not matter what cipher suite I preselect when HELLO_VERIFY_REQUEST is disabled.

**Comment by boaks** [comment]
Thanks, I'll fix it.
(Too many redesigns ;-) ).

**Comment by boaks** [comment]
Next try ... with some unit tests on the finding.

**Comment by anyx9** [comment]
I have found some strange behaviour. For context, I use the dtls_client example software provided in the mbedTLS implementation as testing client.
With the new commit, I can successfully perform a handshake without HELLO_VERIFY_REQUEST, but just once. If I start the client the first time, the handshake is performed without hello verify. If I start the client a second time, I can see a the hello verify and a second client hello packet in wireshark.
If I restart the server, the first handshake is again done without hello verify request, but all subsequent handshakes are performed with hello verify.
This issue could be related to session resumption, but I am not sure.

**Comment by boaks** [comment]
Please try to provide wireshark captures with the [selected messages](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#wireshark).

It's much easier to find such bugs, if I have the details ...

**Comment by boaks** [comment]
I guess it's 

`DTLSConnector.processNewClientHello`

```java
if (!clientHello.hasCookie()) {
	SessionId establishedSessionId = connection.getEstablishedSessionIdentifier();
	boolean sameSession = Bytes.equals(establishedSessionId, clientHello.getSessionId());
	if (!sameSession) {
		// don't overwrite the current connection, first verify address
		// protection for spoofed client_hello, with valid session id
		// and spoofed ip-address of valid other peer.
		addressVerified = false;
	})
}
```

I will check this.

**Comment by boaks** [comment]
Again, next try ... with an unit tests on the finding.

Just to mention, there are two threats.
1. the amplification
2. hide an other established association (starting a handshake on the address of an other valid association).

At  least for now, 2. will affect Scandium also. I'm not sure, if that could be mitigated in a future version.

**Comment by anyx9** [comment]
It seems to be working now. Thank you very much for your efforts. I will reopen this issue if I find any further problems.

**Comment by boaks** [comment]
Thanks for the feedback.
I'm not sure, what you exact use-case is, but though you use mbedTLS, one idea to reduce the amount of data for handshakes is to use [DTLS 1.2 CID](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls-connection-id/) to reduce the number of required handshakes for address changes. If you're interested, let me know.
