### ISSUE TITLE
running CoAP Proxy on Host Side 

### ISSUE THREAD

**Issue by BushAnder** [eclipse/californium#1633]
Hello,
I am currently  using the  CrossExampleProxy2  to forward CoAP-Request  to an HTTP-Server and get the response code back. The  translation and forwarding   process work when   the  Proxy is running on  the Client Side. But  when  I start  the proxy on the Host Side, I'm not any more able to  forward the  request and I get an exception after waiting a long time the request to be transmitted.

This part of code is used  to build and make request from my client with the @dresse : 192.168.1.8

`AddressEndpointContext proxy = new AddressEndpointContext(new InetSocketAddress("192.168.1.2", 5683));   
                        Request request = Request.newPost();
                        CoapResponse response = null;
                        request.setDestinationContext(proxy);
                        request.setProxyScheme("http");
                        request.setURI("coap://192.168.1.2: 8181/file");  
                        request.setPayload(data);
                        request.getOptions().setContentFormat(MediaTypeRegistry.APPLICATION_JSON);
                       CoapResponse response = client.advanced(request);
                        response = client.advanced(request);
                        System.out.println("code:" + response.getCode());`

May I need something  else instead of handling with the  addresses from the  client side ?

Thanks in advance

**Comment by boaks** [comment]
Let me try to describe your setup:

A coap-client is running on 192.168.1.8 (local network).
A http-server is running on 192.168.1.2:8181, it has a resource "/file".
A cross-proxy is running on 192.168.1.2:5683

Right?

```java
request.setURI("coap://192.168.1.2: 8181/file")
```

if the space between "2:" and "8181" is not just a copy & paste issue, and you use that in your request, try to remove it and use

```java
request.setURI("coap://192.168.1.2:8181/file")
```

without the space. 
If that doesn't help, please check [Logs and IP Capturing  - How To Provide The Right Information](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information)

**Comment by BushAnder** [comment]
> if the space between "2:" and "8181" is not just a copy & paste issue, and you use that in your request, try to remove it and use
Yes that's my setup and  there is no space in my request.  Sorry It's  a copy & paste issue

**Comment by boaks** [comment]
Then, please provide logs and wireshark captures. With the space, "localhost" was used as destination, which would have explained your case. If that is not the case, I'm wondering, why that isn't working. The traces and mainly wireshark capture (client-side and proxy) should show, what's going on.

**Comment by boaks** [comment]
One issue may be, that the http-server and proxy are co-located and literal-ip addresses are used. The nasty thing with that is, that this removes the URI-host option and makes it hard for the proxy to determine the final destination. If possible, please try to add "192.168.1.2" after the `setURI` with

```java
request.setURI("coap://192.168.1.2:8181/file");
request.getOptions().setUriHost("192.168.1.2");
```

Or, if "192.168.1.2" has also a "hostname", which supported by your local DNS, use that.

**Comment by boaks** [comment]
I managed to reproduce that scenario.

If the current master-branch is used (or something else including the commit 959e116e535), it works also with literal ip-addresses. But general, I recommend to use dns names for the final destination and not literal-ip-addresses.

**Comment by boaks** [comment]
Sometime the information is there, it's just not on the way and therefore not found.

So, when you start to use the proxy2, did you 
- read the [README.md of californium-proxy2](https://github.com/eclipse/californium/blob/master/californium-proxy2/README.md)?
- or, read the [ExampleProxy2CoapClient](https://github.com/eclipse/californium/blob/master/demo-apps/cf-proxy2/src/main/java/org/eclipse/californium/examples/ExampleProxy2CoapClient.java)?

For those who start with the example, I added some inline comments to the example.

**Comment by BushAnder** [comment]
Thanks for all. Yes I read the READ.md, I also run the Proxy on the same machine with  client, and it worked. But I encounter the issue when  I decided  to start the Proxy on the Host side. I have seen your Wireshark capture  and how the Test you managed with the literal IP is   working. It seems to be an issue with my internal Network, and I'm not allow  using  Wireshark.

**Comment by boaks** [comment]
> I'm not allow using Wireshark.

Second best would be to enable the proxies logs. That's also explained at the [WiKi](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#logs).

**Comment by BushAnder** [comment]
> > I'm not allow using Wireshark.
> 
> Second best would be to enable the proxies logs. That's also explained at the [WiKi](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#logs).

**Comment by BushAnder** [comment]
The issue was resolved !
