### ISSUE TITLE
Error using brainPoolP256r1

### ISSUE THREAD

**Issue by anyx9** [eclipse/californium#1639]
Hi,
I have to provide support for the brainPoolP256r1 and brainPoolP384r1 elliptic curves, because of (in-)security requirements.

For this, I disabled recommended groups only with
`builder.setRecommendedSupportedGroupsOnly(false)`
and defined my support groups with
`builder.setSupportedGroups(listOf(XECDHECryptography.SupportedGroup.brainpoolP256r1, XECDHECryptography.SupportedGroup.brainpoolP384r1))`

Unfortunately, I receive the following error when loading the server's trust certificate:
`java.lang.IllegalArgumentException: curve brainpoolP256r1 is not supported by JVM!`

I am unsure how I can fix this error. I tried downgrading my JDK, adjusting the security properties with
`Security.setProperty("jdk.tls.namedGroups", "brainpoolp256r1,brainpoolP384r1")`
and added a new security provider via
`Security.insertProviderAt(BouncyCastleProvider(), 1)`

I am currently using the 3.0.0-SNAPSHOT on JDK 15 (Android).
So far, nothing seems to help. Any ideas?

**Comment by boaks** [comment]
Scandium mainly uses crypto function provided by the JVM (JCE). It doesn't come with own implementations.
EC functions are used for two topics: ECDHE (for that java-11 supports "brainpoolP256r1" or "brainpoolP384r1") and ECDSA (for that I don't know it).

> Unfortunately, I receive the following error when loading the server's trust certificate:
java.lang.IllegalArgumentException: curve brainpoolP256r1 is not supported by JVM!

> I am unsure how I can fix this error. 

And your certificate is signed with brainpoolP256r1? So you want to use it for ECDSA?
Or for ECDHE?

(Just to mention: I'm not that common to add providers, I mainly use what comes with the JVM. Therefore, I'm also not sure how to fix it. But it would at least require to understand your use-case.)

**Comment by boaks** [comment]
could you please also check, if `XECDHECryptography.SupportedGroup.brainpoolP256r1.isUsable()` returns `true`? That would indicated, that for ECDHE that curve is supported.

**Comment by boaks** [comment]
Just in the case, you need ECDSA:

[java-ecc-brainpool-support-for-certificates](https://stackoverflow.com/questions/31388538/java-ecc-brainpool-support-for-certificates)

Maybe that helps.

**Comment by boaks** [comment]
And [Oracle - Recommended Curves](https://docs.oracle.com/en/java/javase/13/security/oracle-providers.html#GUID-091BF58C-82AB-4C9C-850F-1660824D5254), search for "Recommended Curves".

> Legacy Curves Retained for Compatibility
> 
> Note:It is recommended that you migrate to newer curves.
> 
> The following table lists elliptic curves that are provided by the SunEC provider and are not implemented using modern formulas and techniques. These curves remain available for compatibility reasons to afford legacy systems time to migrate to newer curves. These implementations will be removed or replaced in a future version of the JDK.

So, I have doubts, that using `brainpoolP256r1` is a good idea. 
Maybe you can check, if X25519 or X448 would do it as well?

**Comment by anyx9** [comment]
> And your certificate is signed with brainpoolP256r1? So you want to use it for ECDSA?
Or for ECDHE?

ECDSA

> So, I have doubts, that using brainpoolP256r1 is a good idea.

I guess we are in the same boat ;)

I managed to get it running after trying some more providers. Adding
`Security.insertProviderAt(org.spongycastle.jce.provider.BouncyCastleProvider(), 1)`
did the trick.

**Comment by boaks** [comment]
Just to say: using java 15 Ed25519/Ed448 is the selection with future. But sure, sometimes others have "the say".
