### ISSUE TITLE
Unable to build cf-simplefile-server .jar file

### ISSUE THREAD

**Issue by gor-bit** [eclipse/californium#1652]
Hi, I recently implemented the Californium client in my own project which has worked extremely well.

I noticed there are also `demo-apps` and I would like to try the `cf-simplefile-server` (I am using `californium-3.0.0-M2`):
https://github.com/eclipse/californium/tree/master/demo-apps/cf-simplefile-server.

The [README](https://github.com/eclipse/californium/tree/master/demo-apps/cf-simplefile-server) on this page provides instructions of how to use the compiled .jar file but not how to generate this .jar file, so I am trying to build it with the provided `pom.xml` [file](https://github.com/eclipse/californium/blob/master/demo-apps/cf-simplefile-server/pom.xml).

I noticed that the `demo-apps` is not available on Maven: https://repo.maven.apache.org/maven2/org/eclipse/californium/demo-apps/3.0.0-M2/demo-apps-3.0.0-M2.pom and it appears this is causing me to run into issues when building.

Meanwhile the .jar files I used for the Californium client were available on Maven, so I had no issues at all.

When I compile the project these are the failed build logs:
```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------< org.eclipse.californium:cf-simplefile-server >------------
[INFO] Building Cf-SimpleFileServer 3.0.0-M2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.348 s
[INFO] Finished at: 2021-06-25T14:11:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cf-simplefile-server: Could not resolve dependencies for project org.eclipse.californium:cf-simplefile-server:jar:3.0.0-M2: Failed to collect dependencies at org.eclipse.californium:cf-plugtest-server:jar:3.0.0-M2: Failed to read artifact descriptor for org.eclipse.californium:cf-plugtest-server:jar:3.0.0-M2: Failure to find org.eclipse.californium:demo-apps:pom:3.0.0-M2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1
```

Is there a recommended Maven repository I can use to build this `cf-simplefile-server-3.0.0-M2.jar`?

Thank you!

**Comment by boaks** [comment]
Please, try to build Californium from the root (once a day), see [build](https://github.com/eclipse/californium#build-using-maven).

So, usually, clone the whole repo and build with

```
git clone https://github.com/eclipse/californium.git
cd californium
mvn clean install
```

that build Californium 3.0.0-SNAPSHOT. 
Later you may try to build in the demo-apps/cf-simplefile-server with mvn clean install. 
Using SNAPSHOT may require you to build Californium in the root "once a day".

**Comment by boaks** [comment]
(I added "demo-apps" to the deployed artifacts, with the next release, it may work without to build the root :-) .

**Comment by gor-bit** [comment]
Thank you for your response to this issue, @boaks .

I spent almost 3 hours trying to get this to work and I now see that you even described this solution in your README file.

I will share this recent viral Twitter message which is very relatable in this scenario:
https://twitter.com/jcsrb/status/1392459191353286656

Thank you for answering my question with patience!

**Comment by gor-bit** [comment]
Another quick question which may be related to this build - I can see the DTLS endpoint in this example added here: https://github.com/eclipse/californium/blob/master/demo-apps/cf-simplefile-server/src/main/java/org/eclipse/californium/examples/SimpleFileServer.java#L146

The generated `Californium.properties` file allows me to set the DTLS port, but does not seem to contain the setting for the root certificate and trusted certificates. Where is the configuration of this property located? 
(I believe this would be configured already as part of the `pom.xml` built in this project, but I cannot locate this.)

And what if I want to use PSK instead of certificates, how can I set this using your build?

Thank you!

**Comment by boaks** [comment]
> The generated Californium.properties file allows me to set the DTLS port, but does not seem to contain the setting for the root certificate and trusted certificates.

Yes, that's caused by the order of the layer and I currently try to redesign `NetworkConfig` see issues #1469 , #1601 and #1648.

> if I want to update the certificates and PSK, then rebuild the entire project to have it now in my cf-simplefile-server-3.0.0-M2.jar?

The `cf-simplefile-server` is a very basic and simple demo, it's not considered to be a "out of the box" ready to use solution. You may add the way you want to provide your credentials, "as you want". 

> Is there a way for me to change these properties as part of the Californium.properties file instead of having to rebuild the entire thing?

With 3.0.0-M2 no, in the future, there may be some more support. I don't plan to add a PSK-store (at least not for now), but the certificates parameter may get added. We will see.

**Comment by kevinkngo** [comment]
Thank you again @boaks . I will close this issue. 

I would like to also add, this is a fantastic project and I am very grateful for your work.

**Comment by gor-bit** [comment]
Thank you @boaks . I will close this issue.

I would like to also add, this is a fantastic project and I am very grateful for you and your team's work. Thank you again.

**Comment by boaks** [comment]
You're welcome.

**Comment by boaks** [comment]
> (I added "demo-apps" to the deployed artifacts, with the next release, it may work without to build the root :-) .

That doesn't work, though the demo-apps modul itself is skipped. I will add some comments, that the demos must build in/from the parent.
