### ISSUE TITLE
Support EDDSA ciphersuites?

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [eclipse/californium#1654]
I am not an expert of TLS but I noticed that  `californium` support ed25519 about a years ago #1395,
From the information I collected from google, ed25519 is a specific instance of the EdDSA family of signature schemes.  
So maybe we should add something like TLS_ECDHE_**EDDSA**_WITH_AES_128_GCM_SHA256 to our supported cipherSuites?

**Comment by boaks** [comment]
According [RFC8422](https://datatracker.ietf.org/doc/html/rfc8422) TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 supports the EdDSA as well. I tested that with openssl  and it works, at least for some handshakes.

But please notice, you either require java 15 or a third-party  library, but the one I chosed ago  seems to be not longer maintained.

**Comment by Nick-The-Uncharted** [comment]
@boaks I used bouncycastle with a few hacks, it works:
```
    static {
        BouncyCastleProvider bouncyCastleProvider = new BouncyCastleProvider();
        bouncyCastleProvider.setProperty("Alg.Alias.Signature.1.3.101.112", "Ed25519");
        bouncyCastleProvider.setProperty("Alg.Alias.Signature.1.3.101.113", "Ed448");
        java.security.Security.removeProvider("BC");
        java.security.Security.insertProviderAt(bouncyCastleProvider, 1);
    }
``` 

Hacks：
Overriding org.eclipse.leshan.core.util.SecurityUtil to read Eddsa keys.

**Comment by Nick-The-Uncharted** [comment]
Still it's kind of wired that new auth algorithm reused old cipherSuite. 
Maybe the intention of the author is compatibility, guess we will never know....

**Comment by boaks** [comment]
> Still it's kind of wired that new auth algorithm reused old cipherSuite.

The idea (AFAIK) was even before EdDSA to support different curves/groups. So it was considered to be just an different curve/group.

> Overriding org.eclipse.leshan.core.util.SecurityUtil to read Eddsa keys.

That's leshan, not Californium.
Californium uses either the `Asn1DerDecoder` for the "raw"-key-pair, or the `SslContextUtil` for x509. If you're interested, please test, if that works for you or requires some fixes. (Please use 3.0.0-M2 for that test, no 2.6.3)

**Comment by boaks** [comment]
> support different curves/groups

One remark:
Californium is checking that curves for usage with ECDHE, and there it uses some "reflection calls". Do you plan to use x25519/x448 for ECDHE? Then it would require the possibility for "custom handler".

**Comment by Nick-The-Uncharted** [comment]
@boaks Thanks a lot, you just cleared all my doubts.

**Comment by boaks** [comment]
You're welcome. 
If you find any issues ... let me know. I didn't use it with BC.

**Comment by Nick-The-Uncharted** [comment]
Sure, that's the least I can do~
