### ISSUE TITLE
Retransmission Timeout Ignored

### ISSUE THREAD

**Issue by anyx9** [eclipse/californium#1655]
When setting the retransmission timeout in the builder like so

builder.setRetransmissionTimeout(500000)

It gets ignored and the retransmission is sent after 60 seconds.

[DTLS-Worker-/127.0.0.1:5684#4] handshake flight to peer 127.0.0.1:5685, retransmission 60000 ms.

**Comment by boaks** [comment]
Does the other peer need longer than 60s to answer?

According [RFC6347](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.4.1)

>  Implementations SHOULD use an initial timer value
>    of 1 second (the minimum defined in RFC 6298 [RFC6298]) and double
>    the value at each retransmission, up to no less than the RFC 6298
>    maximum of 60 seconds.

Assuming common address change on longer quiet periods, we limited that timeout to 60s.

**Comment by boaks** [comment]
If you need to check, if larger values work, 

[DTLSFlight.incrementTimeout(int timeoutMillis)](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DTLSFlight.java#L713)

[DTLSFlight.MAX_TIMEOUT_MILLIS(int timeoutMillis)](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DTLSFlight.java#L98)

adapt to code.

**Comment by boaks** [comment]
O do you want to suppress retransmissions at all? What should then be the timeout to fail the handshake?

[DtlsConnectorConfig.Builder.setMaxRetransmissions(int count)](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1990)

adapt the check.

**Comment by anyx9** [comment]
I changed public static final int MAX_TIMEOUT_MILLIS and now it works. 
Would it be possible to make larger timeouts configurable via builder?
The RFC states SHOULD and I have a good reason for longer timeouts, as I am working with power limited, slow smart meters.

**Comment by boaks** [comment]
> Would it be possible to make larger timeouts configurable via builder?

Yes.

> The RFC states SHOULD 

Yes, therefore it's 60s and not 30s, which would be my recommendation :-).

In my experience, using UDP in the "public internet", "home-router" and "cloud", any value above that 30s is optimistic and may result and failures. Usually transmission latency is not more that about 2-3s (even on CAT-NB) and Californium should be fast enough to get not overloaded. 
Using larger value seems to be more a topic of usage outside our main use-cases.
Just to mention, it it's the x509, which requires larger values, there is also a 

`Builder.setAdditionalTimeoutForEcc(int timeout)`

that doesn't escape the 60s, but may help to just increase, when it is required.

**Comment by boaks** [comment]
Just to mention.

[Adopters](https://iot.eclipse.org/adopters/)

[Project-Adopters](https://github.com/EclipseFdn/iot.eclipse.org#project-adopters)

Some more, will be not too bad ;-).

**Comment by boaks** [comment]
I currently work on PR #1653 . 
I guess, that will take until end of next week.
So, the configurable max timeout will take some time ...

**Comment by anyx9** [comment]
No problem, thank you for your time :)

**Comment by boaks** [comment]
Just to mention:

Moving many setting from `DtlsConnectorConfig.Builder` into the general `Configuration` with definitions in `DtlsConfig` is much more typing than I expected. It will take one more week.

**Comment by boaks** [comment]
If possible, please check, if PR #1673 works for you. I plan to release it with 3.0.0-M3 on Monday, 17 July.
