### ISSUE TITLE
Is this messages split into several records expected ? 

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1689]
Here a capture of Leshan 2.0.0-M4 which talked with an unknow client implementation. 
[resume_failed.zip](https://github.com/eclipse/californium/files/6946471/resume_failed.zip)

This capture contains a successful full handshake, then a failed abbreviated one.
The reason why the abbreviated one failed is unknown but probably caused by an issue at client side.

What is surprised me is that the flight was split into several records since packet 16.

Before packet 16 : 
```
15	Server Hello, Change Cipher Spec, Encrypted Handshake Message
```
Since packet 16 : 
```
16	Server Hello
17	Change Cipher Spec, Encrypted Handshake Message
```

Is it the expected behavior ? maybe a feature that I didn't know ?

**Comment by boaks** [comment]
[DTLS_RETRANSMISSION_BACKOFF](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L319)

I guess, the alert (13) is the real issue.

**Comment by boaks** [comment]
[RFC6347](https://tools.ietf.org/html/rfc6347#page-12)

> If repeated retransmissions do not result in a response, and the
>       PMTU is unknown, subsequent retransmissions SHOULD back off to a
>       smaller record size, fragmenting the handshake message as
>       appropriate.  This standard does not specify an exact number of
>       retransmits to attempt before backing off, but 2-3 seems
>       appropriate.

**Comment by boaks** [comment]
The Alert (13) is sent in epoch 1, but the client didn't sent a CCS after a ClientHello of epoch 0.

**Comment by sbernard31** [comment]
I don't focus too much on client behavior as I pretty sure there is issue at client side.
I'm mainly interested/curious  by the server behavior.


> DTLS_RETRANSMISSION_BACKOFF

Is this a new feature introduce in 3.x ?

**Comment by boaks** [comment]
It was introduced with [2.4.0](https://projects.eclipse.org/projects/iot.californium/releases/2.4.0).

**Comment by sbernard31** [comment]
Ok Thx for clarification. 

So all seems OK here. I just missed this new feature :-)

I close this issue.
