### ISSUE TITLE
Unexplainable full handshake (instead of abbreviated one)

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1690]
We faced a very strange issue which I can not explained. The issue is so strange that I'm not so comfortable to report it but maybe you will see something we missed.

## The context

So we have [Flatcar-stable-2605.6.0-hvm](https://aws.amazon.com/marketplace/pp/prodview-2hdonbnvl3s4c?qid=1628264790101&sr=0-1&ref_=srh_res_product_title#pdp-overview) EC2(aws) instance in which we run a **leshan-client-demo** which try to connect to a **server based on Leshan** on the same machine. Each application run in a separated docker container. 

The use case is to run the **leshan-client-demo** with some option to connect using with PSK and force abbreviated handshake on each registration update. : 
```
java -jar leshan-client-demo.jar -u localhost:5684  -i aa -p AA -r -cp 10
```
A successfull output should looks like : 
```
2021-08-06 16:10:53,780 INFO LeshanClient - Starting Leshan client ...
2021-08-06 16:10:54,020 INFO CaliforniumEndpointsManager - New endpoint created for server coaps://localhost:5684 at coaps://0.0.0.0:33559
2021-08-06 16:10:54,021 INFO LeshanClient - Leshan client[endpoint:357409080107560] started.
2021-08-06 16:10:54,023 INFO DefaultRegistrationEngine - Trying to register to coaps://localhost:5684 ...
2021-08-06 16:10:54,057 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : STARTED ...
2021-08-06 16:10:54,125 INFO LeshanClientDemo - DTLS Full Handshake initiated by client : SUCCEED
2021-08-06 16:10:54,163 INFO DefaultRegistrationEngine - Registered with location '/rd/ietDSccgDv'.
2021-08-06 16:10:54,164 INFO DefaultRegistrationEngine - Next registration update to coaps://localhost:5684 in 10s...
2021-08-06 16:11:04,165 INFO DefaultRegistrationEngine - Trying to update registration to coaps://localhost:5684 (response timeout 120000ms)...
2021-08-06 16:11:04,167 INFO CaliforniumEndpointsManager - Clear DTLS session for resumption for server coaps://localhost:5684
2021-08-06 16:11:04,175 INFO LeshanClientDemo - DTLS abbreviated Handshake initiated by client : STARTED ...
2021-08-06 16:11:04,186 INFO LeshanClientDemo - DTLS abbreviated Handshake initiated by client : SUCCEED
2021-08-06 16:11:04,219 INFO DefaultRegistrationEngine - Registration update succeed.
2021-08-06 16:11:04,219 INFO DefaultRegistrationEngine - Next registration update to coaps://localhost:5684 in 10s...
^C2021-08-06 16:11:09,832 INFO LeshanClient - Destroying Leshan client ...
2021-08-06 16:11:09,834 INFO DefaultRegistrationEngine - Trying to deregister to coaps://localhost:5684 ...
2021-08-06 16:11:09,878 INFO DefaultRegistrationEngine - De-register response DELETED(202) null.
2021-08-06 16:11:09,906 INFO LeshanClient - Leshan client destroyed.

```

## The issue :

When we test with `master` version of **leshan-client-demo** (https://github.com/eclipse/leshan/commit/55984dce8cf5b29b7a08d5bbec9395788bec84f7) / and so cf-3.0.0-M3, the abbreviated handshake is not initiated but a fullhandshake instead : 
```
                  LeshanClient 2021-08-06 16:08:21,111 [INFO] Starting Leshan client ...
   CaliforniumEndpointsManager 2021-08-06 16:08:21,258 [INFO] New endpoint created for server coaps://localhost:5684 at coaps://0.0.0.0:51627
                  LeshanClient 2021-08-06 16:08:21,261 [INFO] Leshan client[endpoint:357409080107560] started.
     DefaultRegistrationEngine 2021-08-06 16:08:21,263 [INFO] Trying to register to coaps://localhost:5684 ...
              LeshanClientDemo 2021-08-06 16:08:21,306 [INFO] DTLS Full Handshake initiated by client : STARTED ...
              LeshanClientDemo 2021-08-06 16:08:21,392 [INFO] DTLS Full Handshake initiated by client : SUCCEED
     DefaultRegistrationEngine 2021-08-06 16:08:21,432 [INFO] Registered with location '/rd/QcqImu612w'.
     DefaultRegistrationEngine 2021-08-06 16:08:21,433 [INFO] Next registration update to coaps://localhost:5684 in 10s...
     DefaultRegistrationEngine 2021-08-06 16:08:31,434 [INFO] Trying to update registration to coaps://localhost:5684 (response timeout 120000ms)...
   CaliforniumEndpointsManager 2021-08-06 16:08:31,435 [INFO] Clear DTLS session for resumption for server coaps://localhost:5684
              LeshanClientDemo 2021-08-06 16:08:31,437 [INFO] DTLS Full Handshake initiated by client : STARTED ...
              LeshanClientDemo 2021-08-06 16:08:31,483 [INFO] DTLS Full Handshake initiated by client : SUCCEED
     DefaultRegistrationEngine 2021-08-06 16:08:31,519 [INFO] Registration update succeed.
     DefaultRegistrationEngine 2021-08-06 16:08:31,519 [INFO] Next registration update to coaps://localhost:5684 in 10s...
                  LeshanClient 2021-08-06 16:08:34,826 [INFO] Destroying Leshan client ...
     DefaultRegistrationEngine 2021-08-06 16:08:34,831 [INFO] Trying to deregister to coaps://localhost:5684 ...
     DefaultRegistrationEngine 2021-08-06 16:08:34,876 [INFO] De-register response DELETED(202) null.
                  LeshanClient 2021-08-06 16:08:34,884 [INFO] Leshan client destroyed.
```

## Some investigation

Strangely : 
- if I test with same client and leshan-server-demo in my dev machine, I **can not** reproduce this issue.
- if I test in context described above with leshan-client-demo v2.0.0-M4 (cf-2.6.3), I **can not** reproduce this issue.
- if I test in context described above with leshan-client-demo (https://github.com/eclipse/leshan/commit/16025772d79239b093c7026a11615ea0191714cb) (cf 3.0.0-M2) I **can** reproduce the issue

Which seems to vaguely show that maybe 3.0.0 could be the issue but this issue is faced only in the particular context I described above which makes not so much sense :exploding_head: 

I provide some [logs](https://github.com/eclipse/californium/files/6946783/handshake_logs.txt) logs and a [capture](https://github.com/eclipse/californium/files/6946795/capture3.zip). (log and capture was not get in a same run but the issue is the same)

I will let you know if I find something more about this :confused:

**Comment by boaks** [comment]
> 2021-08-06 13:25:47,891 INFO org.eclipse.leshan.client.demo.LeshanClientDemo$2$1$1 [DTLS-Timer-0.0.0.0/0.0.0.0:57355#1] DTLS Full Handshake initiated by client : STARTED ...

it's late. I will investigate that next week. The used leshan is master? Or which tag?

**Comment by boaks** [comment]
Check for EXTENDED_MASTER_SECRET ...

**Comment by boaks** [comment]
[ExtendedMasterSecretMode](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/ExtendedMasterSecretMode.java)

Client enabled, Server not ...

**Comment by sbernard31** [comment]
I will look at this next week too  :)

**Comment by sbernard31** [comment]
I checked about ExtendedMasterSecretMode.

Here is my understanding tell me if I'm right. 

You added support of a new recommended extension (ExtendedMasterSecretMode) since 3.0.

The behavior of this extension is configurable by : `DtlsConnectorConfig.Builder.setExtendedMasterSecretMode(ExtendedMasterSecretMode)`

The default behavior is ENABLED which means that if one of the peer doesn't support the extension the other will not allow session resumption.

So when you are using cf-2.x with cf-3.x with default configuration,  session resumption does not work anymore and this is the expected behavior.

Did I get it ?

**Comment by sbernard31** [comment]
That makes sense to me. 

Just to be sure:

DISABLE : means the extension is never used.
OPTIONAL : means that the extension is used if possible. 
ENABLED : means that the extention is needed  for session resumption
REQUIRED : not sure to get it ? does it means that the handshake failed if the extension is not present ?

**Comment by boaks** [comment]
OPTIONAL is just for the server-side. Allows to resume with extension and without as well.

REQUIRED: yes, a peer will reject the handshake, if the other one doesn't offer that extension.

**Comment by sbernard31** [comment]
Ok thx a lot for the clarification. :+1:

**Comment by sbernard31** [comment]
I rethinking about this. 

And I ask myself, if this behavior change will not be seen as a bug at first sight by most users who are using abbreviated handshake.

I agree with the new feature and the default value but  maybe if there is a way to make this changes more visible. Like maybe a warn LOG ? I'm really not sure about this.

**Comment by boaks** [comment]
> And I ask myself, if this behavior change will not be seen as a bug at first sight by most users who are using abbreviated handshake.

Not that sure. A abbreviated handshake is more or less a compromise between performance and security (considering, that for PSK it's not that relevant and ECDHE requires a full in order to apply the full security). With that, fallback to a full handshake seems for me not to be that problematic.

> but maybe if there is a way to make this changes more visible. 

That would require something, the people read. Maybe [migration hints](https://github.com/eclipse/californium/blob/master/MIGRATION_HINTS.md)?

> warn LOG

On the client side? On the server side that may flush your logs.

**Comment by boaks** [comment]
How did you find out, that full ones are used? Logs? Maybe, then I can adapt the message in order to provide the reason. But in the comment above, it seems to be logs of leshan.

**Comment by sbernard31** [comment]
I guess migration hints is good point. 
I just feel that some user will not look at it. Especially if they don't depends on the library directly but just use tooling based on it. 
The behavior changes could be hard to understand at first sight, but maybe this is not a real issue. 

We will see how many questions about that we get maybe not so much.


> On the client side? On the server side that may flush your logs.

I feel both side could make sense but I agree this may flush. So no good solution.

**Comment by sbernard31** [comment]
> How did you find out, that full ones are used? Logs? Maybe, then I can adapt the message in order to provide the reason. But in the comment above, it seems to be logs of leshan.

(client side - fact) We detect it because we want to test abbreviated handshake on our server. To do that we use last version of leshan-client-demo (not particularly to test the client). That's how we see that leshan-client-demo abbreviated handshake doesn't work anymore with our server. 

(server side - hypothetical ) In our case maximizing  abbreviated handshake is important (probably for not so good reason but out of our control ... :disappointed:). We monitor it using metrics visualization. So if we had migrated without knowing about this change, we would have seen it easily (+ this probably would had caused some charge issue) as a large part of our fleet doesn't support this extension. I guess we could have lost lot of time to investigate. With a LOG I guess the investigation could have been faster.   
(I insist this case is just hypothetical)

**Comment by boaks** [comment]
>  it seems to be logs of leshan.

My point is, that if you check the Leshan logs, adding messages to the Californium logs won't help :-).

And I would prefer to use "DEBUG", not "WARN". For the client I will provide a Californium PR.

**Comment by sbernard31** [comment]
> My point is, that if you check the Leshan logs, adding messages to the Californium logs won't help :-).

I don't check just Leshan logs :-).
I check default visible logs. Concerning leshan demos,  default one are INFO for Leshan and WARN for all others. (+ some specific one in debug)

For a client generally, if issue is found, doing a massive log level changes using TRACE or DEBUG is not an issue. 

For a production server, we can not do that as this will flush too much.  So we need to target log to activate. (sometime not so possible to active TRACE or DEBUG log because of too much log). a WARN help to detect it immediately (with drawback that deactivate this log will hide other important LOG). 
Facing this kind of issue, I guess just after watching default log, we try to activate some INFO or DEBUG logs for pertinent class In this case probably for DTLSConnector.

**Comment by boaks** [comment]
See PR #1694
