### ISSUE TITLE
[Bug] Block2 cannot be returned for first block

### ISSUE THREAD

**Issue by sharkwouter** [eclipse/californium#1696]
When a client makes a GET request to a Califonium based server and the response does not fit in a single block, because of the maximum block size, the server cannot send the Block2 option along with the response. This is because Californium prevents Block2 from being send by the server if the current block is the first one (num=0). What the Block2 of the request is set to does not matter in this case, since Californium will strip it from the request. The code which is causing this behavior can be found here: https://github.com/eclipse/californium/blob/261ed2c5180e91aab873a1e39e3bff08a58d13b1/californium-core/src/main/java/org/eclipse/californium/core/network/stack/BlockwiseLayer.java#L566-L614

This is in the 2.6.x branch. From what I've seen this behavior is the same in 3.x.x and master, but I have not tested it there.

In the specification for blockwise transfer in COAP, it is specified that if the response doesn't fit in one response, the server communicates this in the request by setting the Block2 options szx/m/num to szx/true/0. See [here]:

```
   Once the Block2 Option is used by the requester and a first response
   has been received with a possibly adjusted block size, all further
   requests in a single block-wise transfer will ultimately converge on
   using the same size, except that there may not be enough content to
   fill the last block (the one returned with the M bit not set).  (Note
   that the client may start using the Block2 Option in a second request
   after a first request without a Block2 Option resulted in a Block2
   Option in the response.)
```
If it makes sense to you, I could propose a change in this behavior in a PR. I'm currently working on a test which can show this behavior.

**Comment by boaks** [comment]
Could you please create [logs&captures](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information)?

The case you describe seems for me to be very basic and works for 1000's of users well.
So I'm not sure, what goes wrong in your case. But logs and captures may bring some light.

**Comment by boaks** [comment]
Which client implementation do you use?

**Comment by sharkwouter** [comment]
It was a configuration error on my side. Thanks for responding!

**Comment by boaks** [comment]
Thanks for your feedback and closing the issue.
