### ISSUE TITLE
Why scandium only support ECDSA signed in CertificateRequest?

### ISSUE THREAD

**Issue by TerenceYi** [eclipse/californium#1697]
1. Learning from the code that scandium only using ClientCertificateType.ECDSA_SIGN in the CertificateRequest, can anyone share more detail? 

2. Does there exists any concern that if add more supported CertificateType? for example ClientCertificateType.RSA_SIGN

**Comment by boaks** [comment]
Because ECDSA is mandatory for CoAP (see issue #517, [RFC7252.](https://tools.ietf.org/html/rfc7252#section-9.1.3.2) ).

ECDSA uses smaller keys (less data to transmit) and is faster.
So, why should someone invest time in RSA?

Anyway, you may cooperate with issue #1693

**Comment by boaks** [comment]
Just to mention, the `CertificateRequest` already contains:

Signature Hash Algorithms (2 algorithms)
    Signature Algorithm: ecdsa_secp256r1_sha256 (0x0403)
    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)

But Californium doesn't support it for the node's certificate, only for CAs. 
That limitation is not even related to the `TLS_ECDHE_ECDSA_WITH_???` cipher suite, though that only defines what should be used for the key-exchange.
But the work, which would be needed to implement it, is for me not worth to spend.
