### ISSUE TITLE
client x509 certificate without "TLS server auth" not accepted

### ISSUE THREAD

**Issue by vitali42** [eclipse/californium#1704]
Followin setup was used:

 - Leshan demo Server (2.0.0-M4)
 - Leshan demo client (2.0.0-M4)
 - as part of Leshan release 2.0.0-M4 Californium 2.6.3

 - Leshan demo client tries to connects to Leshan demo server using x509 certificate authentication
    but failed with an error message:

```
Unable to create and start client ...
java.lang.IllegalStateException: certificate has no proper key usage as servers!
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:3493)
        at org.eclipse.leshan.client.californium.CaliforniumEndpointsManager.createEndpoint(CaliforniumEndpointsManager.java:204)
        at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.factoryBootstrap(DefaultRegistrationEngine.java:195)
        at org.eclipse.leshan.client.engine.DefaultRegistrationEngine.start(DefaultRegistrationEngine.java:180)
        at org.eclipse.leshan.client.californium.LeshanClient.start(LeshanClient.java:267)
        at org.eclipse.leshan.client.demo.LeshanClientDemo.createAndStartClient(LeshanClientDemo.java:888)
        at org.eclipse.leshan.client.demo.LeshanClientDemo.main(LeshanClientDemo.java:621)
```
  - client certificate has following content: 

```
 Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3376027825896665380 (0x2eda0f6bb267b124)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = IoT ECC CA
        Validity
            Not Before: Oct 28 09:51:45 2020 GMT
            Not After : Oct 29 09:51:45 2035 GMT
        Subject: CN = TEST_XXX
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:f7:b6:c2:8d:66:74:4c:e1:dd:ca:f7:e5:99:25:
                    a2:72:6e:34:e8:13:76:de:9b:0d:9c:b7:a2:40:5a:
                    fa:10:ea:f0:62:54:b9:c3:84:ba:81:cc:a3:4d:93:
                    08:52:68:5a:69:8d:cd:52:a8:04:8e:f3:2c:81:ed:
                    78:73:36:18:ba
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Authority Key Identifier:
                keyid:XXX

            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Subject Key Identifier:
                XXX
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:3d:2b:e3:e7:16:5f:01:e6:4c:47:99:ca:8b:e2:
         b5:6a:60:7a:34:16:98:73:e4:d2:07:b6:11:17:fc:a1:aa:44:
         02:21:00:af:c6:47:d5:27:78:0a:10:78:2f:5e:9b:ba:66:98:
         58:d2:68:96:87:04:d3:c4:5c:08:89:a8:24:ee:60:02:ea

```
Please note: Extended Key Usage is specified for client auth only, not for server. 
If the EKU is ommited completelly in the certificate (e.g. self signed cert), it will be accepted as valid and
DTLS connection is establishad successfully. Also other TLS stacks  like mbedTLS, wolfSSL don't
require extended key usage for server auth even for LWM2M protocol.

If it is desired/necessary implementation, could you please provide the reference specification (e.g. RFC)
why are both clien and server auth usage are mandatory for such kind of leaf certs.

Many thanks in advance,
   vitali

**Comment by boaks** [comment]
> Also other TLS stacks like mbedTLS, wolfSSL don't require extended key usage for server auth even for LWM2M protocol.

Sure, they don't support a "DTLS role exchange" (dtls-client and dtls-server are exchanged), and so they can stick to the client-role. If you want that, just configure the Leshan client to "client only" using [DtlsConnectorConfig.Builder.setClientOnly()](https://github.com/eclipse/californium/blob/2.6.x/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConnectorConfig.java#L1558).

(Please, though this is related to the Leshan client, also ask there for recommendations and support.)

**Comment by boaks** [comment]
Please read [leshan - Add Certificate usage support to leshan demos](https://github.com/eclipse/leshan/pull/991) for further explanation.

From the view of Californium:
If you want a Endpoint, which may act in both DTLS roles (client and server), then your certificate must indicate that usage. For historical reasons, that also the default.
If you want a client-only or server-only Endpoint, just configure the DTLSConnector accordingly.

**Comment by sbernard31** [comment]
@vitali42, maybe it makes sense to modify **leshan-demo** to automatically set the client as `clientOnly or serverOnly` depending key-usage. Please [open a leshan issue](https://github.com/eclipse/leshan/issues/new) to talk about this.

**Comment by sbernard31** [comment]
thx for opening the issue (https://github.com/eclipse/leshan/issues/1081)

I guess we can close this one now ?

**Comment by vitali42** [comment]
configuring DTLS connection as "client only" solves the issue, "thanks to @boaks
