### ISSUE TITLE
Dynamic Configuration Definition.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1708]
This ticket concerns the new Configuration Design (#1648)

-------------------------
**The current static way :** (available in `master`)
The new `Configuration` need `Definition` to work and currently all the configuration share definitions in a static MODULES field.

```java
 /**
 * Map of registered modules.
 */
private static final ConcurrentMap<String, DefinitionsProvider> MODULES = new ConcurrentHashMap<>();
```

Definitions are defined in class like `UdpConfig`, `DtlsConfig`, `CoapConfig`, ...  (name is a bit confusing but this is not `Configuration` just module which contains Definitions)  
Those Definitions  are added "automatically"  by some static block/code like : 
```java
public final class DtlsConfig {
         /**
	 * Scale factor applied to the retransmission timeout. Harmonize CoAP and
	 * DTLS.
	 */
	public static final FloatDefinition DTLS_RETRANSMISSION_TIMEOUT_SCALE = new FloatDefinition(
			MODULE + "RETRANSMISSION_TIMEOUT_SCALE", "DTLS scale factor for retransmission backoff-timeout.", 2.0F, 1.0F);
	...  ...
		
	static {
		SystemConfig.register();
		Configuration.addModule(MODULE, new DefinitionsProvider() {

			@Override
			public void applyDefinitions(Configuration config) {
				config.set(DTLS_RETRANSMISSION_TIMEOUT_SCALE, 2.0F);
				config.set(DTLS_SESSION_TIMEOUT, 24, TimeUnit.HOURS);
				config.set(DTLS_AUTO_HANDSHAKE_TIMEOUT, null, TimeUnit.SECONDS);
                                ... ...
				config.set(DTLS_USE_DEPRECATED_CID, null);
				config.set(DTLS_SUPPORT_DEPRECATED_CID, false);
			}
		});
	}

	public static void register() {
		SystemConfig.register();
	}
}
```

Drawbacks: 
 - User doesn't clearly control what happens (mitigated if user choose this new API #1701)
 - Sometime user will need to use the `register` method but sometime this will be done in an hidden way. (it could be confusing)
 - code is more complicated (like need to use threadsafe mechanism) 
 - static way is generally considered as bad practice. 

-------------------------
**Why not using a more dynamic way ?**
Reason until now are : 
- too time costly to develop 
- with static way register is done only one by application where a dynamic way need to always explain which module to use. 
- could be error prone for user (generate some odd behavior if badly used)

I can invest some time in the refactoring.
And I feel there is a dynamic/not so error prone/ way to go. 

---------------------------
**The proposition :**

I propose to make `Configuration` an abstract key->value container without `Definition`.
(So it's not directly possible to create an instance of `Configuration`)
And then we have concrete class which extends `Configuration` with their definition. 
A `CoapConfiguration` (or we reuse `CoapConfig`) with all definition needed by `californium-core`.
A `DtlsConfiguration` (or we reuse `DtlsConfig`) with all definition needed by dtls connector of `scandium`.
A `UdpConfiguration` (or we reuse `UdpConfig`) with all definition needed udp connector.
A `TcpConfiguration` (or we reuse `TcpConfig`) with all definition needed tcp connector.
(Note that : Californium component can be configured by passing this kind of object as nothing force to share the same Configuration for all of them)

And then we have a  `MultiModuleConfiguration` which takes module as constructor parameters and so allow to create a common Configuration with all the definition needed. (Just in case you want all in one Config e.g if you store all in same file)

As user can not create a `Configuration`, he will need to check the javadoc to know how to pass a `Configuration` object requested by the API and where we point both solution. 

To make this even less error prone,  we can also imagine that : 
 - we do not allow setting value for an absent definition.
 - on get if the definition is absent log a warn (and return the default value) 

if wanted Instead of concrete `Configuration` we can have several `ConfigurationBuilder` or `ConfigurationFactory` with pretty much the same idea. Maybe with the benefits to allow  : 
- a more easily way to make the Configuration  immutable.
- make easier to configure once to create several config.
- separate more easily serialization/deserialization from Configuration class

(more historical discussion about this here : https://github.com/eclipse/leshan/pull/1073#discussion_r687709259)

**Comment by sbernard31** [comment]
(@boaks I will be out of office in few minutes and will be back begin of September so you have time to think more abou that)

**Comment by boaks** [comment]
Again, I already wrote that in the leshan PR:

For me the static way is fine. I don't see the benefit in a more dynamic way.
If you want to demonstrate the benefits of the dynamic way in leshan, it's sure possible to open the API to to so (as alternative). Therefore PR #1701 .

For me, the most important topic is to release the 3.0. 
With or without a new Configuration. The Configuration may be postponed to a 4.0, e.g. gives everyone, who want to spend time in it, a couple of months to work on an alternative to demonstrate further benefits.

I'm not sure, what other thinks about a 3.0, with or without the new Configuration. I'm even not sure, if we get some additional statement about that at all.

**Comment by sbernard31** [comment]
> If you want to demonstrate the benefits of the dynamic way in leshan

I talked about Californium code design. I'm not sure how this is related to Leshan ? 

> it's sure possible to open the API to to so (as alternative). 

The idea is to remove the static way. 

> For me the static way is fine.

There is plenty resource about good/bad practice in computer science which explain why static way should be avoided. 
My understanding is that is Dynamic way should be the default way. When you decide to go to a static way you should have a good reason. 

I would like to know if you agree with this statement  above :point_up: ? 
and if you agree what is the reason to keep the static way ?

**Comment by sbernard31** [comment]
> I don't agree with the statements about static above.

If you disagree with this basic statement about how to write better Oriented Object code I guess we will go in an endless discussion. 

>  Such general statements about best practice are most no best practice themself.

This is the kind of sentence which seems smart but could also just be pretentious.

> you will find out, that the cons don't apply too much

I disagree e.g ;  "unknown state of the configuration object". (Eg. state changes depending which class is loaded ...)

Even if this was true  (I don't think it is).  Why doing something which will be considered as code smell to most people if you can do it in a more classic way. 
Eventually you can do that for a personal project but on a community project this is harder to argue.

> Because you may easy demonstrate the benefits there.

This is about how the code is written in californium. I don't get your point at all.

**Comment by boaks** [comment]
@sbernard31 

I guess, you don't work on this. Do you consider to leave it open for someone else? Or is it OK to close it?
