### ISSUE TITLE
HttpTranslator hardcoded path

### ISSUE THREAD

**Issue by nxSwe** [eclipse/californium#172]
HttpTranslator has the following member:

`public static final Properties HTTP_TRANSLATION_PROPERTIES = new MappingProperties("Proxy.properties");`
And then it automatically writes to that file when using the class. Sometimes this is not preferable as the user may not have the rights to write there.

An idea is to make the HttpTranslator methods non-static, and that the class instead had constructors/builder methods to either use the default configuration or to point out a path/filename where to get/write the file.

**Comment by sophokles73** [comment]
Sounds good :-) Would you care to provide a PR?

**Comment by boaks** [comment]
Your PR is merge, so this should be fixed.
