### ISSUE TITLE
Which version of DTLS Connection ID is supported

### ISSUE THREAD

**Issue by JaimieW** [eclipse/californium#1725]
I see that scandium supports dtls connection ids for both client and server.
Can you clarify which version of draft-ietf-tls-dtls-connection-id is supported?
The wiki page points to v07, but the latest version is v13:
https://datatracker.ietf.org/doc/draft-ietf-tls-dtls-connection-id/
My colleague working on the client has pointed out that the MAC computation has changed.

I'm currently using californium v2.3.0 as the dtls server.
The dtls client is a proprietary implementation for constrained devices.

Thanks,
Jaimie

**Comment by boaks** [comment]
The current release 2.6.5 supports the MAC and extension code-point (53) definition before v09, 
the upcoming 3.0.0 supports the new MAC and extension code-point (54) definition of v13.
The upcoming 3.0.0 contains also a configuration switch, to enable the server to support the old definition as well (`DTLS_SUPPORT_DEPRECATED_CID`). RRC is not implemented.

> I'm currently using californium v2.3.0 as the dtls server.

Please update to 2.6.5.

**Comment by JaimieW** [comment]
Perfect, thank you.
