### ISSUE TITLE
some demo with official 3.0.x API

### ISSUE THREAD

**Issue by fizarum** [eclipse/californium#1728]
Where can I find some java/android examples or demo with official 3.0.x API?
Demo for android is based on SNAPSHOT version which has additional not released API
Thnx for helping!

**Comment by boaks** [comment]
The "official 3.0.x API" is not yet fixed ;-).

I consider the current 3.0.0-SNAPSHOT to be very close to the "final API". 
Hoping, that the voting #1709 can be closed begin of next week. 
With that, the final cleanup of the configuration could be started. 
Depending on many things, that may result in RC1 on next Friday (17.9.) or later (e.g. 1.10.).

**Comment by boaks** [comment]
Do you have some special concerns about the API and the usage with Android?

**Comment by sbernard31** [comment]
> Hoping, that the voting #1709 can be closed begin of next week.

What makes the vote closable ?

**Comment by boaks** [comment]
My basic idea is just to close it and see, if that causes complains :-).

**Comment by sbernard31** [comment]
It's really hard to me to understand how this decision will be taken ? :thinking: 


You start a vote open to everybody on your own initiative without really explained how it works.

Then I guess you will follow the result of this vote to take the decision, considering that opinions from:
- unknown user  without any explanation about her choice 
- committer with explanation 
- eclipse project consumer with explanation

have strictly same value.

Correct ?

**Comment by boaks** [comment]
@sbernard31 
@sophokles73 

I don't think, this `static` is worth that discussion.
I don't see, that this voting is different from other ones. 
In fact, i would now like to ask you, Simon, to really stay off, as you announced a year ago.
Thanks!

**Comment by sbernard31** [comment]
>  In fact, I would now like to ask you, Simon, to really stay off, as you announced a year ago.

Could you clarify what means `stay off` exactly ? 
As Leshan eclipse project consumes californium, I can not be totally `stay off`, so could you explain exactly what is allowed to me concerning californium ? 

Eclipse project are open development project. So I would also understand how you understand open development ?

**Comment by boaks** [comment]
> as you announced a year ago.

**Comment by fizarum** [comment]
>The "official 3.0.x API" is not yet fixed ;-).
Oh, I see, now it explains these differences :)

>Do you have some special concerns about the API and the usage with Android?
Nope, just find some differences between API when tried to configure CoapServer and dtls connection. Anyway, its not big issue to use snapshot version of libraries for a while.

> ... in RC1 on next Friday (17.9.) or later (e.g. 1.10.).
Nice to hear it!

**Comment by sbernard31** [comment]
> as you announced a year ago.

This was not an "announce" but a private message which tried to improve a complicated situation.
(By the way pretty strange to refer to a private message in public discussion)

As you don't even answer to questions, I don't know what to do more. Hoping that @sophokles73  will be able to do something.

**Comment by sophokles73** [comment]
I guess everybody needs to calm down a little, take a step back and remember that we are all participating in an open source project following the Eclipse Development Process. In particular, this means that we maintain a *level playing field* and try to establish an open and welcoming environment for contributors. The latter also holds true for existing committers, of course.

Based on that and assuming my role as the Cf project lead, I would like to strongly suggest that you refrain from statements like the one below, @boaks .

> I don't see, that this voting is different from other ones.
In fact, I would now like to ask you, Simon, to really stay off, as you announced a year ago.
Thanks!

That said, I think we (@boaks , @sbernard31  and I) should get together and talk about how we make architecture decisions and how we resolve dissent while keeping everybody comfortable in the process. I will get in touch.
