### ISSUE TITLE
Is there any access to Request object in API 3.0.x?

### ISSUE THREAD

**Issue by fizarum** [eclipse/californium#1737]
Hi,
I'm trying to log information about CoapClient's request and cant find any reference (public) to this object.
I can create instance of Request manually but can't fully initialise it. For example I cant set correct Type (Enum CoAP.Type) since its private filed of CoapClient class.
Is there any method to get configured Request object?
Thnx for help!

**Comment by boaks** [comment]
> cant find any reference (public) to this object.

I'm not sure, what you consider as "public". 

I would just use [Request](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/Request.java) and one of the both [CoapClient.advanced()](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/CoapClient.java#L1060) methods.

**Comment by fizarum** [comment]
> I'm not sure, what you consider as "public".

I mean, I want to get an instance of request object for further storing (I need raw byte representation of request)


I'm trying to do GET and get Request instance, so I see one of API get method:
```
public void get(CoapHandler handler) {
	Request request = newGet();
	assignClientUriIfEmpty(request);
	asynchronous(request, handler);
}
```

inside of `newGet()` we have:
```
request.setType(this.type);
```
and `this.type` (enum Type) is private field which I can't get from application side
I can do it by your recommendation:
```
private Request doGet(CoapClient client, CoapHandler handler) {
	Request request = Request.newGet(); // <- its not the same as CoapClient.newGet() !
	//todo: add place to set request type
	client.advanced(handler, request);
	return request;
}
```
Here I don't have access to `CoapClient.newGet()` which does all required job, so used `Request.newGet()`

Ideally it can be extended like: 
```
public interface CoapHandler {
	public void onLoad(CoapResponse response);
	public void onLoadWithRequest(CoapResponse response, Request request);
	public void onError();
}
```
In this way I can get request with response
Sorry for, maybe strange questions, I still investigate this library and don't know all stuff here :)

**Comment by boaks** [comment]
> (I need raw byte representation of request)

Therefore you use an [UdpDataSerializer](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/serialization/UdpDataSerializer.java) or [TcpDataSerializer](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/serialization/TcpDataSerializer.java).

Just to say: if you have that, it will be strange to send it via Californium. That's not really intended. I'm not sure, what you really want to implement. If you want to use an custom transport-layer, use a custom [Connector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/Connector.java) implementation.

I'm not sure, just in the case your other questions are still relevant:

> and this.type (enum Type) is private field which I can't get from application side

For the `CoapClient` `CoapClient useCONs()` and `CoapClient useNONs()` are used to set that type.
For a Request this is done by using `Message.setConfirmable(boolean con)`or `Message setType(CoAP.Type type)`. There is no need to consider that private filed of the `CoapClient`, if you create the Request by your own.
(see also [CoAP.Type][https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/CoAP.java#L363) ).

I don't think, that extending the `CoapHandler` makes too much sense. If you just want the bytes, use the Serializer. if you want to use custom transport-layer (e.g. Bluetooth LE), the implement a custom Connector. That's of course not that easy and would require some more knowledge about CoAP and about the Californium "EndpointContext/EndpointContextMatcher".

**Comment by boaks** [comment]
Let me add: without knowing, what you really want to achieve, it's hard to help. if you want to understand more about the exchange of messages, there is also the "advanced possibility" to use a [MessageInterceptor](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/interceptors/MessageInterceptor.java), e.g. similar to [MessageTracer](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/interceptors/MessageTracer.java). You need to add that to your `CoapEndoint`using `addInterceptor`. If you not explicitly build a `CoapEndoint`, then check 

```  
EndpointManager.getEndpointManager().getDefaultEndpoint(request.getScheme());
```

for the default endpoint of the CoapClient.

**Comment by fizarum** [comment]
First of all, thnx for helping!

Agreed, I have to share some details.
I'm working on mobile app which should communicate with "black box" by CoAP over BLE. So I have to move communication layer to bluetooth one.
That's why I need to transfer all CoAP serialised packages (messages) by bluetooth to that "black box"
For now I'll check UdpDataSerializer & TcpDataSerializer and https://datatracker.ietf.org/doc/html/rfc7252 for better understanding the structure of packets.
I'll try to update this thread with my results asap.

**Comment by boaks** [comment]
> CoAP over BLE

OK, as I wrote already above, I would recommend to use a custom [Connector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/Connector.java) . Depending on using "additional encryption" or not, you may just start by modifying the [UDPConnector](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/UDPConnector.java).

**Comment by fizarum** [comment]
Ok, looks like everything works as expected, I can get request & responses by implemented customised DTLSConnector with added internal RawDataChannel listener.
Thnx for helping!

**Comment by qbasso** [comment]
Hey @fizarum could you share a snippet how you were able to establish DTLS connection over BLE with `RawDataChannelListener`? I am having problems setting it up

**Comment by boaks** [comment]
Not sure, what a `RawDataChannelListener` will help.

If you use a current version (3.14.0 or 4.0.0-M) the [DTLSConnector](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java) has a [receiveNextDatagramFromNetwork](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1671-L1680) and a [sendNextDatagramOverNetwork](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L3291), that are good candidates to receive and send the bytes. You will need to map the ip-addresses somehow.

**Comment by qbasso** [comment]
@boaks thanks for the response. Seem like you are right, I hoped there is easy way of using BLE as a transport layer, but doing what you suggested I was able to complete DTLS handshake, and `RawDataChannelListener` is not intended for this. I overrode `sendNextDatagramOverNetwork` to transport data over BLE and when I got response on BT interface, I passed byte data to `connector.processDatagram()`.
