### ISSUE TITLE
Question - RST response to Non-Confirmed messages

### ISSUE THREAD

**Issue by paddlebike** [eclipse/californium#1739]
- I'm using the Leshan (Demo) Server which I believe is using Californium 2.6
- The client devices are cellular modems using LwM2M 1.0 UDP over spotty cellular coverage
- I am seeing Non-confirmed messages received at the leshan server and the server responds with a RST message.
- My main question is this required by COAP?  From my reading it seems that non-confirmed message should not get a RST response (but RFC7252) is not explicit on this.
- Below is a Notification and RST response (some payload data stripped)

13:47:51.949630 IP (tos 0x5c, ttl 57, id 12, offset 0, flags [none], proto UDP (17), length 311)
    10.7.7.2.53764 > 172.16.10.145.5683: UDP, length 283
	0x0000:  455c 0137 000c 0000 3911 b8a4 0a07 0702  E\.7....9.......
	0x0010:  ac10 0a91 d204 1633 0123 0307 5845 a3c4  .......3.#..XE..
	0x0020:  b7a0 33b2 55d8 d4e5 6113 60ff 

13:47:51.950254 IP (tos 0x0, ttl 63, id 14527, offset 0, flags [DF], proto UDP (17), length 32)
    172.16.10.145.5683 > 10.7.7.2.53764: UDP, length 4
	0x0000:  4500 0020 38bf 4000 3f11 3b64 ac10 0a91  E...8.@.?.;d....
	0x0010:  0a07 0702 1633 d204 000c c7c7 7000 a3c4  .....3......p...  

This is causing a problem with the modem we are using causing it to sometimes stop sending registration updates.

**Comment by boaks** [comment]
That's a longer story :-).

If you start a observer/notify relation, RFC7641 assumes, that the ip-endpoint of your server is stable.
In many scenarios, that's not the case. For that, it's required to adapt RFC7641, which doesn't come without risk.

So, let me first ask: between the observe-request and the notify, did the ip-address of your device (coap-server) change?

**Comment by paddlebike** [comment]
I'm using all static IP addresses and I verified in the traces that they are not changing.

Thanks for pointing out RFC7641 that was very helpful.  It looks like there are 2 possibilities.
a) The leshan server thinks that the Notification MID is out of sequence and takes the option to send a reset.
b) There is a problem in my observation handling that is causing the server to believe that the observation ID is no longer valid.  (Probably the more likely).

Does Californium take the option to send a RST to an out of sequence non-confirmable Notification?

Many thanks for the quick response!
Ken

**Comment by boaks** [comment]
You're welcome.

The MID should not be an issue (except you send more messages). But the token is very important.

> Does Californium take the option to send a RST to an out of sequence non-confirmable Notification?

I'm not sure, what you mean by "out of sequence"? Californium sends a RST, if there is no observation registered (by token) on the coap-client (lwm2m-server). 

Just to mention: [Wiki - Capture](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information) contains some instructions, which may help to capture your traffic. That usually contains a lot of information. Please use time to select the right messages, otherwise you may "leak" too much information, if you send a capture of all your traffic.

**Comment by paddlebike** [comment]
I am able to verify that lost messages (gaps in the MID) do not cause a RST. (That is what I meant by "out of sequence".
The issue was at least in part to my leshan code sending a new Get/Observe while the modem was sending notifications.  On occasion the modem would send a notification using the "old" token causing the RST as a reply.

The Wiki - Capture page is very helpful

Thanks again for your help!
