### ISSUE TITLE
Private getter for others in OptionSet

### ISSUE THREAD

**Issue by navoda** [eclipse/californium#176]
Is there a purpose for make the `getter` method `private` [here](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/OptionSet.java#L1268).

I need to set other options. But the `private getter` restrict to access other option list.

**Comment by sophokles73** [comment]
You can add other options using the (public) [`addOption(Option)`](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/OptionSet.java#L1337) method.

**Comment by navoda** [comment]
No I wanted to access the options set in a message. But think I can get it with `[asSortedList](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/OptionSet.java#L1281) `method. Not a good solution but can work with that. Thanks :)
