### ISSUE TITLE
Are there considerations about different request types?

### ISSUE THREAD

**Issue by fari112** [eclipse/californium#1762]
For a project I would like request types like patch or something like this. Even if they are not in RFC 7252 it would be nice to have them.

**Comment by boaks** [comment]
Only very generic. 

The codes are included [CoAP.Code](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/CoAP.java#L476-L482) and these codes are reflected in [CoapResource.handle???](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/CoapResource.java#L277-L311).

That isn't really different to the other codes, so maybe you give us more hints, what you expect?

**Comment by fari112** [comment]
Is there a way to use these with the client? So you can maybe make a request like: ```client.patch();```

**Comment by boaks** [comment]
I see. 

Yes, the `CoapClient` doesn't support this. For now you may create the request by `Request.newPatch()` and use `CoapClient.advanced(Request request)`.

In the future, it may be possible to add that as well. Are you interested to  contribute that extension?
Otherwise we will see, when I can spend some time in.

**Comment by fari112** [comment]
Thanks for the answer. Do you have a little example for that? 

At the moment I have to concentrate on finishing my bachelor´s degree but after that maybe.

**Comment by boaks** [comment]
> Do you have a little example for that?

AFAIK, FETCH is similar as GET, so I guess, "copy&modify" the `CoapClient.get(???)s` will be a point to start.
And adding the "handle???" methods to the "HelloWorldServer" may also be an idea. The others have also their similars. 

> At the moment I have to concentrate on finishing my bachelor´s degree but after that maybe.

We will see.

**Comment by boaks** [comment]
@fari112 

Do you still have interest in working on this? Or could it be closed?
