### ISSUE TITLE
Infinite ping pong under TcpStack

### ISSUE THREAD

**Issue by joemag1** [eclipse/californium#178]
If a TcpStack receives an empty message (which is possible, if for example the peer receives a badly formed message and calls CoapEndpoint.reject()) this will initiate an infinite ping pong. This happens because the peer receiving an empty message will itself send an empty message to the friend.

The offending line of code is in CoapEndpoint.reject(), where it checks if type is CON (under TCP we always hard code message type to CON, because we have to set it to something), it will send reject empty message. Which will trigger the same exact thing on the other peer.

The ping that initiates such ping pong is likely a failed message parsing, inside CoapEndpoint.receiveMessage() method.

**Comment by boaks** [comment]
Hm, I didn't test it, but I thought, that both
TcpMatcher.receiveEmptyMessage and TcpAdaptionLayer.receiveEmptyMessage should discard the EmptyMessage on receiving. So doesn't this work?

**Comment by boaks** [comment]
Ok, now I see, that's the InboxImpl!

**Comment by joemag1** [comment]
This code path skips the stack and goes directly to the connector.

**Comment by sophokles73** [comment]
fixed on master in fd9abfbdd3359533cfd50ed7bd93d3ccf08e6722
fixed on 2.0.x in 0f81d787068c940f89441037f3103c24694dee5e
