### ISSUE TITLE
DTLS with PSK

### ISSUE THREAD

**Issue by ce237** [eclipse/californium#1792]
Hi,

Actually i am having problems with DTLS connection and my aim is to be able to encrypt all data with a Pre Shared Key (PSK) before sending it to the californium server.

Any idea on how i may do that. I am very new in this area.

Best regards,

Cedric

**Comment by ce237** [comment]
Hello @boaks 

i am using the resource "create" from Plugtestserver to send a JSON payload "{"command":"periodic","type":"8","number":"33"}" using the PUT-method from CoAP, but the server response is "Bad request":

[trace-2021-10-29T11-50-24.530Z.zip](https://github.com/eclipse/californium/files/7459237/trace-2021-10-29T11-50-24.530Z.zip)

Despite the fact that Json is one of the context format from CoAP. 

Can you please tell me, what i am doing wrong? May be is my annotation wrong or can i send a JSON Payload in the first place?

Thanks in advance

**Comment by boaks** [comment]
1. you don't read the tutorial for captures, otherwise you would select the dtls/coap messages and not just send "all".
2. for reasons, unknown to me, the plugtest server requires you to send the "content format" option. That is also indicated by the response error text in the capture: 4.00 BAD REQUEST, "Content-Format not set".
3. you can sure send JSON as payload. If you use also the content-format-option with the value JSON, then the plugtest server would be much happier. Option 12, application/json 50 (see RFC7252, maybe also time to read that).
4. the payload in the message seems to be messed up, at least in the capture. The payload in the capture show 28 'A' at the begin, followed by 71 times a 0x00.

So, time to start to read :-).

**Comment by boaks** [comment]
@ce237 

Before you start to wonder, the sandbox's ban file contains:

```
coaps Option Content-Format value of 3 bytes must be in range of [0-2] bytes. 
```

Though it's coaps, it may be your device. If you send malicious messages, Californium will ban your device's ip-address for a while. That's also a good reason to run a coap-server on your own. CoAP options are "well defined", I'm not sure, what your client library offers as API. Some API cares for you to comply to [RFC7252 5.10](https://datatracker.ietf.org/doc/html/rfc7252#section-5.10), others offering a raw access and your code must obey the definitions. For content-format, its:

```
12,  Content-Format, uint, 0-2
```

**Comment by ce237** [comment]
Hello @boaks ,

Thank you very much for the informations.

I sent a Json Payload without having to do a DTLS handshake, meaning i used normal UDP. Here is what i got:

[test_non_secure.zip](https://github.com/eclipse/californium/files/7473594/test_non_secure.zip)

For me i think the server responded properly. What do you think please?

In the meantime i have the following issues:

1. The time it takes for my device to connect to the network is too long (more than 10mins). And i think that's not normal and i don't know why the connection time is so long.

2. When i connect to the server, i want the connection between my device and the server to stay. Is it possible in the first place? when yes, are there any configurations i have to make?

Thanks in advance

**Comment by boaks** [comment]
> For me i think the server responded properly. What do you think please?

The payload you send is "{\n\t" 3 (bytes), I guess that's wrong

> The time it takes for my device to connect to the network is too long (more than 10mins). And i think that's not normal and i don't know why the connection time is so long.

I guess, the device tries out a couple of bands, may be even not only CAT-NB also CAT-M1. The solution should come from the modem manufacturer. (I use also the nrf9160 and with my sim-card and selecting CAT_NB and the proper band of my provider, it takes about 2-3s, in some cases up to 60s.)

> When i connect to the server, i want the connection between my device and the server to stay. Is it possible in the first place? when yes, are there any configurations i have to make?

I don't know, what you exactly mean. Usually UDP doesn't "connect", it just send udp-messages.

With dtls, these messages must be encrypted/decrypted using session/association's keys. Though this is normally referred by the ip-address/port, it only works, if your device keeps them. But AFAIK, with iBasis, that is not supported. So, back to my answer in the nordic forum: you have to wait for DTLS CID. With that, the dtls keys are referred by that cid and so  static ip-address is not longer required.
But it is still required, that the device initiates the communication. And after a couple of seconds without message exchange (e.g. 30s) it will get unreachable by the server. But that IP and your mobile provider, not dtls not coap, and so Californium can't do anything for it. (Except sending a lot of messages and keep the device awake :-) ).

**Comment by ce237** [comment]
> The payload you send is "{\n\t" 3 (bytes), I guess that's wrong

 am creating my JSON Payload with the following function:

cJSON * createJsonFromParams(void)
{

    cJSON *root = cJSON_CreateObject();
    cJSON_AddNumberToObject(root, "JSON", 50);
    cJSON_AddNumberToObject(root, "Content-Form", 12);

return root;

}

The main function :

    cJSON_Init();
    cJSON *item = createJsonFromParams();
    char *payload=cJSON_Print(item);

Do you think it is the appropriate way of forming my JSON Payload?or will this be suitable for the server?


And i really want to thank you again for helping me and for you precious time .

**Comment by boaks** [comment]
I'm not cJSON specialist, but I guess `payload` point to the right serialized JSON,

```
{
    "JSON": 50,
    "Content-Form": 12
} 
```

But, when you set it as payload, the length is accidentally truncated to 3.

**Comment by boaks** [comment]
> Do you think it is the appropriate way of forming my JSON Payload?
> or will this be suitable for the server?

Though, it's unclear, what you want to send as JSON, I can't say to much. In the last trace the content-format option seems to be well, but the payload only contains 3 bytes and was no valid JSON.  Though Californium doesn't care on it's own, if the payload is valid JSON, it respond with created.

**Comment by ce237** [comment]
Hello @boaks,

it's me again. Sorry for disturbing.

I can't reach the californium server over NB-IoT. Here is what i got:

[log trace_NB_IoT.zip](https://github.com/eclipse/californium/files/7505604/log.trace_NB_IoT.zip)

ERROR: getaddrinfo fehlgeschlagen -11: which stands for No more processes.

what does that means for me? any idea?

NB: with LTE-M everything works perfectly

**Comment by boaks** [comment]
That's more a question for the modem's manufacturer.
And I see, that you have already asked there.

**Comment by boaks** [comment]
The only, not that brilliant work-around may be, not to use "californium.eclipseprojects.io" and instead the literal-ip-address "35.185.40.182". Or to wait a little, and retry the getaddrinfo say 5s later.

**Comment by ce237** [comment]
> The only, not that brilliant work-around may be, not to use "californium.eclipseprojects.io" and instead the literal-ip-address "35.185.40.182". Or to wait a little, and retry the getaddrinfo say 5s later.

Ok thanks for your suggestion. It worked

**Comment by ce237** [comment]
Hi @boaks,

 i want to thank you once again for all your help. Because of you i really made progress and i am very grateful for that.

I was able to send a same payload every 30s and the Server responded appropriately. But all of a sudden when i send the server didn't respond. Is there any reason for that or is normal?

Here a a wireshark trace: 

[test.zip](https://github.com/eclipse/californium/files/7520448/test.zip)

Thanks in advance.

**Comment by boaks** [comment]
I can't see any reason in the capture.
So, I can only guess, what the cause may be:

- NON request. UDP doesn't grant the delivery of request. In rare cases, UDP message are lost. Therefore CoAP also support CON requests, which are retransmitted in case where the request or the response is dropped.

- IP-Address changes by NATs on the ip-route to the server. The ip-capture, close to the modem, doesn't show that. For that, DTLS Connection ID will be required. Or a new dtls-handshake.

I would recommend, you start with using CON and see, if that works.

**Comment by boaks** [comment]
@ce237 

Could this issue be closed? If you have further questions, please open a new issue.
It's hard for others to search for solutions, if an issue gets larger and larger and the questions are not longer related to the title.

**Comment by ce237** [comment]
for sure, sorry for the late response
