### ISSUE TITLE
CaliforniumFormatter fixed use of "\n"

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#180]
CaliforniumFormatter.format uses "\n".
Would it be possible to make this configurable (e.g. windows "\r\n")?

**Comment by sophokles73** [comment]
Sure, it will need to be changed to use `System.lineSeparator()` instead. We are facing this issue all over the code in log statements ... (sigh)

**Comment by jvermillard** [comment]
>  We are facing this issue all over the code in log statements ... (sigh)

or use slf4j in place of jul :trollface:

**Comment by sophokles73** [comment]
fixed on master in b8d2e29d655b16ff01c8b40ba6b1d46a223d88fc
fixed on 2.0.x in 5ac107872727a0253f75cd943b00e8c6c80cf4af
