### ISSUE TITLE
cf-simplefile-server: Unmatched argument at index 0:

### ISSUE THREAD

**Issue by marinjurjevic** [eclipse/californium#1803]
I'm building tag 2.6.5 and skipping tests because it fails when enabled. 
```bash
> mvn clean install -Dskiptests
```
After this I go to `demo-apps/run` and run following:

```bash
> java -jar cf-simplefile-server-2.6.5.jar /srv/californium 
Unmatched argument at index 0: '/srv/californium'
```

[Here](https://github.com/eclipse/californium/tree/master/demo-apps/cf-simplefile-server) it says first argument will be file root directory. Why am I getting problem above? 

EDIT: I also tested with 2.6.0 and I'm getting same error.

**Comment by boaks** [comment]
The jar is now available at the [Eclipse Release Repository](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/cf-simplefile-server/3.0.0/cf-simplefile-server-3.0.0.jar).
