### ISSUE TITLE
Certificate life-time of demo-certs?

### ISSUE THREAD

**Issue by rogierc** [eclipse/californium#1823]
Some [Mule CoAP Connector](https://github.com/teslanet-nl/mule-coap-connector) tests started to fail, caused by expiration of  certificates in the **demo-certs** . The tests use  **demo-certs** v2.6.5. Logging shows:

```
DEBUG 2021-11-14 13:44:34,863 [DTLS-Timer-0.0.0.0/0.0.0.0:45569#1] org.eclipse.californium.scandium.dtls.ClientHandshaker:(): handshake failed dtls-con: CID=F996E1EE46BE
org.eclipse.californium.scandium.dtls.HandshakeException: Received 'fatal alert/BAD_CERTIFICATE'
	...
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Nov 11 11:30:33 CET 2021
```
There is a workaround however. The demo-certs v3.0.0 seem backward compatible enough to get these tests going again. 

What life-time can we generally expect of the demo-certs? Which versions will get updated?

**Comment by boaks** [comment]
Usually, the demo certificates are valid for one year.
For the RSA support in release 3.0 some additional certificates are used, therefore I've created new ones. 
Branch 2.6.x is also already prepared with the new certificates. I wait for the next bug to fix for release 2.6.6 :-).

**Comment by boaks** [comment]
See issue #1828 .

Can this issue be closed?

**Comment by rogierc** [comment]
Thanks! 
Yes, the issue can be closed.
