### ISSUE TITLE
Server sends ClientHello instead of response

### ISSUE THREAD

**Issue by gergelynagymate** [eclipse/californium#1827]
# Server sends ClientHello instead of response

Hello,

I experience an unexpected behavior of the cf-secure SecureServer demo app as instead of the server response it sends a ClientHello to the client.
The californium log includes the server response to be sent, but it seems to be overridden by DTLSFlight adding the client hello.
## Test details:
* Californium commit version a17eab565661c11634b20a86d9468ddada8f5e33
* Client: an embedded device using mbedTLS 3.0.0 release communicating over public internet on NB-IoT.
* Default timeouts have been increased due to slow network of the device (see attached properties file)
* Californium runs from eclipse on windows over port forwarding of the office's router. DTLS port is modified in the SecureServer source code to 9010.
* SecureServer is run with argument CID:6, but without this the behavior is the same.
* Credentials are the default from the demo app (psk: secretPSK)

[californium_logs_and_captures.zip](https://github.com/eclipse/californium/files/7561551/californium_logs_and_captures.zip)

Could this be a bug, or something in my embedded implementation leads to this behavior?
Thank you!

Best regards,
Gergely

**Comment by boaks** [comment]
In short:

don't adapt the defaults, and I guess, it will work fine :-).

From your `Californium3SecureServer.properties`

```
...
# DTLS additional initial timeout for ECC related flights.
# Default: 0[ms]
DTLS.ADDITIONAL_ECC_TIMEOUT=0[ms]
# DTLS auto-handshake timeout. <blank>, disabled.
DTLS.AUTO_HANDSHAKE_TIMEOUT=10
...
# DTLS initial retransmission timeout.
# Default: 2[s]
DTLS.RETRANSMISSION_TIMEOUT=15[s]
...
# DTLS role.
# [CLIENT_ONLY, SERVER_ONLY, BOTH].
# Default: BOTH
DTLS.ROLE=BOTH
```

I'm not sure about the reasons to chose these settings. 
Let's start with
  
> DTLS.AUTO_HANDSHAKE_TIMEOUT=10

Is this a custom value? If so, what is the reason to use this value "10"? What do you consider to be the effect on the cloud-server-side? What do you guess means, `DTLS.ROLE=BOTH`?

I guess, the answers to this couple of questions, will make the solution obvious.

> DTLS.RETRANSMISSION_TIMEOUT=15[s]

In my experience, the common RTT using NB-IoT is less than 2.5s. I use therefore an initial value of `2500[ms]` and that seems to work very good. If you want to consider "extra time" for ECC (you use currently PSK, at least in the captures), then californium offers `DTLS.ADDITIONAL_ECC_TIMEOUT` for that.

**Comment by gergelynagymate** [comment]
Thank you Achim for your fast reply.
DTLS.AUTO_HANDSHAKE_TIMEOUT=10 was indeed responsible, it should stay blank.
Usually 2.5s NB-IoT transfer time is correct, but in some cases I experience as long as 10 or 20 seconds response times. I just wanted to align every timeout for that without understanding what DTLS.AUTO_HANDSHAKE_TIMEOUT was.

**Comment by boaks** [comment]
> but in some cases I experience as long as 10 or 20 seconds response times.

From PSM wakeup? That's more the network registration time. 
So I recommend, to finetune the dtls stack, if possible. Start the timeout, not when starting to send a message on the record layer, start it, when the modem reports to have sent the message. Maybe you start with 30s and "on modem sent", reduce that to 2.5s, if the dtls-stacks allows that.

**Comment by boaks** [comment]
> DTLS.AUTO_HANDSHAKE_TIMEOUT=10 was indeed responsible, it should stay blank.

Yes, that would mean: 
"10" => "10[ms]" => "if no messages are exchanged for 10ms, the initiate an automatic handshake".
Together with the "DTLS.ROLE=BOTH" (mainly for historical reasons), that causes the cloud-server to change the role to dtls-client and start initiate a handshake.

(I will update the comment for DTLS.AUTO_HANDSHAKE_TIMEOUT and the initial value for the dtls-role in the cf-secure demo.)

**Comment by boaks** [comment]
Any questions left? If not, could this issue be closed?

**Comment by gergelynagymate** [comment]
No more questions, thank you.
