### ISSUE TITLE
Scandium/RawPublicKeyIdentity should trim whitespace from the Id

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#183]
The identity String generated by RawPublicKeyIdentity has a trailing carriage return. I think this should be trimmed, as in:

	private void createNamedInformationUri(byte[] subjectPublicKeyInfo) {
		...
			niUri = b.toString().trim();

**Comment by sophokles73** [comment]
Hi,

I cannot see why the generated NI would have a trailing carriage return. Can you provide a code example that illustrates this problem?

**Comment by LudwigSeitz** [comment]
Try the code below. Note how the id String is visibly the same than the one I've manually added but the one produced by id.getName() is one char longer than the String I'm comparing to.
Also note how the +"END"  part disappears.

==========================Code=========================================
public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeySpecException  {
        String aKey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEtboxNKPgxEKV9JTNzytUvAbxEfkCTVB9kOzheF5wRAoOz2NKP+ln+XLVAQSp1D6jfo09tppvNpoQA1nnBNH6A==";  
        byte[] pubRaw = Base64.getDecoder().decode(aKey);
        System.out.println("PubKey: " + Base64.getEncoder().encodeToString(pubRaw));
    
        X509EncodedKeySpec x = new X509EncodedKeySpec(pubRaw);
        KeyFactory keyFactory = KeyFactory.getInstance("EC");
        PublicKey key = keyFactory.generatePublic(x);

        
        RawPublicKeyIdentity id = new RawPublicKeyIdentity(key);
        System.out.println("ID:" + id.getName() + "END");
   
        System.out.println(id.getName().length());
        System.out.println("ni:///sha-256;xzLa24yOBeCkos3VFzD2gd83Urohr9TsXqY9nhdDN0w".length());



    }

**Comment by LudwigSeitz** [comment]
Note that it might not be exactly a carriage return, but some whitespace that .trim() removes is definitely added in the encoding of RawPublicKeyIdentity().getName()

**Comment by sophokles73** [comment]
Ok, I have taken a look and it seems like there is a bug in the Base64 encoder we are using. It erroneously pads the encoded string with one or more 0x00 bytes if the number of bytes is not a straight multiple of 3. I will fix it this afternoon ...
Thanks for reporting :-)

**Comment by sophokles73** [comment]
fixed on master in a08d5c692729ae2f1a34769bc915c2d90fcc41f7
fixed on 2.0.x in ecb40bcbe6416f72f5648157c55e678b187cb3e7
fixed on 1.0.x in 6b9aea22dffa7a7a497306c6858704e189c144bf

**Comment by LudwigSeitz** [comment]
It would be nice if these changes were uploaded to the maven repo as well. I guess you have some process for that right?

**Comment by sophokles73** [comment]
@LudwigSeitz,

we do not publish master to Maven Central. But we do have nightly builds on the [Eclipse Repo](https://repo.eclipse.org). You should find the necessary info in Californium's readme.md. 
However, the good people at the eclipse foundation currently have some problems with operating repo.eclipse.org reliably ...

**Comment by LudwigSeitz** [comment]
I just re-ran my code example from 22. December above, and the problem still seems to be present in 1.0.5 (which seems to have the fix applied). Could someone check that this is really resolved?

**Comment by boaks** [comment]
I tried your code above with 1.0.5 (both build from tag and loaded from eclipse repo). 
That's my output

```
PubKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEtboxNKPgxEKV9JTNzytUvAbxEfkCTVB9kOzheF5wRAoOz2NKP+ln+XLVAQSp1D6jfo09tppvNpoQA1nnBNH6A==
ID:ni:///sha-256;xzLa24yOBeCkos3VFzD2gd83Urohr9TsXqY9nhdDN0wEND
57
57
```

So for me it seesm to be fixed.

**Comment by LudwigSeitz** [comment]
Ok, I'm using the jar from here: https://repo.maven.apache.org/maven2/org/eclipse/californium/scandium/1.0.5/ and that still produces the old error.
Is there a difference between that build and the one you get directly from the eclipse repo?

**Comment by LudwigSeitz** [comment]
My bad, there was still an old library version spooking around overriding the updated one. Sorry for that.

**Comment by boaks** [comment]
:-) 

Currently I was just writing, that I checked the apache repo version also successful.
