### ISSUE TITLE
How long does it take the server to respond with an ACK?

### ISSUE THREAD

**Issue by ce237** [eclipse/californium#1843]
Hello,

i will like to know, how long it will take for the server to respond to coap messages using a PUT-method or POST-method?

Best regards,

Cedric

**Comment by boaks** [comment]
That depends on a lot of things!

The Californium server itself takes only a few milliseconds (and it's designed, to execute many requests in parallel, if you have more cores).

If the communication delay must be considered, my experience is from a few milliseconds (locally on a machine or fast internet) up to 1-2s (e.g. NB-IoT).
In rare cases, retransmissions are required and results then in 2-3s.

If a DTLS handshake is required additionally, that may also add some more delay. 

So, it really depends.

**Comment by boaks** [comment]
Just to add:
That time for sure depends also on the implementation of that PUT or POST on the server.
If custom code is executed, which delegates the call to a database, that will add that time as well!

**Comment by ce237** [comment]
Thanks very much for the explanations

**Comment by ce237** [comment]
Hi @boaks ,

I used the nRF9160 DK from Nordic to conduct a current consumption measurement using the Power Profiler Kit 2, i had 494µWh by NB-IoT und 120µWh by LTE-M, with PSM enabled. 

Can you please tell me your thoughts based on your experience, on why there is so a large different on current consumption, despite the fact that the payload was the same? 

Thanks in advance


Best regards,


Cedric

**Comment by boaks** [comment]
I even don't understand your test :-).

PSM, ok.
"same payload" ... if your device is in "power sleeping mode", why is there payload?

So, I can only assume, that your test-cycle is:
- device in PSM
- device wakes up
- device registers in the providers network (2-60s)
- device sends request
- device wait for receiving the response (1-2.5s)
- device stays registered (in order to receive more messages) before entering PSM again.

With that, the first question would be:
- is the device in both mode NB-IoT and LTE-M (CAT-M?) really in PSM? Or something else?
- how long does it take, to register in the network? Is CAT-M faster?
- how long does it take to receive the response? Is CAT-M faster?
- how long does it take, that your device goes back to PSM?
- also, what is the current, if the device is in PSM?

Sometimes energy saving is more defined by the possibility to be switched off, than the real efficiency.
The idea behind is, that if your device is switched of for 2h, it's not that important, if the wakeup then takes the 500 µWh every 2h.

**Comment by ce237** [comment]
> So, I can only assume, that your test-cycle is:
> 
> * device in PSM
> * device wakes up
> * device registers in the providers network (2-60s)
> * device sends request
> * device wait for receiving the response (1-2.5s)
> * device stays registered (in order to receive more messages) before entering PSM again.

That's exactly the test cycle.

> * is the device in both mode NB-IoT and LTE-M (CAT-M?) really in PSM? Or something else?
 I conducted the test seperately, meaning one with LTE-M and the other with NB-IoT. But in both cases i enabled PSM.


> * how long does it take, to register in the network? Is CAT-M faster?
Both takes ~6s

> * how long does it take to receive the response? Is CAT-M faster?
For both ~2s

> * how long does it take, that your device goes back to PSM?

LTE-M: ~12,50s
NB-IoT: ~ 22,50s

> * also, what is the current, if the device is in PSM?

LTE-M: ~2,17µWh
NB-IoT: ~ 2,45µWh

> The idea behind is, that if your device is switched of for 2h, it's not that important, if the wakeup then takes the 500 µWh every 2h.

In mine case, the current consumption 494µWh by NB-IoT und 120µWh by LTE-M is after every 30s

**Comment by boaks** [comment]
I guess, if the NB-IoT device stay longer on, that explains some of the consumption. 
Maybe you configure it for a shorter time?

> In mine case, the current consumption 494µWh by NB-IoT und 120µWh by LTE-M is after every 30s

Does that mean: you "capture the consumption for 30s, which includes the above test-cycle"?
It may also be imported, which signal strength reaches your device for both cases.
I would try to shorten the `NB-IoT: ~ 22,50s` and then ask nordic about their ideas. 
AFAIK, there are already some comments ideas about the power consumption.

**Comment by ce237** [comment]
Hi @boaks ,

thanks once again for your suggestions.

I have another question though in regard to current consumption: Is it possible to reduce the "inactive time"? Because during this time, much more energy is consumed.

Any ideas?


Best regards,

Cedric

**Comment by boaks** [comment]
>  "inactive time"

is that the 

> LTE-M: ~12,50s
> NB-IoT: ~ 22,50s

That's a question for nordic.

In fact, I never tried to change the 10s of my BC68 and the nrf9160 doesn't go to sleep at all in my setup.

**Comment by ce237** [comment]
Ok thanks :)

**Comment by ce237** [comment]
Hi @boaks ,

Happy new year, i hope you had good holidays.

Have you ever used Release Assistance Indication with nRF9160 DK? 

I have some questions regarding it.

Best regards,

Cedric

**Comment by boaks** [comment]
Happy new year as well.

I'm currently using it ;-).

(But the topic is related also to your provider, to mode and configuration of your nRF9160 and so on.
Not sure, if I can be of any help.)

**Comment by ce237** [comment]
Ok i see

i just opened a Ticket on [nordic](https://devzone.nordicsemi.com/f/nordic-q-a/83415/release-assistance-indication-rai).

Can you please have a look at it and see if you can add, some insights?

**Comment by boaks** [comment]
Interesting options in "nrf_socket.h". I don't have experience with that advanced mode.

I have a Revision 1 nRF9160 I use the modem firmware 1.2.7.
(I'm not sure, if these advanced features are supported with that.)

Using the "old" ones with `lte_lc_rai_req(true)` and

CONFIG_UDP_RAI_ENABLE=y
CONFIG_LTE_RAI_REQ_VALUE=3 

results in "AT%XRAI=3". 
Logging the RRC state shows me, that it works according to my expectations.

I guess the stuff with `NRF_SO_RAI_NO_DATA` would require to use "AT%RAI=1" (without X), but I'm not sure about that. That's introduced with the modem firmware 1.3.0, which I don't want to use with the hw revision 1.

How do you create those cool captures including the AT cmds? Is that  complicated? Or do you have a link to a how to?

**Comment by ce237** [comment]
> How do you create those cool captures including the AT cmds? Is that complicated? Or do you have a link to a how to?

Do you mean the captures from my current draw?

**Comment by boaks** [comment]
This one

https://devzone.nordicsemi.com/cfs-file/__key/communityserver-discussions-components-files/4/Modem-Trace-Interaktion.pcapng

**Comment by ce237** [comment]
Now i understand what you mean.  For collecting wireshark traces with nRF91, it's a bit tricky, you need an external app for that. Nordic has a tool called [nRF Connect for Desktop](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-desktop) which you need to install. 

Next, within the app, you need to install "Trace Collector v2" plugin (note, it's eseential to get experimantal v2 version, the previous one did not allow to create pcap logs). Once you open the Trace Collector v2, it'll provide you with information on how to enable traces in your sample, and how to collect them.

**Comment by boaks** [comment]
Just as answer to the original question:
Using my Thingy!91, hw revision 1, firmware 1.2.7, the time from RRC Connected to a received response using RFC9146 is about 0,5s (best cases). As usual for wireless technologies, there are also some cases, where this is longer. If the responses leaves my RTT time-window (5s) and my modem get RRC Idle, the it takes at least 3s to receive data again. Also the time to get RTT Connected varies. In good cases it's about 2s, but there are also cases where it takes 10s, or 15s, or more.

**Comment by boaks** [comment]
Is it OK, to close it again?

**Comment by ce237** [comment]
sure
