### ISSUE TITLE
[dtls] Missing information in log on sendRecord failure.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1850]
(About 2.6.x branches, I didn't check if this improvement also concerned 3.0.0)
When for some reason a record can not be sent an IOException can be raised.
```
 LOGGER.warn("Could not send record", e);
```
from https://github.com/eclipse/californium/blob/2.6.5/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L2734L2757

It could be interesting to have more information to investigate, like at least the foreign IP or more if possible

E.G. in our case we face this when sending a Hello_verify : 
```
o.e.c.scandium.DTLSConnector     [] Could not send record
java.io.IOException: Invalid argument (sendto failed)
 at java.net.PlainDatagramSocketImpl.send(Native Method) 
 at java.net.DatagramSocket.send(DatagramSocket.java:693)
```
knowing the IP could allow us to capture the traffic to see the CLIENT_HELLO send and try to reproduce.

**Comment by boaks** [comment]
On a first look, this seems to be related to issue #1298 and PR #1347.

So, would [MdcConnectionListener](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/MdcConnectionListener.java) be worth to try?

**Comment by boaks** [comment]
Maybe, specific for HelloVerify, that doesn't work ;-).

It's part of the "stateless" processing.

[DTLSConnector. processDatagram](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1477-L1481) add for that "PEER". Maybe you can try to use that.

**Comment by sbernard31** [comment]
> DTLSConnector. processDatagram add for that "PEER". Maybe you can try to use that.

I don't get it.

**Comment by boaks** [comment]
The idea of issue #1298 was to use MDC for such information.
For the "stateless phase" (HelloVerify is part of that), there are no related Connection, but the DTLSConnector adds the "PEER" to the MDC for that.

Using logback, you may use something similiar 

[logback-test.xml](https://github.com/eclipse/californium/blob/master/scandium-core/src/test/resources/logback-test.xml#L3-L9)

```
         <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<!-- encoders are assigned the type ch.qos.logback.classic.encoder.PatternLayoutEncoder 
			by default -->
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} %level [%logger{0}]: %msg [%X] \(%class{25}.%method:%line\)%n</pattern>
		</encoder>
	</appender>
```

the %X inserts the MDC.

**Comment by boaks** [comment]
A short test results in

> 11:17:40.798 WARN [PEER=127.0.0.1:42266] [DTLSConnector]: Could not send record

**Comment by boaks** [comment]
If you could check, if MDC works generally for you, I may add a "ClientHelloListener", if you want to add some more details from your ClientHello.

**Comment by sbernard31** [comment]
I will let you now but I will not be able to test this before February.

**Comment by boaks** [comment]
Then we will see in February, what happens.

Just in the case, you can have a look at the (API) changes in PR #1857. It's mainly the case, that without adapting, someone who uses the CoapStackFactory or the extensions for CoapUdpStack, will not be able to benefit from the changes.

If the fix shows to be fit and doesn't stress at some other point, I would go for a similar change in a 2.7.0. AFAIK, that will fix leshan, though that doesn't use custom implementation of the extended APIs.

**Comment by sbernard31** [comment]
I looked at this quickly, it seems OK.

**Comment by boaks** [comment]
@sbernard31 

> I will let you know but I will not be able to test this before February.

Would it be able to do that at the begin of February?
I detected an error in the plugtest-checker (see 7ba012917fc0a3d025a91cb24bb50758f4b6f50a) and so I would like to schedule a next release ...

**Comment by sbernard31** [comment]
To do that I need a teammate who was not available in January and comes back 7 February. 
When he will come back I don't know what his priorities will be. 
So I can not be sure it will be done begin of February.

If you need to do a release soon, probably a best bet to not wait for us.

**Comment by boaks** [comment]
Thanks, we will see.

**Comment by boaks** [comment]
My current plan is to schedule a 3.3 for 24. February. 
If there is some feedback before this, it may be possible to consider that.

**Comment by sbernard31** [comment]
Thx to let us know that. (I let you know if I was able to get feedback before that)

**Comment by sbernard31** [comment]
I just get the you are talking about a **3.3** release.
And we plan to test it on Leshan v1.x with californium 2.x.

**Comment by boaks** [comment]
Anyway, if there is some outcome, that may also be considered for 3.3.

**Comment by boaks** [comment]
If that's a "response" to a received message, I would guess, the source-port (and outgoing destination-port) is `0`.
If so, we can block that in the `DTLSConnector`.

**Comment by sbernard31** [comment]
Some updates :
We use it now in production since 1 week, in a general way it seems to work as expected.
About the `Could not send record` log, we didn't see it for now.

**Comment by sbernard31** [comment]
We get it : 
```
[ection-Handler-1] o.e.c.scandium.DTLSConnector     [PEER=139.130.215.10:0] Could not send record
java.net.SocketException: Can't send to port 0
 at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:820)
 at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
 at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
 at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
 at org.eclipse.californium.scandium.DTLSConnector.sendNextDatagramOverNetwork(DTLSConnector.java:2738)
 at org.eclipse.californium.scandium.DTLSConnector.sendRecord(DTLSConnector.java:2731)
 at org.eclipse.californium.scandium.DTLSConnector.sendHelloVerify(DTLSConnector.java:2263)
 at org.eclipse.californium.scandium.DTLSConnector.isClientInControlOfSourceIpAddress(DTLSConnector.java:2106)
 at org.eclipse.californium.scandium.DTLSConnector.processNewClientHello(DTLSConnector.java:1907)
 at org.eclipse.californium.scandium.DTLSConnector.access$1100(DTLSConnector.java:233)
 ```
 
 And it seems you guess right port is `0`. 
 
 I think we can close this issue.

**Comment by boaks** [comment]
Yep.

Should we filter them out early and add then to DROP_LOGGER?

**Comment by sbernard31** [comment]
This is maybe not about "want" or "not want" as it seems to be a JVM error ?

**Comment by boaks** [comment]
[RFC 768](https://datatracker.ietf.org/doc/html/rfc768)

> Source Port is an optional field, when meaningful, it indicates the port
> of the sending  process,  and may be assumed  to be the port  to which a
> reply should  be addressed  in the absence of any other information.  If
> not used, a value of zero is inserted.

Using 0 in the source means not used. 
I don't see, what the "other information" could be.
Without that, no message could then be sent back.

**Comment by boaks** [comment]
> seems to be a JVM error

AFAIK:
0 in the source port => not used
0 in the destination port => not allowed

**Comment by boaks** [comment]
See PR #1921

**Comment by sbernard31** [comment]
#1921 looks OK.
