### ISSUE TITLE
ConnectionListener interface: Connection object without DTLSSession and Handshaker in onConnectionRemoved event

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/californium#1868]
Hi guys,

I've recently opened an issue in the Eclipse Leshan project (https://github.com/eclipse/leshan/issues/1191) but I was told to go to you.

After upgrading `californium` library from `2.6.3` to `3.0.0-RC1` I noticed the problem with `ConnectionListener#onConnectionRemoved` method. In the previous version, I was able to get some connection details using `Connection#getSession` and `Connection#getOngoingHandshake` methods - e.g. to get peer address, cipher suite, session creation time, and an error cause. Now, these methods always return `null` instead of correct objects.

BTW. I verified also it in the `3.0.0` version and still received `null` in this callback. 

Can you please advise? Is it the regression?

Many thanks.

**Comment by boaks** [comment]
> still received null in this callback.

Is the `connection` in `void onConnectionRemoved(Connection connection);` `null`?
Or does the `getOngoingHandshake` and `getSession` return `null`?

Anyway, the question is much more, at which point in removing the Connection the callback is considered to be called. Currently is called at the end of removing, and there the session may have already been reseted/cleared from the Connection. 

Maybe you describe, what you do there, and I see, how that could be done.

**Comment by gerardolenski** [comment]
Thanks for the answer. So I'll try to explain my case in more detail.

I'm implementing LWM2M Bootstrap Server using the Eclipse Leshan project (which is built on top of Californium) and I need to react when the DTLS handshake failed (e.g. add detailed logs, some custom Prometheus metrics ...). I did it by registering custom `ConnectionListener` to `DtlsConnectorConfig` using:
```
DtlsConnectorConfig.Builder.setConnectionListener(ConnectionListener connectionListener)
```
In the ConnectionListener implementation I used `public void onConnectionRemoved(Connection connection)` callback to retrieve details of failed connection (client address, connectionId, cipher suite, session creation time, failure message):
```
private FailureData toFailureData(Connection connection) {
        var session = connection.getSession();
        var handshake = connection.getOngoingHandshake();
        return FailureData.builder()
                .clientAddress(get(handshake, Handshaker::getPeerAddress))
                .connectionId(retrieveConnectionId(connection))
                .cipherSuite(get(session, DTLSSession::getCipherSuite))
                .sessionCreationTime(get(session, DTLSSession::getCreationTime))
                .errorMessage(retrieveErrorMessage(handshake))
                .build();
    }
```

It worked fine in Californium v. `2.6.3` But now after upgrading to `3.0.0` the both methods `connection.getSession()` and `connection.getOngoingHandshake()` returns `null`. So now I cannot retrieve details about failure connection anymore.

**Comment by boaks** [comment]
The difference I see is the `Handshaker`.

In Californium 3.0, the DTLS implementation (scandium) have been redesigned. The "grants" for such advanced APIs are more or less not that easy, especially if the redesign is larger. I guess, the processing order has changed. We will see. maybe, as mentioned above, make the session listener easier to use (add it to the Configuration) helps also.

**Comment by boaks** [comment]
I'm really wondering. Without trying to reproduce it, from the source code it's hard to see, why that should have changed. 

The Connection's SessionListener will remove the handshaker on failure, before the DTLSConnector's SessionListener removes it from the connection store. I'm not sure, how you achieved the above state.
Is it possible for you, to provide the "stacktraces" as well? May be I see there, what was your case.

Anyway, I guess, adding a SessionListener to the Configuration should work better (and in a defined way).

**Comment by gerardolenski** [comment]
Sure, here is the stack trace. Used with californium v. 3.1.0:
```
java.lang.RuntimeException: Detected Connection without handshaker: connection=dtls-con: CID=723A0FAAF72A, getOngoingHandshake=null, getSession=null
	at com.***.DtlsConnectionListener.onConnectionRemoved(DtlsConnectionListener.java:55)
	at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.remove(InMemoryConnectionStore.java:524)
	at org.eclipse.californium.scandium.DTLSConnector$3.handshakeFailed(DTLSConnector.java:582)
	at org.eclipse.californium.scandium.dtls.Handshaker.handshakeFailed(Handshaker.java:2239)
	at org.eclipse.californium.scandium.DTLSConnector.processExceptionDuringHandshake(DTLSConnector.java:2386)
	at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:2007)
	at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1740)
	at org.eclipse.californium.scandium.DTLSConnector$15.run(DTLSConnector.java:1596)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by boaks** [comment]
My point is:
I can't see, that these calling sequence of the SessionListener has changed since 2.6.3. Nor do I see, that the implemented functions of these SessionListener has changed. At least, I don't see it. 
Therefore the interesting thing would be a stacktrace of the 2.6.3 (this is the last version working for your approach? Otherwise the last version and a stacktrace from that).

**Comment by boaks** [comment]
I found it:

[DTLSConnection.terminateConnection(Connection connection, AlertMessage alert, DTLSSession session)](https://github.com/eclipse/californium/blob/2.6.x/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1622-L1657)

Here in line 1655 `connectionStore.remove(connection);` is called before failing the handshake.

Let me try to explain: I cleaned up scandium mainly to reduce duplicate calls and similar but not equal processing.
I don't think, it's good to restore that old call sequence. Instead I will check, if adding a SessionListener via Configuration is possible. I think, this will do a better job.

**Comment by gerardolenski** [comment]
Thank you for the answer. So if I understand correctly, there will be two configurable listeners:
- the `ConnectionListener` for connection life cycle
- the `SessionListener` for the life cycle of the DTLS session 

And then I should stop listening to `ConnectionListener#onConnectionEstablished` and `ConnectionListener#onConnectionRemoved` callbacks and start using `SessionListener#handshakeCompleted` and `SessionListener#handshakeFailed`, right?

When and do you plan to release your change? It will be on top of `3.1.0` version or also on `3.0.0` ?

**Comment by boaks** [comment]
FMPOV, it will be a 3.2.0 (it adds a feature, I don't consider it as a bugfix, which would then be a 3.0.1 or 3.1.1). 
The schedule is not fixed. I would prefer, if you could test, if the approach works for you ahead. If your feedback is positive, I can usually schedule a release soon, e.g. within a week. The logback fix 856165d6752527dc0bc20698f2a6e1b5d513b98a is anyway waiting to be released.

**Comment by gerardolenski** [comment]
So you suggest I should build californium on my own using your commit `be8aeb6` and change my implementation, right?
Well, I could try to do it.

**Comment by boaks** [comment]
Yes, just to make sure, that this "works for you".

**Comment by gerardolenski** [comment]
I did it. Almost works. The only problem now is that the handshake does not contain information about the peer address. Both:
`handshaker.getPeerAddress()` and `handshaker.getConnection().getPeerAddress()` returns `null`.

**Comment by boaks** [comment]
OK, I will try to provide it.

**Comment by boaks** [comment]
Fixed, next try, please.

**Comment by boaks** [comment]
Will next Thursday 13. January 2022 be OK?

**Comment by boaks** [comment]
See #1870

**Comment by boaks** [comment]
You're welcome.

**Comment by sbernard31** [comment]
> And then I should stop listening to ConnectionListener#onConnectionEstablished and ConnectionListener#onConnectionRemoved callbacks and start using SessionListener#handshakeCompleted and SessionListener#handshakeFailed, right?

I don't know if in your case, this is enough but clearly `ConnectionListener#onConnectionRemoved` are not equivalent to 
`SessionListener#handshakeCompleted` + `SessionListener#handshakeFailed`

> the both methods connection.getSession() and connection.getOngoingHandshake() returns null

I understand that a connection could haven't any ongoing handshake and so returns `null`.
For session, I'm not so sure it this is possible, I guess either there is an ongoing handshake or an established session and it should have always a session ? 

**Just my opinion**, on `ConnectionListener#onConnectionRemoved` :
I can understand that connection.getOngoingHandshake() always return null, as we can consider there is no more ongoing handshake at this moment. 
But ideally, I feel that a `connection.getSession()` should not return null is a session was attached to it.
(:warning: maybe I don't get the problem at all)


> Anyway, I guess, adding a SessionListener to the Configuration should work better (and in a defined way).

Just in case for people who are using a pre-3.2.0 version, it is possble to set a SessionListener like this : https://github.com/eclipse/leshan/blob/leshan-2.0.0-M5/leshan-client-demo/src/main/java/org/eclipse/leshan/client/demo/LeshanClientDemo.java#L227L293

**Comment by boaks** [comment]
Just to add:
The use-case behind this issue was to analyze failing handshakes. With that, I don't think, that the established session had returned something else then `null`. That a address and ongoing handshaker was returned, was caused by the "different" call-sequence.

**Comment by sbernard31** [comment]
Just to add:
My point is not about the issue but just the general behavior of the `ConnectionListener` API.

**Comment by boaks** [comment]
> But ideally, I feel that a connection.getSession() should not return null is a session was attached to it.

Without establishing the session, `connection.getSession()` returns the session of the handshaker. If that is `null`, getSession() is `null`.
With establishing the session, I haven't tested it.
