### ISSUE TITLE
Question: NAK when DTLS session isn't recognized

### ISSUE THREAD

**Issue by eric-martin** [eclipse/californium#1879]
Client-Side: Lobaro-CoAP (with DTLS), Californium + Scandium (v2.6.6)
Server-Side: Californium + Scandium (v2.6.6)

Is it possible for the server-side to NAK a request from an unknown DTLS session? (Instead of a client-side timeout)

Here is the scenario:
Client performs DTLS handshake
Client executes the first transaction against the server
Server is restarted
Client performs another transaction
Server doesn't respond
Client times out

**Comment by boaks** [comment]
Let me try to give an answer:

If you don't consider spoofing, that may make sense. Unfortunately, the most must consider spoofing (even if spoofing is very rare).

So, do you have a setup, where you can exclude spoofing? Then such "Alerts" may make sense. But for now, its not implemented and so not configurable.

Some advertisement:

With Californium 3.2.0 it's possible to do a [dtls graceful restart](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server#benchmarks---dtls-graceful-restart). With that, you problem should be much smaller :-). It's not that easy to set it up for an own server. I would recommend, that you start modifying the [cf-plugtest-server](https://github.com/eclipse/californium/tree/master/demo-apps/cf-plugtest-server). If that works for you, we may check to make it easier to use it for an own server.

More advertisement:

An other scenario is: the client's address visible to the server has changed. Therefore the server doesn't respond.

Also therefore, Californium has an solution: (upcoming) [RFC 9146](https://www.rfc-editor.org/rfc/authors/rfc9146.html). Even better: Eclipse has also an embedded client solution [Eclipse/tinyDtls - branch feature/connection_id](https://github.com/eclipse/tinydtls/tree/feature/connection_id). AFAIK, lobaro-coap has also a mapping for tinyDtls. (Just in the case, you have really interest in that, there is also a currently more [fresh cid branch](ihttps://github.com/bosch-io/tinydtls/tree/client_cid). We (Eclipse) still work very hard to make tinyDtls better and better ;-):

**Comment by boaks** [comment]
@eric-martin 

Still interested? Or can I/you close this issue?

**Comment by eric-martin** [comment]
Thanks @boaks. Closed.
