### ISSUE TITLE
InMemoryPskStore should have the ability to remove a PSK 

### ISSUE THREAD

**Issue by jimsch** [eclipse/californium#189]
As time goes by, a server will need to both add and remove PSK values from its set of security contexts as they are introduced to and time out.  It would also be reasonable to allow for a method of if figuring out which sessions are using a PSK so they can be shut down and prevented from re-starting as well.

**Comment by boaks** [comment]
> As time goes by, a server will need to both add and remove PSK values from its set of security contexts as they are introduced to and time out.

The `PskStore` defines, how scandium access the PSK credentials. The `InMemoryPskStore` is a basic implementation (more for demonstrating the usage). So feel free to implement and use your own `PskStore` implementation which provides all functions required for your use-case.

>It would also be reasonable to allow for a method of if figuring out which sessions are using a PSK so they can be shut down and prevented from re-starting as well.

That would be an enhancement.

**Comment by boaks** [comment]
I did some investigation on this.
The current implementation of the `InMemoryConnectionStore` is mainly "synchronized". That would block, when searching for "connections by principals with matching PSK identity". If the current "keys" (InetSocketAddress) are cloned and the search is the done by iterating over the keys (blocking only for the cloning and then for the single lookups), it may change with the redesign for the connection-id support. So I would go for it, after the connection id stuff is done.

**Comment by boaks** [comment]
It's now possible to remove a PSK. From the in-memory-demo-store and from the connection store.
See PR #1007
