### ISSUE TITLE
Fix Request URI behavior?

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1894]
In 2.x I detected, that applying a URI is either possible by using `Request.setURI` or explicitly `OptionSet` URI functions.

To overcome some ambiguity and to simplify the implementation, I added a comment in javadoc of the `Request`.

> 	 * Note: if uri-path or uri-query option was set explicitly before, they are
> 	 * not cleaned up, if the URI doesn't contain that part. e.g.
> 	 * {@code request.getOptions().setUriQuery("param=2")} and
> 	 * {@code request.setURI("coap://host/path")} results in
> 	 * {@code "coap://host/path?param=2"}. But
> 	 * {@code request.getOptions().setUriQuery("param=2")} and
> 	 * {@code request.setURI("coap://host/path?mark")} results in
> 	 * {@code "coap://host/path?mark"}.
> 	 * 
> 	 * That will be removed in the next major version! Don't set uri-path or
> 	 * uri-query options before the URI!

Unfortunately, I missed to remove that in 3.0. 
There are now two ways to go:

- fix it now as "bugfix"
- fix it with the next major

I prefer to fix it now, even if that may cause in some case a behavior change. If someone has a different opinion, please let me know.

**Comment by rogierc** [comment]
Port of [Mule CoAP Connector](https://github.com/teslanet-nl/mule-coap-connector) to Cf 3 is in early stage. The behavior change  is no problem there.

**Comment by boaks** [comment]
Let's go for it.
