### ISSUE TITLE
Add OSCORE demo to the sandbox server

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#1942]
I was asked via a private e-mail, if the Eclipse/Californium Sandbox (coap://californium.eclipseprojects.io) offers also some OSCORE resources.

Not for now.

@rikard-sics 

Do you think, such an example makes sense? Do you like to make a proposal?
I'm not sure, if a server endpoint can have oscore-resources an others in coexistence, if not, we just may add a OSCORE endpoint for that.

**Comment by boaks** [comment]
Just to mention:

If it makes more sense to use it with leshan and the sandbox there, I think we can also just mention that and point to the leshan sandbox for a oscore demo.

**Comment by rikard-sics** [comment]
> I'm not sure, if a server endpoint can have oscore-resources an others in coexistence, if not, we just may add a OSCORE endpoint for that.

I do think it would be nice to have OSCORE support also in the Eclipse/Californium sandbox. (In addition to the Leshan sandbox). 

Having OSCORE- and non-OSCORE resources co-existing should not be an issue. In fact we can potentially even have the same resource accessible both using OSCORE and not. It may be nice though to have 1 resource only accessible through OSCORE to make it clear in a concrete way when it is being used and not. (Of course having a separate endpoint for OSCORE is fine too).

I can try to put together some proposed code. Practically the code to consider as starting point is the cf-plugtest-server?

One thing to consider for OSCORE is that we need to make the security configuration to use for OSCORE discoverable somehow. Either in a resource on the server or posted on a website associated with it. (Or I guess in the associated cf-plugtest-client).

**Comment by boaks** [comment]
> Practically the code to consider as starting point is the cf-plugtest-server?

Yes, just add a new Resource there (and the cf-oscore dependency).  

> security configuration

I would add it to the [README.md](https://github.com/eclipse/californium/blob/master/README.md#interop-server) and the plugtest checker/client.

**Comment by boaks** [comment]
A new resource is just an idea.
If using an own endoint is easier/less work, then that's also a way to go.

**Comment by rikard-sics** [comment]
> A new resource is just an idea.
> If using an own endoint is easier/less work, then that's also a way to go.

Yes, makes sense. I am starting on this now and initially I will try to make it a new resource.

**Comment by rikard-sics** [comment]
I have now created a PR for this in https://github.com/eclipse/californium/pull/1970

**Comment by boaks** [comment]
PR #1970 is merged.
OSCORE is available at the sandbox of californium.
See [Sandbox - OSCORE Support](https://github.com/eclipse/californium#interop-server---oscore-support) for more information.
