### ISSUE TITLE
How to use Californium Properties file ?

### ISSUE THREAD

**Issue by dasdipanjan** [eclipse/californium#1965]
Hi Team,

I am currently using Californium 2.6.3 version in my project. I have a plan to upgrade it to 3.4.0.
In 2.6.3, I was using customized properties file by using below mentioned code.

NetworkConfig config = NetworkConfig.createStandardFromStream(stream);
CoapServer server = new CoapServer(config, port);
server.start();

But when I upgraded to 3.4.0, I found out that NetworkConfig is not present. Instead I should use Configuration class.
I am using below code.
Configuration configuration = Configuration.createFromStream(inputStream, null);
But it is not taking the keys of properties file. I think  I need to pass instance of DefinitionsProvider. But I am not understanding how can I create instance of DefinitionsProvider. Please help me.

**Comment by dasdipanjan** [comment]
[Californium.properties.txt](https://github.com/eclipse/californium/files/8411172/Californium.properties.txt)

**Comment by boaks** [comment]
[Californium3.properties.txt](https://github.com/eclipse/californium/files/8411693/Californium3.properties.txt)

The keys and the format has changed and I didn't consider to support importing the old format.
I recommend, to start it without "Californium3.properties" to generate a new "Californium3.properties" and then adapt that with your changes. I would also recommend, that you verify, that the changes are really useful. If you consider the that useful, you may also apply a [DefinitionsProvider](https://github.com/eclipse/californium/blob/master/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/BenchmarkClient.java#L180) with your changes in your code.

**Comment by boaks** [comment]
>  I think I need to pass instance of DefinitionsProvider. But I am not understanding how can I create instance of DefinitionsProvider. Please help me.

See the comments above. I will also try, to add that the javadoc in `Configuration`.

**Comment by boaks** [comment]
`ACK_TIMEOUT=10000` will be `COAP.ACK_TIMEOUT=10[s]`.  That's very large.
Though you use the same properties as in issue #1964, is it the same server?
If you sent 10 msgs/s but expect a RTT from about 5s (half the timeout), then you leave  the scope of RFC7641.

`MAX_MESSAGE_SIZE=10240` will be `COAP.MAX_MESSAGE_SIZE=10240`.
That is in the most cases simply unreliable. Hope you have tested it well. For me this looks like just a `0` more.

`NOTIFICATION_CHECK_INTERVAL=86400000` will be `COAP.NOTIFICATION_CHECK_INTERVAL=24[h]` 
`NOTIFICATION_CHECK_INTERVAL_COUNT=100` 

Both values are are used to switch from NON to CON notifies. Though you already use CON, I don't think that adjusting the value makes sense. To enlarge the time, but leave the counter, and sending 10 msgs/s doesn't make sense. it would then switch to CON anyway every 10s

`MAX_SERVER_RESPONSE_DELAY=250000` has been removed.

So, with that, I recommend, that you spend some time in verifying, that you really benefit from these settings. I have my doubts about that.

If you find other different values feel free to report them.

**Comment by boaks** [comment]
See PR #1966
