### ISSUE TITLE
CoapClient does not retransmit message

### ISSUE THREAD

**Issue by tang7526** [eclipse/californium#197]
I was testing the CoAP in a lossy connection environment and got some problem in retransmission.

I tried to use CoapClient api to send CON requests (POST) in the synchronous mode from a client to a server. With a probability of packet loss, a percentage of requests may not be delivered to the server. 

It should triggers the retransmission from the client. 

When in 2 seconds (ACK_TIMEOUT), client should retransmit message and waiting until get response.
But client doesn't retransmit message, it just continue to execute code.

I think that client just sends first times. 
When packet loss, client doesn't retransmit message. 

my californium-core version is 1.0.5.

my code:
```
CoapClient coap_client = new CoapClient("coap://IP:Port);
coap_client.useCONs();

CoapResponse resp = coap_client.post("test", MediaTypeRegistry.TEXT_PLAIN);
if (resp == null) {
     System.out.println("time out");
}else{
      System.out.println("RESPONSE CODE = " + resp.getCode());
}
```

**Comment by sophokles73** [comment]
Can you run your client with the log level for the `ReliabilityLayer` class being set to FINEST?
To do so, you need to create a Java Logging config file. Simply copy the `Californium-logging.properties` file from the `californium-core/src/test/resources` folder and then edit it like shown below:

```
...
# Limit the message that are printed on the console to INFO and above.
java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = org.eclipse.californium.core.CaliforniumFormatter
...
org.eclipse.californium.core.handlers = java.util.logging.ConsoleHandler
org.eclipse.californium.core.useParentHandlers = false
org.eclipse.californium.core.level = INFO
org.eclipse.californium.core.network.level = INFO
org.eclipse.californium.core.network.stack.ReliabilityLayer.level = FINEST
```

In order to use this configuration you need to set a system property on the JVM when starting the client:
```
java -Djava.util.logging.config.file=/path/to/your/Californium-logging.properties ...
```
You should then see some messages being logged by the `ReliabilityLayer` to the console.
Can you post the output here?

**Comment by tang7526** [comment]
output:
```
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 1 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:108) sendRequest() in thread Thread-1 at (2017-01-24 18:42:19)
 9 FINEST [ReliabilityLayer]: Cancel any retransmission - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:251) receiveResponse() in thread Thread-1 at (2017-01-24 18:42:19)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 0 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:58) sendRequest() in thread Thread-1 at (2017-01-24 18:42:20)
 9 FINEST [ReliabilityLayer]: Cancel any retransmission - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:251) receiveResponse() in thread Thread-1 at (2017-01-24 18:42:20)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 0 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:58) sendRequest() in thread Thread-1 at (2017-01-24 18:42:21)
 9 FINER [ReliabilityLayer$RetransmissionTask]: Timeout: retransmit message, failed: 1, message: CON-POST   MID=52692, Token=dc0a, OptionSet={"Uri-Path":["om2m","test_13"], "Content-Format":"text/plain"}, "{"data":"2qoptQp1BMbSZmG".. 1011 bytes - (org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.java:471) run() in thread Thread-1 at (2017-01-24 18:42:23)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 1 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:108) sendRequest() in thread Thread-1 at (2017-01-24 18:42:23)
 9 FINEST [ReliabilityLayer]: Cancel any retransmission - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:251) receiveResponse() in thread Thread-1 at (2017-01-24 18:42:23)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 0 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:58) sendRequest() in thread Thread-1 at (2017-01-24 18:42:24)
 9 FINEST [ReliabilityLayer]: Cancel any retransmission - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:251) receiveResponse() in thread Thread-1 at (2017-01-24 18:42:24)
 9 FINER [ReliabilityLayer$RetransmissionTask]: Timeout: retransmit message, failed: 3, message: CON-POST   MID=52687, Token=197e6d6e3422a5, OptionSet={"Uri-Path":["om2m","test_8"], "Content-Format":"text/plain"}, "{"data":"WnmnrQQ5KI8wMXN".. 1011 bytes - (org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.java:471) run() in thread Thread-1 at (2017-01-24 18:42:24)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 3 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:108) sendRequest() in thread Thread-1 at (2017-01-24 18:42:24)
 9 FINER [ReliabilityLayer]: Send request, failed transmissions: 0 - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:58) sendRequest() in thread Thread-1 at (2017-01-24 18:42:25)
 9 FINEST [ReliabilityLayer]: Cancel any retransmission - (org.eclipse.californium.core.network.stack.ReliabilityLayer.java:251) receiveResponse() in thread Thread-1 at (2017-01-24 18:42:25)
```

**Comment by sophokles73** [comment]
Looks like there are re-transmissions occurring, doesn't it?

**Comment by tang7526** [comment]
But when in 2 seconds (ACK_TIMEOUT), client executes code System.out.println("time out"); doesn't waiting for response.

**Comment by sophokles73** [comment]
By default the `CoapClient` uses `ACK_TIMEOUT` as the max time to wait for a response. So, if the request gets lost and the first retransmission occurs after 2 secs (the default ACK_TIMEOUT) the `CoapClient` will already have stopped to wait for a response. You should use `CoapClient.setTimeout()` to set the client's max time to wait period to a higher value (e.g. 10 or 20 secs) ...

**Comment by tang7526** [comment]
I wish client follow coap spec.   https://tools.ietf.org/html/rfc7252.
default ACK_TIMEOUT = 2 seconds.
default ACK_RANDOM_FACTOR = 1.5
default MAX_RETRANSMIT  = 4
default MAX_TRANSMIT_WAIT = 93 seconds

When client transmits message, client should wait 3(ACK_TIMEOUT*ACK_RANDOM_FACTOR) seconds.
If message lost, client should retransmit message and wait 6(3*2) seconds. 
If message lost agagin, client should retransmit message and wait 12(6*2) seconds. 
If message lost agagin, client should retransmit message and wait 24(12*2) seconds. 
If message lost agagin, client should retransmit message and wait 48(24*2) seconds. 
If message lost agagin, then client should get response null.
total waiting time = 3+6+12+24+48 = 93 seconds.

**Comment by sophokles73** [comment]
You are saying that the `CoapClient`'s default timeout should be set to `MAX_TRANSMIT_WAIT` instead of `ACK_TIMEOUT`, right?

**Comment by tang7526** [comment]
Yes

**Comment by sophokles73** [comment]
@sbernard31,  @boaks , @jvermillard, @mkovatsc 

IMHO this sounds like a reasonable change to make, WDYT?

**Comment by sbernard31** [comment]
set default `ACK_TIMEOUT` to `MAX_TRANSMIT_WAIT` for coapClient make sense to me.

**Comment by sophokles73** [comment]
What about the other direction, i.e. the time it takes to receive the response? `MAX_TRANSMIT_WAIT` only accounts for the time it might take to successfully send the request to the server. However, it doesn't account for the time it takes to send the response from the server to the client, does it? So, IMHO we should rather set the default timeout to `EXCHANGE_LIFETIME` instead ...

**Comment by boaks** [comment]
Yes.

I would add a comment, that sometimes it's recommended to adjust the timeouts to other values depending on the "connectivity" used. 
(A reponse timeout, especially with DTLS, may also be a indicator of a lost session and shorter timeouts would allow earlier a new DTLS handshakes.)

**Comment by sophokles73** [comment]
I can add this to the JavaDoc of `CoapClient.setTimeout()` ...

**Comment by sophokles73** [comment]
fixed on master in 8ec56a97965697acc93e13f51cb9df0f72697310
fixed on 1.0.x in 5c00f9637ee48b9941e4287450134b5dbf491bc4
fixed on 2.0.x in 78ee58a8df2c7181c810884a4099eedd63f8a328

**Comment by phani50** [comment]
Once i have received request, instead of sending ACK immediately i want to send Emty ACK once configured timeout exceeds. then later i will send response as CON to client. But unfortunately i did not found any propery in Californium.properties. is there any way to acheive this ?

**Comment by boaks** [comment]
Fist at all: it's not working to try to sent the empty ACK on timeout. The client will resend on its timeout, and, though the server doesn't know the transmission times, the server can't determine that clients timeout. 

What you can do: 
Sent an empty ACK ASAP, and then a separate response. To do that, the `CoapResource` of the `CoapServer` offers a `CoapExchange` in its handleXYZ methods. Call `CoapExchange.accept()` will send the empty ACK, and a later `CoapExchange.respond()` will send the response as separated response.

Or even better:
Try to make the response always as fast as possible, then you don't need such dirty stuff.

**Comment by phani50** [comment]
Thanks for the reply @boaks .

When the client starts retransmitting the message, that time from server can't we send empty ack ?

**Comment by boaks** [comment]
> When the client starts retransmitting the message, that time from server can't we send empty ack ?
I don't get it. The server can not determine that time! The server must ensure, that the client receives the ACK in time, and that "in time" is defined by the clients time and the time for transmissions. And for the server that time is undefined.

Therefore:
If you think, the response will take to long, send the ACK ASAP.
If you doubt about the response time, you may rely on the clients CON resend mechanism.

**Comment by phani50** [comment]
Our requirement is, When client sends CON message, Server is busy then client starts retransmit the CON message that time we want to send Empty ACK, then client stops resending CON's. later form server will send the CON message as response. 
@Override
    public void handlePOST(CoapExchange exchange) {
          exchange.advanced().getEndpoint().addInterceptor(new MessageInterceptorAdapter() {
                @Override
                public void receiveRequest(Request request) {
                    exchange.advanced().getCurrentRequest().setAcknowledged(true);
                }
            });
...
}
With above piece of code it resolved. when client starts retransmitting that time it called ovverriden receiveRequest method, here we are sending empty ACK

**Comment by boaks** [comment]
I would strongly recommend, not to do so :-)

If the retransmitted request is received, it is not passed to the `CoapResource`.
Instead, the `ReliabilityLayer.receiveRequest` will catch the `request.isDuplicate()`.
You will miss to call the `CoapExchange.accept()`.

To change that, you will need "deep knowledge" and you will be forced to apply your patch on all updates you're going to use.

You try to "improve" the standard, but this implementation is not intended to do so.

What is possible, is to call `CoapExchange.accept()` and later `CoapExchange.respond()`. Then you don't need to care about the retransmissions.

**Comment by phani50** [comment]
_What is possible, is to call `CoapExchange.accept()` and later `CoapExchange.respond()`. Then you don't need to care about the retransmissions._

But here always we are sending the response in a separate response. but what i want is to support both piggybacked and separate response to client.

For example, before client retransmits request, the server got response from backend then server should send response as piggybacked. otherwise send in separate response.

**Comment by boaks** [comment]
That's not implemented. If you need it, you must patch at least the `ReliabilityLayer`.
