### ISSUE TITLE
COAP on top of MQTT ?

### ISSUE THREAD

**Issue by gerardolenski** [eclipse/californium#1974]
Hi guys,

I'm doing some research and maybe you could give me some advice. I'm using californium for COAP connection on top of DTLS and UDP, but now I need to change the connection layer to MQTT. Is it possible somehow with californium? Can you give me any hint?

Many thanks.

**Comment by gerardolenski** [comment]
Many thanks @boaks for all info.

**Comment by boaks** [comment]
I guess, no one is working on this.
In contradiction to assumptions of many, this is no "low hanging fruit" ;-).

So, could this be closed?
