### ISSUE TITLE
Introduce a CoapEndpointBuilder

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#198]
CoapEndpoint has become a class with plenties of constructors.
Maybe it's better to convert that into a Builder pattern.

**Comment by vikram919** [comment]
I have introduced CoapEndpointBuilder class based on builder pattern inside CoapEndpoint class.
Now we can use only one CoapEndpoint constructor instead many constructors and code looks more readable and customizable than before with less ambiguity.
