### ISSUE TITLE
Failed to connect using PSK

### ISSUE THREAD

**Issue by PiKa20** [eclipse/californium#2047]
Hi,

I tried to use nRF9160 to connect to the server via DTLS. 

Firstly, I download [zephyr-coaps-client](https://github.com/boaks/zephyr-coaps-client/tree/main/src) to my nRF9160 DK, and it can connect to the server properly

Then, I use my program which base on [NCS2.0 nrf/sample/nrf9160/coap-client](https://github.com/nrfconnect/sdk-nrf/tree/v2.0.0/samples/nrf9160/coap_client). 

Here is the PSK and PSK Identity I used.

```
static unsigned char psk_id[] = "cali.351516172719221";
static size_t psk_id_length = sizeof(psk_id) - 1;
static unsigned char psk_key[] = ".fornium";
static size_t psk_key_length = sizeof(psk_key) - 1;
```

And I set my `encryption suite` as follow. That doesn't seem like a problem, right.

```
#define TLS_NULL_WITH_NULL_NULL  0x0000   /**< NULL cipher  */
#define TLS_PSK_WITH_AES_128_CCM  0xC0A4  /**< see RFC 6655 */
#define TLS_PSK_WITH_AES_128_CCM_8 0xC0A8 /**< see RFC 6655 */

nrf_sec_cipher_t cipher_list[] = { 
        TLS_PSK_WITH_AES_128_CCM,
        TLS_PSK_WITH_AES_128_CCM_8,
        TLS_NULL_WITH_NULL_NULL, };

err = setsockopt(fd, SOL_TLS, TLS_CIPHERSUITE_LIST, cipher_list, sizeof(cipher_list));
if (err) {
       /* Failed to set up cipher suite list. */
       return -errno;
}
```

Now I use this PSK、PSK Identity and encryption suite to connect the server `californium.eclipseprojects.io`. But when the client sends `client key exchange`, the server does not respond.

![image](https://user-images.githubusercontent.com/33158255/179750532-5fd81b2f-7ade-450e-be32-5a3ef74c1bea.png)

My Wireshark log as follow:

[trace-2022-07-19T12-27-14.230Z.zip](https://github.com/eclipse/californium/files/9141033/trace-2022-07-19T12-27-14.230Z.zip)

**Comment by boaks** [comment]
Thanks for testing [zephyr-coaps-client](https://github.com/boaks/zephyr-coaps-client) ;-).

I check the capture but I can't see, what's wrong. I would assume, that the "secret" is not the same. Where do you set the secret? Maybe, that function requires to pass it in as hexa-decimal ("2e666f726e69756d")?

**Comment by PiKa20** [comment]
I'm using nRF9160 modem API to set the secret

```
err = modem_key_mgmt_write(SEC_TAG,
				   MODEM_KEY_MGMT_CRED_TYPE_IDENTITY,
				   psk_id, psk_id_length);
if (err) {
		printk("Failed to provision id, err %d\n", err);
		return err;
}

printk("Provisioning PSK\n");
err = modem_key_mgmt_write(SEC_TAG,
				   MODEM_KEY_MGMT_CRED_TYPE_PSK,
				   psk_key, psk_key_length);
if (err) {
		printk("Failed to provision psk, err %d\n", err);
		return err;
}
```

I also think there's something wrong with my secret setup. But I pass it in as hexa-decimal, it had the same problem.

**Comment by boaks** [comment]
Californium uses [interoperability-tests](https://github.com/eclipse/californium/tree/main/californium-tests/californium-interoperability-tests) to ensure the compatibility with tinydtls, mbedtls, gnutls and openssl. AFAIK nordic uses mbedtls for the nrf9160. So, the only guess is the mismatch of the secret.

Reading [Modem Key Mgmt](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.0.1/nrf/libraries/modem/modem_key_mgmt.html) doesn't provide too much help, the hint to AT cmd at the top then results in [AT%CMNG](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fref_at_commands%2FREF%2Fat_commands%2Fsecurity%2Fcmng.html) :

> 3 – [Pre-shared Key (PSK)](https://infocenter.nordicsemi.com/topic/ref_at_commands/dita_common/glossary/glossary.html#psk) (ASCII text in hexadecimal string format)

I would try to use a 0 terminated hexadecimal string.

If that fails, I think the nordic devzone is the better place to ask.

**Comment by boaks** [comment]
The modem-trace didn't contain the "%CMNG" stuff. Did you set it up in an other run?
Maybe, if you have a trace with that psk/secret setup, we can see what happens.

**Comment by boaks** [comment]
In [devzone - nRF9160 modem_key_mgmt_cmp returns -1](https://devzone.nordicsemi.com/f/nordic-q-a/89820/nrf9160-modem_key_mgmt_cmp-returns--1) using the secret (PSK) as hexadecimal string works.

**Comment by PiKa20** [comment]
Thank you, I got it. I set the secret(PSK):

```
static unsigned char psk_id[] = "cali.351516172719221";
static size_t psk_id_length = sizeof(psk_id) - 1;
static unsigned char psk_key[] = "2e666f726e69756d";
static size_t psk_key_length = sizeof(psk_key) - 1;
```

I could connect to `californium.eclipseprojects.io`
