### ISSUE TITLE
Deduplicator not work properly in BenchmarkServer?

### ISSUE THREAD

**Issue by Xdeon** [eclipse/californium#207]
Hi All,

If I understand it correctly, Californium needs to cache message exchange information for some period of time in most cases, as specified in RFC7252. Thus a server under heavy load would consume a lot of memory and only free them after exchange information expire or get removed in other ways.

I found the BenchmarkServer example set NO_DEDUPLICATOR in its configuration. So I comment the line of code `.setString(NetworkConfig.Keys.DEDUPLICATOR, NetworkConfig.Keys.NO_DEDUPLICATOR)` in this code block: 
```
// Network configuration optimal for performance benchmarks
NetworkConfig.createStandardWithoutFile()
    // Disable deduplication OR strongly reduce lifetime
    .setString(NetworkConfig.Keys.DEDUPLICATOR, NetworkConfig.Keys.NO_DEDUPLICATOR)
    .setInt(NetworkConfig.Keys.EXCHANGE_LIFETIME, 1500)
			
    // Increase buffer for network interface to 10 MB
    .setInt(NetworkConfig.Keys.UDP_CONNECTOR_RECEIVE_BUFFER, 10*1024*1024)
    .setInt(NetworkConfig.Keys.UDP_CONNECTOR_SEND_BUFFER, 10*1024*1024)
		
    // Increase threads for receiving and sending packets through the socket     
    .setInt(NetworkConfig.Keys.NETWORK_STAGE_RECEIVER_THREAD_COUNT, udp_receiver)
    .setInt(NetworkConfig.Keys.NETWORK_STAGE_SENDER_THREAD_COUNT, udp_sender);
```
and expect that the default deduplicator would work instead. However when I did tests using cf-coapbench (with server recompiled), where many concurrent clients keep sending requests to the BenchmarkServer, the memory usage on server side went up rapidly and did not ever decrease. I waited for serval minutes (more than 247 seconds) and there was no obvious change of the memory consumption. 

I can reproduce this behavior on macOS Sierra and Ubuntu Server 16.04 LTS. I am using Californium release 1.0.5. 

Did I miss something here? Should this enable the default deduplicator which does all the clean work?

Any help appreciated here. Thank you.

**Comment by sophokles73** [comment]
When you use `NO_DEDUPLICATOR` Cf should not cache incoming requests anymore. The memory consumption you are experiencing should simply be related to the fact that you are sending a lot of messages simultaneously. My guess is that a garbage collection cycle would free up heap memory again. So you should first try to figure out whether the garbage collector has actually been running at least once after you stopped sending messages. If yes, then we probably have a problem (i.e. memory leak) that needs further investigation.

**Comment by Xdeon** [comment]
Thank you for reply.

My apology for not stating the problem clearly. 

First what I use as the server under test is under the path `californium/demo-apps/cf-benchmark/` so it is one of the example servers I think. This example sets deduplicatior to `NO_DEDUPLICATOT` (though it also sets `EXCHANGE_LIFETIME` to 1500, I guess it does not have an influence any more when combining with the `NO_DEDUPLICATOT`  setting). When I left it as it was, the memory consumption kept somewhat constant even under heavy traffic, and I believe this is the correct behavior as you mentioned. When I commented out the line that sets `NO_DEDUPLICATOT `, I assume this will trigger the default deduplicator instead. But after stress tests the memory consumption keeps high and never drops.

I use `htop` to monitor memory consumption. So my questions are:
1. Should commenting out the `NO_DEDUPLICATOT` setting enables the default deduplicator?
2. If it does, would the default deduplicator eventually cleans up all caching messages and let memory consumption drop to a normal level?
3. Am I using wrong monitor tool if all the behavior I ran into is not a problem at all?

Again thank you very much for any help here.

**Comment by sophokles73** [comment]
> Should commenting out the NO_DEDUPLICATOT setting enables the default deduplicator?

Yes, the default `MARK_AND_SWEEP` deduplicator will be used in this case. It will run every 10 seconds to find exchanges that have exceeded `EXCHANGE_LIFETIME` (milliseconds).

> If it does, would the default deduplicator eventually cleans up all caching messages and let memory consumption drop to a normal level?

Based on what I wrote above, it should :-) If it doesn't, we need to take a look what's happening, I guess.

> Am I using wrong monitor tool if all the behavior I ran into is not a problem at all?

IMHO a better approach would be to e.g. use [VisualVM](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jvisualvm.html) for profiling the VM you are running the Cf server in.

HTH

**Comment by Xdeon** [comment]
Thanks for your advice.

I did the test again on macOS and tried VisualVM as well as the built-in activity monitor to see how memory consumption changes. After waiting for at least two `EXCHANGE_LIFETIME` (2x247 seconds), the memory consumption remained high. To make sure, despite the `cf-benchmark` instance I also tested against `cf-helloworld-server` since this one should by default use a deduplicator with no doubt.  I still got similar result. I do think the deduplicator removed caching messages somehow, at least from its own records. As when I sent two duplicate requests with an interval larger than `EXCHANGE_LIFETIME`, the logger on the server side did not report on receiving any duplicate messages (it does report when sending duplicate requests within one `EXCHANGE_LIFETIME`). Just the memory consumption measurement shows no evidence of the cleaning up.

Since I am actually not a Java programmer, I really could not confirm I measured the problem correctly.  I was only taking Californium as a test bench. But I feel like to mention this issue (well, if it is an issue) here in case any one gets interested in it afterwards. 

Thank you.

**Comment by sophokles73** [comment]
The fact that the deduplicator removes an exchange from its cache doesn't mean that the memory is actually freed. That can happen only as part of a garbage collector run. Have you seen the GC running during the time you observed the memory consumption? You should be able to see GC runs in VisualVM ...

**Comment by Xdeon** [comment]
I manually triggered GC using VisualVM (after one test and after one `EXCHANGE_LIFETIME `) though the used heap sometimes decreases but total memory usage does not change a lot. If the GC cycle is what the problem actually locates, I will do more tests to verify that. Thank you for answering my confusion.

**Comment by Xdeon** [comment]
Sorry for interrupting you guys frequently...

I did another test where 1000 virtual clients keep sending request in a closed-loop fashion so the memory consumption on server side soon increased to about 3GB in total (with 1.6GB used heap according to VisualVM). After 20 minutes waiting, memory use dropped to around 2GB (with used heap just several hundreds megabytes). It seems a GC happened after a longer time than I expect and still total memory usage did not drop a lot, which is quite different than other CoAP server I tested written in other language. So any suggestion on it?

Thank you.

**Comment by sophokles73** [comment]
No, I don't. And, frankly, without a specific problem statement there is not much we can do. All I hear you saying is that what I had predicted is actually happening. So, if there is no specific problem we can work on, I would like to close this issue.

**Comment by Xdeon** [comment]
Sure. I close it now. Thanks a lot.
