### ISSUE TITLE
How to build a REST Connector to send the COAP messages over REST to SCEF

### ISSUE THREAD

**Issue by nginxsantos** [eclipse/californium#212]
an some one please help by providing some information on how to develop a REST based connector.

Requirement - Send the LWM2M message to SCEF (3GPP TS 23.682)

For example, let us consider how will we send the LWM2M message through the SCEF path which is REST based (please refer to OMA-TS-LightWeightM2M-V1_1-20160902-D for more details).

I have few questions on the probable implementation.

1.  I see there are RFCs defined for CoAP transmission over TCP and UDP. But, I don't see one for Non-IP. Does anyone have it?

2.  Has there been any work already started on this?

3.  We have to build a REST connector to take the payload I believe after DTLS and then sent it over REST.  Any help on how to build a connector? I looked at the TCP connector but it seems a bit more complex. Any help on this would be appreciated.

Thanks, Santos

**Comment by sophokles73** [comment]
Hi,
this seems to be a general question regarding design and implementation of potential extensions to Cf. Can you please use the mailing list for discussing it?
