### ISSUE TITLE
PSKStore latency impact

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#213]
I did some performance test with scandium.
And I face the same issue than Christian. (see [cf-dev](https://dev.eclipse.org/mhonarc/lists/cf-dev/msg01016.html))

Problems occurred when latency is added to PSK Store. (`getKey`)

Here problems I faced :
1) Access to keys through `PskStore` is done in a synchronous way.
2) We only have **1 thread which handle incoming messages** and this thread can be blocked to the `getKey` method. So when we wait for the key we stop to handle messages.
3) **DLTS retransmission** : We schedule a timeout for retransmission when we send a message. We cancel this scheduled retransmission before to send a new handshake message. In case where PSKstore take too much time (more than retransmission timeout) we can send retransmit message although we well received the next message (because we are blocked in `getKey` we don't sent the next message as fast enough and so don't canceled retransmission). In that case client will send again its message in response to of our retransmission and we will go for a new PSKStore access to answer... (Or how to shoot yourself in the foot)
4) **CoAP retransmission** : I did my tests using Californium at client side too. Currently when we send data through DTLSConnector and we don't have connection we initiate an handshake automatically. CoAP layer is not aware about that, it will schedule retransmission layer before data was really sent. So if handshake take too much time CoAP layer will try to resent data before the first handshake was finished and the CoAP message was sent. DTLSConnector will reintiate a full-handshake from scratch.

I just established a picture with this issue. We can create particular issues for each of this point to try to solve this general performance issue.

**Comment by sophokles73** [comment]
There already is an open issue (#23) for item 4.

**Comment by sbernard31** [comment]
Just a precision, this is not exactly the same issue.  Here we talk about retransmission and #23 talk about sending different application data. But it's a good thing to point this problem too as we should have both in mind to find a solution.

**Comment by sbernard31** [comment]
#305 and #312  addressed the item 4.

**Comment by boaks** [comment]
> In that case client will send again its message in response to of our retransmission and we will go for a new PSKStore access to answer... (Or how to shoot yourself in the foot)

I'm not sure. RFC6347 4.2.2

> DTLS implementations maintain (at least notionally) a
> next_receive_seq counter. This counter is initially set to zero.
> When a message is received, if its sequence number matches
> next_receive_seq, next_receive_seq is incremented and the message is
> processed. If the sequence number is less than next_receive_seq, the
> message MUST be discarded. 

As far as I understand this, the retransmitted client message MUST be discarded and therefore no PSK access is caused.

4.2.4 then says:

> 2. The implementation reads a retransmitted flight from the peer: the
> implementation transitions to the SENDING state, where it
> retransmits the flight, resets the retransmit timer, and returns
> to the WAITING state.

OK, I think, this "optimization" is currently not implemented but generally a retransmission of an already received handshake message just triggers a new retransmission without "internal security processing".

**Comment by boaks** [comment]
I will proved a unit test to check the exact behaviour when resending a flight and see, if we access the PSK on retransmissions. 
But for this week I'm too busy.

**Comment by sbernard31** [comment]
@boaks I think you're right a good implementation will just discard the retransmitted message. I look at the code and if message sequence number is well used, our implementation should discard it.
So, for this point  I probably interpreted my tests in a wrong way. :/

**Comment by boaks** [comment]
branch 2.0.x now contains a lot of optimizations for this issue. If possible, please retest this issue. I f it works for you, please close it.

**Comment by sbernard31** [comment]
All the issue reported here seems fixed, except the sync access to PSKStore  (#242).
I tested it and it behave really better.

So we can close this issue, but I would keep the #242 open.
