### ISSUE TITLE
org.eclipse.californium.core.coap.Request.getURI() assumes that Uri-host is set

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#225]
The method getURI() in Request assumes that Uri-host is set, which may not be the case e.g. when using literal IP addresses. See the code in Request.setOptions(final URI uri)

getURI() therefore erroneously returns "localhost" as hostname.

**Comment by sophokles73** [comment]
Fixed on master in 555f329e9446982c918e48ffd3e6dde2cb727259
Fixed on 1.0.x in c11b27e8a3fb535db6ce5af6220c58eae855835b
Fixed on 2.0.x in c9802adbef25bcf731574e7723629481e02a2309
