### ISSUE TITLE
Issues in keystore

### ISSUE THREAD

**Issue by anjanarajan** [eclipse/californium#234]
I downloaded the californium from  github  and while executing am getting a NPE as "Private Key is not null" I am attaching the error file along with this mail.

Kindly help me to sort it out.

Isssue
1 INFO [NetworkConfig]: loading properties from file /home/csti-pc1/Documents/test/californium-master/demo-apps/cf-secure/Californium.properties - (org.eclipse.californium.core.network.config.NetworkConfig.java:230) load() in thread main at (2017-03-08 14:27:54)
Exception in thread "main" java.lang.NullPointerException: The private key must not be null
    at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.setIdentity(DtlsConnectorConfig.java:617)
    at org.eclipse.californium.examples.SecureServer.main(SecureServer.java:98)

**Comment by boaks** [comment]
try to add `demo-certs-2.0.0-SNAPSHOT.jar` from `californium/demo-certs/target` to your classpah.

**Comment by anjanarajan** [comment]
In Eclipse I can able to run after adding classpath but how can i run the coaps (cf-secure) through mvn in linux.In linux enviornment I an getting the same error

**Comment by boaks** [comment]
What does "run the coaps (cf-secure) through mvn in linux" mean?

**Comment by sophokles73** [comment]
The JKS stores of the demo-certs module are not included in the cf-secure artifact because the default scope of the demo-certs dependency is declared as `test`. I'll provide a fix in a minute ...

**Comment by sophokles73** [comment]
fixed on master in a537c2b5b8fb7135c0b5411f1c5d2d17999d1737
fixed on 2.0.x in 7f44d5942a53d830ce4d45354152b7e0b9c1752f

BTW you can run from command line using maven like this:
`mvn exec:java -Dexec.mainClass=org.eclipse.californium.examples.SecureServer` or
`mvn exec:java -Dexec.mainClass=org.eclipse.californium.examples.SecureClient`
