### ISSUE TITLE
Introducing "in process" datagram messaging

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#238]
Hi all,

I would like to replace the DatagramSocketImpl used for testing to omit potential "package" loss using the real stack. It's not too much code, but I'm unsure, if this would require a new sub project.

Placing it in element-connector would mean, that this is available also for none testing stuff.
Placing it in element-connector test would mean, that this is not available outside the element-connector.
Placing it in a new subproject, I'm not sure if it's worth to generate such a new sub project.

So, any ideas where to place it?

**Comment by sophokles73** [comment]
I wouldn't have a problem with putting it into `element-connector`. Others might find it useful to use in their experiments as well. It doesn't do any harm, does it?

**Comment by boaks** [comment]
`DirectDatagramSocketImpl.initialize` must call `DatagramSocket.setDatagramSocketImplFactory()`, which is nonreversible until you restart the VM. But you have to call `DirectDatagramSocketImpl.initialize` otherwise it doesn't anything and so doesn't harm.

**Comment by boaks** [comment]
After some investigations, I found, that exporting the test classes with

			<plugin>
			  <groupId>org.apache.maven.plugins</groupId>
			  <artifactId>maven-jar-plugin</artifactId>
			  <executions>
			    <execution>
			      <goals>
			         <goal>test-jar</goal>
			      </goals>
			    </execution>
		  	  </executions>
			</plugin>

and the using them with

            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>element-connector</artifactId>
                <version>${project.version}</version>
                <scope>test</scope>
                <classifier>tests</classifier>
            </dependency>

would do it without a extra subproject.

**Comment by sophokles73** [comment]
@boaks 

can this be closed now?

**Comment by boaks** [comment]
sure
