### ISSUE TITLE
Asynchronous PSKStore API

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#242]
Currently, the PSKStore API is synchronous. This could cause performance issue if there is too much latency (#213 for details).

A solution could be to propose an asynchronous API like this :
```java
/*******   PskStore Interface *******/
// getKey async method of psk store API
public void getKey(final String identity, final ServerNames serverNames, final KeyCallback keyAccess);

// the callback to use when PSK is available or error is raised
private interface KeyCallback {
    void success(byte[] psk);
    void error(Exception e);
}

/*******   PskStore implementation *******/
// async implementation could looks like this :
public void getKey(final String identity, final ServerNames serverNames, final KeyCallback keyAccess){
    asyncHttpClient.prepareGet("http://example.org/keystore/"+identity).execute(new AsyncCompletionHandler<Response>(){
         @Override
         public Response onCompleted(Response response) throws Exception{
              keyAccess.success(response.getResponseBodyAsBytes());
         }
         @Override
         public void onThrowable(Throwable t){
              keyAccess.error(t);
         }
   });
}
```

**Comment by sbernard31** [comment]
I create a [async_pskstore](https://github.com/eclipse/californium/tree/async_pskstore) branch with experimental works.

This first crappy [commit](https://github.com/eclipse/californium/commit/1072429dc9823e57a56a663ad304b21c21c14489) is just a base for discussion.

The main technical problem is :
Once we get the key, how to continue the handshake process in the same Thread/ThreadPool ?

This should be easier to do once  #233 will be done, but this time we want to enqueue tasks instead of records. So maybe this one [more reason](https://github.com/eclipse/californium/pull/233#discussion_r105172285) to try the [Striped Executor Service](http://www.javaspecialists.eu/archive/Issue206.html).

**Comment by sophokles73** [comment]
I do not think that the Striped Executor Service will solve the problem of associating the async result of the lookup with the original thread of execution. For that, IMHO we would need to re-factor Scandium to build on top of a framework providing support for this, e.g. vertx or project-reactor ...

**Comment by sbernard31** [comment]
Why not ?  It seems to me something like that could work ?
```java
executor.submit(new StripedCallable<Void>() {
    public void call() throws Exception {
       // we imagine that recordProcessor has a method similar
       // to processRecord but for task which handle handshakeException 
       // (send alter and close connection)
       recordProcessor.processTask(new Runnable(){
            public void run(){
                pskAvailable(identity, key);
            }
       });
    }
    public Object getStripe() {
         return connection;
    }
});
```

**Comment by sophokles73** [comment]
Ok, can we then concentrate on #233 first and then deal with this additional improvement? Personally, I believe that introducing e.g. the striped executor will solve most of the problem this PR would help to address. In the end, this PR does nothing else: creating a separate (blocking) thread that needs to do the reading from the DB ...

**Comment by sbernard31** [comment]
I agree about focusing on #233.
As I said,  I just opened an issue and create a branch with some crappy sample of code to expose the problem, discus and keep in mind what could be the next step.
This is not a PR and this is not intended to be merge. By the way this branch help me to detect bug #236 and #227.

**Comment by boaks** [comment]
branch 2.0.x now contains a lot of optimizations for this issue. If possible, please retest this issue. If it works for you, please close it.

**Comment by sbernard31** [comment]
All the optimizations done are really great ! and it will surely be ok at short/mid-term. I already did some tests on my side and it's clearly better, but I doubt it will be enough at long term.

Before our optimization, if there was pskstore latency, we was unable to handle a "large" traffic.
Now, we are able to do handle more traffic by increasing the number of thread, but this number is limited.
Adding a async way to access to pskstore should solve the issues.

**Comment by boaks** [comment]
> but I doubt it will be enough at long term.

From my point of view:
The PSK store is either fast as possible, and therefore no asynchronous API is required,
or the DTLS connector will be vulnerable for DOS attacks from foreign DTLS clients, because it can't sort out the "foreign handshakes" fast enough.

**Comment by sbernard31** [comment]
I'm sry but I do not understand ?
How having an async API should made the DTLS connector vulnerable to DOS attack ?

With sync API, if all threads are blocked to handle handshake. Already "connected peer" can not send application anymore.
With async API, All threads should "never" be blocked, maybe the PSKstore will be overload and so don't be able to answer fast enough, so we can not accept new peers, but others "connected peer" will not be affected.

**Comment by boaks** [comment]
> How having an async API should made the DTLS connector vulnerable to DOS attack ?

That's not, what I'm said. "The PSK store is either fast as possible," that's what I said!
So the anchor is,
fast PSK store => I believe, a asynchronous API is then not required,
slow PSK store => asynchronous API, will make it faster. But then your slower in dropping the foreign messages.

**Comment by sbernard31** [comment]
I get it this time. "If PskStore does not support the load. A DOS attack is possible, as you can easily multiply handshake using bad credentials and so multiplying access to pskstore."

1) I don't think that the idea of this Async API is to support DOS attack. Defends again DOS attack is a real challenge, I 'm not even sure if this should be handled at scandium level. In all case, I don't think this should be an objective at short/mid-term. 

2) The priority should be to make scandium works in production environment. And previously, that was not the case. We have not so much traffic and scandium was not able to handle it, when our PSKStore latency increased. Now, this should be better, but I bet the problem will appear again when  traffic will increase.

3) I still think having a async API should be better.
3.1) Because PSKStore latency will not affect "already connected peers" (https://github.com/eclipse/californium/issues/242#issuecomment-308987958)
3.2) Because I bet this will be more efficient in term of memory consumption (To be verified).

But again, let's see how it behave now in "production" environment, waiting I prefer to not close this issue.

**Comment by boaks** [comment]
> But again, let's see how it behave now in "production" environment, waiting I prefer to not close this issue.

OK, that makes sense.

**Comment by boaks** [comment]
> But again, let's see how it behave now in "production" environment, waiting I prefer to not close this issue.

Still waiting? Or can we close it?

**Comment by sbernard31** [comment]
Not deployed for now. So still waiting.

**Comment by boaks** [comment]
ping ... ping

Any update?

**Comment by sbernard31** [comment]
We didn't face issue this last month but we also add cache to PskStore.
So If you want you can close this issue.
Personally, I still think having this kind of API could be an improvement but I will probably not work on this at short term. (But I keep it in mind for later)

**Comment by sbernard31** [comment]
Not directly link to PSKStore but long time ago I opened a ticket about long time running task in netty. They have pretty much the same "issue" than us with sync API of PSKStore.
It seems they worked on this issue. so , if one day we want to revive this topic, this could maybe worth it to look at what they done (https://github.com/netty/netty/issues/7862)

On our side we will probably give a try with [Hystrix](https://github.com/Netflix/Hystrix) to limit issue about sync API and to relieve overloaded services.

**Comment by boaks** [comment]
In scandium, with the "serial execution based on the Connector", it should be possible to delegate the certificate verification (or PSK fetch) without blocking a thread of the thread pool. It's mainly a question of "work time" to spend. 
For just "fetch secrets (PSK or private key)" information, as the most seems to want, it's at least for me, not that worth :-).
If "once upon a time", then I would go for keep the secrets away and do the calculations where these secrets are involved on the "secrets remote nodes".

**Comment by sbernard31** [comment]
> it's at least for me, not that worth :-).

Could you explain why ? because I do not understand where you think "I'm wrong" in https://github.com/eclipse/californium/issues/242#issuecomment-309024334. (especially the part 3.)

> If "once upon a time", then I would go for keep the secrets away and do the calculations where these secrets are involved on the "secrets remote nodes".

Can you explain a bit more ? I not sure I get your point. :-)

**Comment by boaks** [comment]
> it's at least for me, not that worth :-).

> Could you explain why ?

FMPOV, this data is some, which could be distributed/deployed ahead of usage and so supports perfectly a parallel read cluster, though each node has it's own copy to read. But sure, that depends on the personal preferences and assumptions.

> Can you explain a bit more ? I not sure I get your point. :-)

If simply the "secret data" should be distributed/deployed, then in my opinion it's more efficient to do this ahead then to do it "on demand". 

If the secret is not distributed, but used to calculated e.g. the "premasterkey" or even better the "masterkey" on the "remote service node", then it may provided some extra security benefits.

Just to mention:
My feeling is, to implement a initial/basic asynchronous interface for PSK and certificate validation is not that complicated. But provided tests and make it robust is something, which easily can reach much more time.

**Comment by sbernard31** [comment]
> My feeling is, to implement a initial/basic asynchronous interface for PSK and certificate validation is not that complicated. But provided tests and make it robust is something, which easily can reach much more time.

I agree with that.

> this data is some, which could be distributed/deployed ahead of usage and so supports perfectly a parallel read cluster, though each node has it's own copy to read.

If I understand you correctly, you think this is better that each cluster node has a copy of the whole " "secret base" ?

**Comment by boaks** [comment]
> If I understand you correctly, you think this is better that each cluster node has a copy of the whole "secret base" ?

From the viewpoint of performance and robustness, yes.

**Comment by sbernard31** [comment]
I understand _duplicate secret base_ solves the PSK latency issue but I also see some drawback (at least in some conditions) :
- in case of clustering, synchronized all node could be painful. (add/delete/update) (especially in case where you have difference store where secrets are stored)
- Some of our secrets are calculated by an HSM and so can not be easily store in advance.
- The memory consumption could be an issue but only if you have around hundred of millions of devices.

Currently in normal situation all is fine. But in some rare condition when our "PSK services" we depends on are overloaded, system can become unstable.
"PSK services" respond slower. This blocks/slows more threads.  So we are not able to handle as mush traffic as usual which make devices trying to reconnect more and overload the service more. When all thread are blocked we are even able to answer to already connected peer, which try to reconnect itself and overload even more the "PSK services".

That's why as short term solution we start to use [Hystrix](https://github.com/Netflix/Hystrix).
