### ISSUE TITLE
MTU detection 

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#246]
After #245 I tried to understand the MTU detection.

On windows the localhost interface returns a MTU of `-1`.
According some forums, this is not "invalid", it means just, that the "limit" is `0xFFFFFFFF`.
And `0xFFFFFFFF` interpreted as `int` is `-1`.

Therefore I would propose not to use `1280` for `-1` and instead `1500` (or an even larger value, eg. `16384`).

Any objections?

**Comment by sophokles73** [comment]
I do not understand what you want to do.

**Comment by sophokles73** [comment]
Ok, now I see. So, Windows does not report a meaningful value for the MTU, right?
However, I do not see why we should assume the effective MTU to be 1500 instead of 1280. What purpose would/should that serve?

**Comment by boaks** [comment]
(you may search the web for "mtu windows loopback")

`-1` is meaningful, it means `0xFFFFFFFF`. So, it's not "not defined", it's very large.
And so I would propose to use a larger value so that localhost behaves as the other interfaces.
This would also make the unitests (using localhost) behave more equal on unix and windows.

**Comment by sophokles73** [comment]
The system needs to also work with an MTU of 1280, doesn't it? The only fix we need to make is that if the value reported by the network interface is < 0, we set it to the default value (1280). No need to increase the default value.

**Comment by sophokles73** [comment]
> That's no argument. If the MTU is detected, why should we not use value based on that?
(And not on the wrong interpretation of -1).

We already do, don't we? The value determined from it is 1280. And because the system also needs to work if the interface had reported this value itself, this is indeed an excellent argument for using it as the default value, meaning: this default value is as good as any other (reasonable) default value. Which other value is more to your liking?

**Comment by boaks** [comment]
1280 is sure a good default.

But, again, `-1` is **not** "invalid", it means "very large value".
So in my opinion, a larger value than the default would better express that meaning of -1.

**Comment by boaks** [comment]
After prinitng the MTUs for all interfaces of my PC, I have to confess, that -1 is used for a lot of interfaces and not consequently for "very large". So it's not possible to use the -1 for "very large".
