### ISSUE TITLE
Provide proper OSGi meta-data for all modules

### ISSUE THREAD

**Issue by fipro78** [eclipse/californium#248]
I noticed that Californium is inconsistent in providing OSGi meta-data.
Some bundles provide proper OSGi meta-data, some not. IMHO all provided bundles should provide proper OSGi meta-data.

californium-core-2.0.0-M3 – no OSGi meta-data
californium-proxy-2.0.0-M3 – no OSGi meta-data
element-connector-2.0.0-M3 –incomplete OSGi meta-data provided
scandium-2.0.0-M3 – OSGi meta-data provided

**Comment by sophokles73** [comment]
@fipro78 

is this fixed by your PR? If so, could you please close the issue?

**Comment by fipro78** [comment]
for 2.0.0 it can be closed. How to proceed with the other branches? master and 1.0.x

**Comment by sophokles73** [comment]
It would be great if you could provide PRs for them as well, of course :-)

**Comment by boaks** [comment]
Could you check, if this issues could be closed after mergin your PRs for 1.0 and master branch?

**Comment by fipro78** [comment]
After merging the three PRs for the different branches I think this can be closed now. Further work on the OSGi bundle should be another issue and PR.
