### ISSUE TITLE
Logging levels for unit test 

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#257]
Trying to analyse the failed 2.0.x-nightly #50, I have to confess:
I don't understand "org.eclipse.californium.core.test.lockstep.ObserveServerSideTest.testQuickChangeAndTimeout"!

What I see:
respType and respPayload are used form different threads and I don't see, how this is done thread safe. 

What I don't see:
Which messages are really sent.
Commit 2ae02a5b6ecfbaf6a4d3777eb52a428228341475 reduced the logging of the messages.
Are there any reasons doing so? The DirectDatagramSocketImpl is only used for testing, so what is the benefit of reducing the logging? Is this a limitation of hudson?

**Comment by sophokles73** [comment]
No, I just do not see why the *default* behavior should be to log everything to the console. This slows down the execution of the tests and also provides completely irrelevant information at most times (when the tests are succeeding). When you are debugging you can configure the corresponding logger to log at level FINE and get all information you need. Just update `src/test/resources/Californium-logging.properties` ...

**Comment by boaks** [comment]
The point with randomly failing tests is, that if you repeat the test, the failure will occur only rarely.
I will check, if it's possible to store the messages and only log them, if an error occurs.

**Comment by sophokles73** [comment]
Don't get me wrong. It is perfectly ok to configure the logger for level FINE while you are debugging the build. You can also check it in to the repo so that it takes effect on the HIPP instance. I just didn't want to have all this debugging information logged at level INFO and above.

**Comment by boaks** [comment]
Configure the logger works fine for maven, but if executed locally in eclipse, this seems to me to be a little complicated. Or is there a easy way to configure it in general, when executed in eclipse?

**Comment by boaks** [comment]
Properties may be defined in project/runner as VM arguments, or general for a JRE as default VM arguments (Window->Preferences | Java -> Installed JREs | select and EDIT). So I adjusted the levels in the logging properties and setup my eclipse.
