### ISSUE TITLE
Remove ObserveRelation.notifications

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#274]
Currently the CoAP server stores all NON notifications in `ObserveRelation.notifications` to remove them from the message exchange store, when the observe is finished. They must be added to the message exchange store to react on RST, if the CoAP client is not longer interested in notifications.

In my opinion, this causes two issues:
The `ObserveRelation.notifications` may grow much larger than expected.
The notify MID will be stored longer and will therefore potentially collide with a new one generated by the messageIdProvider (which simply timesout the MID usage).

Proposed solution:
Remove the exchange from exchangesByMID also by timeout.
Therefore delete the `ObserveRelation.notifications`.

**Comment by sbernard31** [comment]
I think you're right.

The proposed solution looks good to me.

**Comment by sophokles73** [comment]
> Therefore delete the ObserveRelation.notifications.

Are you proposing to no longer keeping track of sent notifications?

**Comment by boaks** [comment]
Yes!
The NON notifies are stored in `exchangesByMID` and there we should remove them also by timeout.

**Comment by sophokles73** [comment]
IIRC the NON notifications are also tracked in order to be able to check, if a notification should be sent as a CON once in a while. But we could probably do that with a simple counter as well ...

**Comment by boaks** [comment]
I just checked the references to `ObserveRelation.notifications` and only found the "remove" usage.
So, where does californium use `ObserveRelation.notifications` for switching NON/CON? Or was it just planned to do so?

**Comment by boaks** [comment]
ObserveRelation:

> 	public boolean check() {
> 		boolean check = false;
> 		check |= this.interestCheckTimer + CHECK_INTERVAL_TIME < System.currentTimeMillis();
> 		check |= (++interestCheckCounter >= CHECK_INTERVAL_COUNT);
> 		if (check) {
> 			this.interestCheckTimer = System.currentTimeMillis();
> 			this.interestCheckCounter = 0;
> 		}
> 		return check;
> 	}
 
I think, its already this counter. Therefore the list seems only be used for the remove.
So I would prefer to change it "remove on timeout" .

**Comment by sophokles73** [comment]
Ok, sounds good.

**Comment by boaks** [comment]
I also got right now aware, that `UdpMatcher.removeNotificationsOf` is called frequently on every CON notify. But this "frequency" doesn't ensure, that the NON exchanges don't get into MID conflict, because that `UdpMatcher.removeNotificationsOf` seems not be related with the MID lifetime.
