### ISSUE TITLE
Make other options accessible

### ISSUE THREAD

**Issue by jvalkeal** [eclipse/californium#286]
As `OptionSet.getOthers()` is currently private you can only access these via `asSortedList()` but it is a bit over the top as it builds new sorted list of all options and then you'd need to iterate to find your own option.

Can we get direct access to other options?

**Comment by boaks** [comment]
Would `public Option OptionSet.getOtherOption(int number)` do it for you?

**Comment by jvalkeal** [comment]
I think a use case where these other options would generally be used would benefit if you can get all other options. Having `getOtherOption(int number)` is good if you already know which option to get but lets say that client is sending multiple other options, you really need to get those all if i.e. on server side you want to pass all that other info into next guy. This other guy might i.e. be a simple http call where you'd like to pass all other options as http headers.

**Comment by sophokles73** [comment]
So, what do you have in mind? What kind of access would be helpful to you?

**Comment by jvalkeal** [comment]
I have to ask that what has been motivation to make `OptionSet.getOthers()` private is that's pretty much all you need to access other options, right? That method doesn't actually populate `others` but method returning others as `List<Option>` would be good. I don't expect people to go crazy with number of other options so having something like `getOtherOption(int number) is probably unnecessary(thought nice if you want to add it as well).

**Comment by boaks** [comment]
For a public `List<Option> OptionSet.getOthers()`:

Does it makes sense to return a sorted list? 
Does it makes sense to return a unmodifiable list?

Though currently the "other options" could be accessed, but the method to do so is somehow overdone, I think, we should make it public.

**Comment by jvalkeal** [comment]
I don't think we need to sort that list and definitely that list should not be modified as there is `addOption` which handles adding other options as any option not known to `OptionNumberRegistry` is other option.

**Comment by boaks** [comment]
So:
Split `getOthers()` into `getOthers()` and `getOthersInternal()` by:
Rename current `getOthers()` into `getOthersInternal()`.
Add new `public getOthers()` returning a  unmodifiable list or null.

To all:
Any objections?

**Comment by boaks** [comment]
I changed the `null` into a `Collections.emptyList()` to comply to the other list getters.

**Comment by boaks** [comment]
PR #293 is merged. 

@jvalkeal 
So please, check, if it works for you. If so, please close the issue.
If there is still something to be done for the "other options", don't hesitate to ask for.
(When the issue is closed, I merge the PR into 1.0.x and master)

**Comment by jvalkeal** [comment]
Thanks, I'll check it out over the weekend.

**Comment by jvalkeal** [comment]
@boaks Thanks, works just great! Closing...
