### ISSUE TITLE
MID range in LockstepEndpoint

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#289]
> if (mid < 0 || mid > (2 << 16) - 1)

I'm not sure if `2 << 16` is intended or a typo and should be `1 << 16`.
Any information or opinions?

**Comment by sophokles73** [comment]
Looks like a typo to me. I agree that it should read `1 << 16`.
I also think that the exception being thrown should be `IllegalArgumentException` ...

**Comment by boaks** [comment]
Fixed in branches master, 1.0.x, and 2.0.x
