### ISSUE TITLE
Change Block1 blocksize

### ISSUE THREAD

**Issue by jrossey** [eclipse/californium#29]
Is it possible to change the default block1 size when doing a put? Now it is set to 512 but I want to change it to 1024.

**Comment by Stanislaw-Jakiel** [comment]
There is a setting:
PREFERRED_BLOCK_SIZE
that looks like what u need.
Consult CoAP's RFC how to use it

**Comment by jrossey** [comment]
Thanks, I needed that PREFERRED_BLOCK_SIZE to find the code that I needed.

Example:

NetworkConfig config = new NetworkConfig();
config.setInt(NetworkConfig.Keys.PREFERRED_BLOCK_SIZE,1024);
CoapEndpoint endpoint = new CoapEndpoint(config);

CoapClient client = new CoapClient("uri");
client.setEndpoint(endpoint);
CoapResponse response = client.put(payload, format);
