### ISSUE TITLE
Request.getURI(): keep "localhost" or convert to "127.0.0.1"?

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#296]
I tried to build the current leshan using californium 2.0.0-SNAPSHOT.

Some leshan unit tests are failing:

> CoapRequestBuilderTest.build_create_request__with_instance_id:278 expected:<coap://[localhost/12]> but was:<coap://[127.0.0.1:12354/12?]>

I see two differences: the address "localhost" and "127.0.0.1" and the missing port in the expectation.

The "Request.getURI()" was changed since the 2.0.0.M3.  So my question is:
Should we use "localhost" instead of "127.0.0.1" for the loopback Interface?
Then I would change "Request.getURI()" to use "if (destination != null && !destination.isLoopbackAddress())").
(this will not fix the leshan test, because the missing port in its expectation is just really missing :-)

> CoapRequestBuilderTest.build_create_request__with_instance_id:278 expected:<coap://localhost[/12]> but was:<coap://localhost[:12354/12?]>

**Comment by sophokles73** [comment]
I guess there was a reason why we wanted to use `127.0.0.1` instead of `localhost`, wasn't there?

If the expectation is also lacking the port, i.e. the leshan test case needs to be adapted anyway, I do not see why we should undo the loopback device change in Cf ...

**Comment by boaks** [comment]
> I guess there was a reason why we wanted to use 127.0.0.1 instead of localhost, wasn't there?

I just don't know. Should I read the cited RFC?

After changing the `hosts` in the leshan tests, I got aware, that there is a 3, difference, its the ending with "coap://[127.0.0.1:12354/12?]", the question mark `?` is somehow surprising. It's because even without query options the getOptions.getUriQueryString() returns "" (<emptystring>), which then get's converted to "?<emptystring>".
