### ISSUE TITLE
Move demo certificates into separate maven module change breaks tests

### ISSUE THREAD

**Issue by jaredcohen** [eclipse/californium#3]
I just tried to check out master and build the entire project, but since the certs folder has been relocated, it seems that if you don't skip the tests then all of the DTLS related tests fail.

**Comment by sophokles73** [comment]
Hi @jaredcohen,

works as expected on my machine :-) Can you try to clone into a fresh workspace and do a `mvn clean install`?

**Comment by sbernard31** [comment]
I tested that on Friday and this works for me too.

**Comment by mkovatsc** [comment]
I tested this, then moved them into an explicit "demo-certs" folder (which also helps with asking admins if we intended this), and tested again. Worked for me on the shell and in Eclipse.

**Comment by sophokles73** [comment]
@mkovatsc,

what do you mean by `then moved them into an explicit "demo-certs" folder`? The certs are provided as a jar deployed to the local maven repository (when doing a `mvn install`). In order to reference them you simply need to declare a maven dependency. No need to put anything into a folder ...

**Comment by mkovatsc** [comment]
I mean a simple rename (`git mv ...`) to `demo-certs` to make the purpose clear. The nice thing about the artifact is that Maven still provides them in `certs` to the application, so no code was changed. (I also see it as a feature that the names are now different.)

**Comment by sophokles73** [comment]
I see, I also thought about renaming `certs` to `demo-certs` when I did the restructuring. From my point of view that's ok. I'll do that later this week.

**Comment by jaredcohen** [comment]
Sounds like people aren't really seeing this issue other than me, so I'll assume its some local issue on my machine and close this issue. Sorry for the confusion.
