### ISSUE TITLE
Randomly wrong responses in blockwise (option block2)

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#30]
(Im using leshan with californium 1.0.3)
During tests, I recognized, that sometimes the coap server resends already sent blocks.
(e.g. 23 is resend, 24 is requested).
Any Idea, what could cause this?

``````
- (org.eclipse.californium.core.network.interceptors.MessageTracer.java:64) sendResponse() in thread pool-4-thread-4 at (2016-04-06 17:58:21)
33 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=50932, Token=8ff6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=22)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-3 at (2016-04-06 17:58:21)
33 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=50932, Token=8ff6, OptionSet={"Block2":"(szx=3/128, m=true, num=22)"}, 
06 02 00 1d 07 02 00 57 07 02 00 fe 06 02 00 3b 07 02 00 70 07 02 00 89 07 02 00 9f 07 02 00 c3
07 02 00 dd 07 02 00 2e 08 02 00 47 08 02 00 8c 20 00 20 57 08 02 00 6e 08 02 00 ec 20 00 20 ec
25 00 20 9c 21 00 20 9c 20 00 20 28 26 00 20 10 27 00 00 80 08 02 00 e2 04 00 00 9b 08 02 00 30
b5 04 1c 85 b0 0d 1c 00 2a 04 d0 10 1c 24 49 24 4a ff f7 d7 fc 2b 78 15 2b 3e d1 22 4b 03 93 10
 - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:64) sendResponse() in thread pool-4-thread-3 at (2016-04-06 17:58:21)
54 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=51188, Token=90f6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=23)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-7 at (2016-04-06 17:58:21)
54 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=51188, Token=90f6, OptionSet={"Block2":"(szx=3/128, m=true, num=23)"}, 
23 02 93 ff f7 be fc 20 1c 01 a9 05 f0 46 fe 00 28 22 d1 ff f7 b6 fc 1c 4b 1d 4a 18 88 0c 21 ff
f7 3c fc 08 23 02 1c 04 1c 9a 43 0e d0 02 22 18 4b c3 18 93 43 09 d0 11 28 07 d0 16 4b 98 42 04
d0 a0 21 0f 4a ff 31 ff f7 ac fc 21 1c 13 48 06 f0 9c fd ff f7 96 fc 0f e0 11 4b 98 42 01 d1 10
48 02 e0 10 28 03 d1 0f 48 06 f0 8f fd 04 e0 d7 21 04 4a 49 00 ff f7 95 fc 00 20 05 b0 30 bd cb
 - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:64) sendResponse() in thread pool-4-thread-7 at (2016-04-06 17:58:21)
52 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=51444, Token=91f6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=24)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-5 at (2016-04-06 17:58:21)
52 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=51188, Token=90f6, OptionSet={"Block2":"(szx=3/128, m=true, num=23)"}, 
23 02 93 ff f7 be fc 20 1c 01 a9 05 f0 46 fe 00 28 22 d1 ff f7 b6 fc 1c 4b 1d 4a 18 88 0c 21 ff
f7 3c fc 08 23 02 1c 04 1c 9a 43 0e d0 02 22 18 4b c3 18 93 43 09 d0 11 28 07 d0 16 4b 98 42 04
d0 a0 21 0f 4a ff 31 ff f7 ac fc 21 1c 13 48 06 f0 9c fd ff f7 96 fc 0f e0 11 4b 98 42 01 d1 10
48 02 e0 10 28 03 d1 0f 48 06 f0 8f fd 04 e0 d7 21 04 4a 49 00 ff f7 95 fc 00 20 05 b0 30 bd cb
 - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:64) sendResponse() in thread pool-4-thread-5 at (2016-04-06 17:58:21)
37 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=51444, Token=91f6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=24)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-4 at (2016-04-06 17:58:23)
37 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=51188, Token=90f6, OptionSet={"Block2":"(szx=3/128, m=true, num=23)"}, 
23 02 93 ff f7 be fc 20 1c 01 a9 05 f0 46 fe 00 28 22 d1 ff f7 b6 fc 1c 4b 1d 4a 18 88 0c 21 ff
f7 3c fc 08 23 02 1c 04 1c 9a 43 0e d0 02 22 18 4b c3 18 93 43 09 d0 11 28 07 d0 16 4b 98 42 04
d0 a0 21 0f 4a ff 31 ff f7 ac fc 21 1c 13 48 06 f0 9c fd ff f7 96 fc 0f e0 11 4b 98 42 01 d1 10
48 02 e0 10 28 03 d1 0f 48 06 f0 8f fd 04 e0 d7 21 04 4a 49 00 ff f7 95 fc 00 20 05 b0 30 bd cb
 - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:64) sendResponse() in thread pool-4-thread-4 at (2016-04-06 17:58:23)
54 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=51444, Token=91f6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=24)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-7 at (2016-04-06 17:58:26)
54 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=51188, Token=90f6, OptionSet={"Block2":"(szx=3/128, m=true, num=23)"}, 
23 02 93 ff f7 be fc 20 1c 01 a9 05 f0 46 fe 00 28 22 d1 ff f7 b6 fc 1c 4b 1d 4a 18 88 0c 21 ff
f7 3c fc 08 23 02 1c 04 1c 9a 43 0e d0 02 22 18 4b c3 18 93 43 09 d0 11 28 07 d0 16 4b 98 42 04
d0 a0 21 0f 4a ff 31 ff f7 ac fc 21 1c 13 48 06 f0 9c fd ff f7 96 fc 0f e0 11 4b 98 42 01 d1 10
48 02 e0 10 28 03 d1 0f 48 06 f0 8f fd 04 e0 d7 21 04 4a 49 00 ff f7 95 fc 00 20 05 b0 30 b
```d cb
``````

**Comment by boaks** [comment]
OK, the device didn't use a "random MID" when starting ...

**Comment by boaks** [comment]
I spent some time in more analyses:
The issue occurs only, if my device restarts with the same MID. 
If so, a request will find an old exchange for the MID and setDuplicate to true, and afterwards the ReliabilityLayer sends to old current response.
But if this exchange is blockwise, the MID of the old current reponse may be different one. And so I think:
**californium does it wrong!**

**Comment by boaks** [comment]
Other mixed up case:
NON notification
If such a MID is accidently reused by a CON, you get an empyt ACK.
(OK, with the right MID, but the was never such an answer.)

**Comment by mkovatsc** [comment]
So the client is reusing an MID before it lifetime ends and receives the wrong response?

**Comment by mkovatsc** [comment]
I can see how a changed currentResponse in the exchange will respond with a different response. However, due to the stop and wait of blockwise transfers, current currentResponse does not change unless the client received the previous Block and asked for the next.

**Comment by boaks** [comment]
> So the client is reusing an MID before it lifetime ends and receives the wrong response?

Yes, the client clearly violates RFC 7252, 4.4!
But in the follow up, the server also violates (in my opinion) the RFC (because the ACK must be related with the MID of the CON/NON).

**Comment by sophokles73** [comment]
So, we seem to agree on the following:
* the client violates RFC 7252, 4.4 by reusing an MID before its lifetime has expired

What I do not (yet) understand is what Californium is doing (wrongly) in that case and what it *should* do in your opinion, @boaks.

**Comment by boaks** [comment]
Californium should not violate the message transport layer of RFC 7252 and should only answer messages with the matching MID an the "real previous answer".

52 INFO [MessageTracer]: /192.168.10.106:12.345 ==> req CON-GET    MID=**51444**, Token=91f6, OptionSet={"Uri-Path":["file","fw.zip"], "Block2":"(szx=3/128, m=false, num=24)"}, no payload - (org.eclipse.californium.core.network.interceptors.MessageTracer.java:78) receiveRequest() in thread pool-4-thread-5 at (2016-04-06 17:58:21)
52 INFO [MessageTracer]: /192.168.10.106:12.345 <== res ACK-2.05   MID=**51188**, Token=90f6, OptionSet={"Block2":"(szx=3/128, m=true, num=23)"}, 

The issue is, that the message is sent with 51444, but californium answers with 51188.
(I would guess, that therefore the answer is alos not the previous one to 51188, even if I could not prove this)
If californium would have answered with 51444 and the previous answer to that MID, then it would be easier to understand and analyse the situation.

**Comment by sophokles73** [comment]
I still don't get it. How is the outbound message with MID 51188 related to the inbound message with MID 51444? They seem to be totally unrelated with each other but you assume that Californium has determined that the response (51188) sent is the reply to the request (51444), right?

**Comment by boaks** [comment]
You got it! 

I also assumed, they are unrelated! Therefore I got mixed up and searched, and searched.
And in the end I found, that californium mixes it up and 51188 is the response sent for the request 51444! You may prove this by your own:



```java
	public void receiveRequest(Exchange exchange, Request request) {
		
		if (request.isDuplicate()) {
			// Request is a duplicate, so resend ACK, RST or response
			if (exchange.getCurrentResponse() != null) {
				if (exchange.getCurrentResponse().getMID() == request.getMID()) {
					LOGGER.fine("Respond with the current response to the duplicate request");
				}
				else {
					LOGGER.severe("Duplicate request, but response not available!");
				}

```


Add this to the `ReliabilityLayer` and the make a blockwise transfer and the restart a client, which uses always the same MID on startup. And you will see, what happens :-)

**Comment by sophokles73** [comment]
And what is the correct behavior in your opinion?

**Comment by boaks** [comment]
As written above:

Californium should not violate the message transport layer of RFC 7252 and **should only answer messages with the matching MID an the "real previous answer"**.

**Comment by sophokles73** [comment]
So, Californium could very well return the cached response but should update the MID before sending it out to the client, right?

**Comment by sbernard31** [comment]
I think @boaks want the right MID and **also the right response**. The idea is to help to understand/debug when this unexcepted(out of the spec) case happens. And I suspect that if we don't have the right MID, we don't have the right response too.

From my point of view, just changing the MID and keep the unexcepted response will not really help to debug. (It could be probably worse) 

The real question is why we consider the new message as a duplicate and why we don't return the last response corresponding to this MID.
If the previous exchange was completed, we should remove the MID from the exchangeBy* map and so not considering the message as duplicate. :/

By looking at the code, I maybe found an explanation.
In [Matcher.receiveRequest](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/network/Matcher.java#L277), we look if we have an exchange for a request by URI (not by id). If we find it,  we use the deduplicator to check if the request is a duplicate.
But the deduplicator is not clear when the exchange is completed, removal is based on time. So we could still have a exchange for a previous MID. As the same exchange is used for a blockwise transfer and the current response change each time a new block is exchanged, there is case where we can answer with the bad response. (We probably don't get the right response anymore)

**Comment by boaks** [comment]
@sbernard31 is right, I would like to have the right MID and right message as defined by RFC7252, 4.5 (`response` is a defined term in RFC7252, 5 and the answer-message may have been a simple ACK).

But right now, I don't think you should spent too much time to fix that.
May be a comment as known issue does it also.

**Comment by mkovatsc** [comment]
Did I understand it right, that the client is not Californium?
The problem at the server is caused exactly because of the client violation. Fixing this would be a defensive appraoch to be nice to faulty clients IMHO.
The problem results from the resulting violation of the stop-and-wait of blockwise transfers and the Californium feature of caching the original response in the deduplicator.
So far, I can only imagine an easy solution that kills the actually useful feature or this defensive mechanism that only adds complexity.

**Comment by sophokles73** [comment]
Hey @boaks,

I have (finally) merged #170 to the 2.0.x branch. Can you check whether this is still an issue?
Thanks :-)

**Comment by boaks** [comment]
Hi @sophokles73,

I checked it already earlier, see
https://github.com/eclipse/californium/pull/170#issuecomment-265752643

But I will retest it now with the 2.0 5ef638e341d7b5f6edd48a5ccbfc97a804034a79 and on success then close the issue

**Comment by boaks** [comment]
Retested. MID of response is now matching the request!
