### ISSUE TITLE
Add method to Scandium for setting trusted RPKs

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#301]
When doing a raw-public-key handshake according to RFC 7250 the raw public key of the other peer is said to be verified out-of-band. 

I would like to have a feature in Scandium where I can add a list of trusted raw public keys, from which I will accept DTLS connections (and reject others).

**Comment by boaks** [comment]
`Request` offers `getSenderIdentity`, which provides the access to the raw public key.
So I think, you could check it on incoming request.

**Comment by LudwigSeitz** [comment]
True, but it would be nice to be able to check this in Scandium and not in the application, so that the handshake is aborted.

**Comment by sophokles73** [comment]
I agree, it would be nice to have something along the lines of the PSKStore for RPKs as well.

**Comment by LudwigSeitz** [comment]
I've written some code to solve this issue, what is the preferred procedure for contributing this?

**Comment by boaks** [comment]
The raw public keys are used to create the `RawPublicKeyIdentity` (which implements `Principal`).
But your right, if the client sends application data, the application layer will not get the principal until the server replies. So, if you can't wait for the servers response, scandium must be enhanced.

> I've written some code to solve this issue, what is the preferred procedure for contributing this?
That's defined by eclipse. A PR requires a ECA. 

https://www.eclipse.org/legal/ECA.php

**Comment by LudwigSeitz** [comment]
Did a pull request with code for that feature. Please review.

**Comment by boaks** [comment]
Should be solve with the merging of your PR.
