### ISSUE TITLE
Any idea on how to implement the push-based messaging system using CoAP with Java

### ISSUE THREAD

**Issue by sitoumbaz** [eclipse/californium#307]
I am willing to use CoAP protocol for implementing a java push-based messaging system. Particularly in such a system, a client opens just once a connection with a server (resource) and the server pushes messages (‘non-confirmable’) with a specific rate (e.g., 10 messages per second). However I did not find any existing solution to build the above system.

What I found is the pull-based messaging system. For such case, a client opens a connection with the server and after some time the client sends a GET request. Then, the server handles the request and pushes (as response) a single message to the client.

Hence, for each GET, I have a single message as response -- i.e., a two-way asynchronous interaction.

Does anybody have any idea on how to implement the push-based messaging system using CoAP? Does CoAP supports such a system? 

The pull-based messaging system is implemented as follows 

1. Server Part
              
               public class CoapServerPartAsync extends CoapServer {

              private static final int COAP_PORT = 8891;
              private static int incrementor = 1;
              /*
              * Application entry point.
              */
              public static void main(String[] args) {

                 try {

                 // create server
                 CoapServerPartAsync server = new CoapServerPartAsync();

                 // add endpoints on all IP addresses

                 server.addEndpoints();

                 server.start();

                 } catch (SocketException e) {

                      System.err.println("Failed to initialize server: " +   e.getMessage());
                 }
              }

             /**
              * Add endpoints listening on default CoAP port on all IP  addresses of all network interfaces.
              *  
              * @throws SocketException if network interfaces cannot be determined
              */

              private void addEndpoints() throws SocketException {

                  InetSocketAddress bindToAddress = new  InetSocketAddress("127.0.0.1", COAP_PORT);

                 addEndpoint(new CoapEndpoint(bindToAddress));

                 }

                /*
                 * Constructor for a new Hello-World server. Here, the resources
                 * of the server are initialized.
                 */
                 public CoapServerPartAsync() throws SocketException {

                 // provide an instance of a Hello-World resource
                 add(new HelloWorldResource());
                 }

               /*
                * Definition of the Hello-World Resource
               */

                class HelloWorldResource extends CoapResource {

                      public HelloWorldResource() {

                      // set resource identifier
                      super("helloWorld");

                     // set display name
                     getAttributes().setTitle("Hello-World Resource");
                 }

                 @Override
                 public void handleGET(CoapExchange exchange){

                 // respond to the request
                 System.out.println("Push [Hello World!"+(incrementor)+"]");
                  exchange.respond("Hello World!"+(incrementor));
                  incrementor++;

            }
           }
          }

2. Client Part

           public class CoapClientPartAsync {

                    // static boolean getResponse = false;

                    public static void main(String args[]) { 

                    CoapClient client = new CoapClient("coap://127.0.0.1:8891/helloWorld").useNONs();

                   while(true){
                      CoapObserveRelation relation = client.observe( 
         new CoapHandler() {

                 @Override public void onLoad(CoapResponse response){
                            String content = response.getResponseText();
                           System.out.println("NOTIFICATION: " + content);

                          }

                    @Override public void onError() {
                    System.err.println("OBSERVING FAILED (press enter to exit)");
                  }
               });
               try {
                     Thread.sleep(1000);
                 }catch (InterruptedException e) {
                      // TODO Auto-generated catch block
                      e.printStackTrace();
                 }       
           }
          }
        }

**Comment by sophokles73** [comment]
You can use CoAP's Observe [1] mechanism for that purpose. This is also supported by Californium, both on client and server side.

Take a look at the ObserveTest [2] for how this works ...


[1] http://tools.ietf.org/html/rfc7641

[2] https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/test/java/org/eclipse/californium/core/test/ObserveTest.java


Mit freundlichen Grüßen / Best regards

Kai Hudalla
Chief Software Architect

Bosch Software Innovations GmbH
Schöneberger Ufer 89-91
10785 Berlin
GERMANY
www.bosch-si.com

Registered office: Berlin, Register court: Amtsgericht Charlottenburg, HRB 148411 B;
Executives: Dr.-Ing. Rainer Kallenbach, Michael Hahn
________________________________

**Comment by sitoumbaz** [comment]
Thank you @sophokles73  I used  Observe [1] mechanism for botth and it work fine. Thank you for that.

My need is also to be able to increase the rate of sending messages (e.g., 10 messages per second, 20 message per second, 30 message per second ...) with the above architecture : 

websocket-producer --> websocket-consummer --> CoAP-server --> CoAP-client --> Mqtt(pub-sub) 

But with the spécification of Observe [1] mechanism, the latency (second) between the change of the resource state and the receipt of the notification can not allow me to reach my goal.  Because the latency from a websocket-producer to Mqtt-Sub will increase seriously.
 
 So my question is to know if it is possible to reduce this latency  in the implémentation of this mecanism ?  

Thanks.
Patient NTUMBA W. 
Research engineer
INRIA-MiMove Team
Paris 12
France.

**Comment by boaks** [comment]
@sitoumbaz 
Do you use CONfirmed or NONconfirmed notifies?
If you use CONfirmed try NONconfirmed notifies. With a rate 30 per second, losing one breaks hopefully not your application.

**Comment by boaks** [comment]
If the issue still exists, please open it again or create a new one.
