### ISSUE TITLE
BERT option with TCP connector.

### ISSUE THREAD

**Issue by raipratheek** [eclipse/californium#310]
I am trying to use the Californium for a Java based client and server application running on 2 separate devices. The size of the data that is exchanged is of the order of tens of KB. I am willing to use CoAP with a TCP connector. I performed a few tests and found out the coap blockwise transfer is significantly slower compared to say a simple websocket connection. 
I went through the specification and found that there is an efficient way to transfer blockwise data when using a reliable transport layer protocol like TCP or Websocket. 
https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiv1ICVmP7TAhUMB8AKHWHEA-IQFggiMAA&url=https%3A%2F%2Ftools.ietf.org%2Fhtml%2Fdraft-ietf-core-coap-tcp-tls-07&usg=AFQjCNF1sF_jE0FQt62NYZQoNUhFernTww

Questions:
1) Is the BERT option (SZX= 7) option available for TCP connection ? If not is there any way to increase the data transfer rate for larger payloads?
2) Is the websocket implementation already available or planned?

**Comment by boaks** [comment]
The TCP implementation is currently in an experimental state. 

1. BERT is not implemented.
2. websocket unfortunately also not available nor planned.

We currently focus on release 2.0 and there is still work to be done for UDP ;-(.

**Comment by TianlinZhou** [comment]
boaks@, does Cali has any plan to support BERT?

**Comment by boaks** [comment]
Generally TCP is for 2.0.x considered to be experimental, so don't expect to much support on troubles.

For BERT there is a PR #342 on branch 2.0.x. Depending on the opinion of the other committers, we may open a TCP branch or may merge it into 2.0.x.

**Comment by khannag** [comment]
+1 to indicate interest in the BERT TCP feature. We plan to leverage this to speed up multi-block transfers as well. Is there a resolution on whether this will merge into the 2.0.x or a separate TCP branch to begin with ?

**Comment by raipratheek** [comment]
@TianlinZhou @khannag branch with BERT is now available as tcp_experimental_features.
