### ISSUE TITLE
CoAP Proxy unable to resolve localhost address

### ISSUE THREAD

**Issue by i25959341** [eclipse/californium#313]
Dear Californium developers,

We are experiencing an issue where when we have only one network interface with 3 different IPv6 addresses, the HTTP to CoAP proxy doesn't work and prints the following message

> Temporary failure in name resolution

We believe the issue is to do with HttpTranslator.java at line 468-472

```
// TODO check with multihomed hosts
InetAddress localHostAddress = InetAddress.getLocalHost();
coapRequest.setDestination(localHostAddress);
```

**Comment by i25959341** [comment]
Below is our `ifconfig` output

> eth0      Link encap:Ethernet  HWaddr FA:80:66:76:E1:2F
>           inet addr:192.168.3.11  Bcast:192.168.3.255  Mask:255.255.255.0
>           UP BROADCAST MULTICAST  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1%3069687504/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:86 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:86 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1
>           RX bytes:7956 (7.7 KiB)  TX bytes:7956 (7.7 KiB)
> 
> tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
>           inet6 addr: fe80::e6a4:eb1c:695f:10c1%3069687504/64 Scope:Link
>           inet6 addr: fe80::9b4e:bd09:43e0:f19b%3069687504/64 Scope:Link
>           inet6 addr: fd01::c5c6:e9af:a231:6130%3069687504/64 Scope:Global
>           UP DEBUG POINTOPOINT RUNNING  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:15 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:500
>           RX bytes:0 (0.0 B)  TX bytes:1420 (1.3 KiB)

**Comment by boaks** [comment]
Google says "DNS Problem?" for "Temporary failure in name resolution" :-).
And the javadoc of "getLocalHost" explains, why this may occur.
So, is your DNS proper configured?
(by the way, I don't have experience with this proxy, so unfortunately, I can't help here really.)

**Comment by boaks** [comment]
If this issue still occurs, don't hesitate to reopen this issue or create a new one.
