### ISSUE TITLE
Blockwise transfer progress ?

### ISSUE THREAD

**Issue by mb590721** [eclipse/californium#316]
Hi everyone,

I would like to know if there is a way to monitor the progress of a block-wise transfer on the server side ?
In order to check the progress of a file transfer to a client for example.

Thanks a lot! 👍

**Comment by boaks** [comment]
There are two possibilities.

1. use the transparent blockwise handling (but the downside would be, that it's not only monitoring, it delegates the complete blockwise handling to the upper layer :-) ).

2. Wait for PR #312 and use the MessageObserver.onSent() callback.

**Comment by mb590721** [comment]
Thanks for the response, option 2 is totally what I was looking for!

**Comment by boaks** [comment]
The PR #312 must be extended, because usually someone is observing the first request only, and not the follow up request. I think we should add that forward on the blockwise layer.

**Comment by boaks** [comment]
I made a short test using a 

```
request.addMessageObserver(new MessageObserverAdapter() {
	@Override
	public void onSent() {
                // called on every single "block request"
		blocks.incrementAndGet();
	}
});

```

It works :-).
For a future version, there may be a callback with blockno/size to see the progress.
