### ISSUE TITLE
Name thread in threadpools for easier jstack reading

### ISSUE THREAD

**Issue by jvermillard** [eclipse/californium#32]
For example in CoapEndpoint.java:
`final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor(new Utils.DaemonThreadFactory());`

This generated thread names like:
`"pool-2-thread-1" #26 prio=5 os_prio=0 tid=0x00007fadc03c5000 nid=0x21 waiting on condition [0x00007fad8feed000]`

it makes reading Java thread dump pretty hard

**Comment by sophokles73** [comment]
@jvermillard,

can you check if this fixes your problem and close the issue?
