### ISSUE TITLE
CoapEndpoint ignores Empty Acknowledgement which follows a Non-confirmable response?

### ISSUE THREAD

**Issue by T0bbe** [eclipse/californium#321]
**Scenario:** OSCOAP client sends a confirmable GET to the OSCOAP server and which replies with an ACK response with the correct content. But the client fails to decrypt this response, thus responds by sending an Empty Acknowledgement message back to the server (this all intended to happen, see [1]). This Empty Acknowledgement is, however ignored at the CoapEndpoint. It is ignored because there is no Exchange which matches the MID from the response which the server sent. But should not the CoapEndpoint be able to receive unexpected Empty Acknowledgements? [2]  

Where am I doing wrong?

**[1] The OSCOAP draft states in subsection 7.4 Verifying the Response:**
_If decryption fails, the client MUST stop processing the response and, if the request is a CON message, the client MUST respond with an empty ACK back._

**[2] The RFC 7252 states in subsection 5.2.3 Non-confirmable:**
_However, an endpoint MUST be prepared to receive a Non-confirmable response (preceded or followed by an Empty Acknowledgement message) in reply to a Confirmable request, or a Confirmable response in reply to a Non-confirmable request._

Best regards,
Tobias

**Comment by boaks** [comment]
I can't see, that within RFC7252, an ACK for an ACK is valid.

I would guess, the OSCOAP draft contains an typo and **request** must be corrected to **response**.

> If decryption fails, the client MUST stop processing the response and, if the **response** is a CON message, the client MUST respond with an empty ACK back.

**Comment by T0bbe** [comment]
Thanks for the fast reply, I will raise the issue with them instead.
