### ISSUE TITLE
Scandium certificate generation problem

### ISSUE THREAD

**Issue by louisZL** [eclipse/californium#33]
Hi,

The generated scandium certificates are not working. I tried generating the certificates by following the steps mention in github link https://github.com/eclipse/californium/tree/master/scandium-core. The certificates got generated. After which we are facing BAD CERTIFICATE error from scandium( when we ran the example dtls server and example dtls client in scandium using the newly generated certificates ).

It says on the scandium says, "certificate validation failed due to signature check failed".

**Comment by sophokles73** [comment]
Let me get this straight first.
* You simply re-generated the certificates using the steps outlined in scandium-code without altering any parameters/config? 
* You then updated the DTLS server & client to use the newly generated certificate stores to retrieve the private, public keys and certificates from?
* You ran the client using PSK to authenticate to the server, i.e. the certificate that could not be validated is the server certificate, right?

**Comment by sophokles73** [comment]
No response anymore ...
