### ISSUE TITLE
DTLS / connection from session ticket / peer address

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#337]
If a Connection is created with `Connection(final SessionTicket sessionTicket)` no `peerAddress` will be available. I'm not sure, if `DTLSConnector.resumeExistingSession` would get such an Connection, but if, using the result of `previousConnection.getPeerAddress()` will fail.

So, is it ensured, that `DTLSConnector.resumeExistingSession` will not get a Connection without peer address?

**Comment by sbernard31** [comment]
I never tested `SessionTicket`.
If you talk about [this line](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L1113) I think it's ok as we check that `previousConnection.hasEstablishedSession`  ?

**Comment by boaks** [comment]
Thanks!
