### ISSUE TITLE
How can I solve the NAT traversal problem?

### ISSUE THREAD

**Issue by louisZL** [eclipse/californium#34]
The endpoint is coap server and coap client. But how can I solve the NAT traversal problem ?

**Comment by sophokles73** [comment]
I am sorry but you will need to be a bit more specific regarding what you want to do and what you perceive as
> the NAT traversal problem

**Comment by sophokles73** [comment]
No response anymore ...

**Comment by E12351** [comment]
I have a similar problem with NAT. I need to communicate with a device which is behind the NAT. Simply it has private IP. In my case device is initially send the request to the server, after I need to send a GET request to the device. pls, help.

**Comment by boaks** [comment]
The initial text was just without the details, which would have been required to answer it useful.
The new comment also misses the most of the information.

Base NAT scenario:

> 1. Client (private ip + port) -->  NAT --- (mapped, public ip + NATed port) --> Server
> 2. Client (private ip + port) <--  NAT <-- (mapped, public ip + NATed port) --- Server

That should work!

Extended time NAT scenario:

> 3.  ... time passes ... NAT removes mapping from private ip + port to public NATed port
> 4. lost <--  NAT <-- (public ip + NATed port) --- Server
 
This doesn't work. There are two possibilities to overcome this:
a. don't let the time pass. Send messages just to ensure, the NAT keeps the mapping. This will generate traffic and therefore comes with cost (energy and communication volume).
b. The server is aware, that, if for a certain period of time, no messages are exchanged, then the client gets unreachable until the client start to send messages again (see LWM2M queue mode).

It depends on your application and requirements, if you either use a or b.

**Comment by E12351** [comment]
ok. I'll try those. thank you for the support.
