### ISSUE TITLE
CoapServer / branch 2.0.x

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#348]
`CoapServer.destroy()` in branch 2.0.x destroys the endpoints twice, in lines 252 and in lines 273.
Any reason for that?

**Comment by sbernard31** [comment]
Looks like a bug.
I suppose we should only keep the one in block finally, because tasks execution probably need endpoints ?

**Comment by boaks** [comment]
@sophokles73 

> commit 870fa01f899f28fad2544d318362743d38455d10
> Author: Kai Hudalla <kai.hudalla@bosch-si.com> 2016-09-29 15:59:48
> 
> Improve shutdown of CoapServer's scheduled executor.
> 
> Reduce time to wait for executing tasks to finish.
> 

Was the earlier endpoints destroy  the improvement?
I tested the BlockwiseTransferTest, it takes about 3.5 s with or without the earlier endpoints destroy.

**Comment by sophokles73** [comment]
I tried to find a way to not have to wait the full 5 secs every time the executor is shut down. That's all.

**Comment by boaks** [comment]
Thanks!
So, if we remove the early destroy of endpoint, we just must take care, if the tests then failing.
So I think we can try that.

**Comment by boaks** [comment]
The remove of the duplicate seems not to cause additional failures.
