### ISSUE TITLE
Possible MID reuse before lifetime end for token

### ISSUE THREAD

**Issue by hoqhuuep** [eclipse/californium#354]
Hello,

We recently updated from Californium from version 2.0.0-M2 to 2.0.0-M3. (NOTE: We are still isolating the cause of our issue, there have been other changes, but Californium is a key suspect.)

After this update, we are seeing the below warning regularly in our logs, and we are receiving mismatched responses for our requests.

> Thu, 06 Jul 2017 19:31:03 GMT  82   WARNING        [JUL] [org.eclipse.californium.core.network.UdpMatcher#receiveResponse] Possible MID reuse before lifetime end for token [], expected MID 987 but received 986

We have seen this warning raised with 2 different outcomes:
1. The warning is logged, however we get the correct response for the message anyway
1. The warning is logged, and the **response which is returned is the response for a previous request**!

Are you aware of any recent changes to Californium which could have introduced this issue?

Also be aware that we are funnelling all of our requests through a single thread to try to avoid such issues. This was working fine for us when using 2.0.0-M2.

```java
        private final ScheduledExecutorService timeoutExecutor = Executors.newSingleThreadScheduledExecutor();
        private final ExecutorService executor = Executors.newSingleThreadExecutor();
 
        private Response sendRequest(Code code, String uri, byte[] body, Duration timeout) throws InterruptedException, ExecutionException {
                // Use single threaded executor to ensure request/responses are done one at a time
                return executor.submit(() -> {
                        Request request = new Request(code);
                        request.setURI(uri);
                        request.setPayload(body);
                        request.setToken(new byte[0]);
                        request.getOptions().setContentFormat(MediaTypeRegistry.APPLICATION_OCTET_STREAM);
                        request.getOptions().setAccept(MediaTypeRegistry.APPLICATION_OCTET_STREAM);
                        request.send(getEndpoint());
                        // request.waitForResponse(long timeout) uses System.currentTimeMillis()
                        // which is affected by system time changes, so we need to handle the timeout manually.
                        timeoutExecutor.schedule(() -> {
                                request.setTimedOut(true);
                        }, timeout.toNanos(), TimeUnit.NANOSECONDS);
                        return request.waitForResponse();
                }).get();
        }
```

Thanks!

**Comment by sophokles73** [comment]
My understanding is that the observed behavior you describe above is the one observed with M3, right?
Could you also describe the observed behavior with M2, i.e. did you also see warnings logged but *always* either got the matching response or none at all?

**Comment by boaks** [comment]
> request.setToken(new byte[0]);

If you use multiple request with the same token, overlapping responses could not be mapped!
With the same token, you must ensure "NSTART 1" . 
This means: do not reuse the token until "EXCHANGE_LIFETIME" is expired!
(RFC7252 is more relaxed about that, but:
==== CON/REQ T1 MID1 ====>
      *= ACK/RESP T1 MID1 ===== (delayed somehow)
==== CON/REQ T1 MID1 ====> (repeated)
<=*                                                   (now delayed deliver)
==== CON/REQ T1 MID2 ====> (next new request, same token)
<=== ACK/RESP T1 MID1 ===== (response for the repeated request)

At this point, its impossible to differentiate between the two exchanges)

So use token!

**Comment by sophokles73** [comment]
Or better yet, do *not* explicitly set the token but let Cf determine a token for you on send...

**Comment by boaks** [comment]
Just to add:
The warning message will also be shown for 2.0.x-M4, but the M4 will ignore the MID mismatching ACK.
But I would recommend to use different tokens, it makes it easier to understand, which messages are exchanged.

**Comment by hoqhuuep** [comment]
Thank you both for looking into this!

@sophokles73 Yes, what I mentioned is the observed behaviour with M3. We have run some more targeted testing with M2 over the weekend. We have found some instances of the warning, though fewer than we have seen with M3. In all cases of the warning with M2 it looks like we get the correct response anyway. However, taking into account the scenario that @boaks has mentioned, I feel we just got lucky.

@boaks Thanks for the information! Looks like this is the root cause of our problem.

I remember that we had a reason to explicitly remove the token. I think maybe this part of the protocol was not yet implemented by the sensor nodes which we are sending the requests to. It was 8 months ago when this change was made, so my memory is not so good. I will have to investigate this more.

**Comment by boaks** [comment]
> I think maybe this part of the protocol was not yet implemented by the sensor nodes which we are sending the requests to.

:-) for the sensor node it's just a copy of the token from the request into the response.

**Comment by boaks** [comment]
@hoqhuuep 

So does it work for you? If so, could you please close the issue?

**Comment by boaks** [comment]
If the issue still exists, please open it again are create a new one.

**Comment by hoqhuuep** [comment]
@boaks no worries! Thanks again for the support! Sorry I haven't got back to you with the result yet, this topic has been bumped down our priority list. I will let you know when we have tested the fix.
