### ISSUE TITLE
Block2 request does not seem to notify CoapHandler#onError if exchange stucks on non-first request.

### ISSUE THREAD

**Issue by evgeniynickolaev** [eclipse/californium#36]
Hello!
I've been playing around block transfer and noticed one thing.
I use Californium 1.0.3.
I have a Client which sends CON GET and a Server which responds with large payload.
Then, I tried to emulate network loss and added a connector to the Client which skipped some of ACKs.

When I skip the first ACK, after retries and some time it logs "Timeout: retransmission limit reached, exchange failed, message: ..." and my CoapHandler#onError is being invoked.

When I skip any intermediate ACK, it logs the same line but does not invoke CoapHandler#onError.
I've made some debugging.

org.eclipse.californium.core.network.stack.ReliabilityLayer.java:

```
 protected abstract class RetransmissionTask implements Runnable {
	<skimmed>
359:	} else {
	    LOGGER.fine("Timeout: retransmission limit reached, exchange failed, message: "+message);
	        exchange.setTimedOut();
	        message.setTimedOut(true);
	<skimmed>
```

And if the ```message``` is an intermediate block transfer request, it does not have any handlers, so no onError could be called. But ```exchange#request``` has the original request which has its' handlers.

Maybe the ```exchange#request.setTimedOut(true)``` should be called there in the case of block transfer? It looks reasonable for me because in case of success CoapHandler#onLoad of the original request is called.

The sample code will be provided if requested.

**Comment by sophokles73** [comment]
Hi @evgeniynickolaev,

this is a very good observation you have made. Thanks for pointing this out and doing the debugging :-)
Your proposal for fixing it goes in the right direction, I think. However, we will need to distinguish between requests originating locally vs. requests we are sending a response to. 

Would you like to create a PR for fixing it? If so, make sure to read the [contribution guide](../blob/master/CONTRIBUTING.md) ...

**Comment by evgeniynickolaev** [comment]
Thanks for reply!
Yes, I am very keen to contribute, I'll work on it.

**Comment by sophokles73** [comment]
Cool :-) Looking forward to your PR (and discussing it) ...

**Comment by evgeniynickolaev** [comment]
This is the PR.

Not sure if checking the message class is sufficient to cover:
> However, we will need to distinguish between requests originating locally vs. requests we are sending a response to.

Also I've found this case too special to be included in BlockwiseTransferTest.

**Comment by sophokles73** [comment]
However, it would still be good to have a test case for this.
I think you can create one along the lines of the `org.eclipse.californium.core.test.lockstep.BlockwiseClientSideTest` ...

**Comment by evgeniynickolaev** [comment]
OK, will add

**Comment by evgeniynickolaev** [comment]
I've pushed a test case. I don't really like it but wanted to confirm if the approach is appropriate at first.

**Comment by sophokles73** [comment]
I think the test itself does exactly what it should do :+1: 
Why don't you like it? ;-)
I have added some proposals for simplification ...

**Comment by sophokles73** [comment]
Oh, BTW: please rebase your branch onto current master ...

**Comment by evgeniynickolaev** [comment]
Thank you)
Is it OK to smash my commits into one during rebase and push it with force?

2016-04-22 10:40 GMT+03:00 Kai Hudalla <notifications@github.com>:

**Comment by sophokles73** [comment]
Absolutely

**Comment by evgeniynickolaev** [comment]
Done

**Comment by mkovatsc** [comment]
Hi, also thanks from my side on spotting and fixing this.

I noticed that we are more and more smeering the layers. While this is a valid fix for now, I will try to solve it purely from the BlockwiseLayer, probably by attaching a MessageObserver there on the intermediary blocks.

**Comment by sophokles73** [comment]
Good idea, @mkovatsc :+1:
