### ISSUE TITLE
best Californium.properties values

### ISSUE THREAD

**Issue by RashaGhadeer** [eclipse/californium#360]
I send images from mobile  to californium server using post
when i send one image it  received correctly , but when sending two images in less than 6 sec it give error "org.eclipse.californium.core.network.stack.BlockwiseLayer handleInboundBlockwiseUpload
Wrong block number. Expected 0 but received 9. Respond with 4.08 (Request Entity Incomplete" 
how can i solve it?
and what the best values i should put in file (Californium.properties) to send and receive large resources?

**Comment by boaks** [comment]
Can you give us more information about your client and the PUT? 
Do you use the same token? 
Dou you use the same destination resource?

**Comment by RashaGhadeer** [comment]
the client is mobile app (android) it capture image every interval and save it on mobile then send it to the server , the code for sending image(file) is :
        byte[] bytesArray = new byte[(int) file.length()];
        FileInputStream fis = new FileInputStream(file);
        fis.read(bytesArray); //read image into bytes[]
        fis.close();
        Request request = Request.newPost();
        String u;
        u = "coap://" + mServerAddress + ":" + mPort + "/image";
        request.setURI(u);
        System.out.println(u);
        request.setPayload(bytesArray);
        request.getOptions().setContentFormat(MediaTypeRegistry.IMAGE_JPEG);
        try {
            request.send();
        } catch (Exception e) {
            System.err.println("Failed to execute request: " + e.getMessage());
        }

and the Server receive this image and store it in file (new image file for each image received) then do face detection and face recognition on it.
the code in the server to receive post is:
	public void handlePOST(CoapExchange exchange){		     
		String payload = exchange.getRequestText();
		byte[] pp;
		pp= exchange.getRequestPayload();
		String filename = "D:/coapfaces/pic_"+ System.currentTimeMillis() / 1000L + ".jpg";
		File file = new File(filename);
		try {
			FileOutputStream fileIn = new FileOutputStream(file);
			fileIn.write(pp);
			fileIn.close();
		}
		catch(Exception e)
		{}
		Response response = new Response(ResponseCode.CREATED);
		exchange.respond(response);
            }

**Comment by RashaGhadeer** [comment]
#Californium CoAP Properties file
#Mon May 08 20:56:54 GMT-08:00 2017
HTTP_SERVER_SOCKET_BUFFER_SIZE=1024
UDP_CONNECTOR_OUT_CAPACITY=2147483647
CONGESTION_CONTROL_ALGORITHM=Cocoa
USE_CONGESTION_CONTROL=false
ACK_TIMEOUT=2000
MAX_ACTIVE_PEERS=150000000
TCP_CONNECT_TIMEOUT=10000
NOTIFICATION_CHECK_INTERVAL_COUNT=100
MAX_MESSAGE_SIZE=1024000000
DEDUPLICATOR=DEDUPLICATOR_MARK_AND_SWEEP
TCP_CONNECTION_IDLE_TIMEOUT=10
COAP_PORT=5683
ACK_TIMEOUT_SCALE=2.0
PREFERRED_BLOCK_SIZE=1024
NETWORK_STAGE_RECEIVER_THREAD_COUNT=4
PROTOCOL_STAGE_THREAD_COUNT=4
MAX_TRANSMIT_WAIT=93000
USE_STRICT_RESPONSE_MATCHING=false
UDP_CONNECTOR_RECEIVE_BUFFER=0
EXCHANGE_LIFETIME=247000
HTTP_SERVER_SOCKET_TIMEOUT=100000
CROP_ROTATION_PERIOD=2000
UDP_CONNECTOR_DATAGRAM_SIZE=1024
MAX_RETRANSMIT=4
MAX_PEER_INACTIVITY_PERIOD=600000
MAX_RESOURCE_BODY_SIZE=1024000000
NOTIFICATION_CHECK_INTERVAL=86400000
LEISURE=5000
HTTP_CACHE_RESPONSE_MAX_AGE=86400
BLOCKWISE_STATUS_LIFETIME=600000
UDP_CONNECTOR_SEND_BUFFER=0
TCP_WORKER_THREADS=1
HEALTH_STATUS_PRINT_LEVEL=FINEST
NETWORK_STAGE_SENDER_THREAD_COUNT=4
NON_LIFETIME=145000
TOKEN_SIZE_LIMIT=8
HTTP_PORT=8080
MARK_AND_SWEEP_INTERVAL=10000
HEALTH_STATUS_INTERVAL=60
ACK_RANDOM_FACTOR=1.5
NSTART=1
USE_RANDOM_MID_START=true
HTTP_CACHE_SIZE=32
PROBING_RATE=1.0
NOTIFICATION_REREGISTRATION_BACKOFF=2000
COAP_SECURE_PORT=5684

**Comment by boaks** [comment]
I'm not sure, what you're system is intended to do, if there are more picture data to transfer then coap (over UDP with NSTART-1) is able to transfer.

But anyway:
POST to the same resource (same URI "coap://" + mServerAddress + ":" + mPort + "/image";) makes it difficult for REST to differentiate between your transfers. FMPOV, the newer one would stop the ongoing one. Is this the right approach in your case to lose the old picture?
If not, and you want to get both, you may consider using different URIs (e.g. POST to URI coap://" + mServerAddress + ":" + mPort + "/images/" + (System.currentTimeMillis() / 1000L) + ".jpg" and use Resource, which handles also all sub-resource traffic (not only "images", also "images/1.jpg" or "images/2.jpg", 
see, cf-simplefile-server, SimpleFileServer.FileResource how to implement such resource with 

```
public Resource getChild(String name) {
			return this;
		}

```
, which catches all and use the approach show in handleGET to extract the sub resource path from the sent URI.)

But this will not help you out, if you want to sent more data then coap would be able to transfer.

**Comment by sophokles73** [comment]
I can only support @boaks point:
CoAP over UDP is not very well suited for doing file transfer. If that is your predominant use case you should use FTP or HTTP. CoAP is intended to support the efficient transmission of very small payloads (several to dozens of bytes) where you only need one (small) UDP packet to transfer it.

**Comment by boaks** [comment]
Does it work for you in the meantime?
