### ISSUE TITLE
Implementing CoAP Client

### ISSUE THREAD

**Issue by greluc** [eclipse/californium#361]
Hi,

i've got a problem with implementing a CoAP Client with DTLS.

I used the cli client from californium.tools as blueprint, but i never get handshake with the server:

Test started
 1 CONFIG [InMemoryConnectionStore]: Created new InMemoryConnectionStore [capacity: 150.000, connection expiration threshold: 1.800s] - (org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.java:232) <init>() in thread main at (2017-07-19 09:40:43)
 1 CONFIG [DTLSConnector]: Cannot determine MTU of network interface, using minimum MTU [1280] of IPv6 instead - (org.eclipse.californium.scandium.DTLSConnector.java:356) start() in thread main at (2017-07-19 09:40:43)
 1 INFO [DTLSConnector]: DTLS connector listening on [0.0.0.0/0.0.0.0:50220] with MTU [1.280] using (inbound) datagram buffer size [16.474 bytes] - (org.eclipse.californium.scandium.DTLSConnector.java:309) start() in thread main at (2017-07-19 09:40:43)
22 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Sender-0.0.0.0/0.0.0.0:50220] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
23 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Receiver-0.0.0.0/0.0.0.0:50220] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Receiver-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
Client started
SEND
WAIT
22 FINER [DTLSConnector]: Sending application layer message to peer [vs0.inf.ethz.ch/129.132.15.80:5864] - (org.eclipse.californium.scandium.DTLSConnector.java:1278) sendMessage() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
22 FINER [DTLSSession]: Setting MTU for peer [vs0.inf.ethz.ch/129.132.15.80:5864] to 1.280 bytes - (org.eclipse.californium.scandium.dtls.DTLSSession.java:214) setMaxTransmissionUnit() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
22 FINER [DTLSSession]: Setting maximum fragment length for peer [vs0.inf.ethz.ch/129.132.15.80:5864] to 1.227 bytes - (org.eclipse.californium.scandium.dtls.DTLSSession.java:598) determineMaxFragmentLength() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
22 FINE [Connection]: Handshake with [vs0.inf.ethz.ch/129.132.15.80:5864] has been started - (org.eclipse.californium.scandium.dtls.Connection.java:865) handshakeStarted() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
22 FINEST [Record]: Encrypting record fragment using current write state
DTLSConnectionState:
	Cipher suite: TLS_NULL_WITH_NULL_NULL
	Compression method: NULL
	IV: null
	MAC key: null
	Encryption key: null - (org.eclipse.californium.scandium.dtls.Record.java:939) encryptFragment() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:43)
22 FINEST [DTLSConnector]: Sending record of 93 bytes to peer [vs0.inf.ethz.ch/129.132.15.80:5864]:
==[ DTLS Record ]==============================================
Content Type: Handshake (22)
Peer address: vs0.inf.ethz.ch/129.132.15.80:5864
Version: 254, 253
Epoch: 0
Sequence Number: 0
Length: 80
Fragment:
	Handshake Protocol
	Type: CLIENT_HELLO (1)
	Peer: vs0.inf.ethz.ch/129.132.15.80:5864
	Message Sequence No: 0
	Fragment Offset: 0
	Fragment Length: 68
	Length: 68
		Version: 254, 253
		Random:
			GMT Unix Time: Wed Jul 19 09:40:43 CEST 2017
			Random Bytes: 38 9B 82 43 36 0D 37 5A 93 DE 05 D8 56 AF D7 83 3C CC C7 29 9D 33 E2 FB BE 8C C0 10
		Session ID Length: 0
		Cookie Length: 0
		Cipher Suites Length: 2
		Cipher Suites (1 suites)
			Cipher Suite: TLS_PSK_WITH_AES_128_CCM_8
		Compression Methods Length: 1
		Compression Methods (1 method)
			Compression Method: NULL
		Extensions Length: 24
			Extension: elliptic_curves (10)
				Length: 8
				Elliptic Curves Length: 6
				Elliptic Curves (3 curves):
					Elliptic Curve: secp256r1 (23)
					Elliptic Curve: secp384r1 (24)
					Elliptic Curve: secp521r1 (25)
			Extension: ec_point_formats (11)
				Length: 2
				EC point formats length: 1
				Elliptic Curves Point Formats (1):
					EC point format: uncompressed (0)
			Extension: server_certificate_type (20)
				Server certificate type: RAW_PUBLIC_KEY

=============================================================== - (org.eclipse.californium.scandium.DTLSConnector.java:1441) sendFlight() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:44)
22 FINER [DTLSConnector]: Sending flight of 1 message(s) to peer [vs0.inf.ethz.ch/129.132.15.80:5864] using 1 datagram(s) of max. 1.280 bytes - (org.eclipse.californium.scandium.DTLSConnector.java:1441) sendFlight() in thread DTLS-Sender-0.0.0.0/0.0.0.0:50220 at (2017-07-19 09:40:44)
26 FINE [DTLSConnector]: Re-transmitting flight for [vs0.inf.ethz.ch/129.132.15.80:5864], [3] retransmissions left - (org.eclipse.californium.scandium.DTLSConnector.java:135) handleTimeout() in thread pool-1-thread-1 at (2017-07-19 09:40:45)
26 FINEST [DTLSConnector]: Sending record of 93 bytes to peer [vs0.inf.ethz.ch/129.132.15.80:5864]:

The following code is used:

main method

    fun testCoAP() {
    val gateway = Gateway("1", "vs0.inf.ethz.ch")

    val client = Client(gateway, "sesame")

    println("Client started")

    val listResponses = client.sendMessage("/.well-known/core", "GET", "", false)

    println("Message send and Response arrived")

    if(listResponses.size > 0){
        println(listResponses.get(0).payload)
    }
    }

the client:
     

    public class Client
    {

    static {
        CaliforniumLogger.initialize();
        CaliforniumLogger.setLevel(Level.WARNING);

        ScandiumLogger.initialize();
        ScandiumLogger.setLevel(Level.ALL);
    }

    // for coaps
    private static Endpoint dtlsEndpoint;

    // exit codes for runtime errors
    // initialize parameters
    private URI uri;
    private Gateway gateway;

    public Client(Gateway gateway, String psk) throws IOException, GeneralSecurityException //TODO get secure input of psk over the api from outside
    {
        this.gateway = gateway;

        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();

        InMemoryPskStore pskStore = new InMemoryPskStore();
        pskStore.addKnownPeer(gateway.getInetAddress(), PRESET_CLIENT_IDENTITY, psk.getBytes()); //TODO get secure input of psk over the api from outside
        builder.setPskStore(pskStore);
        builder.setSupportedCipherSuites(new CipherSuite[]{CipherSuite.TLS_PSK_WITH_AES_128_CCM_8});

        DTLSConnector dtlsconnector = new DTLSConnector(builder.build(), null);

        dtlsEndpoint = new CoapEndpoint(dtlsconnector, NetworkConfig.getStandard());
        dtlsEndpoint.start();
        EndpointManager.getEndpointManager().setDefaultEndpoint(dtlsEndpoint);
    }

    LinkedList<Response> sendMessage(String path, String method, String payload, Boolean loop)
    {
        try
        {
            uri = new URI("coaps://" + gateway.getInetAddress().getHostString() + ":" + gateway.getInetAddress().getPort() + path);
        }
        catch(URISyntaxException e)
        {
            System.err.println("Failed to parse URI: " + e.getMessage());
        }

        // create request according to specified method
        Request request = newRequest(method);

        request.setURI(uri);
        request.setPayload(payload);
        request.getOptions().setContentFormat(MediaTypeRegistry.TEXT_PLAIN);

        // execute request
        LinkedList<Response> listResponse = new LinkedList<>();
        try
        {
            request.send(dtlsEndpoint);

            // loop for receiving multiple responses
            do
            {
                // receive response
                Response response = null;
                try
                {
                    response = request.waitForResponse();
                }
                catch(InterruptedException e)
                {
                    System.err.println("Failed to receive response: " + e.getMessage());
                }

                // output response
                if(response != null)
                {
                    listResponse.add(response);
                }
                else
                {
                    // no response received
                    System.err.println("Request timed out");
                    break;
                }
            }
            while(loop);
        }
        catch(Exception e)
        {
            System.err.println("Failed to execute request: " + e.getMessage());
        }
        return listResponse;
    }

    /*
     * Instantiates a new request based on a string describing a method.
     *
     * @return A new request object, or null if method not recognized
     */
    private Request newRequest(String method)
    {
        if(method.equals(METHOD_GET))
        {
            return Request.newGet();
        }
        else if(method.equals(METHOD_POST))
        {
            return Request.newPost();
        }
        else if(method.equals(METHOD_PUT))
        {
            return Request.newPut();
        }
        else if(method.equals(METHOD_DELETE))
        {
            return Request.newDelete();
        }
        else if(method.equals(METHOD_DISCOVER))
        {
            return Request.newGet();
        }
        else if(method.equals(METHOD_OBSERVE))
        {
            Request request = Request.newGet();
            request.setObserve();
            return request;
        }
        else
        {
            System.err.println("Unknown method: " + method);
            return null;
        }
    }
    }

What has to be done to establish a dtls (psk) secured connection with californium and scandium?

Thank you very much,

Lucas

**Comment by boaks** [comment]
Using the californium (2.0.x) demo-apps / cf-secure / SecureServer and 
californium.tools / cf-client / ConsoleClient works on my side. 

java -jar cf-client-1.1.0-SNAPSHOT.jar -psk DISCOVER coaps://localhost
PSK Identity: password
Secret Key (input hidden): sesame

So, which server do you use? How did you setup your used PSK credentials on the server side (identity + preshared secret)?

**Comment by greluc** [comment]
i am trying to connect to the public test server under http://vs0.inf.ethz.ch/

the identity is password and the psk is sesame

**Comment by boaks** [comment]
So, try to connect to a "local"  californium (2.0.x) demo-apps / cf-secure / SecureServer.
If that works, you may contact the people who run that "public test server under http://vs0.inf.ethz.ch/". 
 
For "iot.eclipse.org" it would take me some days to find out, what would be required.

**Comment by greluc** [comment]
ok, i'll try it

**Comment by greluc** [comment]
solved it, was just a simple typo

**Comment by boaks** [comment]
> solved it, was just a simple typo

So, would you then please close the issue?
