### ISSUE TITLE
Using a class implementing Message Deliverer to deliver messages

### ISSUE THREAD

**Issue by lakshT** [eclipse/californium#370]
I want to add some custom code to my implementation such that the code would be executed every time a request arrives but before it reaches its corresponding request handling method (Eg. handleGET) . Is implementing a custom message deliverer a good idea to place that code in?

**Comment by sophokles73** [comment]
I guess this depends on whether the code you want to run is completely independent from the particular resource being requested. If yes, then I'd say that the `MessageDeliverer` is indeed a place where you could plug in such behavior.

Be careful, though, not to block the request processing. You might want to run such code on the target resource's `Executor` (if set) in such cases. This, of course, is no option if your code has to be finished *before* the request is processed by the resource.

**Comment by lakshT** [comment]
If I write my ownMessageDeliverer implementing MessageDeliverer and set it to the server. Would my message deliverer be thread safe by default or do I have to make it thread safe in the code that I write?

**Comment by sophokles73** [comment]
That will depend on the things you want to do in your deliverer. However, it should be fair to assume that when `MessageDeliverer.deliverRequest()` is executing, no other thread will concurrently access the current `Request`.
