### ISSUE TITLE
Scandium: Error while validating client certificate in cf-secure using democerts

### ISSUE THREAD

**Issue by lakshT** [eclipse/californium#371]
I faced an issue while authenticating the client using X.509 certificates instead of RawPublicKeys (i.e. changing the boolean parameter in setIdentity method to false). During the handshake I get a message.

Aug 01, 2017 1:27:37 AM org.eclipse.californium.scandium.DTLSConnector terminateOngoingHandshake
INFO: Aborting handshake with peer [/127.0.0.1:38298]: Certificate chain could not be validated

and the handshake doesn't completes. 

The version I'm using is 2.0.0-SNAPSHOT.
Also the certificates I'm using are from the repository.

**Comment by sophokles73** [comment]
fixed on master in 361b10cf85b19994e54841c303e5fcc821139632
fixed on 1.0.x in 17c1154228a114e444a13d18b7a363230d727db0
fixed on 2.0.x in 7530b2cf01de621e78404895be1796becc879ddb

**Comment by sophokles73** [comment]
@lakshT 
should be fixed, can you re-check using your setup?

**Comment by lakshT** [comment]
Its still not working for me. I get the same error message.

**Comment by sophokles73** [comment]
Are you building from 2.0.x or are you using the snapshots from the Eclipse Repo?

**Comment by lakshT** [comment]
Turns out I was using the snapshots from Maven central repository. I added eclipse californium repo to my pom file. I works fine now.
Thanks for your help, I really appreciate it. :-)

**Comment by sophokles73** [comment]
The fix should have made it into the nightlies on Eclipse Repo by now as well.
If this is fixed for you, can you please also close the issue?

**Comment by lakshT** [comment]
Sure, I'll close the issue.
