### ISSUE TITLE
Add getConnector() on CoapEndpoint

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#396]
Should it be acceptable to add `getConnector` method to `CoapEndpoint` ? 
I faced several situation where I'd like to access to it.
(e.g. in some tests or in Leshan client to be able to clear connection state)

**Comment by boaks** [comment]
How would you like to clear the "connection state"? stop/start?

Are there advantages clearing the connection state without the coap endpoint state?

Though you could pass in a connector, it should be able the control it without a getter but this is sure also an argument to add such an getter. 
So feel free to add, but, please, don't flush issues, if clearing the connector without clearing the coap endpoint raises failures.

**Comment by sbernard31** [comment]
Done commit : 56563fdf67117eb078b243e04374f022e53fb6f6
