### ISSUE TITLE
Replace java.logging.util by slf4j ? 

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#398]
What do you think about replacing java.logging.util by slf4j API ?

Main benefit : let users choose their logging framework.

([To go further](https://stackoverflow.com/questions/11359187/why-not-use-java-util-logging))

**Comment by boaks** [comment]
From my memory, `java.logging` was used to minimize the external dependencies.
Changing that, would cause a lot/flood of changes. Therefore, I'm not sure, when this should be done.
For using californium with leshan, I've implemented a logging bridge (unfortunately, using my leshan extensions, so it was declined :-) ). If wanted, I could make a PR for the LoggingBridge again (but its configuration is base on that leshan extensions). For really changing the logging in californium, I would prefer the have other PRs merged :-).

**Comment by sbernard31** [comment]
If you also think that passing to slf4j is a good point, I prefer to focus on this instead of introduce LoggingBridge in Leshan.

> For really changing the logging in californium, I would prefer the have other PRs merged :-).
It sounds reasonable.

**Comment by jvermillard** [comment]
+1 for slf4j I pushed for this move at the beginning of CF @ eclipse :)
Both performance and general adoption of SLF4J is greater than JUL. Also the API could help to simplify some logging statements

**Comment by sophokles73** [comment]
I agree that slf4j is a much better logging framework than JUL. If we want to do it we should do it as part of the 2.0 release, don't you think?

**Comment by boaks** [comment]
Hi @sophokles73,

we already had a short discussion about the next steps, please see 

https://github.com/eclipse/californium/issues/174#issuecomment-327484691

for our current plan. Though the "endpoint context" and the "logging replacement" would create a flood of changed lines, I prefer to do that step by step.

**Comment by sbernard31** [comment]
Good, it seems we agree to migrate to slf4j :)

**Comment by sophokles73** [comment]
One of the major concerns regarding external dependencies was that we always wanted to make sure that Cf can also run on constrained devices and on Android. However, I do not see why it should cease to do so if we migrate to slf4j.

**Comment by boaks** [comment]
Therefore @kaikreuzer, @fipro78, @mkovatsc, and all other users and developers:

if we change to slf4j, the way back would be too hard.
If you have objections, it's now the time!

**Comment by fipro78** [comment]
No objections against SLF4J

Am 12.09.2017 10:33 schrieb "Kai Kreuzer" <notifications@github.com>:

**Comment by sophokles73** [comment]
Ok, I have started to work on this. I will migrate the code module by module, since a lot of manual changes/adaptations are required.
The proposed order in which I update the modules is
1. element-connector
1. osgi
1. scandium
1. core
1. demo-apps
1. proxy
1. californium-tools

If there are any compelling reasons to do the update in a different order, please do not hesitate to raise your concerns :-)

**Comment by boaks** [comment]
You forgot the `element-connector-tcp` :-).

I'm not sure, if it works "half" migrated. 
I've implemented a logging bridge for `java.util.logging` to `org.slf4j` for my "LeshanExtensions". If we found, that partiality changing the logging is not possible, I could add that logging bridge to `element-connector`.

**Comment by sophokles73** [comment]
just take another look :-)
There is no need for bridging from JUL to SLF4J, during the transition we will use a JUL based implementation of the SLF4J `Logger`. All of that is available from the SLF4J project. No need to re-invent the wheel ...

**Comment by boaks** [comment]
:-).

**Comment by boaks** [comment]
@sophokles73,
your commits to 2.0.x seems to break some open PRs. 
Is this intended? Wouldn't it be better (less work to do), if we first agree on such PR before e change the logging there?

**Comment by sophokles73** [comment]
This was certainly not intended. I wouldn't have thought that the changes to the logging would *break* PRs. However, I am also interested to learn, in what way the PRs have been *broken* before we can discuss the strategy for how to proceed.

**Comment by sophokles73** [comment]
Then my take would indeed be: this is intended ;-)

This doesn't sound like we are dealing with hundreds of lines of complex code that needs to be adapted but rather like: well we need to move one or two lines of comment up or down and we need to change some log statements according to SLF4Js formatting rules.

FMPOV this is *collateral damage* that we should be able to live with if we want to make some progress with the migration to SLF4J. We could run into the same sort of problems with any other change that we are doing to classes that are also affected by the PRs.
So, to me the cost incurred by adjusting some comment and logging lines seems fair in comparison to the cost of needing to figure out at the package/class level which module can be migrated to SLF4J when. However, if I misjudged the impact and you have some PRs for which you need help with rebasing, let me know.

**Comment by sophokles73** [comment]
fixed on 2.0.x in faf1740cd53c4f744df6a43346e0d3ec909d18d1

**Comment by sbernard31** [comment]
Thx @sophokles73 great enhancement :) !

**Comment by sophokles73** [comment]
@sbernard31, let's hope this was the last time we changed the logging framework :-)

**Comment by boaks** [comment]
> last time we changed the logging framework

Why? I thought we did this to easily exchange the implementation, may be in the future to one implementation, which write as useful information then the old one we replaced :-).
