### ISSUE TITLE
Blockwise layer does not check sender identity

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#4]
The blockwise layer does not verify if all inbound requests that are part of the same transfer also contain the same sender identity.

**Comment by sbernard31** [comment]
I looked at this quickly and with the recent @boaks's addition of EndpointContext, I think this is fixed.

All responses of every requests should be sent to the request sourceContext (see [Exchange.java](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/Exchange.java#L244)). So this should also be true for blockwise.

For block requests, it seems that we don't do exactly the same thing for block1 and block2.
  - block 1 we always use the DestinationContext of the "parent" requests.
  - block 2 we use the sourceContext of the last response.

I didn't find any explanation about why we treat block1 and block2 differently.
If there is not , I think we should go for SourceContext for block1 too.

@boaks did I missed something ?

**Comment by vikram919** [comment]
As per RFC 7959 Section 2.3 Block options in request and responses,
I did not find that server/client expects sequence of block requests with block1/block2 should be from the same endpoint, but response with block1 option is used (e.g., a 2.xx response for a PUT or POST request) then:

> i.e., the server collects further blocks from the
            same endpoint and plans to implement the request atomically

**Comment by sbernard31** [comment]
@vikram919, I found : 

>Where access to a resource is only granted to clients making use of
   specific security associations, all blocks of that resource MUST be
   subject to the same security checks

I think we can translate it by all block requests should come from the same endpoint. (at least for secure one)

My previous response was a bit out of topic. The topic was about "all requests received for a given block transfer should come from the same identity". This is not done for now. I think this could make sense to implement it.

**Comment by boaks** [comment]
@sbernard31 

> For block requests, it seems that we don't do exactly the same thing for block1 and block2.

I checked your analysis (but without spending more time in it), it's just as it is and I don't know, if it's a mistake or if there is a good reason for it :-).

Currently I concentrate on other issues, but after that, I will come back to this. so please don't close it!

**Comment by boaks** [comment]
> For block requests, it seems that we don't do exactly the same thing for block1 and block2.
> 
>     block 1 we always use the DestinationContext of the "parent" requests.
>     block 2 we use the sourceContext of the last response.

I would go to change block1 to use also the sourceContext of the last response. That would reflect  in my opinion the best practice of the endpoint context idea.

**Comment by boaks** [comment]
Fixed with 

https://github.com/eclipse/californium/commit/1610ed62ba46d26095afbd429acc66e5223f9060
