### ISSUE TITLE
increase default value of MAX_RESOURCE_BODY_SIZE  ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#403]
`MAX_RESOURCE_BODY_SIZE``is the maximum size of a resource body (in bytes) that will be accepted as the payload of a POST/PUT or the response to a GET request in a transparent blockwise transfer.
The default value is 2048 bytes.

Knowing that default value of `PREFERRED_BLOCK_SIZE` is 512 bytes, this means that by default the we can only do block exchange of 4 blocks.

Should we increase this to something like 5120 or 10240 (maybe more)?

**Comment by boaks** [comment]
your right. I stumbled over that a couple of times in the last day.
I would vote for 8192.

**Comment by sophokles73** [comment]
I have no particular opinion about the default value. My only concern would be memory consumption during operation. That's the reason why I used a low value initially, i.e. requiring people to explicitly set it to a higher value and (hopefully) think a little about the consequences.

**Comment by boaks** [comment]
> think a little

The nasty of this is, that it's not too easy to see that error :-).

**Comment by sbernard31** [comment]
Ok, so let's go for 8192.

**Comment by boaks** [comment]
Done with commit  c77086905e6084b4b095246862446f2cc6d8924b.
