### ISSUE TITLE
Efficient way to notify particular clients [enhancement]

### ISSUE THREAD

**Issue by AGutan** [eclipse/californium#409]
I checked the source code and fount this method `notifyObserverRelations(final ObserveRelationFilter filter)` for notifying a sub-set of clients.

According to my use case, the server has to notify `single particular` clients all the time. 
I feel like the forEach implementation of `notifyObserverRelations` would be a performance issue when having a great number of clients that simultaneously observe a resource.
For every notified client the server in my case would loop through the entire list of clients to find the relation and notify the client.

Would it be more efficient to have a `changed(String relationKey)` to notify only the relation with a specific key.
The implementation of `changed(String relationKey)` would be like:

`observeRelations.get(relationKey).notifyObservers();`

and `ObserveRelationContainer` would have a `.get(String key)` to get the element by key from the HashMap.

I could contribute with a PR on this.

**Comment by boaks** [comment]
> I feel like the forEach implementation of notifyObserverRelations would be a performance issue when having a great number of clients that simultaneously observe a resource.

I'm not sure, if your usage comply to the RFC7641 and the REST paradigm.
If I understand you well, you have 
- a resource
- plenty clients
- changes, which are only intended for a subset of the clients.

But RFC7641 is not a "flexible, general purpose Mechanism", it's just intended to inform (mainly all observing) clients on updates of the state.

So, may be you can describe your use-case more concrete/detailed, so that we could see, if there is a other solution.

**Comment by AGutan** [comment]
Ok let me come up with a simple example:
We have 3 clients: John, Alex, Mary.
They post temperature values to the `temperature` resource.
John: 10,20,30
Alex: 2,4,6
Mary: -5, -10, -15

Temperatures are sent to a processing framework: Spark, Storm etc.
The framework calculates averages of the temperatures.

The clients expect averages so they observe to another resource to get the result. e.g. `temperatureAverages` resource.

When Californium gets the average results from the processing framework it notifies each client individually with the average amount (on `temperatureAverages` resource).
John: 20
Alex: 4
Mary: -10

Now if there are a great number of clients expecting averages, delivering results to each one individually (and frequently) is an issue in my o

**Comment by boaks** [comment]
This smells, like your resource `temperatureAverages` should deliver different values to different clients.
FMPOV this would violate very basic grants of COAP. Such an approach would require much more, then just a selective "notify". Please note: the payload of such a notify is considered to be the same as the payload of a response to a new request. So this would end-up, that a GET will also result in a client specific result.
  
In your case I would consider to model this with different resources (e.g `john/temperatureAverages`).

**Comment by AGutan** [comment]
@boaks in case I want only John to be able to observe `john/temperatureAverages`, then
1. John will call `.observeAndwait(handler)`
2. The `john/temperatureAverages` resource will have
```
        public void handleGET(CoapExchange exchange) {

           if( isJohn(exchange) && exchange.advanced().getRequest().isObserve() )

                      //allow
           else
                      exchange.reject();

        }
```

will it work this way?

Also, generally speaking, is CoaP on Californium suitable for health related data transmission. My project is in the eHealth monitoring category.

**Comment by boaks** [comment]
Generally, if you are able to implement "isJohn" in your Resource implementation, you may use something as:

```
public void handleGET(CoapExchange exchange) {

           if( !isJohn(exchange)) {
                     // not john, the respond with proper error code
                     exchange.response(FORBIDDEN);
           }
           else if (!exchange.advanced().getRequest().isObserve() ) {
                     // you really want suppress GET request without observe option?
                     // read carefully RFC7641, your solution is in danger of not working as you expect!
                     // COAP doesn't support this "smelly misuse-case", therefore 
                     // no specified error code exists. Proprietary use of which error code ever. 
                     exchange.response(???ERROR???);
           }
           else {
               // allow
           }
    }
```

FMPOV: you want very special behaviour! I would recommend to first make a very simple approach and get used to the "overall" function of the observe.
Especially for the "isJohn()" you need a way to authenticate your clients. If this should be save, consider using DTLS encryption and the principal based on the used credentials.

**Comment by boaks** [comment]
Let me add:
californium is COAP implementation intended to comply to RFC7252 from the core group of the IETF.
(see https://projects.eclipse.org/projects/technology.californium) 
The intention is to have interoperability between different implementations.
If "special purpose" stuff would be added, it must be done very carefully not to break that interoperability.
If you don't require interoperability, you may tend to patch it. But such a patch are usually not that interesting for others.

**Comment by sbernard31** [comment]
Maybe an another approach could be to use a simple CoAP PUT.

You clients send temperatures.
When server is done to calculate the average, it do a CoAP PUT on the client `temperatureAverages` resource.

**Comment by jvalkeal** [comment]
I think we should have more precise way to select which clients to notify. I'm trying to make more higher level framework on top of californium and I have a dispatcher resource which i.e. can accept every request starting from root. Essentially I have a case where I already know that I want to notify only one client and in a filter I simply check if `ObserveRelation` is same as the one I got from `org.eclipse.californium.core.CoapResource.addObserver(ResourceObserver)`.

Like in this case it'd be nice if I could just call `changed(ObserveRelation)`. If there is a great number of clients then I assume you spend a lot of time iterating those relations.

https://tools.ietf.org/html/rfc7641 also mention as a example

> <coap://server/?query=select+avg(temperature)+from+Sensor.window:
      time(30sec)>, which accepts expressions of arbitrary complexity
      and changes its state accordingly.

These are kinda things which result only one client to get notified and what is returned back to client is not a single unique state within a resource so you really can't assume that most of a time you will notify all clients.

**Comment by AGutan** [comment]
@jvalkeal great! Looking forward to it! It's definitely a useful feature.

**Comment by jvalkeal** [comment]
https://tools.ietf.org/html/rfc7252 only vaguely mention observe as a concept, rfc7641 then defines a bit more. I've read both rfc's multiple times and I'm not exactly sure how observe should actually get handled(spec only defines what will get send to a client). It think spec leaves a lot of freedom for an implementation to choose how it will actually get implement.

Californium simply seems to `replay` original request when resource change is requested. While I don't think there is anything wrong with that as it seems to be most easiest way to implement observe notification.

If there is something I dislike about coap is its notation about resource which IMHO is a bit off. I've always thinked that coap is just a dummy/enhanced http protocol designed for udp and constrained devices. If one request path would always map to some physical device and its state, then yes observe would probably result notification for all clients, but as client is free to request pretty much same as HTTP clients then I don't think we're no longer working on one resource per one request path(and its request arguments).

I definitely see a lot of value to discuss and make things better in this observe space.

**Comment by jvalkeal** [comment]
I have a research project which hopefully some day will result an actual `Spring COAP` project. Having said that, it will share a lot of similarities with new Spring Framework 5 Webflux framework what comes for a request handling. User level api is non-blocking, though as Californium in a sense is a blocking so there is a limited feature set to behave as truly non-blocking way.

Anyway having below class with Spring Boot would simply result unique unbounded stream for every observable client with `coap://localhost:5683/obs1` and `coap://localhost:5683/obs2`
 ```
@CoapController
public class Obs {

	private final Flux<String> timestamps1 = Flux.interval(Duration.ofSeconds(2)).map(i -> {
		DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
		return "OBS1 " + dateFormat.format(new Date());
	});

	private final Flux<String> timestamps2 = Flux.interval(Duration.ofSeconds(6)).map(i -> {
		DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
		return "OBS2 " + dateFormat.format(new Date());
	});

	@CoapObservable(path = "/obs1")
	public Flux<String> obs1() {
		return Flux.from(timestamps1);
	}

	@CoapObservable(path = "/obs2")
	public Flux<String> obs2() {
		return Flux.from(timestamps2);
	}
}
```
Those who know spring and have used it with http already know where I'm getting with this. This is a same as in Spring Http where a single dispatcher servlet will handle every request within its context path.

Californium has one job which is to make solid foundation just like tomcat, undertow and other servlet engines do in their space. Hopefully coap will get some popularity in iot space and if/when it does, then reality is that people simply don't want to write resources(i.e. nobody writes servlets these days anymore). Meaning coap implementations should provide flexible frameworks for other higher frameworks to rely on.

I hope this kinda gives example of how observable could be used in a real world. One other area what I really haven't even thought of is if user is secured and authenticated and requests observe of `coap://localhost:5683/myinfo` which should notify only specific user related info exactly to that single client. Naturally other users info should not get notified to all users.

**Comment by sophokles73** [comment]
@jvalkeal wrote:

> These are kinda things which result only one client to get notified and what is returned back to client is not a single unique state within a resource so you really can't assume that most of a time you will notify all clients.

IMHO you are mistaken here in assuming that this results in only a single client being notified. Instead, *every* client that has requested the given resource with the observe option set will get notified about changes. AFAIK the Observe mechanism (so far) is not designed to support notification of select clients only. You should probably start a discussion on the IETF Core mailing list if you think that Observe should be changed in that particular way. For Californium, the main priority is to implement the underlying RFC to provide for interoperability. However, you may of course implement any kind of resource on top of that.

**Comment by boaks** [comment]
@jvalkeal 

that's a flood of information, so it's quite impossible to answer your questions or to give you a feedback for your ideas. I know, that frequently we flood a single issue by discussing the much. But I would prefer, if you split your information in separate issues.

This issue started with the idea, to have a more efficient way to filter notifies based on the clients identity. As said above, I don't think this should be done in that way. If such a notify get lost, the client has no chance to get that information again, even if it's still available on the server. so for that use-case, I would recommend do use different resources and optional add "access rights" based on the identity.

Now you point to the "conditional observe". I'm not sure, if a CoAP server will be able to process 1000 observes, or even more, 1000 different conditional observes. In many use cases the observed CoAP server will be the constrained embedded device and so FMPOV this architecture will not be successful. When I introduced the `ObserveRelationFilter`, it was intended to decouple leshan's implementation (LWM2M)  from californium (CoAP). For that, the LWM2M server is the CoAP client and you may have multiple LWM2M servers, but I would not go for 1000. 

So, if you really interested in a more efficient way, supporting such flexible conditional observes, the point would be a implementation idea to "evaluate" such expression efficiently. And can't see, that the proposed 
`changed(String relationKey)` could handle such a "conditional expression evaluation".

**Comment by boaks** [comment]
@jvalkeal 

> Hopefully coap will get some popularity in iot space and if/when it does, then reality is that people simply don't want to write resources(i.e. nobody writes servlets these days anymore). Meaning coap implementations should provide flexible frameworks for other higher frameworks to rely on.

In theoretical use-cases, one side will be a embedded constrained client (constrained starting from 128K flash 16K RAM up to something as 1MB flash, 128K RAM, but **not** a raspberry PI (1G) ). Unfortunately exactly the "thing" will be the CoAP server :-). So, you don't need to implement a californium CoAP resource in java, it's not running on the constrained device. But feel free to provide a solution for such constrained device. (may be you also consider, that for Low Power WPAN your bandwidth may be limited to a small number of "flushs" with about 120 bytes payload.)

On the CoAP client side (here I agree, that java will be one major base for implementations), I didn't really get your points. It would be great, if you could open a separate issue and try to express, what you think, californium should offer in the API.

**Comment by boaks** [comment]
So my sum up:
- if there is interest in a more efficient API for handling "conditional observes", make a proposal
- if there is interest in better usable client API, start an other issue

But: 
if you want different payload for different clients, please discuss that with the IETF-core group. 
I'm pretty sure, there will be no agreement about that!

**Comment by jvalkeal** [comment]
@boaks I'll see if there's other issues I'd need to create.

To get back to this issue of different payloads. Maybe wording in those two specs is bad or if people just have different interpretation of a specs, but a way I understand specs, observable responses can have different payloads.

rfc7252 defines that we can have query options
> each Uri-Query Option specifies one argument parameterizing the resource.

Thus each response in a normal GET can have different payload depending on query options.

rfc7641 do say
> Whenever the state of a resource changes, the server
  notifies each client in the list of observers of the resource.
  Each notification is an additional CoAP response sent by the
  server in reply to the single extended GET request and includes a
  complete, updated representation of the new resource state.

If we have a parameterized resource, then all observables are potentially notified with different payload because original GET request may return different payloads. We're all good in californium as all this already works. This is a point what I didn't understand in your reply - `if you want different payload for different clients, please discuss that with the IETF-core group` as californium can already send different payloads to different clients.

Thus we are back to why OP created this issue, more efficient way to choose observers to get notified. With parameterized resource if you just notify all clients, then you are potentially sending same unchanged payload to some clients. So I suppose we should have a better way to choose clients whose parameterized resource state is changed. This becomes quite clear with an example what rfc7641 mention:

> <coap://server/temperature/critical?above=42>, which changes its
  state based on the client-specified parameter value either every
  few seconds to the current temperature reading if the temperature
  exceeds the threshold or to "OK" when the reading drops below;

The way I read this temp examples is that when temp is above 42 then you get observe notifications when temp changes and if temp is below 42 then client is just notified OK and that payload is not re-sent as below 42 parameterized resource doesn't change. Then different clients can choose different thresholds and you need to choose who to notify.

**Comment by boaks** [comment]
@jvalkeal 

So many words, but no proposal how to improve the API to support your use cases in a "more efficient way" :-).

> This is a point what I didn't understand in your reply 
  
I wrote "different clients" and you explain something about "different Uri-Query Options" in GET.

**Comment by jvalkeal** [comment]
Earlier I mentioned that maybe we could request to notify per `ObserveRelation` (or set of `ObserveRelation`s) as those are the ones you get access from listeners. Project looks to be on jdk7 so we can't use any jdk8's new stream api's which would make possible filters much nicer from user point of view.

Maybe giving more lower level access to all relations which are used to loop through with `ObserveRelationFilter`. That might be enough to give user an option to implement filtering as he/she wishes. Thought I don't know if it's a very common case to notify partial set of clients as all or one seem to cover majority of use cases.

**Comment by boaks** [comment]
> Thought I don't know if it's a very common case to notify partial set of clients as all or one seem to cover majority of use cases.

FMPOV there may be many ideas and implementations of such query options, but these are specific. If someone wants to build a "efficient" system on that, it's mostly bound to his use-case (or "abuse-case" :-) ). It's possible to override the `addObserveRelation`, `removeObserveRelation` in `CoapResource` and call the `ObserveRelation.notifyObservers()` "efficiently" only on those relations, which are affected by the change, but I can't see the general case for a general implementation.

**Comment by jvalkeal** [comment]
Well yes if you start to modify how `CoapResource` works then things become easier to customise. Looks like all of its methods are public but how much guarantees there are that class itself is not changed in future releases(thus breaking if user biggybags its features)? I'd assume its interface `Resource` and thus those methods stays stable. But then `Resource` only cover part what `CoapResource` itself do.

I remember thinking that why `CoapResource` is not an interface as it's so central piece from user point of view. After 2.x is out there's very little flexibility to change its behaviour without raising concerns that user level code breaks. I usually try to be rather careful by not changing behaviour of classes which have an interface.

Having said that, if customisation of `CoapResource` is an answer to questions in this thread, then I suppose this issue became obsolete.

**Comment by boaks** [comment]
@AGutan 

FMPOV your initial issue of notify only specific clients based on "relation key" is no general solution and therefore I don't see, that we include such stuff. I would prefer the other proposed designs as using different resources or PUT. 

@others
Feel free to open new issues for other parts of the discussion. But to be frank, only a flood of words will not change too much :-).
