### ISSUE TITLE
Keep Block handling in BlockwiseLayer

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/californium#41]
#36 fixed a missing onError() call when an intermediary block times out.

To push a bit back on cross-layer concerns, I would like to solve this purely from the BlockwiseLayer, for instance by attaching a MessageObserver on the intermediary blocks that then calls the onError() of the original request.

This is more "nice to have" than urgent...

**Comment by sophokles73** [comment]
Fixed in b266afd
