### ISSUE TITLE
Add event on request to know where it is removed from exchangeStore.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#414]
We can be aware of several events on a message (see [MessageObserver](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/coap/MessageObserver.java))

Unfortunately there is no way to be aware if the exchange related to this message was complete.
I'm not sure if this make sense.

**My real problem :**
In Leshan we have a class which store all the requests we send to be able to cancel it if a device deregister. (see https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/CaliforniumLwM2mRequestSender.java#L142)
The idea is to avoid retransmission after deregistration.

We clear this map when we receive the ack or a response, on cancel, on failed.
But it seems this maps leaks, I suspect that we could face situation where the exchange will be complete and no event was raised through `MessageObserver`.

Maybe a better approach is to clean this map after MESSAGE_EXCHANGE_LIFETIME.

**Comment by boaks** [comment]
Feel free to extend the MessageObserver.

**Comment by boaks** [comment]
> Maybe a better approach is to clean this map after MESSAGE_EXCHANGE_LIFETIME.

If blockwise is not used ...

Otherwise we should also solve issue #316

**Comment by sbernard31** [comment]
I add some tests #475 and all seems ok. So I will close this one. We will see if this re-happen.
