### ISSUE TITLE
SSLEngine based DTLSConnector

### ISSUE THREAD

**Issue by davidgraeff** [eclipse/californium#421]
This is a feature request.

At the moment a DTLSConnector is created with a DtlsConnectorConfig. The methods `setPskStore` and `setIdentity` are used to define the secure connection related parameters.

With Java9, it is possible to implement a DTLS connection purely with an SSLEngine (http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/6721ff11d592/test/javax/net/ssl/DTLS/DTLSOverDatagram.java). 

This issue is about creating a new DTLSConnector9, that has a simplified API and fully operates on an SSLEngine:

```java
public class DTLSConnector9 {
    DTLSConnector9(InetSocketAddress bindToAddress, SSLEngine engine);
}
```

## Necessary changes of Java9, compared to Java8, for DTLS support

* `SSLContext.getInstance("DTLS")`: A DTLS security provider is available. This can be provided for older Java versions as well.
* [`SSLEngineResult.HandshakeStatus.NEED_UNWRAP_AGAIN`](http://download.java.net/java/jigsaw/docs/api/javax/net/ssl/SSLEngineResult.HandshakeStatus.html#NEED_UNWRAP_AGAIN) available next to `SSLEngineResult.HandshakeStatus.NEED_UNWRAP`
* [`engine.getSSLParameters().setMaximumPacketSize(n)`](http://download.java.net/java/jigsaw/docs/api/javax/net/ssl/SSLParameters.html#setMaximumPacketSize-int-) didn't exist before

**Comment by boaks** [comment]
Very interesting!
Could you already make some experience about performance, robustness, or interoperability?
I think, it will take some time for the californium team to setup a connector implementation based on that. 
But, If you would like to spend some time, we may prepare a branch and connector skeleton for you.

**Comment by sophokles73** [comment]
Hi @davidgraeff,

Cf currently requires Java 7 only in order to support constrained devices for which the latest Java versions are often not (yet) available. Are you saying that the Java 9 security provider can be used in Java 7 environments as well?

**Comment by davidgraeff** [comment]
@sophokles73 I checked only against Java 8. There might be more API differences to Java 7.
I have no practical experience yet, if a Java 9 security provider would work with a former Java version.

**Comment by boaks** [comment]
@davidgraeff 

So do you have experience (compared to scandium) with:
- performance
- robustness
- interoperability

And, are you interessted in try to implement a connector based on that DTLS implementation?

Currently, triggered by issue #119, we try to modularise the TCP connectors.

If that is successfull, I see (at least on an experimental branch) the possibility to support J9 DTLS as optional implementation (if the other committers agree).

**Comment by vikram919** [comment]
I have implemented a demo `java9` `DTLS9Server` and `DTLS9Client` which is not scalable.

- `performance:` 20% percent faster 
- `robustness:` did not go so far
- `interoperability:` DTLS9Server and ScandiumExampleClient are working well. On other way round DTLSClient with ScandiumExampleServer did not work. DTLS9Client throws an Exception: `Server sent an unsupported extension: type_19` as the certificate extensions replied by server are not supported by DTLS9Client.


If someone is interested, please tell me how to specify the extension types to be used by `DTLS9Client` or introduce new certificate extension cases in Scandium `HelloExtension`class to handle extensions sent my DTLS9Client. DTLS9Client uses extensions of type 13, type 17 and type 5. 
For now I have done a dirty hack by uncommenting lines  `813` and `819` in `ServerHandshaker` class.

**Comment by sophokles73** [comment]
@vikram919 
we are currently trying to tidy up outstanding issues that prevent us from doing a 2.0.0 release. Adding support for Java9's DTLS stack is currently not one of them. I am sorry, but there are only a few committers working on Cf and this issue is currently not our top priority so you may experience some more delays in getting a reply. Hope you understand.

**Comment by vikram919** [comment]
@sophokles73 
Thanks for the reply. As @davidgraeff  pointed this issue that java 9 implements a DTLS connection purely with an SSLEngine, so out of my interest I investigated on it. There are few problems concerning it. I conclude that java 9 DTLS support lacks enough documentation and seems complicated compared to 
TLS implementation so this issue may not be a high priority at the moment.

**Comment by davidgraeff** [comment]
Psk is a big problem. But I have problems to identify who's responsible at the moment for the java9 dtls module to clarify this.

**Comment by vikram919** [comment]
@davidgraeff 

> I conclude that java 9 DTLS support lacks enough documentation and seems complicated compared to TLS implementation so this issue may not be a high priority at the moment.

No one is responsible for your question. If some one know how to add PSK to java 9 DTLS they will share it here. Do not forget that this is open source platform

**Comment by boaks** [comment]
@davidgraeff 

did you tried to use the `org.eclipse.californium.elements.util.SslContextUtil` to use the same certificates for TLS and DTLS 8as you told me at the EclipseCon)? If that works for you, could you close this issue?
Or do you want to investigate more on the usability of the J9 DTLS implementation?

**Comment by davidgraeff** [comment]
In my opinion dtls should natively be supported by the java framework exactly like TLS. But I didn't manage to get psk working. At the moment I'm trying to contact the guys behind the relevant part of the java9 spec, to either improve documentation or provide an example. Until I have a working solution I will close this issue.

**Comment by boaks** [comment]
PR #561 solves the mentioned incompatibility between scandium and java 9 DTLS
