### ISSUE TITLE
Help regarding CoAP connector

### ISSUE THREAD

**Issue by naveenkumarmarri** [eclipse/californium#433]
Hi,

I'm trying to connect Twitter Heron and CoAP protocol using californium.
For that I'm trying to use UDPConnector class. I couldn't much resources online to use UDPConnector for passively listening on a URL.
Can someone share some examples or some resources on this.

Any help is highly appreciated.

Regards,
Naveen

**Comment by boaks** [comment]
> I couldn't much resources online to use UDPConnector for passively listening on a URL.

The `UDPConnector` is a UDP implementation of `org.eclipse.californium.elements.Connector`. Its inteded usage is documented in the javadoc of that `org.eclipse.californium.elements.Connector`. The UDPConnecto therefore open a DatagramSocket and send an receives UDP Datagrams through that socket. I would guess your intented usage is totally out of scope of the UDPConnector.

**Comment by naveenkumarmarri** [comment]
Hi Achim,

Thanks a lot for the reply.
I see your point on UDPConnector won't serve the purpose.
Currently I'm listening to an CoAP source using client observer and pulling the data.
instead of that I'm exploring the possibility if we can passively listen to the CoAP source.

Please correct me if it isn't possible.

**Comment by boaks** [comment]
> client observer and pulling the data.

I'm not sure, why your "client observer" pulls the data, I thougth, the notifies are send on change by the server without pulling.

>instead of that I'm exploring the possibility if we can passively listen to the CoAP source.
It's much easier to communicate, if you read
https://tools.ietf.org/html/rfc7252
https://tools.ietf.org/html/rfc7641
and use the terms of that specs.

I would guess, you simply want to observe a resource and get notifies on changes. 
Therefore you may use the CoapClient observe methods and the CoapResource.changed().

**Comment by vikram919** [comment]
> I'm exploring the possibility if we can passively listen to the CoAP source
Can you please tell us more how you would like to explore?
I don't think UDPConnector is used for listening/requsting on an URL. There is nothing to do with with UDPConnector. 
You can create an instance of CoapClient class to request an URL/URI.
For observing a resource you need CoapObserveRelation class and a new CoapHandler to receive notifications sent by server.  

.

**Comment by boaks** [comment]
@naveenkumarmarri 

Does this answer your questions about the Connector?
If so, could you please close the issue?

**Comment by naveenkumarmarri** [comment]
Sure
