### ISSUE TITLE
NIO/Async sockets

### ISSUE THREAD

**Issue by martinmine** [eclipse/californium#434]
Are there any plans for adding NIO/Async support to the UDPConnector instead of messing around with receiver/sender threads?

**Comment by boaks** [comment]
AFAIK, no plans to change the thread mess into a async callback lists mess :-).

Generally it seems, that UDP handles traffic from many clients much easier even with the sync API, than TCP does. Therefore in my opinion the benefit of changing to  a async API will not be that large.

**Comment by boaks** [comment]
By the way, you may contribute a `Connector` implementation using NIO, if you want to spend your time in it.

**Comment by sbernard31** [comment]
As we have only one socket, I 'm nore sure using NIO will be relevant.
(see https://stackoverflow.com/a/16048705)

**Comment by martinmine** [comment]
@boaks in my opinion, having to queue/dequeue messages between worker threads is far more expensive than dealing with an async API where someone else takes care of how many threads you are working with both in terms of computational resource and maintainability. I will try and implement a Netty NIO connector and see how the performance is. Thanks for the replies :)

**Comment by martinmine** [comment]
After playing around a bit, it seems that the additional overhead of the callbacks made the processing slightly more expensive compared to the current implementation. OTOH, processing and sending the packets on the same thread gave it a performance boost with the current blocking implementation, but I guess that goes beyond the scope of this issue. I have uploaded the Netty connector as a gist in case anyone is interested: https://gist.github.com/martinmine/7ef19800cdcd380a138bae5bec89e18e

**Comment by boaks** [comment]
Thanks for investigations!
