### ISSUE TITLE
Wrong use of java.util.logging.Logger is causing extensive GC and performance degradation 

### ISSUE THREAD

**Issue by martinmine** [eclipse/californium#436]
In many places around the code-base in this framework, logging is done as following:
```Java
LOGGER.fine("some message with a parameter: " + parameterObject);
```
The message will not get written unless the logger is configured to do so. However, the issue is that the `.toString()` function on `parameterObject` is called at each time this line is called. This happens with for example message objects where each message gets duplicated as their `toString` is called before calling e.g. a logger's `fine` method, for then to disregard the message as it is not going to print anything anyways. 
Instead, these parameters can be provided as arguments to the logger functions. For example:

```Java
LOGGER.log(Level.FINE, "some message with a parameter: {0}, and another one: {1}", 
    new Object[]{parameterObject, anotherParameterObject});
```

Furthermore, there are places where a `StringBuilder` is used to build a log message surrounded with am if-statement checking whether the log level for this class allows logging. This can be completely avoided using the method above.

Looking at the log function's implementation, it will first check whether logging is allowed, _then if it is_, format the message and print it (or write to file, or whatever). The reason I am submitting this issue instead of a PR is that I want to make you guys aware of this issue, as I get the impression you are not aware of the drawbacks of not using log formatting correctly. Neither do I have time to go through the code-base and fix this. This problem became apparent to me from profiling the framework where it turned out that it spent a large amount of time in the `.toString()` method.

**Comment by martinmine** [comment]
@boaks It looks like most of this is fixed in the 2.x release, at least from what I can see :+1:
That being said, this issue is still on the 1.x branch though.

**Comment by boaks** [comment]
Just to mention, currently not too many people can spend their time in developing for californium. 
Therefore I'm not sure, if such "inherited issues"could be cleaned up.

**Comment by martinmine** [comment]
@boaks fair enough. I will go ahead and close this as it seems to be fixed in the master branch and the upcoming release of 2.x.
