### ISSUE TITLE
Option value not set for text/plain

### ISSUE THREAD

**Issue by jvalkeal** [eclipse/californium#440]
On latest snapshots from 2.x(whatever commit eclipse repos have in snapshot build).
If I get options from `CoapExchange` and then log those:
```
List<Option> options = exchange.getRequestOptions().asSortedList();
for (Option option : options) {
  log.info("{} / {} / {} / {}", option.getNumber(), option.getValue(), option.getStringValue(), option.getIntegerValue());
}
```
If with Accept or Content-Format `text/plain` is used, `value` field in Option is empty byte array. With every other media type, value is set.
```
With Accept and Content-Format using text/plain
12 / [] /  / 0
17 / [] /  / 0

With Accept and Content-Format using application/json
12 / [50] / 2 / 50
17 / [50] / 2 / 50
```
It'd be better if value is actually set with `text/plain` as otherwise you need to start doing same tricks as `Option.toValueString()` does by delegating to `Option.getIntegerValue()` in case of Accept or Content-Format which then returns `0` if value byte array is empty.

**Comment by boaks** [comment]
Maybe, you can give `Option.toValueString()` a chance?

**Comment by jvalkeal** [comment]
`Option.toValueString()` doesn't really work that well for option values which are not integers or strings as then it converts to hex string.

**Comment by boaks** [comment]
You asked for `Accept` or `Content-Format`, both should be converted with "toValueString()" into their textual format using "MediaTypeRegistry.toString(getIntegerValue())".

So, which Option you now talking about, which are not Integer nor String?

**Comment by boaks** [comment]
Sorry, I just recognized, that your not talking about your logging output.

But I'm not sure, where you want to "actually set the value with text/plain".

**Comment by jvalkeal** [comment]
I'm just planning to get all options from a request and byte array is its native format. Point was that if client sends `0` with `Accept` or `Content-Format`, options for those should have `0` as value and not empty array. There's few ways to workaround this bug, but I'd prefer to get it fixed. I didn't check why this happens.

**Comment by boaks** [comment]
Maybe you share more, what you exactly doing (e.g. used client, and how the client set the ACCEPT option.) Otherwise you expect someone else to do more work than necessary :-).

**Comment by boaks** [comment]
Maybe you this is caused by RFC7252, section 3.2

> For example, the number 0 is represented with an empty option value (a zero-length sequence of bytes)

According 12.3. "text/plain" is encoded with 0.

So, I'm not sure, if your intention violates those definitions.

**Comment by jvalkeal** [comment]
Ah, bug is in `org.eclipse.californium.core.coap.Option.setIntegerValue(int)`
```
	public void setIntegerValue(int val) {
		int length = 0;
		for (int i=0;i<4;i++)
			if (val >= 1<<(i*8) || val < 0) length++;
			else break;
		value = new byte[length];
		for (int i=0;i<length;i++)
			value[length - i - 1] = (byte) (val >> i*8);
	}
```
If you call that with `setIntegerValue(0)`, first for loop iteration will have `if(0 >= 1 || 0 < 0)`, and as that is false, then it breaks from for loop. `length` is then left to `0` and `value` is set to zero length.

**Comment by boaks** [comment]
> Ah, bug

Did you read my comment https://github.com/eclipse/californium/issues/440#issuecomment-336915604

**Comment by jvalkeal** [comment]
For this I used firefox with coap plugin to set those options for a request.
![ff-coap-2](https://user-images.githubusercontent.com/50398/31621545-e0a7e988-b291-11e7-860c-311d045cc2aa.png)
I did debug that `setIntegerValue` when it was called with that request when I got all options from a request. It was properly called with `0` but not stored because of a reason I wrote ^^^.

**Comment by boaks** [comment]
You seems still refuse, that it is proper implemented according RFC7252, and just your intention is the **bug**.

**Comment by boaks** [comment]
> If you call that with setIntegerValue(0), first for loop iteration will have if(0 >= 1 || 0 < 0), and as that is false, then it breaks from for loop. length is then left to 0 and value is set to zero length.

Exactly as RFC7252, section 3.2 defines it!

https://github.com/eclipse/californium/issues/440#issuecomment-336915604

**Comment by jvalkeal** [comment]
Ah yeah it does say that indeed. Makes perfect sense on a transport layer. I just thought that `Option` itself would have real value in it as `content_format` in `OptionsSet` is set to `0`. So you just decided to represent `0` as empty array as that's what transport assumes. You just never going to know if `Option` value has been set to `0` as that's what it defaults. Kinda reminds me of some database libs where you need to use wrappers to differentiate if some value in a database is empty or null.

It'd be awesome if you could add something to javadocs so that a next guy would also know how these classes behave.

**Comment by boaks** [comment]
null would be indicated by the missing option id in the options list.

Can we close this issue?

**Comment by boaks** [comment]
Javadoc is a good idea. Do you want to make a PR?

**Comment by jvalkeal** [comment]
Yeah, sure I can write something. I now understand that thing better as just realised that you can even have leading zeros in that array. Yeah, closing this.
