### ISSUE TITLE
Can I run "cf-secure" on Android?

### ISSUE THREAD

**Issue by Jimyeol** [eclipse/californium#442]
I want to run "cf-secure example" by running Android local server. Is it possible to change "JKS" to "BKS"?

**Comment by boaks** [comment]
Yes, if you implement it :-).

Note: if you use PSK only, the 

`builder.setPskStore(new StaticPskStore("Client_identity", "secretPSK".getBytes()));`

defines all required credentials and you can just remove the certificate stuff (no key nor trust store is really required for that).

**Comment by boaks** [comment]
```
DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
builder.setPskStore(new StaticPskStore("password", "sesame".getBytes()));
DTLSConnector dtlsConnector = new DTLSConnector(builder.build());

```

For the client, this would be enough to setup the PSK mode.

```
DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
builder.setAddress(new InetSocketAddress(DTLS_PORT));
InMemoryPskStore pskStore = new InMemoryPskStore();
pskStore.setKey("password", "sesame".getBytes());
builder.setPskStore(pskStore);
DTLSConnector dtlsConnector = new DTLSConnector(builder.build());
```

And that for the server.

**Comment by boaks** [comment]
So, did this work for you?

**Comment by Jimyeol** [comment]
No :( 
Server is running. However, client does not receive a response. -> "No Response"

`@Override
    public void onCreate() {
        this.server = new CoapServer();
        server.add(new CoapResource("secure") {
            @Override
            public void handleGET(CoapExchange exchange) {
                exchange.respond(CoAP.ResponseCode.CONTENT, "hello security");
            }
        });

        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setAddress(new InetSocketAddress(DTLS_PORT));
        InMemoryPskStore pskStore = new InMemoryPskStore();
        pskStore.setKey("password", "sesame".getBytes());
        builder.setPskStore(pskStore);
        dtlsConnector = new DTLSConnector(builder.build());

        server.addEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));
        server.start();
    }`

Server


` public void clickGet(View view) {
        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setPskStore(new StaticPskStore("password", "sesame".getBytes()));
        dtlsConnector = new DTLSConnector(builder.build());

        String uri = ((EditText) findViewById(R.id.editUri)).getText().toString();
        new CoapGetTask().execute(uri);
    }`

client

**Comment by boaks** [comment]
Does it work with plain coap: (without encryption)?

And how do you use the dtlsConnector on the client?

**Comment by Jimyeol** [comment]
The server is running. However, the client does not receive a response. "No Response"

Client : 


    public void clickGet(View view) {
        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setPskStore(new StaticPskStore("password", "sesame".getBytes()));
        dtlsConnector = new DTLSConnector(builder.build());

        String uri = ((EditText) findViewById(R.id.editUri)).getText().toString();
        new CoapGetTask().execute(uri);
    }



Server:


    @Override
    public void onCreate() {
        this.server = new CoapServer();
        server.add(new CoapResource("secure") {
            @Override
            public void handleGET(CoapExchange exchange) {
                exchange.respond(CoAP.ResponseCode.CONTENT, "hello security");
            }
        });

        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setAddress(new InetSocketAddress(DTLS_PORT));
        InMemoryPskStore pskStore = new InMemoryPskStore();
        pskStore.setKey("password", "sesame".getBytes());
        builder.setPskStore(pskStore);
        dtlsConnector = new DTLSConnector(builder.build());

        server.addEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));
        server.start();
    }

**Comment by Jimyeol** [comment]
Use "cf-android".

**Comment by boaks** [comment]
OK! 

Add 

`EndpointManager.getEndpointManager().setDefaultEndpoint(dtlsConnector);`

after the  

`dtlsConnector = new DTLSConnector(builder.build());`

If that works, then please move the dtlsConnector setup to onCreate().

I wasn't aware of that code.

**Comment by Jimyeol** [comment]
`EndpointManager.getEndpointManager (). SetDefaultEndpoint (dtlsConnector);`

Add to client?
But there is a problem.
SetDefaultEndpoint in EndpointManager cannot be applied to "dtlsConnector"

**Comment by Jimyeol** [comment]
class CoapGetTask extends AsyncTask<String, String, CoapResponse> {

        protected void onPreExecute() {
            // reset text fields
            ((TextView) findViewById(R.id.textCode)).setText("");
            ((TextView) findViewById(R.id.textCodeName)).setText("Loading...");
            ((TextView) findViewById(R.id.textRtt)).setText("");
            ((TextView) findViewById(R.id.textContent)).setText("");
        }

        protected CoapResponse doInBackground(String... args) {
            CoapClient client = new CoapClient(args[0]);
            EndpointManager.getEndpointManager().setDefaultEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));
            //client.setEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));
            return client.get();
        }

        protected void onPostExecute(CoapResponse response) {
            if (response != null) {
                ((TextView) findViewById(R.id.textCode)).setText(response.getCode().toString());
                ((TextView) findViewById(R.id.textCodeName)).setText(response.getCode().name());
                ((TextView) findViewById(R.id.textRtt)).setText(response.advanced().getRTT() + " ms");
                ((TextView) findViewById(R.id.textContent)).setText(response.getResponseText());
            } else {
                ((TextView) findViewById(R.id.textCodeName)).setText("No response");
            }
        }
    }

**Comment by boaks** [comment]
> SetDefaultEndpoint in EndpointManager cannot be applied to "dtlsConnector"

How did you check that?
Which branch are you using?

**Comment by boaks** [comment]
Uups, sorry, you are rigth, that's for endpoints! And your implementation 

`EndpointManager.getEndpointManager().setDefaultEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));`

looks good. So does this then work?

**Comment by boaks** [comment]
If the first `get` works, that setDefaultEndpint should be also moved to the clients onCreate().

**Comment by Jimyeol** [comment]
![ddd](https://user-images.githubusercontent.com/21171486/32020328-c614a5cc-ba0a-11e7-8a00-1d865c47e575.png)

I did what you said.
still no response....

**Comment by boaks** [comment]
I investigated in that issue using branch 2.0.x:

If executed on a Android 4.4 Tablet (Samsung), the server throws a `CloneNotSupportedException` when creating the cookie to verify the communication  with the peer, see `CookieGenerator.getHMAC()`. Therefore the client will not get a response.

I need to spend more time on that, but I have to confess, this is issue is not of the priority for me. So you may have to be patient.

The client would work with the californium sandbox, but for that you need to change the credentials to:

PSK_IDENTITY: change it from "password" to "cali.<random or MAC in hex>"
PSK_SECRET_KEY: change it from "sesame" to ".fornium".

**Comment by boaks** [comment]
You may check, if #459 works for you.
I also created #460 to support other key store types and different loading mechanisms.
But for cf-android it will still take some time until it get's updated (too much changes, I could not document right now). This may take still longer ...

**Comment by boaks** [comment]
No retest for 1 month, so it seems, that this issue is not longer of high interest.

As far as I tested it with 2.0.x, the issues are solved.
If you still faced issues with android and dtls, ask to reopen this issue or create a new issue.

**Comment by vikram919** [comment]
@Jimyeol 
I have tested cf-secure over android and it works :-), here are some conclusions from what I have learned:
1. For real quick up and running cf-secure I used PSK security mode instead of using RPK with or without certificates.
2. In order to use RPK I used ".p12" (PKCS) file format for storing public, private keys and certificates (For that try to google how to convert .jks file format to .p12 file format)
3. step2 applies to X509 security mode as well.

with above mentioned pull requests there will be no issues, at least for me, as far as I have tested.
Please feel free to reopen this issue if you have problems/issues.

**Comment by boaks** [comment]
@vikram919 

Statement? Question? 
Do you refer to the credential change of the sandbox (californium.eclipse.org) mentioned in:

https://github.com/eclipse/californium/issues/442#issuecomment-339912694

For backwards compatibility, I added in the meantime also the "password" / "sesame" to the sandbox.

If you just want to connect to the "androids localhost coaps-server", just ensure, that they share at least one common identity/password-pair and that this is used.

**Comment by vikram919** [comment]
@boaks 
It is a statement.
BTW, I would like to know. Can I make a pull request for adding DtlsServerService as an example of using "BKS" type KeyStore for cf-Android app.

**Comment by boaks** [comment]
Though using the SslContextUtil supports BKS, it should be easy to setup the android app to use certificate based encryption. If you want to provided a PR to demonstrate, how it works, your welcome. 

Just comply to the ECA (it's your stuff), and our project rules (it should work, source formatting).
