### ISSUE TITLE
cf-helloworld-server limit to ipv4 only

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#444]
Does it exist any reason to limit cf-helloworld-server to ipv4 only ?

(tested on my side with ipv6 address and it seems to works)

**Comment by boaks** [comment]
There have been issues with IPv6 URLs, but I'm not sure, if they still exists.

**Comment by sbernard31** [comment]
I see that. The version 2.0.0-M5 failed because of connector.getURI which does not handle '[ ]' of ipv6 correctly.

I think this is fixed since https://github.com/eclipse/californium/pull/428/files#diff-7fc1ad63c5a71e3b6e336991b107467fR583 (because this constructor handle '[ ]' correctly)

**Comment by boaks** [comment]
OK, remove the IPv4 check and see, what happens :-).

**Comment by sbernard31** [comment]
already done works for me using an ipv6 address

**Comment by sbernard31** [comment]
I remove ipv4 limitation since #447 (integrated in 2.0.x)
