### ISSUE TITLE
Blockwise transfer slow: Each block is only transferred after the previous is acknowledged

### ISSUE THREAD

**Issue by henning77** [eclipse/californium#45]
When analyzing issue #44, I noticed that the client transfers the next block only after the server has acknowledged the previous block. You can see this very clearly in the attached tcpdumps.

This makes block transfers very slow on networks with large delays (e.g. mobile connections).

It this something the spec mandates (I could not find anything)? Otherwise it would be a large performance boost if the client would send blocks without waiting for acknowledgement of previous blocks.

**Comment by mkovatsc** [comment]
CoAP is a stop-and-wait protocol for constrained nodes and networks (i.e., it shall be optimal for microcontrollers and low-power wireless including multihop). Only one open request is allowed at a time (NSTART=1), unless advanced congestion control is implemented (e.g., CoCoA).
