### ISSUE TITLE
InMemoryConnectionStore's sessionEstablished method isn't thread safe and could corrupt the session cache

### ISSUE THREAD

**Issue by lhotari** [eclipse/californium#455]
The method [`org.eclipse.californium.scandium.dtls.InMemoryConnectionStore#sessionEstablished`](https://github.com/eclipse/californium/blob/e788d077f73e4794522910719981351604ac52e3/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/InMemoryConnectionStore.java#L255-L260) should be `synchronized`. The current code can corrupt the `HashMap` used in [`org.eclipse.californium.scandium.dtls.InMemorySessionCache`](https://github.com/eclipse/californium/blob/cd942792ce2d3e534dbefb288e4c35265e5ab9a2/scandium-core/src/test/java/org/eclipse/californium/scandium/dtls/InMemorySessionCache.java#L30). The corruption of HashMap's datastructures [could cause an infinite loop and 100% CPU usage](https://stackoverflow.com/questions/17070184/hashmap-stuck-on-get).

**Comment by boaks** [comment]
```
	@Override
	public void sessionEstablished(final Handshaker handshaker, final DTLSSession establishedSession) throws HandshakeException {
		if (sessionCache != null) {
			// put current connection state to second level cache
			sessionCache.put(establishedSession);
		}
	}
```
So `sessionEstablished` calls `put` of the session cache.

```
	/**
	 * Creates a DTLS connector for a given set of configuration options.
	 * 
	 * @param configuration The configuration options.
	 * @param sessionCache An (optional) cache for <code>DTLSSession</code> objects that can be used for
	 *       persisting and/or sharing of session state among multiple instances of <code>DTLSConnector</code>.
	 *       Whenever a handshake with a client is finished the negotiated session is put to this cache.
	 *       Similarly, whenever a client wants to perform an abbreviated handshake based on an existing session
	 *       the connection store will try to retrieve the session from this cache if it is
	 *       not available from the connection store's in-memory (first-level) cache.
	 * @throws NullPointerException if the configuration is <code>null</code>.
	 */
	public DTLSConnector(final DtlsConnectorConfig configuration, final SessionCache sessionCache) {

```

According the javadoc, the session cache may be shared, so `synchronize` at the `ConnectionStore` may fail either. FMPOV the javadoc for the `SessionCache` should mention the required threadsafe implementation.

The `InMemorySessionCache` is included in the test classes, so it's intention is for testing only. 
But we can implement it there.

**Comment by lhotari** [comment]
@boaks The reason why I suggested adding `synchronized` to the `sessionEstablished` method is that all other methods in `InMemoryConnectionStore` accessing the `sessionCache` are `synchronized`. 
I completely agree that making `InMemorySessionCache` thread safe (which is not the case currently) might also be required.

**Comment by boaks** [comment]
The others are also using the `connections` and therefore they are synchronized.

**Comment by lhotari** [comment]
@boaks yes I get it now. So instead of making `sessionEstablished` synchronized, `org.eclipse.californium.scandium.dtls.InMemorySessionCache` should be made thread safe to fix the issue.

**Comment by lhotari** [comment]
@boaks thanks for the fix. I believe #456 fixes this issue.

**Comment by boaks** [comment]
#456 is merged.
