### ISSUE TITLE
Solving blockwise transfer timeout

### ISSUE THREAD

**Issue by danielhqv** [eclipse/californium#457]
Hi,
I wasn't sure if I should post this here or in the Leshan project, but since there are some common contributors, I'll post it here.

In our current Lwm2m project, we have no choice but to implement firmware update by push, e.g. write to the Package resource of the Firmware update object. As you may suspect we immediately ran into a timeout issue when performing initial tests over the web-GUI of the server demo project.

The info I've found, particularily in this issue https://github.com/eclipse/leshan/issues/302 , indicates that there is work that needs to be done to get this to work. If this is still true, I would like to contribute to this, and solve it in a way that would make good PR's for Leshan and/or Californium.

However, I would really appreciate if I could get some pointers on what is needed.
1) Are the Californium abstractions already designed in a way that supports this?
2) What design considerations are there in Leshan, e.g. do you have any suggestions on how this should be implemented? What classes are involved?

**Comment by boaks** [comment]
Did you calculate, how much time your blockwise write would take?
And did you adjust the request timeout for the leshan-demo (`ClientServlet.TIMEOUT`, currently 5000ms) to that value?

The referred leshan issue propse a change, which would only help, if your blockwise write would work with a proper `ClientServlet.TIMEOUT`.

If that works, then the idea of leshan is, that you not use the demo-server and instead build your own server with the leshan library. Doing so enables you to use a leshan request without a provided timeout (see LeshanServer - 
public <T extends LwM2mResponse> T send(Registration destination, DownlinkRequest<T> request)
or
public <T extends LwM2mResponse> void send(Registration destination, DownlinkRequest<T> request,
            ResponseCallback<T> responseCallback, ErrorCallback errorCallback) ).

If a proper `ClientServlet.TIMEOUT`, doesn't work, I guess, you will need much more investigation, what causes your problem.

**Comment by danielhqv** [comment]
Thx for the quick feedback! A rough estimate is that the transfer may take at least 4-5 minutes out in the field. Because of this, we are investigating if and how it's possible to utilize a timeout on a block level instead of on the request level, since we want an interrupted connection to fail the transfer as quickly as possible.

I've just started looking into this and try to make sense of Californium and Leshan and how they're intertwined. For instance, I've noticed that there is a blockTimeout field in the BlockwiseLayer class, but in Leshan it's corresponding default config value is set to 600000 ms which seems to be a very high value if it's the timeout between individual blocks.

This issue may not belong in this project at all, if that is the case please let me know.

**Comment by boaks** [comment]
So, did it work, if you set the time to that value of 5 minutes?

If yes, we only need to check, if a timeout of a single block request (depending on the ACK_TIMEOUT and MAX_RETRANSMISSIONS) is proper propagated to leshan.

The timeout in the blockwise layer is for cleanup server side cached resources and newly for clients side requests to define a maximum limit when there are collected.

**Comment by boaks** [comment]
To be more complete, the coap timeout depends on the values:

ACK_TIMEOUT
ACK_RANDOM_FACTOR
ACK_TIMEOUT_SCALE
MAX_RETRANSMIT

**Comment by danielhqv** [comment]
OK, thanks, this is exactly the kind of hints I'm looking for. All testing against the real hardware needs to be coordinated with a colleague, so I haven't been able to do that yet. However, I'm also responsible for a Lwm2m client simulator where I will try to simulate a slow connection to get the behavior I need.

**Comment by sbernard31** [comment]
Here some documentations about timeouts in Leshan/Californium (https://github.com/eclipse/leshan/pull/428)

The **block timeout** should be more functional with #449.

**Comment by boaks** [comment]
Do you need more input? Or could we close this issue?

**Comment by danielhqv** [comment]
It's OK to close it, thx!
