### ISSUE TITLE
element-connector >=2.0.0-M2 size & dep too big for constrained CoAP client

### ISSUE THREAD

**Issue by justincranford** [eclipse/californium#463]
Hello,

I am working on a project that used element-connector v2.0.0-M1 in a constrained CoAP client. The 38K size was good for a constrained client. The newest v2.0.0-M5 is now 105KB, and a 3.2MB dependency on netty-all-4.1.1.Final.jar which added in 2.0.0-M2.

- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector
- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector/2.0.0-M1 (38K)
- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector/2.0.0-M2 (59K + 3.2M)
- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector/2.0.0-M3 (74K + 3.2M)
- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector/2.0.0-M4 (105K + 3.2M)
- https://mvnrepository.com/artifact/org.eclipse.californium/element-connector/2.0.0-M5 (105K + 3.2M)

Client size requirement increased ~2 orders magnitude. Furthermore, if-and-when you update to latest netty-all-v4.1.16.Final.jar, that dependency grew from 3.2M to 3.6M. These are not ideal sizes for a constrained client.

- https://mvnrepository.com/artifact/io.netty/netty-all/4.1.1.Final (3.2MB)
- https://mvnrepository.com/artifact/io.netty/netty-all/4.1.16.Final (3.6MB)

Please consider refactoring element-connector to reduce size down to ~35-50KB like in 2.0.0-M1. For example:

1. Optimize code for size.
2. Split into separate modules like Netty, ActiveMQ, Jetty, Groovy, Cassandra, Mockito, etc (See https://mvnrepository.com/search?q=all).

Please consider refactoring netty dependency. For example:

3. Eliminate netty dependency altogether like in 2.0.0-M1.
4. Replace netty dependency with a smaller alternative library.
5. Replace netty-all with individual netty modules (EX: netty-common-4.1.16.Final.jar, netty-buffer-4.1.16.Final.jar, netty-transport-4.1.16.Final.jar, etc)

Thank you,
Justin

**Comment by boaks** [comment]
See issue #119

https://github.com/eclipse/californium/issues/119#issuecomment-321240015
 
And PR #399

https://github.com/eclipse/californium/pull/399#issuecomment-327466032

So, you will need patience ... first PR #294, then #3999

**Comment by sbernard31** [comment]
Since #469 element-connector-tcp has its own project. So if you don't use TCP you will not have the netty dependency anymore.
