### ISSUE TITLE
Observe Relation: Response 4.06, going to onLoad of CoapHandler

### ISSUE THREAD

**Issue by charybr** [eclipse/californium#465]
Hi,

We noticed that when 4.06 response comes from server for a get-observe request, control goes to onLoad. As a result, CoapHandler doesnt get notified about observe being deleted.

Log attached.

[californium.0.0.log.zip](https://github.com/eclipse/californium/files/1441450/californium.0.0.log.zip)

From logs:
Registering obs 
Nov 03, 2017 6:54:58 PM org.eclipse.californium.core.network.BaseMatcher registerObserve
FINER: registering observe request CON-GET    MID=16232, Token=cfb4e4573c35ff28, OptionSet={"Uri-Host":"8eb76988-7264-4a2d-beca-8169df875083", "Observe":0, "Uri-Path":"weighsens"}, no payload

Got 4.06 response from server.
Nov 03, 2017 6:55:00 PM org.eclipse.californium.core.network.UdpMatcher receiveResponse
FINER: received response ACK-4.06   MID=16232, Token=cfb4e4573c35ff28, OptionSet={"Content-Format":"application/cbor"}, no payload

One more 4.06 response from server.
Nov 03, 2017 6:55:02 PM org.eclipse.californium.core.network.UdpMatcher receiveResponse
FINER: received response ACK-4.06   MID=16232, Token=cfb4e4573c35ff28, OptionSet={"Content-Format":"application/cbor"}, no payload

Removed the observation
Nov 03, 2017 6:55:02 PM org.eclipse.californium.core.network.BaseMatcher$2 onResponse
FINE: Response to observe request with token KeyToken[cfb4e4573c35ff28, fd0080000000000000000000000200af:5683] does not contain observe option, removing request from observation store
Nov 03, 2017 6:55:02 PM org.eclipse.californium.core.observe.InMemoryObservationStore remove
FINER: removed observation for token cfb4e4573c35ff28

This response went to onLoad() of CoapHandler with CoapResponse.advanced().getCode() as 4.06. My query is, should it go to onError() instead of onLoad() ?
Or in onLoad(), should we check for response code 4.06 and take some action?

Best Regards,
Chary

**Comment by boaks** [comment]
Please check PR #467

**Comment by charybr** [comment]
Hi Achim,

Thanks!
I tested the fix. I couldnt see any difference in behavior when response is 4.06 i.e it went to onLoad().

Please clarify, if i missed something.

**Comment by boaks** [comment]
Sorry, I just didn't read your issue careful enough :-).

onError() would be called, if the request failed, but receiving a response goes to onLoad(), even if the response contains an error code as 4.06.

**Comment by charybr** [comment]
Thanks! 
Then do you suggest  we check for response code 4.06 (anything other 2.xx) and take some action in onLoad() ?

**Comment by sophokles73** [comment]
Yes

**Comment by charybr** [comment]
Thanks very much!
