### ISSUE TITLE
Make LockstepEndpoint reusable

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#471]
I would like to reuse LockstepEndpoint.

But it is in tests packages, so this is not feasible without californium modification.

The 2 solutions I found to be able to reuse it in a mvn project: 
- modify pom to create a test.jar ([see sufire guide](https://maven.apache.org/guides/mini/guide-attached-tests.html))
- move LockstepEndpoint in a "non-test" package. (could make sense as it's a really good API)

waiting a better solution I duplicate it in my project.

**Comment by sbernard31** [comment]
`SimpleMessageCallback` from element-connector is great too :)

**Comment by boaks** [comment]
The current 2.0.x SNAPSHOT already creates that test-jar.
If you import it with the "conditional test profile" approach, even eclipse builds with "skip tests" will work :-).
Or did I miss something?

**Comment by sbernard31** [comment]
I tested with 2.0.0-M4.
With 2.0.0-SNAPSHOT, it sounds to work with test.jar. The question is : "will this jar be released on maven central ?". We will see. If this is not available for the 2.0.0-M6 this is not a big deal.
