### ISSUE TITLE
 bks and jks communication problems

### ISSUE THREAD

**Issue by 2YoungHoon** [eclipse/californium#482]
Hello. 

I use 'DTLS' to implement communication between Android and Raspberry server.
But it is not doing well. :(
I think this problem is due to the certificate. 
Android - 'bks', Raspberry pie server - 'jks'  Is it possible to communicate with ?

**Comment by sophokles73** [comment]
I do not know what `bks` is supposed to mean. Can you elaborate?
Also, `JKS` does not refer to a certificate type but to a certain type of *certificate store* which contains the certificate(s) used. What types of certificates are you trying to use for securing the communication? Are you only trying to authenticate the server by means of a certificate or do you also wan to authenticate the client using a certificate? Are you using Californium on both client (Android) and server (Raspi)?

**Comment by 2YoungHoon** [comment]
First, I apologize for my lack of questions and knowledge.

What I want to do is apply dtls security between server (rassberry pi3) and client (android) communication.

So both server and client communicate using the cf-secure example provided by Californium.

I ran SecureServer on rassberry pi3 and ran SecureClient on eclipse and it worked fine.

However, on Android, we found that we needed to apply 'bks' instead of 'jks' to run the client.

I keep trying, but the certificate is not referenced. 

So I want your advice on this matter.

**Comment by sophokles73** [comment]
Ok, so it looks like Android doesn't support the SUN provider's default *JKS* key store format.
Californium, on the other hand, *only* supports JKS for the time being. So, sadly, you won't be able to use certificate based authentication running a Cf client on Android for now. However, this does not prevent you from establishing a secure DTLS connection. It just means that you need to use a non-certificate based cipher suite, e.g. PSK_AES_128 which uses a *shared key* for mutual authentication.

**Comment by boaks** [comment]
Maybe you try to read issue #442 and have a look at PR #460 

So:
1. for DTLS you can use a easier setup with PSK, so no keystore required. (See #442)
2. if you want/need to use x.509 you may use the `SslContextUtil`. (See #460)

Currently, only the 2.0.x branch is checked to run on android.  And at least I have no plan to check the other branches :-).

**Comment by vikram919** [comment]
Please read my comment, I have used 2.0.0-SNAPSHOT for using cf-secure over android

https://github.com/eclipse/californium/issues/442#issuecomment-347839255

**Comment by 2YoungHoon** [comment]
Thank you for your advice! :)
I used version scandium:2.0.0-M5. However, I get a compile error in Eclipse.

Server:

    public static void main(String[] args) {

        CoapServer server = new CoapServer();
        server.add(new CoapResource("secure") {
            @Override
            public void handleGET(CoapExchange exchange) {
                exchange.respond(ResponseCode.CONTENT, "hello security");
            }
        });
        
        DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
        builder.setAddress(new InetSocketAddress(DTLS_PORT));
        InMemoryPskStore pskStore = new InMemoryPskStore();
        pskStore.setKey("password", "sesame".getBytes());
        builder.setPskStore(pskStore);
        DTLSConnector dtlsConnector = new DTLSConnector(builder.build());

        server.addEndpoint(new CoapEndpoint(dtlsConnector, NetworkConfig.getStandard()));
        server.start();


        // add special interceptor for message traces
        for (Endpoint ep : server.getEndpoints()) {
            ep.addInterceptor(new MessageTracer());
        }

        System.out.println("Secure CoAP server powered by Scandium (Sc) is listening on port " + DTLS_PORT);
    }


What is the problem?

**Comment by boaks** [comment]
> I used version scandium:2.0.0-M5. 

I don't think, this contains the android fixes. Currently use 2.0.x-SNAPSHOT or wait for M6.

> However, I get a compile error in Eclipse.

It makes it a lot easier, if you provide that errors!
Or do you just mean red crosses in eclipse?
If so, try to run the "mvn clean install" in eclipse 
(select "parent" project, menu "run as ...", "maven build...", add "clean install" as goals, save and run. )
and then update the maven project in eclipse
(select "parent" project, menu "maven", "update project...",  press "OK" and wait ... )

**Comment by 2YoungHoon** [comment]
The following compilation error occurs after adding the library.

I think there is a problem with applying the library.
But I can`t sure.

-------------------------------------------------------------------------------------

Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/californium/elements/CorrelationMismatchException
	at org.eclipse.californium.examples.SecureServer.main(SecureServer.java:81)
Caused by: java.lang.ClassNotFoundException: org.eclipse.californium.elements.CorrelationMismatchException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by vikram919** [comment]
@2YoungHoon 
More information required on which library from the above mentioned maven releases.
Please use M6 or 2.0.x-SNAPSHOT.

**Comment by boaks** [comment]
> java.lang.ClassNotFoundException: org.eclipse.californium.elements.CorrelationMismatchException

But in 2.0.0-M5 there is such a `CorrelationMismatchException`, so the error indicates, that your build tools are missconfigured or misused/wrong used!
I would recommend, you read some tutorials for maven and maven in eclipse IDE usage.

**Comment by boaks** [comment]
With PR #496 (2.0.0-SNAPSHOT) now the demo certificates are also contained in PKCS12 (.p12) format. So together with the `SslContextUtil`, it should work now.

**Comment by 2YoungHoon** [comment]
Thank you for your help. I solved my curiosity.
