### ISSUE TITLE
Lack of buffer re-use leads to extensive GC and performance degradation

### ISSUE THREAD

**Issue by martinmine** [eclipse/californium#483]
When processing incoming requests in Californium, the framework copies the contents of the message buffer multiple times before it is actually serialized. To give a clear example, the class RawData has a method getBytes(), which will return a copy of the byte array representing the "raw bytes" that should be processed. This extensive use of buffer allocation is also used for sending messages. This impacts the performance under high throughput as the rapid allocation and de-allocation of the message buffers cause extensive garbage that the garbage collector will have to deal with. This can be seen in a profiler such as JVisualVM under memory usage:
![Memory usage](https://i.imgur.com/byWkX3v.png)
This is from a benchmark setup, similar to the one I used in PR #479.
Investigating a heap dump shows that the byte[] takes up most space of the heap:
![Heap dump](https://i.imgur.com/O9JgmZZ.png)

This is a pretty big problem for performance, and avoiding buffer copying and large frequent memory allocations through e.g. buffer pools is what makes other frameworks such as Netty shine on performance, and is something I think would make Californium much more resource efficient.

**Comment by boaks** [comment]
My personal current concern about CoAP is not the performance.
Currently we try more to find the "pitfalls" using it.
There very different environment, e.g.

- Intranet, not hostile, fully controlled addresses, where you can use plain CoAP even with MultiCast and use the address for "long term identities", at least as long as you can control those addresses. 
- Internet, hostile, uncontrollable, full of NATs changing you addresses, requires to use DTLS, can't rely on addresses as identity.

Though the "most" committers are working on using CoAP in the internet, they are focus on that usability. On my view, there are issues left for that environment, so I'm not able to spend my time in optimization for now. ;-(. Sorry for that.

**Comment by martinmine** [comment]
@boaks I am ok that performance is not one of the main goals of Californium. I was not expecting anyone to pick up this issue and work on it in the short term. There are two reasons I'm making it, first is to make other people aware that this is an actual problem, the other is to encourage new developments to not write code that extensively copies buffers when this is not needed.

**Comment by boaks** [comment]
@martinmine 
If you want to improve the GC-based performance, have a look at `CCMBlockCipher`. FMPOV there is a lot of potential to save plenties of `new byte[]`. And it could be optimized locally without affecting too much else. 
So, maybe, if you can and want to spend time into this (when ever), your contribution will be welcome :-).

The other `new byte[]` hotspot seems to be the Option class, but I guess, this is not that obvious and would require a redesign of the Option class.

**Comment by boaks** [comment]
@martinmine 

we changed a lot, maybe you can retest the GC usage again.
