### ISSUE TITLE
Add a TrustedCertificateStore like PskStore and TrustedRpkStore

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#484]

**Comment by sbernard31** [comment]
@rkimsb2 I begin to implement this in #533 but we are not totally sure about its usefulness.
I see you +1 this issue, could you explain your use case or why you think this is a good idea ?

**Comment by rkimsb2** [comment]
When client bootstrapping from bootstrap server, there's possibility to change security policy of dtls. If it happened, secured endpoint also have to update it. For now, the way of doing this is only reboot secured endpoint. But rebooting endpoint is some danger for unable to response, and lost messages on UDPConnector's message queue.

**Comment by boaks** [comment]
Does PR #602 solve this issue?

**Comment by sbernard31** [comment]
I think it does.

**Comment by rkimsb2** [comment]
And the point of the comment  i wrote in 26 Jan was changing endpoint's certificate of it's 'own'. It has quite different meaning with this issue.

**Comment by sbernard31** [comment]
So you are more interested by something like #536.
We can close thie one.
