### ISSUE TITLE
Adding BLE transport to Californium?

### ISSUE THREAD

**Issue by bgiori** [eclipse/californium#485]
Hi, I'm looking for a Java CoAP library which can handle non-IP transports, in this case Bluetooth Low Energy (BLE).

My question is, If I were to write a custom connector for BLE using the Bluetooth hardware address (format XX:XX:XX:XX:XX:XX) as the address with port 0, would any of the core source need to be modified? That is, can the core handle non-IP addresses? Additionally, would I also have to add BLE specific subclasses to core (e.g. CoapBleStack).

Thanks,
Brian

**Comment by boaks** [comment]
I'm not sure, what you really intend to do. BLE with GATT or BLE with IPSS?

With IPSS, your bluetooth address is already mapped to a IPv6 address, so there is no need for a non-IP address.

With GATT, I'm not sure, how you want to exchange the CoAP messages. Is you intention to emulate a "COM"? If so, the easiest way to use californium would be to map your bluetooth address into a IPv6 (or IPv4) address. Californium uses `InetSocketAddress` very frequently, so I would not recommend to modify californium-core.

**Comment by bgiori** [comment]
Thanks for your quick response! 

Yes, I should have clarified I was planning on using GATT, where the peripheral would expose a GATT service with two characteristics, one request and one response. The CoAP requests would be "written" by the central (In this case an Android) to the peripheral's request characteristic and responses would be "notified" on the response characteristic. 

I was previously using [Iotivity](https://github.com/iotivity/iotivity), but the size and scope of the project makes it inflexible. 

I'll look into mapping a bluetooth address into an IP address. 

Thanks again!
