### ISSUE TITLE
Why get peerAddress from session frist not from Record Object ?

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#486]
In class Record, Why first get peerAddress from session not from Record Object ?

When receive udp message, we always can get peerAddress from  packet.
InetSocketAddress peerAddress = new InetSocketAddress(packet.getAddress(), packet.getPort());
 
	public InetSocketAddress getPeerAddress() {
		if (session != null) {
			return session.getPeer();
		} else if (peerAddress != null) {
			return peerAddress;
		} else {
			throw new IllegalStateException("Record does not have a peer address");
		}
	}

**Comment by boaks** [comment]
Check the `Record` constructors.
There is one with the `DTLSSession` and one with the `InetSocketAddress`.
The one with `DTLSSession` is sometime "internally" used, where we want to send something, but we have the session rather then the address.

**Comment by boaks** [comment]
@xuzhiweiand 
Do you still think, using the "peer address always from the packet" is better?
If not, can we close this issue?
