### ISSUE TITLE
Concurrent requests to the server return "null" response

### ISSUE THREAD

**Issue by LiPingjiang** [eclipse/californium#49]
In my scenario, there is one android server and several clients(all clients are simulated by a PC, using Threads). The clients will connect to the server and send data arbitrarily. This may lead to concurrency. Each client has a unique ID and send data to the resource named by its ID. So no clients will share resource( otherwise I found it shows "Wrong block number. Expected xxx but received xxx"). But the problem is that if there are more than 15 clients send requests together, most of them will get "null" response. The android server still have enough CPU and Memory. And the CoAP is a really light-weight protocol, so I wonder whether it because I misused the framework so the efficiency is so low.

**Comment by sophokles73** [comment]
Hi @LiPingjiang,

is this still an issue for you? If yes, what version are you using?

**Comment by boaks** [comment]
I'm not sure, what your exact setup looks like.
Please, try to use 2.0.0-M12, and if possible, provide your source. or a more precise description.
