### ISSUE TITLE
Is there a way to update Key while DTLS connector is running ? 

### ISSUE THREAD

**Issue by ClemChe** [eclipse/californium#492]
Hi,

Currently when i have new key to store in my InMemoryPskStore, i have to restart my DTLS connector.
I think it's not the best way to do it because when the connector is restarting i can have several thousand handshakes at the same time.

Do you know a way to update key stored while the connector is running ?

**Comment by sophokles73** [comment]
You can create your own (custom) `KeyStore` implementation that supports dynamic lookup of keys e.g. from a file system location or database.

**Comment by ClemChe** [comment]
Thanks for your answer. 
I already got my KeyStore but i don't know how to tell to the DTLS Connector that he has to use new keys.  My KeyStore is sent to the DTLS with a Builder (from DTLSConnectorConfig), so new keys need to be sent with a builder too ? Or just update keys in my KeyStore is enough ?

**Comment by boaks** [comment]
> I already got my KeyStore but i don't know how to tell to the DTLS Connector that he has to use new keys.

Your using a "static KeyStore" implementation and therefore you want to exchange it.
But that's just the "wrong approach", if you want to exchange the credential dynamically.

> to tell to the DTLS Connector

that's the wrong direction! The DTLS connector calls your `PskStore` and tells your `PskStore`, what the connector wants. So, if your want to exchange the credentials, then implement your own `PskStore`, which implements the methods using your dynamic way of store certificates.

`InMemoryPskStore` may be such a implementation. There you change the credentials within the store, and so you don't need to replace the store used by the connector.

**Comment by ClemChe** [comment]
My bad, i told  `KeyStore` but i already use `InMemoryPskStore`.
So if i understand well, i just have to update keys in my  `InMemoryPskStore` and DTLS connector can access to new keys ?

**Comment by boaks** [comment]
Yes, the only pitfall would be the methods used either by the DTLS client or by the DTLS server.

Handshake starts at the client with `getIdentity(final InetSocketAddress inetAddress)` and then use `getKey(final String identity)` (see `ClientHandshaker.receivedServerHelloDone`). 

The server side use `getKey(final String identity)` or `getKey(final ServerNames serverNames, final String identity)` (see `ServerHandshaker.receivedClientKeyExchange`).

**Comment by ClemChe** [comment]
Thank you very much for your help ! 

I'll close this issue.
