### ISSUE TITLE
Commit of 2.0.0-M6 release is no more in 2.0.x branch

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#494]
I just remark that : 
- commit https://github.com/eclipse/californium/commit/42c76e1e98aba7a9f19addf8ecb100f279fab2f6 and [tag 2.0.0-M6](https://github.com/eclipse/californium/commits/2.0.0-M6) are no more in branch [2.0.x](https://github.com/eclipse/californium/commits/2.0.x).

Is it intended ?

**Comment by boaks** [comment]
I guess, this is a result of migration from hudson to jenkins.

**Comment by boaks** [comment]
Until that, all "releases" have two commits, one with the release-version and afterwards with the snapshot. this time, the second one seems to be missing.

**Comment by boaks** [comment]
OK, so I hope, I did not "forced" my push with commit eeafab335.
But if so, I would create the second "Release ..." commit now on my machine, push it "forced" to 2.0.x and then reapply my changed javadoc.

Not nice, I agree. Afterwards, we release M7, and then we can check, if it works (and it was a wrong push), or if it doesn't work.

**Comment by boaks** [comment]
So, I'm ready to force push the second "Release 2.0.0-M6" commit, which reset to 2.0.0-SNAPSHOT. We will see with M7, if it's my mistake or a build issue.

**Comment by sbernard31** [comment]
sounds good.

**Comment by boaks** [comment]
+ git add pom.xml '*/pom.xml'
+ git commit -m 'Release 2.0.0-M5'
[2.0.x 551ce40] Release 2.0.0-M5

+ git add pom.xml '*/pom.xml'
+ git commit -m 'Release 2.0.0-M6'
[detached HEAD 42c76e1] Release 2.0.0-M6

`detached` instead of `2.0.x`
So I guess, we have to check the jenkins job.

**Comment by boaks** [comment]
I added the the "additional behaviour" "checkout to specific local branch" and tested it with "parent-release-test".

Without the "stale tag" occurs, with the "checkout", the two commits are pushed to the branch. 
Should we close it or wait for the M7 and then close it on "success"?

**Comment by sbernard31** [comment]
We can close it. If problems reoccurred we will reopen it. But I feel its ok now.

**Comment by sbernard31** [comment]
It seems we still have an issue about this.
Tag 2.0.0-M7  is not on the 2.0.0-x branch.

**Comment by boaks** [comment]
I would guess not “still”, just “again” after changing the Jenkins job again …

[workspace] $ /bin/sh -xe /tmp/jenkins6403104951849384766.sh
+ git add pom.xml '*/pom.xml'
+ git commit -m 'Release 2.0.0-M7'
[detached HEAD d6d0112] Release 2.0.0-M7
 26 files changed, 26 insertions(+), 26 deletions(-)
+ git tag 2.0.0-M7

**Comment by boaks** [comment]
I added the fix again. I will start it again but without push to the repos.
Then do some of the fixes and retest with 2.0.0-M8

**Comment by boaks** [comment]
2.0.0-M8 seems to work. SO, if nobody is changing the jenkins jobs again, it should work.
