### ISSUE TITLE
ConcurrentModificationException on coapEndpoint.interceptors

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#50]
An issue was open on leshan about a `ConcurrentModificationException` on `coapEndpoint.interceptors`
See [here](https://github.com/eclipse/leshan/issues/134) for more details.

I think using `CopyOnWriteArrayList` could make sense. What about you ?
(We can use a `CopyOnWriteArrayList` for `observers` too)

**Comment by sophokles73** [comment]
I do not see why we would want to allow dynamic *re-configuration* of an `Endpoint` during runtime. I therefore would rather throw an `IllegalStateException` if client code tries to add or remove an interceptor when the endpoint is already started.

**Comment by sophokles73** [comment]
Fixed on master in dd0e9cdb65a50c5375f38aa113ed097f23ff0e8c
fixed on 2.0.x in 832c896b3fbbd04aa35ec82f7dec9d85238fa31b
