### ISSUE TITLE
Californium message loss control

### ISSUE THREAD

**Issue by JurisPuchin** [eclipse/californium#505]
Hi, I am trying to figure out the intended behavior of Californium in terms of QOS.

That is, are messages guaranteed to go through by default, or is there a setting the need to be set to prevent loss of messages?

I am seeing that under stress (lots of messages being sent, or large messages being sent), COAP messages don't always make it to the other side. Do I need to manually create AKS if I want to ensure transmission? Or are the recommended messages sizes/transmission rates/settings under which Californium transmits messages without loss? I am looking for loss rates of less than 1%, ideally.

**Comment by boaks** [comment]
The most answers should be in RFC7252, chapter 4.

There maybe also some external factors, maybe your network infrastructure drops UDP on the firewall/NAT, if it exceeds a limit.

**Comment by boaks** [comment]
Hope you could get familiar with 

https://tools.ietf.org/html/rfc7252#section-4

If you still have issues, please provide detailed information about that.
If it works for you, please close this issue.

**Comment by boaks** [comment]
As documented here:

https://github.com/eclipse/californium/issues/52#issuecomment-357719189

the message loss using localhost is very low at 0,12%.

> retransmissions (0,12%)

The test sends CON request from 500 clients obeying NSTART-1 (see https://tools.ietf.org/html/rfc7252#section-4.7) implemented with sending the next request when receiving the response in `CoapHandler.onLoad`.

So FMPOV there is no general issue with message loss. 
If you use a special setup, I can't help you without knowing your details.
