### ISSUE TITLE
I immediately reply ACK, and immediately report the data, can not correctly handle the reported data

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#507]
# Please providing basic issue information

I meet a scene, when my client received a observe subscription, I immediately reply ACK, and immediately report the data.
This time the server can not correctly handle the reported data, because in matcher class "exchange == null" request will addMessageObserver and then trigger into the reported data。

how can we deal this problem?

And I find the method receiveResponse(final Exchange exchange, final Response response)  in ReliabilityLayer.java
exchange.getCurrentRequest().setAcknowledged(true);

why not judge the mid is equal ? like this if(exchange.getCurrentRequest().getMID() == response.getMID())

**Comment by boaks** [comment]
If I press "New issue", I get, 

> # Please providing basic issue information
> 
> Issues may be answered much faster, if you provide more details ahead!
> 
> * branch your faced the issue. Currently 
>    * 1.0 is the release, 
>    * 1.1 is the master, 
>    * and 2.0 is the development branch
> * If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
>   commit your using
> * If your issue is related to your own snippet, please provide that
> * If you have logs, please provide them
> * If you have tcpdump captures (wireshark), please provide them.
> 

I'm not sure, why it's impossible to provide this information.

**Comment by boaks** [comment]
Do you intend to provide the required information or is it OK to close this issue?

**Comment by boaks** [comment]
If you still feel, there is a issue, provide information in a new issue.
