### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by bgiori** [eclipse/californium#512]
Hi, sorry if this isn't the place to ask this, but I just wanted to clarify that Californium and the elements package can be used with the EDL and not the EPL (i.e. without distributing the source).

LICENSE.txt states:
 "This program and the accompanying materials are made available under the terms of the Eclipse Distribution License 1.0, which is available at
https://www.eclipse.org/org/documents/edl-v10.php
**_OR_** the Eclipse Public License 1.0, which is available at 
https://www.eclipse.org/org/documents/epl-v10.php"

While the file header license states: 
This program and the accompanying materials are made available under the terms of the Eclipse Public License v1.0 **_AND_** Eclipse Distribution License v1.0 which accompany this distribution.

I'm no lawyer, but the distinction between "**and**" and "**or**" here seems important since the EDL is much less restrictive. 

Thanks,
Brian

**Comment by sbernard31** [comment]
Eclipse say thats dual licensing means : 
_"The code is being made available under both of the licenses. The consumer of the code can select which license terms they wish to use, modify and/or further distribute the code under."_
(Source : https://www.eclipse.org/legal/eplfaq.php#DUALLIC)

**Comment by bgiori** [comment]
Thanks!
