### ISSUE TITLE
demo-app android example is not working

### ISSUE THREAD

**Issue by wallpie09** [eclipse/californium#514]
Each time I try to get localhost using the local server I get the same response, The function handleGET in the server example does not even get called rather another function in CoapServer.java with tha same name handleGET is called which also overrides the main CoapResource class. Can anyone help me with this.

**Comment by wallpie09** [comment]
@sophokles73  @scop @kartben @prafulbhatnagar can you please help me with this. I am a n00b.

**Comment by vikram919** [comment]
@wallpie09 

> Each time I try to get localhost using the local server I get the same response, The function handleGET in the server example does not even get called rather another function in CoapServer.java with tha same name handleGET is called which also overrides the main CoapResource class

Did you check the url,  you use while sending a get request to the server? 
if it is coap://localhost:568 it does only call super class method.
In order get the reponse from you override handleGET method you should probably define resource path in the url (ex: coap://localhost:5683/localResource).

If you have any problems further, please tell me which brach you are using 2.0.x has the latest commits and changes.

**Comment by vikram919** [comment]
@wallpie09 
Do you still have problems ?

**Comment by boaks** [comment]
@wallpie09
If it works now, can you please close this issue?
