### ISSUE TITLE
Does Scandium DTLS works only with ECDHE-ECDSA and preshared keys?

### ISSUE THREAD

**Issue by katkol** [eclipse/californium#517]
Does the Scandium works only with ECDHE-ECDSA and preshared keys? I tried to work with RSA certificates and it says 
java.lang.IllegalStateException: Keys must be ECDSA capable when support for an ECDHE_ECDSA based cipher suite is configured
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.verifyEcBasedCipherConfig(DtlsConnectorConfig.java:976)
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:952)
but, I didn't configure any cipersuite in the code, when I look at the DtlsConnectorConfig.java, it says

for (CipherSuite suite : config.supportedCipherSuites) {
				switch (suite) {
				case TLS_PSK_WITH_AES_128_CCM_8:
				case TLS_PSK_WITH_AES_128_CBC_SHA256:
					verifyPskBasedCipherConfig();
					break;
				case TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8:
				case TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:
					verifyEcBasedCipherConfig();
					break;
				default:
					break;
				}
			}
where I didn't find one suitable for RSA. 
Please help me understand what went worng with my implementation

**Comment by boaks** [comment]
RSA is not supported and I don't see the plan to support it.
Why is ECDHE-ECDSA not proper for your case?

**Comment by katkol** [comment]
Thank you for the information.

Yes, I already had a working implementation with ECDHE-ECDSA. we are working on a research project and would like to get CoAP working with RSA too. Thats fine. No isssues.

**Comment by AlexITC** [comment]
my understanding is that CoAP specifies that the keys should be ECDHE-ECDSA, one thing that you could do is to integrate the `TLSServerConnector` from californium and you will have plenty of cipher suites (like RSA) to use.

**Comment by boaks** [comment]
https://tools.ietf.org/html/rfc7252#section-9.1.3.2

> MUST support the mandatory-to-implement cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8

The ECDHE_ECDSA is mandatory, the RSA-variants not. But I don't see the benefit in using RSA based cipher suites, except to make a test, which then shows, that ECC certificates are smaller and faster calculated then RSA based ones :-).

**Comment by katkol** [comment]
Hi,

Yes, it is already shown that ECC is smaller in key size than RSA. The project I am working is a framework for interoperable IoT devices and we would like to make sure the CoAP implementation of it handles any type of certificates. 

@AlexITC, I didn't get your solution about getting RSA to work, could you please help me understand it more clearly.

**Comment by AlexITC** [comment]
if your device is able to use TCP, you can integrate TCP with Leshan, getting TLS available with a bigger set of supported cipher suites. This is not supported by default in Leshan, we forked the repository and added some updates to be able to use TCP (https://github.com/artikcloud/leshan/tree/artik).

You can set the californium `TLSServerConnector` for the secure endpoint and set a RSA key in the client which the server should now support.

**Comment by boaks** [comment]
Though californium supports the **MANDATORY** ciper suites according RFC7252 (CoAP), any CoAP RFC 7252 compliant device should be able to communicate using DTLS. If it doesn't support the TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 cipher suite, the device is not compliant to RFC7252 :-). 
So I still don't see the benefit of supporting a RSA based cipher suite.

**Comment by AlexITC** [comment]
I don't see the benefit either but it's possible, also I think that we had issues to support `TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8` cipher suite and ended up using BouncyCastle TLS library to support it.

**Comment by katkol** [comment]
Hi, 
@boaks Thanks for your reply. It makes out that ECDHE-ECDSA is mandatory and also efficient than RSA. Maybe it's not worth to get RSA working in this scenario.

**Comment by pedromassango** [comment]
How do I generate ECDSA keys? I'm using [__Portecle__](http://portecle.sourceforge.net/) to generate my `.p12` keystore and there is no option to specify the key type

**Comment by boaks** [comment]
Californium uses the java `keytool` for that. 
We [generate key pairs](https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/create-keystores.sh#L64), then [export Certificate Signing Request](https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/create-keystores.sh#L66), [sign that with a CA](https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/create-keystores.sh#L67), and [import the signed certificate](https://github.com/eclipse/californium/blob/master/demo-certs/src/main/resources/create-keystores.sh#L68) again.
Generally, mixed certificate chains maybe possible (depending on JCA), but the ECDSA cipher suite will require we a ECDSA certificate for the peer itself, it may only be signed by a different signing algorithm (e.g. RSA). Just to mention, Android sometimes differs slightly from other JCA(e.g. "SHA256WITHECDSA" and "SHA256withECDSA"). If you are faced some troubles, don't hestitate to open a new issue. Don't forget logs and/or your Android versions.

**Comment by pedromassango** [comment]
Thank you. I was able to discover the proccess by looking in the script that you used to generate some examples of certificates (in deomo-certs)
