### ISSUE TITLE
Q: is it possible for TLS_PSK_WITH_AES_128_GCM_SHA256 implementation to be merged?

### ISSUE THREAD

**Issue by eugene-nikolaev** [eclipse/californium#525]
Hello!
I am just considering (not yet planning) an option of using GCM mode for DTLS.
Could you please answer, is it possible that such implementation (e.g. TLS_PSK_WITH_AES_128_GCM_SHA256 ) will be merged into Scandium?
Sure I am not afraid to get my hands dirty - it would be my PR.
Thanks.

**Comment by boaks** [comment]
Generally yes, but please ensure, you read

https://www.eclipse.org/legal/EclipseLegalProcessPoster.pdf

**Comment by eugene-nikolaev** [comment]
Is it because of cryptography? I’ve committed to Californium as well and it were just git PRs and then they were just merged.

**Comment by boaks** [comment]
Yes, FMPOV, if encryption is involved, a CQ is required.
Perhaps someone has more experience and knows it better ...

**Comment by eugene-nikolaev** [comment]
Thanks a lot!

**Comment by sbernard31** [comment]
The cartoons one : https://www.eclipse.org/projects/dev_process/ip-process-in-cartoons.php

**Comment by boaks** [comment]
One additional wish:
Currently we support java 1.7. so it would be cool, if it works with that :-).

**Comment by eugene-nikolaev** [comment]
Thanks for replies @boaks and @sbernard31!
My question is answered.
For now, it isn't completely decided what mode will be used.
We are also considering using the old good CCM_8 :)

**Comment by boaks** [comment]
Just to say, if the motivation for doing so is the DTLS performance, I would prefer to have the `CCMBlockCipher` optimized :-).
 
https://github.com/eclipse/californium/issues/483#issuecomment-357505915

**Comment by eugene-nikolaev** [comment]
No, it is because of the other side (embedded device).

**Comment by boaks** [comment]
OK :-)
Reopen it, if it's decided to go for GCM.

**Comment by eugene-nikolaev** [comment]
Thanks for attention, @boaks!

**Comment by boaks** [comment]
Just a update:
The wip branch https://github.com/eclipse/californium/tree/wip_add_dtls_cid contains the first AES_GCM (TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)), for java 1.8 and newer. With that, the PSK variant should not be a too big issue. I hope it will be merged within a couple of weeks.
