### ISSUE TITLE
DTLS Handshake Failure with 'Unsupported Certificate'

### ISSUE THREAD

**Issue by hannestschofenig** [eclipse/californium#53]
I recently tried to connect our mbed client to a local version of Leshan and noticed a problem, which I believe may be caused by a bug in the DTLS californium stack. 

Here is the setup:

* Mbed client (with mbed TLS) supporting PSK and certificate-based authentication (but not raw public keys). 
* The Leshan server (with californium) supports raw public keys and PSK-based authentication (but not certificates). I am using version 0.1.11-M10-Snapshot of the Leshan-demo-server.

At the DTLS handshake one would expect that the client and the server agree on the use of a PSK-based ciphersuite but in this specific case they didn’t. 

Instead the handshake fails with an alert saying ‘Unsupported Certificate’. 

I believe this error is caused by an incorrect handling of the ciphersuite selection. If the server only  possesses raw public keys and the client does not offer the extensions defined in RFC 7250 then the server should not even try to use certificates. 

If I configure the mbed client to only offer a PSK-based ciphersuite (and no certificate-based ciphersuites) then the exchange is successful. 

A packet trace of the exchange is available at [packet-trace.txt](https://github.com/eclipse/californium/files/291656/packet-trace.txt)

**Comment by sophokles73** [comment]
Should be fixed in c603fdb.

Can you give it a try, @hannestschofenig, and close the issue if this solves it for you?

**Comment by sophokles73** [comment]
Please re-open if this is still an issue.
