### ISSUE TITLE
Certificates are not valid anymore

### ISSUE THREAD

**Issue by JanZimmer** [eclipse/californium#54]
Hey,

today I tried to install californium. However, I had problems reagrding the Tests which are executed regarding scandium. I had to reset my Date and tiime to somewhere in June 2015 to make the tests passing, so I assume, that the demo certs are not valid anymore and should be replaced. Correct me if I'm wrong.

Thanks and kind regards,
Jan

**Comment by sophokles73** [comment]
@JanZimmer, you are absolutely right. The root cert expired end of May :-(

I am already working on it to extend their validity period ...

**Comment by sophokles73** [comment]
Should be fixed in 8991069.

Can you give it a try, @JanZimmer and close the issue or provide some feedback, depending on the outcome?

Thanks,
Kai

**Comment by sophokles73** [comment]
Seems to cause no issues anymore ...
