### ISSUE TITLE
EndpointContext in Request

### ISSUE THREAD

**Issue by T0bbe** [eclipse/californium#541]
I am working on enabling OSCORE for the Californium branch 2.0x and I have stumbled upon on problem, or rather a suggestion.

Could the EndpointContext (the destination context) in Requests be created when one calls the method public Request setURI(final URI uri)?

Or I am supposed to set it manually, beside also manually setting the URI for every request (since public InetAddress getDestination() is deprecated)?

**Comment by boaks** [comment]
The current HEAD of 2.0.x should already set the context, can you check, if it's possible to update your branch?

**Comment by T0bbe** [comment]
Thank you. It solved the issue.
