### ISSUE TITLE
Possible NPE in InMemoryMessageExchangeStore

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#547]
This issue relates to the 2.0.x branch. 
I have a situation where a call to InMemoryMessageExchangeStore.assignMessageId()  yields an NPE, since messageIdProvider is null. Since messageIdProvider is not automatically set at creation of InMemory..., there seems to be a possibility that it could still be null when a call to assignMessageId() is processed, thus a non-null check would seem to be a good idea.

**Comment by sbernard31** [comment]
When MessageIdProvider == null, it should be set with a default implementation when we start the MessageExchangeStore.

Could you detail how to reproduce this kind of error or at least in which condition this happen? If you have the stacktrace about the NPE this could help too.

**Comment by boaks** [comment]
Smells like messages are sent before `start()`.

```
	public synchronized void start() {
		if (!running) {
			startStatusLogging();
			if (deduplicator == null) {
				DeduplicatorFactory factory = DeduplicatorFactory.getDeduplicatorFactory();
				this.deduplicator = factory.createDeduplicator(config);
			}
			this.deduplicator.start();
			if (messageIdProvider == null) {
				LOGGER.debug("no MessageIdProvider set, using default {}", InMemoryMessageIdProvider.class.getName());
				messageIdProvider = new InMemoryMessageIdProvider(config);
			}
			running = true;
		}
	}
``` 

should have set it.

**Comment by LudwigSeitz** [comment]
Did some more digging. Apparently what happens is that CoAPExchange.respond(ResponseCode code, byte[] payload) is the culprit, although I'm still unsure why other CoAP responses work and this specific one fails.

**Comment by LudwigSeitz** [comment]
Ok I see. The problem is that my code is actually not sending the message, just creating the exchange and calling the Resource's handlePOST() method (it's part of my Junit tests for a specific resource), so I did not call start() as @boaks pointed out.

**Comment by boaks** [comment]
Hi Ludwig,

sorry for failing to join the hangout. 
I'm not sure, if your work will be affected by our current "redesign" in PR #545 and PR #546.
While searching for the leak in message exchange store (issue #429), I was faced some race conditions I'm currently on. So If you would wait for the end of week, I hope I can finish those changes (or at least have a preview for it).

**Comment by sbernard31** [comment]
>Ok I see. The problem is that my code is actually not sending the message, just creating the exchange and calling the Resource's handlePOST() method (it's part of my Junit tests for a specific resource), so I did not call start() as @boaks pointed out.

I suppose we can close this issue.
Feel free to reopen it if I'm wrong.
