### ISSUE TITLE
Allow to defer client certificate chain validation in DTLS

### ISSUE THREAD

**Issue by AlexITC** [eclipse/californium#549]
* branch: 2.0.x
* commit: 05b12ed8

### Use case
Supporting a dynamic list of certificates authorities for the client certificates.

Example:
- A user registers its CA with us.
- Devices owned by this user sends its own X509 certificate (signed by the user CA) in the handshake (client certificate).
- The server performs the handshake but it doesn't validate the client certificate chain.
- The server implements a custom certificate validator which checks against the dynamic list of CAs.

### Behavior
Currently, if we don't set the `trustStore` in the `DTLSConfig`, the X509 client certificates are disabled, we need a to define a way to enable X509 client certificates without specifying the trusted certificates, using this, the X509 client certificates would be supported while the certificate validation will not be performed if there are no trusted certificates.

What do you think?

**Comment by boaks** [comment]
Fixed with #553.

Please check, if it works for you.

**Comment by AlexITC** [comment]
Sadly, I'm unable to verify it right now because we are tied to a previous californium version, I'm closing this for now and I'll open it again if I find any issue, thanks!
