### ISSUE TITLE
Error when using new certificates 

### ISSUE THREAD

**Issue by dcalvoalonso** [eclipse/californium#55]
As the certificates provided have expired, I have tried to create new one following the instructions of  https://github.com/eclipse/californium/tree/master/scandium-core.
Nevertheless, when I use them, I get the following error:

18 FINE [CertificateMessage]: Certificate validation failed due to signature check failed - (org.eclipse.californium.scandium.dtls.CertificateMessage.java:401) verifyCertificate() in thread DTLS-Receiver-0.0.0.0/0.0.0.0:39912 at (2016-06-03 11:19:18)

18 INFO [DTLSConnector]: Aborting handshake with peer [localhost/127.0.0.1:5684]: Certificate chain could not be validated - (org.eclipse.californium.scandium.DTLSConnector.java:1487) terminateOngoingHandshake() in thread DTLS-Receiver-0.0.0.0/0.0.0.0:39912 at (2016-06-03 11:19:18)

**Comment by sophokles73** [comment]
As part of #54 I have also updated the instructions and have provided a shell script for automatically creating the key stores.

Can you give it a try and provide some feedback, @dcalvoalonso?

**Comment by dcalvoalonso** [comment]
I have just tried the shell script and it works like a charm!! No problem when using the output certificates! Thanks for so a quick solution.

**Comment by sophokles73** [comment]
Glad it worked :-)
