### ISSUE TITLE
Want to know how the package works

### ISSUE THREAD

**Issue by IbrahimaWane** [eclipse/californium#564]
Well, I don't have advanced knowledge about Java and I am actually new in it. But I would like to know in the package, which class is actually sending/receiving the CoAP packet. And which one assembles the packet(where we can say here is the CoAP packet). I hope it's a valid question and thanks in advance.

**Comment by boaks** [comment]
There are examples in "demo-apps", the simplest ones are `cf-helloworld-client` and `cf-helloworld-server`. if you clone the git repo and build it locally, you will find the jars in "demo-apps/run".

**Comment by IbrahimaWane** [comment]
Thanks, I read those examples and understood them but the thing that I am asking is : for example, is the CoAPClient class using DatagramSocket to send packets to the server? If not, which Java built-in method it uses to send packets.

**Comment by boaks** [comment]
>  for example, is the CoAPClient class using DatagramSocket to send packets to the server?

Yes, the messages are sent via a `Connector`, which either send "plain" coap using use a `UDPConnector` (which holds that `DatagramSocket`) or "encrypted" coaps using `DTLSConnector` (also holding a `DatagramSocket`). There are also experimental connectors using coap over tcp.

**Comment by IbrahimaWane** [comment]
Thank you for the quick and precise response. That was it for the message transmission. For the second and last part of my question, let me give also an example. When we send a simple datagram packet, we have the fields of the UDP packet (such as "source port", "destination port"...etc) appended to the payload we sent. Same thing apply with the CoAP packet, the version, type, token length..etc are appended to the payload. But where in the codes (in the library) this action of appending has been performed. I hope it makes sense. :)

**Comment by boaks** [comment]
The destination address and source port are handled by the `DatagramSocket` (source port) and `Datagram` (destination address and destination port). The CoAP server binds its DatagramSocket to the standard CoAP port (specified in Californium.properties as 5683) and the client usually to a random port.

**Comment by IbrahimaWane** [comment]
Thank you. Your answers were helpful
