### ISSUE TITLE
How the Get method works

### ISSUE THREAD

**Issue by IbrahimaWane** [eclipse/californium#574]
Thanks for your great CoAP library... But as I used your package in my Home IOT project, I have been tasked to understand how the whole package works. I am trying to find out how the **get( )** method in the **CoapClient** class sends a get request to a server. While following the traces, I arrived at **outEndpoint.sendRequest(request)** (still in the class), which directs me to **Endpoint** interface(therefore CoapEndpoit class). I don't know how the method **sendRequest(....)** in **OutboxImpl** (which is a subclass of CoapEndpoint) overrides the one in the **CoapEndpoint** class. But nevertheless, the method **connector.send(message)** ( in UDPConnector class ) doesn't do anything except **outgoing.add(msg)**, adding the msg into a blocking queue.

- I know how the message is sent. It's by using **socket.send(datagram);** in **work( )** method, in **Sender**  subclass (in UDPConnector class). But I couldn't connect it to the **get( )**  method in **CoapClient**. 
If someone could help me I would be grateful.

**Comment by boaks** [comment]
> I don't know how the method sendRequest(....) in OutboxImpl (which is a subclass of CoapEndpoint) overrides the one in the CoapEndpoint class. 

It doesn't :-). 
`CoapEndpoint.sendRequest` calls the `CoapStack.sendRequest`, which then forwards the `sendRequest` through several `Layer`s. 
The `StackBottomAdapter` in `BaseCoapStack` then finally calls the `outbox.sendRequest`.

> But nevertheless, the method connector.send(message) ( in UDPConnector class ) doesn't do anything except outgoing.add(msg), adding the msg into a blocking queue.

There is a `Sender` `NetworkStageThread`, which takes the messages out of the queue and send them using the `DatagramSocket` in it's `work` method.

```
			RawData raw = outgoing.take(); // Blocking
                        ...
			socket.send(datagram);

```

**Comment by IbrahimaWane** [comment]
Thanks. From the **get( )** method until UDPConnector, what makes the NetworkStage run the **run()** method?

**Comment by sbernard31** [comment]
Threads are started on connector starts (`UDPConnector.start()`) which is started on coapendpoint start.

**Comment by boaks** [comment]
```
	private void runInProtocolStage(final Runnable task) {
		executor.execute(new Runnable() {
			@Override
			public void run() {
				try {
					task.run();
				} catch (final Throwable t) {
					LOGGER.error("exception in protocol stage thread: {}", t.getMessage(), t);
				}
			}
		});
	}
```

This method in the CoapEndpoint. The "executor" is a `ScheduledExecutorService` which run's the job on it's own thread(s).

**Comment by IbrahimaWane** [comment]
Ok I get that. but what I want to say is that, from **CoapClient.get()** going down until UDPConnector, I'm directed only to **outgoing.add( )** and this one doesn't not call **UDPConnector.start();**. Where the method **start( )** is called?

**Comment by boaks** [comment]
The `Connector`'s are started with the `CoapEndpoint.start()`. Using the default connectors, they are started, when they are added to the `EndpointManager`.

**Comment by IbrahimaWane** [comment]
I finally got it thanks to your help. I'm a bit lazy 🤓 .... I know by the get() method, the type is set to CON and the code to GET...etc. Where is the token set?

**Comment by boaks** [comment]
> Where is the token set?

In `InMemoryMessageExchangeStore.registerWithToken`.
Just to mention: most IDE offers a way to search for calls. In Eclipse IDE, select
Message **setToken**(Token token) and then use the context menu (right button) to select "References" and the the scope (scope "Project" should do it). Then you see all the calls to that method and I'm sure, you will be able to find the important ones :-).

**Comment by IbrahimaWane** [comment]
Thank you Mr Boaks. That was really helpful :)

**Comment by boaks** [comment]
So, if your question is answered, would you close this issue?
