### ISSUE TITLE
Support for Fetch and Patch

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#594]
This is a feature request.

I am planning to work with the latest version of LwM2M which includes Fetch and Patch (https://tools.ietf.org/html/rfc8132). Therefore it would be nice to have those features in Californium. 

Are there any plans to support this? Can I possibly help?

**Comment by boaks** [comment]
Adding new `code`(s) and `handle` methods to `CoapResource` should not be a too big issue.
But I have no glue, if there is more to do in californium.

**Comment by boaks** [comment]
See PR #601

**Comment by boaks** [comment]
PR #601 is merged. If your issue is not solved by that, just add a comment with further information, and I will reopen this issue.
