### ISSUE TITLE
[DTLS] Removing/Disabling renegotiation feature

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#604]
The _"Transport Layer Security (TLS) / Datagram Transport Layer Security (DTLS) Profiles for the Internet of Things"_ ([RFC 7925](https://tools.ietf.org/html/rfc7925#section-17)) advices to disable renegociation feature.

Do you agree to remove it (which will clean the code) ? or should we add a way to disable it ?
(Personnally, I'm not even sure if this feature really works, I never tested it)

**Comment by boaks** [comment]
Votes for remove.

**Comment by boaks** [comment]
Votes for configure.

**Comment by jimsch** [comment]
Given that this is not doable in DTLS 1.3, I see no reason to keep it.

**Comment by boaks** [comment]
@jimsch 
The idea was, to add a vote for "remove" or "configure" in the comments above :-). 
But OK, you seems to agree on "remove".

**Comment by sbernard31** [comment]
#618 is integrated in 2.0.x branch.
