### ISSUE TITLE
Session Ticket implemented ? 

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#619]
While I'm trying to implement #617 (Session lifetime), I faced some code about Ticket Session.
But I'm not sure to understand if [rfc5077](https://tools.ietf.org/html/rfc5077) is implemented ?

It seems to me this work is not really finished ? Am I right ?

2nd question : is SessionCache really used ? and what is the purpose of this ?

**Comment by boaks** [comment]
For me this look like a idea to persist or transfer the dtls session information.
I guess, this was done for the "cluster" or DTLS session overspaning a server restart.
I don't think it's intended to be used for RFC5077.

**Comment by sbernard31** [comment]
> For me this look like a idea to persist or transfer the dtls session information.
> I guess, this was done for the "cluster" or DTLS session overspaning a server restart.

To allowing session resumption in such use cases . I think you're right.

But, this part of the code directly refer the RFC5077 : https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/SessionTicket.java#L75

@sophokles73, do you have more information about that ? Do you know if this is actually used ?

**Comment by sbernard31** [comment]
> At least it was my intention to support RFC 5077 when I wrote the code.

Ok, but this implementation is not finished ? I mean you just lay the foundation, right ?

**Comment by sophokles73** [comment]
IIRC the idea was to have the ticket and codec in place so that it can already be used to store session state in a SessionCache. But I did not implement the HELLO extension nor the server's NewSessionTicket message, i.e. a client currently cannot resume a session based on a Session Ticket.

**Comment by sbernard31** [comment]
Yep
