### ISSUE TITLE
DTLS and Californium Sandbox Server not working

### ISSUE THREAD

**Issue by raMic2387** [eclipse/californium#62]
Hello!
I've written an application which uses californium and scandium to provide coap client functionality. To test the app I've written a litte test server (also using californium). Connecting to this test server works without any problems (with and without dtls).
Now I'm also trying to connect to one of these:
**coaps://californium.eclipse.org:5684
coaps://vs0.inf.ethz.ch:5684
coaps://vs0.inf.ethz.ch:5685**
which doesn't work at the moment.
To find out why it doesn't work I've used the example provided [here](https://github.com/eclipse/californium/blob/master/demo-apps/cf-secure/src/main/java/org/eclipse/californium/examples/SecureClient.java).
Using this example code (with modified server url) doesn't work too. The output using fine logging is:

`Jun 24, 2016 12:22:31 AM org.eclipse.californium.core.network.config.NetworkConfig createStandardWithFile
INFORMATION: Loading standard properties from file Californium.properties
Jun 24, 2016 12:22:31 AM org.eclipse.californium.core.network.CoapEndpoint start
INFORMATION: Starting endpoint at 0.0.0.0/0.0.0.0:0
 1 CONFIG [DTLSConnector]: Cannot determine MTU of network interface, using minimum MTU [1280] of IPv6 instead - (org.eclipse.californium.scandium.DTLSConnector.java:331) start() in thread main at (2016-06-24 00:22:31)
11 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Receiver-0.0.0.0/0.0.0.0:58507] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Receiver-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
 1 INFO [DTLSConnector]: DTLS connector listening on [0.0.0.0/0.0.0.0:58507] with MTU [1.280] using (inbound) datagram buffer size [16.474 bytes] - (org.eclipse.californium.scandium.DTLSConnector.java:281) start() in thread main at (2016-06-24 00:22:31)
10 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Sender-0.0.0.0/0.0.0.0:58507] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
Jun 24, 2016 12:22:31 AM org.eclipse.californium.core.CoapClient setEndpoint
INFORMATION: Started set client endpoint 0.0.0.0/0.0.0.0:58507
10 FINE [Connection]: Handshake with [californium.eclipse.org/129.132.15.80:5684] has been started - (org.eclipse.californium.scandium.dtls.Connection.java:831) handshakeStarted() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
10 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP256r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:373) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
10 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP384r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:381) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
10 FINE [ECDHECryptography$SupportedGroup]: Group [brainpoolP512r1] is not supported by JRE - (org.eclipse.californium.scandium.dtls.cipher.ECDHECryptography$SupportedGroup.java:389) <init>() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:31)
12 FINE [DTLSConnector]: Re-transmitting flight for [californium.eclipse.org/129.132.15.80:5684], [3] retransmissions left - (org.eclipse.californium.scandium.DTLSConnector.java:112) handleTimeout() in thread DTLS RetransmitTask 1 at (2016-06-24 00:22:32)
No response received.
10 FINE [Connection]: Handshake with [californium.eclipse.org/129.132.15.80:5684] has been started - (org.eclipse.californium.scandium.dtls.Connection.java:831) handshakeStarted() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:33)
12 FINE [DTLSConnector]: Re-transmitting flight for [californium.eclipse.org/129.132.15.80:5684], [3] retransmissions left - (org.eclipse.californium.scandium.DTLSConnector.java:112) handleTimeout() in thread DTLS RetransmitTask 1 at (2016-06-24 00:22:34)
12 FINE [DTLSConnector]: Re-transmitting flight for [californium.eclipse.org/129.132.15.80:5684], [2] retransmissions left - (org.eclipse.californium.scandium.DTLSConnector.java:112) handleTimeout() in thread DTLS RetransmitTask 1 at (2016-06-24 00:22:36)
10 FINE [Connection]: Handshake with [californium.eclipse.org/129.132.15.80:5684] has been started - (org.eclipse.californium.scandium.dtls.Connection.java:831) handshakeStarted() in thread DTLS-Sender-0.0.0.0/0.0.0.0:58507 at (2016-06-24 00:22:37)`

Regarding the log it seems that the server simply doesn't respond to the dtls handshake request. Even increasing the RetransmissionTimeout of the DtlsConnectorConfig.Builder doesn't change anything.
This behavior ist the same on all three servers whereas my test server works flawless.
I've tried using version 1.0.0, 1.0.4 and 1.1.0-SNAPSHOT (build from source) but this behavior is the same with all versions.
I hope that you can help me because at least the californium.eclipse.org server is also using californium.
Is there something I'm doing wrong or is there a problem with these servers?
Thanks for the great project and your help.

**Comment by PeterWaher** [comment]
I have the same problem today. There doesn't seem to be anything listening on port 5684 accepting UDP datagrams on the server. Do you know of any other DTLS-enabled test servers available on the Internet?

**Comment by sophokles73** [comment]
no, sorry

**Comment by PeterWaher** [comment]
For others interested in DTLS interoperability testing: http://leshan.eclipse.org/#/security allows you to test DTLS connectivity using Pre-shared keys (PSK). You can create your own identities and PSKs and then connect to it using DTLS/UDP at port 5684.
