### ISSUE TITLE
 The correct way to create a server that handles multicast requests.

### ISSUE THREAD

**Issue by IbrahimaWane** [eclipse/californium#621]
What is the correct way to use multicast as a server? Here is my code:
  @Override
    public void onCreate() {
        this.server = new CoapServer();

        InetAddress addr = null;
        try {
            addr = InetAddress.getByName("224.0.1.186");
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        InetSocketAddress bindToAddress = new InetSocketAddress(addr, 5683);
        CoapEndpoint multicast = new CoapEndpoint(bindToAddress);
        server.addEndpoint(multicast);
        server.add(new HelloWorldResource());
    }
But I send multicast requests and nothing happens.

**Comment by vikram919** [comment]
@IbrahimaWane  
CoapMulticast is not yet implemented in eclipse californium project, you can request the contributors for the current status of multicast, however https://github.com/eclipse/californium/issues/219 gives you some idea.

**Comment by vikram919** [comment]
great!! If you have no more questions can you please close this?
