### ISSUE TITLE
2.0.x, dc9e8d7bc1, Small improvements. => reduced visibility of KEYs/IDs

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#624]
Hi @sophokles73 

I'm not sure, why you changed the visibility from `public` to `package`, but FMPOV `public` enables to create customized `EndpointContextMatcher` in other packages. So I would prefer, if the visibility could be changed back to `public` again.

**Comment by sophokles73** [comment]
That is a good argument for having them public. However, I believe that if that is the intended usage of these constants, a nice JavaDoc explaining their purpose would be helpful so that others implementing such a matcher know what to expect, don't you think?

**Comment by boaks** [comment]
> However, I believe that if that is the intended usage of these constants, a nice JavaDoc explaining their purpose would be helpful so that others implementing such a matcher know what to expect, don't you think?

I think, a documentation, which contains all the details to implement such a matcher will be very broad and rarely used. So right now, I was the only one, who implemented a customized implementation (see Leshan). Therefore, FMPOV, the only (and therefore best) approach to implement such a matcher is to analyse and study the current implementations (including the one in leshan) and the RFCs. 
Doing so, understanding the KEYs shold be the easiest part of that analysis.

**Comment by boaks** [comment]
the keys are public again.
