### ISSUE TITLE
2.0.x, 3ad5bbfb1df, include key algorithm, doesn't fit the fixed key algorithm in CertificateMessage.getPublicKey

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#626]
Adding a "key algorithm" to `RawPublicKeyIdentity` seems not to match the current implementation in `CertificateMessage.getPublicKey()`, which still uses the fixed "key algorithm" "EC".

By the way, the certs and key encoded in ASN.1 already contains the algorithm, so I'm not sure, if adding such parameter should be replaced by a ASN.1 parsing (which would also fix the length bits issues of PR #625).

**Comment by boaks** [comment]
Just to mention: a general TLV-ASN.1 parsing and support of SEQUENCE and OID should be enough to replace the added "key algorithm" argument.

**Comment by sophokles73** [comment]
I haven't found a standard method in Java's certificate/key classes to get at the algorithm. But I agree, the algorithm is contained in the encoded key. Please feel free to implement an ASN.1 parser for retrieving it :+1:

**Comment by sophokles73** [comment]
> Adding a "key algorithm" to RawPublicKeyIdentity seems not to match the current implementation in CertificateMessage.getPublicKey(), which still uses the fixed "key algorithm" "EC".

That might be true. We are facing the same issue in CertificateMessage.getPublicKey() as we do with deserializing a RawPublicKeyIdentity. So, currently we only support ECC based RawPublicKeys. We can fix this once we have an ASN.1 parser ...

**Comment by boaks** [comment]
> However, the serialization/deserialization of a RawPublicKeyIdentifier should work with any kind of key, in particular it should work with an ECC based key.

I still have my doubts, how useful these other "key algorithm" will be using the current scandium implementation.

**Comment by boaks** [comment]
@sophokles73 

So can you give us some information about your intention to change that?
Was it to "finalize" the serialized format?

**Comment by sophokles73** [comment]
I am not sure what you are getting at. Are you proposing to either undo this commit or instead implement an ASN.1 parser to retrieve the algorithm from the encoded key?

**Comment by boaks** [comment]
I want to understand the purpose of this commit. 
It pretends to support other key algorithms for RPK, but as I wrote, I have my doubts, if this is working and under which constraints. Should it work? Which constraints must be applied? 
If it's not intended to "really" support other key algorithms for RPK, the only benefit would be the defined serialization format. so was that the purpose?

**Comment by boaks** [comment]
By the way, I currently try to implement the ASN.1 parser

**Comment by sophokles73** [comment]
> I want to understand the purpose of this commit.

The purpose is to support any kind of public key, not just ECC based keys.

**Comment by boaks** [comment]
OK, so let's see, if I could provide a ASN.1 DER parser to reduce the information-duplication and make the other key algorithms at least "potentially" usable. ("potentially" means, I'm not sure, if I can spend the time to really use other key algorithms, but it will fix the currently limitation of the approach of that commit.)

**Comment by sophokles73** [comment]
this commit has no limitation in itself. But I agree that the CertificateMessage currently is limited to ECC based keys. So, if we could use your ASN.1 parser in both places to remove the hard coded dependency on ECC, that would be awesome :+1:

**Comment by boaks** [comment]
See PR #628

**Comment by boaks** [comment]
Fixed with merged PR #628
