### ISSUE TITLE
Californium re-uses unacknowledged MIDs in outbound requests

### ISSUE THREAD

**Issue by sophokles73** [eclipse/californium#63]
Californium currently uses a simple counter for generating message IDs that is incremented with every message sent and wrapped at 2^16.

When client code uses Californium to send out requests to another CoAP server at a high rate, this may lead to re-use of message IDs for which Californium hasn't received an ACK or CON yet. While such a client's behavior seems questionable (flooding a constrained device with hundreds of requests per second doesn't really fit with the constrained device environment), Californium should make sure not to re-use IDs in this erroneous way. Also see #57 for a more detailed discussion of the issue.

**Comment by magerramov** [comment]
Switching mid assignment to using a BitSet that tracks open exchanges, and then calling BitSet.nextUnset(currentMid) may do he trick here. The cost extra CPU.
