### ISSUE TITLE
Question: How to add new PSK after starting server?

### ISSUE THREAD

**Issue by vikram919** [eclipse/californium#638]
Here is my requirement:
I run a Coap Server on plain and secure sockets, server establishes master secret using OOB authentication mechanism with a Coap Client. I would like to add the master secret as PSK to the server and client. how can I configure server to add a new PSK ? Do I have to create a a new Endpoint with this PSK? or can I make use of existing Endpoint?
I see that` InMemoryPSKStore` to store the list of PSK with their identities.

**Comment by boaks** [comment]
The server's `DTLSConnector` uses a implementation of `PskStore`. The "Static-" or "InMemory" implementations are for demonstration and testing. 
So, if you have requirements, just develop your own `PskStore` implementation which, matches that and pass that implementation in when creating the `DTLSConnector`. My feeling is, that there will be so many different requirement lists, that it's not possible to provide all that implementations in californium itself. Therefore the interface, to enable others to implement it according their requirements.
If `InMemoryPSKStore` works for you, great! It only offers to add credentials and not to remove them. Its intention is, to have a demo implementation for a server, where multiple clients can have different credentials.
