### ISSUE TITLE
Adding new resources dynamically - CoAP

### ISSUE THREAD

**Issue by GPrathap** [eclipse/californium#64]
Once CoAP server is started I need to add new resources dynamically. But I have to stop and start the server again in order to access new resources. I suppose adding new resources same as adding a new HTTP servlet into already started HTTP server.

Here I added source code which is used for adding dynamic resources. If I am missing anything here let me know.

```
private static CoapServer server;

public CoAPEventAdapter(InputEventAdapterConfiguration eventAdapterConfiguration,
                        Map<String, String> globalProperties) {
    this.eventAdapterConfiguration = eventAdapterConfiguration;
    this.globalProperties = globalProperties;
    if(server == null){
        server = new CoapServer();
        server.start();
    }
}

@Override
public void connect() {
    registerDynamicEndpoint(eventAdapterConfiguration.getName());
    isConnected = true;
} 

private void registerDynamicEndpoint(String adapterName) {
        server.stop();
        server.add(new HelloWorldResource(adapterName));
        server.start();
}


class HelloWorldResource extends CoapResource {

    public HelloWorldResource(String resourceName) {
        // set resource identifier
        super(resourceName);
        // set display name
        getAttributes().setTitle("Hello-World Resource");
    }

    @Override
    public void handleGET(CoapExchange exchange) {

        // respond to the request
        exchange.respond("Hello World!");
    }
}
```

**Comment by sophokles73** [comment]
Which version are you working with? Master? 1.0.x?

**Comment by sophokles73** [comment]
This should work. I have just tested it with `HelloWorldServer` from _cf-helloworld-server_ ...
No need to stop and restart the server.

**Comment by GPrathap** [comment]
I am using 2.0.0-M1. Will check it again and let you know. Thanks.

**Comment by GPrathap** [comment]
Yesterday I tried more that 3 times and I could not able to get listed resources which are created dynamically. Now it is working. I change ThreadPoolExecutor login little bit. Maybe something login behind that. 

Please close this. Thanks

**Comment by sophokles73** [comment]
No problem :-)
