### ISSUE TITLE
SNI PresharedKeyIdentity.getName() API break ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#649]
I'm currently integrating cf 2.0.0-M10 in Leshan.
The main API break is about PSK/SNI changes.

I don't think so much about integrating SNI support in Leshan so I disable it for now, using `setSniEnabled(false)`

But my test doesn't pass anymore mainly because of  **`PreSharedKeyIdentity.getName()` returns the `identity` prefixed with a `:` even if there is no virtualhost provided**. (see PreSharedKeyIdentity constructor)

Is it the intended behavior ? 

I was missing a bit the discussion about it and maybe I do not understand so well the idea behind it.

**Comment by sophokles73** [comment]
Sorry to hear that it broke your test(s). The reason to (always) include the colon (`:`) is that otherwise you cannot distinguish between an identifier `the-identity` qualified by virtual host name `my.host` and an unqualified identifier called `my.host:the-identity`.
If the *getName* method is used to determine if two identifiers are equal, then this might pose a problem. The *equals* method therefore checks for both properties, the virtual host and the identifier.

However, the `Principal` interface explicitly defines the *equals* and *hashCode* methods which to me indicates that checking for equality should be based on these methods (and probably not on *getName*). Based on this it might be acceptable to return the same name for the two instances described above and add a warning to the *getName* method's JavaDoc pointing out this problem. WDYT?

Sorry for the inconvenience, I didn't expect any particular problem arising from this. @boaks reviewed the PR and also didn't seem to suspect a problem here.

**Comment by sbernard31** [comment]
Now I understand why this is done like this.

> Sorry for the inconvenience, I didn't expect any particular problem arising from this. @boaks reviewed the PR and also didn't seem to suspect a problem here.

No problem, It's not a big deal to me, I replaced in my code `getName()` by `getIdentity`.
But I still ask myself, if in a general way we want that disabling SNI make scandium behave like before ? Maybe this is acceptable like this ?

**Comment by boaks** [comment]
@sbernard31 

Any open stuff for this issue? Or can it be closed?

**Comment by sbernard31** [comment]
I just raise that `getName()` behavior break compatibility with previous californium version even if you deactivate SNI support. Which surprising me.

On our side we fix that using `getIdentity` instead of `getName`.

As @sophokles73 say if you really want to compare 2 `Principal`, you should probably use `equals`. So finally I don't know what is the purpose of `getName` and so if it's ok to return identity prefixed with `:` if there is no virtualhost.

If you want to compare you use `equals`.
If you want to print/log you  use `toString`.
If you want to access to virtualhost or identity you use the corresponding getter.
So for what do you use getName?

> can it be closed?

If you (@boaks  and @sophokles73 )  think the current `getName` behavior is ok. Yes it can be closed.

**Comment by sophokles73** [comment]
well, the *getName* method is required by `Principal` so we have to implement it. Sadly, the Principal JavaDocs do not provide much guidance regarding the intended use for *getName* so I think we are pretty much on our own here. FMPOV there is nothing wrong with the current implementation.

**Comment by boaks** [comment]
Maybe we switch to 3 modes:
- disabled SNI support (remove ":", just plain "name")
- enabled SNI support, but not used (use ":name")
- enabled SNI support, and used (use "host:name")

With that, configuration disables or enables it, and runtime will decided in enabled, if its used or not.

**Comment by sbernard31** [comment]
When SNI is disabled and client add SNI extension, server will log this in warning :
```
included SNI in HELLO but SNI support is disabled
```
I think warning is too strong for this kind of log. Could I change this to DEBUG ?

**Comment by sbernard31** [comment]
(I change the warn log to debug)

**Comment by sbernard31** [comment]
@boaks what do you plan for this issue ?

Should we close it ? I'm not sure it's worth it to go with : https://github.com/eclipse/californium/issues/649#issuecomment-405494092

**Comment by boaks** [comment]
SNI is still broken (resumption doesn't work, see #644). 
But SNI seems to be not that used, so FMPOV, other issues have a higher prio.
So, I would prefer to keep it open as reminder.

**Comment by LudwigSeitz** [comment]
I very much support the solution proposed by boaks:

-   disabled SNI support (remove ":", just plain "name")
-     enabled SNI support, but not used (use ":name")
-     enabled SNI support, and used (use "host:name")

In order to avoid breaking lots of code that doesn't use SNI.

**Comment by boaks** [comment]
I created the PR #816, which addresses this issue.
Though there are plenty usage combinations, I would appreciate, if everybody check his own configuration and provides feedback, if it works for that. After merging the dtls cleanup #811 on which #816 is based on, I hope that I can add more unit tests as well.

**Comment by sbernard31** [comment]
(For me we can close this)
