### ISSUE TITLE
LeastRecentlyUsedCache.find performance

### ISSUE THREAD

**Issue by jizhenfang** [eclipse/californium#651]
# LeastRecentlyUsedCache.find performance
Hi ,  I am using scandium  in my project.  I  read the resouce code in LeastRecentlyUsedCache and find a issue .  LeastRecentlyUsedCache find method logic  use checking every cache values  in the implements of Predicate to  find the connection isntance. why not use InetSocketAddress instance to find the connection instance via get(key) ? Its better performance than current code .
the  resource code  [https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/LeastRecentlyUsedCache.java](url)

**Comment by sbernard31** [comment]
Hi,

>  LeastRecentlyUsedCache find method logic use checking every cache values in the implements of Predicate to find the connection isntance. why not use InetSocketAddress instance to find the connection instance via get(key) ?

I think `find` method is used only when we search a connection using another key than `InetSocketAddress`. If this is not the case and we are using `find` with a predicate which check `InetSocketAddress` could you point where this is done in the code.

**Comment by jizhenfang** [comment]
the code in DTLSConnector's  processClientHello method .
When processClientHello , the code wanna find the connection by sessionId, but LeastRecentlyUsedCache cache is <InetSocketAddress,Connection>,  so It will  invoke the LeastRecentlyUsedCache.find everytime in DTLS handshake. When the server cache so many connections , it will effect the performance.  Is it better to  make another cache by <SessionId,Connection> ? it will improve the performance when processClientHello.

**Comment by sbernard31** [comment]
Ok, I get it.
Did you face real performance issue or this is just theoretical ?

**Comment by sbernard31** [comment]
Could you share your tests ?

**Comment by boaks** [comment]
@jizhenfang 

I'm not sure, if I understand your findings.
As Simon already wrote, the `LeastRecentlyUsedCache.find` is only used by the InMemoryConnectionStore, and there only for dtls session **resumption**.

So, what did you benchmark? Can you provide some wireshark logs?

I feel, that you may have accidentally set the `autoResumptionTimeoutMillis` to 0 
(instead of `null` to disable the auto resumption).

**Comment by boaks** [comment]
@jizhenfang 

are still interested in this issue? Or can we close it?

**Comment by boaks** [comment]
@jizhenfang 

If you interested again, add a comment here or create a new issue.

**Comment by jizhenfang** [comment]
@boaks  I am sorry  to  reply so late.   The issue can close it.  AutoResumption is disable in my project and thanks for help.
