### ISSUE TITLE
How to use X.509 certificate in CoAP communication

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#655]
We are using Californium library to establish CoAP communication between client and server using X.509 certificates (mutual authentication over DTLS). 
Please help in pointing to the code flow that needs to be implemented on the server and client side to achieve this functionality.

**Comment by AlexITC** [comment]
What's the difference between this question and #652 ?

- On the server, you set a certificate and its private key (this allows the server to decipher the traffic).
- On the client, you add the server certificate as trusted, the certificate has a public key that is used to cipher the traffic.

If you want to use mutual authentication (let's say, the client has a certificate too), I can't say if that's possible with the latest californium version, we applied a couple of commits to allow client certificates, see [californium-2.0.0-M5-Artik](https://github.com/artikcloud/californium/commits/2.0.0-M5-Artik).

**Comment by jas-singh14** [comment]
Hi Alexis,

Thanks for the information. 
How can we be fully sure about mutual authentication?

**Comment by AlexITC** [comment]
As I said, I don't know remember how it works in the current californium, I think you register the trusted CAs on the server and when a client sends its certificate, the server validates that the certificate is signed by one of the trusted CAs.

On our fork, what we did is to defer this validation to a custom client certificate validator.

**Comment by vikram919** [comment]
https://github.com/eclipse/californium/tree/2.0.x/demo-certs

I think above link in the project README, explains clearly how the server and client are mutually authenticated using the example key and trust stores provided by `demo certs` folder using self signed certificate from root CA or a chain of trust from intermediate CA
 
> How can we be fully sure about mutual authentication?

I did not understand, what it means actually?

**Comment by jas-singh14** [comment]
Vikram,

“ how can we be sure about mutual authentication” was in relation to Alexis point that he wasn’t sure if mutual authentication was supported in californium.
So my question was “ how can we be sure if mutual authentication is supported in californium “?
In case it is not supported, can this requirement be added to californium library?
Hope this clarifies...

**Comment by AlexITC** [comment]
I apologize to confuse you, mutual authentication is supported, since the time I was working with californium, there have been several improvements and I'm not sure how it works at the moment.

**Comment by vikram919** [comment]
@jas-singh14 
I have already mentioned in  https://github.com/eclipse/californium/issues/652 that mutual authenticated is implemented, tested and supported by californium.  
There are several examples to demonstrate how it works, above duplicate issue you have raised there I have already written about cf-android example which show mutual authentication example
2. https://github.com/eclipse/californium/tree/2.0.x/demo-apps/cf-secure/src/main/java/org/eclipse/californium/examples cf-secure project also demonstrate it as well.

I also request you to refer to standard RFC 7252 about mutual authentication for CoAP.

**Comment by jas-singh14** [comment]
We are using Californium and .Net library (https://github.com/Com-AugustCellars/CoAP-CSharp). However it seems that we are able to use the public keys from a self signed certificate from .Net library but such a functionality is not available in Californium. Can you please confirm this? and if possible suggest a workaround in californium. Basically our intention is that we should be able to use Californium in the same fashion as .Net library.
The way we have configured client and server using this .Net library is shown below:

1.	Server Code 
//Read Server Certificate
X509Certificate2 x509 = ReadCertificate(@"ServerCert.cer");

//Initialize a object of Pre-Shared Key
PskOne = new OneKey();
PskOne.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
PskOne.Add(CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(Encoding.UTF8.GetBytes(x509.PublicKey.Key.ToString())));
PskOne.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(x509.PublicKey.Key.ToString())));

UserKeys = new KeySet();
UserKeys.AddKey(PskOne);

//Initialize Coap Endpoint using userkey and Coaps port                       
CoAPEndPoint endpoint = new DTLSEndPoint(null, UserKeys, CoapsPort);

//Initialize CoapServer
       CoapServer _server = new CoapServer();

_server.AddEndPoint(endpoint);
_server.Start();

2. Client Code

//Read Client Certificate
X509Certificate2 x509 = ReadCertificate(@"ClientCert.cer");

//Initialize a object of Pre-Shared Key
       PskOne = new OneKey();
       PskOne.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
       PskOne.Add(CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(Encoding.UTF8.GetBytes(x509.PublicKey.Key.ToString())));
       PskOne.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(x509.PublicKey.Key.ToString())));
       
//Initialize Coap Endpoint using userkey and Coaps port                       
DTLSClientEndPoint client = new DTLSClientEndPoint(PskOne);
       client.Start();

**Comment by jas-singh14** [comment]
Also in our understanding, private key is not required for certificate based authentication, So we are bit confused why Cf library is expecting that as one of the parameters (e.g. C# library mentioned above doesn't require private key). Can you please help here as well?

**Comment by sbernard31** [comment]
You say that you C# library works just with a certificate without private key. But as far as I know, this does not make sense.
Look at the [certificate wikipedia page](https://en.wikipedia.org/wiki/Public_key_certificate)
_"In cryptography, a public key certificate, also known as a digital certificate or identity certificate, is an electronic document used to prove the ownership of **a public key.**"_

A public key must be used with a private key to be able to do [asymetric cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography).

If you are owner of those 2 certificates (ServerCert.cer and ClientCert.cer), you should also have the linked private keys as this is the first step to get your certificate :
_"In the X.509 system, an organization that wants a signed certificate requests one via a certificate signing request (CSR).
To do this, it first generates a key pair, **keeping the private key secret and using it to sign the CSR.** "_
(see https://en.wikipedia.org/wiki/X.509#Certificates)

**Comment by jas-singh14** [comment]
Basically we want some clarification about why there is a need of specifying private key in Cf and not in 
C# library:

we are using Cf API's below:
public Builder setIdentity(PrivateKey privateKey, PublicKey publicKey)
OR
public Builder setIdentity(PrivateKey privateKey, Certificate[] certificateChain, boolean preferRawPublicKeys)

**Comment by sbernard31** [comment]
The real question is why the private key is not needed in the C# library...
As I explained above, this private key is needed to be able to do asymetric cryptography ... If there is no private key needed, anybody can just take your public certificate (as it is public...)  and pretend to be you ...

**Comment by boaks** [comment]
@jas-singh14 

If you want answers, maybe you provide a wireshark capture of your C# client using only a "public key". 

> //Initialize a object of Pre-Shared Key

smells, that something happens totally different than assumed :-).

And

https://github.com/Com-AugustCellars/CoAP-CSharp/issues/46

seems also indicating, that x.509 is **NOT** working at all in the C# implementation your using. 

@jimsch

If possible, could you check the above snippet, if it makes any sense to you?

**Comment by AlexITC** [comment]
In asymmetric cryptography, you need the private and the public key, one key is used to cipher and the other one to decipher, if you provide a x509 certificate (it includes a public key) but not a private key, it is very likely that the traffic isn't being ciphered (assuming that your C# example works at all).

**Comment by boaks** [comment]
@jas-singh14 

Are you now **willing** and **able** to provide a wireshark capture of your DTLS handshake of the C# implementation your using?

Are you understand, that the C# implementation your using doesn't support x.509 at all? 
(Only a special branch provides you callbacks to implement it on your own.) 

If you can't provide the capture nor understand the limitaion of the C#  implementation your using, I assume, that your setup just uses the public key as PSK secret (according the comment in your snippet), or, as AlexITC wrote, doesn't use DTLS at all.

The wireshark capture will therefore show, that a "TLS_PSK_WITH_AES_128_???" is used in the SERVER_HELLO and not the "TLS_ECDHE_ECDSA_WITH_AES_128_???", or doesn't contain any valid DTLS records at all, because it doesn't use DTLS.

So without answers, I would like to close this issue and recommed that you use a other DTLS implementation (e.g. the one of java 9) to test your stuff!

**Comment by boaks** [comment]
> I agree that private key is required for certificate generation. But is private key required during handshake between client and server is the prime question?

And the only answer will be the wireshark capture.

**Comment by sbernard31** [comment]
> I agree that private key is required for certificate generation. But is private key required during handshake between client and server is the prime question?

Yes !  Again if that was not the case anybody could just get your public certificate and usurp your identity ...

**Comment by boaks** [comment]
@jas-singh14 

sorry, I didn't get it!
Is this issue now clear to you? So you agree on Simon's statement above, that you need both, the public and private key (which is also what I know)? Or do you still think, the C# sharp can do it without?

If you agree with Simon, and you also accept, that the C# implementation currently not supports certificates, could you then please make a final comment with that and close this issue?

**Comment by jas-singh14** [comment]
Yes, I agree with the observations. Thanks all for the valuable inputs.
