### ISSUE TITLE
Californium comply to RFC 7252

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#661]
We assume that the current Californium version is complying to Internet Engineering Task Force RFC#7252
Please confirm.

**Comment by vikram919** [comment]
@jas-singh14 
Can you be more specific about which feature/issue in compliance to IETF RFC7252 you wanted to point out?
There are open challenges ex: multicast behavior does not comply with IETF RFC 7252

**Comment by boaks** [comment]
If your question is 

"is californium the normative reference implementation for RFC7252?", 

the answer is simply **no**. You may have a look at

https://projects.eclipse.org/projects/technology.californium
https://projects.eclipse.org/projects/iot.californium/releases/2.0.0

about our intended scope. But californium doesn't pretend, that it's free of errors nor free of miss-understanding of the RFC's. The "issues" here provide a lot of useful information. Please consider also to read the "closed" ones (remove "is:open" from the default filter). If you feel, that there is an **new** issue, please provide all information related to your findings, best comply to our template for new issues. In many, many cases you will be asked to provide a wireshark capture, so maybe you prepare to provide that.  

In general, a specification may be difficult to understand. So, if you have any doubt, feel free to ask. Sometimes, if the question is in the first place about that understanding of the specification, I kindly ask you to use the IETF core mailing list ahead, to clarify your issues. That core mailing list is a large collection of information around coap, and may require some time to search for a special topic.

**Comment by jas-singh14** [comment]
Thanks for the inputs. closing this.
