### ISSUE TITLE
CoAP transmission parameters as per RFC 7252

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#666]
Please let us know in which file the transmission parameters like ACK_TIMEOUT, ACK_RANDOM_FACTOR etc, are defined.

**Comment by jas-singh14** [comment]
Also  is it required that the values for both CoAP server and client should match for these parameters i.e. ACK_TIMEOUT, ACK_RANDOM_FACTOR etc. OR they can have different values?

**Comment by boaks** [comment]
This depends on more details.
In general, you will need to test your setup, if it works proper for you.
Many of those parameter are used to optimize the communication, so in my experience they rarely switch between working/not working. So also in my experience, it will not harm too much, if different values are used. In many use-cases different client may connect to the same server. I these cases it will be common, that the clients may use different parameters. So it will not be possible, that the server use the same parameter, if the clients differ. But, as already mentioned, you must check, if it works for you.

ACK_TIMEOUT, ACK_RANDOM_FACTOR define the message retransmission times. They affect the EXCHANGE_LIFETIME on the server. That time is used by (some) Deduplicators to implement https://tools.ietf.org/html/rfc7252#section-4.5. The default value of the EXCHANGE_LIFETIME contains buffer of 100s for internal processing. In my experience this covers a window of values for these parameters. If you change them too much, you may also adjust the EXCHANGE_LIFETIME accordingly. 

If you use "separate responses" as in https://tools.ietf.org/html/rfc7252#section-5.2.2 then you may also adjust your server setting. But this will also depend on the number of devices, which use special settings value. e.g. only very few clients using large values for ACK_TIMEOUT, so would not adjust my server values for these, except they are the most important ones. But you see, it depends on a lot of details to optimize your overall communication.

**Comment by jas-singh14** [comment]
Thanks for the detailed response.
