### ISSUE TITLE
Compliance to RFC7959 (Block-Wise Transfers in the Constrained Application Protocol (CoAP))

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#669]
In case both CoAP client and server are compliant to RFC7959, do we need to configure some settings to enable Block-wise transfer OR is it automatically taken care by the underlying library (e.g. Californium).
i.e. automatically enabled when payload is large and disabled when payload is small.
Please advise.

**Comment by boaks** [comment]
These are two questions:

1. do blockwise transfer require configuration. You may improve four performance by selecting a proper blocksize. Say you run over some "low power wireless" it may be better to chose a small blocksize (e.g. 64 bytes or 128), if you run over IPv4 somehow 512 is a good value, and if you use IPv6 1024 can be a good choice. But you must test, which blocksize works best in your environment.

2. californium has two modes for blockwise, "transparent" means californium tries its best to switch automatically to blockwise, or not transparent, measn californium leaves it to the CoapResource and CoapClient implementation to handle the block options by itself. Especially, if large payload is transferred, copying that into heap may consume too much RAM, so as mentioned above in "transparent" californium tries its best, but you may do it better :-).

Two hint's on blockwise:
Depending on the payload size and blocksize, a blockwise transfer may take some time.
For BLOCK1 (large payload in request, e.g. PUT or POST) it's not supported, that your ip-address changes. So especially for mobile devices, it's not good choice to use BLOCK1.
BLOCK2 may work better, but if you affected by timeouts etc. "transparent" on the client will not work reliable. You need to implement you own handling in none "transparent" mode. 
The easiest setup FMPOV is a CoAP server in the cloud using "transparent" mode, and a client using its specific (none transparent) implementation to cover its communication situation.
