### ISSUE TITLE
Why Californium auto send Observe to Server？

### ISSUE THREAD

**Issue by JavaProgrammerLB** [eclipse/californium#670]
### About every 1 min, my client sent 17 bytes **Observe request** to server, I want to know why this auto send happen and how can I **stop the auto request**?

I use 2.0.0-M6 with dependency below
```
<dependency>
    <groupId>org.eclipse.californium</groupId>
    <artifactId>californium-core</artifactId>
    <version>2.0.0-M6</version>
</dependency>
```

My client log:
![log](https://user-images.githubusercontent.com/3973419/41635566-0cad4daa-747c-11e8-822a-5b219fa4f669.png)

Tcpdump packages:
![image](https://user-images.githubusercontent.com/3973419/41635667-a3c4df82-747c-11e8-8cc3-2d20ca76ed23.png)

TcpDump files:
filter condition: udp.port==3019 || udp.port == 19406
[devicebus-nbiot-access.zip](https://github.com/eclipse/californium/files/2117747/devicebus-nbiot-access.zip)

**Comment by boaks** [comment]
That's specified in

https://tools.ietf.org/html/rfc7641#section-3.3.1

It takes the value of the MaxAge option as time for the reregistration (that's what you have seen) , and the default in absent of that option is 60 seconds.

See https://tools.ietf.org/html/rfc7252#section-5.10.5 for the specification of the MaxAge option.

**Comment by JavaProgrammerLB** [comment]
@boaks Thanks for your detailed explanation
