### ISSUE TITLE
Logging of core UDP packet (CoAP data) data by californium library

### ISSUE THREAD

**Issue by jas-singh14** [eclipse/californium#671]
Is there a possibility that we can see the data on the wire (e.g. CoAP packets sent by client to server) in some form of log etc.
Due to some constraint, we won't be able to use WireShark or other packet sniffer.
e.g. we would be interested what block transfer parameters are agreed between client and server.
Please reply ASAP

**Comment by boaks** [comment]
Maybe you have a look at the examples (ASAP :-) ).

There is a `MessageTracer`, and you will easily find some hint to use in these examples.
For logging slf4j API is used and in the demo we use the logback implementation. 
So depending on the slf4j implementation your using, you need to setup the Logger included in `MessageTracer`.

**Comment by jas-singh14** [comment]
@boaks ,

Thanks for quick and precise response.
