### ISSUE TITLE
PKCS#11

### ISSUE THREAD

**Issue by fabienmifsud** [eclipse/californium#672]
Hi all,

Is that possible to use PKCS#11 with Scandium and Leshan ?

What are the entry points to configure it ?

Thank you !

**Comment by boaks** [comment]
Though PKCS#11 seems to cover a lot, I'm not sure, what the scope of your question is.

Scandium requires a private/public ecc key pair (Raw Public Key), or a private key and  a client certificate chain including the public key (X.509). As long as you can read any format and provide these data to scandium (see `DtlsConnectorConfig`), you should be able to use it. The `SslContextUtil` supports JKS, BKS, PKCS#12, if the java your using provides it. But if you read it on your own, you free to chose your format.

If you want to use none ECC keys, or your question targets to the support of HSM, then that function is not implemented.

**Comment by fabienmifsud** [comment]
Hi Achim,
Thx for the answer, I'm actually trying to connect a client with HSM. In that case, I have to fork scandium to implement it ? Or this is somewhere in your roadmap ?

**Comment by boaks** [comment]
HSM is, AFAIK, not on the roadmap. 
So ,yes please fork. 
If your able to contribute it back, this would be great :-).

**Comment by fabienmifsud** [comment]
Thx a lot
