### ISSUE TITLE
Unable to get block transfer notification in CoAP client OBSERVE

### ISSUE THREAD

**Issue by hirokiht** [eclipse/californium#676]
As shown in https://tools.ietf.org/html/rfc7959#section-3.4, BLOCK2 and OBSERVE should be able to work together. However, CoapHandler for the observation doesn't call onLoad nor onError when a block-transfer mode is used.

The log on the client shows:
`[CoapEndpoint-UDP-0.0.0.0/0.0.0.0:0#1] INFO org.eclipse.californium.core.network.Exchange - Exchange[L1] replace CON-GET    MID=48759, Token=[2a6d178af48fd6d5], OptionSet={"Uri-Host":"localhost", "Block2":"(szx=5/512, m=false, num=2)"}, no payload by CON-GET    MID=48757, Token=[0f720a6516651cc8], OptionSet={"Uri-Host":"localhost", "Observe":0}, no payload
[CoapEndpoint-UDP-0.0.0.0/0.0.0.0:0#1] INFO org.eclipse.californium.core.network.Exchange - Exchange[L1] replace CON-GET    MID=48757, Token=[0f720a6516651cc8], OptionSet={"Uri-Host":"localhost", "Observe":0}, no payload by CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Host":"localhost", "Block2":"(szx=5/512, m=false, num=2)"}, no payload`

I'm using californium-core version 2.0.0-M10.

**Comment by boaks** [comment]
The log indicates for me, that something is mixed up in the client. 
Can you provide us more information about your test setup?

**Comment by boaks** [comment]
You may use the PlugtestClient to see, that blockwise observes are working!
Without more details, I don't know, what's going wrong on your side.

**Comment by hirokiht** [comment]
Actually I found out the problem, I used eTags with different values, hence the payload is not perceived as the same one. It'd be nice to have some kind of error feedback but there's no problem otherwise. Once I fixed the eTag value, it works as expected.
