### ISSUE TITLE
Unable to get Californium coap-coap proxy to work

### ISSUE THREAD

**Issue by Raveesh** [eclipse/californium#678]
I am currently using californium 2.0.0-SNAPSHOT for testing coap based interactions with devices. 
The scenario is as follows: 
The coap client residing in the cloud sends a get observe request to the device and waits for data.
If I write a simple code to perform the GET OBSERVE, I get a valid response. 
```
Request request4 = Request.newGet();
        request4.setObserve();
        request4.setURI(args[1].trim());
        System.out.println("URI : "+args[1].trim());
        System.out.println("Option Set "+request4.getOptions().getUriPath());
        request4.send();
        Response response4 = request4.waitForResponse(20000);
        if(response4!=null)
            System.out.println(response4.getCode());  // prints 2.05
        else System.out.println("null :(");

```
We now introduced a forward proxy in the path of the GET OBSERVE so the scenario looks as follows:
The coap client in the cloud sends a OBSERVE request to the forward proxy (say a controller) by setting the Proxy-Uri option and keeps the endpoint URI as the same. However the request never reaches the controller / forward proxy. I am able to ping both the controller and the device , but for some reason, the request doesnt seem to hit the forward proxy. 

The code is as follows: 
```
System.out.println("Starting OBSERVE REQUEST .. WITHOUT CLEAR URI but with uri");
        Request request3 = Request.newGet();
        request3.setObserve();
        request3.getOptions().setProxyUri(args[0].trim());
        request3.setURI(args[1].trim());
        System.out.println("PROXY_URI : "+args[0].trim() );
        System.out.println("URI : "+args[1].trim());
        System.out.println("Option Set "+request3.getOptions().getUriPath());
        request3.send();
        Response response3 = request3.waitForResponse(20000);
        if(response3!=null)
            System.out.println(response3.getCode());
        else System.out.println("null :(");
```

Could you please let me know as to where I am making a mistake. and how I can make the coap proxy work. I have tried the arguments with both the hostname and ipv6 address and they both yield the same null response.

**Comment by sophokles73** [comment]
You need to put the URI on the origin server, i.e. the URI that you want to invoke via the proxy, into the *Proxy-Uri* option. The host name and port of the proxy itself need to go into the corresponding *Uri-Host* and *Uri-Port* options. See https://tools.ietf.org/html/rfc7252#section-5.7.2 and https://tools.ietf.org/html/rfc7252#section-5.10.2

**Comment by vikram919** [comment]
@Raveesh  as @sophokles73  mentioned 
```java
Request request3 = Request.newGet();
request3.setObserve();
request3.getOptions().setProxyUri(args[1].trim());
request3.setURI(args[0].trim());
```

just reverse those options, you used them in opposite way :-)

**Comment by boaks** [comment]
@Raveesh 

Does it work for you? If so, can we close this issue?

**Comment by Raveesh** [comment]
Thanks @boaks and @sophoklrs73 .. reversing the options worked for me . Please go ahead and close the issue 

Thanks for all the help
