### ISSUE TITLE
Support certificate validation via OCSP

### ISSUE THREAD

**Issue by wenzheng** [eclipse/californium#684]
Is it possible to support the OCSP online validation to a PKI system during the DTLS handshake process?

**Comment by sophokles73** [comment]
(Almost) everything is possible. However, Californium does not support OCSP validation yet and there are currently no plans to do so. Personally,I would be a little concerned about the latency involved. We already provide means to implement a (remote) key store for PSK keys and this already has a negative impact on the number of handshakes that can be performed in parallel.

**Comment by sbernard31** [comment]
I think you could implement this using the new API :  [`CertificateVerifier`](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/CertificateVerifier.java).

But @sophokles73 is right you could face some latency issue.

I ask to the netty project (https://github.com/netty/netty/issues/7862) as it seems they face the same issue. For OCSP it could be OK as it seems that _"The server fetches it out-of-band from the CA's OCSP responder server and caches it for up to the TTL that is configured in CA's response (I believe 10 days is the max)"_ (source : https://github.com/netty/netty/issues/7862#issuecomment-385809171)

I didn't read the OSCP spec and so can not validate this but it may worth to check that.

**Comment by wenzheng** [comment]
Thanks, I will take a look and try it out
