### ISSUE TITLE
CoAP-DTLS Secured Server is failing to send message under performance tests

### ISSUE THREAD

**Issue by vikram919** [eclipse/californium#696]
Server fails to send the message when the payload is 8275 Bytes, it works  fine when the payload is 7700 Bytes.
Attached the log file seen at server.
[debug.log](https://github.com/eclipse/californium/files/2183779/debug.log)

**Comment by sbernard31** [comment]
Your log seems to say that your `MAX_RESOURCE_BODY_SIZE=8192`.

According to the javadoc : 
```java
/**
 * The maximum size of a resource body (in bytes) that will be accepted
 * as the payload of a POST/PUT or the response to a GET request in a
 * <em>transparent</em> blockwise transfer.
 * <p>
 * This option serves as a safeguard against excessive memory
 * consumption when many resources contain large bodies that cannot be
 * transferred in a single CoAP message. This option has no impact on
 * *manually* managed blockwise transfers in which the blocks are
 * handled individually.
 * <p>
 * Note that this option does not prevent local clients or resource
 * implementations from sending large bodies as part of a request or
 * response to a peer.
 * <p>
 * The default value of this property is
 * {@link NetworkConfigDefaults#DEFAULT_MAX_RESOURCE_BODY_SIZE}.
 * <p>
 * A value of {@code 0} turns off transparent handling of blockwise
 * transfers altogether.
 */
public static final String MAX_RESOURCE_BODY_SIZE = "MAX_RESOURCE_BODY_SIZE";
```

Your log does not contains only log server right ? there is also client one ? (I see 4 endpoints created)

I also see : `requested resource body exceeds max buffer size [8192], aborting request` which should be a log raised at client side.

**Comment by vikram919** [comment]
> Your log does not contains only log server right ?

sorry for that, you are right, both server and client are running on my local machine hence the log is mixed up.

**Comment by vikram919** [comment]
@sbernard31 Thank you it worked now, after altering the parameter
