### ISSUE TITLE
Scandium DTLS - JDK10 interop issue

### ISSUE THREAD

**Issue by kiemlicz** [eclipse/californium#703]
## Overview
JDK10 client (`SSLEngine` based) with Scandium-M10 server doesn't finish the handshake (see attached file and screenshot below, packets marked with black come from server)
![screenshot_20180724_112615](https://user-images.githubusercontent.com/7331452/43129339-7de65e76-8f34-11e8-8d41-38f7a9e8c596.png)
[dtls_jdk.zip](https://github.com/eclipse/californium/files/2223144/dtls_jdk.zip)

## Details
The JDK10 `SSLEngine` remains in the `NEED_UNWRAP` state, meaning it still waits for handshake messages.  
However the `org/eclipse/californium/scandium/dtls/ServerHandshaker.java:321`  contains following check: `if (!clientAuthenticationRequired || getKeyExchangeAlgorithm() != KeyExchangeAlgorithm.EC_DIFFIE_HELLMAN)` that prevents the server from sending the `CHANGE_CIPHER_SPEC`

## Questions
Why such check is used and why is it named `clientAuthenticationRequired`?  
Isn't it the case that after `KEY_EXCHANGE` the server **must** wait (or process if already received) for `CHANGE_CIPHER_SPEC` **unconditionally**?
Setting `clientAuthenticationRequired=false` (by default it is set to `true`) 'fixes' this

Please advice further steps: is it bug in Scandium or expected behavior (if so please explain)

## Code
Used Scandium M10  
Code references from `2.0.x` branch
Some annotations lead to #186

**Comment by boaks** [comment]
Sorry, screenshots are close to useless! 
Please export the selected dtls messages an provide that exported capture

**Comment by vikram919** [comment]
> Setting clientAuthenticationRequired=false (by default it is set to true) 'fixes' this

This means by default DTLS scandium server is expecting CLIENT VERIFY message from client.
If the server doesn't expect it you need to configure using DtlsConfig by setting it to false.

**Comment by vikram919** [comment]
> Why such check is used and why is it named clientAuthenticationRequired?

It is a check to set the server Dtls handler to expect the next message from the client

**Comment by kiemlicz** [comment]
Thank you, I've somehow missed that upon `CERTIFICATE_VERIFY` the `expectChangeCipherSpecMessage()` is also called.

After some more [reading](https://tools.ietf.org/html/rfc5246#section-7.3)
```
If the client has sent
   a certificate with signing ability, a digitally-signed
   CertificateVerify message is sent to explicitly verify possession of
   the private key in the certificate.
```

Yes it means that `CERTIFICATE_VERIFY` is mandatory when certificate doesn't contain DH params.
So why does the check is not like that:
```
if (!clientAuthenticationRequired || getKeyExchangeAlgorithm() == KeyExchangeAlgorithm.EC_DIFFIE_HELLMAN) {
  //certificate doesn't have signing ability, no CERTIFICATE_VERIFY expected, expect CHANGE_CIPHER_SPEC
  expectChangeCipherSpecMessage();
}
```

Moreover why `clientAuthenticationRequired` is configurable when it is clear when to expect `CERTIFICATE_VERIFY`?

**Comment by vikram919** [comment]
After closely looking into Certificate message sent by client the Certificates length is 0, as per [spec](https://tools.ietf.org/html/rfc5246#section-7.4.6)

> If the client does not send any certificates, the server MAY at its discretion either continue the handshake without client authentication, or respond with a fatal handshake_failure alert.

This is a correction on Scandium server because the server continue handshake without throwing fatal alert.

**Comment by vikram919** [comment]
> Moreover why clientAuthenticationRequired is configurable when it is clear when to expect CERTIFICATE_VERIFY?

Scandium server does not continue handshake since there are no certificates sent by client for authentication,  `clientAuthenticationRequired` option on server side provides configurability on server side to proceed with handshake protocol as per TLS 1.2 even if client does not provide certificate.

**Comment by boaks** [comment]
Maybe, you first decide, what you want:

1. no client certificate: client ensures to talk to the server, but server doesn't really know, which client sends the data.
2. with client certificate, both sides can trust each other.

For 1., as @vikram919 already mentioned, just set the "setClientAuthenticationRequired"
in `DtlsConnectorConfig.Builder` to `false`, which overwrites the default `true`.

For 2- provide the `KeyManager` with the client certificate-chain to the SslEngine (J10).

I used option 2 and java 9 and it worked for me.

**Comment by boaks** [comment]
So the question is:
1. Should the handshake be successful, because both comply to DTLS?
2. Should the error handling be improved, by validating the messages more deeply and then sending alerts.

FMPOV, I would start with 1.

**Comment by boaks** [comment]
I think, the Java 10 behaviour is based on the different functions:

```
sslEngine.setWantClientAuth(true);
sslEngine.setNeedClientAuth(true);

```

I guess, the first is request and accept 0,
the second one is request and fail.

That will comply to https://tools.ietf.org/html/rfc5246#section-7.4.6 

@kiemlicz 
Do you want  to setup the stuff that it is working **now**, or do you want to wait until scandium get's extended to the want/need approach?

**Comment by kiemlicz** [comment]
Thank you for replies.
The root cause was lack of Certificate after `CERTIFICATE_REQUEST`, thank you @vikram919   
Properly configuring KeyManager yields the `CERTIFICATE_VERIFY` from the jdk10 client side.
It was purely implementation bug  

> Should the handshake be successful, because both comply to DTLS?

As you say, Scandium DTLS server tries to accept the zero length certificate.   
But it doesn't continue the handshake omitting client authentication (it still waits for `CERTIFICATE_VERIFY` that is not sent by the JDK).  
Thus I don't know if they both comply to DTLS (either JDK doesn't send `CERTIFICATE_VERIFY` when it couldn't find matching certificate or scandium doesn't continue without client auth)

The JDK10 DTLS server approach with explicit [want](https://docs.oracle.com/javase/10/docs/api/javax/net/ssl/SSLEngine.html#setWantClientAuth(boolean))/[need](https://docs.oracle.com/javase/10/docs/api/javax/net/ssl/SSLEngine.html#setNeedClientAuth(boolean)) client auth seems more comprehensible and explicit to me.

**Comment by sbernard31** [comment]
If we don't change the Scandium API, I agree with @vikram919 

> If client does not provide certificate, and server does not want to continue handshake, server should throw fatal alert, so the client can understand what is the problem?

If we want to make enhance API behavior, [here](https://golang.org/pkg/crypto/tls/#ClientAuthType) is the GO example.

```go
type ClientAuthType int

const (
        NoClientCert ClientAuthType = iota
        RequestClientCert
        RequireAnyClientCert
        VerifyClientCertIfGiven
        RequireAndVerifyClientCert
)
```

**Comment by boaks** [comment]
if still interested in this issue, you may check PR #823.

**Comment by boaks** [comment]
Don't hesitate to add a new comment or open a new issue, when you have new information for us.
