### ISSUE TITLE
LeastRecentlyUsedCache behavior.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#707]
Currently, the LeastRecentlyUsedCache behave like this :

**Javadoc:**
An in-memory cache with a maximum capacity and support for evicting stale entries based on an LRU policy. 
The cache keeps track of the values' last-access time automatically. Every time a value is read from or put to the store, the access-time is updated. 
A value can be successfully added to the cache if any of the following conditions is met: 
	- The cache's remaining capacity is greater than zero. 
	- The cache contains at least one stale entry, i.e. an entry that has not been accessed for at least the cache's expiration threshold period. In such a case the least- recently accessed stale entry gets evicted from the cache to make place for the new value to be 
	 added. 
**For the get :**
If the cache contains the key but the value is stale the entry is removed from the cache.

**Meaning**
So this means that after `threshold` seconds of inactivity and even if the element is still in the store,  it will be considered as absent.

**Should we change this ?**
In californium does it make sense to remove element on get ?
I mean why not using this data if we keep it in memory all this time.
Maybe we could consider `threshold` as a warranty that the entry can not be removed during this time but not as lifetime. 

By the way,  I believe the `find` method seems to not remove stale entries.

**Current usage of  LeastRecentlyUsedCache:**
- DTLS connection
- Message ID
- transparent blockwise transfer data

WDYT ?

**Comment by boaks** [comment]
In #617 the idea is to remove a even recently used DTLS session (based on a other timeout).
For me this is somehow "running in circles" :-). 
The ideas seems to be triggered by issue 
https://github.com/eclipse/leshan/issues/542
but I'm not sure, what the "common expected" functionality should be for LRU-cache.

My guess is, a standard component was copied and adjusted for the special purpose (without adjusting the documentation) and the `find` was then added completely "out of scope" (it doesn't update the usage timestamp).
If the above change should really be implemented, I would prefer to have it moved into a own implementation with correct documentation.

**Comment by sbernard31** [comment]
#617 is something else it is about a maximum session(connection?) lifetime.

Could we agree first about the behavior we would like then see how we could implement this ?

**Comment by boaks** [comment]
Let me split it into two parts:

For short term:
We had already a short discussion in #343 about the stale dtls sessions. I'm OK with a get(), which doesn't apply "expired". I have overseen that usage. When I was switching from currentTimeMillis to nanoTime, I got aware, that get() uses the expire-timespan, and put() the expire-timepoint for stale(). With 600s and currentTimeMillis, get() never expired. With the documentation in mind, which states to expire the get(), I "fixed" it. But I wasn't really aware, that this also violates #343. So I would prefer to either provide an additional get() or an parameter to select the behavior or to clone and move the implementation.

Long term:
I'm not really convinced, that a a short "stale time" used for stale dtls handshakes is a good solution.
Especially for https://github.com/eclipse/leshan/issues/542 the pings will not update the last usage time and so, in shortage of cache entries, these elements will be removed. But I don't plan to invest time into that for the next months.

**Comment by sbernard31** [comment]
> Especially for eclipse/leshan#542 the pings will not update the last usage time and so, in shortage of cache entries, these elements will be removed.

I think the ping must not update the last usage time, as in the case of https://github.com/eclipse/leshan/issues/542 the ping is not a valid DTLS message.

**Comment by boaks** [comment]
> I think the ping must not update the last usage time

I didn't wrote, that the ping should update the last usage time. I just wrote, that with that behavior, the ping clients are in danger of being removed from the cache, if other clients are try to establish a DTLS session.

The pitfall here is, that even trying clients (which may not have the proper credentials) would evict valid ping clients. That's why I think, stale DTLS handshakes should be treated different from stale DTLS sessions.

**Comment by boaks** [comment]
@sbernard31 

the changes, which caused the different behavior are reverted in the meantime.
Could you please consider to close this issue?

**Comment by sbernard31** [comment]
Fixed in Cf 2.0.0-M12 (confirmed by @bernhard-seifert at https://github.com/eclipse/leshan/issues/542#issuecomment-423326655)
