### ISSUE TITLE
Make DTLSSession.getMasterSecret publicly accessible 

### ISSUE THREAD

**Issue by lhotari** [eclipse/californium#715]
Change request:
Make it possible to extract the master secret from a DTLSSession.

Use case:
Wireshark supports decrypting DTLS traffic. It can decrypt a single PSK or all DTLS traffic as long as a log file of the TLS session IDs and session master keys are provided. Making DTLSSession.getMasterSecret accessible will make it possible to create a solution for making a Wireshark compatible log file for decrypting DTLS traffic. 

 In the described use case, DTLSSession.getMasterSecret would be used for example in this way:

```
public class KeyLoggingSessionCache implements SessionCache {
...
    public void put(DTLSSession session) {
        logDTLSMasterKey(session);
    }

    // Log key in format readable by Wireshark
    // https://github.com/boundary/wireshark/blob/07eade81/epan/dissectors/packet-ssl-utils.c#L4170-L4175
    private void logDTLSMasterKey(DTLSSession session) {
        byte[] masterKeyBytes = session.getMasterSecret();
        if (masterKeyBytes != null) {
            String sessionKey = Hex.encodeHexString(session.getSessionIdentifier().getId());
            String masterKey = Hex.encodeHexString(masterKeyBytes);
            keyLogWriter.println("RSA Session-ID:" + sessionKey + " Master-Key:" + masterKey);
        }
    }
....
```
I have experimented with this solution. I currently need to use reflection for extracting the session master key.

**Comment by boaks** [comment]
In branch 2.0.x it's public available via the `SessionTicket`

```
DTLSSession.getSessionTicket().getMasterSecret();
```

hope it work for you.

**Comment by lhotari** [comment]
@boaks Thanks. I wasn't aware of that. I'll close this issue since no change is needed.
