### ISSUE TITLE
Make it possible to register SessionListener instances in a custom subclass of DTLSConnector

### ISSUE THREAD

**Issue by lhotari** [eclipse/californium#716]
Currently it's not possible to make use of the `org.eclipse.californium.scandium.dtls.SessionListener` interface for custom purposes. 

My usecase is about having custom logging (to a custom logging solution) when a DTLS handshake fails. 
The `SessionListener` has `handshakeFailed` callback which suits my usecase. The problem is that DTLSConnector doesn't have a way to register custom `SessionListener` instances to new Handshaker instances. 

I'd be happy with a solution that requires subclassing DTLSConnector. For example adding this kind of method would be helpful:
```
   protected void handshakeInitialized(final Handshaker handshaker) {

   }
```
 This method would be called where there is currently calls to `addSessionCacheSynchronization(handshaker)`. I guess the code could be refactored to take care of both, adding a new method `initializeHandshake` which calls `addSessionCacheSynchronization` and `handshakeInitialized` and replacing the calls to `addSessionCacheSynchronization` by calls to `initializeHandshake`. Maybe this proposal isn't useful and there are better ways. I'm just trying to lower the barrier for getting the change done so that it would be possible to register custom SessionListener instances...

**Comment by boaks** [comment]
Please, check if the merged PR fits your requirements and close this issue, if so.

**Comment by lhotari** [comment]
Thanks @boaks , good work. I'm happy with the changes.

**Comment by boaks** [comment]
@lhotari 

That's long time ago. I'm not sure, if you still use it.
If so, could you check, if PR #1869 works for you as well? 
Then I would deprecate to old way (`onInitializeHandshaker`) and remove it in  4.0 :-).

**Comment by lhotari** [comment]
> @lhotari 
> 
> That's long time ago. I'm not sure, if you still use it.
> If so, could you check, if PR #1869 works for you as well? 
> Then I would deprecate to old way (`onInitializeHandshaker`) and remove it in  4.0 :-).

#1869 looks great. Thank you @boaks .
