### ISSUE TITLE
Make it possible to provide custom `ResumptionSupportingConnectionStore` in DTLSConnector

### ISSUE THREAD

**Issue by lhotari** [eclipse/californium#717]
Currently DTLSConnector can only use the `InMemoryConnectionStore` although an interface `ResumptionSupportingConnectionStore` exists. 

The constructor `DTLSConnector(final DtlsConnectorConfig configuration, final ResumptionSupportingConnectionStore connectionStore)` is using default access so a custom subclass cannot call it (it would have to be protected or public in this case). Besides this issue there is an assumption in that construct that `ResumptionSupportingConnectionStore` also implements `SessionListener`. Maybe `ResumptionSupportingConnectionStore` should extend `SessionListener` to make that explicit. 

I'd be happy with a protected constructor that would require subclassing DTLSConnector in order to use a custom `ResumptionSupportingConnectionStore` implementation.

**Comment by boaks** [comment]
Change 

```
DTLSConnector(final DtlsConnectorConfig configuration, final ResumptionSupportingConnectionStore connectionStore)
```

from `package` scope to `protected`?
You aware of the API change of PR #713 (added removes variants)?
We will see, if someone had a intention to use that scope, but principally it would be OK for me to change the scope.

**Comment by lhotari** [comment]
yes `protected` would be ok so that DTLSConnector subclasses could call it.

Besides that it would also be good to resolve the current assumption that connectionStore implements `SessionListener` ([in DTLSConnector constructor](https://github.com/eclipse/californium/blob/23ceec42/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L273)). Do you have a solution for that?

API changes in PR #713 look fine to me.

**Comment by boaks** [comment]
Please, check if the merged PR fits your requirements and close this issue, if so.

**Comment by lhotari** [comment]
thanks @boaks , great work. This fits my requirements.
