### ISSUE TITLE
CoAP over TCP leaks exchanges

### ISSUE THREAD

**Issue by joemag1** [eclipse/californium#72]
With switching to CoAP over TCP we no longer close outgoing exchanges that never receive any response. This is because in the past reliability layer + deduplicator were performing this function, and TCP stack no longer uses those.

This has two impacts:

1) Clients using async invocation never get called back
2) TcpMatcher will slowly accumulate old exchanges in its map.

To solve, likely need to introduce a TCP version of reliability layer to close expired exchanges.

**Comment by joemag1** [comment]
I will take this one and submit a patch in the next few days.

**Comment by boaks** [comment]
@joemag1 

Is this issue still open?

**Comment by boaks** [comment]
If this issue still occurs, don't hesitate to reopen this issue or create a new one.
