### ISSUE TITLE
getDestinationContext return null

### ISSUE THREAD

**Issue by auxor** [eclipse/californium#729]
# Please providing basic issue information
I use the following release:
org.eclipse.californium:californium-core:2.0.0-M11

My code is following:
`            
           Gson gson = new Gson();
            CoapClient coapClient = new CoapClient("coap://" + addr + "/" + path);
            if (isCon) {
                coapClient.useCONs();
            } else {
                coapClient.useNONs();
            }
            String reqStr = gson.toJson(r);
            LogUtil.d(TAG, "%s, request %s", coapClient.getURI(), reqStr);
            CoapResponse response = coapClient.post(reqStr,
                    MediaTypeRegistry.APPLICATION_JSON);
            if (response == null || !response.isSuccess()) {
                throw new RuntimeException("response failed");
            }
            LogUtil.d(TAG, "%s, response %s", coapClient.getURI(), response.getResponseText());

            Rsp rsp = gson.fromJson(response.getResponseText() ,c);
            if (response.advanced().getDestinationContext() != null) {
                rsp.peerIp = response.advanced().getDestinationContext().getPeerAddress().toString();
                LogUtil.d(TAG, "%s, peer ip %s,", coapClient.getURI(), rsp.peerIp);
            } else {
                LogUtil.d(TAG, "getDestinationContext null");
            }
            return rsp;
`
The response text is correct. But the getDestinationContext return null, so I cannot get the peer address.

**Comment by boaks** [comment]
Though the response is received, the "destination " would be the receiving peer.
I guess, you want the "source" of the response, so try `getSourceContext()`.

**Comment by auxor** [comment]
@boaks You are right. getSourceContext() works for me.
