### ISSUE TITLE
Small possibility of Exchange leak when receiving non-piggybacked responses

### ISSUE THREAD

**Issue by joemag1** [eclipse/californium#73]
Repro steps:

1) Client sends a CON request
2) Server calls exchange.acknowledge(), but then never sends a response, either due to a bug, or because server crashed.
3) The exchange on the client side never times out.

This has two undersired effects:

If client used CoapClient.(put|get|delete|post) variant with CoapHandler, then neither onLoad() nor onError() methods are ever called. Furthermore, the offending exchange is never removed from Matcher's tracking maps.

Potential solution: have one of CoapStack layers add a task that will fire after EXCHANGE_LIFETIME and call Exchange.timeout() if Exchange is still incomplete.

**Comment by joemag1** [comment]
This is a more generic problem of https://github.com/eclipse/californium/issues/72

It just so happen in TCP mode every request is hit by this issue because there are no ACKs in TCP land.

**Comment by boaks** [comment]
@joemag1 

Is this issue still open?

**Comment by boaks** [comment]
If this issue still occurs, don't hesitate to reopen this issue or create a new one.
