### ISSUE TITLE
CoCoA Congestion Control not working for Server

### ISSUE THREAD

**Issue by samkumar** [eclipse/californium#736]
I am working with the latest version (2.0.0-M11), but I experience similar issues with version 1.0.6.

I am using CoAP in the following scenario: a client repeatedly sends data to a server using POST messages, and the server responds with the return code 2.04 CHANGED (this response is just to conform to REST; we could also just replace it with a CoAP ACK).

This is the base server implementation, and it works fine:

```
import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.CoapServer;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.core.server.resources.CoapExchange;

public class Main {
	public static void main(String[] args) {
		CoapServer server = new CoapServer();
		server.add(new CoapResource("anemometer") {
			@Override
			public void handlePOST(CoapExchange exchange) {
				System.out.printf("Got a message of size %d\n", exchange.getRequestPayload().length);
				exchange.respond(CoAP.ResponseCode.CHANGED);
			}
		});
		server.start();
	}
}
```

I have tried to add CoCoA congestion control to this setup. The client (which is using Contiki's Erbium implementation of CoAP) seems to be behaving normally when I use the server above, even when I enable CoCoA on the client. However, I also tried enabling CoCoA on the server, using the following code:
```
import org.eclipse.californium.core.CoapResource;
import org.eclipse.californium.core.CoapServer;
import org.eclipse.californium.core.coap.CoAP;
import org.eclipse.californium.core.network.config.NetworkConfig;
import org.eclipse.californium.core.network.stack.congestioncontrol.Cocoa;
import org.eclipse.californium.core.server.resources.CoapExchange;

public class Main {
	public static void main(String[] args) {
		NetworkConfig config = new NetworkConfig();
		config = config.setBoolean(NetworkConfig.Keys.USE_CONGESTION_CONTROL, true);
		config = config.setString(NetworkConfig.Keys.CONGESTION_CONTROL_ALGORITHM, Cocoa.class.getSimpleName());
		CoapServer server = new CoapServer(config);
		server.add(new CoapResource("anemometer") {
			@Override
			public void handlePOST(CoapExchange exchange) {
				System.out.printf("Got a message of size %d\n", exchange.getRequestPayload().length);
				exchange.respond(CoAP.ResponseCode.CHANGED);
			}
		});
		server.start();
	}
}
```

Once I enable CoCoA on the server, the setup totally breaks. Here are PCAP files, for both implementations of the server (with and without CoCoA): [captures.zip](https://github.com/eclipse/californium/files/2326314/captures.zip)

I'll point out some problems I can see in the capture file:
1. Upon receiving the first CoAP POST message, no ACK was sent out. The ACK was only sent out when the POST was retransmitted after 2.14 seconds.
2. When the second POST message arrived, the ACK was not sent, though the response was sent as a confirmable message (there's no good reason I can think of why this cannot be piggybacked with the ACK)
3. The whole server just hangs after five attempts at transmitting the response, and stops ACKing or responding to future requests.

The server behaves similarly if I use v1.0.6 instead of v2.0.0-M11. I have also seen the server throw `NullPointerExceptions` in v1.0.6.

One question I have is whether I actually need to enable CoCoA in the server? The server isn't sending large amounts of data to the client; in fact, every message it sends should be piggybacked with an ACK. I wonder whether the reason I am seeing these strange errors is that CoCoA is meant only for use with CoAP clients, not with CoAP servers... it would be nice if someone more knowledgeable about CoCoA could clarify this.

**Comment by samkumar** [comment]
As a side note, is there any way to just send a CoAP ACK in reponse to a request, without sending a full response? If I remove the `exchange.respond` line, then CoAP ACKs are not sent, even without CoCoA, causing the client to repeatedly retransmit the request...

**Comment by boaks** [comment]
> As a side note, is there any way to just send a CoAP ACK in reponse to a request, without sending a full response?

For CoAP RFC7252, any request wait's for a response. You may send a separate ACK before the response, but only ACK without response is not RFC 7252. Californium's state-machine is not implemented for ACK only (as it is not RFC 7252 :-) ).

**Comment by boaks** [comment]
> Once I enable CoCoA on the server, the setup totally breaks. 

Unfortunately, all congestion control implementations in californium are full of threading and synchronization issues. I personally will not be able to spend my time in fixing this "in time", but maybe some else will be able to spend time into it.

**Comment by boaks** [comment]
Yes, a separate response is sure supported, therefore I wrote

> You may send a separate ACK before the response, but only ACK without response is not RFC 7252.

In californium you may either use `CoapExchange.accept()` or `Exchange.sendAccept()` before the `resond`.

> I'll leave it up to you whether to keep this issue open.

In my head/brain it's open now from more than two years :-). 
But though it's not that widespread used, I didn't start to sort it out. Threading is always very hard, and we sorted out the threading issues for the Exchange and DTLS and so it's mainly the question, on which issue we can spend time ...

**Comment by samkumar** [comment]
Sorry, I misunderstood what you said earlier. Thanks for the clarification!

**Comment by boaks** [comment]
I spent some time in redesign the implementation.

In my considerations there is a lot of stuff to be defined and tested.

What should work now, is that NSTART-x may be used to queue requests. I would do that only for very short periods (<10s), though there are no means to manage these queues.

The RTO optimization may depend very much on the use-case. In my experience, the RTT as base for the RTO depends on many factors and so I'm not sure, if a dynamic RTO based on that will show benefits.

Anyway, with PR #1597, this issue will be closed.
