### ISSUE TITLE
Tips for making an request to an broadcast address.

### ISSUE THREAD

**Issue by auxor** [eclipse/californium#741]
This is not an issue, just for recording tips which may help someone. It's not defined in rfc and is not recommended.

I am using 2.0.0-M11. By default, californium can not handle response after making an request to an broadcast address. Because of the following reasons:

1. The request's destination address is a broadcast address (like 192.168.1.255), but the response's address is an real address(like 192.168.1.4).  The response will be discard by [isResponseRelatedToRequest](https://github.com/eclipse/californium/blob/984cbaea63996c66d1d5adb2d27fb2b2ea41bed1/element-connector/src/main/java/org/eclipse/californium/elements/UdpEndpointContextMatcher.java#L68)
2. If you have start an sever, the server will receive the broadcast request too, and response an 4.04. 

With the following changes, you will get correct response after making an request to an broadcast address. (Note, only the first response will be handled)

1. Create an your endpoint, and set response matching to relexed. Then it will discard any response.
`        NetworkConfig config = NetworkConfig.getStandard();
        config.setString(NetworkConfig.Keys.RESPONSE_MATCHING, "RELAXED");
`
2. If you have start an server, custom an ServerMessageDeliverer and override preDeliverRequest. Then the server will not response to itself.
`
protected boolean preDeliverRequest(final Exchange exchange) {
        if (exchange != null ) {
            Request request = exchange.getRequest();
            if (request.getSourceContext() != null) {
                String sourceAddr = request.getSourceContext().getPeerAddress().getHostName();
                if ("YOUR LOCAL ADDRESS".equals(sourceAddr)) {
                    return true;
                }
            }
        }
        return false;
 }
`

**Comment by auxor** [comment]
Just for recording tips.

**Comment by boaks** [comment]
You may be also faced some MID/deduplication issues.
And it mainly works in a intranet and not in the internet :-).

Vikram919 has made some basic extensions to solve that MID issues, but currently I didn't find the time to integrate his solution into californium. It would also require a review, and currently we have also a bottleneck at the reviews. So I'm not sure, when we can provide a 2.0, which will be able to do multicast/broadcast.

**Comment by auxor** [comment]
In hope of that.

**Comment by boaks** [comment]
If interested, check PR #742.

**Comment by boaks** [comment]
Fixed with merge of #742

**Comment by boaks** [comment]
Thanks for your feedback.
