### ISSUE TITLE
X509v3 keyusage mandatory ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#748]
Currently in Scandium, `X509v3 keyusage` is mandatory for some type of certificate.
I mean if the certificate does not include this extension with the `digitalSignature` value there is no way to do an handshake.

(see [CertificateRequest#isSupportedKeyType](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/CertificateRequest.java#L437))

I don't know if this is the right behavior ? 
I can not find any clear answer but I would say that if the X509v3 usage is present we should check that digitalSignature is present but if the extension is not present we could accept the certificate.

The [Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile](https://tools.ietf.org/html/rfc5280#section-4.2.1.3) says :
_"The key usage extension defines the purpose (e.g., encipherment,
   signature, certificate signing) of the key contained in the
   certificate.The usage restriction might be employed when a key that
   could be used for more than one operation is to be restricted..."_

**Comment by sbernard31** [comment]
To be totally honest, I face this "issue" creating a certificate with simple openssl command.
I also see that certificates (which was not created by me) in leshan-integration-test don't have any `keyusage` extension.

So this makes me search if this is normal that scandium does not accept this kid of certificate.

**Comment by boaks** [comment]
These extensions are available for openssl

https://access.redhat.com/solutions/28965

But, if you prefer to investigate, if they are really proper used, don't hesitate to do so.
May be the "extended key usage" should be also considered, and/or a method is added to the `CertificateVerifier` which checks the "meetsSigningRequirements".

**Comment by sbernard31** [comment]
Thx @boaks, I already found a way to add this kind of extension using openssl. :)
I just explained how I came to this question.

Searching I found this : https://stackoverflow.com/questions/15353595/is-it-mandatory-to-have-keyusage-in-certificate-if-using-jdk7/18071857#18071857
Which seems to go in a way that this should be present but not mandatory.

I thing checking only if the extension is present could make sense. Especially in case where you are using [`domain-issued certificate`](https://tools.ietf.org/html/rfc6698#section-2.1.1) which is [the only supported case in LWM2M 1.0.](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/187)

But clearly  this question is not a critical or urgent one.

**Comment by sbernard31** [comment]
(I would like to keep this issue open for now as I want to investigate this a bit more)

**Comment by sbernard31** [comment]
In `CertificateRequest`, I change the line like this : 
```java
boolean meetsSigningRequirements = !type.requiresSigningCapability() ||
                      (type.requiresSigningCapability() && 
                                 (cert.getKeyUsage() == null || cert.getKeyUsage()[0]));
```
As expected, the handshake succeed as the check is only done at client side. (This is the client which stop the handshake thinking that its certificate will not be accepted, but currently the server accept it)

FMOV, we should integrate this "fix" as the spec seems to say that this extension is optional and see later if we want to add some constraint about `keyusage` and `extendedKeyUsage`?

**Comment by boaks** [comment]
OK.

**Comment by sbernard31** [comment]
I pushed this fix in 2.0.x
We can just close this issue or keep it open if we want to trace the `keyusage` feature.

**Comment by sbernard31** [comment]
I remove my commit from master as I missed that it breaks 1 test.
I pushed a PR with test fixed : #753

**Comment by sbernard31** [comment]
The fix is pushed again in 2.0.x. (#753)

> We can just close this issue or keep it open if we want to trace the keyusage feature.

**Comment by boaks** [comment]
I stumbled over

https://github.com/wolfSSL/wolfssl/blob/master/src/ssl.c#L4101

Seems, that the key usage is more important for CA then for the server- or client-certificate.

**Comment by sbernard31** [comment]
Another recent thread about this : http://ietf.10.n7.nabble.com/Certificate-keyUsage-enforcement-question-new-in-RFC8446-Appendix-E-8-tp577849p578071.html
