### ISSUE TITLE
2.0.0-M12 is released

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#755]
Includes a couple of fixes and enhancements.

**Comment by yemkay** [comment]
Where can we find release information? I'm upgrading from M10 to M12 and would like to see the changes done in M11 and M12. 

Thanks for your time!!

**Comment by boaks** [comment]
Unfortunately we don't have release information. The main work was bug fixing, smaller DTLS extensions, and a redesign of the multi-threading execution. The experience from others was, that the update was not too hard and could be done even without "migration instructions". 

So, just try it.

In some cases "bug fixes" may/have affect/ed "none compliant" stuff. If you feel, something has changed and stops your solution from working, don't hesitate to report it in a new issue. If possible, we may then include "backward switch".

**Comment by boaks** [comment]
Maybe you consider to try (also?) the current 2.0.x-SNAPSHOT.
It comes with some more bug fixes.
I hope we can release it soon as M13.

**Comment by boaks** [comment]
2.0.0-M13 is released!
