### ISSUE TITLE
Scandium support for TLS 1.3 and ed25519 curves

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#762]
Is there a plan to support TLS 1.3 in Scandium?

If so, will there be support for the ed25519 curves for public key-based handshakes?

(Note that ed25519 support is recommended  in TLS 1.3).

**Comment by sbernard31** [comment]
As far as I know, not at short or midterm.

**Comment by boaks** [comment]
I'm not sure, if vikram could spend time into the ed25519 curves (see issue #595), but except from him, I don't know someone, who is working on that issues and willing to contribute his work (in align with the ECA rules).

**Comment by boaks** [comment]
X25519 with java 11 is already supported, and PR #1395 adds EdDSA.

(For (D)TLS 1.3 I still don't plan to add this in the next time.)

**Comment by boaks** [comment]
I don't expect contribution for DTLS 1.3 "soon".
