### ISSUE TITLE
Duplicate files in deplyed Jars - jfxmobile-plugin

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/californium#770]
When using californium in an [jfxmobile-plugin](http://docs.gluonhq.com/javafxports/) environment (e.g., on Android) the gradle process fails with the following message

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apkDebug'.
> com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK edl-v10.html
        File 1: C:\Users\<user>\.gradle\caches\modules-2\files-2.1\org.eclipse.californium\californium-core\2.0.0-M12\5b61477cf0f3634bbdf786b265178b7a50a07ae3\californium-core-2.0.0-M12.jar
        File 2: C:\Users\<user>\.gradle\caches\modules-2\files-2.1\org.eclipse.californium\californium-core\2.0.0-M12\5b61477cf0f3634bbdf786b265178b7a50a07ae3\californium-core-2.0.0-M12.jar
```
The reason seems to be that both `element-connector-2.0.0-M12.jar` and `californium-core-2.0.0-M12.jar` contain basic html files in the root (e.g., about.html, edl-v10.html, ...).

Removing those html files in one of the Jars makes the gradle build succeed.

Californium version in use is 2.0.0-M12 but this issue was already the case for 2.0.0-M9 and probably earlier.

Does it make sense to
* remove those html files from the jar _or_
* put them in a package _or_
* name them differently?

I think I run into a similar issue with Java9+ where files need to be unique also.

Hope this helps and thanks for your feedback!

**Comment by sbernard31** [comment]
>Does it make sense to
>    remove those html files from the jar or

Those files are about license. Removing it will not avoid californium or element-connector to work. But we need it for legal purpose.

>    put them in a package or

I believe this is a common practice to put license in jar root folder.

>    name them differently?

It sounds strange to have different name from one jar to another.

I have no experience with gradle but after looking at this error on the web, it sounds a common issue.
https://stackoverflow.com/questions/37428636/com-android-builder-packaging-duplicatefileexception-duplicate-files-copied-in

We have an android demo which are using Graddle you should have a look at the [build.gradle](https://github.com/eclipse/californium/blob/2.0.x/demo-apps/cf-android/app/build.gradle).

**Comment by danielpeintner** [comment]
Thanks for your feedback!

It seems best to use `packagingOptions` such as:

```
packagingOptions {
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/maven
}
```

**Comment by boaks** [comment]
> It seems best to use

Californium offers also a android demo app (see demo-apps/cf-android). In the apps gradle (app/build.gradle) 

```
    packagingOptions {
        pickFirst 'about.html'
        pickFirst 'edl-v10.html'
        pickFirst 'epl-v10.html'
        pickFirst 'notice.html'
        pickFirst 'META-INF/INDEX.LIST'
        pickFirst 'META-INF/LICENSE'
        pickFirst 'META-INF/io.netty.versions.properties'
        pickFirst 'LICENSE-2.0.txt'
        exclude   '**/*.jks'
    }
```

`pickFirst` is used to keep the license infos once.
