### ISSUE TITLE
How to set Notification to support ACK-CON

### ISSUE THREAD

**Issue by iot-cloud** [eclipse/californium#772]
# Please providing basic issue information

Issues may be answered much faster, if you provide more details ahead!

* branch your faced the issue. Currently 
   * 1.0 is the release, 
   * 1.1 is the master, 
   * and 2.0 is the development branch Yes - currently support in the Leshan 1.0.0-M9
* If you use a SNAPSHOT, ensure your updated to the latest. Please provide the
  commit your using
* If your issue is related to your own snippet, please provide that
* If you have logs, please provide them
* If you have tcpdump captures (wireshark), please provide them.

Thank in advanced. Regards, Henry

Issue in regarding Notification with ACK-CON, currently by default both Leshan and Californium support ACK-NON when the Notification is sent by the Client Application, mostly Firmware.

The currently logic is embedded in the ObserveLayer.java. Please provide some guidance to access to the ObserveLayer from Leshan.

Please help me to understand what the meaning of the following:
// By default use NON, but do not override resource
// decision

	@Override
	public void sendResponse(final Exchange exchange, final Response response) {

		final ObserveRelation relation = exchange.getRelation();
		if (relation != null && relation.isEstablished()) {

			if (exchange.getRequest().isAcknowledged() || exchange.getRequest().getType() == Type.NON) {
				// Transmit errors as CON
				if (!ResponseCode.isSuccess(response.getCode())) {
					LOGGER.debug("response has error code {} and must be sent as CON", response.getCode());
					response.setType(Type.CON);
					relation.cancel();
				} else {
					// Make sure that every now and than a CON is mixed within
					if (relation.check()) {
						LOGGER.debug("observe relation check requires the notification to be sent as CON");
						response.setType(Type.CON);
					} else {
						// By default use NON, but do not override resource
						// decision
						if (response.getType() == null) {
							response.setType(Type.CON);
							//HNG - temporary -- response.setType(Type.NON);
						}
					}
				}
			}

			/*
			 * Only one Confirmable message is allowed to be in transit. A CON
			 * is in transit as long as it has not been acknowledged, rejected,
			 * or timed out. All further notifications are postponed here. If a
			 * former CON is acknowledged or timeouts, it starts the freshest
			 * notification (In case of a timeout, it keeps the retransmission
			 * counter). When a fresh/younger notification arrives but must be
			 * postponed we forget any former notification.
			 */
			if (response.getType() == Type.CON) {
				prepareSelfReplacement(exchange, response);
			}

			// The decision whether to postpone this notification or not and the
			// decision which notification is the freshest to send next must be
			// synchronized
			Response current = relation.getCurrentControlNotification();
			if (current != null && isInTransit(current)) {
				LOGGER.debug("a former notification is still in transit. Postponing {}", response);
				relation.setNextControlNotification(response);
				// do not send now
				return;
			} else {
				relation.setCurrentControlNotification(response);
				relation.setNextControlNotification(null);
			}

			/*
			 * The matcher must be able to find the NON notifications to remove
			 * them from the exchangesByMID hashmap
			 */
			if (response.getType() == Type.NON) {
				relation.addNotification(response);
			}

		} // else no observe was requested or the resource does not allow it
		lower().sendResponse(exchange, response);
	}

**Comment by sbernard31** [comment]
Just in case you missed my response about that : https://github.com/eclipse/leshan/issues/564

// By default use NON, but do not override resource
// decision

This means that the behavior I explained in https://github.com/eclipse/leshan/issues/564 is only applied if the CoapResource does not set a response type (in Handle*)

**Comment by boaks** [comment]
Maybe, instead of asking details about the implementation, you can give us a idea of what you want to achieve?

In my experience, RFC7641 is one of the trouble hot-spots, because it defines proper a behaviour for updating a state with best effort, but a lot of people intend to misuse it for "time series transfer".
And the disasters mostly starts with CON notifies :-).

**Comment by boaks** [comment]
Thanks for your description.
You use the LWM2M Data Reporting (coap observe/notify)?
You use leshan as LWM2M server?
And your devices are also using leshan? Or which LWM2M client implementation do they use? wakaama?
Do you use DTLS (coaps) or plain UDP (coap)?

Just as first remarks:
If you use observe/notify, the message your talking of is the notify from the device.
If leshan/californium is NOT on the device and only used for the LWM2M server, you don't need to change anything there. If the device really send CON messages, all would be OK. The setup of the notification type is only done in the device firmware.

The rest of the answer depends on DTLS (coaps) and plain UDP (coap). So please provide the answers to the above questions, maybe we can sort it out.

**Comment by iot-cloud** [comment]
Thanks for taking your time to answer the questions.

You use the LWM2M Data Reporting (coap observe/notify)? 
You use leshan as LWM2M server?

In fact, I use the Leshan Server to perform an automate/integration/regression testing with our Customer Device and Leshan Client (to simulate the Customer Device. Our Customer Device sends CON in the Notification but Leshan Server does not handle it. So I have to find a way for the Leshan Server to send ACK back to the Customer Device.

I have to use Leshan Server to initiate CoAP PDU as Our Customer Device does not develop to accept request. You know Modem and AT commands etc...but mostly novice developers and refuse to explore...


And your devices are also using leshan? I develop the Leshan Client to simulate the Customer Device.

 Or which LWM2M client implementation do they use? 
Proprietary and In house development by our Customer

wakaama?
Wakaama is develop to run on various platform except for Micro-Controller, BareMetal, small Flash Memory (100KB for two banks of firmware image - firmware update) with efficient firmware practices. There are few sketchy porting to various Micro-Controller but not suitable for firmware. Do you know any good development? We are willing to pay within reasonable budget.

Do you use DTLS (coaps) or plain UDP (coap)?
It just plain UDP. It should be at least PSK. Unfortunately I have no input...

If you use observe/notify, the message your talking of is the notify from the device.
If leshan/californium is NOT on the device and only used for the LWM2M server, you don't need to change anything there. If the device really send CON messages, all would be OK. The setup of the notification type is only done in the device firmware.

Let me do a quick check with the firmware guys. All I know is I have been asked to support CON in Notification and Simon says Leshan can not do it. I traced it down to the Californium implementation.

While we are here I observe a quirky behaviour in the order of the bootstrap parameters - if it is not in correct Leshan order (/rd?b=UQ&lwm2m=1.0&lt=60&ep=EndPoint-01) the traffic remains in Californium (as I got an ACK) on the rd as a result of Leshan not receiving rd the logic in the device sleep and awake will not work.

**Comment by boaks** [comment]
> Our Customer Device sends CON in the Notification but Leshan Server does not handle it

I'm really wondering about that. I use CON-notifies in tests an didn't get that failing behaviour.

> It just plain UDP.

OK. Do you control the ip-address/local-port of your device? If the address/port changes, the notify will mot be matched with the observe. You may have look at #719, maybe that is also a solution for you.

Though you testing, is it possible to get some wireshark logs (server host) of your communication?

**Comment by boaks** [comment]
> Let me do a quick check with the firmware guys. All I know is I have been asked to support CON in Notification and Simon says Leshan can not do it. I traced it down to the Californium implementation.

From Simon:
> Unfortunately, there is now way to configure the use of CON or NON by resource/object for now.

That only says "configure by (per) resource". So, currently, you can only have **all** notifies from a leshan demo LWM2M client in CON or **none**.

**Comment by boaks** [comment]
If you use the current leshan master, modify the leshan-client-cf as following:

LeshanClient.java, Constructor:

```
        // Create CoAP resources for each lwm2m Objects.
        for (LwM2mObjectEnabler enabler : objectEnablers) {
            ObjectResource clientObject = new ObjectResource(enabler, bootstrapHandler, new DefaultLwM2mNodeEncoder(),
                    new DefaultLwM2mNodeDecoder());
            if (enabler.getId() == 3303) {
                // set notification type for OID 3303 
                clientObject.setObserveType(Type.CON);
            }
            clientSideServer.add(clientObject);
        }
```

Then my log shows:
```
12:26:43.929 | CON-GET | 65465 | [39aacbe0d58cc0df] | Uri-Path: "3303", "0" - Accept: "application/vnd.oma.lwm2m+tlv" - Observe: 0 |  
-- | -- | -- | -- | -- | --
12:26:43.945 | ACK-2.05 | 65465 | [39aacbe0d58cc0df] | Content-Format: "application/vnd.oma.lwm2m+tlv" - Observe: 17 | Hex:e815e1084032b33333333333e815e2084034000000000000e8164408403319999999999ae3164563656c
12:26:44.459 | CON-2.05 | 7944 | [39aacbe0d58cc0df] | Content-Format: "application/vnd.oma.lwm2m+tlv" - Observe: 19 | Hex:e815e1084032b33333333333e815e2084034000000000000e81644084033800000000000e3164563656c
12:26:44.459 | ACK- | 7944 | [] |   |  
12:26:46.472 | CON-2.05 | 7945 | [39aacbe0d58cc0df] | Content-Format: "application/vnd.oma.lwm2m+tlv" - Observe: 22 | Hex:e815e1084032b33333333333e815e20840344ccccccccccde816440840344ccccccccccde3164563656c
12:26:46.472 | ACK- | 7945 | [] |   |  
12:26:48.472 | CON-2.05 | 7946 | [39aacbe0d58cc0df] | Content-Format: "application/vnd.oma.lwm2m+tlv" - Observe: 26 | Hex:e815e1084032b33333333333e815e20840344ccccccccccde81644084034000000000000e3164563656c
12:26:48.472 | ACK- | 7946 | [] |   |  
12:26:50.472 | CON-2.05 | 7947 | [39aacbe0d58cc0df] | Content-Format: "application/vnd.oma.lwm2m+tlv" - Observe: 29 | Hex:e815e1084032b33333333333e815e208403499999999999ae8164408403499999999999ae3164563656c
12:26:50.472 | ACK- | 7947 | []
```

So, the client send CON notifies (on per object base) and the server receives them.

That smells for an other issue your setup.

**Comment by sbernard31** [comment]
> All I know is I have been asked to support CON in Notification and Simon says Leshan can not do it. I traced it down to the Californium implementation.

... I said : it should be supported at Server Side ...(see https://github.com/eclipse/leshan/issues/571#issuecomment-424404073) If not this is maybe a bug ...

...  and I said : this is doable to configure Leshan client to always send CON for all observations of every objects ... (https://github.com/eclipse/leshan/issues/564 and https://github.com/eclipse/leshan/wiki/LWM2M-Observe#i-want-leshan-client-to-send-con-notifications) ... This should be enough to reproduce and issue ...

... :expressionless:  ...

**Comment by boaks** [comment]
@iot-cloud 

Could you recheck the issue with the CON notifies?

Just to mention:
FMPOV, really rare changing resources could be successfully observed using CON notifies.
But these scenarios are too often affected of address changes. 
The configuration described in

https://github.com/eclipse/californium/issues/719#issuecomment-413468004

would be a good starting point to make it working, but please ensure, you understand the security effects of that.

**Comment by iot-cloud** [comment]
Thank for everything. I will look closely to the question and answers.
