### ISSUE TITLE
Server timesout 

### ISSUE THREAD

**Issue by sridevgit** [eclipse/californium#774]
When Client connects to Leshan server behind NAT, After 2 mints, server is no longer in position to issue any requests to client until next registration update. We are going live very soon and lot of our devices are LTE, So it would be practically impossible to send registration update every 2 minutes since the devices will be in motion most of the time, it would be hard to have network everywhere. Any help for workaround for this issue would be much appreciated. Thank you

**Comment by boaks** [comment]
Just to add:
If you can't change the address translation timeout, but your NAT is on a router, some router have also a "port forwarding", which may be used to by pass the NAT.
