### ISSUE TITLE
Question: A method that returns the whole CoAP message.

### ISSUE THREAD

**Issue by IbrahimaWane** [eclipse/californium#784]
Hello,
Is there any method that returns the entire CoAP packet, not only the payload? I tried with RawData.getBytes(), but I only received my payload back. I.e. excluding the header and other optional fields. 
Thank you in advance.

**Comment by boaks** [comment]
> Is there any method that returns the entire CoAP packet, not only the payload?

> I tried with RawData.getBytes(), but I only received my payload back. I.e. excluding the header and other optional fields.

That doesn't make sense. The RawData is the entire CoAP message, handover to UDP (or DTLS,TLS,TCP) and is used there as content of the UDP message.

If you send a Request with payload "Hello", I'm pretty sure RawData.getBytes() will contain more than 5 bytes!

So, please post you snippet and the real dumps!

**Comment by IbrahimaWane** [comment]
Let me put it in this way. I would like to retrieve the entire CoAP message, before sending it, and make a security Tag from it and then send the tag along with it.  First off, do you think that is possible? If yes how can I get the RawData bytes filled up before sending the request?

As for the snippet, first, I only did something like:
RawaData rd = new RawData(payloadBytes, inetSocketAddress);
byte [] coapBytes = rd.getBytes();
then I printed it and only the payload shows up.
I guess there are some threads that must be run, to get it filled up with the CoAP message components.
So I did like:
Endpoint ep = new CoAPEndpoint();
ep.start();
CoapClient cc = new CoapClient();
cc.setEndpoint(ep);
print coapBytes but still only the payload.

Thanks

**Comment by boaks** [comment]
Just to mention: DTLS offers such MAC (Message Authentication Code) and crypts the message itself. (See https://de.wikipedia.org/wiki/Message_Authentication_Code).

So, do you want send the message in plaintext and only add a MAC? 
Are you sure, that you have all the security constraints and requirements under control?

The easiest way to implement something like that would be to implement a extension of the UDPConnector by extending that. Currently only the send could be easily overwritten, but I think, adding a "outer" receive to the connector should not be a blocker (you may do this on your own ahead and we add it, if you succeed with your approach).

**Comment by boaks** [comment]
> As for the snippet, first, I only did something like:
> RawaData rd = new RawData(payloadBytes, inetSocketAddress);
> byte [] coapBytes = rd.getBytes();

If you create your own `RawData`, yes it contains what you put in.
Californium uses the `DataSerializer`, to serialize a `Message` (convert it to bytes), and that contains all of the message including options and payload.

**Comment by boaks** [comment]
And, one wish from my side:
Please don't use the standard port 5683 nor 5684, because you change the protocol and it will not longer be RFC7252 (CoAP) nor RFC6347 (CoAP over DTLS).

**Comment by boaks** [comment]
```
Endpoint ep = new CoAPEndpoint();
ep.start();
CoapClient cc = new CoapClient();
cc.setEndpoint(ep);
```

Please use the CoapEndpoint.CoapEndpointBuilder. Provide your own `UDPConnector` implementation to the builder with the `setConnectorWithAutoConfiguration`.

**Comment by IbrahimaWane** [comment]
Thank you for complete answer. I finally, decided to apply it to the payload portion only.
