### ISSUE TITLE
Set IPv6 uri to CoapClient

### ISSUE THREAD

**Issue by tuncagurkan** [eclipse/californium#786]
Hello everyone,
I try to set a simulation scenario on Cooja. Server mote is running on Cooja and its address is IPv6 (coap://aaaa::212:7407:7:707:5683/test). How can I set IPv6 uri correctly to CoapClient()?
I set the uri like below but I can't test this:

CoapClient client = new CoapClient("coap://aaaa::212:7407:7:707:5683/test");

Thanks in advance,
Tunca

**Comment by tuncagurkan** [comment]
Yes, I did it but I can't get any successful response yet from the server, so I'm not sure which is correct. Can you say how can I check the uri style is correct or not?

**Comment by boaks** [comment]
If you use either 2.0.0-M12 or the current head of 2.0.x, the IPv6 syntax works. You may use wireshark to capture the package (filter "copa").

**Comment by boaks** [comment]
If you still interested in IPv6, just provide the information and logs.
FMPOV, it works.
