### ISSUE TITLE
being able to deactivate DTLS retransmission

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#788]
Currently, in scandium there is no way to deactivate retransmission. The better we can do is to limit it to 1 retransmission.

```java
/**
 * Sets the maximum number of times a flight of handshake messages gets re-transmitted
 * to a peer.
 * 
 * @param count the maximum number of re-transmissions
 * @return this builder for command chaining
 */
public Builder setMaxRetransmissions(int count) {
	if (count < 1) {
		throw new IllegalArgumentException("Maximum number of retransmissions must be greater than zero");
	} else {
		config.maxRetransmissions = count;
		return this;
	}
}
```

For debugging deactivate retransmission can help.
Currently, a workaround for debugging can be to use a very large `RetransmissionTimeout`.
This could be more elegant to be able to just deactivate retransmission.

I believe that changing the test by `if (count < 0)` should work.

**Comment by boaks** [comment]
Even before #779 handshakes, which didn't receive any response handshake message and reached the max retransmissions, have been timed out.
The change was, that the first received message stopped any timeout handling doesn't longer apply. It now only stops the retransmission, but not the timeout.
So FMPOV, a large timeout would be the easiest configuration and would not require any change.

**Comment by sbernard31** [comment]
> So FMPOV, a large timeout would be the easiest configuration and would not require any change. 

That's my final thought too.
