### ISSUE TITLE
Can Californium be deployed in the Class 1 device?

### ISSUE THREAD

**Issue by caocan** [eclipse/californium#805]
In the Rfc 7228， it classifies the constrained devices as three levels. It shows as below:
![image](https://user-images.githubusercontent.com/12294613/48889860-2046e680-ee72-11e8-8518-4be2437679f0.png)

So Can I deploy the californium in the Class 1 device? Thank you.

**Comment by boaks** [comment]
I'm not sure, if you would be even able to deploy a java "hello world" to class-1 device, could you? :-).

As far as I know, this class definition assumes your program in C (or any other environment/language, which is efficient enough).

Californium targets mainly the server side. It may be used on larger devices, e.g. Android.
Currently the californium-core itself has a 380 K jar, the element connector is about 120 K, and it encryption is to be used, scandium comes with additional 308 K. Depending on your "embedded java", this my be compressed somehow, but I would forecast, not into 100K.

You may read also our project page about the intended target devices.
https://projects.eclipse.org/projects/technology.californium
