### ISSUE TITLE
Help on testing CoapResource.handle*() methods

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#808]
I've just updated to the 2.0.0-M12 branch, and some old code of mine broke.

I used to test a CoapResource I implemented by manually creating an Exchange and calling the handler methods (e.g. .handlePost()) with that exchange.

Now exchange requires an additional parameter, the Executor and I cannot figure out how to create the right one.

Any suggestions on how to proceed for testing CoapResource methods without having to set up a whole Coap stack and a client and a network?

**Comment by boaks** [comment]
Exchange provides javadoc

`* @param executor executor to be used for exchanges. Maybe {@code null} for unit tests.`

did you read that? 
For simple testing, parallel processing of several exchanges with several messages is mostly not required. The most unit test of californium core therefore provide `null`.

**Comment by LudwigSeitz** [comment]
Seems I missed that, sorry for the hassle.

**Comment by boaks** [comment]
Very strange, `Exchange` has 3 constructor, and all 3 constructors have a javadoc, which contains a description of the parameter `executor` (Exchange.java, lines 269, 282, and 297).
So, where exactly do you miss the javadoc?
