### ISSUE TITLE
the problem about all MIDs are in use

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/californium#814]
WARN InMemoryMessageExchangeStore - cannot send message to /172.16.100.35:8098, all MIDs are in use

while I new a request send to my coap server,I have the tip.how to resolve it.

**Comment by boaks** [comment]
The MID is a 16 bit number, so you have about 65536 ID. All messages are kept for deduplication for about 250s. So one peer is limited to about 250 message/s, what is quite a lot for a mikro-controller. I'm not sure, what you scenario looks like, but I assume, it's not a coap typical one.

**Comment by bujingyun8** [comment]
Thank u,I just test creating coap requests for 1 to 100000

**Comment by boaks** [comment]
The use-case, one fat-client "as fast as possible", is not working for CoAP. 
If you want to benchmark a CoAP server, use multiple clients.
Californium offers some examples for that:
cf-extplugtest-server
cf-extplugtest-client (BenchmarkClient)
And the BenchmarkClient also

> WARN [UdpMatcher]: message IDs exhausted, could not register outbound request for tracking

if only 1 client tries it "as fast as possible". But if you start 1000 clients, you will get I idea about the performance.

So my recommendation:
- if your use-case is "one fat-client as fast as possible" don't use CoAP.
- if your use-case is "many small client as fast as client and server can", use CoAP

**Comment by bujingyun8** [comment]
thank u
