### ISSUE TITLE
OptionSet is missing some size1 and size2 processing

### ISSUE THREAD

**Issue by rogierc** [eclipse/californium#815]
While testing the Mule-Coap-Connector found some little bugs.

The **OptionSet( OptionSet origin )** copyconstructor and the **optionSet.clear()** method do not process  **size1** and **size2** options. 
These options are therefore not copied and not cleared by these methods. 

Used Californium version: **2.0.0-M12**

**Comment by boaks** [comment]
Tanks for reporting!

I pushed the fix to the 2.0.x. head. If possible, please retest with that version.

**Comment by rogierc** [comment]
Run tests using 2.0.0-SNAPSHOT. They show the issue solved.

**Comment by boaks** [comment]
Thanks!
