### ISSUE TITLE
Error: Block option's length must at most 3 bytes inclusive?

### ISSUE THREAD

**Issue by tarunsmalviya** [eclipse/californium#817]
I am trying to tranfer firmware over coap with blockwise option. The process stops exactly at 4096 block number with exception shown in image below.
Please help me resolving this issue.
<img width="836" alt="screenshot 2018-12-03 at 3 31 59 pm" src="https://user-images.githubusercontent.com/9993036/49367018-d59a5980-f710-11e8-9d78-d5d9fa8d6c9c.png">

Jlink Debugger:
<img width="829" alt="screenshot 2018-12-03 at 3 34 26 pm" src="https://user-images.githubusercontent.com/9993036/49367066-f5ca1880-f710-11e8-8749-fb3c32b6826a.png">

**Comment by boaks** [comment]
According:

https://tools.ietf.org/html/rfc7959#section-2.1

The block option is limited to 3 bytes. Though the error seems to be cause by some received message, it may be a violation of the message sender.

https://tools.ietf.org/html/rfc7959#section-2.2,Ffigure 1, shows, that 20 bits are left for the number, 4096 should fit into that. 
So, could you provide a capture of your traffic, to see, if the block option is encode in more than 3 bytes?
Is the sender of the request also californium? Or a embedded client?

**Comment by boaks** [comment]
I added the 4096 to the unit test. FMPOV californium does it right. 
So, please check your client.

**Comment by tarunsmalviya** [comment]
@boaks  Thanks for your response. I will update once i get logs of the block transfer.

**Comment by boaks** [comment]
Any news on this?

**Comment by tarunsmalviya** [comment]
@boaks Sorry for late response.

I checked the packet, there was error in packet formating. It was exceeding 3 bytes.

**Comment by tarunsmalviya** [comment]
@boaks Yes it was issue of the client library.
Yes, you can close this issue.

Thanks!

**Comment by tarunsmalviya** [comment]
@boaks Yes it was issue of the client library.
Yes, you can close this issue.

Thanks!
