### ISSUE TITLE
Can I support multiple client formal verification? And how to get the client certificate from the business layer?

### ISSUE THREAD

**Issue by tangwenhua** [eclipse/californium#819]
Can I support multiple client formal verification? And how to get the client certificate from the business layer?

**Comment by boaks** [comment]
For 2.0.x (2.0.0-M12 or newer):

Scandium verifies certificates using:

https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/CertificateVerifier.java

You can provide your custom implementation in

`DtlsConnectorConfig.setCertificateVerifier(CertificateVerifier)`

Or you may use the standard approach and use a set of trusted certificates:

`DtlsConnectorConfig.setTrustStore(Certificate[])`

Received messages are forwarded to the coap-stack with attached `EndpointContext`.
That contains the peer's identity, if available.

`EndpointContext Message.getSourceContext()`
`Principal EndpointContext.getPeerIdentity()`

with x509, the principal should be of class `X509CertPath`.

**Comment by tangwenhua** [comment]
Thank you very much。
So，I think  DtlsConnectorConfig.setIdentity() can set server certificate。DtlsConnectorConfig.setTrustStore(Certificate[]) can set client trusted certificates， this method is the standard approach。
DtlsConnectorConfig.setCertificateVerifier(CertificateVerifier) can slove multiple client formal verification,and I can provide my custom implementation in  CertificateVerifier。

**Comment by boaks** [comment]
If the question is answered, can we close this issue?
