### ISSUE TITLE
Media types for LwM2M 1.1

### ISSUE THREAD

**Issue by cavenaghi9** [eclipse/californium#820]
The LwM2M TS 1.1 adds support for the following standardized media types:
- SenML JSON | application/senml+json | 110
- SenML CBOR | application/senml+cbor | 112

I'm trying to implement encoder/decoder in Leshan for above media type, these media types must to be registered in [MediaTypeRegistry.java](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/MediaTypeRegistry.java) as well. 

Is there any plan to support above media type in Californium, or I can contribute changes.

**Comment by boaks** [comment]
I can add them, or, 
if you have a https://www.eclipse.org/legal/ECA.php, you may provide a PR for it.

**Comment by boaks** [comment]
I added the type and pushed it to 2.0.x.
If possible, please check, if it works for you.
