### ISSUE TITLE
2.0.0-M13 Released.

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#827]
Though a lot of small issues have been fixed and the question, when the M13 will be release, was already raised (see https://github.com/eclipse/californium/issues/810#issuecomment-446666502), I started to think about a M13 release.

Proposal:
- include the initial proposed fix for issue #776, PR #830
- updated "about.html"s, PR #829
- issue #677, PR #828
- PR #826

The implementation of the <a https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md>draft-ietf-tls-dtls-connection-id</a> showed first successful message exchanges, but also, that the changes/redesigns are too large to be released soon.
    
Any opinions? 
Additional issues, which should be fixed for M13?

**Comment by boaks** [comment]
I add PR #835 and #836 to M13.

That are the fixes for findings during my work on the connection id #824

**Comment by sbernard31** [comment]
I looked quickly PRs above. That's sounds good to me.
We could maybe fix #834 for M13 ?
I'm ok about not adding 'connection id' for now.

**Comment by boaks** [comment]
I'm done with PR #829 .
If noone has an objection, I will merge it on Monday and start the M13 release.

**Comment by boaks** [comment]
Released!

**Comment by sbernard31** [comment]
I started to integrate it in Leshan (https://github.com/eclipse/leshan/pull/644)

Some feedbacks :
1. In `DtlsConnectorConfig`, `getTrustStore` is deprecated but there is no alternative proposed:
```java
/**
 * Gets the trusted root certificates to use when verifying
 * a peer's certificate during authentication.
 * 
 * @return the root certificates
 */
@Deprecated
public X509Certificate[] getTrustStore() {
```
In Leshan, we are using it but maybe for overkill check ..

2. create an coapServer and destroy it without started it before raise an NPE :
```
java.lang.NullPointerException
	at org.eclipse.californium.core.CoapServer.destroy(CoapServer.java:291)
	at org.eclipse.leshan.client.californium.impl.CaliforniumEndpointsManager.destroy(CaliforniumEndpointsManager.java:256)
	at org.eclipse.leshan.client.californium.LeshanClient.destroy(LeshanClient.java:139)
	at org.eclipse.leshan.integration.tests.RegistrationTest.stop(RegistrationTest.java:71)
```
I agree this is an unusual use case but I think it can make sense.

**Comment by boaks** [comment]
For 1. 
Though the "trust" is now implemented with a CertificateVerifier, I'm not sure, if the getter makes sense, at least not, if a custom CertificateVerifier is used. But with changed javadoc, we can undeprecate it :-).

**Comment by boaks** [comment]
For 2.
Will be fixed in M14 :-).

**Comment by boaks** [comment]
1. done, 2 see PR #856
