### ISSUE TITLE
Duplicated CoAP Tokens

### ISSUE THREAD

**Issue by DanielMaier-BSI** [eclipse/californium#83]
In `Matcher` there is a method `createUnusedToken()` that should ensure that there are no duplicated CoAP tokens. However there are issues that lead to duplicated tokens anyways.

These issues differ on master branch and 2.0.x branch.

Master branch:

The createUnusedToken mechanism is not thread-safe. It gets checked if the token already exists but the new token gets added to the map later on, i.e. two threads may generate the same "unused" token.

2.0.x branch:

- The same concurrency issue as above,
- the AND condition in the while loop needs to be an OR condition.

I think on master branch we could fix this with `putIfAbsent()`, but on 2.0.x branch things get more complicated. Are there any suggestions how to fix this? Of course one fix would be to introduce some locks.

Remark (I am not a maths expert): One may assume that the probability for this clash is not that high, but it is (especially on 2.0.x branch). Caused by the variable length of the token we have a 1:8 probability to generate a one byte token. Inside these one byte tokens then we have some kind of birthday problem. In summary I get a clash on average with about 165 iterations with a test run.

Thanks
Daniel

**Comment by sbernard31** [comment]
**1. createUnusedToken()**
As you say, we can use a lock but this will be a big one ... :'(
Or create a new store just to reserve Token with a putIfAbsent method ... :/
I can't find any elegant solution.

**2. Random token size**
Personally, I'm not sure that was a good idea to have random token size.
The [spec](https://tools.ietf.org/html/rfc7252#section-5.3.1) say that we could _"use a nontrivial, randomized token to guard against spoofing of responses (Section 11.4).  This protective use of   tokens is the reason they are allowed to be up to 8 bytes in size."_

So allowing to configure the TOKEN_SIZE_LIMIT seems not so relevant. (see Daniel explanation above). We should probably only define a TOKEN_SIZE or a TOKEN_MIN_SIZE/TOKEN_MAX_SIZE.

**3. Custom token**
Even if we fixed createUnusedToken issue, we can still face request with same token as user can define its own token value using `Request.setToken()`

Just an Idea, but with **2.** and **3.** in mind maybe the solution is just  to try to minimize collision using random+not threadsafe test+large token size. And inform correctly the enduser when a collision happen which should not be usual.

**Comment by evansd963** [comment]
Agreed with @sbernard31 on point 2.

It is not a good idea to randomise the token size. By randomising the token size rather than increasing the protection against spoofed responses it is instead reduced.

Assuming the Token is populated in the current way then 25% of messages have a token which complexity is 2^16 or less.

I can't think of a reason why TOKEN_SIZE_LIMIT shouldn't be changed to be the token size and a new configuration value of TOKEN_SIZE added. TOKEN_SIZE should probably be used going forward with TOKEN_SIZE_LIMIT being used for backwards compatibility (assuming that’s normal practice).

I did notice this issue a few weeks ago but I have a few other priorities at the moment. I am still planning to create a pull request with the proposed solution when I get the time.

The proposed changes to how the token size is determined wouldn't fix the duplicate token value issues found in the test run by @DanielMaier-BSI assuming that the TOKEN_SIZE_LIMIT was set to 1.

Duplicate values would still be produced and the smaller the token size the more likely this is. If using a small token sizes and avoiding collisions was the original intention of this discussion, then I am talking about something different and would need a different solution.

Instead the proposed changes would address a wider security problem with the way that tokens are created when the TOKEN_SIZE_LIMIT is large.

**Comment by joemag1** [comment]
FWIW, TCP stack uses constant token size.

**Comment by sophokles73** [comment]
> 1. createUnusedToken()
As you said, we can use a lock but this will be a big one ... :'(
Or create a new store just to reserve Token with a putIfAbsent method ... :/
I can't find any elegant solution.

I think we could/should encapsulate the generation of the token into the call for registering the exchange when sending a request. This way we could reduce the scope of the lock down to the registry object.

> 2. Random token size
Personally, I'm not sure that was a good idea to have random token size.
The spec say that we could "use a nontrivial, randomized token to guard against spoofing of responses (Section 11.4). This protective use of tokens is the reason they are allowed to be up to 8 bytes in size."
So allowing to configure the TOKEN_SIZE_LIMIT seems not so relevant. (see Daniel explanation above). We should probably only define a TOKEN_SIZE or a TOKEN_MIN_SIZE/TOKEN_MAX_SIZE.

The only reason I can imagine why the token size has been made random, is to make it harder to predict tokens when using a weak RNG.

> 3. Custom token
Even if we fixed createUnusedToken issue, we can still face request with same token as user can define its own token value using Request.setToken()

Does anybody have a use case at hand where a client would actually *need to be able* to manually/explicitly set the token on a request? Maybe we can simply make it a read-only property and always have `Matcher` generate the token.

**Comment by sbernard31** [comment]
>The only reason I can imagine why the token size has been made random, is to make it harder to predict tokens when using a weak RNG.

But, I bet It's harder to predict a large constant size token generated with weak RNG. Than a random size token, with high probability to have 1 or 2 bytes token generated with weak RNG.

> Does anybody have a use case at hand where a client would actually need to be able to manually/explicitly set the token on a request?

Maybe if we try to integrate a send/receive API like in Leshan with ticketId and if we use token as ticketid. (I still have this is mind to remove the "special" observe API, but this is not so clear)

About the lock, using cluster mode, we can still face conflict ?

**Comment by DanielMaier-BSI** [comment]
I also would like to encapsulate the token generation. If we make it plugable someone could implement own strategies e.g.:
- If I use DTLS I don't need random stuff at all
- If I run in a cluster I can generate unique tokens over all cluster nodes, e.g. using first byte for clusterId
- ...

The only thing I don't like with such a `TokenProvider` is that it must be aware of the `ObservationStore` (on 2.0.x branch). Otherwise implementations that use persistent `ObservationStore` do not work.

**Comment by DanielMaier-BSI** [comment]
To sketch up the two different approaches I created two branches on our fork:
- https://github.com/bsinno/californium/tree/fixes_to_duplicate_tokens_with_token_provider_2.0.x
- https://github.com/bsinno/californium/tree/fixes_to_duplicate_tokens_inside_matcher_2.0.x

As I said I don't like the `TokenProvider` needs knowledge about `ObservationStore`. Perhaps someone has a better Idea?

**Comment by sbernard31** [comment]
Why not, just removing the dependency.

If someone want to share token through several cluster instances. He must implement a TokenProvider which are able to do that. 
He can create a TokenProvider  which depends to ObservationStore or create a TokenProvider which store all used token in a shared structure (like redis), up to him.

In that case, for observation, token should not be released on exchanceComplete but  when observation is cancelled.

**Comment by DanielMaier-BSI** [comment]
I agree with you that this will work. But I am not so happy that someone who implements a persistence for `ObervationStore` (probably even not for clustering, just to survive restarts) needs to know that he needs implement his own `TokenProvider`. But perhaps my happiness does not count here :).

**Comment by DanielMaier-BSI** [comment]
I created PR #85 without dependency to `ObservationStore` to discuss it there.

**Comment by canismail** [comment]
hi I have a question you would.
I created a virtual network with cooja.
and I want to acces motes using java application with coAP.
But I don't know how to do it. 
Can you help me ?
thanks for feedback

**Comment by sophokles73** [comment]
@canismail,

I do not know whether your behavior is caused by ignorance, lack of knowledge or simply impertinence. In any case, if you do not stop hijacking our issue threads I will report your abusive behavior to GitHub and have you banned.

BTW you should do your homework yourself before asking other people to do it for you ...

**Comment by canismail** [comment]
@sophokles73 ,

I absolutely agree with you. I am here only for orientation and so things..

**Comment by sophokles73** [comment]
fixed on master in 96d65f90700d09cada13bcd89674ade7d4bf5dc7
fixed on 2.0.x in 52104bd8511f74935bfb11bce280200972cb4eed
