### ISSUE TITLE
Certificate chain question

### ISSUE THREAD

**Issue by tangwenhua** [eclipse/californium#850]
Is the first layer or the Nth layer in the certificate chain a root certificate?
From the inside of the code, the public key is obtained from the layer 0 certificate.

public PublicKey getPublicKey() {
		PublicKey publicKey = null;

		if (rawPublicKeyBytes == null) {
			if (certPath != null && !certPath.getCertificates().isEmpty()) {
				publicKey = certPath.getCertificates().get(0).getPublicKey();
			} // else : no public key in this certificate message
		} else {
			// get server's public key from Raw Public Key
			EncodedKeySpec publicKeySpec = new X509EncodedKeySpec(rawPublicKeyBytes);
			try {
				String keyAlgorithm = Asn1DerDecoder.readSubjectPublicKeyAlgorithm(rawPublicKeyBytes);
				publicKey = KeyFactory.getInstance(keyAlgorithm).generatePublic(publicKeySpec);
			} catch (GeneralSecurityException e) {
				LOGGER.error("Could not reconstruct the peer's public key", e);
			}
		}
		return publicKey;
	}

**Comment by boaks** [comment]
> Is the first layer or the Nth layer in the certificate chain a root certificate?

The peers certificate is in 0 (the first, AFAIK that's the "common order" ). 
The rest depend on the use-case and handshake. In some use-cases the root-certificate is not sent at all. Though I don't know, which use-case you have, I would recommend, that you add some logging or use WireShark to see, what is exchanged.

**Comment by tangwenhua** [comment]
In the logic of the code, if the 0th item of the certificate array（X509Certificate[] rootCertificates） is the root certificate, an error will be reported. The Nth item is a certificate chain with the certificate。

However, when the above code is used to verify the certificate, it is the 0th item, not the public key of the root certificate. Will cause certificate signature verification to fail

try {
			int index = 0;
			CertificateFactory factory = CertificateFactory.getInstance(TYPE_X509);
			for (Certificate cert : certificateChain) {
				if (!(cert instanceof X509Certificate)) {
					throw new IllegalArgumentException("Given certificate is not X.509! " + cert);
				}
				X509Certificate xcert = (X509Certificate) cert;
				LOGGER.debug("Current Subject DN: {}", xcert.getSubjectX500Principal().getName());
				if (issuer != null && !issuer.equals(xcert.getSubjectX500Principal())) {
					LOGGER.debug("Actual Issuer DN: {}", xcert.getSubjectX500Principal().getName());
					throw new IllegalArgumentException("Given certificates do not form a chain");
				}
				++index;
				if (xcert.getIssuerX500Principal().equals(xcert.getSubjectX500Principal())) {
					// a self-signed root certificate
					if (index != certificateChain.size()) {
						throw new IllegalArgumentException(
								"Given certificates do not form a chain, root is not the last!");
					}
					if (includeRoot || certificateChain.size() == 1) {
						certificates.add(xcert);
					}
				} else {
					// not a self-signed certificate
					certificates.add(xcert);
					issuer = xcert.getIssuerX500Principal();
					LOGGER.debug("Expected Issuer DN: {}", issuer.getName());
				}
			}
			return factory.generateCertPath(certificates);

**Comment by boaks** [comment]
I don't understand, what you mean.
As I wrote the certificate a position 0 is the certificate of the peer.
1 would be the certificate of the ca, which signed the peer's certificate, and so on.

> In the logic of the code, if the 0th item of the certificate array（X509Certificate[] rootCertificates） is the root certificate, an error will be reported. 

The "if the 0th" is false (peer not root), so the rest is meaningless?

> However, when the above code is used to verify the certificate, it is the 0th item, not the public key of the root certificate. Will cause certificate signature verification to fail

The above code is **not** used to verify the certificate. It's just a first check, if the chain is in the right order (means certificate[n] is signed by certificate[n+1]). And, for some cases, it removes the root-certificate at the last position, because the other side should have it already (off-band).

The verification of the certificate-chain is done, as explained in my answer to your other question

https://github.com/eclipse/californium/issues/840#issuecomment-452674653

The default implementation verifies the certificate-chain with 

```
PKIXParameters params = new PKIXParameters(trustAnchors);
params.setRevocationEnabled(false);

CertPathValidator validator = CertPathValidator.getInstance("PKIX");
validator.validate(message.getCertificateChain(), params);
```

I still do not know your use-case. 
Do you have an issue with the certificate verification?
Do you analyse the implementation?

**Comment by tangwenhua** [comment]
if 0 signed by 1。why the public key used the 0-layer public key?

if (certPath != null && !certPath.getCertificates().isEmpty()) {
			publicKey = certPath.getCertificates().get(0).getPublicKey();
		} 

As I wrote the certificate a position 0 is the certificate of the peer.
1 would be the certificate of the ca, which signed the peer's certificate, and so on.

**Comment by boaks** [comment]
> if 0 signed by 1。why the public key used the 0-layer public key?

"used" for what? Sorry, my feeling is, that you have something in mind, but I can't guess what :-).

So, again, do you have an issue with the certificate verification (as implemented in californium/scandium)?
Or do you analyse the implementation (may be to understand the usage of certificates in DTLS)?

If you have an issue, I would appreciate, if you could write something specific about that issue.
if you want to analyse, I would also appreciate to know the scope of that. Are you interested in general information about the usage of certificate during the DTLS handshake? Or is your interest limited to the usage here in californium/scandium?

So just on a very high-level (without links to the RFCs):
During the DTLS Handshake "public keys" are use for two purposes:

- Verify the signing-chain within the certificate-chain to use that chain for a indirect trust-relation. The default implementation of that is using `CertPathValidator validator = CertPathValidator.getInstance("PKIX");` and the "use/access" of the public keys of the CAs is implemented within these java API classes (and not within californium/scandium).
  
- Verify, that the the other peer is really the owner of it's certificate (that at position 0). That is implemented by signing the KeyExchange messages with the "private key" (of the peers certificate at position 0) and verify the sign with the related public key . That's implemented in the subclasses of `KeyExchange` and the `CertificateMessage.getPublicKey()` is used to access the other peers public key for that verification.
