### ISSUE TITLE
How do subscribe messages from the server

### ISSUE THREAD

**Issue by Allen-cxl** [eclipse/californium#853]
I need subscribe messages，how to use？

**Comment by boaks** [comment]
The CoAP core (RFC7252) is REST, not PubSub. You may have a look at observe/notify (RFC7641), but that's also no PubSub.

**Comment by Allen-cxl** [comment]
Can it can receive notifications？how to do?

**Comment by boaks** [comment]
if the coap-server supports observe/notify, You just use the `observeAndWait` or `observe` methods of the `CoapClient` class. The notifies will be reported in the `CoapHandler.onLoad(CoapResponse)` to your implementation of that `CoapHandler` interface.

The `ObserveTest.testObserveClient` is one of the examples for that observe/notifies.

General, in CoAP it's very easy to implement and "endpoint", which is both, a coap-client and coap-server, at the same time. So even if your "primary" coap-client wants to receive message from the "primary" coap-server, not only observe/notify is able to provide that, you may alos just excahnge the roles and use PUT-request (or POST) in the other direction. But, try observe/notify, I find out, if it's a solution for you.

**Comment by Allen-cxl** [comment]
thinks, it's ok

**Comment by boaks** [comment]
If your question is answered, please close this issue.
