### ISSUE TITLE
DTLSConnector server not able to decode client encrypt HandShake 

### ISSUE THREAD

**Issue by sgoyaldel** [eclipse/californium#858]
# Please providing basic issue information

Encrypt handshake decode failed due to mac validation failure .  i am using Leshan Client with 2.0 M12 Cf version and have created my own version of dtls server using same cf version.

I am using PSK for encryption .

**Comment by boaks** [comment]
Leshan uses  the secret in hexa-decimal, californium in bytes.

e.g. 
californium : "secretPSK".getBytes()
leshan: "73656372657450534b"

Some editors offer such a conversion and also some web-pages (search ascii to hex).

**Comment by boaks** [comment]
Did the answer solve your issue? Was it the hex/bytes mix?

**Comment by sgoyaldel** [comment]
Thanks . it resolve the issue
