### ISSUE TITLE
OMA 1.1 support related

### ISSUE THREAD

**Issue by sgoyaldel** [eclipse/californium#863]
We need following the suggestion in Cf/ Scandium related to 1.1 OMA LW2M update 
1. CBOR Payload support 
2. TLV formate support
3. OSCORE support 
4. CoAP over TLS for FOTA and SOTA
5. CoAP + OSCORE on CIoT information

Thanks

**Comment by boaks** [comment]
Did you had a look at the https://www.eclipse.org/leshan/ project? It's currently not LWM2M 1.1, but https://github.com/eclipse/leshan/issues/563 at least the "kick off" discussion was started.

For your question around californium you may find some useful information on our project page
https://projects.eclipse.org/projects/technology.californium

"1. and 2."
About the payload formats, please read
https://github.com/eclipse/californium/issues/663#issuecomment-456331098

"3."
The ri.se contributed an oscore implementation. Find out, if it works for you.
See issue #516 (and read my comment https://github.com/eclipse/californium/issues/516#issuecomment-357271931 )

"4."
CoAP over TLS is still an experimental feature. It doesn't fully comply to https://tools.ietf.org/html/rfc8323 e.g. the https://tools.ietf.org/html/rfc8323#section-5 is not implemented. though californium is an open source project, you may consider to contribute to our "element-connector-tcp" moulde to get it closer to the RFC.

"5." 
no glue, what you mean :-)

**Comment by sgoyaldel** [comment]
thanks.
For point 5 :
 in 1.1 version CoAP over cellular IOT support added (LPWAN etc) like we  have CoAP over SMS (i assume CoAP over SMS already supported)

**Comment by boaks** [comment]
> CoAP over cellular IOT support added (LPWAN etc) like we have CoAP over SMS

No, that's currently not supported out of the box. I don't know, if this requires more changes, but in general, you may implement your own 

https://github.com/eclipse/californium/blob/2.0.x/element-connector/src/main/java/org/eclipse/californium/elements/Connector.java

We do this for 
coap: (plain UDP), UDPConnector
coaps: (DTLS), DTLSConnector
coap+tcp: (TCP), TcpClientConnector and TcpServerConnector
coaps+tcp: (TLS), TlsClientConnector and TlsServerConnector

so you may have a chance :-).

**Comment by sgoyaldel** [comment]
thanks a lot.
. if we require trigger mode SMS for Coap . do we have support for Coap over SMS ?

**Comment by boaks** [comment]
I don't get it.

Californium doesn't currently support Coap over SMS.

From my side, there is not plan to support it.
SMS seems for me to be somehow deprecated. "Wake-up on SMS" is in my opinion a myth. To receive the SMS the device already require a lot of energy. It may have been true long ago, that receiving a SMS takes much less power than ip-traffic, but with newer cellular modes you will recognize, that the difference is not that large. And with the upcoming technical innovations as CAT-NB, it may even get less. 
Receiving SMS on the cloud-side was in my experience also not easy and depends on the APi your "Provider" offers you.

@sbernard31 
Though you're much closer to the "real physical technic", do you plan SMS support for leshan? Or do you already use SMS for LWM2M?

**Comment by sgoyaldel** [comment]
thanks. actually i am talking about , i  this Coap URI will be sms+ MSISDN number for enduri
https://tools.ietf.org/html/draft-becker-core-coap-sms-gprs-06

**Comment by boaks** [comment]
From the draft:

> Expires: August 24, 2017 

May be, I'm not the only one, who has doubts about the use of SMS!

**Comment by sbernard31** [comment]
> do you plan SMS support for leshan? Or do you already use SMS for LWM2M?

We don't use LWM2M over SMS in production and we don't plan to support it in Leshan. One of the big challenge is probably to make DTLS work.

AFAIK, in production we only use SMS for very simple wake up based on "home-made" protocol. (single message from server to device)

**Comment by boaks** [comment]
@sgoyaldel 

I guess, you will not receive more information or other information on this topic. 

To be clear:
- I don't plan to improve the coap-over-tcp implementation. It would require some work to align it with the RFC 8323. If you want it, feel free to contribute it.
- I don't plan to implement SMS support at all. If you want it, feel free to implement it based on the Connector.

I guess, the other committers are also not able to help you on the tcp or sms stuff.

If your interested in tcp and sms and you want to check, if other californium user are interested as well and help you on those issue, I would appreciate, if you just open two new issues for that. But I'm not too optimistic, that other user will spend their time, especially on the sms stuff.

**Comment by sgoyaldel** [comment]
MAy i ask when 1.1 related support available? I mean there are some new messages are defined as observercomposite, CancelComposite etc ?

**Comment by boaks** [comment]
I can only answer for myself (more or less again):
- I don't plan it. If you or someone else want it, feel free to contribute it.

If your interested in these features and you want to check, if other californium user are interested as well and help you on those issue, I would appreciate, if you just open new issues for that.

**Comment by boaks** [comment]
Seems, that this issue is replaced by a new one #881.
Can we therefore close this one?

**Comment by sgoyaldel** [comment]
we can close #881

**Comment by boaks** [comment]
I'm not sure, which one you want to close this #863 or the other #881 
Though you created the issues, you may also close the one, which is obsolete.

**Comment by boaks** [comment]
Seems, that the interest to contribute for these points is not that large.
