### ISSUE TITLE
MulticastSocket used by UdpMulticastConnector always uses the default network interface

### ISSUE THREAD

**Issue by aml2610** [eclipse/californium#872]
Hi! 

## Version
I saw that https://github.com/eclipse/californium/pull/742 added multicast support so I started using 2.0.0-M13 version of californium-core.

## Issue
For my use-case I need to bind the multicast socket to a non-default network interface so whilst trying to do so I discovered that `UdpMulticastConnector` does not set the network interface on the `MulticastSocket` that it uses so the socket always ends up bound to the default interface.

## How to reproduce
When creating a CoAP server you can provide an endpoint that uses a `UdpMulticastConnector` e.g:
```
        ....
        // Add multicast endpoint
        final InetSocketAddress serverSocketAddress = new InetSocketAddress( "<INET_ADDR_OF_CUSTOM_IFACE>", <LOCAL_PORT>);

        final Connector connector = new UdpMulticastConnector(serverSocketAddress,CoAP.MULTICAST_IPv4);

        final CoapEndpoint.Builder builder = new CoapEndpoint.Builder();
        builder.setNetworkConfig(config);
        builder.setConnector(connector);

        server.addEndpoint(builder.build());
        ....
```

If you debug up to `UdpMulticastConnector.start()` and inspect the `MulticastSocket` created inside that method you will see the interface is never set, therefore `Multicast.interfaceSet` remains set to `false` so when `MulticastSocket.joinGroup(group)` is called it will always set the network interface to the default one - can check that by adding a breakpoint to the `setNetworkInterface(defaultInterface);` call inside `MulticastSocket.joinGroup()` method.

## Expected behaviour
I would expect that if I provide an address corresponding to a custom network interface, the multicast socket will be bound to that interface instead of the default one.

## How to fix
I think a possible fix would be something along these lines: inside `UdpMulticastConnector.start()`, after it creates a `MulticastSocket`, call `multicastSocket.setInterface(addr)` with addr being the local address provided to the CoAP endpoint.

I am happy to do the fix if you decide this is indeed an issue and if I am not mistaken in any of the above.

Thanks

**Comment by boaks** [comment]
Currently `MulticastSocket socket = new MulticastSocket(localAddr);` is called, and at least the intention was, that this defines the interface by the provided local address. 
Do you have a network interface, which doesn't have a local address assigned?

**Comment by boaks** [comment]
I investigated on this in the web. At least there are hints, that the `MulticastSocket` is somehow mixed up. I will check that, but it may take some days to find the time.

**Comment by boaks** [comment]
I tried to reproduce your result.
I use a coap multicast server on ubuntu 16.04 with java 1.8 and two network interfaces.
If I use the address of the reachable interface, the server received the request and the client gets a response.
If I use the address of the none-reachable interface, the server didn't receive the request and the client didn't get a response.

Are you sure, that using the `<INET_ADDR_OF_CUSTOM_IFACE>` doesn't work? May be you can add some more details? did you already try your fix? Does it work?

**Comment by boaks** [comment]
Let me add:
According my web investigation, using the address in the constructor is reported to make sometime trouble with linux, but these "troubles" are rather unsharp. 
And changes without verification are usually not really lasting.

**Comment by boaks** [comment]
In managed to test both interfaces and it works for both on "my machine".

So, I would propose to add the `MulticastSocket` `setInterface`,  `getInterface` and other special methods to the `UdpMulticastConnector`. This would enable the everyone to use the methods, which are required in his environment. Is that OK for you?

**Comment by aml2610** [comment]
Hi @boaks 
Thank you so much for looking into this and detailing your investigation.
I haven't spent any more time on this since I reported it because I have found a way to work around around this.

I tested on a machine running macOS Mojave and java 1.8.0_181, only with a reachable interface. As I mentioned before, the thing that caught my eye was that in `MulticastSocket` constructor it does not set the flag `interfaceSet` to true so when you call `MulticastSocket.joinGroup()` it would check that flag, find it to be `false` and call `setInterface()` on the default network interface (whatever that may be on your system).

To further test this, I created my own `UdpMulticastConnector` so that I have access to the socket. I constructed the socket using the address of the (reachable) interface. I then output the result of `getInterface()` before and after calling `joinGroup()` and I could see that before the `joinGroup()` call `getInterface()` would return what I expected i.e my interface, after that call it would return the default interface, indicating that the interface used for multicast was altered by that method call.
That this affects or not the multicast communication I did not know for sure, but suspected it did, since I mentioned I needed the multicast traffic to be handled by my custom, non-default interface.

I then went on to call `setInterface()` separately on my socket before providing it to my custom `UdpMulticastConnector`. In that case the interface would not be overriden by the `joinGroup()` call anymore. This seemed to fix the issue on my end. Note I did not test this with the californium project but it does offer strong indications that the fix would work.

Thank you for running your own tests. I can see the value in running with a non-reachable interface and getting that result (i.e the request not being received by the server), that indicates that indeed the interface you supply to the connector is attempted to be used, which I realise kind of contradicts my own findings, but the environments of our tests are different ones.
Given these "contradictory" results, I would say it highly depends on the environment you're running on and more specialised tests would probably uncover exactly what those differences are, but I myself don't have any time/don't see much point in testing this further - I guess you're probably in the same situation.

I agree with your proposed fix and am happy to implement it if you're OK with that. We might also want to mention this potential issue somewhere in the documentation so people would know to call `setInterface()` if needed - what do you think?

**Comment by boaks** [comment]
> I agree with your proposed fix and am happy to implement it if you're OK with that. We might also want to mention this potential issue somewhere in the documentation so people would know to call setInterface() if needed - what do you think?

Yes, good idea. I would welcome a PR with added methods to the `UdpMulticastConnector` exposing the special methods of the `MulticastSocket` and some more javadoc.

Please read https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md , especially the section with the Eclipse Contributor Agreement, http://www.eclipse.org/legal/ECA.php

Don't forget to sign your commit using the same e-mail as for the ECA.

**Comment by aml2610** [comment]
https://github.com/eclipse/californium/pull/895 should fix this so I am closing it. Thanks for the support!

**Comment by boaks** [comment]
@aml2610 

Just, if you're still interested in the multicast feature:

There is an ongoing discussion in the ietf core-mailing-list, see [RFC 7252 - 8.2 - Multicast - Request / Response Layer, page 67, top](https://mailarchive.ietf.org/arch/msg/core/d2CJN0g-ksq9uf0hDqBCRqcHz5g/).
I addressed the discussed topic in PR #1272.
I wold appreciate, if you can test that new function on macOS.

**Comment by aml2610** [comment]
Hi @boaks 

Unfortunately, I don't work with Californium anymore.
If you still cannot find anyone to test this for you on a mac, I could probably try it out for you this weekend and let you know?

**Comment by boaks** [comment]
It's not really required. 
I mainly informed you in order not to surprise you too much, once you update :-).
