### ISSUE TITLE
Javadoc generation broken for Java11+

### ISSUE THREAD

**Issue by bdamm** [eclipse/californium#874]
# Javadoc gen under Java11 is broken

Due to Java11 javadoc defaulting to and validating html5 as the output format, the html 4.0.1 elements in the source's javadocs do not pass. The javadoc plugin must receive:

```
<additionalOptions>-html4</additionalOptions>
```

**Comment by boaks** [comment]
If possible, please retest with the PR #875 

Just to mention:
Californium 2.0 promises to run with java 1.7, to use java 1.11 is rather experimental. 
If you collect experience, your feedback will be welcome. Simply create an issues with the feedback, regardless of failures or success stories :-).
