### ISSUE TITLE
Question about the DTLS handshake 

### ISSUE THREAD

**Issue by TerenceYi** [eclipse/californium#876]
We are using 2.0.x branch of californium, we need to record the handshake success rate, Do you think is reasonable to expose a method in DTLSConnector allowing feed in extra SessionListener?

**Comment by TerenceYi** [comment]
The default connection store InMemoryConnectionStore has implemented the SessionListener but provided  
 with empty implementation.

**Comment by boaks** [comment]
Please check the solution in issue #716 if ti works for you.

Sum up of the solution:
Derive from `DTLSConnector` and overwrite `void onInitializeHandshaker(final Handshaker handshaker)`.

Please provide us feedback, if it works for you or not.

**Comment by TerenceYi** [comment]
> onInitializeHandshaker

Thanks for your quick response, i'll check it.

**Comment by TerenceYi** [comment]
That's what I need. thanks
