### ISSUE TITLE
Multithread handshake in DTLSConnector

### ISSUE THREAD

**Issue by jizhenfang** [eclipse/californium#877]
hi all  
Scandium(version 2.0.0.M3) is used in a IoT project and the device is communication  with server in  CoAP over DTLS.  
In performance test, it's only 84.95 tps handshake in every  request.  
I have read Scandium source code and it maybe cause by DTLSConnector's receiver work in a single thread.   
The improvement is  multithread to receive dtls data and hash to a fix thead by source ip&port in my opinion. Is it right?

**Comment by boaks** [comment]
Please update M3 to M13 and retest. In the newer version the crypto-calculations are already executed by a thread pool. 

> In performance test, it's only 84.95 tps handshake in every request.

Do you use PSK or ECDSA base cipher suites? (PSK is simpler and faster)
How many simultaneous CoAP requests are used? (With only 1 simultaneous CoAP request, the thread pool will not show benefits) 
Do you test with one DTLS handshake for one CoAP record? 

I would hope, at least with the implementation of
https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md
which is currently being implemented in californium
https://github.com/eclipse/californium/issues/824
it should be some more requests per dtls handshake.

The demo-apps contains also some examples to test the performance.Try cf-extplugtest-server with the BenchmarkClient of cf-extplugtest-client.

**Comment by jizhenfang** [comment]
> Please update M3 to M13 and retest. In the newer version the crypto-calculations are already executed by a thread pool.
> 
> > In performance test, it's only 84.95 tps handshake in every request.
> 
> Do you use PSK or ECDSA base cipher suites? (PSK is simpler and faster)
> How many simultaneous CoAP requests are used? (With only 1 simultaneous CoAP request, the thread pool will not show benefits)
> Do you test with one DTLS handshake for one CoAP record?
> 
> I would hope, at least with the implementation of
> https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md
> which is currently being implemented in californium
> #824
> it should be some more requests per dtls handshake.
> 
> The demo-apps contains also some examples to test the performance.Try cf-extplugtest-server with the BenchmarkClient of cf-extplugtest-client.

thanks for your answer.  
We have use ECDSA base cipher suites first and It's only 84.95 tps. It's not  meet our project demand so we have chaged PSK later.    
There are 1 million device to send CoAP request to server  per 2 minites and It is growing.   
>Do you test with one DTLS handshake for one CoAP record?    
 

Yes, we test this situation because the device is mobile and the source ip&port is changed after minites, so device is handshake with server again.

**Comment by boaks** [comment]
And you use M3? At least I would try to benchmark M13 to see, if that is faster.

> We have use ECDSA base cipher suites first and It's only 84.95 tps. It's not meet our project demand so we have chaged PSK later.

> Yes, we test this situation because the device is mobile and the source ip&port is changed after minites, so device is handshake with server again.

What do you run on your devices? Which DTLS CoAP implementation do you use?
M13 offers the "auto-resumption" feature, if it runs on the device. An address change only requires a resumption handshake, which is the same for PSK or ECDSA. But if you already use PSK, I guess the resumption will not be that faster.

The new draft  
https://github.com/tlswg/dtls-conn-id/blob/master/draft-ietf-tls-dtls-connection-id.md
addresses these ip changes. if you done with your M13 benchmark, you may have a look at the 
wip branch "wip_add_dtls_cid". 
I guess your devices are not android-phones? If they are android phones, you may test the wip-branch even with them (I do it, it works not too bad :-) ).
But if you can't use californium on the device, you would need a device-implementation as well.

**Comment by boaks** [comment]
M13 will also fix your issue #651. The `find` now uses a hashmap for the session ids.

**Comment by boaks** [comment]
Last weekend the 2.0.0-M14 was released. This version offers the requested functionality.
I recommend, that you retest your benchmarks with that. I'm very interested in the results and I'm strongly believe, the performance is much better.

Currently californium has mainly 2 active committers and a couple of active contributors.
I don't see, that we can provide a similar function based on 2.0.0-M3.

There are some differences on the "protocol layer" between M14 and M3, but as far as issues are reported to us, these differences are no blockers.

Changes related to RFC7959 (blockwise):
PR #527 fixes the usage of ETAG
PR #821
PR #887
PR #892 
PR #892   

Other notable changes:
PR #844 
We also introduce a `CoapEndpoint.Builder`. The migration should be obvious.

Just to mention: a lot of the blockwise issues and fixes are reported by @mb590721 during update from 2.0.0-M1 to M12. So you will not be the first. If you detect some problems, we will try our best to sort them out in new milestones :-) .

**Comment by boaks** [comment]
@jizhenfang 

May be you have a look at [DTLS CID load-balancer](https://github.com/eclipse/californium/wiki/DTLS-1.2-connection-ID-based-load-balancer). 

For now it's just a demonstration. A lot of things required for a "production load-balancer" is missing (e.g. alive-monitoring). But it demonstrates the strength! You can even restart the load-balancer-node and though the CID routing is static, the peer will still be forwarded to the right node in the cluster.
