### ISSUE TITLE
PSKStore not support  asynchronous

### ISSUE THREAD

**Issue by jizhenfang** [eclipse/californium#878]
hi all
Scandium(version 2.0.0.M3) is used in a IoT project and the device is communication with server in CoAP over DTLS.  
The keyExchageAlgorithm is psk  in our project and  Every device has an independent psk  for security.  
PSK will read from  redis  when device handshake with device gateway.  
ClientHandshaker's  code
`byte[] psk = pskStore.getKey(identity);`  
It is not support asynchronous and blocking until the psk‘s value is return. It will impact the  throughput.  This feature is import in  ocean IoT devices and Will it be done in the future ?   Thanks .

**Comment by boaks** [comment]
We discussed that for about a year, see issue #242.
I would recommend, that you try to push and deploy the credentials to the nodes proactive before they used. 
But, if you think, it is useful, to load it on request, may be you consider to implement and contribute it.

**Comment by boaks** [comment]
@sbernard31 

May be you're interested in this issue. Either by providing your experience (may be some details about your cache solution) or by (co-)implementing this feature.
My personal plans for the near and middle future is to reduce the number of handshakes :-).

**Comment by sbernard31** [comment]
I checked quickly and if I'm not wrong. 2.0.0M3 does not event support multithreading for DTLSConnector.

Since this M3 release a lot of progress has been done to limit those kind of problem. So I really advice you to use a more recent version. From my experience, the 2.0.0-M12 is the most stable version of Californium/Scandium I never used. (I didn't test the 2.0.0-M13 in production so far so I can not tell about it).

On our side, we add some cache to `PskStore` when that was possible too and now we don't face issue about that anymore.

For more details about issues of 2.0.0-M3 : #213.

I still feel #242 idea would be an enhancement but :
 - I don't expect this will allow you to handle significantly more handshakes, I think this will just not disturb already connected peers if pskstore is busy.
 - As it works enough for now,  this seems not to be a priority for us.

**Comment by boaks** [comment]
> I never used

Do you mean "ever"?

**Comment by boaks** [comment]
> (I didn't test the 2.0.0-M13 in production so far so I can not tell about it).

May be, you save the time and wait for M14 with the "cid redesign" :-). 
Just to mention: my "continues testing" was never as stable as with the current redesign for the cid.

**Comment by jizhenfang** [comment]
> I checked quickly and if I'm not wrong. 2.0.0M3 does not event support multithreading for DTLSConnector.
> 
> Since this M3 release a lot of progress has been done to limit those kind of problem. So I really advice you to use a more recent version. From my experience, the 2.0.0-M12 is the most stable version of Californium/Scandium I never used. (I didn't test the 2.0.0-M13 in production so far so I can not tell about it).
> 
> On our side, we add some cache to `PskStore` when that was possible too and now we don't face issue about that anymore.
> 
> For more details about issues of 2.0.0-M3 : #213.
> 
> I still feel #242 idea would be an enhancement but :
> 
> * I don't expect this will allow you to handle significantly more handshakes, I think this will just not disturb already connected peers if pskstore is busy.
> * As it works enough for now,  this seems not to be a priority for us.

hi , sbernard31

I have add cached to Pskstore in my project  and Pskstore is  not support asynchronous, When the distributed cache node is down and it will return psk slow, It will block device handshark with CoAP server.

**Comment by sbernard31** [comment]
@jizhenfang, which version of californium are you using ?

**Comment by jizhenfang** [comment]
@sbernard31  The version of californium is 2.0.0-M3.

**Comment by boaks** [comment]
@jizhenfang 

I can only recommend to test with 2.0.0-M14. 
That should show, that with that version the performance is already improved. 
With that version the crypto functions are executed by a thread pool. 
The default size of that thread pool is

`DEFAULT_EXECUTOR_THREAD_POOL_SIZE = 6 * Runtime.getRuntime().availableProcessors();
` 

Depending on the latency of your solution, you may even try a larger number.

**Comment by sbernard31** [comment]
@jizhenfang, ax explained above , the 2.0.0-M3 has real performance issue (see #213). AFIAK, there is no good solution with this version. I can only recommend you to upgrade to a more recent one.

**Comment by boaks** [comment]
We released 2.0.0-M18.
It doesn't provide the requested asynchronous support for PSK, but it should be our fastest and securest DTLS 1.2.
Feedback based on that version will be very welcome.

**Comment by boaks** [comment]
@jizhenfang

Today I created PR #1304 with support for an asynchronous PSK store.
If you are still interested, it may be worth to test, if it fits for you.
Don't hesitate to give us your feedback.

**Comment by boaks** [comment]
PR #1304 is merged.
