### ISSUE TITLE
Does paradigm "Observing resources with COAP" awareness of  limitation of 250 message per second  as for the  paradigme "request-response with CoAP"  ?  

### ISSUE THREAD

**Issue by sitoumbaz** [eclipse/californium#883]
Hi committer,

I can implement and run  an Observing Resources with CoAP. Howerver when I increase the rate of changing the resource at the server side, the Observer (Client) stop for a while with the following output log :

`INFO: Duplicate response for open exchange: NON-2.05   MID=47773, Token=d8ac711d74a012, OptionSet={"Observe":67711}, "{"payload":"afbcdefwfxik".. 283 bytes`

Why I am getting this message, is it realated to the coap limitation of message rate (250 messages/sec ) ? 
The most important is the rate of changing resource it higher than 250 times per second (300 times/sec and 352 times/sec).

Bellow are the  maven dependencies  of Californium that I am using: 

```
<dependency>
  <groupId>org.eclipse.californium</groupId>
  <artifactId>californium-core</artifactId>
  <version>1.0.3</version>
</dependency>
<dependency>
  <groupId>org.eclipse.californium</groupId>
  <artifactId>scandium</artifactId>
  <version>1.0.3</version>
   <type>jar</type>
</dependency>
```

**Comment by boaks** [comment]
The limit "250 messages per second per client" results from a 16 bit MID and 247s default message exchange lifetime. Generally, every NON or CON message could be rejected by a RST-message with the same MID. If the default lifetime for a exchange is 247s then the 65536 MID must span over that time. That results in the "250 messages per second per client".

So you have two possibilities:
- use a protocol with a MID range larger than 16 bit (preferred! CoAP is not intended for message streaming :-).
- use a smaller exchange lifetime (e.g. Californium.properties => remove the last 0 from EXCHANGE_LIFETIME=247000 => 24700, that will use only 24.7s, **NOT** preferred)  
 
If you use more clients (e.g. 4000) then it's possible to reach 40.000 - 60.000 messages per second with an modern PC (e.g. R7-2800).

**Comment by boaks** [comment]
Please use  2.0.0-M13 unless you have a good reason to stick on 1.0.x

**Comment by sitoumbaz** [comment]
Thanks for the reply I do not want to change basic setting of COAP paramters now. 
In additional I will want to understand how works DEDUPLICATOR parameter,  is it related to the The limit "250 messages per second per client" ? 

Thanks I will set my dependecies to 2.0.0-M13.

**Comment by sitoumbaz** [comment]
Regarding the message
`INFO: Duplicate response for open exchange: NON-2.05 MID=47773, Token=d8ac711d74a012, OptionSet={"Observe":67711}, "{"payload":"afbcdefwfxik".. 283 bytes`. 

I got this message log just once after 250 secondes running my experiments, the reste of the time I do not get anymore this message. That means that the there is some automatic setting of CoAP to reduce the   EXCHANGE_LIFETIME parameter ?

**Comment by boaks** [comment]
> That means that the there is some automatic setting of CoAP to reduce the EXCHANGE_LIFETIME parameter ?

I'm not aware of such a `automatic setting` :-).

**Comment by sitoumbaz** [comment]
Thanks.  I checked the code to see if there is some `automatic setting`. You are right there is no such automatic setting.

**Comment by phani50** [comment]
How to do Rate limit at CoAP resource level(server side). for example per minute, 10 requests form same client.
