### ISSUE TITLE
Support cipher suites TLS_PSK_WITH_AES_128_CCM and PSK-AES256-CCM for Scandium DTLS

### ISSUE THREAD

**Issue by AndreasHuber-CH** [eclipse/californium#884]
Would it be possible to add support for two additional cipher suites TLS_PSK_WITH_AES_128_CCM and TLS_PSK_WITH_AES_256_CCM ?

I think they should not be too different from the cipher suite TLS_PSK_WITH_AES_128_CCM_8 that you already support as only they diff only in the key size and the MAC size.

**Comment by boaks** [comment]
I added more ciphersuites in the branch "wip_add_dtls_cid", and I agree, it's not a too big issues.
Would it be possible for you to wait? I guess up to 3-4 weeks. We work in integrate that wip into 2.0.x.

**Comment by AndreasHuber-CH** [comment]
Ah, that would be great. 3-4 weeks should be just about fine. Can we maybe test the code on the branch a bit sooner already?
I saw you currently added new ECDHE_ECDSA cipher suites and not yet these PSK ciphers.

**Comment by boaks** [comment]
Sure, may be tomorrow or on Monday.

**Comment by boaks** [comment]
I added TLS_PSK_WITH_AES_128_CCM and TLS_PSK_WITH_AES_256_CCM to the branch "wip_add_dtls_cid". Please test it, if it works for you.

**Comment by AndreasHuber-CH** [comment]
I tried out scandium on the branch, and yes both requested cipher suites worked without any problem in our scenario.
Thank you very much for the quick response and implementation!

**Comment by boaks** [comment]
Great. So could this issue be closed?

**Comment by boaks** [comment]
@AndreasHuber-CH 

Hi Andreas,

you may have recognized, that with 2.0.0-M17 we disabled the AES-CBC cipher by default. You must unlock them by setting `DtlsConnectorConfig.Builder.setRecommendedCipherSuitesOnly` to `false`.

We also currently discuss, how that thread should be mitigated. The publications starting with lucky 13, means, if the same message is sent frequently, that maybe discovered. If the attacker is an on-path attacker close to your server. There is a mitigation available (not a fix/resolution!), and there are also reports about wrong implementations. And currently the experts seems to focus now even on "on machine" attacker. Scandium has some weakness with that and currently we discus, what we offer as mitigation. There are voices, which want to use RFC7366, I personal don't think, that this is really an option. 
I tried also some mitigation, see the PR 1037.
So feel free, to write us your opinion/requirements, if you want.

**Comment by AndreasHuber-CH** [comment]
Hi,
I'm really sorry for my very late response. I talked to our security architect and forwarded him the question, but I didn't follow up when he did not respond.

From my point of view: We are quite happy with the CCM cipher. It does not have the security issue related to padding oracle attacks. And as a bonus it only require AES encryption algorithm. This can be useful on very constraint devices as the SHA-256 code does not need to be present at all.

To me, supporting RFC7366 looks way more complicated than simply switching to already existing cipher suites that don't suffer from the security issues. Especially as the extension won't necessarily be supported by the clients anyway.

**Comment by boaks** [comment]
> I'm really sorry for my very late response. I talked to our security architect and forwarded him the question, but I didn't follow up when he did not respond.

It's still welcome, I'm even more happy to read from you now, then I would have been in Sept. 2019, when I was much more under stress :-).

> We are quite happy with the CCM cipher.

Thanks, so are the most. 
Seems that I remembered it wrong, I thought you want to use also some AES-CBC stuff.

> This can be useful on very constraint devices as the SHA-256 code does not need to be present at all.

It's still required even for AES-CCM in the handshakes PRF (HMAC using SHA-256) and the "verify_data" in the FINISH message.

**Comment by AndreasHuber-CH** [comment]
> It's still required even for AES-CCM in the handshakes PRF (HMAC using SHA-256) and the "verify_data" in the FINISH message.

Ah your right. I've been mixing up things. In another place we also use AES to encrypt and authenticate messages, but not related to DTLS
