### ISSUE TITLE
No response on early blockwise negociation for empty payload

### ISSUE THREAD

**Issue by mb590721** [eclipse/californium#885]
Hi,

While making some tests with the M13 version i discovered a problem since the #821 PR.

When using the strict block2 configuration at the server side and making a request with early block2 negociation, if there is no content in the response payload the response is never send back by the server.

It happen for success and error response.

I pinpoint the the problem lies in the `Block2BlockwiseStauts.forOutboundResponse` method.

`status.buf.put(response.getPayload());` 

when there is no payload it seems to throw an NPE but no stacktrace or californium logs are showing up in the console and no response is received by the client.

I will provide a PR with a test case and try to solve the issue and understand why nothing is logged.

**Comment by mb590721** [comment]
I created the PR #886 with a test case.

**Comment by boaks** [comment]
Thanks for reporting and the test case.
PR #887 should fix it.

Just to mention:
"the strict block2 configuration" is intended to cover cases, where the client implementation assumes a interpretation of block2 option usage, which I don't share. Therefore my recommendation is the change the client implementation, whenever this is possible.

**Comment by mb590721** [comment]
Hi,

Yes I agree that origin of the problem lies in the client implementation. 

For those who use M13 and are experimenting this problem just setting manually the payload to an empty byte array solve the issue by the meantime another milestone is released.

**Comment by boaks** [comment]
So, should PR #887 be merged?

If yes, would you then rebase your PR #886 after merging #887 on the top of that, so that we can merge your test contribution also?

**Comment by mb590721** [comment]
Yes I think it should still be merged. At least it add a layer of security with the try-catch mechanism and enhanced logging.

Yes no problem for rebasing PR #886, just let me know when #887 is merged. :-)

**Comment by boaks** [comment]
Merged. It would be great, if you rebase your PR. May be you now remove the added comment so that it only adds the missing test. Thanks in advance.

**Comment by mb590721** [comment]
I rebased and committed the PR, let me know if it's missing something.

**Comment by boaks** [comment]
The tests are merged, so could this issue be closed?

**Comment by mb590721** [comment]
Yes that's ok for me, I close the issue.

Thanks !
