### ISSUE TITLE
Useless call to SessionCache.get() triggered by DTLSConnector.processNewClientHello()

### ISSUE THREAD

**Issue by AndreasHuber-CH** [eclipse/californium#890]
I'm trying to implement the SessionCache interface.
While testing DTLS session resumption I observed that SessionCache.get() is called twice for the same ClientHello.
The first call is triggered when DTLSConnector.isClientInControlOfSourceIpAddress() checks if there is an existing connection for the given session id. If there is no session in the local cache SessionCache.get() is called and potentially a new Connection is returend that is initialized with the SessionTicket from the cache.
But this cache lookup is actually useless because isClientInControlOfSourceIpAddress() wants to verify the peer address, but a new Connection initialized from a SessionTicket has never a peer address.
As the cache lookup could be quite expensive (e.g. database call) this could be a performance issue.

A possible solution would be to call "InMemoryConnectionStore.findLocally()" instead of find() inside of isClientInControlOfSourceIpAddress() as only local connections are of interest at that point. But in this case the findLocally method must be added to the ResumptionSupportingConnectionStore interface.

Here the part of the call stack that show where the useless cache lookup happens:
	at org.eclipse.californium.scandium.dtls.InMemoryConnectionStore.find(InMemoryConnectionStore.java:386)
	at org.eclipse.californium.scandium.DTLSConnector.isClientInControlOfSourceIpAddress(DTLSConnector.java:1455)
	at org.eclipse.californium.scandium.DTLSConnector.processNewClientHello(DTLSConnector.java:1322)
...

The issue is only on the 2.0 branch. I discovered it on the branch wip_add_dtls_cid.

Actually while trying out the session resumption I also discovered that you support the "connection id" feature from RFC https://datatracker.ietf.org/doc/draft-ietf-tls-dtls-connection-id.
Do you think this draft will be finalized any time soon?
Because this feature actually would make some of the DTLS session resumptions unnecessary as a change of port/ip does no longer interrupt an open DTLS session.

**Comment by boaks** [comment]
> But this cache lookup is actually useless because isClientInControlOfSourceIpAddress() wants to verify the peer address, but a new Connection initialized from a SessionTicket has never a peer address.

If you have a lot of time, read PR #751 and #768 

The short form:
Protection against spoofing requires something special. Usually this is achieved by the HELLO_VERIFY_REQUEST and the exchange of a stateless cookie. If a client want's to resume a session and presents a valid session id, this may also be considered to protect against spoofing. To guess a valid session id is equal to guess a valid cookie. The main difference will be the timespan, that information is valid, which is much longer for the session id. Therefore californium enables you to configure the wanted behaviour (see DtlsConnectorConfig.getVerifyPeersOnResumptionThreshold).

> As the cache lookup could be quite expensive (e.g. database call) this could be a performance issue.

May be, we can optimize the second call to reuse the result of the first. I would always recommend to not have any "expensive" calls in the handshake. If you have that, then please configure "VerifyPeersOnResumptionThreshold" to 0. I will add this to the javadoc there and in the `SessionCache`.

> Do you think this draft will be finalized any time soon?

That's a question for the tls@ietf.org mailing list. Or you create a issue in the github repo 
https://github.com/tlswg/dtls-conn-id with that question. With the discussion about the usage of empty CIDs I assume, that it will stay as it is defined now. The IANA registration numbers may changes.

For tests, to find out, if that's a solution for the future, it works quite well.

**Comment by AndreasHuber-CH** [comment]
Thanks for the response. I'll go with setting VerifyPeersOnResumptionThreshold to 0 for now.
And I'll see what I can do about 'slow' operations during the handshake.

I think I got also mixed up when I read the code. So I agree, that the cache lookup is needed in isClientInControlOfSourceIpAddress().
