### ISSUE TITLE
Consecutive early negociation blockwise requests

### ISSUE THREAD

**Issue by mb590721** [eclipse/californium#891]
My issue is based on branch 2.0.x but may be present since erlier on.

When making consecutives requests with early block2 blockwise negociation, the server respond to the following ones without forwarding them to the applicative layer.

It seems that the server forward it when making a request to another resource, the blockwise status lifetime and/or exchange lifetime are outdated.

I think it's the way the blockwise layer determine if it's a new blockwise request or part of an existing one for which new blocks are asked for. In the `BlockwiseLayer.receiveRequest` :
`
KeyUri key = getKey(exchange, request);

Block2BlockwiseStatus status = getBlock2Status(key);
`

Maybe it's intended but it's seems a little weird.

**Comment by mb590721** [comment]
See PR 892 with a dedicated test case

**Comment by boaks** [comment]
Also a good catch. :-).

**Comment by boaks** [comment]
Please check, if PR #893 works for you.

**Comment by mb590721** [comment]
@boaks 

Do you think of any workaround which could be implemented while waiting the next release ?
Decrease at the minimum possible the block2 status lifetime maybe ?

**Comment by boaks** [comment]
Hm, then I would prefer to release 2.0.0-M14 without the new cipher suites.

@sbernard31 
What do you think about a M14?

**Comment by mb590721** [comment]
I checked and reducing blockwise status lifetime would not really be a suitable solution for us anymay,

If you can release an M14 it would be great but otherwise we will rollback the migration and wait for its release.

By the way from what I saw it seems to be present since the M3.

**Comment by boaks** [comment]
I scheduled the M14 release for Friday, 8-March-2019 (see issue #900).
Though I want to ensure, the M14 will work with https://cloud.google.com/community/tutorials/cloud-iot-coap-proxy , I would like to postpone the M14 release to Monday, 11-March-2019. But only, if this doesn't effect you negative. So, please give me your feedback, if Monday is also OK for you.

**Comment by mb590721** [comment]
Monday is ok for us too, you can do as it fits better for you :-).

**Comment by boaks** [comment]
Great, thanks!

**Comment by boaks** [comment]
2.0.0-M14 is released. Please check it. If you have any trouble, don't hesitate to report it. If it works for you, I would appreciate, that the issue gets closed.

**Comment by mb590721** [comment]
I will make some tests tomorrow and keep you up-to-date.

**Comment by boaks** [comment]
Take all the time you need :-) !

**Comment by mb590721** [comment]
Hi,

Seems ok to me, I close the issue.

**Comment by boaks** [comment]
Thanks! Don't hesitate to report new issues, if you hit one :-).
