### ISSUE TITLE
Client Hello after Handshake crash 

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#9]
It seems the [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483371) was not completely fixed.

On Leshan sandbox, I regulary encounter this issue. Here is the log :  

    Feb 08, 2016 6:29:08 PM org.eclipse.californium.scandium.DTLSConnector processHandshakeRecordWithConnection
    FINE: Discarding HANDSHAKE message [epoch=0] from peer [/84.14.163.130:56830] which does not match expected epoch(s)

When this happen, the device will not be able to connect to the server with the same host/port...

I suspect the issue was [here](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L738).
I think we should not test if we have an established session, I mean if we get a Client_Hello with epoch 0 we probably want to do a fresh handshake.
The only case, we don't want that is if this is a retransmission but we have this [code](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L864) to prevent this.

**Comment by sbernard31** [comment]
I just test it and it seems that this fix the problem.

**Comment by sbernard31** [comment]
@sophokles73 , If you ok with that I would like to integrate [this](https://github.com/eclipse/californium/commits/fresh_handshake) in 1.0.x and released a 1.0.2 ?
What do you think ?

**Comment by sophokles73** [comment]
I would like to better understand under which circumstances a client's CLIENT_HELLO can end up being handled by [this line](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L742).

It seems like we are missing a particular case where
1) there already exists a `Connection` instance for the client's IP address
2) there is *no* ongoing handshake with the peer and
3) there is *no* established session yet.

I simply cannot imagine how this can happen. Can you?

**Comment by sbernard31** [comment]
I agree with you something strange happened, I will investigate this deeply later.
Maybe we are in the case we have an ongoing handshake with read epoch = 1 (just after the change cipher spec) and so no established session... (so we have an ongoing handshake bu read epoch is not equal to record.epoch)

But in all case, I think this code should be as robust as possible. And any CLIENT_HELLO with epoch =0 should restart an handshake. This will avoid any blocking state.

**Comment by sophokles73** [comment]
Fair enough. You should merge it to both *master* as well as *1.0.x* branch.
Before we are able to create a 1.0.2 release we need to adapt the release build in Hudson. It would probably be good if we did that together. What do you think, are you up for a session doing this together? Maybe tomorrow morning?

**Comment by sbernard31** [comment]
Ok I integrated it in 1.0.x branch and master.
For tomorrow morning, I'll be [there](https://webchat.freenode.net/?channels=californium) around 10:30 am, but you probably know the hudson build better than me :).

**Comment by sophokles73** [comment]
That's true and that's also the problem. I would like to share the knowledge with you so that in the future multiple people can work on it ... :-) I was thinking more about a WebEx session where we could share the screen and work together on the build in Hudson.I'll send you an invite tomorrow morning...

**Comment by jvermillard** [comment]
Good luck for running webex on Linux :D

**Comment by sophokles73** [comment]
We can also use Google Hangouts if that works better. However, I would need your google mail address for that purpose, @sbernard31 ...

**Comment by sophokles73** [comment]
fixed in 1.0.2 and on master
