### ISSUE TITLE
DTLS: Add access to server and client random in Handshaker

### ISSUE THREAD

**Issue by AndreasHuber-CH** [eclipse/californium#901]
Hi, 
we have a use case where we need to be able to access the server and client random values when a DTLS handhake is complete.
I found that these values are stored inside the Handshaker class which is passed to the SessionListener.

Would it be possible to add a public getter for the clientRandom and serverRandom fields in the Handshaker?

**Comment by boaks** [comment]
@sbernard31 
Any objection?

**Comment by sbernard31** [comment]
:+1:

**Comment by boaks** [comment]
Done, pushed to 2.0.x HEAD.

**Comment by AndreasHuber-CH** [comment]
Thanks a lot. Thats perfectly fine.
