### ISSUE TITLE
Scope of release 2.0 - 2019

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#905]
Since issue #556 of last year californium 2.0 (with java 1.7 promise) made much progress in stability and some in functionality. So I think, it's time to ask again for the "final set" of fixes and features for a
2.0 release.

One of the major topics seems to be the stability of the APIs.
From the experience of the last two year, the APIs will still slightly change.
I don't see, that this damages too much.

My open topics/issue:
- CoapClient - observer/notify - since the clustered-observe this seems to be somehow "in between".
- Deduplicator - those who tried the "extplugtest" benchmarks may have recognized, that a lot of heap is required for message-deduplication. One part may be to reduce the kept data, the other part will be to add an additional deduplicator based on `SoftReference` or something else, which will remove older messages even before the exchange time expires in order to be able to process new messages. Potentially we can also open the implementation to support "custom deduplicators".
- cleanup  of scandium, still in progress, may be postponed after the release.

Feel free to write your feedback, opinion,  or your requirements wish-list.

And no, 
- no DTLS 1.3 support for californium 2.0. I think, that should be moved into a 3.0 with java 11. There we have the basic crypto-functions to do so. 
- no LWM2M-1.1 stuff, the 2.0 is a base for leshan 1.0, and that's LWM2M 1.0. Any extensions, if contributed, will be applied to a later version.

**Comment by sbernard31** [comment]
> Potentially we can also open the implementation to support "custom deduplicators"

It could be a good approach.

About feature, I need to think more about https://github.com/eclipse/californium/issues/617

**Comment by boaks** [comment]
> About feature, I need to think more about #617

Please, consider to make it configurablet :-).

**Comment by boaks** [comment]
My current state:

> CoapClient - observer/notify - since the clustered-observe this seems to be somehow "in between".

I would prefer to go back to the simple old solution in the client before the clustered observe. I don't see easy implementations and no one else implemented something.
The solution with "many" handlers, each called to check it's token, has too many time penalties.

> Deduplicator

Still to be done.

> cleanup of scandium 

At least my open stuff may be merged at the end of next week.

So anything else open/wanted?

**Comment by boaks** [comment]
> Potentially we can also open the implementation to support "custom deduplicators".

I found, that this was already implemented in the `DeduplicatorFactory`.

**Comment by boaks** [comment]
[Forgotten issues in CoapClient](https://github.com/eclipse/californium/pull/532#discussion_r163281516)

I still think, that the javadoc fix would be an improvement.
