### ISSUE TITLE
Default cipher suites

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#909]
PR #904 adds some more cipher suites.
Though a client sends a list of its supported cipher suites in the CLIENT_HELLO, this may get larger and larger with every new added cipher suite. To prevent issues as #722, in my opinion it's a good idea to have a smaller selection as default.

PR #904 will offer several possibilities to configure, which cipher suites are use:
- explicit set the used cipher suites (`setSupportedCipherSuites`).
- select, if all cipher suites, which match the provided credentials, are supported (`setExtendedCipherSuites(true)`)
- or only the default  cipher suites, which match the provided credentials, are supported.
 
We're now discussing, which cipher suites should be the defaults.
The next comments will list the current possibilities. Please give your votes or propose alternatives.

Please use "Thumb up" on the comments you prefer most. All users, contributor or committers are allowed to vote. If you don't have a github account, you may use the mailing list  https://accounts.eclipse.org/mailing-list/cf-dev.

Seems, that multiple votes are wanted, so feel free to do so :-).

**Comment by boaks** [comment]
TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_PSK_WITH_AES_128_CCM_8
TLS_PSK_WITH_AES_128_CBC_SHA256

(if both, certificate and PSK credentials are provided)

**Comment by boaks** [comment]
TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8
TLS_PSK_WITH_AES_128_CCM_8

(if both, certificate and PSK credentials are provided)
That matches the mandatory cipher suites of RFC 7252.

**Comment by boaks** [comment]
"Don't introduce" / "Remove" `setExtendedCipherSuites` and always support all matching cipher suites.

**Comment by sbernard31** [comment]
FMPOV, this is a CoAP library so default LWM2M cipher is out of scope.

And by the way there is [known security issue with CBC based cipher suites](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/6#issuecomment-243403391) without [rfc7366](https://tools.ietf.org/html/rfc7366) (which is not supported in Scandium).

> To prevent issues as #722

For now the list is pretty short, so this is not really an issue to just use all cipher by default. (except if we plan to add lot of more ciphers for the 2.0.0)

**Comment by boaks** [comment]
@sbernard31 

asking my colleague was not that successful :-). 
Fell free to ask one of your colleague to vote.

**Comment by sbernard31** [comment]
@DanielMaier-BSI, if you could explain your choice ? I'm more interested by the reasons than the vote itself :)

**Comment by msangoi** [comment]
I voted for #3 because I'm in favor of simple configuration. The user can easily restrict the list if required.

**Comment by boaks** [comment]
Thanks for voting!

should we keep it open for a week or should we take the result?

**Comment by boaks** [comment]
> in favor of simple configuration.

That was my idea :-) 
Simple for the server to support all by just use the boolean. 
Simple for the client to use, what usually should be supported to keep the client hello as small as possible.
But OK, this could be also achieved bx explicit providing the cipher suite.

**Comment by DanielMaier-BSI** [comment]
I voted for #3 because of simplicity for users. If the user wants to change something he needs to explicitly provide the supported cipher suites. And no one comes to the idea to set both `setSupportedCipherSuites` and `setExtendedCipherSuites`.

Option #1 I only chose because it is the same as in californium 1.0. But as I said I don't really like the two configuration options `setSupportedCipherSuites` and `setExtendedCipherSuites`. So my favorite would be more option #3 :).

**Comment by sbernard31** [comment]
> should we keep it open for a week or should we take the result?

@boaks,  As you want but I suspect there will be no more vote.

**Comment by boaks** [comment]
> there will be no more vote.

Yes, so the voting is closed :-). 
3 is elected. 
I will remove the "extended" stuff :-)

**Comment by boaks** [comment]
PR merged.
