### ISSUE TITLE
sc-dtls-example demo app not working properly?

### ISSUE THREAD

**Issue by sudeepta-bhuyan** [eclipse/californium#91]
I built Cf project from source and wanted to try out the demo app for DTLS. If I try to run sc-dtls-example-1.1.0-SNAPSHOT.jar , I can only see ExampleDTLSServer prints. There are no ExampleDTLSClient prints:

_sudeepta@Sudeepta-ThinkStation-P300:~/californium/demo-apps/run$ java -jar sc-dtls-example-1.1.0-SNAPSHOT.jar 
 1 CONFIG [DTLSConnector]: Cannot determine MTU of network interface, using minimum MTU [1280] of IPv6 instead - (org.eclipse.californium.scandium.DTLSConnector.java:331) start() in thread main at (2016-09-17 14:36:34)
 1 INFO [DTLSConnector]: DTLS connector listening on [0.0.0.0/0.0.0.0:5684] with MTU [1,280] using (inbound) datagram buffer size [16,474 bytes] - (org.eclipse.californium.scandium.DTLSConnector.java:281) start() in thread main at (2016-09-17 14:36:34)
 9 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Sender-0.0.0.0/0.0.0.0:5684] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Sender-0.0.0.0/0.0.0.0:5684 at (2016-09-17 14:36:34)
10 CONFIG [DTLSConnector$Worker]: Starting worker thread [DTLS-Receiver-0.0.0.0/0.0.0.0:5684] - (org.eclipse.californium.scandium.DTLSConnector$Worker.java:-1) run() in thread DTLS-Receiver-0.0.0.0/0.0.0.0:5684 at (2016-09-17 14:36:34)_

NOTE: For other examples in the demo-app directory, seperate jars for client and server get created (for e.g. cf-helloworld-client-1.1.0-SNAPSHOT.jar and cf-helloworld-server-1.1.0-SNAPSHOT.jar). But for sc-dtls-example only one jar gets created.

**Comment by sophokles73** [comment]
You can run the client by specifying the class to run on the command line (from the `run` folder you are running the server from).

````
java -cp sc-dtls-example-1.1.0-SNAPSHOT.jar org.eclipse.californium.scandium.examples.ExampleDTLSClient
````

Since you already have diagnosed the problem, i.e. we are not creating separate jars for server and client, maybe you feel inclined to provide a PR for doing so?

**Comment by sudeepta-bhuyan** [comment]
Sure. I will do that. Thanks for your response.

**Comment by sophokles73** [comment]
Looking forward to it :-)
