### ISSUE TITLE
Build issue with californium-legal-2.0.0-M14-sources.jar artifact

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#910]
Trying to build leshan with `mvn clean install -Pall` with the californium 2.0.0-M4, I get this error :
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:
shade (default) on project leshan-all: 
Error creating shaded jar: error in opening zip 
file /...../californium-legal/2.0.0-M14/californium-legal-2.0.0-M14-sources.jar -> [Help 1]
```

It seems there is any issue with this jar but didn't find what for now. 
(Error is reproduced in local or on jenkins)

Reading the `pom.xml` of californium-legal :
```xml
<properties>
	<source.skip>true</source.skip>
	<javadoc.skip>true</javadoc.skip>
</properties>
```
I guess, maybe generating this source.jar was not intended.

(I have a workaround for now : https://github.com/eclipse/leshan/commit/eb75fc8b7d5560944e6d532f1a09d5e5c6e54559)

**Comment by boaks** [comment]
Using

```
<maven.source.skip>true</maven.source.skip>
<maven.javadoc.skip>true</maven.javadoc.skip>
```

the source.jar will not longer be created. I adjust demo-certs also.
We will see, if that helps with the next milestone.

**Comment by sbernard31** [comment]
Tested in local with 2.0.0-SNAPSHOT version and it seems ok!

**Comment by boaks** [comment]
In the meantime I assume, that the deployment wasn't successfully completed caused by "temporary unknown issues". That may be wrong, because the eclipse repo has also the broken jar.
Next time I will check that before I release the artefacts. May be that brings then more light into this issue.

**Comment by sbernard31** [comment]
I made some tests building Leshan (without [workaround](https://github.com/eclipse/leshan/commit/eb75fc8b7d5560944e6d532f1a09d5e5c6e54559)) and removing `~/.m2/repository/org/eclipse/californium/` between each tests :
- getting californium M14 from maven central :   :x: leshan build failed
- building californium M14 locally : :heavy_check_mark:  leshan build succeed
- building californium SNAPSHOT with your fix locally : :heavy_check_mark: leshan build succeed 

I confirmed that before your fix a `sources.jar` was generated and after your fix sources-jar is not generated.

Anyway, I guess you right about broken jar in maven.repository ... It's a bit freaky :scream: ...
Did you face any issue when you release 2.0.0-M14 ?

**Comment by boaks** [comment]
> Did you face any issue when you release 2.0.0-M14 ?

I tried to check my latest changes but these tries overwrote the job of the M14 deploy.
Therefore I'm not sure, if this was only a unclosed deployment.

Right now I checked, if https://search.maven.org/remotecontent?filepath=org/eclipse/californium/californium-legal/2.0.0-M14/californium-legal-2.0.0-M14-sources.jar is smaller than a locally build jar. To my complete surprise, the downloaded jar is not longer broken :-). 

Which leshan branch/commit your are using, so I can retest it again?

**Comment by sbernard31** [comment]
Any commit between https://github.com/eclipse/leshan/commit /eb75fc8b7d5560944e6d532f1a09d5e5c6e54559 and https://github.com/eclipse/leshan/commit/d00ad25baa0c190fc1fe600f964751f337098ff6

see : https://github.com/eclipse/leshan/commits/master

Do not forget to launch the build with `-Pall`

**Comment by boaks** [comment]
```
Caused by: java.util.zip.ZipException: error in opening zip file californium-legal-2.0.0-M14-sources.jar
```

7-zip repairs the jar, but the jar is still broken.
So, just wait for M15 and see what happens.
