### ISSUE TITLE
Redesign ByteId of cf-oscore to extend Bytes

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#913]
Branch 2.0.x:

In the meantime californium has a central implementation for byte array based ids:

https://github.com/eclipse/californium/blob/2.0.x/element-connector/src/main/java/org/eclipse/californium/elements/util/Bytes.java

I would appreciate, if redesign of `ByteId` extending `Bytes` is analyzed and if it works, a PR is created. 

See Token, SessionId, or ConnectionId for examples.

@rikard-sics 
May be you can spend some time in it :-).

**Comment by rikard-sics** [comment]
> May be you can spend some time in it :-).

Sure, I can take a look at this for a future PR.

**Comment by boaks** [comment]
Thanks!

**Comment by rikard-sics** [comment]
I have now created a pull request to solve this issue:
https://github.com/eclipse/californium/pull/921

**Comment by boaks** [comment]
Fixed with PR #921
