### ISSUE TITLE
ci-eclipse jenkins e-mails to cf-dev

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#915]
Currently the ci-eclipse jenkins build jobs send e-mails to cf-dev mailing list, if the status of the builds changes. Though the jenkins is a "busy shared instance", tests, which assume something to happen in time, frequently fails.
e.g.:
test response for request within 2s, usually successful, but fails, if the test doesn't get the "shared" CPU for 3s.

To ensure the quality, I run the test frequently on none shared private instances. Depending on the instances resource, the tests fail there very rare:
- Raspberry Pi 3B (4x1.2Ghz at 1GB Ram) => 800 tests builds -> 2 failures
- Asus Tinker (4x1.8Ghz at 2GB Ram) => 800 tests builds -> 1 failures
- j4205 (4x1.5 GHz at 8GB Ram) => 800 tests builds -> 0 failures

Today cf-dev received the first complains about these build-mails to the cf-dev mailing list.
 Therefore I would like to ask the users, if it's preferred to have these build mails on the list, or not. Please give us your feedback/vote. 

Please use thumb up below.

**Comment by boaks** [comment]
stop build mails to cf-dev list.

**Comment by boaks** [comment]
continue with build mails to cf-dev list.

**Comment by sbernard31** [comment]
I could understand that for users this could be considered as annoying information.

I think there is maybe 2 kind of informations :
   - for committers/developpers of californium itself
   - for users of californium.

Some projects use 2 kind of mailing list ***-dev** and ***-users** but in our case users are using the only one cf-dev mailing list.(even if it is defined as [a developer discussions mailing list](https://accounts.eclipse.org/mailing-list/cf-dev))

At Leshan we are using an hidden **leshan-commit** mailing list for committers which recently [disappeared](https://bugs.eclipse.org/bugs/show_bug.cgi?id=545541)  by the way ...

We could use those kind of solution for Californium or as we are for now only 2 committers really involved we can just add directly our 2 email addresses in jenkins job configuration.

**Comment by boaks** [comment]
OK, so wait a couple of days. If no-one  votes for "continue with build mails to cf-dev list." I reconfigure the jenkins for your and my mail.

**Comment by boaks** [comment]
So go for e-mails to you and me :-)
Your "@sierrawireless.com" ?

**Comment by sbernard31** [comment]
Yep :)

**Comment by boaks** [comment]
Done.
