### ISSUE TITLE
configured NOTIFICATION_REREGISTRATION_BACKOFF value has no effect

### ISSUE THREAD

**Issue by rogierc** [eclipse/californium#917]
Testing Mule CoAP Connector using Californium 2.0.0-M14 showed that setting NOTIFICATION_REREGISTRATION_BACKOFF in the endpoint configuration to another value than 2000 ms, has no effect on the actual re-registration timing. The backoff time always remains the default of 2 seconds.

I've made a test independent of Mule CoAP Connector to show the Cf issue. It counts the number of reregistrations that happen during the defined test period and compares it with the expected number, taking the configured backoff into account. See:
https://github.com/rogierc/californium/blob/reregistration_issue/californium-core/src/test/java/org/eclipse/californium/core/test/NotificationReregistrationBackoffTest.java

The test only succeeds when backoff is set to 2000 ms

It seems that a fixed value is implemented in CoapObserveRelation. Possible fix could be: add a member to hold the configured value. See:
https://github.com/rogierc/californium/blob/reregistration_issue/californium-core/src/main/java/org/eclipse/californium/core/CoapObserveRelation.java

Question: CoapObserveRelation.prepareReregistration method has a backoff parameter. Is it needed, or could it just use the member value?

**Comment by boaks** [comment]
Thanks! Good catch. Would it be possible, that your prepare a PR with your changes?

(Just one remark: RFC7641 has pros and cons. In the most common cloud scenario "device, dtls client, coap-both" - "cloud, dtls-server, coap-both" it establishes a "long term reverse coap-client-server" relation (device coap-server, cloud coap-client). That causes a lot of pain. At least, I don't recommend to use it in a large scale deployment.)

**Comment by rogierc** [comment]
OK, I 'll make a PR.
Any opinions on the prepareReregistration method question? 
Should I let the 'backoff ' parameter be, or remove? I don't see added value of the parameter, but it could be there for a reason...

RFC7641 is IMHO a powerfull feature (indeed, powerfull could very well also mean "handle with care"). It enables a client to get updated with minimal latency, valuable when responsiveness is important. Polling also has its cons (latency, more networktraffic), but client has more controll over timing and no long term memory use on server side.
What kind of pain did you experience?

**Comment by boaks** [comment]
> Any opinions on the prepareReregistration method question?

Uups, sorry I missed the question. Yes, your right, using the introduced field and remove the parameter makes sense. Please modify it.

**Comment by boaks** [comment]
> RFC7641 is IMHO a powerfull feature ... Polling 

In CoAP, you don't need to poll, because in many cases the endpoints are mixed endpoints with coap-server and coap-clients. So at least on application layer it's easy to implement such updates by usual coap-request from the device as coap-client. There is no need to poll, but it would be application specific (at least for now, may be in the future such approaches may be also standardized). This may also be easier too support on a cluster, depending on the application specific definition.

Notifies are special responses but must match https://tools.ietf.org/html/rfc7252#section-5.3 and https://tools.ietf.org/html/rfc7252#section-9.1.2 .
Especially 9.1.2 was discussed over the years (see https://mailarchive.ietf.org/arch/msg/core/h8NoXBwt3ttVkB5QZglMoW6Y--Y). FMPOV, it depends too much from the setup (e.g. DTLS using unique principals) to be solved in a general way. For californium we implemented the "EndpointContextMatcher" for that. It must be used according your setup. @sbernard31 wrote a very good explanation how it is used in leshan https://github.com/eclipse/leshan/wiki/LWM2M-Observe .

**Comment by rogierc** [comment]
OK, mixed enpoints is another way. (with a less clear client/server-role separation, though) 
Thanks for the info and links!!

**Comment by boaks** [comment]
the usage of RFC7641 really depends on your setup. How many devices, how long the observation should last. Restarts and NAT changed addresses will get more significant, as longer the observation should last. Move the mechanism into the application layer enables the application to care on its own.

**Comment by rogierc** [comment]
PR is issued.

**Comment by rogierc** [comment]
> really depends on your setup

Clear

> How many devices

Is there maybe an empirical rule-of-thumb, order of magnitude ?

> Move the mechanism into the application layer enables the application to care on its own

Of course, but evidently the point of having such a feature in the protocol is that the application layer has less complexity. If the feature works, that is ;-)  Using sensible max_age, notification check interval, reregistration timing, will be paramount for that. When network gets unreliable, NAT, etc, things can get difficult, sure...  no silver bullets ;-)

**Comment by boaks** [comment]
> Is there maybe an empirical rule-of-thumb, order of magnitude ?

Depends on the used machine.
With the current implementation using a `CoapClient.Adapter` for each observe-request  and iterates over them in `CoapEndpoint.NotificationDispatcher` I would go for several dozen up to a few hundred notifications per seconds. 
If that is implemented in a more optimized way, I would go for a few thousands.
Depending on the assumed changes, this would be good for several hundred or a few thousand devices.
I'm very interested in feedback on this topic. May be, if you use it for sometime, you can provide us your experience.

**Comment by rogierc** [comment]
>you can provide us your experience.

Our deployment is small (few dozen) right know, but should grow to many thousands in the coming years. I 'll let you know... 

>many cases the endpoints are mixed endpoints

These cases, do they use seperate DTLS sessions / endpoints or literally one and the same for client and server operations? Haven't tried to use just one endpoint for both coap-client and coap-server - wondering whether it's possible / advisable.

**Comment by boaks** [comment]
I use a common endpoint for both. The message.typ and message.code https://tools.ietf.org/html/rfc7252#section-3 is used to distinguish between incoming request. 

LWM2M uses that approach now for a couple of years!
The device start as dtls-client/coap-client sending a registration request.
The server then starts to send request to that device and exchange therefore the roles server => coap-client, device => coap-server.

**Comment by boaks** [comment]
Fixed with the PR #919 

Thanks!
