### ISSUE TITLE
CoapClient.synchronous() exceptions could probably be improved

### ISSUE THREAD

**Issue by aml2610** [eclipse/californium#920]
Hi again!

I am using the M13 snapshot, but can see the same code on the development branch. `CoapClient.synchronous()` will throw a `RuntimeException` no matter what error is extracted from the request:

```
if (sendError != null) {
    throw new RuntimeException(sendError);
}
```

There are cases where it does not make sense to crash, and by throwing a Runtime the user will not be aware these cases can happen.
One such case is when the network is unreachable (i.e you try to make a synchronous request to an unreachable IP), the request will then fail "silently" throwing a Runtime exception which could cause the user's app to crash.
In that case I think it makes more sense for the user to be "forced" to become aware of the failure so that they can re-try to send the request.

I can see two possibilities for this improvement:
1. In my example, network unreachable is actually a checked exception, so maybe a checked exception could be re-thrown when the exception on the request is also checked. I realise you don't want to add all potential exceptions to the method signature but could wrap them all in a single, checked exception, and add that to the signature.
2. A second solution would be to just return null if the exception on the request is a checked one. This way when the user gets back null he knows he can re-try. (I am not completely convinced this would work)

What do you guys think?

**Comment by boaks** [comment]
Good catch!

I see IOException, then the californium specific EndpointMismatchException, EndpointUnconnectedException, and MulticastNotSupportedException, and finally the DTLS exceptions. The later seems to be the most "undesigned" part. My feeling is, correcting the "exception handling" in scandium internals will be a large job :-). Anyway, may be IOException and a newly introduced ConnectorException will do a much better job than RuntimeException now. And may be in the future scandium could be also adjusted. The californium specific exception may be changed to extend that new ConnectorException.

@sbernard31 
What do you think?

**Comment by sbernard31** [comment]
> Anyway, may be IOException and a newly introduced ConnectorException will do a much better job than RuntimeException now

It sounds good.

I think the more important is to :
 - raise specific exception(s) (like a new ConnectorException)
 - add documentation.

So, If adding checked exception is "too impacting", starting with more specific documented unchecked exception it's fine too me. 

Personally, I have no strong opinion about : raising checked or unchecked exception.  I mean it's possible to create a usable API using unchecked exception. (By the way in the jvm you could find source code where unchecked exception is used, visible in the method signature and well documented in the javadoc : https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#parseInt(java.lang.String)).

E.g. You can also have a look at [the way we do in Leshan](https://github.com/eclipse/leshan/blob/leshan-1.0.0-M10/leshan-server-core/src/main/java/org/eclipse/leshan/server/LwM2mServer.java#L63), we have more high level exception and details is available in the "cause".
Reading this I see I missed to add the new `SendFailedException` to the javadoc :grin:.

**Comment by aml2610** [comment]
> I mean it's possible to create a usable API using unchecked exception.

Just a matter of preference really. One of the approaches forces you to deal with it, other one assumes you will do the sensible thing if you read the documentation.

I personally always opt for the solution which "forces" me to do the right thing since it's one less issue to worry about really 😃 

With that in mind, documented, specific, unchecked exceptions are indeed a good start if we cannot add the checked one. I am happy with either.

Also, I did not mention, I am happy to contribute

**Comment by boaks** [comment]
> Also, I did not mention, I am happy to contribute

If you contribute it,you're free to chose the approach you prefer :-). 
I will support your decision.
