### ISSUE TITLE
All MIDs are in use when probing a CoAP-to-CoAP Proxy

### ISSUE THREAD

**Issue by caff93** [eclipse/californium#922]
Hi,
I'm testing a CoAP to CoAP reverse proxy and I face this issue: all MIDs become busy and simulation freezes. 
I'm testing my proxy with the JMeter tool with about 300 concurrent threads.
The weird thing is that with even much larger number of threads, when I probe the server, it works just fine.
N.B: I use modified version of cf-helloworld-server and cf-proxy.

Thank you so much.

**Comment by boaks** [comment]
Check, if

https://github.com/eclipse/californium/issues/883#issuecomment-465739905

explains the behavior. If not, provide the requested information, e.g. version, logs.

(I assume, the number of coap endpoints is related to the number of threads. Though the number of messages per endpoint per second is limited, a larger number of threads using a larger number of endpoints results in a larger number of messages.)

**Comment by caff93** [comment]
I already checked the issue you mentioned but i didn't have any luck finding a solution.
So my topology is build up by a Proxy and a Server running on two different Raspberries (for a school project).  We are running two "stress" test, one involving the server and one involving the proxy.
Concerning the server, no matter what the requests are (CON, NON), I face no issue and everything works smoothly, but when I run the same test on the proxy at a certain point I run out of MIDs. More specifically, in case of NON Request I got the "InMemoryMessageExchangeStore assignMessageID WARNING: Cannot send message to (IP address) all MIDs are in use" while in case of CON Request my simulation just stops for a while and then restarts following this pattern for the entirely duration of the test.

The test is executed by JMeter with 300 conccurent threads over 5 minutes time.

The Californium version I use is 1.1.0-SNAPSHOT
The proxy is a modified version of cf-proxy I created while the server is a modified version of cf-helloworld-server.

This is my proxy.java
Hope you can help me figuring this out.

`public class MyProxy extends CoapServer { 

	private static final int COAP_PORT = NetworkConfig.getStandard().getInt("PROXY_PORT", 5683);
	Cache cache = new Cache();
    /*
     * Application entry point.
     */
    public static void main(String[] args) {
        
        try {
            // create server
            MyProxy myProxy = new MyProxy();
            // add endpoints on all IP addresses
            myProxy.addEndpoints();
            myProxy.start();

        } catch (SocketException e) {
            System.err.println("Failed to initialize server: " + e.getMessage());
        }
    }

    /**
     * Add individual endpoints listening on default CoAP port on all IPv4 addresses of all network interfaces.
     */
    
    private void addEndpoints() {
    	for (InetAddress addr : EndpointManager.getEndpointManager().getNetworkInterfaces()) {
    		// only binds to IPv4 addresses and localhost
			if (addr instanceof Inet4Address || addr.isLoopbackAddress()) {
				InetSocketAddress bindToAddress = new InetSocketAddress(addr, COAP_PORT);
				addEndpoint(new CoapEndpoint(bindToAddress));
			}
		}
    }
	
    /*
     * Constructor for a new Remote server. Here, the resources
     * of the server are initialized.
     */

    public MyProxy() throws SocketException {
        
        // ( CREO IL GESTORE DELLA RISORSA DA OSSERVARE ...
        CoapClient client = new CoapClient("coap://127.0.0.1:5683/temperature");
             
        add(new RemoteResource());
    }
	
    /*
     * Definition of the Remote Resource
     */
    class RemoteResource extends CoapResource {
        
        public RemoteResource() {
            
            // set resource identifier
            super("temperature");
            
            // set display name
            getAttributes().setTitle("PROXY (NO Resource)");
        }
        
        @Override
        public void handleGET(CoapExchange exchange) {
        
        	if(System.currentTimeMillis() - cache.getLastUpdate() < 1000*cache.getMaxAge()){
        		// USO IL DATO IN CACHE
        		exchange.respond(cache.getValue() +"(DA PROXY - CACHE)");
        		return;
        	}
        	
        	try{	// QUESTI PASSAGGI DOVRANNO ANDARE IN UN THREAD ANONIMO
		        // ESTRAGGO I PARAMETRI DI exchange
		        
		        Request request = exchange.advanced().getRequest();
		        System.out.println("Requested URI: " + request.getURI());
		        URI uri = new URI(request.getURI());
		        System.out.println("Path: " + uri.getPath()); // Restituice il path (la risorsa)
		        
		        CoapClient client = new CoapClient(new URI("coap://192.168.56.10:5683"+uri.getPath()));
		        CoapResponse response = client.get();
		        
				if (response!=null) {
				
					System.out.println(response.getCode());

					System.out.println("Origin Server Resource: " + response.getResponseText());
				
					System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
					System.out.println("MAX-AGE: " + response.getOptions().getMaxAge());
					cache.update(response.getResponseText(), response.getOptions().getMaxAge());
					System.out.println(Utils.prettyPrint(response));
					
					
				} else {
					System.out.println("No response received.");
				}
		        
		        // respond to the request
		        exchange.respond(response.getResponseText()+"(DA PROXY)");
            } catch(URISyntaxException e){
            	System.err.println("Failed to initialize URI: " + e.getMessage());
            }
        }
    }
    
    class Cache{
    
    	private String value;
    	private long lastUpdate;
    	private long maxAge;
    	
    	public Cache(){
    		value = "";
    		lastUpdate = 0;
    		maxAge = 0;
    	}
    	// PER ORA NON INSERISCO IL COSTRUTTORE (USO QUELLO DI DEFAULT)
    	public void update(String value, long maxAge){
    		this.value = value;
    		this.maxAge = maxAge;
    		lastUpdate = System.currentTimeMillis();
    	}
    	
    	public long getLastUpdate(){
    		return lastUpdate;
    	}
    	
    	public long getMaxAge(){
    		return maxAge;
		}
		
		public String getValue(){
			return value;
		}
 }
}`

**Comment by boaks** [comment]
> (for a school project)

Do you want the solution or assistance, to solve it on your own?

I would go for analyse the traffic from JMeter (without proxy). How many different source-ports do you see (a source endpoint is defined by it's ip-address and port, so every port is a own endpoint).

If you enable your proxy and analyse the traffic outgoing from the proxy, how many source-ports do you see?

You may use wireshark, tcpdump or californium's `MessageTracer` (add it to the endpoints, easy for the server. For the proxy client the default endpoint maintained by the `EndpointManager` is used, so add it to that).

**Comment by boaks** [comment]
If you can spend some time afterwards, I would recommend, that you repeat your test with the 
2.0.x-SNAPSHOT or 2.0.0-M14.

**Comment by caff93** [comment]
Hi, 
thank you for your answer. I'd like to have the solution,

Concerning what you aked me above here is traffic analysis regarding the server.
<img width="1182" alt="Screenshot 2019-04-02 at 11 50 15" src="https://user-images.githubusercontent.com/48949869/55393629-e7183480-553d-11e9-9dcd-46005e7d971f.png">
<img width="293" alt="Screenshot 2019-04-02 at 11 50 36" src="https://user-images.githubusercontent.com/48949869/55393632-e7b0cb00-553d-11e9-988a-ef0d6681c1f6.png">

How you can see the source port remains the same for all the concurrent requests by JMeter.

Now, the proxy:
![prova](https://user-images.githubusercontent.com/48949869/55394156-f21f9480-553e-11e9-8af2-e3c32864ead7.png)
<img width="279" alt="Screenshot 2019-04-02 at 11 59 05" src="https://user-images.githubusercontent.com/48949869/55394158-f2b82b00-553e-11e9-9cd5-88af7a4e0650.png">

The first figure is the result from the JMeter test. After 44 seconds it stops sending the temperature.
I just don't know why the proxy behaviour is so different from the server

What did I do wrong?

**Comment by boaks** [comment]
I guess, the issue is your JMeter plugin. 
Does it wait for the responses using CON? But not using NON?
And though the JMeter uses only one client endpoint, your limited as explained in the 

https://github.com/eclipse/californium/issues/883#issuecomment-465739905

or in

https://github.com/eclipse/californium/issues/814

(Using a raspberry PI may also limit the throughput even if multiple client endpoints are used.
The data for deduplication is stored in the java heap and even a 1GB RAM pi may overfill that deduplication table. But with one endpoint, that should be not the bottleneck.)

**Comment by caff93** [comment]
If JMeter is the problem (and now I think it is) can you suggest me some other tools to simulate server/proxy coap performance?

**Comment by boaks** [comment]
If you can switch to branch 2.0.x-SNAPSHOT or 2.0.0-M14 you will find a benchmark client, which uses multiple endpoints. 

See demo-apps/cf-extplugtest-client BenchmarkClient.

It uses CON POST

For NON GET it must be patched ;-(.

```
final Request post = Request.newPost();
post.setURI(client.getURI());
```

to

```
final Request post = Request.newGet();
post.setType(CoAP.Type.NON);
post.setURI(client.getURI());
```

(in all places :-) ).

**Comment by boaks** [comment]
if your only interested in a "theoretical maximum", you may also switch of the deduplication.
Edit `Californium.properties` and change.

```
DEDUPLICATOR=DEDUPLICATOR_MARK_AND_SWEEP
```

into 

```
DEDUPLICATOR=NO_DEDUPLICATOR
```

**Comment by boaks** [comment]
May be, you show also your JMeter Plugin. CoapClients could be setup to use their own endpoints ( `CoapClient.setEndpoint(Endpoint)` ).

**Comment by caff93** [comment]
Hi, thanks to your suggestions I was able to find this JMeter Plugin.

https://github.com/Tanganelli/jmeter-coap

When I run the test It uses different endpoints as you can see in the figure below, so now it works as I expected. 
![Untitled](https://user-images.githubusercontent.com/48949869/55541526-769c1f80-56c5-11e9-8ed9-90ac2554bb32.png)

Last thing: the Proxy response time, when my 5 minutes test approaches to the end, grows up too fast.
Why is that, in your opinion?

Attached, the response time
![Response Times Over Time](https://user-images.githubusercontent.com/48949869/55542046-87996080-56c6-11e9-9142-806ffbf2efeb.png)

**Comment by boaks** [comment]
Did you adjust the configuration in `Californium.properties` ?
If not, just try

`DEDUPLICATOR=NO_DEDUPLICATOR`

**Comment by caff93** [comment]
Should I adjust the `Califorium.properties` present in JMeter?

**Comment by caff93** [comment]
Is there a way I can do it without change this without Californium.properties? 
(I execute the server through Dockerfile in a Raspberry, so I can't see where the Californium.properties got created)

**Comment by boaks** [comment]
At the very beginning of `main`:

```
NetworkConfig config = NetworkConfig.createStandardWithoutFile();
config.setLong(NetworkConfig.Keys.EXCHANGE_LIFETIME, 10000); // ms
```

or

```
NetworkConfig config = NetworkConfig.createStandardWithoutFile();
config.setString(NetworkConfig.Keys.DEDUPLICATOR, "NO_DEDUPLICATOR");
```

May be, if the "NO_DEDUPLICATOR" doesn't work on it 's own, add also
```
config.setString(NetworkConfig.Keys.MID_TACKER, "NULL");
```

**Comment by caff93** [comment]
Okay, I did it. Now, testing on my Mac it creates me the Californium properties file, but in the DEDUPLICATOR option there is DEDUPLICATOR_MARK_AND_SWEEP. 
Is that normal?

This is my main
`public static void main(String[] args) {
 
    	NetworkConfig config = NetworkConfig.createStandardWithoutFile();
    	//config.setLong(NetworkConfig.Keys.EXCHANGE_LIFETIME, 10000); // ms
    	config.setString(NetworkConfig.Keys.DEDUPLICATOR, "NO_DEDUPLICATOR");
    	//config.setString(NetworkConfig.Keys.MID_TACKER, "NULL");
        
        try {
            // create server
            TemperatureServer server = new TemperatureServer();
            // add endpoints on all IP addresses
            server.addEndpoints();
            server.start();

        } catch (SocketException e) {
            System.err.println("Failed to initialize server: " + e.getMessage());
        }
    }`

**Comment by boaks** [comment]
> in the DEDUPLICATOR option there is DEDUPLICATOR_MARK_AND_SWEEP. Is that normal?

That's the default value. Could you delete it and retry?

**Comment by boaks** [comment]
```
private static final int COAP_PORT = NetworkConfig.getStandard().getInt("PROXY_PORT", 5683);
```

Sorry, I overseen that. Please move that into the main behind your config setup! Requires either removing `final` or you convert the port into a parameter of `addEndpoints()`.

**Comment by caff93** [comment]
Thank you, now it works as expected.

Could you please me some additional information about the DEDUPLICATOR and what the differences between NO_DEDUPLICATOR and DEDUPLICATOR_MARK_AND_SWEEP?

**Comment by boaks** [comment]
UDP doesn't come with a "build in reliability". Therefore CoAP introduces CON messages, which may be repeated, if no ACK is received. But it's not only the request, which may be dropped, it's also possible, that the request reaches the server, but the ACK is dropped. In that case the client can't distinguish and will resend its request. With the NO_DEDUPLICATOR the server potentially processes the request again and may send even a altered ACK. With deduplication the server keeps the first ACK and would resend that, if it receives the request again. The "keep the ACK" may require some heap, especially, if piggybacked responses are used as ACK. And performance tests frequently tries to send as much as possible. But a raspi doesn't have enough RAM for the heap. Therefore benchmarks with less RAM is not possible. 

https://tools.ietf.org/html/rfc7252#section-4.2

There are also some other cases, e.g. send a RST to indicate, that the message could not be processed. Therefore not only CON messages are using a MID.

**Comment by caff93** [comment]
Okay, now it's all clear.
You have been very helpful!

Thank you so much.
