### ISSUE TITLE
californium-proxy as a reverse proxy

### ISSUE THREAD

**Issue by andreas1327250** [eclipse/californium#929]
Hi!

I want to use californium-proxy to set up a CoAP-HTTP-Proxy for Matrix (matrix.org). The CoAP-specification says that a proxy can be a forward proxy (using the proxy-uri option) or a reverse proxy.

I want to make my proxy configurable as both (by just passing the target-host as an environment variable in the reverse proxy case). But in "ProxyHttpClientResource.java", the forwardRequest-method starts with:

"if (!incomingCoapRequest.getOptions().hasProxyUri()) {"

also the HttpHost isn't configurable at all. Am I missing something? Is using calfifornium-proxy as a reverse proxy possible somehow else?

And a second question: in "HttpClientFactory.java", createCustomRequestConfig() sets the default socket timeout to 500 ms, which I always run into - is this value configurable somehow?

Thanks in advance!

(I am using the 2.0.0-M14-release from mvn central)

**Comment by boaks** [comment]
> I want to make my proxy configurable as both (by just passing the target-host as an environment variable in the reverse proxy case). But in "ProxyHttpClientResource.java", the forwardRequest-method starts with:
> 
> "if (!incomingCoapRequest.getOptions().hasProxyUri()) {"
> 
> also the HttpHost isn't configurable at all. Am I missing something? Is using calfifornium-proxy as a reverse proxy possible somehow else?

I'm not too deep into the proxy function, so I'm not sure, if this helps:

In my understanding `ProxyHttpClientResource` is a CoAP resource, which converts the CoAP request into a HTTP request. It's a generic "solution", where the HTTP target URL is provided in the CoAP option "Proxy-Uri/Proxy-Scheme", as specified in https://tools.ietf.org/html/rfc7252#section-5.7. 

The "reverse proxy" (http -> coap) is implemented in `HtppStack`, and the the transformation is done in 
`public Request HttpTranslator.getCoapRequest(HttpRequest httpRequest, String proxyResource, boolean proxyingEnabled) throws TranslationException`. My understanding is, that the coap-URI is derived from the http-URI.

> And a second question: in "HttpClientFactory.java", createCustomRequestConfig() sets the default socket timeout to 500 ms, which I always run into - is this value configurable somehow?

Seems so, that it is compiled in. But longer timeouts may also cause CoAP retransmissions, if a CON request is used. That should not harm unless it exceeds several seconds, except that there is more traffic
from the retransmissions.

**Comment by andreas1327250** [comment]
Thanks for the answer!

I meant reverse-proxy in the sense of "the client is not aware that it is talking to a proxy".
Like it is defined in 5.7.3:
https://tools.ietf.org/html/rfc7252#section-5.7.3

**Comment by boaks** [comment]
No, that implementation seems to be a "generic proxy" where the client must know that. 
If you need something else, you may just try to add your specific handler to the http stack.
And, though this is an open source project, if you like to contribute it, your welcome :-).

**Comment by andreas1327250** [comment]
So, we would need a config-flag: Reverse-proxy: true or something. Where would be the place to put this? In NetworkConfig via the Californium.properties? And I maybe could also add the http client timeout settings there?

**Comment by boaks** [comment]
I'm really not too familiar with that proxy.

> So, we would need a config-flag: Reverse-proxy: true or something. 

From RFC 7252 5.7.3:
> determine the destination (next hop) of a request from information in the request and information in their configuration.
 
It implements a "reverse-proxy" using the information from the provided URI in the request. I'm not sure, if there is a general "configuration" that could be used instead. May be it requires a use-case specific implementation. 

There is a `ProxyProperties`. With the first eye, it seems to be the right place. With the second, it's not used ;-(.

May be you can use `NetworkConfigDefaultHandler` (e.g. see [definition](https://github.com/eclipse/californium/blob/2.0.x/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/BenchmarkClient.java#L144) and [usage](https://github.com/eclipse/californium/blob/2.0.x/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/BenchmarkClient.java#L580) ). Please start all new properties with "PROXY_"  but don't include them into the `NetworkConfig.Keys`.

**Comment by boaks** [comment]
I'm still not sure, if you want a coap-http-reverse-proxy or a http-coap-reverse-proxy.
The first one may be derived from `ProxyHttpClientResource`. For a `Resource`, which catches up all child see [getChild](https://github.com/eclipse/californium/blob/2.0.x/demo-apps/cf-simplefile-server/src/main/java/org/eclipse/californium/examples/SimpleFileServer.java#L144).
The later would require to adjust/extend the `HttpStack` and/or `HttpServer`.

**Comment by boaks** [comment]
A coap-http-reverse-proxy is used in [gcloud-iot-coap-proxy](https://cloud.google.com/community/tutorials/cloud-iot-coap-proxy), [Source](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/cloud-iot-coap-proxy/proxy/src/main/java/com/agosto/iot/IotCoreForwardingResource.java)
