### ISSUE TITLE
[Proposal] Make multicast sender robust to network interface restart

### ISSUE THREAD

**Issue by aml2610** [eclipse/californium#930]
I realise it's a very very specific requirement, but would you be interested in having the ability to recover from network interface restarts?
I am proposing this for 2 reasons:
1. maybe it could help someone else too, it is a very simple solution I already have in place in my custom connector:
```
            /*
             * HACK: We need to make sure that even though the interface restarts, the system is able to recover
             * So before sending any multicast CoAP message we try to fetch the interface currently set on the socket
             *
             * If the interface went down and back up, we will get an exception with a message containing the text
             * "returned index to unrecognized interface" because the interface indexes don't match anymore (when an
             * interface is restarted it gets a new index)
             *
             * Therefore if we get that particular exception we (try to) fetch the interface again (assuming it is back
             * up this will work) and set it once again on the sender socket.
             *
             * Note: We only need this on the sending side.
             */
            try {
                socket.getInterface();
            } catch (final SocketException socketException) {
                final String exceptionMessage = socketException.getMessage();

                if (exceptionMessage.contains("returned index to unrecognized interface")) {
                    // set interface on socket again
                } else {
                    throw new MulticastException("Could not fetch multicast socket interface, reason: " + socketException.getMessage());
                }
            }
```
I do this in the sender's `work()` method.

2. The second reason is it would make my life easier as I probably wouldn't have to use my own connecter anymore.

Note: I would only add this to multicast connector's sender, but functionality could be replicated anywhere it's needed.

If you decide this could be useful, I am open to feedback if it can be improved in any way. As always, I am happy to contribute when I have time.

Thanks

**Comment by boaks** [comment]
Good idea. Three weeks ago I was playing with some raspberries and DHCP and got also aware, that there is a gap, if dynamic interfaces are used. Unfortunately, there are even more gaps, as your issue #920 or #736 .

Currently I'm very busy with the [DTLS CID](https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-04). The IETF IANA has started to assign the numbers, and I try to cleanup a improved android example to be used with the upcoming M15 (it will be just a wip and not part of that). 
One of the objectives to participate in this open source project was to promote to used CoAP/DTLS directly for cloud communication. Therefore my personal working focus is not the intranet usage. But, yes, if contribution are provided,I will appreciate that.

So don't hesitate to prepare a PR. The "easiest way" to get it accepted is to make it configurable :-). Then everybody can decide on it's own, if it's used or not.

**Comment by boaks** [comment]
I think, if someone will work on it, just add a comment and we open the issue again.
