### ISSUE TITLE
Race condition when processing new CLIENT_HELLO

### ISSUE THREAD

**Issue by AndreasHuber-CH** [eclipse/californium#931]
When doing a performance test we observe occasionally the following issue:
- The client repeats the CLIENT_HELLO after 1 second because it didn't get a response from the server.
- The server processes both CLIENT_HELLO simultanously (I still have to determine why this can happen...)

Then as you can see in the log below, two new Connections get allocated by Scandium for the same handshake one replacing the other. And Scandium responds with two SERVER_HELLO, SERVER_HELLO_DONE messages that contain two different values for the ServerRandom.

Later on (not in the logs below) the handshake fails with MAC verification errors because the client and server did apparently not use the ServerRandom value out of the two returned by Scandium.

```
12:19:59.973 org.eclipse.californium.scandium.DTLSConnector FINE: Processing new CLIENT_HELLO from peer [/10.3.12.25:61533]
12:19:59.973 org.eclipse.californium.scandium.dtls.Record FINE: Parsing message without a session
12:19:59.973 org.eclipse.californium.scandium.dtls.Record FINE: Parsing HANDSHAKE message plaintext [null]
12:19:59.973 org.eclipse.californium.scandium.dtls.HelloExtensions FINE: Peer included an unknown extension type code [13] in its Hello message
12:19:59.973 org.eclipse.californium.scandium.dtls.InMemoryConnectionStore FINE: connection: add CID=1127952BF1 (size 400)
12:19:59.973 org.eclipse.californium.scandium.dtls.InMemoryConnectionStore FINE: connection: CID=1127952BF1 - /10.3.12.25:61533 added!
12:19:59.973 org.eclipse.californium.scandium.DTLSConnector FINE: Received Handshake (22) record from peer [/10.3.12.25:61443]
12:19:59.973 org.eclipse.californium.scandium.DTLSConnector FINE: Processing new CLIENT_HELLO from peer [/10.3.12.25:61533]
12:19:59.973 org.eclipse.californium.scandium.dtls.Record FINE: Parsing message without a session
12:19:59.973 org.eclipse.californium.scandium.dtls.Record FINE: Parsing HANDSHAKE message plaintext [null]
12:19:59.973 org.eclipse.californium.scandium.dtls.HelloExtensions FINE: Peer included an unknown extension type code [13] in its Hello message
12:19:59.973 org.eclipse.californium.scandium.dtls.InMemoryConnectionStore FINE: connection: add CID=B1E211AF41 (size 401)
12:19:59.973 org.eclipse.californium.scandium.dtls.InMemoryConnectionStore FINE: connection: CID=B1E211AF41 - /10.3.12.25:61533 added! CID=1127952BF1 removed from address.
```

I used scandium-2.0.0-20190403.065916-681 in this test.

I think the issue is around the following lines in DTLSConnector, that can replace a connection by a new one if called for the same peer simultaneously:
connection.hasOngoingHandshakeStartedByClientHello() returns false for a very short time between the creation of the connection and the time the processClientHello() is executed in the executor that then sets the Handshaker in the connection
```
if (connection == null || !connection.hasOngoingHandshakeStartedByClientHello(clientHello)) {
    connections.setConnectionByAddress(new Connection(peerAddress, new SerialExecutor(getExecutorService())));
    if (!connectionStore.put(connections.getConnectionByAddress())) {
        return;
    }
}
```

**Comment by AndreasHuber-CH** [comment]
In one of the performance test runs I got the following stack trace.
```
Exception in thread "dtls-6" java.lang.NullPointerException
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.hasBeenStartedByClientHello(ServerHandshaker.java:947)
        at org.eclipse.californium.scandium.dtls.Connection.hasOngoingHandshakeStartedByClientHello(Connection.java:324)
        at org.eclipse.californium.scandium.DTLSConnector.processNewClientHello(DTLSConnector.java:1317)
        at org.eclipse.californium.scandium.DTLSConnector.access$700(DTLSConnector.java:205)
        at org.eclipse.californium.scandium.DTLSConnector$6.run(DTLSConnector.java:820)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I think this is caused by the same issue, but the NullPointerException occured only single time while main issue was reproduced a couple of times.

The ServerHandshaker.receivedClientHello() method signals first handshakeStarted() and then calls createServerHello() that sets the clientRandom field. So if ServerHandshaker.hasBeenStartedByClientHello() gets called in between there will be this NullPointerException.
There might also be a visibility issue as the clientRandom field is not volatile but ServerHandshaker.hasBeenStartedByClientHello() is called from multiple threads.

**Comment by boaks** [comment]
I'm on it. My available unit tests are currently running. I'm waiting for the outcome.
I hope I can propose a fix in a few minutes for your tests.

**Comment by boaks** [comment]
Either fetch the PR from this repo, or clone the https://github.com/bsinno/californium .
Hope the fix works :-).

**Comment by AndreasHuber-CH** [comment]
I'm on holidays for a few days and I can only test the fix next Wednesday. I looked at the code change for now.

I'm not sure the fix is correct.
Before, two client hellos from the same peer could both have a "null" connection which made that for both a new connection was created. This is adressed with the synchronized block that updates the connection if it is "null". But if this lookup finds another connection, the AvailableConnections instance must be updated or else it still contains the null connection it was created from and a NullPointerException will be thrown later in processClientHello().

Second, after leaving the synchronized block connection.hasOngoingHandshakeStartedByClientHello(clientHello) will return false, as the connection initially has no handshaker.
Then when the client hello is processed, first the handshaker is set at which point calling connection.hasOngoingHandshakeStartedByClientHello(clientHello) would throw a NullPointerException as the clientRandom of the handshaker is still null.
Then the clientRandom is set and connection.hasOngoingHandshakeStartedByClientHello(clientHello) correctly returns true.
So to me it looks like there is still a race condition around the hasOngoingHandshakeStartedByClientHello() method.

But now, when thinking about it, maybe a simpler solution inspired from your change might fix the issue:
```java
synchronized (connectionStore) {
    if (connection == null) {
        if (connectionStore.get(peerAddress) != null) {
            // Race condition occurred for the creation of a new connection for this peerAddress.
            // Dropping this CLIENT_HELLO as another CLIENT_HELLO is already beeing processed.
            return;
        }
    }
    if (connection == null || !connection.hasOngoingHandshakeStartedByClientHello(clientHello)) {
        connections.setConnectionByAddress(new Connection(peerAddress, new SerialExecutor(getExecutorService())));
        if (!connectionStore.put(connections.getConnectionByAddress())) {
            return;
        }
    }
}
```

This way the 2nd client hello is dropped and only one ServerHello message will be sent. The original code actually dropped the 1st handshake when the connection was updated, but both ClientHellos were processed which leads to two different ServerHellos.
What do you think of this fix?

I also realized what must have triggered the issue is that the server was receiving too many message and sometimes it took more than 1s before the 1st ClientHello was processed. The issue is probably partly caused by our PSK lookup that is not that cheap. (I saw multiple posts related to slow psk lookups #242 #878. I'll try changing the size of the thread pool to see what value works best and I'll check how the psk lookup can be improved)

**Comment by boaks** [comment]
I had already planned to introduce more tests, including performance tests, about the handshakes. But until now, I didn't find the time.  If you're back and able to test your proposal this would be the fastest solution for now :-).

**Comment by boaks** [comment]
Next try. 
I moved the "is started by" detection (based on the client random) into the connection itself and check it now in the synchronized section. But I still not able to spend that required time into tests ;-(.
Anyway, when your back, please test and give me your feedback.

**Comment by boaks** [comment]
I added some tests. Without the fix, the test fails with a high probability. With the fix, if succeeds with a high probability :-). I'm looking forward to your results.

**Comment by AndreasHuber-CH** [comment]
I could redo the performance tests. With your fix all handshakes are successful.
To be sure, we repeated the tests without the fix and multiple handshakes failed as before.
So the fix looks all fine to us.
Thanks a lot!

**Comment by boaks** [comment]
Merged, please close this issue.
