### ISSUE TITLE
some concerns about `ExecutorsUtil`

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#936]
Looking at #934, I looked at `ExecutorsUtil` and I have some concerns.

1.  the static block create ScheduledThreadPoolExecutor which can not be shutdown and which is shared by default.
2.  Experimental SplitScheduledThreadPoolExecutor seems to be activated by default, and can not be deactivated.

**Comment by boaks** [comment]
That mainly caused by the past, where stop or restart of components wasn't considered to be that important. My experience with the `DTLSConnector` and `UDPConnector` was,  that fixing (reported for pending messages  by callback) that is enormous time consuming. Therefore I didn't pay too much attention to stop and restarts and spent my time in other issues.

So, do you have only concerns about have that "general scheduler" always running? Or is there a current issue? 

The "experimental" stuff worked well for a couple of months. 
Or do you have issues except of the javadoc?

**Comment by sbernard31** [comment]
> So, do you have only concerns about have that "general scheduler" always running? Or is there a current issue?

The concerns here are not linked to any bug.
But having a "shared", "always running"  `ScheduledThreadPoolExecutor` sounds not so clean.

> The "experimental" stuff worked well for a couple of months.

There is 2 mode in the code but not easy way to switch from one to another... so any easy way to compare it.

**Comment by sbernard31** [comment]
About removing the static  `ScheduledThreadPoolExecutor` from `ExecutorsUtil`.

1) Do we really need a separated thread pool ? Why not just using the `CoapServer` one ?
2) If we really need it, I experiment some code about this. You could have a look at #937.

**Comment by boaks** [comment]
I have two office days left before my  vacation.  And the office days are filled with a lot of "none open source" stuff. So it's just the wrong time for deep discussion.

1.  (of your initial comment)
```
	/**
	 * Get general scheduled executor.
	 * 
	 * Intended to be used for rare executing timers (e.g. cleanup tasks).
	 * 
	 * @return scheduled executor service
	 */
	public static ScheduledThreadPoolExecutor getScheduledExecutor() {
		return scheduler;
	}
```

I chose that to not pass around the scheduled executor of the `CoapEndpoint`.  At least at the time,  when I tested that idea, the PRs have been large enough. And now my feeling is, that there are other issues with more priority.

2. 
```
SplitScheduledThreadPoolExecutor
```
My plan was to create a own special `ScheduledThreadPoolExecutor`once in the future. The most timers are intended to be prepared with some randomness and then they a tried to executed with the "time ordered heap" in precise time. One idea would be to add just the timers to a list for a period and so execute the job of period in mix with the direct jobs. That would speedup adding jobs and removing the head. But also here currently, there I flood with other tasks. But I will go to cleanup the javadoc.

**Comment by sbernard31** [comment]
>  At least at the time, when I tested that idea, the PRs have been large enough

If there is no other reason, replace usage of static ScheduledThreadPoolExecutor by the coapEndpoint/coapServer one could really simplify the code.

**Comment by boaks** [comment]
> If there is no other reason

I wasn't faced other reasons, but I also stopped that approach very early.
So you will see, if there are other reason.

> really simplify the code.

Did you look at my idea about fixing the unit test? 
FMPOV it's not about simplicity, it's more about what you expected and what you found.

**Comment by sbernard31** [comment]
I suspect I was not clear.

You're right that I don't expect that when I load a class, a new threadpool is created and could never be shutdown. This seems to be a bad practice to me. Maybe I'm wrong.

To fix this I would replace the static ThreadPoolExecutor by a dynamic reference.
But this implies there are 2 ScheduledExecutorService attributes in CoapServer. (like I do in #937)
This should not change the behavior so much.

But having 2 ScheduledExecutorService sounds maybe overkill, so I asked if there is any reason to use 2 differents executor instead of 1. When I talk about "simplify the code", this is about using 1 executor instead of 2 executors in the dynamic version. (not comparing the static vs dynamic one) 

> Did you look at my idea about fixing the unit test?

I'm not sure to see what you are talking about.

**Comment by boaks** [comment]
> Did you look at my idea about fixing the unit test?

> I'm not sure to see what you are talking about.

Commit b85f63f701467aef0d6 , you already included that into your PR #935 
My impression was, that the root cause of your concerns was the failing of the unit test introduced with that PR #935 and your work-around for that. 
So I wanted to point you to my proposal of fixing that thread-count stuff.

**Comment by sbernard31** [comment]
to test with benchmark.sh I need to launch server before ? any recommendation ?

**Comment by boaks** [comment]
I added some documentation about the required server to the "benchmark.sh" (see PR #949 ). The benchmark reports the overall time to the console. If that differs more than you expect or willing to accept, you may consider the logs with the times of the single tests.

The TCP stuff report sometimes more warnings, but that's not on my "priority list".

**Comment by sbernard31** [comment]
@boaks, this is not directly link to this issue but,

Did you try or do you think it's possible to use and share executors for receiving data (DTLS) and sending/receiving data (UDP) ?

This is the last issue to be able to simulate a lot of coap client/server without the issue of creating `n` thread by client.

**Comment by boaks** [comment]
Yes, we need to use the async nio. 
But, though it seems to be only for "mass tests" and not really for "production use", I soent my time in other stuff (as the connection ID, cluster, and currently the android demonstrator).

**Comment by sbernard31** [comment]
I think we can close this one.
Remaining question could be discussed in #969.
