### ISSUE TITLE
ServerInterfaceFactory is not public 

### ISSUE THREAD

**Issue by tcazabat** [eclipse/californium#940]
Hello,

I am using the OSGi project of the branch 2.0.x.

Actually the interface **ServerInterfaceFactory** is not public, I use my proper implementation of this interface, so I modified the visibility to public and it seems to work properly.

Is there any reason for this interface not to be public?

Thank you,
Thomas

**Comment by boaks** [comment]
I guess, the `package` `scope` is a mistake and should be `public` as for the other factories.
I will change it and and prepare a PR. We will see, if someone has an objection.

**Comment by tcazabat** [comment]
Thank you :)
