### ISSUE TITLE
OSGi manifest file for 2.0.0-X artifacts

### ISSUE THREAD

**Issue by tcazabat** [eclipse/californium#943]
Hello,

The artifacts available on Maven central don't have an OSGi manifest, they don't have the import and export packages. 

For example:
```
<dependency>
     <groupId>org.eclipse.californium</groupId>
     <artifactId>californium-osgi</artifactId>
     <version>2.0.0-M14</version>
     <type>bundle</type>
</dependency>
```
The manifest is:
```
Manifest-Version: 1.0
Implementation-Title: Californium (Cf) OSGi
Implementation-Version: 2.0.0-M14
Built-By: genie.californium
Implementation-Vendor-Id: org.eclipse.californium
Build-Jdk: 1.7.0_80
Created-By: Apache Maven 3.5.4
Implementation-URL: https://www.eclipse.org/californium/californium-os
 gi/
Implementation-Vendor: Eclipse Foundation

Name: about.html
SHA-256-Digest: 81ZpKnoltXghRZVpG1CBCNVIc7/vCnOrvOjYGI6HChg=

Name: org/eclipse/californium/osgi/ServerEndpointRegistry.class
SHA-256-Digest: ut47g0Tny05pE2W4/d1ujhIkNVWgzgYt1UBNy6SVLTw=

Name: org/eclipse/californium/osgi/EndpointFactory.class
SHA-256-Digest: epAg+Gj5BK8Tt1SrQga9cPUGTZFka+elqfOCGUyFtD4=

....
```
I get the source code and build it on my computer, the result is the same I don't have the OSGi part in the manifest.

To be able to get the right manifest file, I have commented in pom file this part: 
```	
<plugin>
	<artifactId>maven-assembly-plugin</artifactId>
	<configuration>
		<descriptors>
			<descriptor>enhanced-jar-with-licenses.xml</descriptor>
		</descriptors>
	</configuration>
</plugin>
```
I think it overrides the manifest generated by maven-bundle-plugin.
I don't know how to handle this, can you have a look?

Thomas

**Comment by boaks** [comment]
Would it be possible, to check the fix in the PR, if it works for you?

**Comment by tcazabat** [comment]
Hello,

Thank you for your help, it works fine for the OSGi bundle, but I think this also has to be done for user jar/bundle such as californium-core.

Thomas

**Comment by boaks** [comment]
> this also has to be done for user jar/bundle such as californium-core

Thanks! 
Next try, I update the PR. Please check, if all the modules required by you now have the proper manifest.

**Comment by tcazabat** [comment]
It seems to be perfect now.
Thank you.

**Comment by boaks** [comment]
If you find any new issues, don't hesitate to report them.
