### ISSUE TITLE
Race condition in SessionCache when DTLS sessions are resumed rapidly

### ISSUE THREAD

**Issue by AndreasHuber-CH** [eclipse/californium#948]
To test DTLS session resumption I sometimes use openssl with the "-reconnect" option.
In this mode openssl opens a DTLS connections, closes it and then repeates this five more times, trying to resume the initial DTLS connection.

While DTLSConnector handles this scenario correctly, the SessionCache that I implement in our application sometimes gets the put() and remove() calls not in the expected order.
Sometimes "SessionCache.put()" is called for the 5th DTLS and just afterwards "SessionCache.remove()" is called for "close_notify" of the  4th DTLS session.

As we use the SessionCache.remove() call also as way to detect when a DTLS connection is closed in order to clean-up some state (other than updating the 2nd level cache), this call actually clears some state that should be kept for the 5th DTLS connection that is still open.

I changed the code in processNewClientHello() to reuse the SerialExecutor of a resumed sessions if one is available instead of always creating a new SerialExecutor:
```java
SerialExecutor executor = null;
if (connections.getConnectionBySessionId() != null) {
    executor = connections.getConnectionBySessionId().getExecutor();
}
if (executor == null) {
    executor = new SerialExecutor(getExecutorService());
}
connection = new Connection(peerAddress, executor);
```

I didn't fully understand this race condition, but using the same SerialExecutor when a connection is resumed fixed the issue for me.

I think real world DTLS clients would not need this fix. The issue can only occur in a test scenario like when using openssl. But maybe its still worth fixing to save someone else from the same surprise when testing session resumption.

I discovered the issue with the latest 2.0.X snapshot.

**Comment by boaks** [comment]
Scandium discard the session state on "close_notify" instead of only discard the connection state. So, if "close_notify" is used, reconnect resumes a removed sessions. Luckily it seems to be only a test option :-). Even if that "close_notify"  processing may be fixed, I'm not sure, if "close_notify" makes too much sense in DTLS, especially reordering of records may cause irritation. But it's just a wild guess, I didn't spent time in investigating that.

**Comment by AndreasHuber-CH** [comment]
You‘re right. And actually our devices also would never resume a session if they send a close_notify in the first place. So if it’s only the openssl test option that behaves strangely, the issue needs not be fixed.
