### ISSUE TITLE
M14 hides DTLS handshake exceptions

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#955]
This concerns scandium-M14. I've noticed a behaviour change if a DTLS handshake fails due to an untrusted raw public key. M13 and earlier this would (correctly) throw a HandshakeException.
Since M14, instead a java.io.IOException is thrown with the message "address changed!"

To me it feels strange that the much more serious HandshakeException (which is still thrown and caught in DTLSConnector.proccessHandshakeRecord() ) is hidden behind the IOException thrown by Connection.updatePeerAddress().

Is this intentional?

**Comment by boaks** [comment]
Please check PR #953

**Comment by boaks** [comment]
@LudwigSeitz 

If your common the DTLS handshake, may be you can help us out:

https://github.com/eclipse/californium/pull/953#discussion_r285563832

@sbernard31 wants to clean up some more stuff. Unfortunately I'm currently too busy. 
So, if you can spend the time to discuss, if the "special processing of failed handshakes with established sessions" should be removed, that would really help! It will be easy to be removed, if you both think, that's the better way.

**Comment by boaks** [comment]
Fixed with the merge of PR #953.

If possible, please validate the fix.

**Comment by LudwigSeitz** [comment]
I can confirm the fix works. Note that the changes to the public API of PskStore didn't exactly make it easy to update towards M15. Is there really a case where the psk-identity is something else than a String?

**Comment by boaks** [comment]
> I can confirm the fix works. 

Thanks!

> Note that the changes to the public API of PskStore didn't exactly make it easy to update towards M15. 
> Is there really a case where the psk-identity is something else than a String?

See issue #902 and the discussions in PR #918 . It's not about the String, it's about the UTF-8 encoding. We decided to go for a single API and a support class [StringPskStore](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/pskstore/StringPskStore.java).  If possible, please try that and provide us your feedback.
