### ISSUE TITLE
Adding CoAP Publish Subscribe Model to Californium

### ISSUE THREAD

**Issue by wajd** [eclipse/californium#956]
My team and I have used your library to build a project for a university course that allows client-side use of Californium using the [IETS's RFC for Publish Subscribe](https://datatracker.ietf.org/doc/draft-ietf-core-coap-pubsub/). 
You can see the project [here](https://github.com/wajd/TeamMulticast-CoAP-PubSub). It has 2 simple classes and 1 alternative to WebLink, Topic.
We would like to contribute our features to this library as it uses a lot of Californium classes and we could not successfully mask them. 
Unfortunately we built it on Java 12 and used Californium 2.0.0-M14. We also did not write any test cases, so a lot of our 
Would you want this contribution? What should we do in order to make our contribution compliant with your guidelines? (besides forking californium 2.0.x, using Java 1.7, and adding test cases)

**Comment by boaks** [comment]
I did a very short check of the classes, currently I'm unfortunately can't spent more time on it.
I could compile them with java 1.7, so that seems to be not issue.
I'm not sure about the scope, so correct me:
- that are some classes, you would like to contribute to californium, that implements the client-side
- an example is missing?
- the server-side is missing?
- unit tests are missing?

FMPOV, some guide to show how to use it, would be very welcome. May be I just overseen it.

To contribute that, obey [contribution guide](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md), mainly the [ECA](http://www.eclipse.org/legal/ECA.php). 
Please add a license header to all java files and name all authors.
If other authors are also involved, we need their permission as well.

I would recommend to move the classes into a package, e.g. "org.eclipse.californium.pubsub.client".

**Comment by wajd** [comment]
The scope of the project was to build a client-side CoAP Publish Subscribe model library that allows developers to have easy access to functions that interact with a Coap PubSub broker. 

The networks lab intends to replace their current use of MQTT in their client side (databases, front-end clients, etc.) with CoAP publish-subscribe, and so we were tasked with building the IETS's RFC for pub-sub so that a front-end client such as a website or app could use it to read data from their sensor networks.

The Networks lab that commissioned the project already had a broker built, this is its [github](https://github.com/PethrusG/CoAP-PubSub-Broker) so we had no need to build the broker/server-side because they already had one.

It would take time to set up a working environment to use any of the functions as it requires the aforementioned broker to be running to communicate with it. 

it's great that it compiles with Java 1.7, we'd still need to use Californium 2.0.x rather than 2.0.0-M14 which doesn't let our classes compile, though we're willing to make the adjustments including packaging them. I've read the guide and I think I can follow most of it, but I don't believe we'll be able to write unit tests considering we're at the end of the project duration. 

Some extra context if desired: We originally started writing the project to be built on top of Californium without the developer using our library having to use Californium, but eventually realised that we'll need to use Californium classes such as CoapResponse and CoapHandler which is why we realised that perhaps we should contribute our classes to Californium instead. Does that make sense or is that not something Californium needs?

**Comment by boaks** [comment]
[About the your license](https://github.com/wajd/TeamMulticast-CoAP-PubSub#license)

Using EDLv1.0 is not "virulent". Just if your distribution contains such stuff, please mention that in your license that you use californium. But for your stuff, you can use what ever you want as license (until you want to contribute it to the californium project).

**Comment by boaks** [comment]
FMPOV, the missing unit-test are no issue. Also the complexer setup of the broker is OK for me.

> it's great that it compiles with Java 1.7, we'd still need to use Californium 2.0.x rather than 2.0.0-M14 which doesn't let our classes compile, though we're willing to make the adjustments including packaging them. 

I don't get it. Do you want to use java12 and 2.0.0-M14 doesn't work with that?
Currently only first test with java11 have been made. If java12 doesn't work with 2.0.0-M14, what kind of errors do occur?

**Comment by boaks** [comment]
> Does that make sense or is that not something Californium needs?

FMPOV, it makes sense. 
Even if I'm not sure, how good a "observe" from a device to a broker resource works. That may depend on your network environment, but if that is NATed, the notify from the server will hardly reach the device.

**Comment by wajd** [comment]
License:
I see, I went with GPLv3 at first but then switched to EDL just to be safe.

> Also the complexer setup of the broker is OK for me.    

That's great, I linked the [github of the broker](https://github.com/PethrusG/CoAP-PubSub-Broker), hopefully you can get it running. You might face some issues if not using a Linux distro I believe.

>I don't get it. Do you want to use java12 and 2.0.0-M14 doesn't work with that?
Currently only first test with java11 have been made. If java12 doesn't work with 2.0.0-M14, what kind of errors do occur?  

Sorry, I'm not making myself clear. 
We have no problem switching to any Java version as the decision was arbitrary. 
We used M14 just to avoid any new commits to Californium breaking our library, we can switch to 2.0.x with some adjustments and testing.

> Even if I'm not sure, how good a "observe" from a device to a broker resource works. That may depend on your network environment, but if that is NATed, the notify from the server will hardly reach the device.  

 We understand the issue with NATed networks environments, but the idea behind our project is to try to implement a client-side API of the CoAP PUB/SUB. At our university, Royal Institute of Technology, 
 The Networks Lab that commissioned us to build this has a sensor networks that are publishing data to a broker running on a server, and the ability to access the data using CoAP Pub/Sub from a front-end client such as an Android app or an API, was somewhat missing/lacking. 

The project we have built is of course incomplete and still needs further development (e.g. NATed networks). As such, one of the professors from the networks lab that commissioned this project encouraged us to submit our work into Californium since Californium does not have a direct way of using a Publish-Subscribe model yet as described by the [IETS's RFC](https://datatracker.ietf.org/doc/draft-ietf-core-coap-pubsub/), where it could be developed further.

We will go ahead and make the changes needed (except for the unit-tests) to submit a pull request of our classes into Californium.

**Comment by boaks** [comment]
Thanks for the detailed information!

So, please keep in mind:
- each source file requires a license header listing the authors
- if your not the only author, we need the permission of the other authors (may be just by e-mail).
- please move the classes into a package and modify your module to a californium submodule 
  (e.g cf-pubsub, setup/pom similar to cf-oscore.) 
- please copy also readme with the instructions.

The first contribution doesn't need to be perfect, especially, if your project is almost finished.
If you agree, I would like to mark it as "early experimental implementation".

**Comment by wajd** [comment]
Please go ahead and mark it as such. 
I will go ahead go through the contribution steps.

I do have one last question though; we have classes Topic and Converter that basically do the same thing, but using different approaches. We created both bc we couldn't determine what's the best approach, how do you want us to go about making that clear enough to any users/other contributors?

**Comment by boaks** [comment]
Your "README.md" contains it and would be sufficient for me.

**Comment by wajd** [comment]
I've created a pull request just now and the changes have been tested locally though I'm not sure if it affects Californium in some way that I could not see. https://github.com/eclipse/californium/pull/959

What email should I send the email with our team members permissions?

**Comment by boaks** [comment]
Just to me, achim.kraus@bosch-si.com 

Contributions with multiple authors requires a CQ (Contribution Questionare, review by the eclipse team). I create that after we checked your PR. It will take some days to pass that review, so just as information, the merge will take some time :-).

**Comment by boaks** [comment]
Merged.
