### ISSUE TITLE
cf-oscore pom file has dependency on californium-core and scandium

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#958]
This applies to 2.0.x branch M14.

The pom file of cf-oscore has a dependency on both californium-core and scandium. I don't think that should be that way (e.g. scandium has no dependency on californium-core in its pom file).

Update: The dependency on scandium is justified, cf-oscore uses CCMBlockCipher from scandium, but it seems the dependency on cf-core could be removed.

**Comment by boaks** [comment]
`public class OSCoreStack extends BaseCoapStack `

And your sure, that this extends of a cf-core class work without dependency?

**Comment by LudwigSeitz** [comment]
Ok, that makes sense, it's weird though since it compiles without cf-core, but not without scandium.

**Comment by boaks** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project cf-oscore: Compilation failure: Compilation failure: 
> [ERROR] /projects/californium/cf-oscore/src/main/java/org/eclipse/californium/oscore/HashMapCtxDB.java:[35,41] cannot find symbol
> [ERROR]   symbol:   class Token
> [ERROR]   location: package org.eclipse.californium.core.coap

I get errors, if I remove the cf-core dependency ...
