### ISSUE TITLE
DTLS1.2 connection ID draft version in Californium

### ISSUE THREAD

**Issue by Philago** [eclipse/californium#961]
Hello,

I have a quick question, what is exactly the version of the connection ID draft implemented in californium and merged in the 2.0.X branch ? https://github.com/eclipse/californium/issues/824 and so the version is draft-ietf-tls-dtls-connection-id-03 ? Or draft-ietf-tls-dtls-connection-id-04 and draft-ietf-tls-dtls-connection-id-05 have been implemented as well ?

Thank you

**Comment by boaks** [comment]
There is no large difference between the 03 and 05.
It's more the wording and extending the new MAC to the block and not only aead ciphers.
In my opinion, that was somehow clear also before.
The change in the wording is, that the negotiated cid is used. That is currently the same as in the record (as implemented in scandium), therefore I would have preferred to refer the record headers cid.

Or do you see any difference? Or do you have any trouble?
The code points are still not assigned, at least, I'm not aware of that.

**Comment by Philago** [comment]
Thank you for your answer.

It was my understanding as well that between 03 and 05 the differences were just in the wording

We'll be ready to test a DTLS1.2 client with connection ID soon, I was just checking if we are aligned or not on the version of the cid draft

**Comment by boaks** [comment]
> We'll be ready to test a DTLS1.2 client with connection ID soon, 

Great! Is it possible to know, which implementation you use on the client?

**Comment by boaks** [comment]
At least "temporary":
[early IANA assignment](https://mailarchive.ietf.org/arch/msg/tls/3wCyihI6Y7ZlciwcSDaQ322myYY)

> The following temporary assignments have been made for draft-ietf-tls-dtls-connection-id:
> 
> Registry: TLS ExtensionType Values
> Value: 53
> Extension Name: connection_id
> TLS 1.3: - 
> Recommended: Y
> 
> Registry: TLS ContentType Registry
> Value: 25
> Description: tls12_cid
> DTLS-OK: Y
> 
> J/C/S

**Comment by Philago** [comment]
Great !

**Comment by boaks** [comment]
Released with 2.0.0-M16.
Sandbox will be updated until tomorrow (18.07.2019).

**Comment by Philago** [comment]
yes it can be closed

**Comment by boaks** [comment]
Thanks!

Just to mention:
https://github.com/eclipse/californium/issues/653#issuecomment-511719316
and PR #1012 

It's not included in 2.0.0-M16, but I hope it will make it into the next milestone.
If you want to provide use feedback, it's highly welcome.
