### ISSUE TITLE
Do we need a secondary executor ? 

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#969]
## Some context
Since Californium 2.0.0-M13 (54b516d1f9bd66bdd72167ac9670ce233a2616a8), Californium are using 2 executors to execute its tasks. One main executor and another secondary one for rare executing tasks (like cleanup tasks).

Secondary executor was a static one. Since #937 it is now dynamic, meaning that it is not shared anymore and you can change it. (see for more detail about this changes #936)

## Keeping or removing secondary executor.
A remaining question is  : **Do we need a secondary executor ?**
The idea would be to just use only 1 executor for all tasks (even cleanup one)
But there is some concerns about performance issue.

Since #937, you can experiment this by using same executor as main and secondary one :
```java
CoapServer.setExecutors(mainExecutor, secondaryExecutor, boolean);
CoapClient.setExecutors(mainExecutor, secondaryExecutor, boolean);
```

Feedbacks about this are welcomed !

**Comment by sbernard31** [comment]
Here some results acquired using  `demo-apps/cf-extplugtest-client/benchmark.sh` on a debian stable : Intel® Core™ i7-2620M CPU @ 2.70GHz × 4 / 8GB RAM. 
(config -Xmx4g for server and -Xmx2g for client)


1. First test commit (8fee470e70) using 2 executors at server and client side.
2. Second test same commit with modification below to use only 1 executor.
```diff
--- a/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/BenchmarkClient.java
+++ b/demo-apps/cf-extplugtest-client/src/main/java/org/eclipse/californium/extplugtests/BenchmarkClient.java
@@ -645,8 +645,8 @@ public class BenchmarkClient {
                ScheduledExecutorService connectorExecutor = config.getInt(KEY_BENCHMARK_CLIENT_THREADS) == 0 ? executor : null;
                boolean secure = CoAP.isSecureScheme(uri.getScheme());
 
-               ScheduledThreadPoolExecutor secondaryExecutor = new ScheduledThreadPoolExecutor(2,
-                               new DaemonThreadFactory("CoapServer(secondary)#"));
+               ScheduledThreadPoolExecutor secondaryExecutor = (ScheduledThreadPoolExecutor
+) connectorExecutor;
 
                System.out.format("Create %d %s%sbenchmark clients, expect to send %d request overall to %s%n", clients,
                                noneStop ? "none-stop " : "", secure ? "secure " : "", overallRequests, uri);
diff --git a/demo-apps/cf-extplugtest-server/src/main/java/org/eclipse/californium/extplugtests/ExtendedTestServer.java b/demo-apps/cf-extplugtest-server/src/main/java/org/eclipse/californium/extplugtests/ExtendedTestServer.java
index 59955709..29dc601c 100644
--- a/demo-apps/cf-extplugtest-server/src/main/java/org/eclipse/californium/extplugtests/ExtendedTestServer.java
+++ b/demo-apps/cf-extplugtest-server/src/main/java/org/eclipse/californium/extplugtests/ExtendedTestServer.java
@@ -140,7 +140,7 @@ public class ExtendedTestServer extends AbstractTestServer {
                                        new NamedThreadFactory("CoapServer(main)#")); //$NON-NLS-1$
 
                        ExtendedTestServer server = new ExtendedTestServer(config, protocolConfig, noBenchmark);
-                       server.setExecutors(executor, ExecutorsUtil.newDefaultSecondaryScheduler("CoapServer(secondary)#"), false);
+                       server.setExecutors(executor,executor, false);

```
Results seems slightly the same.
 [statistics-8fee470e70-twoexecutor.log](https://github.com/eclipse/californium/files/3282316/statistics-8fee470e70-twoexecutor.log)
[statistics-8fee470e70-oneexecutor.log](https://github.com/eclipse/californium/files/3282318/statistics-8fee470e70-oneexecutor.log)

Maybe a notable difference on `coap://localhost:5783/reverse-observe?obs=25000&res=feed-NON&rlen=400 500 1 stop 1000 20 100`
501 requests in 108 ms, 4638 reqs/s (2 executors) 
501 requests in 146 ms, 3431 reqs/s (1 executor)

**Comment by boaks** [comment]
I guess, we can unpin it :-).

**Comment by sbernard31** [comment]
Yes as expected, this is not the most trendy topic ;)
