### ISSUE TITLE
a quection about fota

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/californium#973]
How to put a large file to a url block by block

request.setPayload(byte[100000]);
can it work?

**Comment by boaks** [comment]
PUT with a large file would require a very stable network.
GET may be adapted to not that stable networks, if a blockwise resume is implemented in the client.

In both cases, please adjust `MAX_RESOURCE_BODY_SIZE` to your requirements.

**Comment by sbernard31** [comment]
It sounds to be same question as https://github.com/eclipse/leshan/issues/698.

@boaks I written [a page](https://github.com/eclipse/leshan/wiki/Using-CoAP-Block-Wise-to-transfer-large-file-%3F) about that. Do not hesitate if you see any mistakes or missing points.

**Comment by bujingyun8** [comment]
> It sounds to be same question as [eclipse/leshan#698](https://github.com/eclipse/leshan/issues/698).
> 
> @boaks I written [a page](https://github.com/eclipse/leshan/wiki/Using-CoAP-Block-Wise-to-transfer-large-file-%3F) about that. Do not hesitate if you see any mistakes or missing points.

Thank you very much,we have impletment solution like "coap://","http://",but North American carrier VZW/TMO  certification requires the server MUST can send the package to client writing resource package(5/0/0)

**Comment by bujingyun8** [comment]
If I only want to meet the carrier's test, but not use in the production environment, is that what I have to write like this:

client.sendRequest(CON, GET, tok, ++mid).path(path).go();
		client.expectResponse(ACK, CONTENT, tok, mid).block2(0, true, 128).size2(300).payload(respPayload.substring(0, 128)).go();
		client.sendRequest(CON, GET, tok, ++mid).path(path).block2(1, false, 128).go();
		client.expectResponse(ACK, CONTENT, tok, mid).block2(1, true, 128).payload(respPayload.substring(128, 256)).go();
		client.sendRequest(CON, GET, tok, ++mid).path(path).block2(2, false, 128).go();
		client.expectResponse(ACK, CONTENT, tok, mid).block2(2, false,  128).payload(respPayload.substring(256,300)).go()

So I'm going to take the payload off to some blocks by myself?

**Comment by boaks** [comment]
AFAIK, just configure the `MAX_RESOURCE_BODY_SIZE` in "Californium.properties".
And configure the blocksize, if wanted, in `MAX_MESSAGE_SIZE` and `PREFERRED_BLOCK_SIZE`. Then you should be able to send the larger payload,

**Comment by bujingyun8** [comment]
> AFAIK, just configure the `MAX_RESOURCE_BODY_SIZE` in "Californium.properties".
> And configure the blocksize, if wanted, in `MAX_MESSAGE_SIZE` and `PREFERRED_BLOCK_SIZE`. Then you should be able to send the larger payload,

If I send the payload size is big than MAX_RESOURCE_BODY_SIZE or MAX_MESSAGE_SIZE ,what will happen.

**Comment by boaks** [comment]
> If I send the payload size is big than MAX_RESOURCE_BODY_SIZE or MAX_MESSAGE_SIZE

Which values do you want to use?
payload size
MAX_RESOURCE_BODY_SIZE
MAX_MESSAGE_SIZE
PREFERRED_BLOCK_SIZE

For the Californium.properties javadoc is available [NetworkConfig.Keys](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L80)

**Comment by boaks** [comment]
Feel free, to add new comments or open an new issue.
