### ISSUE TITLE
jenkins migration

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#979]
Eclipse is migrating its jenkins infrastructure. (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=547119)

This issue aims to share progress about this migration for californium project.

Migration are not smooth mainly because of this issue. (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=547626)

To fix it at short term, I will go for [Mikeal's workaround](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547626#c8).
([Pipeline](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547626#c14) seems also to have severals advantages and could allow us to workaround this issue too, This solution was started but is in [standby for now](https://github.com/eclipse/californium/pull/965))

Currently I workarounded the [2.0.x build](https://ci-staging.eclipse.org/californium/job/2.0.x/). If there is no objection, I will tried to do exactly the same for other builds on Monday.

There are [a lot of jobs](https://ci-staging.eclipse.org/californium/), I think we don't use all.
I plan to migrate jobs below and will deactivate others. Later we can decide what we keep and what we remove. Just let me now, if the list is not OK.
- 1.0.x
- 1.0.x-nightly
- 2.0.x
- 2.0.x-nightly
- actinium
- parent-deploy-eclipse
- parent-deploy-maven-central
- parent-release
- tools
- tools-release

I also tried to migrate 2.0.x-nightly but I get :
```
FATAL: Couldn?t find any executable in /opt/tools/apache-maven/latest
```
(I tried with different version of maven, same result)
This build was configured to be built on `centslave1`, when I remove this constraint, it sounds OK. I will go for it for now.

**Comment by boaks** [comment]
The jobs/projects:

- actinum
- tools
- tools-release

are using java 8, and so should not be affected by [Java 7 issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547626)

**Comment by boaks** [comment]
Executing jobs on `centslave1` was done to overcome the "failing test on cpu starvation". 
On the new jenkins I would just try to do it without specifying a slave/node.

**Comment by boaks** [comment]
`2.0.x` worked for merging PR #978 .
So, please go ahead with the other jobs, which requires java 7.

**Comment by sbernard31** [comment]
About actinium build.
It seems this is a continuous build of master branch, so I removed the maven `deploy -U` and only let "clean install". Does it make sense ?

**Comment by boaks** [comment]
Maybe you can copy the job and configure one as 
ci / sccm 5 min / clean install 
cd / sccm at night / clean deloy

**Comment by sbernard31** [comment]
You think that "clean deploy" will deploy jar at [eclipse](https://repo.eclipse.org/content/repositories/californium/org/eclipse/californium/actinium/) ?
I will test this.

**Comment by sbernard31** [comment]
Ok it seems to be deployed [here](https://repo.eclipse.org/content/repositories/californium-snapshots/org/eclipse/californium/actinium/2.0.0-SNAPSHOT/) and [there](https://repo.eclipse.org/content/repositories/californium/org/eclipse/californium/actinium/2.0.0-SNAPSHOT/).

Not sure to understand why :thinking: ... Anyway I will do what you propose **actinium** and **tools**.

**Comment by sbernard31** [comment]
I finished [the workarounding](https://ci-staging.eclipse.org/californium/).  
I didn't test release jobs, but I tested all other activated ones.  
I finally keep the californium-dry-run. (tell if you want to remove it)
I clean a bit some job descriptions.  
There is no description on `tools-release` because I'm not sure of what it is supposed to do. (I believe something like parent-release+parent-deploy-eclipse but for tools project) 
[This ssh issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=547119#c11) seems to be the last one.

Next step removing jobs ? Good candidate seems :   
- 1.1.x-nightly (v1.1 is dead,  right ?)
- all californium.core* (last build more than 3 years)
- element-connector (last build more than 3 years)
- scandium (last build more than 3 years)
- scandium-sonar (last build more than 3 years)
- parent-release-tagged( seems not used too, last build more than 3 years )

For master, master-nightly-sandbox, tools-release-tagged, debug and hudson-debug  I don't know if we need it.

I think we could maybe keep 1(or several job) about pipeline as example.

We should maybe rename some jobs too ?
1.0.x => californium-1.0.x
1.0.x-nightly => californium-1.0.x-nightly
2.0.x => californium-2.0.x
2.0.x-nightly => californium-2.0.x-nightly
parent-deploy-eclipse => californium-deploy-eclipse
parent-deploy-maven-central => californium-deploy-maven-central
parent-release => californium-release
tools-release => tools-release-deploy

**Comment by boaks** [comment]
I'm not sure, if master is "dead". Last time I asked to switch master to 2.0.x, @sophokles73 had objections.
May be it's now the time to inform the list of the eol of the master 1.1  and switch to 2.0.
But for now, I would keep the 1.1 jobs.

Renaming to californium-???
Not for me, I would just keep the names. I don't see the benefit in that rename.

**Comment by sbernard31** [comment]
> Not for me, I would just keep the names. I don't see the benefit in that rename.

When I see a job which is called : 1.0.x, I guess this is to build 1.0.x branch but I don't know from which project. The naming "parent-*" does not really make sense to me, what is parent ?
Renaming jobs like this will regroup visually all californium jobs together.

Renaming a job in jenkins is doable easily.
Do you see any issue about renaming it ?
You prefer the current name than my proposal or you just don't care ?

**Comment by sbernard31** [comment]
> May be it's now the time to inform the list of the eol of the master 1.1 and switch to 2.0.

:+1: 

> But for now, I would keep the 1.1 jobs.

Not sure to get why but OK.

**Comment by boaks** [comment]
:-) 
isn't it the jenkins for the project californium? I didn't name the jobs, but for me it was clear, what they do.
But, If you want, I have no objection. Only for right now, I would keep the names, until the release jobs could be tested. I tried the parent-release, but without success. so wait on instructions form eclipse how to proceed. But after it works, you may rename it.

**Comment by boaks** [comment]
> Not sure to get why but OK.

To wait for the answer. with the answer it may be removed.

**Comment by sbernard31** [comment]
> isn't it the jenkins for the project californium?

Yes, you're right but as there is several project in one. (californium, actinium, tools)
It confuses me. :D 

> But after it works, you may rename it.

Roger that.

> To wait for the answer. with the answer it may be removed.

Get it now. It sounds good !

**Comment by boaks** [comment]
`parent-release` and `parent-deploy-maven-central` are working in the meantime (I will update the poms in 1.0.x, 1.1.x, and 2.0.x tomorrow). So feel free to rename ...
For tools and actinum I will fix the jobs with the next Milestone.

**Comment by boaks** [comment]
The pom's are updated.

**Comment by boaks** [comment]
@sbernard31 

FMPOV, the jobs on the new jenkins are fine.

If you finish your finally checks, then please close the bugs on https://bugs.eclipse.org so that the old jenkins could be released/shutdown.

**Comment by sbernard31** [comment]
That's sounds good ! 
Just a last point, about [removing jobs](https://ci-staging.eclipse.org/californium/view/Trash/).

- **element-connector** : I pretty sure forgot to delete it, as you delete old one like it (californium-core and scandium).
- **master** : we don't need it for now, and if we need it again, it is simple to recreate it from `californium-2.0.x` job.
- **master-nightly-sandbox** :  this one I not so sure as I don't know how the sandbox is updated and which version is used for sandbox.
- **scandium-sonar** : sounds really old and seems to used deprecated build action : `"The SonarQube Post-build Action is deprecated"` (so not really a good example?)
- **parent-release-tagged** : I don't get it. is it redundant with other `release`/`deploy` job ?
- **tools-release-tagged** :  same as above.

I will close the eclipse bug.

**Comment by boaks** [comment]
The sandbox is update by me, manually, with a 2.0.x-SNAPSHOT I consider to be worth to be online.  It's more ore less every couple of weeks.

**Comment by boaks** [comment]
OK to remove:
parent-release-tagged
tools-release-tagged 

I would appreciate, if we keep them even if they are not working for now: 
master-nightly-sandbox
scandium-sonar 

Please keep it until there is a decision:
master

**Comment by sbernard31** [comment]
I do that.
OK to remove element-connector too ?

**Comment by boaks** [comment]
> OK to remove element-connector too ?

Yes, I just forgot it. I hope I can talk to @sophokles73 about the master/1.1 on Tuesday and if he agrees also on stop 1.1 and move master to 2.0.x, I will send a e-mail to the dev-list afterwards.

**Comment by sbernard31** [comment]
> The sandbox is update by me, manually, with a 2.0.x-SNAPSHOT I consider to be worth to be online. It's more ore less every couple of weeks.

Leshan use a script shell on the sandbox to update it automatically (It was written by Julien and updated a bit by me), I can share it if you want  ?.

The idea is to poll regulary for jar at https://hudson.eclipse.org/leshan/job/leshan/lastSuccessfulBuild/artifact/ with `wget -N` (https://www.gnu.org/software/wget/manual/wget.html#Time_002dStamping) and so restart sandbox only if we download new artifact.

**Comment by boaks** [comment]
The usage statistic uses a random initialized sha on the ip-addresses to count different hosts without keeping their ip-addresses. Regular updates would make that useless :-).

**Comment by boaks** [comment]
@sbernard31 
Any reason to keep this open?

**Comment by sbernard31** [comment]
Nope, I close it. :)
