### ISSUE TITLE
How to implement a single device single certificate？

### ISSUE THREAD

**Issue by xuzhiweiand** [eclipse/californium#985]
How to implement a single device single certificate ？

use interface  CertificateVerifier, how we can Identify Different device？

**Comment by boaks** [comment]
I'm not sure about the scope of the question.

To generate certificates for demonstration you may have a look at
[Demo Cedrtificates](https://github.com/eclipse/californium/blob/2.0.x/demo-certs/src/main/resources/create-keystores.sh#L33)

If the question is about validating/checking of client certificates (e.g. unique certificates per device), there are multiple options. Do you go for client certificates, which are signed by a "few CAs", or are they intended to be self-signed or use "many CAs"? Will the "additional" check be done "fast/synchronous" or is it more "undefined long"?.
   



`CertificateVerifier`: implement it

**Comment by xuzhiweiand** [comment]
Sorry, I didn't express it clearly. 
Device access with unique certificates per device
like device access by psk.  which we can use pskid to determine the psk of each device.  If it is a certificate, each device has a certificate on the server. How do we determine whether the client certificate is  consistent or match with this client certificate on server ?
is we only can set one certificate on the server ?

**Comment by boaks** [comment]
Certificates works very different as "identity/secret".

A peer uses it's certificate to proof it's identity, mainly by being signed by a CA (Certificate Authority) and providing a matching public key for it's (secret) private key. Therefore, in many use-cases, it's more about add that CA, used to sign your peer's certificate, to the trusts of the other peer.

The server has one certificate, with it's public key for it's private key, and the clients have there own certificates, also along with their public key and the private key (unique, don't reuse these keys!).
All are signed by a CA, and that CA is added to the trusts of the other peer.
With that, validating the certificate ensures, that all client certificates are signed by a trusted CA.

If you additionally want to check something, the best place depends on the answer to

> will the "additional" check be done "fast/synchronous" or is it more "undefined long"?
