### ISSUE TITLE
OSCORE: remove single instance pattern from HashMapCtxDB 

### ISSUE THREAD

**Issue by boaks** [eclipse/californium#990]
Add the `CoapThreadsRule` I got aware, that the current "single instance" approach for the `OSCoreObserveTest` has its drawbacks. I would prefer, if a `HashMapCtxDB` is passed into the `CoapStack` by the `OSCoreCoapStackFactory` and then stored in the `ObjectSecurityLayer`. The changes seems to be have limited scope. I would add also a `setHashMapCtxDB` to the    `OSCoreCoapStackFactory`, so that shared `HashMapCtxDB` will still be possible.

If agreed, I can implement that next week.

@rikard-sics
@LudwigSeitz 

Any opinion?

**Comment by rikard-sics** [comment]
So then the following:
`private final static HashMapCtxDB db = HashMapCtxDB.getInstance();`
Would instead become something like?
`private final static HashMapCtxDB db = ObjectSecurityLayer.getHashMapCtxDBInstance();`

And sharing the DB between a client and server like in the OSCoreObserveTest can be done with:
`OSCoreCoapStackFactor.setHashMapCtxDB(db);`
(I suppose sharing a DB like is done in the OSCoreObserveTest is not really needed, it was just for convenience to have one DB for the whole JUnit class. Normally the client and server would be two separate applications.)

The main point for me would be to keep it possible to get and modify the DB from different parts of an application in a convenient way. With your proposed changes one application would in general still have a single DB? And it would be accessible via some method both from the OSCORE code in Californium and inside code of an application using Californium?

Currently getting and modifying the DB is used in many places with:
`OSCoreCtxDB db = HashMapCtxDB.getInstance();`
So keeping it possible to do that somehow in a convenient way from different parts of the code would be good.

**Comment by boaks** [comment]
The complete static stuff around the `HashMapCtxDB` must be removed.
The `ObjectSecurityLayer` holds it's (optionally shared) `HashMapCtxDB` and use that for all operations and pass it into the other classes, which access the `HashMapCtxDB`.

**Comment by boaks** [comment]
> in many places

Hm, my feeling was, it's mainly the `ObjectSecurityLayer` and a few encrypt/decrypt functions.

**Comment by rikard-sics** [comment]
> The complete static stuff around the `HashMapCtxDB` must be removed.
> The `ObjectSecurityLayer` holds it's (optionally shared) `HashMapCtxDB` and use that for all operations and pass it into the other classes, which access the `HashMapCtxDB`.

I am trying to think about how this would affect the functionality. For instance currently I am also working on integrating OSCORE in Leshan. Let's say I am in the code of the Leshan server where a new LWM2M-client that will be using OSCORE has just been added in the web interface of the management server.

Currently I add the context doing the following steps (all in the code of the Leshan server):
1. Parse the settings the user has entered in the web interface.
2. Create an OSCORE context based on the settings entered.
3. Retrieve the context db using the following:
`OSCoreCtxDB db = HashMapCtxDB.getInstance();`
4. Add the newly created context in the context db. It is associated to the URI the user entered in the web interface.

With the proposed changes how would I go about getting the context db from an arbitrary position in the Californium code or code of an application?

> Hm, my feeling was, it's mainly the `ObjectSecurityLayer` and a few encrypt/decrypt functions.

From a search it seems to be done in the following files:
```
main/java/org/eclipse/californium/oscore/ObjectSecurityLayer.java
main/java/org/eclipse/californium/oscore/ResponseDecryptor.java
main/java/org/eclipse/californium/oscore/RequestDecryptor.java
main/java/org/eclipse/californium/oscore/ContextRederivation.java
main/java/org/eclipse/californium/oscore/OSCoreCtx.java
main/java/org/eclipse/californium/oscore/HashMapCtxDB.java
test/java/org/eclipse/californium/oscore/OSCoreTest.java
test/java/org/eclipse/californium/oscore/HelloWorldClient.java
test/java/org/eclipse/californium/oscore/ContextRederivationTest.java
test/java/org/eclipse/californium/oscore/HelloWorldServer.java
test/java/org/eclipse/californium/oscore/OSCoreServerClientTest.java
test/java/org/eclipse/californium/oscore/OSCoreObserveTest.java
test/java/org/eclipse/californium/oscore/DecryptorTest.java
test/java/org/eclipse/californium/oscore/HashMapCtxDBTest.java
```

**Comment by boaks** [comment]
Ahhh, I checked the implementation, not the tests.
For me it looks like the test access the db to setup the context. That would be pretty much the same, expect, that they create the db and pass it to the factory just before creating the endpoint.

**Comment by rikard-sics** [comment]
> Ahhh, I checked the implementation, not the tests.
> For me it looks like the test access the db to setup the context. That would be pretty much the same, expect, that they create the db and pass it to the factory just before creating the endpoint.

Alright so an application could create the context db and make sure to set it in the OSCoreCoapStackFactory before creating the first Endpoint (or at least before sending/receiving the first OSCORE message)? Or perhaps it could be set when running OSCoreCoapStackFactory.useAsDefault() which needs to be run?

So letting the application create and set the db could be fine. But then how will it be retrieved in the OSCORE code for instance in RequestDecryptor.java that needs it?
https://github.com/eclipse/californium/blob/7b45b3c47a995ffcf0b68489e54f30bc9ac67cfd/cf-oscore/src/main/java/org/eclipse/californium/oscore/RequestDecryptor.java

What is the scope of an OSCoreCoapStackFactory? For instance then in the OSCoreObserveTest the client will have one and the server a separate one?

**Comment by boaks** [comment]
That's called from `ObjectSecurityLayer`. So, with a clean up of the `static` there as well, it seems to be straight forward to me.

**Comment by boaks** [comment]
The `OSCoreCoapStackFactory` would be extended with a setter, which must be called before a endpoint is created and a new db should be used. "Not that brilliant" but it works and is better than a singleton.

**Comment by rikard-sics** [comment]
> The `OSCoreCoapStackFactory` would be extended with a setter, which must be called before a endpoint is created and a new db should be used. "Not that brilliant" but it works and is better than a singleton.

> That's called from `ObjectSecurityLayer`. So, with a clean up of the `static` there as well, it seems to be straight forward to me.

Yes, if you feel it is a better design let us change it accordingly. Then it would be the responsibility of the application to create a context db and provide it to OSCORE. The context db can then be provided from the ObjectSecurityLayer as argument to other methods.

**Comment by LudwigSeitz** [comment]
My IETF-ACE application uses that in several places. Most of them would be ok since they are directly related to creating a CoAP client or server, thus having access to the StackFactory, but I have an important use-case where I need to access this from the application layer. How would that be realized?

**Comment by boaks** [comment]
Your application may use a singleton to maintain a single db, which is then passed into the factory.
If that's OK for your application, that will be a valid application solution. But for a library I would prefer a little more flexibility (even if that is just triggered by the unit tests.)

**Comment by boaks** [comment]
I prepared a first PR #1000 to see, if it is "usable" for your requirements.

**Comment by boaks** [comment]
PR merged.

**Comment by LudwigSeitz** [comment]
I will be able to test this when PR#1002 is merged as well.
