### ISSUE TITLE
Wanted to know how server will send blockwise response in piggyback

### ISSUE THREAD

**Issue by phani50** [eclipse/californium#992]
Hi Team,

I wanted to how to enable or send blockwise response from server to device in piggybacked.

The requirement is like below,

when device send CON, based on the size of response from backend my server should decide to send response as normal or blockwise. as of the i am using below code to send response ,

byte[] payload = //came from backend ...
Response coapResponse = new Response(ResponseCode.CHANGED);      coapResponse.getOptions().setContentFormat(IgwConstant.COAP_OPTIONAL_CONTENT_FORMAT);
coapResponse.setPayload(payload);
exchange.respond(coapResponse);

How can i make use of above to support blockwise response as well based on payload size.

for example if payload size is >= 1024 i need to send as blockwise response.

**Comment by boaks** [comment]
Set the "Californium.properties" accordingly:

MAX_RESOURCE_BODY_SIZE
MAX_MESSAGE_SIZE
PREFERRED_BLOCK_SIZE

(see javadoc in [NetworkConfig.Keys](https://github.com/eclipse/californium/blob/2.0.x/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfig.java#L140)

That should do the job.

**Comment by phani50** [comment]
is it possible to change max_message_size and prffered_block_size dynamically? because we have clients with varying MTU.

**Comment by boaks** [comment]
No currently there is no way to adjust these values dynamically per client.

RFC7959 has a "blocksize negotiation" include. Maybe you can check that, if it works for you.
See [RFC7959 examples](https://tools.ietf.org/html/rfc7959#page-19) e.g. `Figure 4`

Do you use DTLS? Then it may get more dirty. Without DTLS you may see in the coap-header of an incomplete message, that the blocksize is too large. With DTLS, this cut's off the MAC and the record must be dropped without decrypting the coap-header ;-(. Therefore the negotiation only works, if larger messages are generally OK, but may be less efficient than smaller ones.
